* Fears Rise of Thargoid Expansion

/27 Aug 3308/

*Pilots’ Federation ALERT* 

Ships travelling in the vicinity of HIP 22460 have reported so-called ‘hyperdiction’ incidents at increased distances from the Thargoid-controlled system. 

Pilots have filed similar reports about encounters in V0402 Aurigae, HR 1490, Synuefe SA-C b33-2 and several other systems. The number of ships being pulled from hyperspace and scanned by Thargoid vessels – or in some cases attacked immediately - has substantially increased.  

Admiral Maxton Price issued a statement on behalf of the Federal Navy: 

“Our initial analysis suggested that, having eliminated the Proteus Wave, the Thargoids would extend their forces out from the HIP 22460 system. Unfortunately, those predictions have proved correct. New data indicates that they are using that system as a base of operations to expand into the sector.” 

“Historically, hyperdiction events did not always result in conflict. But the recent spate of direct attacks proves that the Thargoids’ aggression toward humanity has reached new levels. All civilian traffic should exercise extreme caution while travelling within the Pleiades region.” 

Professor Alba Tesreau published an alternative viewpoint: 

“What we interpret as a military expansion may instead be an attempt to reclaim territory. The Pleiades Nebula has long had a considerable Thargoid presence, with many planets containing barnacle sites where their vessels harvest meta-alloys. It seems logical that they would use their increased numbers in HIP 22460 to reassert their claim on the region.”