* Understanding the ‘Thargoid Roar’

/10 Nov 3308/

Professor Alba Tesreau, Professor Ishmael Palin and Ram Tah have released a joint statement regarding the alien sound heard at HIP 22460. 

“There has been much speculation about the mysterious noise that was recorded following the Battle of HIP 22460, which is clearly of Thargoid origin. Thanks to the help of Seo Jin-ae, formerly known as Subject D-2, we have started to comprehend some of its meaning.” 

“What was audible to humans was only part of a complex multi-frequency transmission, amplified by the energy surging through the Thargoid surface site which housed the Proteus Wave weapon. Its specifics remain indecipherable for the moment, but certain aspects were isolated with the aid of Ms Seo, whose unique neural implants were designed to interface with Thargoid technology.”  

“She believes there is a ‘call and response’ element, as if the signal was a reply to the Thargoid forces in HIP 22460. This was interwoven with a sense of acknowledgement and focus, which Ms Seo described as: ‘We see them. We are coming.’” 

“Further insights from Ms Seo plus advanced audio analysis leads us to conclude that the sound emanated from a single Thargoid entity, and was transmitted with more power than anything previously encountered.” 

“Popular theory has linked this ‘Thargoid roar’ to the anomalies known as rogue signal sources, which are currently converging on the core systems. Seo Jin-ae appears convinced that, whatever their ultimate motive may be, they have been deployed by the Thargoids as a direct response to Salvation’s Proteus Wave weapon.” 

“We solemnly predict that the Second Thargoid War is about to enter a new phase, and humanity may not yet be prepared to withstand it.”