* Marlinists Hold Public Referendum

/05 Apr 3308/

The population of the Marlinist Colonies will vote to accept or decline the offer to become an Imperial protectorate. 

Emperor Arissa Lavigny-Duval’s proposal aims to build links between the independent colony systems and the Empire, from where the Marlinists originally fled as political refugees in 3306. 

The Marlin Standard ran an editorial summarising the situation: 

“Should the Marlinist Colonies remain an isolated republican society, or should we move beneath the Empire’s protective wing? It’s a question that most of us never expected to be asked.” 

“Many expressed fierce anger that Emperor Arissa has dared to ask for our allegiance. In her desperation to hunt down the NMLA she persecuted all believers in Marlinism, arresting thousands and displacing millions of her own citizens. Can we now trust her to welcome us back?” 

“Others are concerned that the Marlinist Colonies remain vulnerable, claiming that becoming a satellite nation of the Empire would provide military defences as well as economic boosts. And for those still holding on to their past lives, the attraction of reconnecting with friends and family in the Empire is strong.” 

“Whatever the outcome, First Minister Octavia Volkov’s swift decision to put this issue to a referendum is a splendid example of Marlinism in action. Votes are already being cast, and the result will be revealed at the end of this week.”