* Unexplained ‘Flare’ Detected in Deep Space

/05 Sep 3308/

*Pilots’ Federation ALERT* 

Reports from independent explorers indicate that an unusual visual phenomenon has appeared in deep space. 

A distant point of light, described as a reddish-orange flare with faint radial patterns, has been observed close to the Barnard's Loop nebula. It is thought to have appeared only recently. Universal Cartographics has confirmed that the location of this ‘flare’ does not match any previously catalogued stellar body or star. 

Early attempts to verify these reports have noted a strange response when the same region of space is observed through a full spectrum system scanner (FSS). No definitive target can be isolated, but claims of a faint background noise generated by FSS audio converters have been asserted. 

Commander Eva Llewellyn, speaking to Vox Galactica, remarked: 

“I’m used to the FSS making all sorts of strange noises, but listening to this thing – comet, solar flare, whatever it is – gives me goosebumps. Something feels off, all right. The scanner tells me there’s nothing there, nothing to focus on. Can’t say I agree. Still, smarter people than me will figure out the truth of it all, I guess.” 

At present, it is unknown if this is a naturally occurring stellar event. Pilots are attempting to gather more data, but as yet no authority or scientific body has provided any official analysis of the phenomenon.