* Rackham Achieves Trillionaire Status

/09 May 3308/

The personal fortune of entrepreneur Zachary Rackham has now surpassed one trillion credits, due to a new corporate acquisition. 

A report in The Tau Ceti Journal highlighted the achievement: 

“Rackham Capital Investments now officially owns the company Kavanagh Spaceframes Ltd, which constructs Orbis starports. The business deal had been in the pipeline for years with little sign of progress, but was unexpectedly agreed by both parties in the last few days.” 

“Susannah Haynes, CEO of the now-renamed Rackham Spaceframes, welcomed the arrangement. She remarked that ‘improved financial stability can only benefit our efficiency at manufacturing orbital habitats’.” 

“Analysts estimate that the total value of Mr Rackham’s estate is now approximately 1,012,000,000,000 credits. This makes him one of a handful of private citizens in the Federation who can claim to be trillionaires.” 

The Federal Times featured a response from the journalist Bryanna Blanco: 

“I cannot question the legality of the Kavanagh Spaceframes purchase. But the timing is suspicious, following Rackham’s recent self-hype about running for president. Whatever he did to push this deal through, the publicity will be worth it. Political supporters and corporate investors will surely flock to his side now that he has become the Federal equivalent of royalty.”