* Arissa Addresses the Empire

/26 Jan 3308/

The Imperial Senate has shared a personal message from Emperor Arissa Lavigny-Duval, who has been in a secure location for nearly a year. 

The brief statement was broadcast on all public channels: 

“Citizens of the Empire, be assured that your Emperor is alive and well. I regret that my temporary seclusion has lasted for so long, but I have remained in contact with the Senate during this time.” 

“I was advised to depart from Capitol when Imperial Intelligence warned me about a legitimate NMLA assassination attempt, and of Marlinist sympathisers within the highest levels of our government. Once the work of this loyal agency is complete, I will continue my work in leading us toward a prosperous future.” 

Eye on Achenar reported that this address was “welcomed by a relieved Empire”, adding that it was vital to “root out all Marlinist traitors”. The Imperial Herald noted that the Emperor seemed to absolve Imperial Intelligence of the allegations that it was secretly enabling the NMLA. 

However, a caution was sounded by Princess Aisling Duval: 

“Arissa has communicated with the Senate in the same manner for months, so this changes nothing. Only a public appearance will alleviate my concerns regarding her wellbeing. I would be delighted to host a suitable event if she will accept my invitation to attend in person.”