* Marlinists Reject Emperor’s Offer

/08 Apr 3308/

A public referendum in the Marlinist Colonies has resulted in the majority voting to remain fully independent from the Empire. 

Emperor Arissa Lavigny-Duval had proposed to make the colony systems an Imperial protectorate in return for Marlinist allegiance to the Imperial throne. This would have permitted an autonomous government while creating many civil and military links. 

First Minister Octavia Volkov announced the referendum’s results in the Marlinist Parliament: 

“Our people have given us a clear mandate: the colonies stand alone. In accordance with the key principles of Marlinism, we reject monarchy rule in favour of republican governance and direct representation.” 

“Most of us are still haunted by the trauma of becoming refugees in 3306, when millions of innocent Marlinists were accused of supporting terrorist acts. We fled from an Empire that had become intolerant and abusive. This cannot be so easily forgotten.” 

“Nevertheless, we recognise that approximately a quarter of our population voted to accept the Emperor’s proposal. The ties to our homelands remain strong, and we still share much culture and history with the Empire. But the will of the masses is evident.” 

“I offer my thanks to Her Majesty for extending this offer, and call upon her to recognise and respect the decision of the Marlinist Colonies.”