* A Retrospective of 3308 (Part Two)

/30 Dec 3308/

Sima Kalhana continues her review of the most significant historical events that occurred during the past year. 

“In May 3308, the Thargoid invasions of the Didio, Novas and Sosong systems were completely repelled by the use of Salvation’s unique superweapons. This convinced the Alliance, Empire and Federation to support Azimuth Biotech in developing this Guardian-based technology, with Salvation claiming that he could end the Thargoid threat forever.” 

“Elsewhere that month, the Kumo Crew syndicate faced civil war as pirate rebels tried to replace Archon Delaine. Eventually his loyal forces triumphed, with the Blue Viper Club dredger clan fleeing his reprisals. And in the Federation, trillionaire entrepreneur Zachary Rackham announced his presidential candidacy for the 3309 election.” 

“June saw the Golconda generation ship repaired and updated by the Artificers Clan. This provided the majority of its original inhabitants, descended from Earth colonists, the opportunity to resume their spacefaring lifestyle.” 

“The news around this time was dominated by Salvation, particularly when he rebranded Taurus Mining Ventures as Azimuth Biotech. The scientist, once named Dr Caleb Wycherley, admitted that the corporation had evolved out of the notorious Azimuth Biochemicals. But Allied, Federal and Imperial leaders chose to ignore this, having pinned their anti-xeno strategy on Salvation’s superweapon technology.” 

“HIP 22460 was the system chosen to construct the Proteus Wave. This interfaced Guardian technology with a Thargoid ground settlement, and was designed to deliberately attract the Thargoids before wiping them out. During July and August, upgraded capital ships along with independent pilots defended Azimuth Biotech’s operation from swarms of Thargoid vessels.” 

“After weeks of intense combat and delivering vital supplies, the Proteus Wave was activated on 9th August. Initially it seemed successful, rendering the Thargoids powerless, but an unexpected second energy pulse from the planetary site had the same effect on all human ships. The resulting massacre saw the Thargoids take control of the HIP 22460 system, establishing a permanent presence.” 

“Salvation was dead. Azimuth Biotech’s plans had failed. The superpowers were in retreat. And speculation grew about an unearthly alien screech heard in HIP 22460, dubbed the ‘Thargoid roar’.”