* Medicines Delivered for Starport Bombing Survivors

/25 Mar 3307/

*Pilots Federation ALERT* 

Safeguard Interstellar has successfully received medical supplies for civilians wounded during the NMLA terrorist attack. 

The bombing of nine starports across the Alliance, Empire and Federation left huge numbers of people injured, some with caustic burns due to Thargoid enzymes deployed by the explosives. 

Noel Beaumont, the aid organisation’s CEO, announced: 

“We are immensely grateful to all pilots who brought shipments of basic medicines and advanced medicines. These have been transported directly to the relevant systems, where they will be used to ease the suffering of several hundred thousand civilians.” 

Safeguard Interstellar confirmed that its partner factions have made rewards available at the three systems used as staging areas for deliveries.  

Pilots can collect from the Perez Ring Brewery at Krylov Ring in the He Bo system, Lavigny's Legion at Mackenzie Relay in the Cemiess system, and the Duamta Gold Creative Corp at Davis Terminal in the Duamta system. 

Over the past two weeks, emergency services have been concentrated on the nine damaged starports in the Achenar, Alioth, Eotienses, Gateway, Kamadhenu, Lave, Nanomam, Rhea and Sol systems. All survivors have been accounted for and repairs are largely completed, mainly due to dedicated support by members of the Pilots Federation.