* Marlinist Colonies Receive Emergency Food Supplies

/21 Jan 3307/

*Pilots Federation ALERT* 

Large amounts of food commodities have been delivered to the Marlinist Colonies. 

Multiple shipments of animal meat, fish, fruit and vegetables, and grain were transported to Stillman Hub. Messages of gratitude were broadcast from all the Marlinist factions, which have distributed these vital supplies across the eight colony systems. 

The Free Marlinists of Carinae also issued bounty vouchers for wanted ships, in order to protect the deliveries. Contributing pilots can now collect their rewards from Stillman Hub in the HIP 22550 system. 

In related news, the first Marlinist Parliament has been democratically elected. The respected community leader Dr Jenna Fairfax was chosen by a majority public vote to be First Minister. In a public address, she said: 

“This path was not chosen by us, but our people have turned Marlin Duval’s ideology into a functioning republican society. Now that we are fully independent members of the galactic community, we can repay those who aided our survival by offering discounts on commodities and establishing regular trading.”