* Rare Goods Received for Political Delegates

/25 Feb 3307/

*Pilots Federation ALERT* 

A wide range of luxurious food and drink for the Galactic Summit has been delivered to the Sirius Corporation. 

Orders were placed for Eden Apples Of Aerial, Ethgreze Tea Buds, Gerasian Gueuze Beer, Giant Irukama Snails, Goman Yaupon Coffee, Karsuki Locusts and Lavian Brandy. Large quantities of these rare items were shipped to Ashby City in the Luyten’s Star system. 

The consumables will be ferried to the nearby Sirius system, where the diplomatic conference will take place. This initiative was considered a priority, since some delegates only agreed to attend if their requests for these rarities were met. 

CEO Li Yong-Rui has expressed his personal thanks to all pilots who delivered the rare goods, who can now collect their payment at Ashby City in the Luyten’s Star system. 

Sirius Corporation has been organising the Galactic Summit for the past month, which has involved increased freight runs into its home system as well as heightened security. Preparations are now complete, and the first ambassadors from the Alliance, Empire and Federation are on their way.