* Anti-NMLA Intelligence Unit Formed

/17 Mar 3307/

The Alliance, Empire and Federation have created a centralised agency dedicated to investigating and eliminating the NMLA paramilitary group. 

The new Affiliated Counter-Terrorism unit (ACT) is a direct result of the Cornelius-Lasky Convention, which was signed at the Galactic Summit. 

This treaty requires the superpowers to share information on any large-scale threats to civilian populations. With a combined death toll rising over half a million, the recent starport bombings have obtained such status. 

ACT will be jointly led by the veterans of the tri-superpower taskforce that defeated the League of Reparation in 3304: Captain Niamh Seutonia of the Imperial Internal Security Service, Inspector Mara Klatt of Alliance Interpol, and Senior Agent Tanya Ramirez of the Federal Intelligence Agency. 

Captain Seutonia gave a brief statement: 

“ACT is an independent organisation dedicated to bringing the NMLA to justice. We will draw resources from Alliance, Empire and Federation security forces and elsewhere.” 

“However, we foresee the need for even larger numbers of dedicated personnel. Therefore, we have contacted the Pilots Federation for permission to invite independent pilots to gather information for us when necessary.” 

Pilots are advised that civilians still require transportation from damaged starports in the Achenar, Alioth, Eotienses, Gateway, Kamadhenu, Lave, Nanomam, Rhea and Sol systems.