* Kumo Crew Campaign Starts Drug Production

/15 Jul 3307/

*Pilots Federation ALERT* 

The Kumo Crew syndicate has procured enough materials to introduce a new product to the market. 

The drug originated with the Blue Viper Club, a piratical travelling community whose dredger is currently in the vicinity of Kumo City station.  

It was confirmed that enough shipments of agronomic treatment, liquid oxygen and performance enhancers were received to enable immediate mass production. Pilots also fought to protect haulage vessels from pirate ships, suspected to be Kumo Crew rivals. 

The Interstellar Health Organisation has obtained a product sample and confirmed that, despite the name ‘helix’, it is a new variant of the recreational drug onionhead. As such, the product will be legally classified as onionhead gamma strain when it appears on the market. 

Despite claims of medicinal and psychological benefits, it is likely to be illegal in most systems. President Zachary Hudson, Princess Aisling Duval and several other political heavyweights have expressed outrage at the open manner by which its ingredients were procured. 

Archon Delaine, warlord of the Kumo Crew, responded: 

“Every system government generates revenue from the pharmaceutical trade, so the holier-than-thou attitude from these hypocrites turns my stomach. Helix brings happiness, and provides income for my people. I make no apologies!” 

Rewards for pilots who contributed to this campaign are now available at Kumo City in the Pegasi Sector PN-T C3-14 system.