* A Fractured Federation

/23 Aug 3307/

Shadow President Felicia Winters has claimed that further systems declaring independence could severely damage the Federation. 

Her statement was in response to the conflict in the Kuwembaa system, which resulted in more Federal factions seceding from the superpower. Dozens of others are now openly considering breaking away and becoming independent. 

Addressing Congress, Shadow President Winters said: 

“We now face the possibility of large-scale rebellion, as more citizens reject intrusion into their private lives. Unless these authoritarian surveillance laws are repealed, we risk many more factions and allies losing their trust in any Federal government.” 

Vice President Jerome Archer responded: 

“The Proactive Detection Bureau provides increased security and decreased crime levels for all Federal systems. I deeply regret that a few have rejected its benefits, but we must concentrate on the bigger picture.” 

The Sovereign newsfeed described how the newly seceded systems are celebrating freedom from government scrutiny. It claims that up to fifty other factions have expressed interest in becoming independent. 

However, The Federal Times reported that more pragmatic leaders have voiced concerns that they are now more vulnerable. There are particular fears of retaliation by pro-Federation groups or attacks from opportunistic hostile forces.