* Date Set for Trial of Fleet Admiral Vincent

/11 Jan 3307/

Fleet Admiral Lucas Vincent of the Federal Navy will stand trial on the 25th of January, charged with conspiracy to commit murder and treason. 

The Federal Attorney’s Office has successfully obtained a grand jury indictment against Fleet Admiral Vincent. He is accused of arranging the sabotage of presidential vessel Starship One in 3301, to assassinate then-President Jasmina Halsey. Although she was later recovered alive, hundreds died when the ship was destroyed in flight. 

These charges were brought following the trial of Rory Webster, a naval technician who was implicated in the failure of Starship One’s hyperdrive system. Mr Webster confessed his involvement, but offered a plea bargain by providing evidence that he was following clandestine orders from Vincent. 

The subsequent arrest caused repercussions in military and political circles. President Zachary Hudson’s long-term association with Vincent resulted in Republican congressmen losing confidence in his leadership, and increased the Liberal Party’s popularity. 

As a naval chief of staff, Fleet Admiral Vincent is the highest ranking Federal military officer to ever stand trial. Media interest remains intense, with much public speculation about corruption among the Federation’s highest echelons. 

The trial will take place at the Federal High Court in Olympus Village on Mars, and is expected to last several weeks.