* Neo-Marlinists Seek Sanctuary at Marlinist Colonies

/16 Apr 3307/

Survivors from the Neo-Marlinist Order of Mudhrid have arrived in the Marlinist Colonies, requesting political asylum from the Empire. 

The faction was recently defeated by Imperial forces in the Mudhrid system, after an ACT investigation confirmed that it provided logistical support for the NMLA attacks on starports.  

Landgrave Delacroix and his loyalists fled aboard the Steel Majesty megaship to the Hyades Sector RO-P b6-2 system, which is controlled by the Marlinism Reformation Party. Minister Aaron Whyte, its elected leader, announced: 

“Not every individual within the Neo-Marlinist Order of Mudhrid is an NMLA activist. We have the right to offer asylum to protect innocents from persecution, just as the Federation protected us when we were refugees.” 

The Empire has officially demanded that the Neo-Marlinists be apprehended, with Senator Patreus claiming “The Landgrave of Mudhrid is a traitor and a war criminal.” 

Both the Alliance and Federation have likewise insisted on their arrest. However, Shadow President Winters reminded Congress that the Marlinist Charter grants their systems the same legal powers of asylum as the Federation. 

The Marlinist Parliament has declared an emergency situation. First Minister Fairfax called for a discussion of options, while Ministers Amrita Ross and Tamsin Taylor urged cooperation with the Empire.