* Saud Kruger Seeks New Holiday Worlds

/23 Sep 3307/

*Pilots Federation ALERT* 

An initiative to gather data on potential tourist destinations has been launched by shipbuilding corporation Saud Kruger. 

The luxury passenger ship manufacturer aims to identify new Earth-like planets that would be attractive to holidaymakers. These trips will be managed by its subsidiary, Astrogator Tours. 

CEO Stanislav Kruger announced the campaign to the press: 

“We are keen to acquire data on Earth-like worlds, to assess their suitability as destinations for future holidaymakers seeking the adventure of a lifetime. However, all exploration data is valuable and will earn generous payments.” 

“In addition, our marketing department is keen to receive images of eye-catching sights found within unpopulated systems containing Earth-like worlds, to spot the most potentially exciting additions to the Astrogator Tours catalogue.” 

Vistaenis Incorporated has agreed to organise the initiative on behalf of Saud Kruger. Contributing pilots are invited to deliver exploration data to Youll Port in the Vistaenis system. They can also submit their most compelling images by Thursday the 30th of September.  

By Thursday the 28th of October, the most suitable locations will receive tourist beacons and credit the Commander for their submission where appropriate. 

If successful, Saud Kruger’s Dolphin, Orca and Beluga Liner ships will be reduced in price for one week from Friday the 1st of October, with the percentage dependent on the volume of data received. There will also be a discount on the luxury-class cabins used by these crafts to transport VIP passengers.