:PROPERTIES:
:ID:       bce02e51-c68c-4594-86fe-88dda4915a74
:END:
#+title: Duval
* Family
- [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Augustus Duval]]
- [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]]
- [[id:3cb0755e-4deb-442b-898b-3f0c6651636e][Hengist Duval]]
- [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]


* 0135 [[https://eddb.io/attraction/72934][Battlegroup's Disappearance]]                      :beacon:EliteHistory:
In 2924, a further conflict started up in the Alioth system, initiated
by a squabble over its hydrocarbon resources. [[id:a4742b9a-2519-400a-9e11-50710be11771][The Durn and Resner
Corporation]] applied for Imperial assistance to enforce its claim over
a large swathe of the system's mining rights. A small force of
Imperial cruisers and their support ships arrived in the system and
rapidly deployed to enforce these claims. They vastly outnumbered the
mustered Federal units, and forced them out of the entire system
within a year. But then, without warning in 2925, the Imperial battle
group disappeared. Federal vessels returned and [[id:32d2f6e7-6a55-41ca-aa2c-8c3396eb0509][Hassoni-Kruger]]
appropriated the system's mining rights. Within months all assets of
the Durn and Resner Corporation were seized by the Emperor. The reason
for these strange events has never been discovered. Federal
intelligence sources were later to accuse the [[id:bce02e51-c68c-4594-86fe-88dda4915a74][Duvals]] of instigating a
[[id:4d2ace21-1658-4733-a922-e2fa97dfd3cd][cloning programme]] to breed specialised infantry units.
