* Thargoid War Bulletin: Titan Destroyed

/04 Mar 3310/

Titan Taranis, one of the eight Thargoid motherships, is presumed destroyed after a concerted attack using Guardian nanite torpedoes. 

The journalist Jade Sanderlyn published a bulletin via Vox Galactica: 

“We’re receiving incredible news from the Hyades Sector FB-N b7-6 system, where independent pilots were supporting Aegis’s assaults against the Titans. The new Guardian nanite torpedoes have proved effective against the Titans’ thermal vents, forcing their hulls to open and vent internal heat. And that has allowed Commanders to target the core of each gigantic ship.” 

“What were believed to be Taranis’s death throes were closely observed. A massive release of energy repulsed all ships, followed by further explosions. At present the Titan’s status cannot be verified, due to an intensely corrosive gas cloud that prevents ships from approaching. Aegis is confident, however, that the detonations were fatal.” 

“It’s too early to analyse what this means for the ongoing Thargoid war. But this looks like a significant victory, proving that these giants can be toppled after all. As attacks continue against the seven remaining Titans, we will follow these developments closely.”