* Famed Treasure Hunter Herman Colt Missing

/29 Oct 3310/

A prominent figure in the treasure hunting community has gone missing, prompting speculation as to his fate. 

Herman Colt, known for recovering several notable historical artefacts across the core systems, departed the Frenis system three weeks ago along with several other pilots. It is believed Colt’s latest expedition sought the final treasure hoard of Captain Morrigan, a fearsome pirate active in the mid-3200's. 

Rewired spoke to a colleague of Colt’s, Natasha Moore, for an insight into Colt’s whereabouts: 

“It’s unlike Colt to maintain radio silence during an expedition. In fact, it's fair to say he loves the attention. Each new expedition generates buzz among the exploration community, with dozens of pilots begging to be taken along for the adventure.” 

“Colt has a soft spot for Captain Morrigan – I think he’s already got some bits and pieces from her life on display at his home. I know he was excited about this trip, and the chance to find Morrigan’s final treasure stash. But typically Colt would have sent me an update by now. Hopefully he’s just having too much fun on his latest voyage.” 

Captain Morrigan was known for a series of daring raids between 3253-3261, with her gang often overpowering significantly larger forces to steal cargo from trade convoys in and around Frenis. Her most significant rivals belonged to the Candira gang, and firefights between the two groups were common. Morrigan was last sighted in 3265, and it is believed she died in action around this time.