* Thargoid Titan Wreckage ‘Could Accelerate Multiple Scientific Fields’

/16 Oct 3310/

Aegis scientists have recently held a public forum to discuss ongoing research into the wreckage left behind by Thargoid Titans. 

The Xenological Science Symposium on Procyon B 7 discussed topics including technological advances made since the start of the Second Thargoid War, their potential application to non-military industries, and hypothetical future-tech in the event of victory against the Thargoid invasion force. 

Keynote speaker Professor Shamus Madigan, part of the Federal delegation to the Aegis Initiative, chose to discuss the Thargoid Titan wreckage and potential advancements from the components thus far recovered from them. 

“Obviously, we’ve seen huge strides in human aerospace technology with the SCO frame shift drive. Achilles Aerospace has delivered a marvellous device which greatly amplifies the travel speeds of small spacecraft within a star system.” 

“But the reality is that the scientific community is exploring further applications of this xeno material. For example, the Titans design has mastered thermodynamic efficiency. The exchange of energy to power while distributing heat away from core components is so effective it has essentially redrawn the map of our understanding.” 

“If we can harness this efficiency into large-scale manufacturing, say, it’ll offer so many opportunities. Industrial installations could work harder and faster without compromising safety. Raw resources processed into finished products at higher rates could reduce consumer costs and increase accessibility.” 

“It’s quite an exciting time for research, industry and corporations of all sizes.”