* Zorgon Peterson Event Reveals New Exploration Vessel

/15 Oct 3310/

Zorgon Peterson has delighted fans and investors alike with the confirmation of its first new vessel in six years. 

At an extravagant launch party, the Mandalay was introduced to an enthusiastic reception. Presented as an exploration-focused vessel, Zorgon Peterson chief marketing officer Devin Kaneda provided the following details: 

“With the Mamba, Zorgon Peterson’s team showed we can match all other manufacturers in terms of speed. With the Fer-de-Lance, we demonstrated our understanding of excellent military design. Now, with the Mandalay, we aim to provide consumers with a premium exploration option.” 

“Our design division has focused on specific performance advantages once again. The Mandalay brings a significant jump range for a medium-sized vessel. Careful attention has also been placed on improving ship handling in atmospheric environments.” 

“We’ve also listened to explorers regarding quality-of-life features. Therefore, the disembark platform is forward-facing, strong landing-mode illumination acts as a beacon during journeys of discovery. Structural support for SCO frame shift drives is also included as standard.” 

Early reviews have complimented the design, performance, and aesthetics of Zorgon Peterson’s latest release. It is believed that Faulcon DeLacy management are extremely impressed with the launch event and are optimistic for the vessel’s market performance. 

The Mandalay is expected to be available for public purchase soon.