* Torben Rademaker Demands ‘Disconnection’ of Seo Jin-ae

/21 Oct 3310/

Azimuth Biotech CEO Torben Rademaker has claimed that Seo Jin-ae's current medical situation is ‘dangerous’ for humanity. 

Last week, Aegis’ special advisor Seo fell into a coma following a violent seizure. Head of Aegis Alba Tesreau confirmed the incident shortly afterwards, stating that Seo was receiving the best possible care at an Aegis medical facility. 

Following a request for comment statement by Vox Galactica’s Conrad Sterling, Rademaker discussed his views on the latest developments in the Thargoid war and the status of Seo: 

“The original whistleblower of this tragic event did everybody a huge favour. No doubt Aegis would have hidden the truth otherwise, as the initiative has done so many times over the years.” 

“One thing I noticed from Ms. Tesreau’s statement was the lack of any reference to the ‘incredibly high brain activity’ mentioned by the whistleblower. Surely if this detail were incorrect, it would have been refuted. Instead, it was ignored. Isn’t that strange, Conrad?” 

“I can only conclude that the link Seo possesses to the Thargoid hive mind is active in ways we cannot comprehend. And that is a danger we simply must not permit. I call on Aegis to do the right thing and disconnect Seo Jin-ae from whatever external force has control of her. By any means necessary.” 

When called for a response, an Aegis spokesperson simply mentioned that Rademaker’s comments were ‘characteristically insensitive.’ The latest update on Seo’s condition suggests she is currently stable but remains unconscious.