* New Reports of Criminal Fleet Raise Questions

/01 Jun 3312/

Rumours are spreading across several systems following multiple sightings of ships bearing unidentified markings in formation. 

Security officials have more reported instances of malware bearing sigils previously discovered in the Lhou Mans attack appearing at otherwise unconnected locations, often at trading outposts, surface ports, and outlying orbital installations. 

Multiple malware sigils have also been reported by system authorities investigating data breaches, described as what appears to be ‘twin axes’, an ‘animal’, and an ‘ornate mask’ across separate incidents. 

While no formal link has been established between the motifs, Crime correspondent Mira Bukowski has suggested that their appearance is linked to the reports surrounding the emergence of the pirate figure known as Lady Zi. 

“These reports are too coincidental to be random and unconnected,” she wrote for Vox Galactica. 

Imogen le Ray, CEO of Frontline Solutions, responded to the reports indicating in a statement issued to Bukowski for Vox Galactica that “Frontline is preparing to provide additional services to combat the rise in criminal activity,” and strongly hinted at a formal announcement in the coming days.