* Vista Genomics Exobiology Initiative Deemed a Success

/09 Jul 3312/

Vista Genomics has confirmed the successful conclusion of its exobiology initiative across the Sanguineous Rim. 

In partnership with Faulcon DeLacy, both confirmed that pilots not only secured vast quantities of exobiological data needed to investigate genetic diversity across the region but also helped confirm that the Nomad improved planetary exploration. 

Chief Engineer Frank Endis, who supervised the campaign for Faulcon DeLacy, reported that the Nomad “allowed for more efficient exobiology sampling and research to be conducted than previously experienced by explorers.” 

“The new Mk II Biological Scanner and Mk II Sensor modules that the Nomad provides also offered explorers and exobiologists more productive journeys thanks to their enhanced range capabilities.” he added. 

With the trials now concluded, Faulcon DeLacy hopes that the Nomad will quickly become a key feature of long-range exploration and exobiology expeditions for those who own ships that can equip the vessel. 

The Nomad is currently available for exclusive purchase initially and will transition to standard shipyard inventories at a later date.