* Major Corporations Promote Colonia Celebrations

/13 Jul 3312/

Multiple corporations have supported the recent announcement of Colonia’s tenth anniversary celebrations. 

Vox Galactica business correspondent Marlon Royce spoke to several representatives of major names from the technology, transport, mining and tourism industries. 

“Colonia stands as a beacon of human achievement in deep space,” commented Naomi Landseer, chairperson of Lakon Spaceways. “Lakon Spaceways is synonymous with success out in the black, and we applaud the continued success of Colonia’s people.” 

Meanwhile, Jaques and the Colonia Council gave Vox Galactica more behind-the-scenes information about planned festivities. 

“It’s high time the corporations in the core systems showered us with some love and attention,” Jaques said enthusiastically from his bar. “So, we’re inviting them to help us pull together the first ‘Colonia Fair’ - a galaxy-sized exposition that’ll include exhibitions, activities, performances, films, art, food...and plenty of libations!” 

Vox Galactica understands that preparations are underway for a massive transportation effort of commodities and rare goods from across the core systems to Colonia, with details of the logistics to be announced soon.