* SRV and Surface Mining Trials Deemed Resounding Success

/17 Sep 3312/

Vodel confirmed in a joint press statement with Wreaken Mining that recent early release trials of the new Rhino SRV had been a huge success. 

Telemetry data received from independent pilots taking part in the recent initiative showed that the new surface vehicle performed across even the roughest planetary terrain. 

"We're extremely proud of the Rhino and its capabilities." said Owen McKenna, CEO of Core Dynamics. 

Dr. Ben Curtis, Chief Geologist of Wreaken Mining, added "The amount of minerals received as a result of the new surface mining rig was unprecedented," 

"My research has been proven, and I cannot wait to see what this new technology will yield in time." 

With the trials now concluded, both Vodel and Wreaken hope that the Rhino and the rig will usher in a new era of surface mining. 

The Rhino with the mining rig included as standard are currently available for exclusive purchase initially and will transition to standard shipyard inventories at a later date.