* Increased Traffic Near Prison Ships Sparks Concern

/14 Sep 3312/

Governing authorities of several star systems have reported unusually high traffic around prison reformatories during recent inmate transfers. 

Known affiliates of local pirate factions have been spotted flying in formation near the prison ships, but so far have not engaged with local security forces or prisoner transports. 

"Although no direct action has taken place, the pattern and frequency of their appearance suggest that these criminal elements are observing inmate transport movements," a spokesperson for The Independent Detention Foundation remarked to Vox Galactica. “Given that many of the identified pilots have seen the inside of our cells at some stage, it’s unusual to be so brazen in their activity." 

"For now there has been no conflict with these vessels, and pilots are complying with directives to maintain a minimum distance. We're working closely with local authorities across our fleet itinerary to ensure there are adequate security forces in place to deter any escalation."