* Guardian Archive Hints at Ancient Radicoida Parallels

/28 May 3312/

Ram Tah has confirmed the existence of previous mention of what appears to be Radicoida unica in the Guardian Archives. 

In a statement issued to Leon Banerjee, science correspondent for Vox Galactica, he revealed that in the weeks since the discovery of the rare flora, he has been re-examining Archive data in the hope it would elicit more information about the plant’s past origins. 

Ram Tah referenced archive passages describing a “kingdom of blessed roots,” alongside accounts of a substance derived from seed pods used by Guardian factions that rejected advanced technology. 

“These traditionalist groups appear to have utilised a naturally occurring compound to enhance their warriors prior to battle during their civil wars,” he explained. 

“While much of the context remains unclear, the descriptions are striking.” 

Additionally, accompanying diagrams within the recovered data include biological schematics that bear a strong resemblance to recent resonance imaging of Radicoida unica. 

“It was unfortunate, however, that a member of my team got way ahead of himself and alerted the October Consortium without permission about my discovery,” he added. 

“I can only assume this is what prompted their sudden interest in Guardian artefacts. We were willing to share this information, after all.” 

The implications of this discovery remain uncertain, although many now widely believe it may point to a far older, deliberate connection between the species of flora and the long-extinct Guardians.