* Federation Breaks Silence on October Accords Exclusion

/29 Jun 3312/

President Felicia Winters conveyed ‘disappointment’ at the Federation’s continued exclusion from Radicoida unica research. 

While careful not to criticise members of the October Accords directly, Winters made clear that denying the Federation any level of access to the research and its findings would force the superpower to act: 

“We recognise the October Consortium's duty to uphold the Accords it helped establish as a framework for peace in the enclave conflict. However, I would remind Lexi October that the Federation rewards those who choose cooperation." 

“Should the outcome of this research put the Federation at a technological or strategic disadvantage against its rivals, my administration will have no choice but to view the situation as a potential threat. That threat will, in turn, dictate our own research priorities.” 

Today's press conference from the White House marks the first time the President has spoken openly about the Accords since the conflict for HIP 87621 concluded in February this year. 

The Federal Times has reached out to representatives of the members of the October Accords but so far all have declined to comment.