* Faulcon DeLacy Announces New Ship-Launched ‘Nomad’

/30 Jun 3312/

Faulcon DeLacy, the manufacturer behind the popular Python and Cobra ship designs, has announced the limited release of the Nomad. 

The Nomad is a ship-launched craft intended to aid explorers in larger ships, allowing them to explore planet surfaces and locations requiring tight manoeuvrability and speed. 

Chief of Design, Frank Endis, stated in the press release: 

“The Nomad is different to other ship-launched vessels in that it can fly independently of its mothership’s presence. Our team recognised a gap in the market for a smaller craft that grants explorers an alternative option to using their primary ship when navigating difficult terrain.” 

“We’re excited to see the most extreme places pilots can take it.” 

The Nomad comes with a new Mk II Biological Scanner with an enhanced range and is complemented by a Mk II Sensor for close range signals, allowing pilots to locate biological surface signals directly from the ship. 

The Nomad is immediately available as an early-release purchase and will later transition to wider shipyard availability.