* Colonia Plans to Distribute Celebration Commodities

/30 Jul 3312/

With huge numbers of commodities transferred from Brewer Corporation’s megaship fleet to Jaques Station, preparations for the tenth anniversary are in full swing. 

Colonia Council is calling for aid with the second logistical phase of the celebrations by helping to distribute the commodities across the region. 

“We’ve been up against the clock bundling all these commodities into cargo packages! All citizens in Colonia are excited to take part in the celebrations and it’s up to us to supply them,” said Jaques in a press conference held at his bar. 

“The station crew have done an amazing job and are exhausted, but we’re not done yet!” 

Colonia Council member Magen Wolf thanked pilots’ efforts to date, adding: “The success of these celebrations has been largely down to the incredible pilot community and we’re asking for one final push.” 

All independent pilots willing to aid in the final stages of the anniversary preparations should head to Jaques Station and distribute curated commodity packages to designated markets in Carcosa, Einheriar, Randgnid, and Asura.