* Galactic News: Weekly Security Report

/19 Apr 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Social Lalande 2682 Alliance 

Mebech Tzu Protectorate 

Snoqui Xian Future 

Epsilon Indi Purple Central 

Orgetu Jet Mafia 

Liberals of Chongguls 

Fomovithi Corp. 

Alliance of Neganhot 

Official Elska Movement 

Jet Power Network 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Noblemen of Nez Perce 

HIP 80242 Blue Universal Serv 

Alliance of Reddot 

Revolutionary UGP 145 Free 

Friends of Oho Bajo 

Allied CE Bootis Defence Force 

George Pantazis Democrats 

Partnership of DW Camelopardalis 

Namago Commodities 

Friends of Arngi 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.