* Galactic News: Weekly Health Report

/23 Nov 3302/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

Left Party of HIP 43845 

Order of Ethgreze 

GCRV 4654 State Interstellar 

AG+21 1754 Citizen Party 

Ololos Drug Empire 

Chukchair Fortune Group 

Conservatives of HIP 41984 

Totegafook Posse 

HIP 115314 aristocrats 

HR 3954 Crew 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

Uru Federal Interstellar 

HIP 73428 Exchange 

Kvenland Services 

Coalition of Ngaliba 

Uszaa Society 

Chet Crimson Society 

Dragons of HIP 1914 

LHS 1387 Jet Mob 

Marquis du HIP 110867 

Waime Worker's Party 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.