* Galactic News: Weekly Economic Report

/28 Mar 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

League of Gliese 9073 Order 

Sun Wen Ho Allied Corp. 

HIP 17298 Network 

Gliese 3318 aristocrats 

Movement for Liu Yanec Union 

Future of Regnenses 

Jana Blue Dynamic Exchange 

Yukan Hand Gang 

Granthaimi Group 

51 Aquilae Independents 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

LTT 911 Dragons 

Autocracy of BD+02 4718 

Traditional LHS 3262 Nationalists 

HIP 25795 Family 

Olelbis Blue Camorra 

HK Aquarii Industry 

Bureau of Bodb Dearg Flag 

Kokojina Gold Travel Systems 

Natural Tote Bureau 

Dragons of Urvane 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.