* Galactic News: Weekly Economic Report

/22 Feb 3302/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 12,191 minor factions currently enjoying an economic boom: 

Regir Boys 

Official Eravate Flag 

New 15 Lambda Aurigae Revolutionary Party 

Amun Public Co 

Polevnic Blue Universal Inc 

Hurukuntak Company 

Hermoduroua Incorporated 

New Meliae Flag 

6 Andromedae Order 

Noatiaca Public Limited 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 524 factions currently experiencing economic bust: 

United Epsilon Indi Flag 

Erh Lohra Crew 

BD-02 4304 Jet Drug Empire 

Ross 720 Crimson Cartel 

Gridge Public Group 

Jupalo Purple Boys 

People's Urvane Labour 

Mahei Posse 

HR 8170 Blue General Commodities 

Liberals of Wolf 287 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.