* Freelance Report: Friendly Fire over Merope 2 A

/01 Jul 3302/

Despite assertions from Admiral Maxton Price that Federal ships in Merope would not initiate conflict, a recent incident report tells a different story. 

The report claims that a clearly marked Asp Explorer science vessel was shot down, without provocation, by Federal vessels above Merope 2 A. Rescue teams from Obsidian Orbital, responding to a distress call, found the smoking wreckage of the ship a short distance from a barnacle site guarded by a Farragut Battle Cruiser and a squadron of combat ships. The pilot – a captain in the Federal Auxiliary Navy – was only slightly injured.  

A spokesperson for the Federal Auxiliary Navy said: "A lone Asp with retracted weapons is no threat to a battle group, and the Navy can't shoot whomever they want without jurisdiction. If one of my boys ignored the rules of engagement like that, I'd throw the book at them. Admiral Price can expect a formal inquiry from the JAG as soon as the paperwork is done." 

The Federation has not issued an official response.