* Community Goal: The Dangerous Games Begin

/02 Jun 3302/

The galaxy is home to countless factions, some boasting thousands of members and others comprising only a handful of individuals. Some exist to serve the galactic community, while others follow more antagonistic dogmas. For almost every creed in human space, there is a corresponding faction. 

Recent reports indicate that the largest of these factions have gained such significant levels of power and influence that they are on the cusp of being recognized as powers in their own right. This development coincides with mounting speculation that the empire of Pirate Lord Archon Delaine, once the most formidable power in the Pegasi Sector, is on the brink of collapse. 

With a paradigm shift looming, the largest of the galaxy's factions have taken the unprecedented step of organising a semi-official competition for the right to be recognised as an official power. The name of this competition? The Dangerous Games. 

Trinity Avon, a reporter for The Sovereign, elaborated on the nature of the event: 

"There are five factions competing in the Dangerous Games: the Alliance Elite Diplomatic Corps, the Border Coalition, GalCop, the Interstellar Communist Union and the Social Eleu Progressive Party. Between June and July 3302, these groups will participate in a series of community campaigns, giving the galaxy's independent pilots a chance to support their chosen faction." 

But these will not be the only factions taking part. With the start of the event still some weeks away, a number of smaller factions have begun competing for their chance to participate in the Dangerous Games. In the coming weeks, these factions will attempt to rally Commanders to their respective causes through a series of community-oriented events. Whichever faction successfully dominates its rivals in these 'Wildcard' events will enter the Dangerous Games, competing for the right to join the ranks of the galaxy's most powerful. 

The first Wildcard event requires pilots to fire up their mining lasers and gather gold for their chosen faction. The faction with the most gold at the end of the week-long campaign will be declared the victor of the first Wildcard heat. Naturally, pilots are also free to disrupt their rivals' efforts. 

The event begins on the 2nd of June 3302 and will run for one week.