* Galactic News: Weekly Security Report

/19 Jul 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Gondul Jet State Company 

Atrimih Gold Transport Comms 

Justice Party of Zeta Tucanae 

Tatapai Company 

Revolutionary Nysa Future 

Social Cupinook Free 

Itzamnet Group 

Guaneponne Partners 

Raurici Empire Consulate 

Social G 181-6 Liberals 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Firdaus Crimson Family 

Ovid Vision and Co 

Ringardha Commodities	 

Haokipi Galactic Network 

Labour of LHS 283 

HIP 33368 Vision Network 

Eranin Industry 

Movement for LHS 450 Progressive Party 

CD-53 136 Imperial Society 

Theotokos Universal Exchange 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.