* Galactic News: Weekly Security Report

/11 Oct 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

People's Ross 860 Independents	 

Putamasin Future 

Confederacy of AC +67 1894 

Pirates of Sun Takush 

Workers of LHS 139 Revolutionary Party	 

36 Ophiuchi Federal Corporation 

Uniting LTT 2622 

Fire Flasa Stakeholders 

The Imperial Vanguard 

Khun Ltd 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Yaque Systems 

LHS 3197 Central and Co 

Pirates of LHS 450 

Pirates of Luyten's Star 

Cartel of Wolf 397 

V374 Pegasi Progressive Party 

Social Wolf 397 Progressive Party 

Traditional EP Eridani Defence Party 

Kremata Defence Force 

Opala Group 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.