* Galactic News: Weekly Health Report

/30 Nov 3302/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

Social Zaragas Independents 

GCRV 4654 State Interstellar 

AG+21 1754 Citizen Party 

Ololos Drug Empire 

Waime Worker's Party 

Chukchair Fortune Group 

Totegafook Posse 

HIP 115314 aristocrats 

League of Machimi Front 

HIP 15545 Gold Syndicate 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

Social Zaragas Independents 

LTT 377 Purple General Corp. 

HIP 19773 Shared 

Bubii Rats 

Uszaa Society 

Allied Ualapalor League 

Iptera Allied Corp. 

Dragons of HIP 1914 

HIP 14759 Guardians of Tradition 

Ngandrusa Purple Boys 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.