* Galactic News: Weekly Conflict Report

/29 Apr 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Shanteneri United Limited 

Ross 199 Law Party 

Future of Wurango 

Revolutionary Calea Labour 

Calea Jet Central Holdings 

Liberty Party of LHS 1788 

V886 Centauri Corporation 

Al-Qaum Independents	Federation 

Union of Luhman 16 Values Party 

HIP 12605 Empire Party 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Independents of Parenni 

Brontes League 

HR 4720 Labour 

Guardians of Harmony 

Li K'anja Energy Industries 

Chowei Purple Major Group 

HIP 18527 Silver Energy PLC 

Eurybia Empire Consulate 

Tofana Blue Electronics Network 

Sayango Silver Galactic Holdings 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.