* Galactic News: Weekly Security Report

/22 Nov 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Brotherhood of LP 98-132 

Emperor's Will 

Rajgonta for Equality 

Leaders of LFT 1404 

Ovid Defence Force 

Sifjar Group 

People's Cegreeth Values Party 

Lei Mati Blue Allied Commodities 

Quince Jet Family 

Monarchy of Elbiones 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Brotherhood of LP 98-132 

Wolf 359 Blue Travel Commodities 

WISE 0855-0714 Gold Gang 

Confederation of LPM 26 

Oho Bajo Public Holdings 

Segoveduwa Empire Party 

Ross 775 for Equality 

Xuanduna Silver Allied PLC 

Social LP 510-10 Future 

Lei Mati Patron's Principles 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end