* Freelance Report: Puritanical Organisation Targets Traders

/17 May 3302/

Earlier this week, private security firm the Diamond Frogs issued a request for liquor and other legal narcotics to be delivered to Skvortsov Orbital in 63 G. Capricorni for a massive party celebrating the success of the Distant Worlds Expedition. Independent traders throughout civilized space have responded enthusiastically to the appeal, but it would appear not everyone wants to share in the festivities. 

Recent reports indicate that an extremist temperance organisation from the nearby system of Eravate has been interdicting and destroying merchants attempting to deliver legal intoxicants to Skvortsov Orbital. Although only minor casualties have been reported, representatives from the Diamond Frogs have expressed concern about the social unrest in Eravate spilling over into neighbouring sectors. 

Commander Paramemetic, the Diamond Frogs' chief logistics officer, said that the security firm would take steps to ensure the safety of traders making deliveries. "It's a shame these puritanical troublemakers are trying to steal the spotlight from the explorers," he said, "but we'll make sure they don't interfere with the celebrations." 

'Disc' Commander Felix Dyson, Radio Skvortsov