* Galactic News: Weekly Economic Report

/18 Apr 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Gullici Jet Pirates 

Chao Wu Commodities 

Unionists of CD-66 2585	0 

Nocoma Solutions 

Natural HIP 18327 Nationalists 

HIP 117706 Purple Netcoms Inc 

Angelic Church of Messi 

Kelie Silver Major Industries 

League of Hrunapori Autocracy 

Independent Kiliwatsuki Free 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

LP 104-2 Silver State Comms 

Paucates Gold Brothers 

Kaiablingah Blue Raiders 

Grovichun Purple Boys 

United Epsilon Indi Flag 

LTT 8517 Jet Gang 

Irukama Labour 

Natural Vega Liberty Party 

Gridge Life Exchange 

Maiki Silver Mafia 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.