* Galactic News: Weekly Conflict Report

/21 Oct 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

LFT 1448 Federal Industries 

Purple Dynamic Incorporated 

Citizen Party of Argel 

Argel Universal Solutions 

Revolutionary Nemehi Future 

Ofaye Aibe Inc 

Amun Gold Brotherhood 

Green Party of He Pola 

Cai Quapa Purple Comms Corp. 

HIP 38129 Life Systems 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Dyr Values Party 

Time of Chaos 

Camumba Partners 

Ditae Empire League 

Progressive Party of Wolf 433 

Bletones Legal Industry 

Earls of Xibalba 

BD+23 296 Blue Federal Inc 

Chunza Dominion 

Reddot Blue Clan 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.