* Galactic News: Weekly Security Report

/01 Nov 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Kokary Holdings	 

Ngaliba Blue Camorra 

Liaedin Mafia 

Inupiates Patrons of Law 

Bhotho Rats 

LHS 3384 Progressive Party 

Ciboney Labour 

Social Gabiko Liberals 

Segoveduwa Empire Party 

United Wat Yu Confederacy 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Kokary Holdings	 

Limapa Blue State Commodities 

Zaragas Energy Corp. 

Ngaliba Blue Camorra 

Labour of Ethgreze 

Apoyota Domain 

HIP 26883 State Company 

Nationalists of Aulin 

Rajgonta for Equality 

Leaders of LFT 1404 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.