* Galactic News: Weekly Conflict Report

/05 Feb 3302/

This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data. 

Here are 10 of the 15,345 minor factions involved in a civil war: 

Ocairi Inc 

Birhepri Federal and Co 

Independent Birhepri Citizen Party 

HIP 48025 aristocrats 

HIP 48025 Boys 

Crew of Tharu 

Tharu Future 

Party of Pancho	 

Future of Pancho 

Maon Jet Dragons 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 6,831 minor factions at war: 

HR 494 Incorporated 

Partnership of Zang Tangma 

LTT 7488 Patron's Principles 

Independent IV Comae Berenices Labour 

HR 827 Empire Party 

Icovit United Partners 

Alliance of BD-11 4280 

Amahinohara Law Party 

Syntha Blue Camorra 

Grans Jet Gang 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

Data is correct at time of publishing.