* Galactic News: Weekly Economic Report

/01 Feb 3302/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 12,154 minor factions currently enjoying an economic boom: 

HIP 29964 Natural Limited 

Ocairi Inc 

Values Party of Wei Jung 

Future of Durok 

Wunjo Independent Union 

LTT 12058 Values Party 

Waricare Group	 

Siaroju Gold Posse 

Lahara Allied Network 

Thiana United Group 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 600 factions currently experiencing economic bust: 

Njorog Democrats 

Furbaide Syndicate 

Pand Inc 

Wandjin Boys 

Wolf 896 Crimson Crew 

Official Rajukru Party 

LHS 1446 Blue Partnership 

League of George Pantazis Defence Force 

HIP 101846 Crimson Fortune 

Integrated Qahat 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.