* Galactic News: Weekly Conflict Report

/09 Dec 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Uru Federal Interstellar 

Eravate Life Services 

New 31 Aquilae Green Party 

HIP 5712 State Corp. 

Chamunda Crimson Gang 

Fusang Fortune Commodities 

LHS 3479 Interstellar 

LTT 377 Purple General Corp. 

Ross 754 Universal and Co 

Luyten 674-15 Industries 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Cemiess Commodities 

Yakabugai Exchange 

Kini Drug Empire 

Order of Ethgreze 

United LHS 3479 Green Party 

Crimson State Group 

GCRV 4654 State 

Ross 754 Labour 

Independents of Mildeptu 

39 Tauri Interstellar 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.