* Galactic News: Salomé – Pride or Prejudice?

/19 Aug 3302/

The Imperial Citizen has published its second editorial on Commander Salomé, who the Citizen alleges is Lady Kahina Tijani Loren, the missing Imperial senator. 

"According to Lady Kahina's account, she escaped a hardened gang of freedom fighters and faced down a notorious pirate lord. Is it not more likely that she colluded with these terrorists to murder her family so she could become a senator? Is it not convenient that she slaughtered these terrorists before they could be questioned, and then did the same to her mentor? And with a sword, too." 

"Don't forget that Kahina almost triggered a war between the Empire and the Federation. Thousands died in that battle – a battle she started. Heroine of the Prism system? Hardly. She was responsible for the largest loss of life that Imperial outpost ever saw, exceeding even her father's appalling legacy." 

"Not content with acquiring her father's senatorial position via her so-called 'reclamation', Lady Kahina then gallivanted around the core worlds trying to gain support in a bid to become Emperor. She soon found, however, that her self-image was out of step with reality. But did she return to her supposedly beloved homeworld? Of course not. She disappeared for several months only to reappear, as if she were the patron saint of explorers, on the far side of the galaxy in the Distant Worlds Expedition." 

"Along the way she engendered the support of misfits, miscreants, starry-eyed explorers and dissident organisations masquerading as legitimate factions. Why she seeks such support is not known." 

"Have no doubt – this so-called 'lady' is no saint. Whatever she does is solely to further her own interests, manipulating those around her as she has always done. She is clearly deluded, but her powers of persuasion are formidable. Many have sworn loyalty to her, particularly those disaffected by the politics of the core worlds." 

"Beautiful and charismatic she may be, but she is also a bloodthirsty, selfish and manipulative individual who will stop at nothing to achieve her goals. Do not trust a word she says."