* Galactic News: Weekly Conflict Report

/04 Mar 3302/

This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data. 

Here are 10 of the 15,278 minor factions involved in a civil war: 

NLTT 2969 Partners 

Prthautas Electronics Ltd 

Setet Public Exchange 

Setet Purple Pirates 

Prthautas Jet Crew 

HIP 25359 Democrats 

HIP 25359 Universal Company 

Meene Purple Drug Empire 

Meene General Industries 

Mere Federal Partners 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 7,104 minor factions at war: 

Rosmerta Citizens of Tradition 

HIP 20924 Labour 

Maasates Imperial Society 

Satio Blue State Exchange 

Tan'gika Gold Clan 

Raidenwitha Defence Force 

Halamaitu Jet General and Co 

Xiongga Industries 

Mirdia United 

Belaba Constitution Party 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

Data is correct at time of publishing.