* GalNet Weekly Conflict Report

/28 Aug 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data (*). 

Here are 10 of the 13,342 minor factions involved in a civil war: 

Masters of Wolf 906 

LP 811-17 Corporation 

Yawa Empire Party 

Natural LP 811-17 Conservatives 

NLTT 13249 Limited 

HIP 20480 Coordinated 

HIP 20480 Universal Incorporated 

Allied Wu Kich Dominion 

Progressive Party of Wu Kich 

Ernutet United Co 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 2,443 minor factions at war: 

Family of HIP 94863 

Independent Gladyangar Revolutionary Party 

Crew of Gamamonga 

Amahutii Gold Dragons 

Purungurawn Purple Society 

Haolin Ti Partners 

Nik Future 

Lodemovoi Advanced Incorporated 

Worker's Party of Tamor 

G 126-31 Purple Federal Org 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

* Data is correct at time of publishing.