* Ending Corruption at Home and Abroad

/30 Jul 3301/

Ending Corruption at Home and Abroad 
 
Concerns have been raised that the ongoing war of liberation in the Pegasi sector, Operation Davy Jones, has left the Empire exposed to invasion and corruption. Addressing these concerns, Senator Arissa Lavigny-Duval had these words for her constituents: 

"With so many of our Imperial fleets engaged in battle, it is understandable that some are anxious about the security of our territory. I want to assure our citizens that local security forces are not impacted – in fact, over half of the Imperial fleet is held in reserve. Over the past weeks, a number of Imperial systems in our home space witnessed corrupt and repressive governments replaced by traditional patronages. Much of the heavy lifting has been done by Imperial reserve fleets. Our continued success in the Pegasi sector will soon liberate our citizens living there. To shirk our duties to our citizens, whether at home or abroad, is unacceptable.” 

Commander Corrigendum