* GalNet Weekly Economic Report

/10 Aug 3301/

GalNet Weekly Economic Report 
 
In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit (*). 

Here are 10 of the 3,788 minor factions currently enjoying an economic boom: 

Shenich Legal Solutions 

Nijuna Company 

Heheng Freedom Party 

Labour of HR 244 

LHS 221 Vision Systems 

Koskit Company 

Gongalungul Comms Organisation 

5 G. Capricorni for Equality 

Ditian Imperial Society 

Official V640 Cassiopeia Front 

When in boom, the wealth of the system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction’s influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 54 minor factions experiencing an economic bust: 

Values Party of BD+26 2184 

New HIP 18187 Flag 

Law Party of YZ Ceti 

Tialocan Jet Raiders 

Justice Party of AZ Cancri 

Sosoling Purple Netcoms Network 

HIP 19758 Empire Consulate 

NLTT 12619 Confederacy 

Forculus Ltd 

Values Party of Jitani 

The wealth of a system diminishes while in bust and the minor faction’s influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

* Data is correct at time of publishing