* GalNet Galactic Trade-Labour Report

/28 Feb 3301/

An influx of semi-professional miners from Sol has caused a significant increase in the demand for Mineral Extractors in LAWD 26. In order to meet that demand, the Union of Toofla Progressive Party is currently offering excellent rates for all Mineral Extractors sold to Stone's Legacy. As if that wasn't generous enough, in order to attract new potential trading partners the Union of Toofla Progressive Party are also selling off large amounts of gold at bargain basement prices. Furthermore, the Union of Toofla Progressive Party has guaranteed that they will discount the price of locally sourced gold even further if they manage to secure their place as a major player in the local markets. 

*** 

The Sirius Corporation released a statement today announcing that thanks to the tireless work of hundreds of explorers, 8 new colonisation candidate systems have now been identified. Sirius scientists hope to discover many more potential sites as they continue analysing the petabytes of data they've received over the last week. Explorers interested in helping with the Sirius Corporation's colonisation project only have a few hours left to make their submissions to Universal Cartographics on Nourse Orbital in Lambda Andromedae.  

* * * 

Despite heavy interference from pirates and imperial mercenaries, Core Dynamics are still looking to source a large supply of copper for use in the construction of the new Federal Capital Ship aboard Hudson Dock in BD+03 2338. It is believed that Core Dynamics have requested additional funding from the Federal Navy in order to hire private security to protect traders bringing copper into the system. At time of publication the funding had not yet been approved.