* Blaine Address State of the Emperor

/20 Jun 3301/

Blaine Address State of the Emperor 
 
Chancellor Blaine made an appearance before the Senate today in order to provide an update on the Emperor’s health, following the attempt on the Emperor’s life a little over a month ago. 

“I am pleased to report that the Emperor is recovering nicely,” the Chancellor began. “There was some small concern that an excessive amount of toxins had been allowed to take root in the Emperor’s body, but His Grace’s physicians have proven themselves more than up to the task of removing them.” 

“Similarly, praise must go to Princess Lavigny, whose invaluable assistance in tracking down the conspirators led to the restoration of the Emperor’s justice in several dozen systems. A fact which I am sure will be of great comfort to those who were worried that the Duval legacy would be allowed to fall into ruin. Doubtless the Princess’s father would be extremely proud.” 

“On that note, I am pleased to announce that His Grace, Emperor Hengist Duval, has begun to show signs of returning to good health. The Emperor’s personal physicians have assured me that should His Grace continue to heal at his current rate, the Emperor will almost certainly make a full recovery.” 

“Hail the Emperor, bask in his glory.”