* GalNet Weekly Economic Report

/20 Jul 3301/

GalNet Weekly Economic Report 
 
In this weekly digest the latest GalNet data is compiled to show the economic states for a short list of minor factions and the star systems they inhabit (*). 

The following 10 of the 4370 minor factions are currently enjoying an economic boom: 

Mombawet Nationalists 

Amementi Silver Life Exchange 

Allowair Constitution Party 

NLTT 21088 Bridge Network 

Independents of LFT 37 

HIP 15205 Prison Colony 

Finteno Free 

Workers of Luan Yun Di Green Party 

Waq Services 

Uzumeru Netcoms Incorporated 

When in boom the wealth of the system is increased for the duration and all trade missions have doubled effects on influence. It can also positively increase the minor faction’s influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they run out or some other indicator takes precedence, such as famine. 

These 2 minor factions are suffering an economic bust: 

Wolf 750 Liberals 

Jet Energy Industry 

The wealth of a system diminishes while in bust and the minor faction’s influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

* Data is correct at time of publishing