* The Doom That Comes To Quivira

/11 May 3301/

For the last week Civil War has ravaged the independent nation of Quivira. 

Quivira Electronics Plc, acting under orders of Senator Denton Patreus, launched an all out attack on the People’s Quivira for Equality Party, leading to fierce fighting between the two parties in the skies above Godel and Stapledon Docks. 

The People’s Quivira for Equality Party managed to successfully evacuate millions of refugees to the nearby systems of Summerland and Persephone. In particular, the People’s Quivira for Equality Party would like to thank Commanders Maclolie, Tavok, Reliant, Morningstar and Aydro for holding the line long enough for the innocent residents of Quivira to escape. 

Unfortunately for those left behind, it appears that Senator Patreus is not quite done with Quivira. Reports from the region indicate that several Imperial Majestic class Interdictors have been spotted entering Quivira’s airspace. According to sources close to the situation, Senator Patreus now intends to make an example of the defiant nation of Quivira by driving all Independent influences out of the system.