* GalNet Weekly Economic Report

/14 Dec 3301/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 10,244 minor factions currently enjoying an economic boom: 

Justice Party of Caill Reddi 

Cauan Tzu Stakeholders 

Dominion of Zorya Nong 

Kurichchan Coalition 

HIP 87679 Purple Creative Org 

Furuhjelm III-674 Republic Party	 

Regina Blue General Corporation 

People's Bibri Labour 

Carthage Silver Drug Empire 

CD-68 29 General Organisation 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 1,509 factions currently experiencing economic bust: 

Korovii Purple Comms Limited 

Defence Force of Giryampi 

Baker Confederacy 

Uru Bureau 

Hirapa Blue Camorra 

People's Party of Asoorajara 

Nobles of Lacaille 9352 

Bureau of Zeta Aquilae 

Green Party of Diso 

Bhritzameno Regulatory State 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.