* The Bacon City Hangover

/08 Oct 3301/

Last week, the starport of Bacon City played host to the inaugural Bacon Protests anniversary celebrations, which commemorated the repeal of the meat ban that affected citizens of the Carnoeck system in 3288. Revellers from across the galaxy descended on Bacon City to join in the fun, and hundreds of independent pilots ferried animal meat and narcotics to the starport to fuel the festivities. 

The event was not without problems, however, as the steady stream of traders and party goers attracted pirates and other disruptive elements to Bacon City. At one point, the starport was blockaded by an animal-rights group, who ordered ships carrying animal meat to jettison their cargo at gunpoint. 

A spokesperson for United Carnoeck for Equality, the event's sponsors, released the following announcement: 

"For the most part the celebrations have been a huge success, but an event like this is bound to attract a few unsavoury elements. Fortunately we anticipated such an eventuality, and set aside some money for the post-party cleanup. So if you're a bounty hunter and you want to help clear the spaceways around Bacon City, get yourself to the Carnoeck system! We'll make it worth your while."