* The Truth about Emperor’s Dawn

/10 Sep 3301/

The Truth about Emperor’s Dawn 
 
As the campaign against Emperor’s Dawn escalates, captured materials have revealed more about the group and its aims to destabilise imperial society. 

Reporters from a number of respected imperial newsfeeds, including the Imperial Herald, were invited to inspect some of the seized information. At first the reporters were surprised by how innocuous the material appeared. Taken at face value, it seemed to espouse beliefs and traditions supported by many throughout the Empire, despite the rather extreme tone. The propaganda became more sinister, however, when it elaborated on how these beliefs would ideally be enforced. Some of the items included speeches denouncing the Emperor and his ‘complicity in the erosion of tradition’. Elsewhere, demands were made to remove the Emperor so that someone more fitting could take his place. So far, nothing has been revealed about who the group considers a proper candidate for Emperor.