* Antares Incident Links to VP’s Death?

/28 Aug 3301/

Antares Incident Links to VP’s Death? 
 
The case of reporter Elaine Boyd took an unexpected turn today as several respected newsfeeds, including the Federal Times, received encrypted data packages. It is claimed that these were automatically sent by Elaine Boyd from a public storage server with instructions to be delivered if newsfeeds reported her death. 

The data apparently reveals a connection between the death earlier in the year of Vice President Nigel Smeaton and the Antares Incident. His death was officially declared an accident, although many at the time suspected foul play. Those suspicions are likely to rise again with the revelation that he was related to one of the crew aboard the Highliner Antares when it disappeared on its maiden flight 50 years ago. 

Elaine Boyd discovered details of a private ‘off the books’ investigation by the Vice President into the incident and that he suspected it was caused by sabotage, rather than drive component failure. He had already spoken to a number of now quite senior officers involved in the original enquiry. Elaine Boyd’s information implied that he may have been killed to stop his investigation. 

In a statement, the chief editor of the Federal Times said: 

“We hope that amongst the information Elaine has provided there is evidence to prove her innocence in the crimes she was implicated in. We are continuing to examine the data in detail.”