* A Vision of the Future

/06 Jun 3301/

For decades, the Utopian compound on Antal was seen as a place where people could visit the future. Technology that was years ahead of its time was openly on display for anyone to see. The secrets uncovered by the Utopian engineers were made freely available for study, regardless of the factional leanings of those who wished to explore their mysteries. 

That freedom of information, that willingness to share knowledge and ideas, is what has allowed Utopia to grow into a living network of technological communes that will help lead the galaxy towards a better tomorrow. 

In the last five years, hundreds of thousands of scientists, programmers and engineers have begun their journey into the Utopian lifestyle. Their hard work and dedication has been rewarded with a wealth of new technologies that will revolutionise the galaxy once mass production has been achieved. 

Of course, mass production is difficult without the right materials to do the job. Utopia estimates its workshops require around 30 million tonnes of assorted metals per month. So far, no single supplier has been able to meet their requirements. As such, Utopia will be offering a range of bonuses each month to any interstellar traders who bring the Utopians a large supply of metal. 

Those interested in offering assistance to the Utopian Project are asked to deliver metals to Lobachevsky Station in Antal.