* Emperor’s Dawn Issues Request for Supplies

/11 Sep 3301/

Emperor’s Dawn Issues Request for Supplies 
 
As news spreads that Senator Denton Patreus has launched a military operation against Emperor’s Dawn, journalists at The Imperial Citizen report that the insurgent group has issued a public appeal for commodities. Significantly, the goods the group has requested – progenitor cells and narcotics – are illegal in many jurisdictions. 

Emperor’s Dawn has not explained its need for these commodities, but given its militant stance it can be safely assumed that the goods will used in its ongoing campaign against the Empire. The organisation is understood to have set up delivery points at starports in the Ipilyaqa and Ch’i Lin systems. 

The Empire has not issued a response to the appeal, but it is likely that it will implore the public to ignore the request. But with so many independent traders in the galaxy, many of whom have no particular loyalty to the Empire, it seems inevitable that at least some will answer the call of Emperor’s Dawn.