* Torval Apologises for Synteini Slave Snafu

/21 Apr 3301/

Last weekend the Imperial Slavers Association was supposed to make 5 million Imperial Slaves available for a significant discount in the markets aboard Lagerkvist Gateway. Much to the dismay of hundreds of eager Imperial traders, the slaves (and their associated discount) were delayed by members of Princess Lavigny-Duval’s retinue as they attempted to pass through LTT 9810. 

This unfortunate snafu meant that the ISA was unable to make good on Senator Zemina Torval’s promise. Reports from those close to the Senator state that Zemina was furious when she learned that Princess Arissa’s agents had seized her shipment. However, in light of the Silver Allied Network incident, the Senator is said to have since seen the wisdom of the investigators' actions. 

In a statement released earlier today, Senator Torval had this to say: 

“It is with deep embarrassment that I must apologise to all those whose businesses were unfortunately affected by the ongoing investigation into the attack on our beloved Emperor.” 

“I have no doubt that Senator Lavigny’s agents acted with the Emperor’s best interests at heart. As do we all. Indeed I urge those hard working loyalists to come and partake in the fantastic selection of discounted produce we have available for sale in Synteini.”” 

“A fresh shipment of Imperial Slaves is currently being prepared for sale at Lagerkvist Gateway. The sale is now officially underway, as promised, but stock levels will remain low until the new shipment arrives in Synteini later this week.”