* GalNet Weekly Security Digest

/10 Nov 3301/

In this weekly report, the latest GalNet data is assembled to present ten minor factions experiencing civil unrest or lockdown in their systems. 

Here are 10 of the 2,036 minor factions in lockdown: 

Amenniya Bureau 

LTT 874 Empire Party 

Maeve Noblement 

Nyanmil Crimson Partnership 

Yerava Crimson Life Commodities 

LTT 6043 Law Party 

Slavisc Crimson Natural Limited 

Bommatsuri Emperor's Grace 

Calhuacan Empire Party 

Rabh Empire Pact 

Lockdowns increase the security rating for a system but also have a negative effect on the system's wealth. Increased bounty hunting activity can shorten the lockdown period. 

Here are 10 of the 2,076 minor factions experiencing civil unrest: 

United Ys Left Party 

Kunggul Ltd 

HIP 73244 Systems 

Forculus Citizen Party 

Xhosag Purple Brothers 

Giabaing Emperor's Grace 

Raiders of HIP 3142 

Union of LHS 1794 Confederation 

Eximo Universal Co 

BPM 72121 State Limited 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

Data is correct at time of publishing.