* GalNet Weekly Security Digest

/24 Nov 3301/

In this weekly report, the latest GalNet data is assembled to present ten minor factions experiencing civil unrest or lockdown in their systems. 

Here are 10 of the 1,685 minor factions in lockdown: 

LTT 6830 Partners 

NLTT 6667 Republic Party 

Partnership of LTT 6710 

Tirfing Natural Organisation 

LHS 3022 Pirates 

Quan Gurus Crimson Public Ltd 

Grovichun Gold Netcoms Inc 

Ross 154 Vision Partners 

Freedom Party of HIP 110205 

Bureau of Zosian Tse 

Lockdowns increase the security rating for a system but also have a negative effect on the system's wealth. Increased bounty hunting activity can shorten the lockdown period. 

Here are 10 of the 1,592 minor factions experiencing civil unrest: 

Citizen Party of LP 542-33 

Order of Juan 

Bureau of Andvaroges Justice Party 

Co-op of Ross 523 

Macalites Democrats 

Aku Gold Family 

Quikindji Independents 

Dakshu Partners 

Mullag Solutions 

Revolutionary Balatu Progressive Party 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

Data is correct at time of publishing.