* GalNet Weekly Security Digest

/30 Jun 3301/

GalNet Weekly Security Digest 
 
In this weekly report the latest GalNet data is assembled to present  ten minor factions experiencing civil unrest or lockdown in their systems (*). 

The following are 10 of the 412 minor factions are in lockdown: 

NLTT 53690 Republic Party 

Yupini Imperial Society 

Calhuacan Empire Party 

Democrats of Chamunda 

Kaliki Citizens' Forum 

Wolf 906 Incorporated 

Vodyanes Emperor's Grace 

Crowfor Vision Services 

Groombridge 1618 Inc 

LTT 14437 Labour 

Lockdowns increase the security rating for a system but also have a negative effect on the system’s wealth. Increased bounty hunting activity can reduce the lockdown period. 

These are 10 of the 848 minor factions are experiencing civil unrest: 

Biko Crimson Council 

Simyr Constitution Party 

Kalana Independents 

Freedom Party of HIP 21778 

Wong Guin Imperial Society 

Freedom Party of LHS 3447 

LFT 78 Patron's Principles 

Crowfor Vision Services 

Nunus Imperial Society 

Aulin Silver United Company 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

* Data is correct at time of publishing.