* Sirius Corporation Begins Analysing Wreckage

/31 Dec 3301/

Last week, the Sirius Corporation launched a search for the remains of the Antares, an innovative passenger liner that disappeared during its maiden voyage in 3251. The initiative piqued the interest of the galactic community, and hundreds of independent pilots took part in the search, scouring the galaxy for remains of the lost ship. 

Today, the Sirius Corporation confirmed that it has received thousands of tonnes of space-borne debris, and that it would soon begin analysing the wreckage to determine its origin. Li Yong-Rui, CEO of Sirius Gov, released a brief statement to the media: 

"The galactic community has responded to our appeal with great enthusiasm, and we are extremely grateful to all those who took part in the search. Now we must analyse the debris to determine whether any of the wreckage delivered to us is from the Antares. We will make a further announcement as soon as our analysis is complete. Our hope is that the fate of the Antares will not remain a mystery much longer."