* GalNet Weekly Conflict Report

/25 Sep 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data (*). 

Here are 10 of the 13,414 minor factions involved in a civil war: 

Cupis Power Corp. 

Workers of Aulis Green Party 

Yab Camalo Systems 

Conservatives of Comanga 

Comanga Universal Co 

HIP 17970 Monarchy 

HIP 17970 Jet Galactic Industry 

LDS 2314 Galactic Co 

LDS 2314 Progressive Party 

Nasaraudi Dominion 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 2,555 minor factions at war: 

Lambda-2 Phoenicis Principles 

Nu Kuni Jet Life Incorporated 

Partnership of LHS 2819 

Confederation of Bendi 

Autocracy of Guguurtuu 

Dimoco Industry 

Dimoco Industry 

Partnership of GD 319 

Syndicate of Timbo 

Pyemmairre Jet Bridge Partners 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

* Data is correct at time of publishing.