* GalNet Weekly Conflict Report

/18 Sep 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data (*). 

Here are 10 of the 13,336 minor factions involved in a civil war: 

LHS 140 Jet Universal Company 

Chamuluma Purple Energy Dev 

Chamuluma Empire Party 

Tsimshis Nationalists 

Tsimshis Gold Public Inc 

Hannonner Ltd 

United Hannonner Republic Party 

Jingones allied 

Purple State Organisation 

Triteia Crimson Council 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 2,579 minor factions at war: 

Mendindui Systems 

Independent Pichanto Alliance 

Napia Organisation 

Wiknatanja Corporation 

Syndicate of Silvantzin 

Republic Party of Kou Mantes 

Revolutionary Hu Jini Progressive Party 

Frey Free 

LTT 12360 Corporation 

Koria Spiritual Mission 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

* Data is correct at time of publishing.