* Aisling’s Angels Challenge the Senator’s Slavers

/01 Apr 3301/

The fortunes of societies least fortunate may finally be changing this week, as Senator Torval has accepted a challenge to go head to head with the Diva Duval to prove once and for all whose position the citizens of the Empire truly support. 

Senator Torval and the Imperial Society will be buying up all the unregulated Slaves they can get their hands on at Lagerkvist Gateway in Synteini.  

Aisling Duval, in association with Stop Slavery Stupid and the Empire Party, will be accepting donations of Imperial Slaves (with the express intention of setting them free) at Mackenzie Relay in Cemiess. 

If Aisling wins, Senator Torval has sworn to set free any Slaves brought to her training centres during the course of the wager.  

If Senator Torval wins, Aisling has agreed to take on a personal contingent of Imperial Slaves for no less than one year. 

Citizens can show their support by signing up to deliver Slaves or Imperial Slaves to the candidate of their choice at the stations mentioned above.