* Race to Center of Galaxy Starts in Sol

/23 Apr 3301/

Pilots from all over civilized space are gathering on Galileo station near planet Earth to begin one of the most ambitious organized rally race ever attempted. Called the Buckyball Run A*, this endurance race challenges commanders to reach the supermassive black hole at the center of our galaxy, Sagittarius A*, in the shortest amount of time possible. This contest is the latest iteration of the popular Buckyball Runs, a series of unsanctioned point-to-point rally races across the galaxy. 

According to Mirana Ortilano, a spokesperson for the event, the choice of Sagittarius A* as the finish line is explained by its significance as the center of the Milky Way galaxy. “It’s a pilgrimage for many, for many different reasons. We’re just helping pilots get there faster.” 

The Buckyball Run A* however differs from the previous competitions as this time the challenge will remain permanently open. To elaborate on this difference, Mirana Ortilano adds: “This is the first long distance endurance challenge. Needless to say, the risk and commitment of the pilots are much greater than in previous runs.” 

Although there is no prize to be won, she insists that “there is a tangible benefit. Commanders who run more than one Buckyball are invariably better pilots.The skills earned will stay with a pilot through his or her entire career.” 

The Buckyball Braben Star-to-Shining-Star Memorial Trophy Dash, simply known as the Buckyball Run, is not endorsed by any official organization. Commanders seeking to participate in this contest are asked to register directly with representatives of the Buckyball Run. 

At the time of broadcast, the galactic record holder for the fastest travel from Galileo station to Sgr A* is commander Anuranium, at the helm of a Faulcon DeLacy Anaconda. 

Léonard Chamberlain - Galnet News Correspondent