* The St. Valentine's Day Regatta

/13 Feb 3301/

Captain Millington, chief of racing operations, has finally announced the details of this year's St. Valentine's Regatta, one of the most prestigious events on the yearly racing calendar. The race, which begins in the Kumbaya system, will see participants follow a gruelling 500ly route that passes through some of the most dangerous areas in the surrounding sectors.   

 "As every pilot knows, St. Valentine's is a gruelling test of nerve and daring, a headlong dash from one side of inhabited space to the other. Many enter, but only one can win. In the 37 years of the race's history (excluding 3284, when it was cancelled due to the civil war) this race has never been won by a pilot with less than exemplary skill. Many winners have gone on to become legends, so join us on the 14th to find out who will be next to ascend to glory amongst the stars." 

Any last minute entrants should contact Commander Kitiara for more information on how to sign up.