* Nascent Starport Targeted by Pirates

/29 Oct 3301/

Last week, the Explorers' Association announced plans to construct a starport in the Pleiades Nebula, and issued an appeal for resources. The response to the request was positive and work on the station superstructure is now underway. With the project poised to enter its second phase, the Explorers' Association has issued another request, this time for assistance of a more practical kind: 

"We were delighted with the response to our appeal, and are thrilled that our dream of building an Ocellus starport in the Pleiades Nebula is finally becoming a reality. Projects of this sort are bound to attract opportunists, however, and unfortunately ours is no exception. Pirates have begun congregating in the Kaushpoos system, preying on the traders and contractors travelling to and from the construction site. Fortunately, we anticipated such an eventuality, and set aside a cash reserve specifically for the reimbursement of bounty hunters. Experienced combat pilots are invited to come to the Kaushpoos system and help deal with these troublemakers. We are also in need of palladium for the next phase of the construction, so those who prefer trade to combat can also contribute to this exciting project." 

Pilots who want to participate in the operation are encouraged to travel to the Kaushpoos system.