* GalNet Weekly Conflict Report

/09 Oct 3301/

This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data. 

Here are 10 of the 21,924 minor factions involved in a civil war: 

Ross 720 Crimson Cartel 

Mundjiga Patrons of Law 

Mariyacoch Solutions 

El Tio Empire Party 

Mariyacoch for Equality 

Dewindji Silver Energy Ind 

Confederation of Dewindji 

Comanes Purple Drug Empire 

Comanes Gold Dynamic Limited 

Democrats of HIP 24777 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 3,374 minor factions at war: 

Codorain Emperor's Grace 

Karnarki Blue General Company 

Komovoy Crimson Posse 

Kivah Resistance 

Saisiyat Patron's Principles 

Okua'gsa Empire Party 

Xerente Blue Transport Comms 

Movement for Ariminimi Labour Union 

Jet Travel Services 

Miskai Incorporated 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

Data is correct at time of publishing.