* Palin Invited to Join Research Group

/27 Sep 3301/

Palin Invited to Join Research Group 
 
Last week saw reports that Professor Ishmael Palin has been forced to cease his research into the so-called anomalous extraterrestrial objects, also known as 'unknown artefacts'. The Voice of Varati has since received a statement from the Canonn Interstellar Research Group, an independent scientific body: 

"We were extremely distressed to read reports that Professor Palin has seen his attempt to research the unknown artefacts forcibly terminated. This is indeed a sad end to a promising beginning, especially given the insights concerning the artefacts the professor had shared with us all. 

"We can only speculate as to why he's been silenced in this way, but the fires of suspicion are spreading rapidly. Someone in a position of power knows far more about these things than the rest of us, but wishes this information to remain secret. The question is – why? 

"The Canonn is going to redouble its efforts to conduct open research into the UAs, as we feel it is in the interests of humanity to learn as much about these mysterious artefacts as we can. We also urge Professor Palin to join us, as we feel it would be in his and his team's best interests. The professor can contact our council at any time, and we will assemble a quick-response team to assure his safety." 

Commander Lord Zoltan, The Voice of Varati