* Week in Review

/15 Apr 3304/

Here are this week’s major stories. 

Princess Aisling Duval’s comments about Aegis have attracted a measure of support. One Imperial senator suggested that Duval had “correctly gauged the mood of the people”, while another commentator suggested that her comments were a sign of maturity. 

Meanwhile, an independent report suggests that piracy has declined since the return of the Thargoids. The author of the report has suggested that the presence of an alien threat has dampened felons’ appetite for preying on fellow humans. Security forces in the Pegasi Sector have refuted these suggestions, however. 

The Empire has announced plans to build a new training centre for novice pilots, and has placed an open order for research materials and mined resources for use in the construction. Once complete, the centre will be home to a state-of-the-art training programme designed to create the next generation of starship pilots. 

In other news, astronomers based in the Sol system may have detected a signal from New Horizons, a space probe launched in 2006 with a mission to study various objects in the Kuiper belt. One of the astronomers responsible for the find gave details of the object’s approximate location, and encouraged explorers to seek it out. 

Finally, a spokesperson for the Atlas Corporation has announced that its campaign to build a megaship has reached a successful conclusion. A parallel initiative from the Privateers Alliance has also achieved its aims, after the organisation’s appeal for commodities was enthusiastically received by the galactic community. 

And those are the main stories this week.