* Thargoid Surveillance Continues

/17 Mar 3304/

According to Aegis, their operation to monitor Thargoid activity in the Pleiades Nebula has already begun to show results.  

Aegis released the following statement on behalf of Admiral Aden Tanner, their chief military liaison: 

“The new Eagle Eye installations are a success, they have identified fluctuations in Thargoid transmissions from a number of planet side structures. With the invaluable help of the members of the Pilots Federation we have identified that the new signals are pointing to locations in human space. We believe these to be identifying the location of potential Thargoid attacks and if this is proved to be the case it will be a huge break through and a validation of our work here. 

We continue to monitor the Thargoid activity using the Eagle Eye installations in the Pleiades and have confirmed reports that the Eagle Eye installations have detected new signals. We urge all available pilots to investigate these changes to see if we can thwart the Thargoids.”