* Presidential Candidates on the Campaign Trail

/27 Sep 3304/

The three candidates for the Alliance presidency have spent much of the past week delivering their campaign messages. 

Incumbent president Gibson Kincaid, who seeks re-election, has demanded radical change to the constitution: 

“To occupy the same league as the other superpowers, we need a single ruler with overall control. I ask that you empower me to lead the Alliance into a new era of strength and unity. That is my vision.” 

An increase in commerce is the focus for entrepreneur Fazia Silva: 

“The current president is driven entirely by ego, as are all career politicians, but it’s money that makes the galaxy go round. Only by investing in trade and industry can the Alliance truly grow.” 

Councillor Elijah Beck has been critical of his rivals’ approach: 

“President Kincaid has little respect for our values, and Ms Silva wants to make it easier for her companies to increase profits. The Alliance deserves a president who puts the wellbeing of its people first, rather than their own selfish goals.” 

The new president of the Alliance will be announced in October.