* Alliance Presidential Gala

/07 Sep 3304/

The Alioth Independents has announced plans to host a gala event in the Alioth system, to officially begin the Alliance presidential election. 

The event will give the as-yet unannounced presidential candidates an opportunity to meet distinguished figures from among the upper echelons of Alliance society. 

Durien Ballas, chairman of Alioth Independents, issued the following statement: 

“Everyone’s heard of President Gibson Kincaid, but the other candidates may not be so well known. This will be their chance to shine. As well as hosting key members of the Alliance Assembly, we can also confirm that Prime Minister Edmund Mahon and three members of the Council of Admirals will be in attendance.” 

To make this a truly spectacular event, the Alioth Independents have placed an open order for Esuseku Caviar, Ceremonial Heike Tea and Live Hecate Sea Worms, promising to reward pilots who deliver these commodities to Smith Landing in the Amber system. The organisation has also placed a kill order on all ships on its wanted list, to ensure that those contributing material to the campaign can do so safely. 

The campaign begins on the 6th of September 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.