* Aisling Duval Assassination Foiled

/03 Aug 3304/

An attempt to assassinate Princess Aisling Duval has been prevented by the Imperial Internal Security Service. 

The attempt occurred in the Zhao system during a fundraising event for Unchain, the anti-slavery charity formed by the princess and campaigner Jarl Toredo.  

Captain Takio Diomedes of the IISS gave this statement: 

“Shortly after the fundraiser began, Princess Duval’s security detail detected explosive charges in key locations across the event centre. We immediately evacuated the building. The explosives, which were of amateur design, were disabled. Forensic analysis is underway to determine their origin.” 

Aisling Duval has not addressed the incident, and is continuing her fundraising duties for Unchain. Her fiancé, Federal Ambassador Jordan Rochester, made this comment: 

“Had the explosives not been found, they would have killed hundreds of innocent people. Aisling and I are grateful to both Federal and Imperial security services, which are working together to ensure our safety. This is a splendid example of inter-power cooperation, which we hope will soon be commonplace.”