* Oktoberfest in Bhagui

/27 Sep 3304/

Citizens of the Bhagui system are attempting to resurrect the ancient Oktoberfest celebration, an annual event based on a centuries-old Earth tradition.  

The scale of the event is unprecedented, and local suppliers are reeling due to the weight of demand. Consequently, Mould Federal Mining Incorporated has volunteered to finance an emergency initiative that will supply the required resources. 

A spokesperson for the company issued the following statement: 

“This will be a party like no other, where people can come together to celebrate life, love and beer. We are honoured to play our part in supporting a festival such as this. Nothing is more important to us than helping our communities.” 

Mould Federal Mining Incorporated has placed an open order for animal meat, fish and beer, promising to reward pilots who deliver these commodities to Leavitt Port in the Bhagui system. The organisation has also placed a kill order on all ships on its wanted list, to ensure that those contributing to the initiative can do so safely. 

The campaign begins on the 27th of September 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.