* Blight Traced to Synthetic Contaminant

/20 Oct 3305/

A tri-superpower group has identified the cause of the blight that has ruined crops on multiple worlds. 

Gino Borstein of the Federal Intelligence Agency delivered a report on behalf of the cross-superpower taskforce: 

“Working with the Rockforth Corporation, we have confirmed that the EX7 fertiliser was deliberately contaminated with a chemical compound shortly after mass production began.” 

“The contaminant has a unique synthetic composition specifically designed to introduce a highly aggressive pathogen that quickly destroys plant matter. Our investigations have uncovered several potential leads, and we expect to identify the contaminant’s point of origin soon.” 

Vox Galactica journalist Adalyn Cross commented: 

“Taken at face value, this seems to absolve Rockforth of causing the blight. But there may yet be culpability issues, considering the company’s cavalier attitude towards regulatory checks. Commentators have pointed to the requests made by the Interstellar Association for Agriculture as evidence that the company placed profit above safety.” 

“The question is: who is behind this attempt to eradicate the food supplies of billions of people? Are we dealing with a terrorist attack on an interstellar scale? Or was this an attempt to ruin Rockforth, perhaps committed by a dangerous corporate rival?” 

In related news, additional cargo checks have been implemented at starports following the blight’s rapid spread. Researchers have theorised that contaminated goods ferried by unsuspecting traders are to blame for introducing the blight to non-agricultural systems.