* Witch Head Planetary Ports Established

/08 Aug 3305/

Humanity’s expansion into the Witch Head Nebula has continued with the introduction of seven planetary ports. 

Six ports now occupy systems surrounding the existing enclave. The Alliance, Federation and Empire have each established two ports, strengthening the presence of their representative factions.  

The seventh port, Cinder Dock, is located in Witch Head Sector DL-Y d17. Professor Alba Tesreau of Aegis Research provided some additional details: 

“A facility managed by the engineer Chloe Sedesi has been installed at Cinder Dock. The engineering blueprints available at the facility offer upgrades to frame shift drives and thrusters.” 

“Following last-minute discussions held aboard the megaship Spirit of Minue, a tech broker and material trader have also agreed to bring their services to the planetary ports. These contacts are located at Bray Landing and Ratchet Hub respectively.” 

“With these new resources available ahead of schedule, we hope to accelerate the ongoing efforts to repair the starports damaged during recent Thargoid assaults. Ezra Point is the first to declare itself fully functional, with all standard services back online.” 

Further installations have been planned over the coming weeks, as migration continues to bring new opportunities and financial investment to the enclave. 

“These achievements are founded on the tireless efforts of many independent pilots,” said Tesreau. “Their bravery and dedication were key factors in securing humanity’s access to meta-alloys within the Witch Head Nebula. On behalf of Aegis, I offer these pilots my deepest gratitude.”