* Week in Review

/05 Jan 3305/

Here are this week’s main stories. 

The theft of a spectacular work of art has soured New Year festivities for thousands of Federal citizens. A colossal holo-sculpture, inspired by the Federal insignia, was due to be unveiled to mark the start of 3305. But upon activation, the image that materialised was a gigantic cat's face, winking repeatedly. 

Meanwhile, Professor Katrien Rook has admitted that her company’s nanomedicines are of Utopian origin, and revealed that the original material was sold to Vitadyne Labs by independent pilots. She offered to return the original cargo to Utopia while insisting that Vitadyne be allowed to continue the manufacture of its derived nanomedicines. Simguru Pranav Antal has insisted that production cease, however. 

In other news, preparations are underway for the second Distant Worlds expedition, which will see a community of explorers cross the galaxy. The expedition will chart a course through the heart of the galaxy, mapping unexplored regions and making new scientific discoveries. It will also involve the construction of a starport dedicated to the study of Sagittarius A*. Nearly four thousand Commanders are expected to take part. 

The isolationist group Nova Imperium has started mustering its forces in the Paresa system, prompting Senator Denton Patreus to issue a statement ordering the ships to disperse. The Imperial Navy must now find a way to quash the threat without it being seen as a massacre of Imperial citizens, which will only fuel further rebellion. 

An open order for military supplies has been placed on behalf of the Federal Navy by the League of Zearla. A parallel operation is being run by Imperial faction the Sirsir Co. Both initiatives begin on the 3rd of January 3305 and will run for one week. 

Finally, an initiative run by Herculean Machines, manufacturer of Duradrive personal computers, has concluded. Multiple shipments of consumer technology, hardware diagnostic sensors and computer components were delivered to the Blatrimpe system, which will be used to fulfil a large order from the Federal Navy. 

And those are the main stories this week.