* The Golconda Generation

/11 Nov 3305/

The culture of the generation ship Golconda has been examined by Professor Elizabeth Perez, head of anthropology at Orion Independent University. 

“Little is known about the Golconda’s origins. There are no intact records of its launch, and the lack of archived blueprints suggests a privately funded colonisation attempt. But there’s no doubt this microcosm of 22nd Century society will have diverged over the past thousand years.” 

“The inhabitants’ language is entirely comprehensible, however, and their social structure is recognisable. Rigid security measures are in evidence, as one would expect from an isolationist culture.” 

“We also know there is a custodian tasked with ensuring the community’s wellbeing, and a chaplain who provides spiritual guidance. All signs point to contentment with – maybe even an addiction to – their spacefaring existence.” 

While audio messages recorded by the Golconda crew are available to the galactic community, only a select handful of individuals representing Upaniklis Vision Incorporated have been permitted to dock with the Golconda. Professor Perez travelled to Upaniklis to speak with them as part of her study. 

“Interviews with those who delivered supplies were fascinating. As one pilot put it: ‘The loading procedures were done at top speed, hardly any comms chatter at all. Nobody on the Golconda entered the cargo bays before we left. I got the impression they were scared stiff of us.’” 

“History shows that isolated cultures can be irrevocably damaged by contact with outsiders. We must ensure that efforts to support the Golconda community do not destroy this unique bubble-colony.”