* Week in Review

/03 Mar 3305/

Here are this week’s main stories. 

The Federal Intelligence Agency has announced that a nuclear weapon known as the Lucifer Device is in the possession of a cult known as the Children of Tothos. The cult is thought to have used information coerced from a financier to locate and raid the research outpost working on the device. 

It has been revealed that Lady Talitha Ambrose’s 300 billion credit fortune was lost as a result of a record high-stakes game of deadlock poker, hosted by the elusive Jokers’ Deck gambling ring. Lady Talitha has been disowned by her family.  

In other news, open conflict in the Drevlyada system has ceased. The battle came to a halt following the summary executions of General Kendrick and Marshal Cooper, whose personal quarrel was responsible for the considerable loss of life among their respective forces. 

Finally, tech company Macrosphere is developing a specialised scanning device to detect illicit interference with personal robots. They have called for the delivery of commodities to the DS Leonis system to aid them in their efforts. 

And those are the main stories this week.