* Aegis Receives Titan Materials for Xeno-Research

/22 Jun 3309/

*Pilots’ Federation ALERT* 

Aegis and Azimuth Biotech have concluded rival campaigns to deliver tissue samples harvested from the Thargoid Titans. 

Titan tissue samples were obtained from the surfaces of the Thargoid capital ships using research limpets and brought back to human space by daring pilots.  

Dr Maximo Fonseca, the Allied scientific liaison to Aegis, delivered a congratulatory message: 

“It takes a special kind of pilot to travel through the Maelstroms and fly across the surfaces of these enormous motherships, but it seems such courage is not in short supply. The samples we received will undergo scientific testing by Allied, Federal and Imperial specialists. We are confident that they will shed light on the Titans’ capabilities and the technologies used in their construction.” 

A parallel campaign by Azimuth Biotech also received deliveries of Titan-based materials, but the number of shipments were notably fewer than those provided to Aegis. Observers have labelled this outcome as encouraging for Aegis’s reputation, with the tri-superpower initiative failing to attract contributors away from private corporate interests in the past. 

Pilots who contributed on behalf of Aegis can collect their rewards from Wiberg Station in the Kioskurber system. Supporters of Azimuth Biotech can do likewise from Stebler City in the Djeriman system.