* Titan Taranis Surrounded

/01 Dec 3309/

The star system Hyades Sector FB-N B7-6, which contains Thargoid Titan Taranis, has been surrounded by human forces. 

Aden Tanner, special advisor to Aegis, provided the following update: 

“Our pilots appear to have pushed Thargoids out of all systems in Titan Taranis’s area of control. It’s taken a huge effort, one which should rightly be recognised as outstanding.  We don’t know for certain what will happen next. But for now, the region is back in humanity’s control.” 

“I strongly urge pilots to keep fighting the Thargoid fleet wherever it is encountered. We must not become complacent - the Thargoids have surprised us before, and have demonstrated the ability to respond when defeat seems inevitable. Those who fought in the HIP 22460 campaign and witnessed the Proteus Wave event will testify to the dangers of assuming the war is won.” 

Systems in the immediate vicinity, such as Hupang, Swahku and HR1737, have initiated repairs to starports which have been abandoned since November 3308. Titan Taranis itself remains largely resistant to conventional assault, and Hyades Sector FB-N B7-6 is still considered a Thargoid stronghold.