* Resources Needed for Thargoid Pulse Neutraliser

/02 May 3309/

*Pilots’ Federation ALERT* 

Aegis has requested materials in the YZ Ceti system to mass-produce a defence for ships entering the Maelstroms. 

Professor Alba Tesreau, head of the tri-superpower agency, announced the initiative at a press conference: 

“Final tests have been conducted on the Thargoid pulse neutraliser, which offers ships a brief window of insulation from the energy wave encountered inside a Maelstrom. Their primary components are based on unclassified relics, which are created by interfacing Guardian artefacts with Thargoid surface sites. Ram Tah and Professor Palin have donated some of their research supplies to this project.” 

“Aegis has been assigned a generous budget to purchase large quantities of cobalt, ion distributors and power converters. These will be used to create a manufacturing and distribution base, making the Thargoid pulse neutraliser commercially available on all rescue megaships.” 

Clement Orbital in the YZ Ceti system will serve as the delivery point for all shipments. Aegis has been authorised to redeem bounty hunting vouchers for all wanted ships in the vicinity, since transporting such valuable materials is likely to attract pirates.  

Representatives from the superpowers and the scientific community congratulated Aegis, while military figures emphasised the importance of finding ways to hinder or destroy the Maelstroms. Rear Admiral Daniel Parry claimed: “This is the most strategically significant breakthrough to date. It will allow us to modify our military tactics based on what is discovered inside the deadly clouds.”