* Caine-Massey Victorious in Corporate Conflict

/13 Apr 3309/

*Pilots’ Federation ALERT* 

Fierce combat in the Tavgi system has resulted in Caine-Massey’s partner Tavgi Blue Life Inc overcoming Torval Mining Ltd resistance. 

The conflict was triggered by the murder of Caine-Massey’s former CEO Johann Fleischer. The assassin was tracked from Mars to the Torval Mining megaship Orchestral Falcon. Circumstantial evidence suggested he was an undercover Imperial agent. 

Philippa Barlow-Lyons, acting CEO of the Caine-Massey corporation, declared: 

“Largely thanks to tremendous support from Federal auxiliaries, the path was cleared for us to take control of the Orchestral Falcon megaship. Only then did Torval Mining Ltd agree to hand over Johann’s killer, rather than risk the loss of its precious vessel. A security team has now delivered him to Federal authorities, where I am sure we will see justice finally served.” 

The Federal Intelligence Agency provided an update to the media from Executive Agent Viola Trask: 

“The man in our custody has been formally arrested and charged with the homicide of Johann Fleischer. All known IDs associated with him are false. Along with the skills he displayed, this suggests that he is a professional assassin. We are working with the Proactive Detection Bureau and the Federal Navy Intelligence Office to broaden the scope of this investigation.” 

Independent pilots who fought on behalf of Tavgi Blue Life Inc during the conflict can collect their rewards from Gordon Enterprise. Despite its defeat, Torval Mining Ltd has also agreed to reimburse its supporters from the Orchestral Falcon.