* Far God Cultists Rescue Seo Jin-ae

/23 Mar 3309/

Seo Jin-ae has arrived safely in the Luyten’s Star system, aboard an Order of the Far God megaship. 

A message was transmitted by the First Apostle of the True Chapters, a proactive sect of the pacifistic religion, from aboard the Testament: 

“The one known to non-believers as Subject D-2 or Seo Jin-ae is sacred to us as the Preceptor – the first human to interpret the will of the Far God. We know her to be a holy emissary, on a personal pilgrimage that exposed her to great danger. I was able to convince my brethren to locate the Preceptor and offer her safe harbour from the heretics.” 

“I beseeched the Preceptor to help us hear the Far God’s divine thoughts as she does, but she informed me that the time was not yet right. She requested a reunion with her friends, who also seek ways to commune with Its heralds. While this insistence on collaborating with the unworthy is curious, we have faith that the Far God guides her path. One day the Preceptor will prepare us for the extinction of all life. It is our honour to serve her.” 

Professor Alba Tesreau gave a statement to the media: 

“I am very grateful to the First Apostle for her help. The Testament’s timely intervention routed several unidentified hostile ships that were hunting Seo Jin-ae. Once she has completed a medical assessment, we hope to learn more about her recent findings.” 

Congressman Tom Gillespie has instructed Aegis not to make formal contact with Far God cultists, whose faith is outlawed in the Federation as well as the Empire. A week’s clemency has been issued in recognition of Seo’s safe return, but the Testament’s presence deep in Federal territory is likely to irritate President Hudson.