* Week in Review

/21 Apr 3305/

Here are this week’s main stories. 

Aegis has entered into a partnership with the engineer Ram Tah to manufacture Guardian-related technology. In a statement, Aegis asserted that its considerable resources would ensure the supply of current and future technology, while clarifying that the XG fighters would remain available from technology brokers. 

Authorities in systems recently attacked by the Thargoids have issued fresh appeals for aid. Admiral Aden Tanner commented that the Thargoids were apparently ignoring key social and military targets, and stated that independent pilots remained humanity’s most effective defence. 

In other news, Taja Gavaris has resigned from her post as CFO of Rackham Capital Investments, amid claims from the Federal Times that it provided information on owner Zachary Rackham to fake FIA operatives. It is thought that the data was used to blackmail Gavaris into stepping down along with several supporters. 

Vodel, manufacturer of the Scarab SRV, has been purchased by Core Dynamics following a downturn in profits. Core Dynamics CEO Jupiter Rochester made a statement confirming that his company would retain Vodel’s core team of designers and engineers. Business analysts are viewing the acquisition as a smart investment. 

Hadrian Duval has declared a non-aggression pact with Princess Aisling Duval. While Hadrian reaffirmed his existing views and his status as a royal exile, he pledged to keep an open mind regarding Nova Imperium’s policies.   

Finally, the Pilots’ Federation has announced the establishment of a permit-controlled area tailored to new pilots. The district offers independent pilots combat exercises and tailored assignments within several designated systems. 

And those are the main stories this week.