* Week in Review

/26 May 3305/

Here are this week’s main stories. 

Conflict has broken out in the Synuefe EN-H d11-96 system following a series of attacks against convoys transporting Guardian commodities. Zende Partners, who recently established a research operation in the system aided by a megaship transport service, have claimed the violence was organised by Segnen Exchange. Both corporations have called on the galactic community to support their respective security campaigns. 

In related news, the prior appeal by Zende Partners to install a technology broker at The Prospect in Synuefe EN-H d11-96 was successful. Guardian modules are now available for purchase at the outpost. 

Prime Minister Edmund Mahon has called on President Gibson Kincaid to step down pending an official inquiry. Mahon has claimed that Kincaid’s unauthorised command of the Alliance’s Zaonce fleet, combined with recent claims of illegal campaign funding, is sufficient to suspend the presidency. Kincaid has dismissed the demands as unconstitutional. 

And finally, commentators have linked ship thief Gan Romero’s dream journal with the statements given by Jasmina Halsey following the disappearance of Starship One. The Rewired network claimed these ‘bodiless voices’ had disregarded the relative standing of these two individuals, and questioned how many others had experienced similar calls. 

And those are the main stories this week.