* Week in Review

/24 Feb 3305/

Here are this week’s main stories. 

The Federal Intelligence Agency has uncovered evidence that Zlota Federal Holdings funded an illegal outpost from which a portable nuclear weapon was recently stolen. It is believed that one of the faction’s members also arranged the theft, which resulted in the massacre of personnel working at the outpost. 

An independent journalist has claimed that Lady Talitha Ambrose is associated with the secretive gambling circle Joker’s Deck. It was proposed that the Ambrose Foundation’s bankruptcy may have followed a poor series of wagers from the missing heiress.  

A supply campaign to increase security in the Merope system has concluded successfully. The Atlas Research Group had arranged for military supplies to be delivered, reassuring the local populace of their ongoing protection from the Thargoid threat. 

In other news, the defence contractor Prax Incorporated has denied accusations that it has failed to comply with industry safety regulations. CEO Lucina Prax dismissed the claims, and stated that her company is working on a new weapons system following a record financial year. 

Finally, a personal rivalry between two military leaders has erupted into open military conflict in the Drevlyada system. The individuals concerned, General Kendrick and Marshal Cooper, have each asked the galactic community to provide them with support. 

And those are the main stories this week.