* Week in Review

/16 Jun 3305/

Here are this week’s main stories. 

President Gibson Kincaid has been removed from office and arrested following a majority impeachment vote. A number of corporate and political figures supporting Kincaid’s plan to assume executive control of the Alliance have also been arrested. Tashmira Silva, who privately funded the investigation uncovering Kincaid’s conspiracy, shared her satisfaction with the news. 

A company who recently purchased 4,000 Imperial slaves for a construction project in the Eotienses system has revealed itself as a slavery emancipation group. The leader of the group, Garrett Kline, declared their affiliation with the radical anti-slavery activists known as Autonomy. The slaves have been freed outside of Port Isabelle, the capital of Eotienses A 3. 

In other news, Evangeline’s Elite Expeditionary Force has announced plans to build a megaship in the Shana Bei system. Archangel Evangeline, the faction’s commander, has invited the galactic community to contribute materials to the undertaking in exchange for financial reward. 

And those are the main stories this week.