* Galactic News: Weekly Expansion Report

/09 Jul 3302/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Thakur Ltd 

Maratians Co-op 

People's Ququve Progressive Party 

Allied Almudji Front 

Hu Jini Patron's Principles 

Hidar Federal Industries 

Keiadir Company 

Picoria Defence Party 

Medusa Galactic Systems 

Li Bestina Ltd 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Limapa Blue State Commodities 

Koraik Dragons 

United Teaka First 

United Pendijin Focus 

He Pola Empire Pact 

Gebel Empire League 

League of George Pantazis Defence Force 

Social LFT 859 Green Party 

Inhers Alliance 

LHS 1380 Empire Assembly 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.