* Galactic News: Weekly Conflict Report

/25 Mar 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Njunmin Allied Partners 

Clan of LP 888-62 

Tsakhmet Purple Mob 

Iksvatan Purple Organisation 

Order of Iksvatan 

Nasaraudi Company 

Nasaraudi Dominion 

Traditional Wiljanherbi League 

Wiljanherbi Jet Crew 

Allied HIP 72223 Nationalists 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

HIP 23627 Crimson Dragons 

Green Party of HIP 23716 

Igbirikan Holdings 

Revolutionary HIP 90539 League 

Purple Electronics Inc 

Brigid Imperial Society 

Barons of HIP 9059 

Workers of HD 13931 Revolutionary Party 

Ross 835 Dynamic Limited 

Workers of Velim People's Party 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.