* Galactic News: Weekly Security Report

/29 Nov 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Brotherhood of LP 98-132 

Potriti Gold Mafia 

Leaders of BD-08 2963 

Barnard's Star Alliance 

WISE 0855-0714 Gold Gang 

Imenhit Limited 

Movement for LHS 463 Values Party 

Xuanduna Silver Allied PLC 

Social LP 510-10 Future 

Tomas Union 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Kini Drug Empire 

Quator Ring 

Bhotho Rats 

Xihe Purple Brothers 

Segoveduwa Empire Party 

Aulin Focus 

Imenhit Limited 

BD+14 2955 Republic Party 

Diaguthivar Dynasty 

Nobles of HIP 69783 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.