* Galactic News: Weekly Security Report

/10 May 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

People's Hadad Union Party 

MCC 858 Organisation 

Jaque 

Nagarans League 

Glaucus PLC 

Workers of Angawal Partnership 

Calarum Drug Empire 

LHS 6007 Gold Energy Limited 

Vetta Order 

V374 Andromedae Peoples Party 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

LTT 911 Allied Limited 

New Chi Orionis Resistance 

Official Kartam Flag 

Labour of 70 Ophiuchi 

Yarigui Liberty Party 

Hel Purple Energy Industry 

CD-79 950 Gold Energy Services 

CD-40 395 Empire League 

Sanda Confederacy 

Coalition of Shesmu 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.