* Galactic News: Weekly Economic Report

/20 Jun 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Official Darkates Freedom Party 

Adeo Vision Industries 

Condovichs Purple Partnership 

Kappa Fornacis Industry 

Kitche Citizens' Forum 

Official Clayakarma Defence Force 

Jeterait Bridge Interstellar 

Jera Nationalists 

Social Megrez Labour 

Kakas Flag 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Procyon Incorporated 

Bunuson Crimson Natural Inc 

Clota Nationalists 

Anototo Gold Family 

HIP 99551 Jet Central Inc 

Mannodava Holdings 

38 Lyncis Drug Empire 

Abukunin Corporation 

78 Ursae Majoris Blue Boys 

Reynhardt IntelliSys 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.