* Galactic News: Weekly Security Report

/07 Jun 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

HR 5082 League	 

Opala Power Commodities 

Latji Coalition 

NLTT 2969 Labour 

Wyrd Jet Power Industries 

Union of V740 Cassiopeiae Future 

Purple Energy Co 

LP 355-51 Dynasty 

Zhang Fei and Co 

HIP 1187 Public Corp. 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Aymifa PLC 

Movement for Kaukamine Labour 

Imenhit Jet Organisation 

LFT 37 Purple Comms Corp. 

Natural Indaol Dominion 

Oho Bajo Co 

Aulin Silver United Company 

Official Khaman Defence Party 

Wyrd Raiders 

LP 726-6 Commodities 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.