* Galactic News: Weekly Conflict Report

/28 Oct 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

HIP 94905 Power Partners 

Nagii Autocracy 

Law Party of LHS 3776 

LHS 3776 Co-operative 

Freedom Party of Sirius 

CD-63 201 Empire Pact 

United Redoneangi Autocracy 

United Teaka First 

Values Party of BD+26 2184 

Sokariang Empire League 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

G 165-13 Commodities 

Manian Co-op 

Partnership of Draualang 

Barons of Ba Nari 

Andhi Liberals 

NLTT 8653 Empire Assembly 

Menero Kimi Empire Group 

Alioth Independents 

BD+03 515 Ltd 

Haritana Dynamic Group 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.