* Galactic News: Weekly Security Report

/03 May 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Tegidana Free 

Arque Commodities 

Social Michael Pantazis Left Party 

Denka Patron's Principles 

Pathan Bridge Systems 

LTT 9156 Empire Party 

Revolutionary LHS 448 Confederation 

East Galaxy Company 

Okinura Democrats 

HR 638 Corp. 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

CD-49 3617 Limited 

Independent Qi Lisu Partnership 

LTT 10918 Jet Natural Industries	 

LP 30-55 Silver Creative Ex 

Nemetes Independents 

Zhangana Empire Assembly 

New 17 Draconis Alliance 

LTT 518 Company 

Li Jungu Dominion 

People's Huichi Resistance 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.