* Galactic News: Weekly Economic Report

/27 Jun 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Federal Congress 

Progressive Party of Abukunin 

Natural LP 811-17 Conservatives 

HIP 117865 Flag	 

Freedom Party of Walka 

Hu Jona Natural Systems 

Liberty Party of Han Xiang 

Jera Social Democrats 

HIP 116460 Patrons of Law 

LTT 700 Front 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Lalande 18115 Natural Network	 

51 Aquilae Gold Creative Systems 

Coringha Galactic Industry 

Coastakal Co-op 

Brani Federal Holdings 

Gang of LHS 512 

Epsilon Indi Party 

Dominion of Sowiio 

Jet Bridge Inc 

Haritana Dynamic Group 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.