* Galactic News: Weekly Conflict Report

/24 Jun 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Aditi Jet Mafia 

Diaguandri Interstellar 

LHS 246 Federal Holdings 

LTT 9846 Limited 

Sudii Commodities 

LHS 449 Central Interstellar 

Fan Cechehe Worker's Party 

Mafia of Chacobog 

Cartel of Diaguandri 

AG+21 1754 Travel PLC 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Alliance of Rusasaei 

BD+47 2112 Holdings 

CE Bootis Purple Dragons 

Alrai Company 

Gliese 58 Inc 

Confederacy of Furbaide 

Baxbakaeris Interstellar 

Abazi Blue Clan 

Dhrutin Purple Cartel 

Varangian Syndicate 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.