* Galactic News: Weekly Conflict Report

/18 Mar 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

HIP 2239 Blue Mafia 

HIP 2239 Silver Universal Sysy 

HIP 62118 Family 

HIP 62118 Universal PLC 

HIP 7705 Life PLC 

Integrated HIP 7705 

Posse of Apiru 

Apiru Domain 

United HR 6797 Democrats 

HR 6797 Brotherhood 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

People's Lalande 27055 Independents 

G 125-30 Comms Organisation 

Revolutionary G 205-47 Confederation 

Hyroku Interstellar 

Justice Party of BD-17 1955 

Kumal Partners 

Ngalakan Free 

Syndicate of Bhumbla 

New Wolf 1398 Confederation 

45 c Bootis Travel Organisation 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.