* Powerplay: Weekly Report

/13 May 3302/

The Powerplay weekly report summarises recent activity in Federal, Imperial, Alliance and Independent spheres of influence. 

The Federation 

Under the pretence of tightening security, President Zachary Hudson's fleets were deployed to the Ravas system where they established a forward operating base. The movement of the Federal ships led to a supply shortage in 26 Ophiuchi, threatening the combat readiness of the fleet stationed there. Only a continued show of Federal might will be enough to ensure law and order prevail. 

Shadow President Felicia Winters focused her Federal aid campaigns on the Kali system, in an attempt to demonstrate how Liberal values will bring a better life to all. Kali has been controlled by the Alliance-aligned Green Party of Kali for some time, but Blue Netcoms Ltd – a Federal corporation – is likely to gain influence with the increased Federal presence. 

The Empire 

Shield of Justice logistics failed to allocate sufficient resources to systems throughout Emperor Arissa Lavigny-Duval's domain, resulting in a loss of control in HIP 47328 and HR 4720. If the Shield of Justice cannot adequately garrison the Emperor's systems, Cook and HIP 10694 will follow suit. 

Princess Aisling Duval's backers acquired controlling stakes in media networks throughout the Conii system this week, and a repeat of last week's successes is now being attempted in Ekono and Kurichime. 

Using her economic connections and vast wealth, Senator Zemina Torval's brokers collected deeds to purchase both land and infrastructure in Jamuxa and Belgitan, allowing her to acquire a controlling interest in both systems. 

Senator Denton Patreus despatched his fleets to Ehi, an anarchic system controlled by the Ehi Silver Rats. Although resistance to the Imperial presence was crushed, budgetary considerations forced Imperial fleets to withdraw. 

The Alliance 

Agents of Prime Minister Edmund Mahon undertook diplomatic missions in BPM 89444, 7 Zeta-2 Lyrae and Alkaid, and successfully forged trade agreements with these systems. Alliance representatives have a busy week ahead of them, with negotiations underway in a total of nine systems. If all nine were to join the Alliance trade network, Prime Minister Mahon would have ties with 106 systems. 

Independents 

Violent insurrections in HIP 103138, He Xian Gu, HIP 90190 and Bakabienil compelled system defence forces to mobilize in an attempt to clean up the corrupt influences seeking to take control. Security forces successfully repulsed the Kumo Crew in the latter three systems, while resistance in HIP 103138 proved too weak. Resistance fighters have paid the inevitable price in blood, and their families have been sold into slavery. 

Sirius Gov CEO Li Yong-Rui leveraged connections with Sirius Corp. to secure investment from the population of Artume. Vast funds were allocated to buy up a controlling interest in the system. Unfortunately, an eleventh-hour financial review revealed the system to be unprofitable, and the acquisition was terminated on Thursday morning. 

Utopian enforcers were unable to liberate the people of 63 G. Capricorni and Kelie from misguided bureaucrats resisting the truth of Utopia. Undeterred, negotiators have sent out feelers for new opportunities to share the vision of Utopia. 

Commander Corrigendum