* Powerplay: Weekly Report

/09 Apr 3302/

The Powerplay Weekly Report summarizes the activities of the galaxy's movers and shakers in the Federation, the Empire, the Alliance, and Independent spheres of influence during the previous week. 

The Federation: 

Federal President Zachary Hudson passed a busy week, guiding the establishment of naval bases in Opet, Annwn, Adan, Ch'iang Fei, Okinura, Delta Pavonis and Gitse. These attempts to expand the Federal powerbase ultimately failed due to serious supply shortages, which also necessitated the withdrawal of Federal fleets from Bandjigali and Lalande 37120. If Federal supply chains cannot meet demands, Phra Mool may also lose the direct protection of the Federal Navy.  

In contrast, Shadow President Winters passed a quiet week on the home front. As a result, a budget surplus will allow her to extend aid to more systems than previously projected during the coming week.  

The Empire: 

Emperor Arissa Lavigny-Duval's staff exposed endemic corruption in Ande, Sawait and Tujil last week. The Emperor has authorized Shield of Justice Patrols to bring criminal elements operating in these systems to justice. 

Princess Aisling Duval secured new supporters in HIP 105391. A fresh batch of sealed contracts are en route to Blod and HIP 95256. Should these systems accept the contracts, the People's Princess will directly influence 60 key systems. 

Many private security vessels within Senator Zemina Torval's domain remained moored this week, with political unrest the lowest it's been in about 15 weeks. The Senator's brokers are currently preparing deeds for the purchase of a key assets in Grudi and HR 6948. 

Senator Denton Patreus' sale of marked arms in Medzistha and Mula Wendes were initially well received, but the movement of the Senator's fleets in both systems has stimulated anti-Imperial sentiments in both systems. System resistance forces have assembled to violently oppose the presence of Patreus' fleets. 

The Alliance: 

The vast trade network of the Alliance of Independent Systems fell into a deep recession this week. Blockades are currently in place in 21 systems with Alliance trade agreements. These blockades  were reportedly put into place by Federation corporations looking to increase their dominance in the galactic market. It is unclear at this time how long this blockades may last, or how the galactic markets will economy will be affected. 

Independents: 

The movements of Archon Delaine and the Kumo were the highlight of independent power activities this week. The conquest of Devata Baru increased the total number of strongholds occupied by the Terror of the Pegasi Sector to 42. The Pirate Lord has incited insurrections in Latugara and Mikunn, and may soon subject these systems to his rule. 

Simguru Pranav Antal's Utopian society and CEO Li Yong Rui's SiriusGov were occupied primarily with administrative tasks. Utopia is at last prepared to send ambassadors abroad to entice systems to join the commune. If all goes well during the coming week, Sirius will finalize a contract with the Chemaku system.