* Galactic News: Weekly Economic Report

/26 Sep 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Panoi Holdings 

Progressive Party of LHS 142 

Anlave First 

LHS 1914 Liberals 

Social Freng Independents 

GR 316 Gold Mob 

Idomatyritu Empire Party 

Jaaka Crimson Advanced Exchange 

Apurui General Co 

Kuanes Resistance 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Partnership of LHS 2819 

Official i Bootis Liberty Party 

Imperial Cartographic Cooperative 

Mbukuravi Crimson Major Dev 

Liberty Party of GD 219 

Partnership of Taribes 

Integrated Shu Babassi 

Federal Defense League	 

Lords of the DarkStar Imperium 

Hagglebeard's Heroes 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.