* Galactic News: Weekly Security Report

/12 Apr 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Cordenses Energy Corp. 

New LHS 3728 Alliance 

People's Ququve Progressive Party 

Ix Chim Jet Life Ltd 

GCRV 1526 Solutions 

Revolutionary Nysa Future 

Manites Electronics Exchange 

Coalition of Onyali 

Future of 12 Persei 

Brestla Silver Vision Network 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Bunuson Crimson Natural Inc 

Peregrina aristocrats 

Future of Arro Naga 

Vennik Fortune Systems 

G 139-50 Blue United Corporation 

BD+35 3145 Company 

Leesti Alliance Union 

Citizen Party of Atayuta 

Blue Federal Partners 

Alacagui Resistance 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.