* Galactic News: Weekly Security Report

/05 Jul 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Amarak Dominion 

Katta Collective 

V989 Cassiopeiae Progressive Party 

Naiti Cartel 

Swaza Gold Crew 

Ethen Life Holdings 

Flousop Silver Fortune Network 

Karadjari Legal Solutions 

CD-66 2585 Jet Travel PLC 

Opala Power Commodities 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Lanciansene Advanced Interstellar 

Kamadhenu Gold Drug Empire 

Copityar Purple Posse 

Independent Hsuanqueno Values Party 

Potriti Public Partners 

Anlave First 

Casmatyas Industry 

Sekhenses Defence Party 

H Puppis Gold Cartel 

Kausalya State Incorporated 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.