* GalNet Weekly Economic Report

/18 Jan 3302/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 12,273 minor factions currently enjoying an economic boom: 

Lords of Ajani 

LHS 3022 Blue Allied Corp. 

Wabayo Silver Power Industry 

Order of Njorth 

Justice Party of Ogowendes 

New Tjindjin Revolutionary Party 

Menusha Empire Consulate 

NLTT 46621 Major Network 

HIP 73244 Systems 

Tamanka Jet Crew 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 694 factions currently experiencing economic bust: 

Sowiio Services 

Miphifa for Equality 

New HIP 43296 Nationalists 

Friends of Wurun 

LP 131-66 Syndicate 

Lords of Feng Du 

Onyayp Silver Family 

Ross 209 Fortune Organisation 

Ixbakah Purple Transport Corp 

Almar Emperor's Grace 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.