* Galactic News: Weekly Expansion Report

/12 Nov 3302/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Crimson State Group 

Zugen Incorporated 

Mutujiali Empire Consulate 

Cegreeth Citizens' Forum 

Ngakwites Empire Consulate 

Chi Eridani Crimson Travel and Co 

Untuatucate Limited 

Idomatyritu Empire Party 

Unified Tagarilocan 

Quince Creative Holdings 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Limapa Blue State Commodities	 

Coquim Industry 

Kokary Liberals 

Revolutionary Heheng Future 

HR 8170 Brotherhood 

Ross 210 Pro-Alliance Party 

Heike Co 

LHS 3598 Transport Group 

Green Party of Lung 

Firdaus Transport Company 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.