* Galactic News: Weekly Economic Report

/07 Mar 3302/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 11,071 minor factions currently enjoying an economic boom: 

Liberty Party of LHS 1788 

Mehen Group 

Barons of Yerava 

Autocracy of StKM 1-1341 

Haush Blue Boys 

Cempsigi Energy Corporation 

Aristocrats of Coriosolite 

HIP 22249 Silver Netcoms PLC 

HIP 16038 Freedom Party 

Traditional Xuane League 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 479 factions currently experiencing economic bust: 

14 i Orionis Jet Camorra 

30 Ceti Purple Clan 

38 Lyncis Drug Empire 

64 Arietis Jet General Solutions 

Abukunin Corporation 

Aegilakan Crimson Gang 

Aleumoxii Purple Brotherhood 

Allied Brani First 

Allied Kamadhenu Nationalists 

Alpha Centauri Advanced Corp. 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.