* Galactic News: Weekly Security Report

/04 Apr 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Revolutionary UGP 145 Free 

Votadini Fortune Holdings 

Dukes of Karsu 

LHS 2637 Dominion 

LTT 17149 Pro-Independent Party 

Barnard's Star Advanced Corp. 

Nationals of NLTT 897 

FF Andromedae Jet Comms Holdings 

Siris Exchange 

LP 282-7 Gold Federal Corp. 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

HIP 24597 Bridge PLC 

Sandagaray United 

Laukang Corp. 

HIP 10716 Vision PLC 

Kuyu Organisation 

Maridwyn Constitution Party 

Ch'u Ti Co 

Nan Sapwe Crew 

Nationals of Algreit 

Social Miola Coalition 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.