* Galactic News: Weekly Security Report

/31 May 3302/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Warnates Free 

Deep Space Clan 

Peregrina aristocrats 

Jangore Power Systems 

FF Andromedae Jet Comms Holdings 

LHS 1004 Nobles 

Daruwutja for Equality 

Unktock Free 

Wolf 54 Legal and Co 

Bacon Cats Arbitration and Transport Services 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Liaedin Patron's Principles 

Pangluya Vision Group 

Orishpucho Crimson Legal Int 

Kudiyu Solutions 

Wen Chang Guardians of Tradition 

Freedom Party of EGM 823 

Doris Vision Systems 

Noblemen of Coras 

Summerland Patron's Party 

LHS 3836 Commodities 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.