* Galactic News: Weekly Conflict Report

/07 Oct 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Xib Cail Co-op 

United Blanquichu Confederation 

Traditional Scylla League 

LTT 15461 Defence Force 

Union of LTT 15461 Liberals 

Matres Nobles 

NLTT 9949 Blue Partnership 

NLTT 9949 Dynasty 

Grabi Power Group 

HR 7756 People's Co-operative 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

LHS 3437 Coalition 

LHS 293 Corp. 

LHS 1393 Services 

Workers of Nebtete Resistance 

Yawa Commodities 

Partnership of Li Cha 

Pleiades Resource Enterprise 

Independents of Lie Yupik 

Black Omega 

Kacomam Empire Group 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.