* Galactic News: Weekly Expansion Report

/10 Dec 3302/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Vanayequi Independents 

Durius Dominion 

HR 8170 Brotherhood 

Djabe Order 

Jaques 

Revolutionary Abazates Democrats 

Partnership of Triviatii 

Lampade Empire Party 

HIP 27371 Empire League 

Wolf 718 Comms Solutions 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Crimson State Group 

Iptera Allied Corp. 

Nahua Citizens' Forum 

Social Bakaduninka Future 

HIP 113100 Silver Ring1 

Firdaus Transport Company 

HIP 114044 Empire Group 

Lao Zi Blue Fortune Corp. 

Peng Dung Jet Creative Network 

Karsha Empire Consulate 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.