* Galactic News: Weekly Economic Report

/29 FEB 3302/

In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit. 

Here are 10 of the 11,826 minor factions currently enjoying an economic boom: 

Reshero Blue Organisation 

Nialfi Dynasty 

United Qi Lieh Constitution Party 

Ndan Blue Galactic Organisation	 

Mob of Mikinn 

Haghole Regulatory State 

Crew of NLTT 2969 

CD-52 187 Empire Consulate 

Cauda Monarchy 

HIP 5178 Nationalists 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction's influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 517 factions currently experiencing economic bust: 

Defence Force of Duamta 

Wadjetese Crimson Raiders 

WISE 1506+7027 Company 

HIP 27609 Brotherhood 

PSPF-LF 2 Purple Family 

Dragons of Kappa Fornacis 

Yun Puggera Crimson Posse 

Mikinn Gold Federal Industries 

Mehuenomici Purple Family 

New Groombridge 1618 Focus 

The wealth of a system diminishes while in bust and the minor faction's influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

Data is correct at time of publishing.