* Galactic News: Weekly Security Digest

/08 Mar 3302/

In this weekly report, the latest GalNet data is assembled to present ten minor factions experiencing civil unrest or lockdown in their systems. 

Here are 10 of the 622 minor factions in lockdown: 

Labour of Ross 151 

Kamchairra Allied Services 

Independent CK Arietis Green Party 

LP 302-22 Jet Electronics Comp 

Strigenses Netcoms Solutions 

Synteini Industries 

Tailtsur Blue General Comms 

HIP 96943 Public Industry 

Labour of 70 Ophiuchi 

Gwiones Travel Exchange 

Lockdowns increase the security rating for a system but also have a negative effect on the system's wealth. Increased bounty hunting activity can shorten the lockdown period. 

Here are 10 of the 624 minor factions experiencing civil unrest: 

47 Ursae Majoris Dynasty 

LP 387-31 allied	 

Liberals of LP 102-320 

League of LHS 529 First 

Liberty Party of Lodhary	 

Arevakimos Hand Gang 

Bureau of Unktock Front 

Union of Malina Confederacy 

Stein 2051 Services 

Nationals of 10 Theta Piscium 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

Data is correct at time of publishing.