* Galactic News: Weekly Health Report

/17 Aug 3302/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

Haita Council 

Moirai Camorra 

Dain Gold Dragons 

Pera Jet Central Ltd 

People's HIP 22006 Republic Party 

Khemaraui Vision Services 

Gurney Slade Dynasty 

Aerial Worker's Party 

CD-79 950 Labour 

United Nangutsu Flag 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

LHS 2265 Liberals 

Elysia Unionists 

Milscothach Network 

LHS 3677 Silver Society 

Kongan Collective 

Kehperi Liberty Party 

B'Titus Partnership 

Natural Aphra Front 

Quillaente Imperial Society 

Paletes Crimson Organisation 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.