* Galactic News: Weekly Expansion Report

/01 Oct 3302/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

LHS 1442 Exchange 

Democrats of Nyoru 

The Gathering 

Apadecavi Blue General Solutions 

Wattunukam Monarchy 

Langjela Blue Galactic Exchange	 

Future of LHS 3877 

BD-20 2665 State Organisation 

Vucasto Patrons of Law 

LHS 1391 Patron's Principles 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

HO Bootis Corporation 

HIP 18527 Silver Energy PLC 

Wayutabal Empire Pact 

Revolutionary Party of Pepper 

Gold Systems Ltd 

HIP 32135 Fortune Network 

Ahanyamwezi Creative Inc 

Biataxo Coalition 

Cao Guatun Empire Consulate 

LTT 1272 Corporation 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.