* Galactic News: Weekly Conflict Report

/12 Aug 3302/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

People's Epsilon Indi Progressive Party 

CD-24 10619 Democrats 

Indrians Interstellar 

Baker Nationalists 

Party of LTT 617 

Ross 193 Network 

Earls of Ross 193 

League of LP 834-42 Party 

Elycoco Purple Mafia 

Elycoco Nationals 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Keries Camorra 

El Confederation 

Himardisc Bureau 

Epsilon Hydri Commodities 

Wolves of Jonai 

Bagai Crimson Mafia 

Guardians of Harmony 

Integrated Caelottixa 

LTT 18486 Jet Energy Company 

Zoryang Gold Mafia 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.