* Galactic News: Weekly Economic Report

/12 Dec 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Colanja Gold Power Services 

Uru Federal Interstellar 

Avan Labour Union 

Wolf 359 Blue Travel Commodities 

Union of Wolf 359 

Coalition of Ngaliba 

Lords of Ngaliba 

Potriti Gold Mafia 

Coquim Industry 

Orrere Ring 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Brotherhood of LP 98-132 

The Pilots Federation 

Alacha Purple Society 

49 Arietis Left Party 

LHS 4031 Ring 

Hotototo Stakeholders 

Gabri Silver General Limited 

HIP 1572 Limited 

Citizen Party of Anotchi 

Lopocareni United 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.