* Galactic News: Weekly Economic Report

/18 Jul 3302/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Anlave First 

Delta Phoenicis Limited 

Fawaol Patrons of Law 

LTT 8856 Gold Brotherhood 

Ambivas Power Partners 

Progressive Party of LTT 15449 

Mokosh Order 

Ho Hsi Corp. 

Constitution Party of Eotienses 

HIP 111755 Commodities 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Prismatic Imperium 

HIP 5623 Crimson United Services 

Social Wolf 397 Progressive Party 

Siluror Group 

Brotherhood of LP 98-132 

Movement for Kambila Labour 

Gang of Aphra 

Lhou Xuang Prison Colony 

Federation Unite! 

HDS 3215 Defence Party 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.