* System Colonisation Equipment Reaches Public Market

/26 Feb 3311/

Brewer Corporation’s much-anticipated system colonisation module and claim management process is now available. 

While colonisation technology has existed for over a millennium, a formal claim and colony establishment process for individuals, communities and minor factions has not previously been available. Analysts consider this a moment of historical significance, as viable colony targets will not be dictated by large corporations or superpower governments. 

CEO Madelyn Teague shared her enthusiasm at a gala event in Minerva, covered by Vox Galactica: 

“The sheer potential of this process is staggering. I’m delighted that the move towards widespread, community-led expansion was so eagerly endorsed by all three superpowers. System colonisation contacts will be available on starports to facilitate the initial work on a claimed system.” 

“This is an exciting time, and I can't wait to see how the next few months unfold. Particularly when the latest additions to Brewer Corporation’s Trailblazer fleet are finished next week. That initiative is still ongoing at Starlace Station, by the way!” 

Those looking to begin a new colony are advised to purchase and prepare a suitable transport vessel, as considerable resources are needed to establish a new port in a claimed system.