* Trading Blocs Compete in Alliance Space

/22 May 3311/

Two significant trading blocs have emerged in Alliance territory following the termination of the Strategic Defence Pact. 

Last week, Sirius Corporation was ordered by the Alliance Assembly to reduce its involvement in Allied military infrastructure and logistics. The move, labelled ‘fascinatingly short-sighted' by Sirius Corp CEO Li Yong-Rui, has triggered an economic rush from Allied corporations to grab the lucrative contracts issued as a result. 

The two trading blocs have somewhat predictably formed around the two leading voices in the Alliance Assembly – Edmund Mahon and Nakato Kaine. 

This marks the latest in a growing series of confrontations between the galaxy's major Powers. In LP 855-34, a contested mining system, Felicia Winters initially secured control by the end of the first week of conflict. However, her success provoked an immediate and forceful response from Yuri Grom's supporters. Conflict zones erupted across the system as Grom's forces pushed back, ultimately overturning Winters' hold and plunging the region back into an unoccupied state. 

Mahon’s supporters aim to reinforce the Prime Minister’s position as leader of the Alliance via high levels of trade. A spokesperson said that Mahon ‘will prevent the economic disaster which Kaine’s Assembly motion has threatened.’ 

Meanwhile, Kaine’s supporters claim that ‘the Sirius pact was paper covering the cracks of Mahon’s economic weakness’, pointed to as evidence of ‘Mahon’s over-reliance on megacorporate support to get things done.’ Kaine herself has always advocated for a political shift towards favouring businesses founded in Alliance member systems. 

Both trade blocs have asked for shipments of Semiconductors, Ceramic Composites and Synthetic Fabrics. 

Trade pilots looking to help Edmund Mahon’s trade bloc can sign up at Bowersox Port in Winiama. 

Trade pilots looking to help Nakato Kaine’s trade bloc can sign up at Fuca Dock in Apura.