* Sandra’s Workshop Asks for Festive Gift Couriers

/15 Dec 3311/

The CEO of leading children’s toy manufacturer Sandra’s Workshop has once again requested help with parcel deliveries. 

Sandra Corrs, the much-loved philanthropist who provides gifts to children across the core systems each year, has made similar requests in previous years. Last year, with the Thargoid invasion just beginning, her courier fleet was loaned out to help refugee evacuation efforts. 

This year a different problem has emerged, as Sandra explained to Vox Galactica: 

“We had Our Dolph’s Routes transport fleet all prepped in advance this year, and with no Thargoids in sight, we thought we would finally have no more hiccups. Oh, how wrong we were! 

This year, we’ve been hacked, and most of our location data for each present was wiped clean. We managed to restore the majority from a backup, but a few presents are going out that we still need help with figuring out where to deliver them.” 

“Even our fleet won’t be able to deliver all our presents on time, given the extra work needed to track down their proper delivery points. We’ll need to rely once again on kind-hearted pilots to volunteer their time and ensure we can brighten the smiles on every child on our list.” 

Pilots willing to help Sandra’s Workshop can collect festive gifts from the Frost Dock outpost in the Njambalba system. The outpost can only provide landing pads for small- and medium-sized vessels. 

A beacon outside Frost Dock holds delivery information, which can be acquired via scan.