* Gutamaya Joins Peers in New Spacecraft Boom

/01 Apr 3311/

Imperial socialites were treated to a tour of Gutamaya’s newest ship, the Imperial Corsair, at an extravagant launch on Capitol in Achenar. 

Gutamaya's event was attended by over a thousand prominent engineers, senators, press members and other notable individuals. Princess Aisling Duval and her cousin, Lucretia Roche-Duval, were the guests of honour. 

Positive reviews of the Imperial Corsair’s public unveiling have been published in several outlets across the Empire already. 

"The Corsair’s specifications showed a promising mix of straight-line speed and large cargo capacity, making it ideal for traders who value efficient travel times,” said Eugine Varrik of the Imperial Herald. “The sleek design employs Gutamaya’s famous curves – attendees were queueing up with their blinks to take the perfect selfie.” 

“What impressed me was the flexibility of the Corsair’s internal components,” said Miyu Azusa for Eye on Achenar. “With the right modules this vessel could adapt well to any pilot profession. All while enjoying a classic Imperial aesthetic, of course!” 

The Imperial Corsair is a medium-sized vessel, notable for being the first multipurpose Gutamaya ship which will be commercially available to pilots outside of the Imperial Navy. It is expected to be available for purchase from shipyards next week.