* Aegis Confirms Seo Jin-ae ‘Hiatus’ from Advisory Role

/03 Jun 3311/

‘Special advisor’ Seo Jin-ae has taken a hiatus from her duties, according to a joint statement released by Aegis. 

Seo has worked with the Aegis initiative since November 3308, providing insight into Thargoid communications thanks to a prototype cortical implant. This implant, inserted while Seo was a captive test subject for the clandestine Project Seraph, allows her to ‘hear’ the Thargoid hive mind. 

The Aegis statement reads as follows: 

“Seo Jin-ae has served Aegis faithfully, providing vital intelligence on Thargoid tactics at considerable physical and mental cost. Following several months of recuperation since a medical emergency last October, Seo has chosen to leave the Aegis facility in Duamta. We wish her all the best and look forward to her safe return.” 

Attached was a message from Seo: 

“After Titan Cocijo exploded in Sol, I had my best night’s sleep in years. No sounds in my head to keep me awake. No images behind my eyes. The Thargoids have left us. Hopefully forever.” 

“I did my best to translate Thargoid thoughts during the war, and people told me this data was useful. But I blame myself for the attack on Sol – the importance of Earth was pulled from my memories, against my will. Alba Tesreau helped me recognise that the implant in my brain was placed there by Salvation, also against my will.” 

“During Project Seraph, 197 people died at Oaken Point in HIP 26176. I am the only survivor of those experiments that Salvation oversaw. Many will say I’m crazy, but I believe Salvation exists beyond his physical death in HIP 22460. I owe it to those 197 souls – and to every victim of his Proteus Wave failure - to find Salvation and shut him down forever.” 

Aegis did not immediately comment when asked if it agrees with Seo’s claims.