* Rackham Funds Exploration Push After HIP 87621 Discovery

/08 Sep 3311/

The mystery surrounding the permit-locked HIP 87621 system continues, with claims of unusual planetary signatures detected via long-range scan. 

Many independent pilots have also reported that all colonisation has been blocked within a 37ly radius, fuelling speculation further. 

While authorities remain tight-lipped, multiple independent analysts claim that at least one world within the system is exhibiting anomalous exobiological readings. These findings have prompted the galaxy’s wealthiest citizen, Zachary Rackham, to offer a lucrative incentive for explorers willing to examine the puzzle via cross-reference. 

Rackham, speaking from his villa on Lake Rackham on Homeland, said: 

“Whatever’s in HIP 87621 is strange enough to have the boffins scratching their heads. Therefore, I propose scouring every corner of the galaxy for similar planets. With enough data, maybe our top scientists will be able to confirm that these anomalous readings are indeed unique to this mysteriously locked system!” 

“Of course, I will be funding this initiative personally. No expense spared for our brave heroes in the science and research fields!” 

 Independent pilots are being asked to locate and conduct full scans of Rocky and High Metal Content worlds, the same classifications as those of interest within the system. The resulting data will be collated and analysed by scientific experts sponsored by Rackham Capital Investments, with results expected to be shared publicly at a later date.