* Pirate Raids Threaten Colonisation Convoys

/07 Aug 3311/

Brewer Corporation has issued an urgent call for assistance following a wave of pirate attacks targeting the Minerva based resupply efforts for the Trailblazer fleet. 

The convoys, which are transporting historically large volumes of aluminium, steel, titanium and CMM composites, have become high-priority targets for opportunistic raids. Security analysts have noted the coordinated nature of the attacks, prompting speculation that elements within a superpower may be providing clandestine support for the attacks. 

A Brewer Corporation spokesperson commented: “The Trailblazer fleet remains a key element in supplying humanity’s expansion into the stars and exploiting the opportunities this affords. It’s disappointing, if not surprising, that some forces would prefer to see that vision of independence fail.” 

Pilots are asked to defend shipping lanes by registering for the initiative at Starlace Station in Minerva and destroying hostile pirate forces found throughout the Minerva system.