* Rumours Spread About HIP 87621 Flora

/20 Nov 3311/

Speculation continues to mount around Radicoida unica, the rare exobiological discovered in HIP 87621. 

Though scientific data remains tightly controlled, fragments of research are circulating among the scientific community opposed to the system’s military lockdown. The source of these research fragments is currently unconfirmed. 

The source suggests that Radicoida unica can remain dormant for centuries and contains an unusually complex bio-chemical compound which may have pharmaceutical applications. 

Critics argue that military control of the enclave is less about protecting a fragile discovery, and more about ensuring exclusive access to what could become the most potent biological discovery in centuries. Since the leaked reports of its unusual bio-chemical make-up, analysts note that military mobilisation has increased across the enclave with some suggesting the region could soon become a flashpoint. 

It remains to be seen whether Radicoida unica's potential merits the powers increasing their military presence in the region surrounding HIP 87621 over the past week. For now, the rumours only deepen the mystery surrounding the galaxy’s most in-demand plant.