* Strategic Order Placed with Brewer Corporation

/14 Oct 3311/

Brewer Corporation has issued an urgent call for mined and manufactured materials to support the rapid construction of multiple new starports. 

Reports have started to circulate among the pilot community of receiving internal communications from their Power contacts specifically calling for their support in relation to securing interests around HIP 87621. 

While the corporation confirmed that the priority was immediate, it declined to identify their clients or intended deployment locations. 

The megacorp’s CEO, Madelyn Teague, explained: 

“Brewer Corporation adheres to the strictest standards of client confidentiality and therefore cannot reveal the origin of this order. What I can assure shareholders is that the sheer scale and limited timeframe of the order is considerable. While this has stressed our reserves of certain stocks, we are taking steps to ensure the order is fulfilled with the level of service Brewer Corporation is famed for.” 

Brewer Corporation has nominated the Trailblazer Dream in the HIP 90578 system as the staging point for this order, and independent pilots are requested to deliver Bromellite or Cobalt to its commodity market. These materials will be sent directly to construction yards and support networks building the modular starport sections.