* Galactic News: Weekly Security Report

/10 Jan 3303/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Morgor Crimson Pirates 

Amahu Labour 

Lokitaka Mu Silver Universal Net 

LHS 535 Silver United Ltd 

Blue Major Exchange 

G 180-18 Jet Society 

United CD-61 6801 Democrats 

Official CD-61 6801 Flag 

People's Bactondinks Future 

Velnians Gold Transport Holdings 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Fusang Fortune Commodities 

Vanayequi Independents  

Uszaa Society 

Quator Ring 

Democrats of BD-02 4304 

Bhotho Rats 

Segoveduwa Empire Party 

Nationalists of Aulin 

Aulin Focus 

Xuanduna Silver Allied PLC 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.