* Galactic News: Weekly Expansion Report

/11 Jun 3303/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Crimson State Group 

United Onduwatya Defence Party 

Sui Xenates Indie Union 

Egovi Dominion 

LTT 3981 Purple Legal Limited 

Traditional Kapperapai Dominion 

Ossian Purple Major Limited 

Marquis du Unuteniling 

Karkinicha Life Network 

Future of Guayambaan 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Limapa Blue State Commodities 

Yenistani Guardians of Tradition 

Alliance of Yemakinni 

Liu Di Imperial Society 

HIP 59486 Purple Ring 

Babai Public Incorporated 

Palliyar Blue Adv Inc 

Igala Gold Public Ltd 

Mbayame Brotherhood 

Orisala Co-operative 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.