* Galactic News: Weekly Economic Report

/08 May 3303/

This report presents the latest data on the economic health of the galaxy’s minor factions. 

Here are the latest factions to experience an economic boom: 

Colanja Gold Power Services 

Social Zaragas Independents 

Brani Federal Holdings 

New 31 Aquilae Green Party 

Ross 754 Labour 

Order of Ethgreze 

Cemiess Commodities 

Kokary Holdings 

Eravate Network 

Panoi Holdings 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction’s influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Coalition of Ngaliba 

League of Orishpucho Movement 

Lopocareni United 

Values Party of Orishpucho 

Orishpucho Crimson Legal Int 

Libanatya Gold Netcoms Comms 

Social HIP 86063 Free 

Aristocrats of G 239-25 

Lidpar Blue Hand Gang 

Confederacy of Hyperion 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction’s influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.