* Galactic News: Weekly Conflict Report

/22 Jul 3303/

This report presents the latest data on conflict among the galaxy’s minor factions. 

Here are the latest factions to experience a civil war: 

LHS 3479 Interstellar 

AG+21 1754 Citizen Party 

Allied FK5 2550 Autocracy 

Liaedin Mafia 

Aymifa Resistance 

Villae Cartel 

Liaedin Electronics PLC 

Zhu Veddi State Limited 

Mob of HIP 7106 

Progressive Party of Ross 210 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

HIP 22145 Gold Mafia 

Coquim Industry 

Crimson State Group 

Co-operative of Yiman 

HIP 96289 Blue Major Inc 

Khakum Prison Colony 

Independents of Jura Lungs 

Democrats of BD-02 4304 

Condovichs Purple Partnership 

Ciguru Republic Party 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.