* Galactic News: Weekly Health Report

/18 Jan 3303/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

HR 3954 Crew 

Koleti Purple Dynamic Co 

LHS 3705 Dominion 

New Mutj Nationalists 

Cenni Corp. 

Sesmu Incorporated 

LPM 26 Pirates 

Workers of Jurokkju Democrats 

Laifang Silver Mob 

Social Hunahau Free 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

HIP 105577 One 

League of Villae 

Delphin Blue Federal PLC 

Junga Interstellar 

Kvenland Services 

HIP 32350 Industries 

Anlave First 

Chicoana Silver Travel Corp. 

HIP 105639 Party 

HIP 9610 Jet Legal Systems 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.