* Galactic News: Weekly Economic Report

/12 Sep 3303/

This report presents the latest data on the economic health of the galaxy’s minor factions. 

Here are the latest factions to experience an economic boom: 

Official Darkates Freedom Party 

Laedla and Co 

Liberty Party of Zeessze 

Union of Wolf 359 Labour 

Coquim Industry 

Opila Ltd 

Kini Drug Empire 

LHS 3479 Interstellar 

Crimson State Group 

Brani Federal Holdings 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction’s influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Quator Ring 

Nationalists of Aulin 

Morgor Crimson Pirates 

Alliance of HIP 13269 

Sauraratec Industries 

38 Lyncis Comms Network 

Hehe Camorra 

Luyten 347-14 Prison Colony 

Revolutionary LP 1-52 Labour 

United Kini Coalition 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction’s influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.