* Galactic News: Alliance Campaign Concludes

/18 Aug 3303/

The Alliance has announced that its new research initiative has been enthusiastically received by the galactic community. Huge quantities of resources were delivered to Neville Horizons over the past week, allowing the Alliance to start constructing a range of instruments expressly designed to analyse Thargoid material. The campaign also received the support of hundreds of independent combat pilots, who took to their ships to protect the spaceways and defend the traders contributing to the initiative. 

As the campaign drew to a close, an Alliance spokesperson said: 

“With the aid of the galactic community, we are now in a position to embark on a detailed study of Thargoid technology and other material. I hasten to add, however, that analysis of this kind is a slow process. The public should not expect profound revelations in the immediate future! But rest assured that our scientists will be working tirelessly to deepen our understanding of the Thargoids.” 

Pilots who contributed to the initiative can now collect their rewards from Neville Horizons in the Kaushpoos system.