* Galactic News: Weekly Security Report

/21 Jun 3303/

This report presents the latest data on the security status of the galaxy’s minor factions. 

Here are the latest factions to experience a lockdown: 

Brotherhood of LP 98-132 

Potriti Gold Mafia 

Bhotho Rats 

Cegreeth Citizens' Forum 

Zeus Jet Organisation 

Traditional Tofana League 

New LTT 14094 Republic Party 

Sirius Free 

Rugabugait Shared 

Chiccan Revolutionary Party 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system’s wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Ngaliba Blue Camorra 

Wolf 359 Blue Travel Commodities 

Green Party of Lung 

United Wat Yu Confederacy 

Nationalists of Aulin 

LHS 535 Silver United Ltd 

League of Chick Ek 

Coalition of Djagana 

Crimson Major Incorporated 

League of Ross 1015 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system’s wealth. Combat missions and activities can bring civil unrest to an end.