* Galactic News: Children of Raxxla Release Report

/03 Feb 3303/

The Children of Raxxla, based in the HR 6421 system, have released an analysis of the exploration data recovered by the galactic community in November last year. 

A spokesperson for the organisation said: 

"There was a vast amount of data to sift through, but our analysis led to some notable discoveries in the Formidine Rift, the Conflux and Hawkin's Gap. There are indications that some kind of covert mission took place in these regions back in the 3270s. So far we have found shipwrecks, beacons and abandoned settlements dating from that time, and logs and records relating to this strange mission." 

"It appears that a fleet was despatched, over 30 years ago, to install a series of beacons in the region. None of the ships returned to their point of origin. It seems that this mission was called 'the Dynasty Project'. The purpose of the mission isn't yet clear, but it was evidently a massive undertaking, particular given the technological limitations of the time – it would have taken a year to complete that journey 30 years ago." 

The spokesperson was asked if the data supported the organisation's belief that Kahina Loren was innocent of the attempted assassination of Admiral Denton Patreus. 

"Unfortunately there is nothing in the data that throws new light on Salomé's demise. But before she was arrested, she indicated that these three sectors were significant. We now believe that that is why she was killed."