* Community Goal: Operation Andronicus

/03 Nov 3303/

With Thargoid attacks becoming a regular occurrence in the Pleiades Nebula, Aegis has leveraged its considerable reserves to fund a military operation in the Pleiades Sector IR-W d1-55. The initiative, dubbed ‘Operation Andronicus’, has been expressly conceived to counter Thargoid aggression in the region. 

Admiral Aden Tanner, Aegis’s chief military liaison, elaborated on the nature of the initiative: 

“Personal-scale craft are particularly effective against Thargoid vessels, not least because of the comparative vulnerability of capital-class ships. I therefore believe the most effective way to address the Thargoid threat – in the short term at least – is a militia of seasoned combat pilots. Aegis has agreed to finance this initiative, which will aim to deliver a strategic blow to the Thargoids in the Pleiades Sector IR-W d1-55.” 

Aegis Research has confirmed that it will reward pilots who hand in Pilots Federation Combat Bonds at The Oracle in the Pleiades Sector IR-W d1-55. 

The operation begins on the 2nd of November 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.