* Galactic News: Weekly Health Report

/04 Jan 3303/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

HIP 73428 Exchange 

HIP 19773 Shared 

HIP 105577 Boys 

HIP 10570 Constitution Party 

Zelano Systems 

Junga Interstellar 

Dulos Defence Party 

Allied Ualapalor League 

Chicoana Silver Travel Corp. 

Auste Gold Ring 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

HIP 105577 One 

HIP 22145 Gold Mafia 

Kvenland Services 

Order of Ethgreze 

Zeaex Flag 

Conservatives of HIP 41984 

Cuicatec Gold Power Co 

Hatmehit Purple Crew 

HIP 9610 Jet Legal Systems 

Traditional Auste Dominion 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.