* Galactic News: Weekly Security Report

/21 Mar 3303/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Zaragas Energy Corp. 

Liaedin Mafia 

WISE 0855-0714 Gold Gang 

Opala Power Commodities 

Lokitaka Mu Silver Universal Net 

Monoto Worker's Party 

Chick Ek Partnership 

Afli Patron's Principles 

G 180-18 Jet Society 

Alliance of HIP 13269 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Kini Drug Empire 

Delta Pavonis Vision Services 

Xihe Purple Brothers 

Segoveduwa Empire Party 

Nationalists of Aulin 

Aulin Focus 

HIP 111755 Commodities 

Nationals of Algreit 

Yenistani Commodities 

Saisiyat Patron's Principles 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.