* Galactic News: Weekly Economic Report

/16 May 3303/

This report presents the latest data on the economic health of the galaxy’s minor factions. 

Here are the latest factions to experience an economic boom: 

Brotherhood of LP 98-132 

Uru Federal Interstellar 

Wolf 359 Blue Travel Commodities 

Union of Wolf 359 Labour 

Ngaliba Blue Camorra 

Potriti Gold Mafia 

Cemiess Commodities 

Coquim Industry 

Orrere Ring 

Eravate Network 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction’s influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Nang Ta-khian Public Co	 

LHS 535 Silver United Ltd 

League of Ross 1015 

Calennero Shared 

Sif League 

League of Orishpucho Movement 

Backlum Gold Allied Organisation 

League of 36 Ursae Majoris 

Lopocareni United 

Taliesin Crimson Fortune Systems 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction’s influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.