* Galactic News: Weekly Security Report

/02 Aug 3303/

This report presents the latest data on the security status of the galaxy’s minor factions. 

Here are the latest factions to experience a lockdown: 

Chamunda Crimson Gang 

Alpha Centauri Gold Brotherhood 

Turnat Justice Party 

Drug Empire of Baga 

Gang of Hsuan Zu 

Earls of LTT 4447 

Bureau of BD+41 2026 Flag 

Lohan Purple Drug Empire 

Movement for Cashis Revolutionary Party 

LTT 2262 Comms Group 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system’s wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Chamunda Crimson Gang 

Kini Drug Empire 

Traditional Auste Dominion 

Akbakshu Crimson Drug Empire 

Umbila Corporation 

Bishankun Comms PLC 

Atroan Gold Gang 

Kwatiles Purple Electronics Ind 

Njambian De Republic Party 

HIP 83247 Stakeholders 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system’s wealth. Combat missions and activities can bring civil unrest to an end.