* Galactic News: Weekly Conflict Report

/08 Jul 3303/

This report presents the latest data on conflict among the galaxy’s minor factions. 

Here are the latest factions to experience a civil war: 

Chamunda Crimson Gang 

Liberty Party of LP 751-1 

Liaedin Mafia 

Partnership of GD 215 

Villae Cartel 

Luyten 674-15 Industries 

Gliese 868 Services 

Liaedin Electronics PLC 

Zhu Veddi State Limited 

Attach Federal and Co 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Order of Ethgreze 

Liberals of Delta Pavonis 

Co-operative of Yiman 

LHS 1387 Jet Mob 

HIP 96289 Blue Major Inc 

Modgud Commodities 

Khakum Prison Colony 

Democrats of BD-02 4304 

Condovichs Purple Partnership 

Momotaro Silver State PLC 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.