* Galactic News: Weekly Health Report

/27 Apr 3303/

This report presents the latest data on health issues among the galaxy’s minor factions. 

Here are the latest factions to experience famine: 

Kvenland Services 

Jamatia Central Corp. 

HIP 32350 Industries 

HIP 14759 Guardians of Tradition 

Traditional Siluruba Autocracy 

New Zeta Tucanae Free 

Marquis du HIP 110867 

HIP 9610 Jet Legal Systems 

Waime Worker's Party 

HIP 115314 aristocrats 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

Labour of Ethgreze 

Eravate Network 

HIP 105577 Boys 

Ololos Drug Empire 

HIP 14759 Guardians of Tradition 

Chet Crimson Society 

HIP 9610 Jet Legal Systems 

Auste Gold Ring 

HR 3954 Crew 

League of Machimi Front 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.