* Galactic News: Weekly Economic Report

/23 Jan 3303/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Colanja Gold Power Services 

Social Zaragas Independents 

New 31 Aquilae Green Party 

HIP 105577 One 

Avan Labour Union 

LTT 377 Purple General Corp. 

Order of Ethgreze 

G 41-14 Purple Travel Solutions 

Ruchbah Industry 

Cemiess Commodities 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

LHS 535 Silver United Ltd 

49 Arietis Left Party 

San Guan Silver Family 

14 Herculis Commodities 

Independent Sopdu Labour 

League of 36 Ursae Majoris 

Surya PLC 

Workers of MCC 445 Green Party 

HIP 1419 Empire Consulate 

Taurina Silver Transport PLC 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.