* Galactic News: Weekly Expansion Report

/06 Aug 3303/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

HIP 13269 Silver Drug Empire 

Koing Dynasty 

Mbayame Domain 

Khruvani Universal Organisation 

Bhisma State Corporation 

Integrated Tzeltal 

Lords of Kamil 

Sun Pin Jet Federal Limited 

United Vitola Unionists 

Yarica Nationalists 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

LHS 3384 Progressive Party 

Eranin Peoples Party 

Matia Empire League 

Ngakwites Empire Consulate 

Revolutionary Abazates Democrats 

Gilyadar Front 

Coalition of Djagana 

HIP 113454 Crew 

Velnians Gold Transport Holdings 

Imset Patron's Principles 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.