* Galactic News: Message Received from Col 70 Sector

/08 Apr 3303/

A weak signal from the Col 70 Sector has been detected by listening posts in both Federal and Imperial space. 

The message is incomplete, but it appears to pertain to some kind of rally point. Meanwhile, Federal and Imperial intelligence services have confirmed that thousands of covert and coded messages have recently been transmitted in the vicinity of the Col 70 Sector. 

"Something is going on out there," said an unidentified member of the Imperial intelligence community. "We think it could be...her." 

A bounty has been issued for Commanders Salomé, Tsu Annabelle Singh and Raan Corsen, but with all three fugitives still at large, the Empire has increased the bounties to five million for Salomé and two million apiece for Singh and Corsen. An Imperial spokesperson reiterated that pilots should not attempt to communicate with these individuals, and should shoot on sight. 

Imperial intelligence services have also placed a bounty on one Commander Yuri Nakamura, referred to as 'Conformist Oboe XX' in an intelligence briefing given to the media. A two- million-credit bounty has been placed on Commander Nakamura.