* Galactic News: Weekly Health Report

/13 Jul 3303/

This report presents the latest data on health issues among the galaxy’s minor factions. 

Here are the latest factions to experience famine: 

HIP 22145 Gold Mafia 

Liberty Party of Zeessze 

Kvenland Services 

Dragons of HIP 1914 

Conservatives of HIP 41984 

Hand Gang of Taunitoq 

Co-operative of HIP 49102 

Parhul Silver Electronics Hldgs 

Constitution Party of Palengue 

Dilga Purple Mob 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

HIP 22145 Gold Mafia 

Liberty Party of Zeessze 

Green Party of HIP 103138 

Kvenland Services 

Marquis du HIP 110867 

Conservatives of HIP 41984 

Modgud Commodities 

Independent HIP 108971 Values Party 

LTT 700 Silver Federal Exchange 

New 31 Aquilae Green Party 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.