* Galactic News: Weekly Economic Report

/24 May 3303/

This report presents the latest data on the economic health of the galaxy’s minor factions. 

Here are the latest factions to experience an economic boom: 

Social Zaragas Independents 

Brani Federal Holdings 

New 31 Aquilae Green Party 

Ross 754 Labour 

Cemiess Commodities 

Kokary Holdings 

Eravate Network 

Zeessze Clan 

Panoi Holdings 

Ross 754 Universal and Co 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction’s influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Brotherhood of LP 98-132 

Lords of Ngaliba 

Nang Ta-khian Public Co 

Aleutes Bureau 

Sif League  

HIP 5700 Empire League 

Backlum Gold Allied Organisation 

G 239-25 Alliance 

League of 36 Ursae Majoris 

Values Party of Orishpucho 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction’s influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.