* Galactic News: Weekly Expansion Report

/18 Jun 3303/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Leschanatya Future 

LTT 3981 Purple Legal Limited 

Earls of Primpo 

Sokaram Citizens of Tradition 

Revolutionary Eluskapu Partnership 

Purple Universal Co 

League of Wikmeang Party 

Kherthaje Collective 

HIP 68936 Partners 

Bactrimpox Gold Society 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Crimson State Group 

HIP 13269 Silver Drug Empire 

Dominion of Skadjalini 

League of HIP 3509 Flag 

HIP 111755 Citizens of Tradition 

Movement for Pienate Labour 

Bodharail Empire Party 

CD-54 9671 Empire Group 

Revolutionary Abazates Democrats 

Flesk Transport Organisation 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.