* Galactic News: Weekly Security Report

/28 Mar 3303/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Wolf 359 Blue Travel Commodities 

Laedla and Co 

People's Changthini for Equality 

WISE 0855-0714 Gold Gang 

Delta Pavonis Vision Services  

Zeus Bureau  

Emperor's Will  

Segoveduwa Empire Party  

Sanna Galactic PLC  

Codorain Network 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Chamunda Crimson Gang  

Zeus Bureau  

Ross 490 Mafia  

Independents of LHS 3262  

Kappa Fornacis Industry  

United Wat Yu Confederacy  

Nationalists of Aulin  

Allied Herthans Front  

Justice Party of Minot 

Kakas Flag 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.