* Galactic News: Weekly Health Report

/06 Jul 3303/

This report presents the latest data on health issues among the galaxy’s minor factions. 

Here are the latest factions to experience famine: 

HIP 10570 Constitution Party 

Dragons of HIP 1914 

Hand Gang of Taunitoq 

Parhul Silver Electronics Hldgs 

LHS 531 Democrats 

Dilga Purple Mob 

Brothers of LHS 199 

Idomatyritu Travel Industries 

Social Gabiko Liberals 

Mob of Nantariates 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak:HIP 22145 Gold Mafia 

HIP 22145 Gold Mafia 

Kvenland Services 

Chamunda Crimson Gang 

Conservatives of HIP 41984 

Hand Gang of Taunitoq 

Co-operative of HIP 49102 

Independent HIP 108971 Values Party 

Attach Federal and Co 

Smethells 119 Blue Life Int 

i Bootis Democrats 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.