* Galactic News: Speculation over Thargoid Ship

/14 Oct 3303/

Some of the galaxy’s leading Thargoid experts have been discussing the discovery of a new alien ship in the HIP 17125 system. 

Images of the crashed vessel reveal that it is structurally distinct from the Thargoid Interceptor, while sharing many superficial similarities. The ship has been classified as a ‘Thargoid Scout’ by the Pilots Federation for the purposes of identification and differentiation. 

Discussing the discovery on the ‘Galaxy Now’ programme, Admiral Aden Tanner, Aegis’s chief military liaison, said: 

“There are clear similarities between this ship and the Interceptor, both of which appear to be made from a quasi-organic material. It would be logical to extrapolate from the ship’s profile that it would be faster and perhaps more manoeuvrable than the Interceptor, but I’d be reluctant to speculate further.” 

Speaking on the same programme, Professor Alba Tesreau, also of Aegis, commented: 

“Recent analysis of the Thargoid shipwreck in the Pleiades Sector AB-W B2-4 system indicates that it is a little over 100 years old, despite being extremely similar, if not identical, to the currently active Thargoid Interceptor. This suggests that Thargoid ship design does not change particularly rapidly, and also that the shipwreck in HIP 17125 could be equally old.”