* Galactic News: Weekly Security Report

/17 Jan 3303/

This report presents the latest data on the security status of the galaxy's minor factions. 

Here are the latest factions to experience a lockdown: 

Brotherhood of LP 98-132 

Wolf 359 Blue Travel Commodities 

Alpha Centauri Gold Brotherhood 

New CD-61 6801 Flag 

Democrats of BD-02 4304 

Bhotho Rats 

Njikan Jet Dynamic Industry 

Oho Bajo Public Holdings 

Confederation of Dahan 

Nationalists of Aulin 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system's wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Brotherhood of LP 98-132 

Ngaliba Blue Camorra 

WISE 0855-0714 Gold Gang 

Partnership of LHS 2819 

i Bootis Central Limited 

Mictlan Empire Assembly 

Ovid Defence Force 

Lokitaka Mu Silver Universal Net 

Blue Major Exchange 

Values Party of Snotock Ek 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system's wealth. Combat missions and activities can bring civil unrest to an end.