* Galactic News: Weekly Conflict Report

/05 Aug 3303/

This report presents the latest data on conflict among the galaxy’s minor factions. 

Here are the latest factions to experience a civil war: 

Zelano Systems 

Kokary Liberals 

Junga Interstellar 

Chamunda Crimson Gang 

LHS 3479 Interstellar 

AG+21 1754 Citizen Party 

Liberty Party of LP 751-1 

Allied FK5 2550 Autocracy 

Liaedin Mafia 

LHS 1387 Jet Mob 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Order of Ethgreze 

Brotherhood of LP 98-132 

Laedla and Co 

Crimson State Group 

Bureau of HIP 1914 Focus 

39 Tauri Interstellar 

Liberals of Delta Pavonis 

HIP 9610 Jet Legal Systems 

Alioth Pro-Alliance Group 

Gitxsan Limited 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.