* GalNet Weekly Conflict Report

/24 Jul 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission takes the latest GalNet data and lists some of the systems currently in conflict around the galaxy. (*). 

These are 10 of the 12,542 minor factions involved in a civil war: 

Uadjarii Nobles 

Wogama Gold Council 

Hou Yangk Partnership 

Nu Tauri Mob 

Traditional LHS 135 Flag 

Labour of LHS 135 

Nurundere Power Limited 

Natural Nurundere First 

Kholevi Labour 

New Kholevi Constitution Party 

Civil wars take place between minor factions in the same system over ownership of major assets like starports. During civil wars only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

The following are 10 of the 2,485 minor factions at war: 

Sitakapa Empire League 

LPM 746 Life Commodities 

Jet Power Exchange 

Fugeirones Shared 

Jang Tun Corp. 

Raiders of Theemetana 

Pirates of LHS 450 

Independent Savaroju Values Party 

Auaker Prison Colony 

Deciani Empire League 

Wars occur when a minor faction invades another star system. For the duration of the conflict standard of living, wealth and security are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges then the war will end in a ceasefire. 

* Data is correct at time of publishing.