* A Week in Powerplay

/11 Dec 3301/

Prime Minister Edmund Mahon finalized trade agreements with the HIP 80243 and Marralteki systems this week, defying economic downtrends seen elsewhere in populated space. Benanekpeno is the latest system to curry favour with the Alliance and attempt to join the list of preferred trade partners. 

President Zachary Hudson did not establish any new bases this week, instead focussing his efforts on strengthening supply lines to existing bases in his jurisdiction. But the growing Federal fleet is seeking new berths in Dhanchu, HIP 44811, and Wolf 287. If these systems become fully operational Federal bases, President Hudson's domain will extend to 82 bases in total. 

Emperor Arissa Lavigny-Duval's domain was relatively peaceful this week, as shield of Justice patrols kept her territory safe. The Emperor has a busy week ahead of her, as six new systems - Gitse, HIP 21991, LTT 1345, Mbutsi, Neites, and Paucates - have requested the protection of her fleets. If these systems join her cause, the Emperor will hold sway over 83 key systems by the end of the week. 

Shadow President Felicia Winters witnessed a surge in opposition this week, but successfully thwarted the challenges with minimal effort. Codorain and Shenggan are currently accepting liberal aid packages, and will likely join the Shadow President's cause within the week. 

Princess Aisling Duval's representatives concluded negotiations with the leaders of Woyo Mina and Kanuket without a consensus being reached. The two systems have formally withdrawn their support from the People's Princess, and the leaders of the Duryampas system have also told Aisling's representatives that they intend to withdraw their support. 

Sirius Gov CEO Li Yong-Rui sold off assets in Tote, GCRV 2743, and NLTT 6655 this week, attempting to hedge against a potential galactic recession. Unfortunately, the economic situation has worsened, and the corporation is facing another week of potential losses. Li Yong-Rui is currently weighing options, and considering divesting additional systems. 

Senator Denton Patreus's fleets countered a surge in enemy activity on the fringes of his territory, nearly setting a record for the distribution of garrison supplies. But despite these efforts, the system of Contiku was left open to attack, and was plunged into turmoil early Thursday morning. 

Senator Zemina Torval's enterprises continue to struggle with the economic crisis, but the sale of Junga's infrastructure enabled Torval to balance her budget this week. With a galactic recession looming, it may become necessary for Torval to divest herself of additional systems to remain profitable. 

Pirate Lord Archon Delaine was repulsed from the remote Alchera system this week, but several new Kumo-sponsored insurrections have emerged. Four Imperial systems – Inmutha, Itzamnets, Kenna and LTT 874 - have been targeted by the Kumo Crew, and with the Imperial Expeditionary Force still reeling from recent defeats, many question whether system defences will hold. 

Simguru Pranav Antal was unsuccessful in opening new enclaves this week, although Utopia currently has the resources to bring several new systems into the fold. Utopian representatives are being sent far and wide in an attempt to extend Utopia's influence throughout inhabited space. 

Commander Corrigendum