* GalNet Weekly Security Digest

/03 Nov 3301/

In this weekly report, the latest GalNet data is assembled to present ten minor factions experiencing civil unrest or lockdown in their systems. 

Here are 10 of the 2,532 minor factions in lockdown: 

Butors Empire Pact 

Movement for Ross 1051 Confederacy 

Munfayl Labour	 

Anemoi Noblement 

Dukes of Milcenu 

Union of Njunmin Free 

Law Party of MCC 858 

LHS 3505 Services 

Bureau of Bodb Dearg Flag 

Kipsigines Vision Partners 

Lockdowns increase the security rating for a system but also have a negative effect on the system's wealth. Increased bounty hunting activity can shorten the lockdown period. 

Here are 10 of the 2,657 minor factions experiencing civil unrest: 

Autocracy of LTT 16764 

Partnership of Skaoismont 

G 69-11 Co-op 

Workers of Skeggiko O Labour 

El Tio Empire Party 

Groombridge 1618 Inc 

Jeterait Bridge Interstellar 

Green Party of HIP 103138 

Lumanans Confederacy 

BPM 590 Creative Network 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

Data is correct at time of publishing.