* GalNet Weekly Conflict Report

/11 Dec 3301/

This weekly transmission lists some of the systems currently in conflict around the galaxy, based on the latest data. 

Here are 10 of the 11,668 minor factions involved in a civil war: 

Aymifa Empire Pact 

Aymifa PLC 

LHS 2995 Federal Co 

Allied LHS 2995 Autocracy 

Nauahtunu aristocrats 

People's Nauahtunu for Equality 

Ba Babal Dominion 

Ba Babal Silver Comms Corp 

Miratres Family 

Miratres Co-operative 

Civil wars involve conflict between minor factions in the same system over ownership of major assets such as starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

Here are 10 of the 5,066 minor factions at war: 

HIP 15376 Gold Creative Limited 

Dominion of HIP 16783 

Arthinn Purple Rats 

Raba Clan 

CD-64 139 Purple State Exchange 

Ruchbah Industry 

Bommatsuri Emperor's Grace 

Alexandrinus Society 

Confederation of Tsetsi 

HR 8474 Industries 

Wars occur when a minor faction invades another star system. For the duration of the conflict, wealth, security and standard of living are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war ends in a ceasefire. 

Data is correct at time of publishing.