* GalNet Weekly Economic Report

/17 Aug 3301/

GalNet Weekly Economic Report 
 
In this weekly digest, the latest GalNet data is compiled to show the economic state of a short list of minor factions and the star systems they inhabit (*). 

Here are 10 of the 3,685 minor factions currently enjoying an economic boom: 

HIP 106213 Independents 

Nan Sapwe Purple Energy PLC 

Bangwa Independents 

Hanneng Labour 

Ekonir Nobles 

Nu Jet Crew 

BPM 28514 Purple Power and Co 

Huokang Silver Universal Ind 

Menambe State Organisation 

Kruger 60 and Co 

When in boom, the wealth of a system is increased for the duration and all trade missions have double the effect on influence. Boom can also positively increase a minor faction’s influence. Boom can be entered by consistent trade profits and completed trade contracts. Booms tend to last until they naturally expire or until some other indicator takes precedence, such as famine. 

Here are 10 of the 50 minor factions experiencing an economic bust: 

Zandu Jet Syndicate 

Democrats of LTT 4961 

Chi Orionis Vision Organisation 

Bodhengue Independents 

Conservatives of Zandu 

Defence Party of Arro Na 

Social Tjakiri Progressive Party 

Caeritis Front 

United CD-58 538 Resistance 

Borasetani Syndicate 

The wealth of a system diminishes while in bust and the minor faction’s influence is also lessened. The effect of trade contracts and actions do not contribute to boom while a bust is active. A bust generally has to run its course before ending. 

* Data is correct at time of publishing