* GalNet Weekly Conflict Report

/03 Jul 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission takes the latest GalNet data and lists some of the systems currently in conflict around the galaxy. (*). 

These are 10 of the 9,977 minor factions involved in a civil war: 

LTT 15899 Jet Netcoms Systems 

Blatuntino Party 

Blatuntino Vision Partners 

Babai Public Incorporated 

Mendego Conservatives 

League of 41 Lambda Hydrae Nationalists 

Natural HIP 118213 Liberty Party 

HIP 112002 Labour 

Vashis Jet Mafia 

Partnership of JoroLiberty Party of LP 751-1 

Revolutionary Party of Nuenets 

Bhotho Rats 

HIP 118169 Freedom Party 

Bactondinks Ring 

Green Party of Lung 

Bactondinks Life Corporation 

Blue Major Exchange 

HIP 118169 Silver Electronics 

Union of Bets 

 Civil wars take place between minor factions in the same system over ownership of major assets like starports. During civil wars only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

* Data is correct at time of publishing.