* GalNet Weekly Security Digest

/22 Dec 3301/

In this weekly report, the latest GalNet data is assembled to present ten minor factions experiencing civil unrest or lockdown in their systems. 

Here are 10 of the 1,626 minor factions in lockdown: 

Revolutionary Party of Wichaimi 

Kinne Blue Boys	 

LP 417-213 Power Solutions 

Lovedu Blue Major Inc 

HIP 15587 Free 

Niamara Electronics Services 

Kui Hsien General Ltd 

Natural Contien Movement 

Renssen Construction 

Barann Fortune Interstellar 

Lockdowns increase the security rating for a system but also have a negative effect on the system's wealth. Increased bounty hunting activity can shorten the lockdown period. 

Here are 10 of the 1,550 minor factions experiencing civil unrest: 

Yimanbin Nationalists 

KUI 11 Crimson Natural Org 

Friggi Independent Union 

UBV 15076 Jet Bridge Partners 

Barons of Coringha 

Orishanann Crimson Allied Net 

BD+47 2391 Silver Central Org 

Ba Xian Netcoms Co 

No Chique Blue Allied Exchange 

Cemiess Purple Council 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

Data is correct at time of publishing.