* GalNet Weekly Conflict Report

/31 Jul 3301/

GalNet Weekly Conflict Report 
 
This weekly transmission takes the latest GalNet data and lists some of the systems currently in conflict around the galaxy. (*). 

These are 10 of the 12,761 minor factions involved in a civil war: 

Ruchbah Progressive Party 

Lwalama Patron's Principles 

Mapor Incorporated 

Independent Khawchuang Green Party 

HR 2283 Independents 

Monarchy of Luyten 205-128 

Confederation of Caelottixa 

Sosoling Alliance 

Hemaskas Corp. 

Arimavante Constitution Party 

Civil wars take place between minor factions in the same system over ownership of major assets like starports. During civil wars, only combat missions and activities help bring the conflict to a resolution. Security, development level and standard of living indicators all drop for the duration of the civil war. 

The following are 10 of the 2,415 minor factions at war: 

Crimson Netcoms Co 

Quiness for Equality 

GQ Virginis General Corporation 

Xolotl and Co 

United Ao Progressive Party 

Revolutionary 16 c Ursae Majoris Future 

HIP 92342 Silver Fortune Comms 

HIP 8564 Corp. 

Irusamara Drug Empire 

Union of Huveang De Alliance 

Wars occur when a minor faction invades another star system. For the duration of the conflict, standard of living, wealth and security are all severely impacted. Combat missions and activities determine who wins the war. If no winner emerges, the war will end in a ceasefire. 

* Data is correct at time of publishing.