* GalNet Weekly Security Digest

/07 Jul 3301/

GalNet Weekly Security Digest 
 
In this weekly report the latest GalNet data is assembled to present  ten minor factions experiencing civil unrest or lockdown in their systems (*). 

The following are 10 of the 390 minor factions are in lockdown: 

Yupini Imperial Society 

Ildaker Prison Colony 

LHS 1852 Empire League 

HIP 82032 Silver Society 

Pirates of Sheela Na Gig 

Green Party of LFT 926 

Natural Contien Movement 

Peckollerci Democrats 

Conservatives of Comanga 

Crowfor Vision Services 

Lockdowns increase the security rating for a system but also have a negative effect on the system’s wealth. Increased bounty hunting activity can reduce the lockdown period. 

These are 10 of the 824 minor factions are experiencing civil unrest: 

Wong Guin Imperial Society 

Freedom Party of LHS 3447 

Irukama Mafia 

Halbangaay Imperial Society 

Ninabin Jet Advanced Inc 

Ngarawe Empire Pact 

Kalana Independents 

Morommo Incorporated 

Pirates of Luyten's Star 

Synteini Industries 

Civil unrest is caused by illegal activity within the system as well completing contracts from more nefarious sources. The wealth rating and standard of living will suffer when a system contains civil unrest. Combat missions and activities can be utilised to end civil unrest. 

* Data is correct at time of publishing.