* Galactic News: Weekly Health Report

/25 Jan 3303/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

Siluruba Purple Transport Ltd 

Traditional Auste Dominion 

HIP 15545 Public Network 

Iptera Allied Corp. 

HIP 9610 Jet Legal Systems 

Hajon Industries 

Gold Travel Ltd 

Hanukuntit Jet Natural Holdings 

Mooramoora Union Party 

Future of Zeta Fornacis 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

League of Villae	 

Zeessze Clan 

Liberty Party of Zeessze 

Delphin Blue Federal PLC 

Kvenland Services 

AG+21 1754 Citizen Party 

HIP 32350 Industries 

United Hatmehit Revolutionary Party 

Traditional Siluruba Autocracy 

HIP 111486 First 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.