* Galactic News: Weekly Security Report

/16 Aug 3303/

This report presents the latest data on the security status of the galaxy’s minor factions. 

Here are the latest factions to experience a lockdown: 

Brotherhood of LP 98-132 

Green Party of Lung 

Alliance of HIP 13269 

Crimson Major Incorporated 

Republic Party of Thraskias 

Revolutionary Kanean Resistance 

HIP 24655 allied 

Monarchy of HIP 24655 

Dhak Union Party 

Opontani Nationals 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system’s wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Apoyota Domain 

Ngadjal Citizens' Forum 

Hecate Creative Industries 

Mafia of Chacobog 

Revolutionary Kanean Resistance 

HIP 29241 Conservatives 

Traditional Hehe Flag 

NLTT 47967 Purple Brotherhood 

Phra Indji Crimson Mob 

Auta Isuang Blue Hand Gang 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system’s wealth. Combat missions and activities can bring civil unrest to an end.