* Galactic News: Weekly Security Report

/17 May 3303/

This report presents the latest data on the security status of the galaxy’s minor factions. 

Here are the latest factions to experience a lockdown: 

Delta Pavonis Vision Services 

WISE 0855-0714 Gold Gang 

Partnership of LHS 2819 

Macame Industries 

G 180-18 Jet Society 

Coalition of Djagana 

Quince Creative Holdings 

New Perktomen Left Party 

Purple Central and Co 

HIP 20916 Left Party 

When a faction experiences a lockdown, the security rating of the system it controls temporarily increases and the system’s wealth temporarily decreases. Bounty hunting activity can shorten the lockdown period. 

Here are the latest factions to experience civil unrest: 

Lords of Ngaliba 

United Wat Yu Confederacy 

Emperor's Will 

Codorain Network 

Morgor Crimson Pirates 

Quince Creative Holdings 

Quince Jet Family 

Nobles of Eoto 

Leaders of Aunochis 

LTT 4716 Jet Netcoms Industry 

Civil unrest is the result of illegal activity. When a faction is affected by civil unrest, the standard of living in the system it controls temporarily decreases, as does the system’s wealth. Combat missions and activities can bring civil unrest to an end.