* Galactic News: Weekly Conflict Report

/17 Feb 3303/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

New 31 Aquilae Green Party 

Zeessze Clan 

Ross 754 Universal and Co 

Fusang Fortune Commodities 

Vanayequi Independents 

Liberty Party of Zeessze 

Alpha Centauri Gold Brotherhood 

Gliese 868 Services 

Luyten 674-15 Industries 

Aymifa Resistance 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Colanja Gold Power Services 

Official Darkates Freedom Party 

Order of Ethgreze 

Coalition of Ngaliba 

Laedla and Co 

The Pilots Federation 

Nuenets Corp. 

Independents of Mildeptu 

HR 3954 Crew 

People's Changthini for Equality 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.