* Galactic News: Weekly Conflict Report

/03 Mar 3303/

This report presents the latest data on conflict among the galaxy's minor factions. 

Here are the latest factions to experience a civil war: 

Vanayequi Independents 

New 31 Aquilae Green Party 

Kini Drug Empire 

Fusang Fortune Commodities 

Luyten 674-15 Industries 

Leesti Alliance Union 

Alpha Centauri Gold Brotherhood 

Aymifa Resistance 

Bodb Den Advanced Network 

Liaedin Electronics PLC 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Limapa Blue State Commodities 

Lords of Ngaliba 

Labour of Ethgreze 

Order of Ethgreze 

Crimson State Group 

Liberty Party of LP 751-1 

Alioth Pro-Alliance Group 

Gandui Empire Group 

Zugen Incorporated 

Nuenets Corp. 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.