* Galactic News: Weekly Expansion Report

/14 Jan 3303/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Kapurri Emperor's Grace 

Betel Free 

Ovid Democrats 

Leschanatya Future 

Dilga Empire Consulate 

HIP 111755 Commodities 

CD-54 9671 Empire Group 

Partnership of Bean 

HIP 117865 Empire Pact 

Tetek Patrons of Law 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Delphin Blue Federal PLC 

HIP 105577 Boys 

Kvenland Services 

HIP 10570 Constitution Party 

Junga Patron's Principles 

United Hatmehit Revolutionary Party 

HIP 15545 Public Network 

Chicoana Silver Travel Corp. 

Auste Gold Ring 

Hand Gang of Taunitoq 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.