* Galactic News: Weekly Conflict Report

/09 Sep 3303/

This report presents the latest data on conflict among the galaxy’s minor factions. 

Here are the latest factions to experience a civil war: 

Left Party of HIP 43845 

Junga Interstellar 

Liberty Party of LP 751-1 

LHS 1387 Jet Mob 

Natural Toolfa Nationalists 

HIP 105639 Party 

Partnership of GD 215 

Dulos Defence Party 

Liaedin Electronics PLC 

Mob of HIP 7106 

Civil wars occur when minor factions compete for control of major assets such as starports. When a faction is involved in a civil war, the standard of living, development level and security level in the system it controls are temporarily reduced. Combat activities can bring a civil war to an end. 

Here are the latest factions to experience war: 

Brotherhood of LP 98-132 

Kokary Liberals 

Liberals of Delta Pavonis 

Chicoana Silver Travel Corp. 

Modgud Commodities 

Green Party of Dulos 

Gitxsan Limited 

Ross 210 Pro-Alliance Party 

i Bootis Democrats 

Njikan Jet Dynamic Industry 

Wars occur when a minor faction invades a star system controlled by another minor faction. For the duration of the war, the standard of living, wealth level and security level in the disputed system are reduced. Combat activity between the two warring factions determines the outcome of the conflict. If neither faction succeeds in dominating the other, the war ends in a ceasefire.