* Galactic News: Weekly Economic Report

/02 Jan 3303/

This report presents the latest data on the economic health of the galaxy's minor factions. 

Here are the latest factions to experience an economic boom: 

Social Zaragas Independents 

New 31 Aquilae Green Party 

Avan Labour Union 

LTT 377 Purple General Corp. 

G 41-14 Purple Travel Solutions 

Labour of Ethgreze 

Brotherhood of LP 98-132 

Laedla and Co 

Liberty Party of Zeessze 

Panoi Holdings 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction's influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

LHS 535 Silver United Ltd 

League of Ross 1015 

Alacha Purple Society 

Dragons of Neche 

HIP 5700 Electronics Co 

Etznabal Silver Boys 

Comanga Crimson Crew 

Union of Aparctias Future 

h Draconis Resistance 

Ys Silver Major Group 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction's influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.