* Galactic News: Weekly Health Report

/11 Jan 3303/

This report presents the latest data on health issues among the galaxy's minor factions. 

Here are the latest factions to experience famine: 

HIP 10570 Constitution Party 

Delphin Blue Federal PLC  

HIP 105577 Boys 

HIP 73428 Exchange 

Kvenland Services 

Junga Patron's Principles 

Bureau of HIP 1914 Focus 

United Hatmehit Revolutionary Party 

Gliese 868 Services 

Hand Gang of Taunitoq 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

HIP 105577 One 

League of Villae 

Kvenland Services 

GCRV 4654 State Interstellar 

Junga Interstellar 

HIP 32350 Industries 

Hatmehit Purple Crew 

Leesti Alliance Union 

HIP 9610 Jet Legal Systems 

Conservatives of HIP 41984 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.