* Galactic News: Weekly Economic Report

/31 May 3303/

This report presents the latest data on the economic health of the galaxy’s minor factions. 

Here are the latest factions to experience an economic boom: 

Limapa Blue State Commodities 

Avan Labour Union 

Wolf 359 Blue Travel Commodities 

Union of Wolf 359 Labour 

Coalition of Ngaliba 

Lords of Ngaliba 

Potriti Gold Mafia 

Cemiess Commodities 

Coquim Industry 

Eravate Network 

Boom is usually the result of consistent trade profit and completed trade contracts. When a faction experiences a boom, the wealth of the system it controls temporarily increases and trade missions completed in the system have double the effect on influence. The faction’s influence may also increase. Booms typically last until they naturally expire. 

Here are the latest factions to experience an economic bust: 

Brotherhood of LP 98-132 

Ngaliba Blue Camorra 

Lords of Ngaliba 

Alpha Centauri Gold Brotherhood 

Movement for 11 Cephei Worker's Party 

Orishpucho Jet Hand Gang 

Aleutes Bureau 

Leaders of Santal 

Indines Commodities 

Bakara Empire Party 

When a faction experiences a bust, the wealth of the system it controls is temporarily reduced and the faction’s influence is temporarily diminished. Trade actions do not contribute to boom while a bust is active. A bust typically has to run its course before ending.