* Galactic News: Weekly Expansion Report

/30 Apr 3303/

This report presents the latest data on expansion and withdrawal among the galaxy's minor factions. 

Here are the latest factions to have expanded into new systems: 

Wolf 217 Left Party 

Nun Major Industry 

HIP 65921 Silver Bridge Systems 

Kelish Citizens' Forum 

Gliese 9106 Partners 

Koing Dynasty 

Union of Laguvii 

Union of Rang Guans Revolutionary Party 

Labour Union of Ahayan 

Future of Guayambaan 

Expansions occur when a minor faction reaches a sufficient level of influence and there is a populated system within striking distance. Expansion is costly, so when a faction expands, the wealth and development level of the system it controls are temporarily reduced. 

Here are the latest factions in withdrawal: 

Order of Ethgreze 

Khodhis Exchange 

HIP 65921 Silver Bridge Systems 

Djinaura Brotherhood 

Syntec Industries 

Purple Universal Co 

Orisala Co-operative 

Future of Guayambaan 

Kamarada Jet Legal Services 

HIP 19198 Future 

Factions are considered to be in withdrawal if their level of influence within a system drops below a certain level. If the faction's influence remains low for a total of five days, the faction must leave the system entirely. If the faction manages to increase its level of influence, it remains in the system.