* Galactic News: Weekly Health Report

/08 Jun 3303/

This report presents the latest data on health issues among the galaxy’s minor factions. 

Here are the latest factions to experience famine: 

Eravate Life Services 

HIP 15545 Gold Syndicate 

HIP 9741 Incorporated 

Hanukuntit Jet Natural Holdings 

Parhul Silver Electronics Hldgs 

Union of HIP 114188 

Values Party of HIP 42408 

HIP 26883 Purple Camorra 

Official i Bootis Liberty Party 

HIP 305 Nationalists 

When a faction is affected by famine the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while a famine is active. Completing food-trade missions can bring a famine to an end. 

Here are the latest factions to experience an outbreak: 

Siluruba Purple Transport Ltd 

Kvenland Services 

Ololos Drug Empire 

Hatmehit Purple Crew 

HR 3954 Crew 

Aonghus Co 

Hajon Industries 

Iptera Allied Corp. 

Auste Gold Ring 

Bodb Den Advanced Network 

When a faction is affected by an outbreak the standard of living in the system it controls temporarily decreases. Combat activity has no effect on influence while an outbreak is active. Completing medicine-supply missions can bring an outbreak to an end.