:PROPERTIES:
:ID:       d5026aa6-6751-497d-880e-517baa2578e6
:END:
#+title: The Consortium
#+filetags: :Codex:

* Faction
[[id:b6cc5a1a-935d-4119-9989-1e916a3e7339][NGC 6188 Sector LC-V c2-28]] (4402.19 ly from Sol)
[[id:d561cb4a-e5b9-4b91-8c6c-3bd52bac3de5][Morgan's Rock]]
* The Consortium
The Consortium is a powerful [[id:3fdaedf3-fedf-47a2-9ee7-e93fcdf08402][crime syndicate]] specialising in
[[id:f1778ba6-dab1-442b-88ff-1dfe06ee2616][blackmail]], [[id:f15a269f-7b00-45dd-a4e5-632d0a37ad95][theft]], and the production and trafficing of [[id:50e5a3c1-a834-4b39-8471-f3fcd22ad82c][illegal
drugs]]. Like most criminal syndicates, it is motivated principally by
profit. It is highly resourceful and well organised, which has in turn
made it extremely successful.

The Consortium started life as an unruly band of brigands and thieves,
no different from thousands of other criminal confederacies. But its
course changed when an ambitious young rogue named Catelyn Voss took
control of the group, sometime in the 3120s, and started aggressively
expanding its operations.

Voss, originally the head of the small-scale drug ring, was guided by
a single principle: criminals were, on the whole, stupid. To
outmanoeuvre one's rivals, all one had to do was outthink them. And
for Voss, gifted with a streak of cold-blooded intellect, this
presented no difficulty.

Propelled by Voss's ambition, the Consortium started supplanting its
opponents, and quickly came to dominate the [[id:1506f0af-2c30-4c8f-aedb-f654114d319d][smuggling]] and
drug-trafficking rackets in its particular area of space. The
Consortium's rivals, unhappy at this development, arranged a
conference. They extended an invitation to Voss, hoping to broker an
agreement what would allow the sector's various criminal enterprises
to peacefully coexist. Voss declined to attend, instead despatching an
envoy bearing a large quantity of [[id:872eaf94-45d6-463c-af9f-36cf2f5cdf8f][Tarach]] spice as a peace offering. In
truth, the cargo canisters were packed with high-yield explosives. No
sooner was the bomb in place then Voss detonated it, annihilating her
rivals in a single stroke.

Voss had realised that her competitors, for all their brutality, were
bound by a simple code of honour. To them, the use of extreme tactics
such as [[id:6b803756-caf9-47f7-b316-31023c2f1ef6][suicide]] bombers was unthinkable. And that gave her a clear
advantage.

In the decades that followed, the Consortium's expansion continued
unopposed, the fear of extreme retaliation keeping rival ciminal
organisations in line. Indeed, potential competitors quickly realised
it was smarter to side with the Coalition than against it, which
allowed the organisation to assimilate dozens of smaller criminal
enterprises.

It is not known if [[id:32dd8281-61d5-418c-aa27-c533207d38d5][Catelyn Voss]] still controls the Consortium, or even
if she is still alive. Some rumours assert that she spent much of her
personal fortune on [[id:ef2cdcaf-36f7-4759-860c-4e489f48226c][progenitor cells]], allowing her to artificially
extend her life and maintain control of her criminal empire. Others
insist that she has retired, and is now living a life of quiet
anonymity in a remote corner of space. Still others opine that Voss is
long dead, and that control of the Consortium passed to one of her
lieutenants many years ago. The [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]] may never be known.

Efforts on the part of law enforcement to topple the Consortium have
been largely unsuccessful. The organisation is now so large that
[[id:f67167ac-8719-4dbe-9f2e-38df44539f3d][Omnipol]] can do little more than chip away at the margins. Ironically,
many of the organisation's most senior figures are believed to have
segued into legitimate business, leading intelligence agencies to
theorise that those at the top of the Consortium may, to all outward
appearance, be law-abiding citizens. Only the capture of the
Consortium's leader - whoever that may be - could threaten its
dominion.
