:PROPERTIES:
:ID:       d8e3667c-3ba1-43aa-bc90-dac719c6d5e7
:END:
#+title: Zemina Torval
#+filetags: :Empire:Alliance:KnowledgeBase:Codex:Individual:

* Zemina Torval

#+begin_quote

  "It is essential to the stability of any state that its members know
  their place, and that all roles are understood to be equally worthy.
  To condemn a slave for being merely a slave is the height of
  stupidity. If your hand were condemn your foot for being a foot,
  clumsy and graceless, pressed repeatedly into the filth, you would do
  well to hack it off at the wrist! Worse, imagine if your eyeballs
  demanded that every other part of you should be an eyeball too, in the
  name equality. What an abomination you would be then."

  "But the truth is that the Federation and the Alliance think in
  exactly this way. You will notice that I wear a beautiful stone upon
  my finger. There is no other like it, which means that only one person
  can wear it. 'But that is unfair!' cries the Federation. 'Why should
  you be the only one to enjoy it?' They would have me smash it to bits
  and give everyone a tiny piece. But then the beautiful stone would be
  gone, and nobody could ever wear it again."

  --- Zemina Torval, midwinter address to the Bitterwood Children, 3303
#+end_quote

Zemina Torval is an Imperial senator with an immense personal fortune
and a redoubtable private army. She is an unapologetic traditionalist,
especially where the Empire's use of slavery is concerned. Her own
wealth derives directly from slavery -- she owns a majority share in
Mastopolos Mining, which depends upon slave labour -- but she draws a
distinction between Imperial slaves, who are owed a duty of care, and
slavery as it is commonly understood. This distinction is held in
contempt elsewhere in the galaxy, however, and the Federation in
particular considers it mere sophistry.

Torval was born and educated at Bitterwood, her palatial family estate
in the Synteini system, alongside a host of siblings and cousins
including members of the Mastopolos dynasty. Among Bitterwood's many
cavernous hallways and vaulted arcades, she learned to fence and play
strategic games as well as mastering higher mathematics, politics and
galactic history. She quickly learned how to play her relatives against
one another to get what she wanted, and the right things to say to an
adult to elicit sympathy. She also learned that carefully laid plans,
rather than rash action, were the most efficient way to settle a grudge.

It was at Bitterwood that Torval met the slave Metropa Laish, who soon
became a mother figure, the young Torval having been starved of parental
affection. Commentators have suggested that Torval's relationship with
Laish underpins the senator's passionate defence of Imperial slavery.

Torval's chief interests are industry and education. As well as
sponsoring schools across Imperial space, she runs a private academy at
Bitterwood for the Empire's most promising children. The selection
process is rigorous but meritocratic, with candidates chosen on the
grounds of ability rather than background. Even Imperial slaves can
apply, although they cannot enrol while they are still slaves, so
arrangements are sometimes made to purchase a candidate's freedom. Every
year, a fresh crop of Torval's Bitterwood Children goes out into the
Empire to assume positions of leadership in the military and in
industry.

