:PROPERTIES:
:ID:       d56d0a6d-142a-4110-9c9a-235df02a99e0
:END:
#+title: The Federation
#+filetags: :Federation:Empire:Alliance:Thargoid:KnowledgeBase:Codex:

* The Federation
** Introduction
#+begin_quote
"For I dipped into the future, far as human eye could see, 
Saw the Vision of the world, and all the wonder that would be.

Saw the heavens fill with commerce, argosies of magic sails, 
Pilots of the purple twilight dropping down with costly bales...

Till the war-drum throbbed no longer, and the battle-flags were furled
In Parliament of man, the Federation of the world."

/Alfred, Lord Tennyson, Locksley Hall (1835)/
#+end_quote

#+begin_quote
"How, then, to attempt the impossible task of summining up the
Federation? We are the ones who draw the lines. Our forefathers, who
lived through the bitter anguish of global wars, drew a line under
them and declares: no more. We enshrined the rights of all citizens in
our Constitution, underlined them, and signed. WE plotted the lines
that first linked the star systems, bringing humanity to the shores of
new worlds, opening the way to interstellar trade. And when humanity
itself, in the exuberence of youth, threatened the delicate balance of
alien life, again we drew a line; thus far let us lawfully tread, and
no further."

/[[id:77091a28-dc28-405d-bb97-c32a1aecdd33][Isaac Gellan]], Federation President, inaugural speech (2862)/
#+end_quote

The Federation is the oldest of the galaxy's three superpowers, a vast
geopolitical entity reaching out from the core system of [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]] and
encompassing a road socio-economic spectrum. Among the myriad Federal
star systems one can find extraordinary wealth, crushing poverty, and
everything in between.

By contrast with the Empire, which offers a social safety net in the
form of state-sanctioned slavery, the poorest members of Federal
society have no safeguards, and no way out. For them, life on the
graffiti-stained streets is inescapable, and the gulf between their
lives and those of the super-rich could not be more insurmountable.

At its best, the Federation embodies the values of its founding
nations - democracy, industry and liberty - but Federal society can
also be competitive and unforgiving. Corporations wield too much
power, politicians are often corrupt, and a sink-or-swim ethos
prevails.

** History
*** The nations of Earth united in the aftermath of war.
After the devastation of World War III, the United States of the
Americas rose to become the planet's dominant nation. Over the years
it gradually brought the other nations of the world under its
aegis. Called at first 'The Federation of the USA', the expanding
democracy was soon given the less exclusive title of The Federation.

*** Humanity reached for the stars.
When faster-than-light travel became a reality in the 22nd century,
several terreestrial corporations competed fiercely to establish the
first human colony in a new star system. Tau Ceti was the first system
to be colonized, followed by Delta Pavonis, Beta Hydri, and Altair. In
their wake there followed a wild scramble of pionnering expeditions
and colonial ventures.

*** The first colony rebelled.
The year 2161 saw a dispute between the colony of Tau Ceti 3 and the
Federation authority, centered on the colonists' repeated refusal to
limit the damage they were inflicting on the alien ecosystem. Earth
dispatched a fleet with orders to revoke the colony's charter. The
colony responded by declaring independence.

A military stalemate led a gruding compromise and the Federal Accord
resulted, granding the system rights and represenation along with
concomitant duties. The Federation, born on Earth, was now an
association of star systems.

*** The Birthright Wars gave corporations preferential treatment.
Starting in 2621, a group of corporations subjected the Federal
government to over a century of unrelenting pressure. They demanded
the right to buy up under-exploited colonial land from its hereditary
owners.

Under the terms of the original charters, the land belonged to the
colonists and their descendants regardless of their ability to mine,
farm or otherwise exploit it, maning that immense resources were lying
untapped. The corporations argued that with the machinery, workforce
and fleets at their disposal they could tap those resources; the
Federation would be enriched, the original owners would be
compensated, and everyone would be satisfied.

The Federation bowed to pressure and allowed compulsory purchase of
the families' land, albiet for far less than the expected
sums. Outrage, rebellion and - in one case - the defiant resettlement
of an entire colony resulted.

The Federations' detractors often point to this dark episode as
indicative of its true nature: a mere administrative puppet bent to
the will of rapacious corporations.

** Society
*** A federated democracy.
The Federation's legislative body is made up of congressmen, elected to represent their system or state. Apart from the oldest core systems such as Sol, which encompass multiple states, each star system within the Federation is considered a single state.

New colonies do not qualify for full Federation membership until and unless they fulfill the development objectives set down for them. With self-reliance comes representation. 

The Federal Government has its seat on Mars, which was terraformed in 2286. Congress was moved there from Earth in the early third millennium.

The executive branch is headed by an elected President with a fixed eight-year term.

*** Constitutional rights obtain.
The soverign rights of all individuals are enshrined in the Constitution, which is a modified and streamlined version of the US Constitution, originally codified in the 18th Century. The right to liberty underscores the absolute ban on slavery within the Federation, and is a point of contention with the Empire.

*** Corporate interests dominate.
Although the Federation is loudly and proudly democratic, corporations still exercise tremendous influence over the democratic process, shaping citizen's choises through celebrity endorsement, lobbying and occasionally outright corruption.

The government is notoriously reluctant to curb corporate activity; the typical question in Congress is not whether a given policy will favour corporate interests, but which ones it will favour. Competition between corporations for Congress support can lead to a deadlock in the government

** Military
*** The Federal Navy.
The Federation has maintained a battle fleet since the days of the first Federal colony, which was established in the Tau Ceti system. Its official mandate is to protect shipping and defend the borders of Federal space, but it has also frequently been deployed against the Federation's own rebellious citizens.

At first the Federation's member systems were required to contribute the required ships, making the mustering process a cumbersome one. But following the Birthright Wars, corporations were chartered to produce centralised fleets, which made for a far more efficient system.

The Naval shipyards and training academy were originally based in the Anlave system, but the academy has since been moved to the custom world of Navy Central in Eta Cassiopaeia.

The Navy benefited from massive investement following the forced sell-off of colonial land in the Birthright Wars, during which it was wielded against the colonists in a bitterly resented move. When the Thargoids were first encounted in 2849, the Navy was boosted once again in fear of the alien threat, and a further bolstering followed in 2867 in the aftermath of what were believed to be Thargoid attacks.

Governor [[id:9492a08d-0edc-46db-969f-dc8670665346][Raul Santorini]] championed heavy cuts to the Navy budget in 3022, which were not reversed until President Varian Scott came to power in 3144. Scott talked up the Thargoid threat, again increasing funding to the Navy and removing the requirement for military actions to be approved by Congressional vote.

*** Land forces.
In addition to the rank and file, the Federation still enjoys the loyal service of special military divisions such as the Gurkha Regiment, who have served since the days of Earth. Keeping up long-standing traditions such as this is an important link to the past for Federal citizens.

** Culture and Values
*** If you want to eat, you have to work.
The Federation has no room for freeloaders. It has nurtured the core
'frontier values' of self-reliance and entrepreneurship since its
inception, and respects the self-made citizen.

This insistence upon paying your way and pulling your weight also
applied, notoriously, to the process whereby new colonies were
established. Until a given colony was able to fulfill the development
goals set down for it by the Federation, it could only ever be a
dependency with no voice of its own. Given that the Federation's
assigned goals could vary wildly from one colony to the next, this
requirement frequently chafed with the colonists.

While the Federatioin maintained that it was simply exercising
flexibility, since no two worlds were the same, some colonies were
tempted away to the Empire by the promise of being recognised as
soverign without having to jump through arbitrary hoops.

*** Corporations took humanity into space.
The Federation has never forgotten the role played by private
enterprise in the initial migration from Earth. Corporations enjoy
substantial freedom and influence under the Federation, so much so
that it often seems they are the powers truly running the show.

Federal citizens can be as passionately loyal to their corporations as
they would be to a family or clan group, and it is common for
successive generations of a given family to serve the same corporation

*** Harvest the limitless riches of space, but respect nonhuman life.
The Federation and the Empire have hugely differing views on the primacy of humanity in the cosmos. While the Federation insists that its colonies treat indigenous nonhuman life with care, the Empire typically takes a more human-centric approach. This attitude has allowed the Empire to poach several developing Federation colonies who felt themselves hamstrung by ecological regulations.

*** Wealth is freedom.
Federal citizens actively embrace corporate culture, expressing their identity through brand choices and media consumption.

***Diplomatic

*** The Empire.
In 2292, a group fo colonists established a settlement on Achenar 6d, chose for its remoteness. The original intent was merely to live free from interference, but autocrat Hensen Duval rapidly took control of the colony and had himself proclaimed Emperor. The Federation attempted military reprisals, partly due to the nascent Empire's insistence on independence, but faced a harder fight than they had expected and were held at bay. Over the next fifty years, the Empire expanded to many other worlds.

The Federation's relationship with the Empire is one of entrenched mistrust stemming from irreconcilable ideological differences, mollified somewhat by the corporations, which have a presence in both territories and thus act as a stabilising influence. Outright hostilities between the powers, when they occur, are usually conducted through proxy forces.

*** The Alliance.
In 3228, the Federally aligned corporations supplying the Alioth system attempted to raise their prices, leading to a citizen rebellion. Several independent systems assisted the rebels.

Neither galactic superpower was able to suppress the revolt; the Empire was too far away to intervene effectively, whereas the Federation was hampered by unexpected public sympathy for the rebels.

The Alliance of Independent Systems, founded on Alioth in 3230, drew in new members for the next 20 years; some were already independent, while others defected from the Federation or Empire.

In order to keep more worlds from defecting, the Federation was forced to reform the process whereby colonies could achieve full Federal membership. So far, it has only managed to slow the loss of worlds to the Alliance and has yet to tempt any back.
