:PROPERTIES:
:ID:       85b241ae-7c33-4613-b06b-03ac7360b4fc
:END:
#+title: Sirius Corporation: The Fourth Superpower?
#+filetags: :3307:Federation:Empire:Alliance:Thargoid:galnet:

* [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation: The Fourth Superpower?

/15 Jun 3307/

The galaxy’s largest megacorporation is continuing to influence the political arena and affect billions of lives. 

A review was published by [[id:d4e49144-20cb-468e-b3ce-f594c2b5bf13][Marlon Royce]], business analyst for Vox Galactica: 

“With its own government, laws and naval fleet, it’s not surprising that [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation is occasionally referred to as ‘the fourth superpower’. That now seems to be its actual goal, as its impact upon interstellar politics increases.” 

“When [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation resettled the Marlinist refugees in their own colony systems, it averted war between the Empire and the Federation. But this seemingly altruistic move enabled CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] to claim political neutrality, gaining public support to host the Galactic Summit in the Sirius system.” 

“That success was undermined by the controversy of granting diplomatic status to pirate warlord [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]. Rumours of secret business dealings were reinforced when [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] subsidiaries appeared alongside the Kumo Crew’s new starports.” 

“High-level agreements were also made with the Alliance, with [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Atmospherics aiding colonisation of the Coalsack Nebula. But some believe that its project to terraform ammonia worlds brought retaliatory strikes from the Thargoids and enormous casualties.” 

“The latest news is of a collaboration with technology brokers to make a previously limited ship module commercially available. Is this a shrewd business decision, or part of [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation’s strategy of political dominance?”
