:PROPERTIES:
:ID:       5e9a4e6a-0673-4b0a-9472-cb282751e553
:END:
#+title: Far God Cult Attacked
#+filetags: :3304:galnet:

* Far God Cult Attacked

/20 Jul 3304/

There has been a spate of violence against the Thargoid-worshipping Far God cult, resulting in dozens of deaths and hundreds of injuries. 

Since the Church of Eternal Void declared war against the sect, its members have compelled citizens to attack Far God believers in many systems. Several of the sect’s places of worship have been firebombed.  

The Far God cultists have offered no resistance to the aggression, and have even refused to leave burning hive-chapels. 

Cardinal Hieronymous, representing the Church of Eternal Void, addressed a large crowd: 

“Our loyal followers are performing the Guardians’ righteous work! Those who serve the Thargoid demons are demons themselves, and we must cast them out with fire and fury.” 

A vocal campaigner against the Far God sect, Juanita Bishop, told the media: 

“It might not be pretty, but what’s happening now is no different to what our brave pilots are doing out there in space – defending their own kind. We will do whatever it takes to protect our children from these monsters.” 

Local security forces have been slow to respond to the incidents, and few arrests have been made. Councillor Quinn Damico commented: 

“The lack of an immediate clampdown is inexcusable. The Church is inciting criminal acts and persecuting a legally registered religion. I call upon the authorities to bring the full force of the law against any vigilante behaviour.”
