:PROPERTIES:
:ID:       3c9b3ac6-2b3c-406f-b0de-dc02f3a1e9c1
:END:
#+title: Takada
#+filetags: :Corporation:
* Takada

#+begin_quote

  "Harmonious by design."

  --- Source
#+end_quote

The dynastic corporation Takada started life in 3223 as a haulage
corporation. Presided over by patriarch [[id:64396ad5-a889-428b-ae1d-5d3416af25a6][Hideo Takada]], the company
gobbled up market share by transporting high-risk shipments at a
fraction of competitor prices. Instead of hiring external security as
escorts, Takada chose to make a long-term investment by recruiting and
training its own.

Within five years, the company's last major competitor had vacated the
area increasingly known as 'Takada space'; by 3244 the conglomerate had
a vice grip on the local economy, with everything from starports to
planetary colonies bearing its name.

The company's prominence came at a cost, however, with Takada shipments
persistently targeted by pirate gangs. Rather than relying on
beleaguered system security forces, Takada poured further funds into its
private defence team, only to find that mass-market firearms did not
meet its needs.

Convinced Takada could do better, Hideo's heir [[id:40474008-e96b-46f5-a893-aaad56305830][Ronan Takada]] tasked
engineers with developing concepts for personal laser weapons. He also
hired several industry veterans, including former [[id:622aa817-7abf-4605-b524-e99d52b6bbc8][Ross Projectiles]]
designer [[id:27c5fabd-9b60-4594-914d-ef1d8ece70d6][Edward Le]]. The results exceeded even Ronan's lofty
expectations.

Sensing an opportunity for additional revenue, [[id:40474008-e96b-46f5-a893-aaad56305830][Ronan Takada]] quietly
began taking weapon orders from local factions, using an abandoned
Takada facility for production. When order volume dramatically
increased, Ronan was compelled to legitimise his experiment.

Assembling an audience of journalists, engineers and government
representatives, Ronan declared it was time to give consumers "the same
opportunities for personal defence enjoyed by the Takada corporation".

The announcement marked Takada's official shift into the defence sector,
with the company shuttering its former operations to focus exclusively
on arms production. Although [[id:64396ad5-a889-428b-ae1d-5d3416af25a6][Hideo Takada]] initially disapproved of the
shift---going so far as to call his son 'reckless'---he later
acknowledged that the defence market was more profitable for Takada than
haulage had ever been.
