:PROPERTIES:
:ID:       a0859087-958c-4c46-9f8b-f0f8583637db
:END:
#+title: Community Goal: Lave Radio Appeals for Blood Crystals
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio Appeals for Blood Crystals

/03 Mar 3302/

The [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio Network has launched a campaign to construct a new transmitter relay in the [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] system. John Stabler, Head of Operations at Lave Station, said: 

"We were performing scheduled maintenance when we discovered that our interstellar transmitter was broken. Very broken. It seems most of the components had been scavenged by raiders, or taken home by staff, or something." 

"Unfortunately we can't afford real estate in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] system," explained Commander Jarvis, head of station entertainment at the Lave Radio Network. "It's wonderful that the Lave system is free from dictatorship these days, but territory used to be a lot more affordable. Now scalpers and investors have the best of it. Nevertheless, we're very glad for this opportunity to foster a relationship with the…*sigh*...Diso system." 

The [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio interstellar transmitter system uses powerful focusing crystals found only in the Cherbones system. These blood crystals are extremely rare, and are extracted via a highly dangerous mining operation. Lave Radio's second technician – a former Cherbones Mining Authority employee – spoke fondly of his first assignment: 

"Those were happy times. There was a fair amount of injury, but what posting doesn't have its share of dangers? I mean, everything's dangerous in space: gantries, zoological laboratories, airlocks, vending machines – everything." 

The [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio Network has asked the galactic community to deliver as many blood crystals as possible to Lave Station in the Lave system for the new interstellar transmitter. The campaign begins on the 3rd of March 3302 and will run for one week. If the final target is met earlier than planned, the campaign will finish immediately.
