:PROPERTIES:
:ID:       8ab91713-b001-4fd6-b504-2171a0b99612
:END:
#+title: Rackham’s Lavish Celebration Concludes
#+filetags: :3308:Federation:galnet:

* Rackham’s Lavish Celebration Concludes

/19 May 3308/

*Pilots’ Federation ALERT*

A party held by newly confirmed trillionaire [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] has concluded, with attendees claiming it was an ‘incredible’ event.

The week-long event took place in the upper storeys of the Rackham’s Spire building on the planet Homeland. This required regular supplies of the luxury items [[id:b27fcb6d-4c69-4cff-9acc-10c618a11a77][Apa Vietii]], [[id:aa2662c4-12d2-4842-8ff2-ca213e1b1f9e][Gerasian Gueuze Beer]], [[id:5fd3adda-81be-4ccd-82a6-324dab2156c7][Pantaa Prayer Sticks]], Uszaian Tree Grubs and [[id:618b671b-2863-4735-b7ef-30e5851e99a7][Anduliga Fire Works]].

A spokesperson for [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]] thanked pilots for these deliveries, and confirmed that payment could be collected at Edmondson High in the [[id:0db1f0b9-a70d-4384-96a5-c1587a8270b1][Beta Hydri]] system. The spokesperson remarked that Mr Rackham himself was unable to make a personal appearance due to ‘fatigue’.

[[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]] published this piece by financial journalist [[id:2d151711-b41e-452d-88fc-9ec34e317af9][Bryanna Blanco]]:

“First-hand accounts from some of the partygoers suggest this was more like a no-expense-spared holiday. Each attendee was assigned an [[id:04ba4637-336a-46c7-bab0-3ac12f16b2f9][Achilles Corporation]] [[id:b1ac4269-50e7-44ff-934f-7e9e1111e80b][PA-961]] serving robot as a personal butler, constantly attending to their every whim. An impressive range of beverages, cuisine and various legal stimulants were available. Those who wished to stay overnight were provided with luxurious suites near the peak of Rackham’s Spire, offering fantastic views of the picturesque landscape.”

“There were exclusive live shows from top performers, including steeldub band Gr@wl!x and popular singer Caspar Karma. Exotic entertainers from the Lucinda Ninespice Agency provided both public and private entertainment. And everyone departed with a goodie bag containing limited edition Duradrives, colonies of [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]]ian Skin, and gambling credit chips for the new Rackham’s Casino down below in Los Pioneros.”

“The guestlist included PR specialist [[id:464bcd90-c51a-4650-b5bb-83011a9dc5de][Anya Blackriver]], [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]] Today’s owner [[id:3c9dcd13-a5a3-4dd8-8367-43fba712cb4f][Neive McFarlane]], [[id:0db1f0b9-a70d-4384-96a5-c1587a8270b1][Beta Hydri]] Corporation’s entire board of directors, senior management from half a dozen Federal banks, and no less than eight independent, Liberal and Republican congressmen.”

“How many of these tried to convince Rackham that running for president was a mistake, and how many offered their support in hopes of future rewards? I’m sure the old pirate will pursue whichever route offers the greatest opportunity for new treasure.”
