:PROPERTIES:
:ID:       912b2a84-39dc-40d0-a60f-13c66d1752a1
:END:
#+title: Jarl Toredo Resigns from Unchain
#+filetags: :Empire:3304:galnet:

* [[id:5fdbd5d4-1f5f-4984-8876-4bee1d590dd7][Jarl Toredo]] Resigns from Unchain

/09 Aug 3304/

Campaigner [[id:5fdbd5d4-1f5f-4984-8876-4bee1d590dd7][Jarl Toredo]] has resigned from Unchain, the anti-slavery organisation he founded with Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]. 

Unchain’s press office released this statement: 

“We can confirm that [[id:5fdbd5d4-1f5f-4984-8876-4bee1d590dd7][Jarl Toredo]] has officially resigned from his position as co-chief executive officer, effective immediately. Princess Duval remains our patron and CEO. We wish Mr Toredo all the best with his future endeavours.” 

Reema Falco, a journalist writing for The Imperial Herald, made these observations: 

“Considering Toredo’s passionate rhetoric against Imperial slavery, it’s surprising for him to abandon an organisation that he co-founded. The recent assassination attempt against Princess Duval at an Unchain fundraiser may have caused him to regret allying with such a volatile political figure.” 

“As yet, there is no comment from Her Imperial Highness. This has led to speculation that there was a falling-out between the two. Rumours of a romance between them never quite went away, even after the princess’s engagement to [[id:81c5c161-1553-44f0-b5fb-c4a58f1f71d7][Jordan Rochester]]. Is this perhaps a jealous rival storming off in a fit of pique?” 

Representatives from Unchain have said that their campaigning, fundraising and slave-liberation programmes will continue as normal.
