:PROPERTIES:
:ID:       b88a2eed-8f0b-49d0-be42-8d3591906e1f
:END:
#+title: Scythe of Panem Militants Defeated
#+filetags: :Federation:galnet:

* Scythe of Panem Militants Defeated

/28 Oct 3305/

Scythe of Panem, the activist group responsible for the crop-destroying blight, has been defeated in the Quator system. 

Supported by Bruthanvan Co security teams, independent pilots were able to neutralise the group’s militant ringleaders. Scythe of Panem members have also been arrested following the raid of an unregistered facility discovered beneath the planetary port Weber Settlement. 

FIA Agent Gino Borstein spoke on behalf of the tri-superpower taskforce investigating the blight: 

“Initial questioning has confirmed that Scythe of Panem originally sought revenge for the Federation’s orbital bombing of Onion Head crops on Panem nearly five years ago. But a recent change in leadership led them towards more extreme methods, fuelled by anti-capitalist sentiment, with the objective of disrupting the galactic economy.” 

“The term ‘Crops for Crops’ recurs in many of the data entries and communications recovered from the underground facility. We believe this phrase was used as a rallying cry by members.” 

Traders are currently transporting the agronomic treatment for the blight pathogen, with a focus on the Diso and Orerve systems. As yet there is no official word regarding its effectiveness, but the Interstellar Association for Agriculture remains optimistic. 

Vox Galactica published an opinion piece from journalist Adalyn Cross: 

“A vital question remains: has the damage already been done? While the originators of the blight have been brought to justice, can a galaxy-wide eradication of food supplies be prevented?”  

Pilots who assisted with the campaign in the Quator system can now pick up their rewards from the Bruthanvan Co at Quator Station.
