:PROPERTIES:
:ID:       193591f6-23aa-455a-b8d5-a1de6cc00abe
:END:
#+title: Master Chefs Coming to Market
#+filetags: :galnet:

* Master Chefs Coming to Market

/26 Nov 3301/

Last month, a remarkable story emerged from the Noti system. According to an anonymous report, an organisation known as the Revolutionary Noti Values Party had created a new strain of slave labour known as 'the Master Chefs'. The unidentified whistleblower claimed the slaves were subjected to an intensive training programme designed to transform them into the galaxy's greatest gourmets – a claim dismissed by many as an imaginative hoax. A subsequent report from the Federal Times of a Master Chef training facility at Weber Gateway went some way towards lending credibility to the story, but most people remained unconvinced. 

The sceptics were proved wrong, however, when the Revolutionary Noti Values Party announced that not only were the Master Chefs real, they would soon be available for purchase. The announcement invoked the ire of human rights activists, who condemned the allegedly inhuman practices employed in training the Master Chefs. But this did little to deter consumers from placing advance orders for the epicurean slaves. 

Now, the Revolutionary Noti Values Party has announced that it intends to further improve the efficacy of its gastronomic labourers by implanting a comprehensive compendium of culinary knowledge directly into their cerebellums. A spokesperson for the organisation said: 

"By embedding this knowledge directly in a slave's brain, we can ensure total data integration and retention, which when combined with the slave's inherent culinary ability will result in unmatched gastronomic efficacy. These guys will be able to make a bacon sandwich fit for a king." 

The Revolutionary Noti Values Party concluded its announcement with a public appeal for Xihe Companions, which it will combine with the latest holographic technology to create the implants. The group has promised to give generous rewards to pilots who deliver the necessary materials.
