:PROPERTIES:
:ID:       560b6024-bae6-4249-b171-a82a80d059e7
:END:
#+title: Freelance Report: Guardian Archangel
#+filetags: :3302:galnet:

* Freelance Report: Guardian Archangel

/26 Nov 3302/

Last week, the galaxy witnessed a truly audacious rescue. 

While returning from [[id:80ea667a-62b4-4082-bed0-ce253d76869b][Beagle Point]], Commander Felix [[id:9bca8c31-9d54-48a5-b284-f90bfda7eff7][Macedonica]] found himself without sufficient germanium to synthesise an FSD injection and continue his journey home. Faced with the choice of spending the rest of his life 65,000 light years from home or destroying his beloved Lakon Type-6E and riding the escape capsule back to civilisation, Felix was in dire straits indeed. 

At that moment, Commander Chiggy Vonrictofen was exploring the Zunou sector. When Chiggy picked up a weak sub-ether distress signal, he quickly established a private link with Felix before appraising the system for asteroid belts and ringed planets that could potentially yield germanium. He then departed for [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] to fit a mining laser and larger fuel tank. 

With his ship appropriately equipped, Chiggy proceeded to cover the first 30,000 light years from [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] in less than 13 hours, a wraith of speed and purpose. Stopping only to sleep, he finally arrived less than 48 hours after receiving Felix's first transmission. 

The pair travelled to the nearest belt and Chiggy spooled up the mining laser as Felix watched the scanner. Nickel, iron, sulphur, manganese, phosphorus – the elements kept coming, but not the one they needed. 

Despair started to creep in. Then it appeared, a word that brought with it a cascade of emotions: germanium. Felix swooped in and secured his freedom. 

"Chiggy's efforts have left me speechless," said Felix. "His perseverance shows that the indomitable human spirit has no bounds." 

Commander [[id:56e961c9-9cb2-42b0-a52d-7b5c1909480f][Mad Billy]] 

Institute for Galactic Exploration and Research
