:PROPERTIES:
:ID:       4535d2b8-8921-4540-aece-cc4deaa8bee3
:END:
#+title: Crew Missing from Celebrity’s Starship
#+filetags: :3305:galnet:

* Crew Missing from Celebrity’s Starship

/10 Jan 3305/

A luxury star yacht belonging to famous actor Consuela Knight has reached its destination with nobody onboard.

The incident was reported by independent newsfeed [[id:82f6fe30-acb7-4e40-a7d5-3f1338d4f520][The Sovereign]]:

“Consuela Knight’s beautiful ship often attracts admirers when it arrives at a starport. But on this occasion it also brought security forces, since the custom-built private yacht was completely empty.”

“Investigators discovered that the ship was in perfect condition with all escape pods intact. There were signs of recent activity, such as unfinished meals and handheld equipment on the floor. Computer records confirmed the crew's presence until a few minutes before arrival, when all five people – including Ms Knight– simultaneously vanished.”

“Engineering and [[id:f9515545-c736-42cc-88ec-f3f269afd1b8][hyperspace]] experts have begun analysing data to unravel this mystery. But there is no reason to believe there are any survivors of this phenomenon.”
