:PROPERTIES:
:ID:       7002d126-0eb4-4b02-ac69-d6db3926a124
:END:
#+title: Patreus Demands Debt from Themiscrya
#+filetags: :Empire:3301:galnet:

* Patreus Demands Debt from Themiscrya

/31 Mar 3301/

The small system of Themiscrya has found itself embroiled in a row with Imperial Senator Denton Patreus. According to sources close to the situation, last year the Nationals of Themiscrya borrowed heavily from Senator Patreus in order to initiate regime change in Themiscrya. Now the Senator has called in the debt, and the Nationals of Themiscrya find themselves in the unfortunate position of being unable to make good on their obligations. 

Since taking over the government of Themiscrya last June, the Nationals of Themiscrya have instituted a number of policies designed to help stabilise the previously volatile region. One such policy included heavily fortifying both their headquarters on Lily May and Themiscrya’s satellite defence system aboard Bamford Station. Unfortunately, the defence system was sold to Themiscrya by representatives of Senator Patreus in the first place. Whether or not Patreus has remote access to the satellite defence system remains to be seen. 

Senator Patreus has offered the Nationals of Themiscrya a 7-day grace period in which to come to terms with the Senator’s finance team. If an agreement cannot be reached, Senator Patreus has indicated that he will be sending bailiffs to reclaim his property.
