:PROPERTIES:
:ID:       ab5c21fe-e6cb-4327-bb5e-230e4d69c923
:END:
#+title: Yong-Rui: ‘History Will Judge Sirius’
#+filetags: :3308:Federation:Empire:Alliance:galnet:

* Yong-Rui: ‘History Will Judge [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]’

/19 Apr 3308/

The CEO of [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation has addressed public concerns regarding its anti-xeno defence pact with the Alliance. 

Li Yong-Rui’s comments were made during an in-depth interview with The Alliance Tribune: 

“The best way to predict the future is to study the past. This is as true of interstellar organisations as it is of individuals – our former actions indicate the probability of behaviour. So I invite you to study the role that [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation has previously played on the political stage.” 

“Ever since the Battle of [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]] and the widespread conflicts of the 2300s, our neutrality has allowed us to mediate between the Empire and the Federation on many occasions. More recently, we defused inter-power tensions by establishing the Marlinist Colonies, which provided permanent homes for millions of refugees.” 

“It should also not be overlooked that the Galactic Summit was hosted in the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system, where we encouraged humanity’s leaders to peacefully debate their differences. Furthermore, our development of the frame shift drive has revolutionised exploration and allowed many independent societies to flourish.” 

“Some continue to cast aspersions on our strategic partnership with the Alliance, and I fully understand their caution. The fear that corporations can only act self-servingly is born from a millennium of notable examples. But it is history that will judge [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation’s efforts to defend and preserve civilisation. I truly hope the Alliance will play a significant role in those efforts.”
