:PROPERTIES:
:ID:       224c6545-ba55-43ee-a11b-28b5b563cdd1
:END:
#+title: Colonia Bridge Project Launches Phase Three
#+filetags: :3308:Federation:galnet:

* [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge Project Launches Phase Three

/06 Jan 3308/

*Pilots’ Federation ALERT* 

Brewer Corporation intends to improve the travel corridor between the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] and [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] systems by constructing several new starports. 

The previous two phases of the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge project established stationary megaships in 56 systems. These provide rest, refuel and repair facilities for vessels making the 22,000 light year journey to and from the Colonia region. The additional infrastructure has also increased the amount of tritium available at these markets, easing the journey for capital-size ships. 

A press release from Brewer Corporation outlined this latest initiative: 

“Phase three aims to enhance the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge by building permanent starports in key locations along the route. These will offer a wide range of services to travellers, and also serve as homes for the many new communities that we expect to spring up around them.” 

“Our plan is to construct one starport in the vicinity of [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]], and up to five starports stretching out from [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]]. Station structures will be assembled by the 27th of January, with additional services scheduled for implementation at a later date.” 

“Pilots are asked to deliver ceramic composites, computer components and thermal cooling units to [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system and Macdonald Settlement in the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] system.” 

“Assuming deliveries reach the required level, engineered frame shift drives will once again be available as rewards.” 

“The highest contributor in [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]], and up to the top five contributors in [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]], will be invited to submit naming suggestions for the new starports. All name submissions will be subject to review by the Brewer Corporation board of directors.”
