:PROPERTIES:
:ID:       3057d854-bc5f-49ca-879d-9d6922518d1b
:END:
#+title: Terrorist Hit Squad Targets Hadrian Duval
#+filetags: :Empire:galnet:

* Terrorist Hit Squad Targets [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]]

/27 Oct 3306/

Imperator[[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Augustus Duval]] has been severely wounded in an assassination attempt by Neo-Marlinist extremists. 

The attack took place at Dyson City in the Paresa system, headquarters of the isolationist organisation Nova Imperium. A small team of armed intruders broke into the command deck and opened fire. Three people were killed and four injured, including [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]], before his Praetorian Guard eliminated the assassins. 

The [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] has claimed responsibility. On propaganda channels, the paramilitary group vows to “sever every head of the Duval hydra”, and calls for all citizens to rise up and demand democracy. 

Praetor[[id:3fdf3f05-e7b5-436f-906e-e67dafa5d254][Leo Magnus]], Nova Imperium’s head of security, gave this statement to Vox Galactica: 

“The Imperator is in a critical condition but receiving our finest medical care. I am personally overseeing an investigation into how the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] infiltrated our starport and bypassed security checks.” 

“Such attacks are as sickening as they are cowardly, and Nova Imperium stands firmly against these terrorists.” 

Hadrian Duval is the illegitimate grandson of Emperor Hengist. His father, the late Commander[[id:8d725ff3-3036-473a-b339-09e4da4e43d0][Hector Jansen]], was the result of a secret liaison with a household slave. Although disowned by the Imperial Family, Hadrian claims to be a rightful heir to the throne.
