:PROPERTIES:
:ID:       703f9750-4bd3-4296-bc63-442c567229ee
:END:
#+title: A Gift from the Golconda
#+filetags: :galnet:

* A Gift from the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]

/22 Nov 3305/

The inhabitants of the generation ship [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] have offered a token of gratitude to authorities in the Upaniklis system for their recent help. 

The gift was a case of an alcoholic spirit labelled Apa Vietii, distilled only aboard the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] for many centuries. An accompanying note explained that the production technique has remained largely unchanged since the 22nd century.  

Analysis of the beverage confirmed it was safe for consumption, although nothing is known of the raw ingredients or distillation process. 

As yet very few people have sampled Apa Vietii, but the celebrated gourmet and critic Giles Cappelleo was invited to appraise the spirit: 

“Well, what a delight this is – to experience a previously unheard-of libation! Apa Vietii is refreshing on the palate with a smooth, crisp flavour, but delivers a vigorous thump to the senses once swallowed. If it ever becomes widely available, connoisseurs everywhere would surely adore it. The [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] crew is sitting atop a potential goldmine!” 

Professor Elizabeth Perez of the Orion Independent University provided an anthropologist’s take: 

“This is a significant gesture from a society that has been highly reluctant to interact with outsiders. Although their isolationist stance remains prevalent, offering Apa Vietii could be interpreted as the start of a cultural exchange programme prior to rejoining civilisation.”
