:PROPERTIES:
:ID:       b6979c93-dce3-4603-b4a6-b7fd9a143012
:END:
#+title: Terrorism Respite as Marlinists Prepare for New Homes
(fset 'galnet\ import
   (kmacro-lambda-form [?\C-m ?\C-f ?\C-f ?\C-@ ?\C-e ?\C-\[ ?w ?\C-c ?r ?f ?\C-y ?\C-m ?\C-\[ ?x ?\C-\[ ?p ?\C-m ?\C-\[ ?p ?\C-m ?\C-\[ ?\[ ?8 ?^ ?\C-x ?o ?\C-x ?h ?\C-\[ ?w ?\C-x ?o ?\C-y ?\C-a ?\C-i ?\C-\[ ?\[ ?8 ?^ ?\C-m ?\C-c ?\C-c ?\C-x ?k ?\C-m ?\C-x ?k ?\C-m ?\C-n] 0 "%d"))

* Terrorism Respite as Marlinists Prepare for New Homes

/21 Dec 3306/

As independent colonies are set up for Marlinist refugees, there has been a lull in terrorist strikes from the Neo-Marlinist Liberation Army (NMLA). 

In recent months, the paramilitary group launched multiple attacks across the Empire. Starports and administrative buildings were bombed and dozens of individuals assassinated, including Prince Harold and more distant members of the Duval family. 

However, the number of incidents has fallen drastically following successful operations by the Imperial Internal Security Service: 

“After the Federal Security Service identified NMLA members aboard the emigrants’ megaships, these were transferred to us for interrogation. We obtained information that enabled us to shut down many terrorist cells, although there is evidence that the NMLA’s network remains widespread.” 

In related news, hundreds of thousands of Marlinist refugees are preparing to occupy new colony systems established by the Sirius Corporation. Mass transportation will take place early next year, overseen by Safeguard Interstellar. The Empire, Federation and Sirius Gov have all agreed that the settlements will remain fully independent. 

The refugee population has already begun to determine its future social structure, based on the principles of Marlinism. A transitional parliament has been formed by community leaders such as Dr Jenna Fairfax, Aaron Whyte and Amrita Ross. Democratic elections for a representative government will take place once the Marlinist Colonies are operational.
