:PROPERTIES:
:ID:       9591f7e4-b5b3-4cc6-bfec-0ccb8c5e3c70
:END:
#+title: Jupiter Division Inspires Corporatist Movement
#+filetags: :galnet:

* Jupiter Division Inspires Corporatist Movement

/01 Jun 3307/

The Core Dynamics breakaway faction created by ex-CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] has survived, by gathering believers in the corporate rule of the Federation. 

Conrad Sterling, political journalist for Vox Galactica, published this report: 

“With its military forces defeated in February, and its leader found guilty of mass murder and imprisoned for life, Jupiter Division should now be a footnote in the Federation’s history.” 

“Yet in recent months it has steadily grown, retaking control of HIP 54530 and several neighbouring systems. Its megaship, Victory’s Forge, even managed to repel Federal troops and remains under Jupiter Division’s command.” 

“There is much speculation about the underlying reasons for this. Alongside general unrest with the Federation’s current policies, there is a rising interest in Rochester’s grand vision – replacing democracy with corporatocracy – among those wishing to see change. Many have flocked to Jupiter Division’s banner, preventing its collapse.” 

“Core Dynamics, its parent company, has also continued to see defections within its ranks. However, new CEO Owen McKenna has vowed to destroy his predecessor’s rogue department. It is possible that Jupiter Division’s survival was only a brief reprieve, unless the corporatists can gather in sufficient numbers to sustain it.”
