:PROPERTIES:
:ID:       7497e422-c726-412c-9788-aafd6c844f58
:END:
#+title: ‘Ghost Ship’ Arrives in Chukchan System
#+filetags: :galnet:

* ‘Ghost Ship’ Arrives in Chukchan System

/29 Oct 3306/

*Pilots Federation ALERT* 

An abandoned megaship that set out two centuries ago has returned on automatic pilot to the Chukchan system. 

Local security forces were scrambled to intercept an unidentified vessel that was detected on a collision course with Chukchan 5 B. 

The megaship displayed no signs of life, so tugs were deployed to wrench it into a safe orbit. This caused onboard power systems to overload with explosive results, damaging cargo holds and spilling debris. 

The name of the ship was confirmed as the Adamastor, but no further information is available in the public domain. 

Specialists from the Alliance Salvage Guild boarded the derelict to conduct an investigation. Their preliminary report stated: 

“The Adamastor has been travelling at sublight speed through interstellar space for nearly two hundred years. There are no remains of the crew. All escape pods and secondary craft have been launched, and several airlocks were manually opened from within.” 

“A complete absence of identification suggests that this ship was intended for clandestine operations. All data drives have been deliberately erased.” 

“There is evidence of a reinforced cargo hold, fitted with what looks like the remains of environmental equipment. Recent fire damage makes it impossible to be more specific.” 

“The ship’s original destination is unknown, having returned to its launch point on autopilot. Calculating its trajectory implies that it passed near the HIP 61595, HIP 64011 and HIP 65201 systems.” 

The Adamastor will remain in orbit for further examination.
