:PROPERTIES:
:ID:       232182c4-650b-4972-bac7-032cde57e64e
:END:
#+title: Calls to Execute Far God Worshippers
#+filetags: :3304:galnet:

* Calls to Execute Far God Worshippers

/13 Sep 3304/

Juanita Bishop has called on Federal Congress to make Thargoid worship a capital crime, and for all members of the Far God cult to be executed. 

Addressing a rally during her congressional campaign, Mrs Bishop stated: 

“I speak for all those who live in fear of Thargoid infiltration. If elected, I will make sure this foul cult is outlawed and all its followers put to death. Congress has a duty to protect families from these alien-loving collaborators.” 

Vihaan Niven, an independent political analyst, commented: 

“Juanita Bishop’s statement has triggered considerable debate in Congress. Some congressmen have aligned with her, eager to be seen as ‘tough on Thargoids’. But others have criticised Mrs Bishop for her ‘inhumane rhetoric’ and for proposing the execution of Federal citizens without trial.” 

“Meanwhile, the Federal Intelligence Agency continues to arrest adherents of the Far God sect and detain those who have had contact with them. As casualties from the Thargoid conflict mount, it’s hard to see this most unlikely of faiths surviving much longer.”
