:PROPERTIES:
:ID:       3a923424-a222-413d-9e4c-65c308b5108b
:END:
#+title: Further Arrests of Far God Cultists
#+filetags: :Thargoid:3304:galnet:

* Further Arrests of [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Cultists

/10 Aug 3304/

The Federal Intelligence Agency has apprehended further members of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult, to determine if they are communicating with the Thargoids. 

Media channels report a division in public opinion regarding the FIA’s actions. Some see the arrests as illegal and tantamount to religious persecution. Others claim that the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] worshippers have invited suspicion upon themselves, and that the detainments are justified. 

Dr Jameelah Griffin of the Galactic Interfaith Commune commented: 

“We strongly oppose this hostility against the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect. These arrests are motivated by fear rather than evidence. We must fight for the civil rights of our fellow citizens, even if we do not share their beliefs.” 

A prominent campaigner against the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult, Juanita Bishop, told the media: 

“This is a victory for right-thinking people everywhere. Those warped alien-lovers are a blight on our system – one that should have been eradicated long ago.” 

Senior Agent Micah Whitefield of the FIA stated: 

“This operation is purely a security matter. Under Federal law, any action that undermines enemy activity during wartime is legal, including the suspension of civil liberties. We are expanding our investigation to include all members of this organisation and anyone with a connection to it.”
