:PROPERTIES:
:ID:       a7e62a12-6e07-4085-b579-904e8bed929f
:END:
#+title: Witch Head Planetary Ports Established
#+filetags: :Thargoid:galnet:

* Witch Head Planetary Ports Established

/08 Aug 3305/

Humanity’s expansion into the [[id:ce73c3e5-6875-480c-95a9-c146f6247bb7][Witch Head Nebula]] has continued with the
introduction of seven planetary ports.

Six ports now occupy systems surrounding the existing enclave. The
Alliance, Federation and Empire have each established two ports,
strengthening the presence of their representative factions.

The seventh port, [[id:3e0bac16-dadc-40cd-bbde-d0d8eb29b441][Cinder Dock]], is located in [[id:24048a7f-662d-4779-bc3c-64ffcf85bd49][Witch Head Sector DL-Y
d17]]. Professor [[id:c2623368-19b0-4995-9e35-b8f54f741a53][Alba Tesreau]] of [[id:3808ab0e-fcff-4299-b882-f8c3946f272d][Aegis Research]] provided some additional
details:

“A facility managed by the engineer [[id:ff1f91b2-2084-4a2a-9060-f5a4aa0fe5bb][Chloe Sedesi]] has been installed at
Cinder Dock. The engineering blueprints available at the facility
offer upgrades to frame shift drives and thrusters.”

“Following last-minute discussions held aboard the megaship [[id:274e224f-da81-4d15-9f78-eb794565efb4][Spirit of
Minue]], a tech broker and material trader have also agreed to bring
their services to the planetary ports. These contacts are located at
Bray Landing and Ratchet Hub respectively.”

“With these new resources available ahead of schedule, we hope to
accelerate the ongoing efforts to repair the starports damaged during
recent Thargoid assaults. [[id:392c2c3c-89fa-49bd-880f-adfa219b484d][Ezra Point]] is the first to declare itself
fully functional, with all standard services back online.”

Further installations have been planned over the coming weeks, as
migration continues to bring new opportunities and financial
investment to the enclave.

“These achievements are founded on the tireless efforts of many
independent pilots,” said Tesreau. “Their bravery and dedication were
key factors in securing humanity’s access to meta-alloys within the
Witch Head Nebula. On behalf of Aegis, I offer these pilots my deepest
gratitude.”
