:PROPERTIES:
:ID:       dc67fc6e-67ad-4236-aa87-7b5621521227
:END:
#+title: Initiative to Outfit Far God Megaships
#+filetags: :galnet:

* Initiative to Outfit [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Megaships

/22 Jul 3307/

*Pilots Federation ALERT* 

The Pleiades Concordat has requested deliveries to support the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult in the Panjabell system. 

Members of the secretive Thargoid-worshipping sect have gathered in huge numbers, and are preparing to outfit one or more megaships for religious purposes.  

Although the cult has no official spokespeople, local newsfeeds carried a brief message from one of its senior members, known only as the First Herald of the Fifty-Eighth Chapter: 

“The faithful have hidden in the shadows for too long. Now is the time to reach out and welcome the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]], with the support of our friends in the Pleiades Concordat.” 

“The first megaship, the Testament, will be a missionary vessel to spread the word to all humankind. If we are blessed enough to obtain commodities for more megaships, these will be sent on a pilgrimage into deep space to commune with the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]].” 

The Pleiades Concordat has requested that pilots deliver auto fabricators, emergency power cells and insulating membrane to Moore Hub in the Panjabell system. 

Far God believers are generally accepted to be non-threatening, albeit controversial due to their reverence of the Thargoids. As the cultists are routinely targeted by anti-xeno extremists, the Pleiades Concordat has placed bounties on all wanted ships to protect deliveries.
