:PROPERTIES:
:ID:       915ef6eb-43ed-44d1-9bb3-9e83b298b8e1
:END:
#+title: Archon Delaine Campaign to Build New Starports
#+filetags: :galnet:

* Archon Delaine Campaign to Build New Starports

/15 Apr 3307/

*Pilots Federation ALERT* 

The Kumo Crew syndicate has launched an initiative to construct up to five starports to stimulate galactic trade. 

Kavanagh Spaceframes Ltd, an independent construction company, has been privately contracted by the Kumo Council to build fully operational Orbis stations. These will be located in uninhabited systems close to key trading regions and areas of commercial interest. 

The Pegasi Sentinel newsfeed featured this statement from Archon Delaine: 

“As sovereign ruler of the Kumo nation, it’s my responsibility to increase prosperity for the systems under my protection. My new starports will extend our reach and boost trading of all kinds… legitimate and otherwise.” 

“I have also placed bounties on the heads of anyone who dares to interfere with my plans. The one thing we never trade in is mercy.” 

The Razor Whips, one of Delaine’s loyal factions, is organising the campaign. It will reimburse pilots who deliver ceramic composites, semiconductors, polymers and water purifiers to Gabriel Enterprise in the Harma system. 

The number of new starports will depend on the quantity of deliveries. The targeted locations are: 

Pegasi sector PN-T C3-14, near the Harma system 

HIP 18390, near the California Nebula 

HIP 10792, near the Sothis system 

HIP 62154, in the Coalsack Nebula 

Eol Prou PC-K c9-91, in the Colonia region
