:PROPERTIES:
:ID:       ad7d290d-4256-47b3-833a-47cc0a4aa457
:END:
#+title: Freelance Report: The Reclamation of Facece
#+filetags: :galnet:

* Freelance Report: The Reclamation of Facece

/02 Jul 3302/

After months of vicious fighting, the Imperial Naval Auxiliary has reinstated the Facece Empire Party as the controlling power of the Facece system. 

Marquis Endincite, who coordinated the effort to reclaim the system, made the following statement to the Imperial Herald: 

"The Empire Party has regained administration of Facece, and we beseech Imperial Commanders everywhere to ensure its continued dominance in the system. Never again should the Empire allow its pre-eminent Naval base to fall under the sway of disloyal elements." 

The Allied Facece Order, which seized Facece late last year, retains control of multiple planetary and orbital stations. Fighting is likely to continue for months. 

Chancellor Anders Blaine, the system's administrator, has yet to make an official statement. But he is reportedly preparing to address the Empire, and to commend Marquis Endincite and the Imperial Naval Auxiliary for their service. 

Commander Corrigendum
