:PROPERTIES:
:ID:       bfe48a1a-e2b9-4f56-ad7b-9b94faed973a
:END:
#+title: Deliver Resources for Extraction Missile Manufacture
#+filetags: :galnet:

* Deliver Resources for Extraction Missile Manufacture

/28 Sep 3309/

*Pilots’ Federation ALERT* 

Aegis has requested materials to construct sub-surface extraction missiles that recover imprisoned humans from the Titans. 

Professor Alba Tesreau, head of Aegis, announced: 

“Using blueprints provided by Sirius Corporation, engineering teams have worked around the clock to modify sub-surface displacement munitions. These adaptations enable the projectiles to breach sections of the Titans’ hulls and jettison the bio-storage capsules embedded within.” 

“We could spend the next few months in a testing cycle, and ideally that would be the case – but lives are at risk and we can’t be sure how much time our missing have. Therefore, we have approved mass production of these sub-surface extraction missiles. Industrial materials are urgently needed to establish assembly centres, so that we can distribute them as rapidly as possible.” 

Princess Aisling Duval, who is coordinating the Empire’s involvement with Aegis, transmitted a personal message: 

“My heart goes out to the families and friends of the millions unaccounted for following the Thargoid invasions. But I urge you all to hold onto the hope of seeing your loved ones again. With this breakthrough, we finally have a chance to rescue some of those poor souls. Nobody doubts that this will be dangerous, and yet if this war has proved anything, it’s that we can rise to any challenge when we work together.” 

Aegis has requested shipments of CMM composites, neofabric insulation and osmium, to be delivered to Springer Gateway in the Senlu system. To protect transports, bounty vouchers for all wanted ships in the system will be redeemed by the Green Party of Senlu.
