:PROPERTIES:
:ID:       f6fe63ae-0c05-46ec-94cb-5b4d894a51eb
:END:
#+title: Community Goal: The Colonia Exodus
#+filetags: :3303:galnet:

* Community Goal: The Colonia Exodus

/08 Dec 3303/

Despite the repeated assurances of the galactic authorities, which have endeavoured to downplay the scale of the Thargoid threat, it is clear that many of those in the core systems feel less than secure. This is evidenced by the huge numbers of citizens fleeing to Colonia, eager to escape the Thargoids. 

In response to this development, the Colonia Council issued the following statement: 

"Colonia has always been a haven, and we would never deny entry to those fleeing danger. But if we are to provide people with homes and employment, we must build. We have therefore made plans to establish a number of new outposts throughout Colonia, to support our new neighbours." 

"Unfortunately, the urgency of the situation means we cannot rely on our usual trade partners, and we are therefore turning to the galactic community for support. We have placed an open order for a range of construction materials, and have set aside considerable premiums for pilots who deliver these goods to Pilkington Orbital in the Einheriar system." 

The campaigns begin on the 7th of December 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
