:PROPERTIES:
:ID:       c48ee636-fa07-4c2e-914c-9bd2f4cbec1b
:END:
#+title: Galactic News: Laksmii Jet Power Industries Operation Thwarted
#+filetags: :galnet:

* Galactic News: Laksmii Jet Power Industries Operation Thwarted

/19 Jan 3303/

Authorities in the Parun system have reported that the Laksmii Jet Power Industries plot against the Independents of Parun has been foiled. The operation centred on smuggling various items into Underwood Port so Imperial agents could use it to conduct guerrilla attacks against the  Independents of Parun, the system's controlling faction. 

After learning of the plot, the Independents of Parun placed bounties on Laksmii Jet Power Industries ships operating in the Parun system. The strategy resulted in the destruction of hundreds of Laksmii Jet Power Industries vessels, severely undermining the organisation's plan. 

A spokesperson for the Independents of Parun thanked those who supported the operation. 

Pilots who contributed to the initiative can now collect their rewards from Underwood Port in the Parun system.
