:PROPERTIES:
:ID:       a1440905-adcd-48a9-bd31-fec6acad5f89
:END:
#+title: Senator Arissa Lavigny-Duval Gains More Powerful Support
#+filetags: :galnet:

* Senator Arissa Lavigny-Duval Gains More Powerful Support

/28 Sep 3301/

Senator Arissa Lavigny-Duval Gains More Powerful Support 
 
Capitol has been abuzz with rumour following Senator Denton Patreus' open declaration of support for Senator Arissa Lavigny-Duval. While possibly not a frontrunner for Emperor, Patreus commands a sizeable fleet and is rich and influential enough to help Arissa Lavigny-Duval become Empress. 

Senator Lavigny-Duval already enjoys the support of Chancellor Anders Blaine, whose voice is perhaps the loudest and most influential in the Senate.  

The Imperial Herald's revelations concerning connections between Princess Aisling's office and the Emperor's Dawn insurgency have severely impacted her rating, and are likely to have cost her support in the Senate. The political landscape has been shaken further by Senator Zemina Torval's announcement that she is backing Arissa Lavigny-Duval to be crowned Empress.
