:PROPERTIES:
:ID:       181afc70-e09c-4846-ae7a-1bf1b77128da
:END:
#+title: Freelance Report: Buckyball Spring Break Controversy
#+filetags: :Federation:3302:galnet:

* Freelance Report: Buckyball Spring Break Controversy

/11 Mar 3302/

Accusations of reckless endangerment have been levelled at the Buckyball Racing Club regarding its upcoming Spring Break chauffeurs event. Commander Seneh, the event organiser, had this to say: 

"This event is a community outreach programme. There will be no 'first place' or prizes. While it is true that the club will give performance scores to participating pilots, those scores will be based on the happiness and safety of the escorted students, not on distance travelled or speed." 

She continued: "All participants are Pilots Federation members, but some are still provisional, myself included! We appreciate that having a documented safety rating from a Grant Academics sanctioned event will help our careers, so we intend to respect our passengers and fly with the utmost care." 

Veteran Buckyball pilots will escort students from the Exigus campus of Grant Academics to the biggest tourism hotspots in the region between the 18th and 26th of March. 

Commander Jak 

Buckyball Racing Club
