:PROPERTIES:
:ID:       c9a3ea4c-e15d-4de5-9fa2-f94c369a43ee
:END:
#+title: Aegis Megaship Vanishes in Hyperspace
#+filetags: :3307:Thargoid:galnet:

* Aegis Megaship Vanishes in Hyperspace

/04 Jun 3307/

The Alexandria has failed to arrive in the HIP 30944 system as scheduled, and may have been hyperdicted by the Thargoids. 

The Aegis-owned megaship triggered an attack by Thargoid vessels when it travelled from the [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]] system to HIP 16538 on the 20th of May. Aegis believes this was caused by the large quantity of Guardian artefacts in its cargo holds. 

To reduce the risk of further casualties, the Alexandria plotted a route to a low-population prison colony in the HIP 30944 system. All independent ships were undocked before it made the hyperspace jump on the 3rd of June. 

However, the megaship never reached its arrival point and all communication with it has ceased. Search teams in local systems have not detected its presence. 

Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], chief military liaison with Aegis, informed the media: 

“We regret to announce a complete loss of contact with the Alexandria. Although there is no evidence of damage or destruction, its disappearance while travelling through hyperspace raises the possibility that it was intercepted en route by Thargoid forces.” 

“Captain Jacob Morales and over four thousand crewmembers will be listed as missing presumed dead. In addition to this great tragedy, Aegis’s research programme into Guardian technology has been severely impacted by the loss of many precious artefacts.”
