:PROPERTIES:
:ID:       82582e28-97ac-446b-81da-71480c18e398
:END:
#+title: Cult Requests Rare Commodities
#+filetags: :Federation:3304:galnet:

* Cult Requests Rare Commodities

/06 Dec 3304/

An obscure [[id:e65a893c-7018-496a-a3c9-14c4494efe8f][cult]] based in the [[id:5849073c-4bb5-4d8e-8d9f-991a1a8dad06][Zlota]] system has requested a range of
rare items for an arcane ceremony.

A handwritten statement from [[id:05a4b221-ceba-499f-aa92-d379b8189c7a][Barnabas Cole]], leader of a group named
the [[id:4bc224d4-a885-4911-829e-2c8a70cc478d][Children of Tothos]], was submitted to the media:

“This is the rite that will unmask us and allow us to see the path –
the path we will all take, together, toward freedom.”

[[id:5fa4a7bd-96ee-4321-91b6-4ef6b1b594fe][Zlota Federal Holdings]], which is thought to have some connection to
the cult, has requested [[id:040941c0-97fa-4dbc-b532-4cbc45f039c7][Aganippe Rush]], [[id:c1ed0385-9e08-4c48-8be9-9e7428bdfded][Motrona Experience Jelly]] and
[[id:2c677289-63df-4c19-81c7-4b05bc381674][Onion Head]] to be delivered to [[id:014990fb-678e-47fe-9898-8b27f633c001][Nusslein-Volhard]] Settlement in the [[id:5849073c-4bb5-4d8e-8d9f-991a1a8dad06][Zlota]]
system. It has also placed a kill order on all ships on its wanted
list, to protect those delivering these rare commodities.

The initiative begins on the 6th of December 3304 and will run for one
week. If the final target is met earlier than planned, the campaign
will end immediately.
