:PROPERTIES:
:ID:       e2743eb6-e972-422b-876e-d34c6f831fd2
:END:
#+title: Aisling Duval Criticises Aegis
#+filetags: :Empire:3304:galnet:

* [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] Criticises Aegis

/06 Apr 3304/

In a public interview, Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] levelled criticism at Aegis in relation to the ongoing [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] conflict. 

“The people are scared,” she said. “They fear that their way of life – their very existence – might vanish unless more is done to protect them. I’m not convinced Aegis is capable of doing so. The Empire has invested heavily in the organisation. Are we sure the other powers have done the same?” 

“It has taken far too long for Aegis to determine why the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] are attacking, and it’s not clear what their strategy is now. If we are to trust them to defend humanity, we need to see more obvious progress.” 

Although Princess Duval has received some support for her viewpoint, The Federal Times offered a sarcastic rebuttal: 

“Apart from undertaking scientific research, developing defensive systems, producing anti-Thargoid weaponry, creating the Eagle Eye surveillance network, building two military megaships and actively engaging [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] forces in combat…what has Aegis ever done for us?” 

A media spokesperson for [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] was equally dismissive: 

“This is nothing more than public posturing – an attention-seeking gambit from someone who is no longer as newsworthy as she once was. Aegis has made incredible breakthroughs, and is clearly dedicated to ending the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] war.”
