:PROPERTIES:
:ID:       94e4e4f9-676f-463f-a8c5-20963176a0dd
:END:
#+title: Week in Review
#+filetags: :3304:galnet:

* Week in Review

/22 Sep 3304/

Here are this week’s major stories. 

Political journalist Vanya Driscoll has published an analysis of the Alliance presidential candidates. She has observed that while Elijah Beck seems content with the status quo, Fazia Silva has promised to boost the economy, and current president Gibson Kincaid has proposed that the role should include executive powers. 

In other news, business magnate Lloyd Hardacre has been arrested for corporate fraud after his personal administrative robot revealed incriminating evidence. The incident took place during the annual general meeting of Copernicus Shipping Ltd, a firm founded by Mr Hardacre. Lieutenant Inspector Ramesh Thorne of the Federal Security Service is investigating. 

Independent reporter Gethin Okonkwo has revealed that he has been living undercover in the Far God cult for three months. According to his account, the cult has no contact with the Thargoids, with most of its followers being harmless fatalists. Mr Okonkwo recorded his experience using concealed micro-cameras, and has shared his data with the Federal Intelligence Agency, hoping to prove that the sect is not dangerous. 

Meanwhile, two rival technology companies – Supratech and Herculean Machines – have appealed for commodities to support the release of forthcoming products. Supratech is developing a personal computing device called the Torc, while Herculean Machines is working on a machine called the Duradrive. Both companies are hoping that the support of the galactic community will allow them to share working prototypes at a technology expo on the 3rd of October. 

Finally, the Libertas Cooperative has announced that its appeal for commodities has reached a successful conclusion, having received an overwhelming response from the galactic community. Land enrichment systems, animal monitors, aquaponic systems and marine equipment were delivered to Ocrinox's Orbiter over the past week, allowing construction of a megaship where manatees will be farmed. 

And those are the main stories this week.
