:PROPERTIES:
:ID:       c40f9a87-47b9-4bda-9224-9501b1c5f361
:END:
#+title: Further Omega Grid Secrets Revealed
#+filetags: :galnet:

* Further [[id:22dfd239-84ed-4b35-aa95-bc955ca95e8b][Omega Grid]] Secrets Revealed

/21 Feb 3308/

ACT has released details about a plan by the Lords of Restoration to frame Hadrian Augustus Duval as the leader of the NMLA. 

The information was extracted from the NMLA’s [[id:22dfd239-84ed-4b35-aa95-bc955ca95e8b][Omega Grid]] network and published by Captain [[id:ccaf380d-14e8-4a1a-9458-8c3bad87b25c][Saskia Landau]]: 

“It was Senator Ursula Torquatus who devised a scheme to undermine the Imperial Family and turn citizens against them by ‘exposing’ a Duval as the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] mastermind. Hadrian Duval was seen as the logical choice since many viewed him as an extremist through his prior association with Nova Imperium, though Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] officially pardoned him in 3306.” 

“The Lords of Restoration used a virtual doppelganger of the Emperor, indistinguishable from authentic transmissions, to convince the Senate that she was communicating from a safe location. A similar doppelganger was developed to replicate Hadrian and was used to send orders to [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] allies such as the Landgrave of Mudhrid.”  

“This is how they planted evidence, discovered in April 3307, that Hadrian had converted to Neo-Marlinism and was determined to wipe out all other Duvals. Yet, despite triggering an unsuccessful Federal attack in the Paresa system, the accusation was not verified or widely believed.” 

“Months later, the Lords of Restoration tried to kill Hadrian and Lady Astrid before their son Hector could be born, fearing the continuation of the Duval dynasty. But other senators moved the family to a secure location, beyond the reach of their agents.” 

Hadrian Duval has publicly thanked ACT for uncovering this information and officially absolving him of all suspicion in this matter.
