:PROPERTIES:
:ID:       fa67971c-fab0-4043-89e8-68e5d48aa32c
:END:
#+title: Mahon Wins Alliance Election
#+filetags: :3307:Alliance:galnet:

* Mahon Wins Alliance Election

/28 May 3307/

The election for Alliance prime minister has been won by the incumbent [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]], who begins a second six-year term in office. 

The Alliance Assembly voted yesterday to elect the new head of state. Mahon received more votes than any other candidate, albeit not a majority of the electorate. Some council members demanded additional checks, causing a delay in announcing the results. 

Prime Minister Mahon gave a victory speech to the public: 

“It is my great honour to continue serving the diverse peoples of the Alliance. We will hold fast to our principles of democracy, prosperity and mutual defence, no matter what the galaxy throws at us.” 

[[id:b26ee6ca-29a4-4dca-b69f-b4957b1ae650][Vanya Driscoll]], political correspondent for The Alliance Tribune, observed: 

“With the core systems affected by political unrest, terrorist threats and economic turmoil, it is no surprise that the Assembly voted for stability. Mahon is a known quantity, and the Alliance has become reliant on his calm, measured leadership.”
