:PROPERTIES:
:ID:       1852a0fd-d902-4357-8fa3-f87f77edfafc
:END:
#+title: Protecting Colonia
#+filetags: :3304:galnet:

* Protecting Colonia

/02 Mar 3304/

As the Thargoid offensive continues, authorities in Colonia have decided to step up security by building a new security installation in the region. 

A spokesperson for the Colonia Council, which is overseeing the initiative, gave the following statement: 

“The Thargoids have now entered the core systems, and their hostility shows no signs of abating. Meanwhile, Colonia’s defensive capabilities remain limited. It is clear to us that the time to act has come.” 

Colonia has agreed to fund the operation, and has placed an open order for various mined resources for use in the construction. Pilots who deliver the requested resources to Dove Enigma in the Colonia system will be generously compensated. 

The campaign begins on the 1st of March 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
