:PROPERTIES:
:ID:       a5b52a42-c7db-4ed5-8fb4-737bf495b74f
:ROAM_REFS: file:../references/Community%20Goals/Federation_Appeals_for_Exploration_Data_01_Dec_2016.md file:../references/Community%20Goals/Federation_appeals_for_Exploration_Data_29_Sep_2016.md
:END:
#+title: Community Goal: Federation Appeals for Exploration Data
#+filetags: :Empire:Federation:CommunityGoal:3302:galnet:

* Community Goal: Federation Appeals for Exploration Data

/22 Sep 3302/

[[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][The Federation]] has issued a public appeal for exploration data as part of its ongoing operation in the [[id:7e99a467-6e3d-418e-8b10-72cf3660efa6][Pleiades Nebula]]. The appeal is being coordinated by the [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]], which released the following statement to the media:

"Given the recent discovery of possible non-human wreckage in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]], it is essential that we have comprehensive and up-to-date information on the entire region. We are therefore asking pilots to sweep the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] and deliver any resultant exploration data to Pre Logistics Support Gamma in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] Sector IH-V C2-5 system. Commanders who contribute to this initiative will be generously rewarded."

The announcement comes in the midst of animated debate over recent Federal and Imperial action in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]].

The campaign begins on the 22nd of September 3302 and will run for one week. If final targets are met earlier than planned, the campaign will end immediately.
