:PROPERTIES:
:ID:       da38fa5a-d82a-4729-b181-ce8af5cf8d39
:END:
#+title: Galaxy's Most Wanted: Who is Archon Delaine?
#+filetags: :galnet:

* Galaxy's Most Wanted: Who is Archon Delaine?

/03 Jun 3301/

Villain, murderer, madman. Titles with which Archon Delaine, the self-styled Pirate King, are all too familiar. 

37 years ago, Archon Delaine rose to prominence after brutally beating the Kumo Crew’s previous leader to death with his bare hands. Thus, at the tender age of 15, Archon assumed the role of Pirate Lord and began to cut a bloody swathe across the Pegasi sector.  

During the first 20 years of his rule, Archon Delaine faced a constant stream of challenges from upstarts and other crews alike. Each and every challenger was struck down, and as each one fell, the legend of Archon grew ever greater. 

Growing weary of the constant infighting, Archon oversaw a massive restructuring of his ‘family’. He turned them from a loosely affiliated rag-tag assortment of pirate crews into a single-minded killing machine whose only desire is to obey Archon’s every order. Under his leadership, the Kumo Crew has gone from being a feared local drug cartel to one of the most influential criminal syndicates in the galaxy. 

The systems he runs still function – in some cases better than before they were taken. The Kumo Crew rule by fear and are utterly intolerant of those who work against them, but in equal measure have been known to protect and reward those in the systems they have subjugated who have shown loyalty, brutally enforcing their own ruthlessly simple ethos. 

So far, Archon Delaine has only been active in the Pegasi sector, but some reports have begun to surface of Kumo Crew members beginning to move out of the sector.
