:PROPERTIES:
:ID:       cd8cabff-85e9-444f-b877-3f3a0cf28fa5
:END:
#+title: Segnen Exchange Announces Outpost
#+filetags: :galnet:

* Segnen Exchange Announces Outpost

/16 May 3305/

Segnen Exchange has revealed plans to build an outpost in the Synuefe EN-H d11-96 system.  

CEO Cedrik Stone gave the following statement:  

“As Zende Partners has graciously provided a transport service to Guardian space, it makes sense for my company to support the increased pilot activity in that area. Segnen Exchange can offer a variety of services to those travelling to the area.” 

“Segnen Exchange thrives at the forefront of innovation, and the wealth of artefacts soon to flow through Synuefe EN-H d11-96 offers fantastic opportunities in the field of advanced Guardian-human technology.” 

The announcement, coming so soon after Zende Partners established The Prospect in the same system, has received a mixed response from business analysts. Some view the move as likely to trigger direct conflict between the two corporations, while others believe the presence of both companies can only benefit the research initiative.
