:PROPERTIES:
:ID:       11e9d3ec-fbe5-4166-b136-e84666ff1860
:END:
#+title: Community Goals: Alliance to Build New Outpost
#+filetags: :Alliance:CommunityGoal:3302:galnet:

* Community Goals: Alliance to Build New Outpost

/22 Dec 3302/

Alliance Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has announced plans to construct a planetary outpost in the California Nebula. In a statement, Mahon explained that the new outpost would serve as a centre for xenobiological and astronomical research. He went on to say: 

"We have placed an open order for Geological Equipment, Hazardous Environment Suits and Surface Stabilisers for use in the construction of this new outpost, and authorised 160 SOAR to reward pilots who deliver these materials to Tshang City in the Furuhjelm III-674 system." 

To ensure those contributing materials can do so safely, 160 SOAR has also placed a kill order on all wanted ships operating in the Furuhjelm III-674 system, and has promised to reward pilots who deliver bounty vouchers to Tshang City. 

The campaign begins on the 22nd of December 3302 and will run for two weeks. If the final target is met earlier than planned, the campaign will end immediately.
