:PROPERTIES:
:ID:       78a45711-d0fb-41d8-91d5-a5b1263cb11b
:END:
#+title: Freelance Report: Canonn at Full Tilt
#+filetags: :Federation:3302:galnet:

* Freelance Report: Canonn at Full Tilt

/27 Jun 3302/

Following a recent statement from Admiral Maxton Price of the Federal Navy concerning Farragut Battle Cruisers in the Merope system, [[id:941ab45b-f406-4b3a-a99b-557941634355][Dr Arcanonn]] of the Canonn Interstellar Research Group has responded: 

"Admiral Price's authoritative assurance is most welcome. Canonneers and other researchers can hereafter refer to his words as we learn more about the barnacles, and why the Unknown Artefacts point towards Merope." 

Dr Arcanonn also confirmed that barnacle sites had been located in the Witch Head Nebula, while Canonn vessels continue to search for barnacles in other nebulae. 

Concluding his statement, [[id:941ab45b-f406-4b3a-a99b-557941634355][Dr Arcanonn]] commented on the elusive Unknown Probes – believed to be related to Unknown Artefacts. 

"We are now examining an Unknown Probe secured by my esteemed colleague Professor Monkey D Luffy. Early research indicates that it orients itself towards Merope 5 C, a site of barnacle proliferation. Obviously, Merope remains under intense scrutiny." 

Commander Nicholas Powell
