:PROPERTIES:
:ID:       8b67a0cb-7119-4484-be83-d83ed3ad6fb6
:END:
#+title: Enhanced Missile Rack Initiative Concludes
#+filetags: :3307:Federation:galnet:

* Enhanced Missile Rack Initiative Concludes

/12 Feb 3307/

*Pilots Federation ALERT* 

Deliveries of mined materials have allowed the engineer [[id:cb71ba02-e47b-4feb-a421-b1f2ecdce6f3][Liz Ryder]] to make a one-off modified ship module widely available. 

The module is a fully engineered lightweight and high capacity Class 2 Seeker Missile Rack with thermal cascade. It was only available for a brief period in October 3306, but can now be purchased from any human technology broker. 

Freshly mined bromellite, lithium hydroxide, osmium and samarium were delivered by a large number of pilots. Due to the volume of shipments received, the initial amount of materials required by customers to purchase the weapon has been temporarily reduced. 

Liz Ryder made this statement from her Demolition Unlimited workshop: 

“Thank you to everyone who helped launch – so to speak – this module onto the market. I hope that engineers and tech brokers can continue working together on providing more options to the galactic community.” 

Pilots who delivered commodities for this initiative can now collect their rewards from Awyra Flirble in the Eurybia system.
