:PROPERTIES:
:ID:       4587cc17-1353-4789-9922-e50788adf412
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/8d1c5d50-d867-4157-9a32-b661a98ae289?resourceVersion=id%3A4843
:END:
#+title: Core Dynamics Funds Takeover with Ship Discounts
#+filetags: :Alliance:galnet:

* Core Dynamics Funds Takeover with Ship Discounts

/14 Dec 3306/

*Pilots Federation ALERT* 

Prices for several Core Dynamics vessels have been temporarily reduced, as part of an attempt to purchase Lakon Spaceways. 

The shipbuilding corporation has applied a 30% discount to sales of the Eagle Mk II and the Vulture. There is also a 20% discount on sales of Federal Assault Ships, Federal Dropships and Federal Gunships, although the Federal Navy rank requirements for each vessel continue to apply. 

The reduced prices are expected to last until the 30th of December 3306. 

Core Dynamics recently made a proposal to acquire rival company Lakon Spaceways, which rejected the offer then applied markdowns to its own ships to increase short-term profits.  

The Alliance Tribune’s business reporter Irfan Karim speculated on these developments: 

“CEO Jupiter Rochester remains tight-lipped on the reasons for these discounts, but it seems likely that he is raising funds for a more aggressive bid. Rumours are circulating of Lakon investors being bribed to sell their shares, or coerced into demanding that the board of directors accepts ownership by Core Dynamics.”  

“Many industry analysts are convinced that a hostile takeover of Lakon Spaceways is underway. If successful, we could see vessels that are commonly associated with the Alliance – such as the Chieftain and Type-10 Defender – manufactured by a Federal corporation in the future.”
