:PROPERTIES:
:ID:       55458d28-d34f-4c42-8c48-2dcebc51c5e0
:END:
#+title: Azimuth’s Plan Elicits Further Reactions
#+filetags: :Empire:Federation:Alliance:Thargoid:galnet:

* Azimuth’s Plan Elicits Further Reactions

/15 Jul 3308/

Prominent figures on the political stage have commented on [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s anti-xeno operation in the HIP 22460 system. Key points from each are collated below. 

Archon Delaine: “My opinion on the Thargoids remains the same: burn them all! As I stated at the Galactic Summit, the Kumo nation stands ready to help wipe out these alien scum.”  

Yuri Grom: “I trust [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] as little as I trust the Federation. What guarantee do we have that this Proteus Wave will not be turned against human targets, once the Thargoids are dealt with?” 

Senator Zemina Torval: “Azimuth Biotech has emerged as a strategically significant corporation. I’ve advised the Imperial Senate to establish long-term commercial links that are mutually beneficial.” 

Hadrian Augustus Duval: “The Thargoids are a genuine threat. Yet I hope that our military collaboration with the Alliance and the Federation is a temporary measure only. The Empire must develop the strength to stand alone.” 

First Minister Octavia Volkov: “Thargoid attack is an ever-present danger for the Marlinist Colonies. We are observing events closely. Personally I do not view Azimuth as a trustworthy ally.” 

Ambassador Jasmina Halsey: “I’m pleased to see the Federation working closely with the Alliance, but disappointed that it is limited to anti-xeno matters. Whatever happens in HIP 22460, we should grasp this opportunity to increase diplomatic as well as military cooperation.”
