:PROPERTIES:
:ID:       74ecc49d-6b44-48aa-abf0-02fa7ec86de0
:END:
#+title: Marlinist Refugees Migrate from Alliance
#+filetags: :galnet:

* Marlinist Refugees Migrate from Alliance

/27 Apr 3308/

Over two million ex-Imperial citizens who sought sanctuary with [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] are now being repatriated to the Marlinist Colonies. 

Ambassador Elijah Beck, head of [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Office of Diplomatic Relations, announced: 

“Political refugees from Imperial systems have been arriving since late 3306, following the Empire’s crackdown on Marlinism. At the time they had no legal status or resources, and relied entirely upon the charity of local factions for their survival.” 

“Our successful negotiations with the Marlinist Consulate have now led to a solution. The Assembly will fund safe passage to the Marlinist Colonies for all refugees in Allied space. Pending security checks, they will be granted full citizenship.” 

The decision was welcomed by First Minister Octavia Volkov: 

“Thanks to the Alliance’s generosity, any Marlinists currently within their territory can now take advantage of free transportation to a colony system of their choice. There we will provide state support and work opportunities, to help them establish new permanent homes.” 

“More than a million people who fled the Empire are still unaccounted for, having dispersed throughout the core systems. I call for them to contact us via the consulate, and join our growing republican society.”
