:PROPERTIES:
:ID:       d236a0cf-b80e-4594-9658-0744c7cbb620
:END:
#+title: Community Goal: Empire Appeals for Meta-Alloys
#+filetags: :3302:galnet:

* Community Goal: Empire Appeals for Meta-Alloys

/28 Jul 3302/

As the galaxy becomes increasingly focused on the meta-alloys, the Empire has issued a galaxy-wide request for the controversial material. A spokesperson for the Zagoro Imperial Society, which is coordinating the appeal, released the following statement: 

"We don't yet know all the applications of the meta-alloys, but their ability to counter the harmful effects of the Unknown Artefacts indicates a potentially significant relationship between them, the Artefacts and, presumably, the unknown probes. It would therefore be unwise to let anyone to establish a monopoly on this material." 

"By supporting this initiative, you can help ensure that humankind is ideally positioned to meet the future – whatever it may hold." 

It is presumably not immaterial that the Empire's initiative coincides with a Federal campaign to establish a new outpost on the planet HIP 17225 A 1 – a known barnacle site. 

The Zagoro Imperial Society has promised to reward pilots who deliver meta-alloys to Axon Station in the Zagoro system. The campaign begins on the 28th of July 3302 and will run for one week. If the Empire's targets are met earlier than planned, the campaign will end immediately.
