:PROPERTIES:
:ID:       730a15a7-d06a-465a-a34a-08558f852729
:END:
#+title: Prism Senator Continues to Woo Federation Residents
#+filetags: :Empire:Federation:3301:galnet:

* Prism Senator Continues to Woo Federation Residents

/17 Mar 3301/

Lady Kahina Tijani Loren's unofficial entourage has begun a tour of the outer gas giants in the Sol system. Hundreds of privately owned Federation-registered vessels have turned out to greet the Senator, in lieu of an official welcome, as she continues her passage through the Sol system despite continued apathy from officials. 

Requests for interviews from the diplomatic representatives on Mars have been turned down, but one, rather stressed, aide was quoted as saying, "Listen. We have no intention of jumping through hoops for some jumped-up Imperial prima donna who won't do the paperwork properly. That's off the record, yes?" 

Questioned on this at a Merchants Guild reception hosted on Titan, Lady Kahina was quoted as saying, "We Imperials often do get accused of being arrogant and overbearing, but at least we're good at it."
