:PROPERTIES:
:ID:       b010d59d-6784-464e-95fa-4fc3ee87ac20
:END:
#+title: Galactic News: Perpetrators of Darnielle's Progress Heist Identified
#+filetags: :3303:galnet:

* Galactic News: Perpetrators of Darnielle's Progress Heist Identified

/24 Mar 3303/

Three of the five individuals responsible for the recent theft of meta-alloys from Darnielle's Progress have been positively identified, following analysis of starport security footage. Remarkably, one of the perpetrators has been acknowledged as Commander Salomé, also known as Kahina Tijani Loren. 

Loren was sentenced to life imprisonment last year for the attempted murder of Admiral Denton Patreus, but when her convoy was destroyed en route to Koontz Asylum it was assumed she had been killed. 

Responding to the news, Imperial authorities promptly placed a galaxy-wide bounty on Salomé to the tune of 500,000 credits. 

Meanwhile, Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] released a brief statement: 

"Commander Salomé is a disgraced senator and a convicted murderer. She incites violence wherever she goes, and in the interest of public safety she must be stopped. I urge all those loyal to the Empire to deliver justice to this criminal." 

Salomé's accomplices have been identified as former MetaDrive employee [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Raan Corsen]] – previously believed deceased – and former Junior Alliance operative Tsu Annabelle Singh. The Empire has placed sizeable bounties on both individuals. 

Imperial military sources issued the following advice to those interested in pursuing these bounties: 

"These individuals should be considered armed and dangerous. Make no attempt to communicate with them. Shoot on sight. Visual evidence of a target's death will guarantee the relevant bounty." 

Salomé's current location is unknown, but she is believed to have fled the core systems.
