:PROPERTIES:
:ID:       6c407ecc-075e-4fc6-907a-28449ecf4d15
:END:
#+title: Fuel Rats Complete 1,000th Rescue
#+filetags: :3301:galnet:

* [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel Rats]] Complete 1,000th Rescue

/26 Aug 3301/

Fuel Rats Complete 1,000th Rescue
 
Heroes: that's what some call the [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel Rats]]. Ever since launching
their emergency fuel delivery service a little over two months ago,
the Fuel Rats have made an impact on the lives of over 1,000
commanders who would otherwise have faced a long spacewalk home.

For one stranded commander, over 31,500 light years from inhabited
space with five months’ worth of exploration data on board, the [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel
Rats]]’ service was greatly appreciated. Commander [[id:85cdabdd-7a6e-4f90-a2b1-fe434fe3a786][Paul Kavinsky]], in
partnership with Commander [[id:f0a7a516-4d16-4e97-8bc0-f39d6844b92b][Rusticolus]], made an incredible high-speed
transition to the far side of the galaxy to rescue Commander
[[id:14fe6750-1266-4c3a-8737-1e2eb20e863f][TheHairyMob]].

Commanders [[id:8c6e19e1-9523-4321-a333-41cacd7a47ee][Anuranium]] and [[id:7a203bd3-fb88-4152-b39b-36fce7a943a9][Domaq]] also demonstrated the lengths to which
the [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel Rats]] will go. High above the galactic plane, 2,800 light
years north of [[id:84d9b01d-a9d6-47d9-b9f9-f6154233e585][Sagittarius A*]], a commander found himself stranded with
no hope of returning home under his own power. The limited number of
nearby stars made locating the hapless commander exceptionally
difficult, but the rats found their man.

A little closer to home, Commanders [[id:e42f0fc8-f8d9-4535-9dc4-f603fa0c34a4][Aitken]] and [[id:3adb9da0-dea0-474d-a346-135306bf53ad][Dardevel]] were not to be
outdone. Commander [[id:158cc7a9-09fb-4d14-9980-5f2b8e3f2257][Ghetto King]] was only moments away from drawing his
last breath, with only two seconds of emergency air remaining, when
the [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel Rats]] swooped in to save the day.

This reporter joined the [[id:de6c1eee-a957-4d48-a840-f3fe15b5801b][Fuel Rats]] to witness a rescue mission
firsthand. I experienced a mix of adrenaline and warm satisfaction in
knowing I had made a positive difference to another pilot’s fate.

Commander [[id:3fa4a5b4-c9e2-4d08-ba8e-8e2e8f21c0a3][Ceska Zbrojovka]] 

[[id:cd6c18b5-7020-46f3-a197-4769933ca5a8][Radio Sidewinder News]]
