:PROPERTIES:
:ID:       d905ae5c-ad06-4bf9-be8d-6176261eb25c
:END:
#+title: Galactic News: Alliance Initiative Successful
#+filetags: :Empire:Federation:Alliance:3302:galnet:

* Galactic News: Alliance Initiative Successful

/21 Apr 3302/

An Alliance spokesperson has announced that the campaign to establish a new outpost received the wholehearted support of the galactic community. The spokesperson confirmed that significant quantities of robotics, semi conductors and auto fabricators were delivered to [[id:d8f9e754-4f57-4123-b488-118f0755df72][Noti]] Dock, allowing construction of the new station to begin. 

Harlyn Tavistok, a member of the Alliance Assembly who has been overseeing the campaign, released a brief statement to the media: 

"We are extremely grateful for the public's support, which has been integral to the success of this campaign. Construction of the new outpost is scheduled to begin at once. Soon we will have a valuable new resource in the sector." 

But the success of the campaign has been overshadowed by criticism from Imperial and Federal commentators, who questioned the purpose of the new outpost. Some have asked whether the Alliance's avowed intention to 'maintain awareness' is in fact an allusion to monitoring Imperial and Federal activity. Others have speculated that the outpost campaign might be the first phase of an expansion initiative. 

Harlyn Tavistok declined to address the rumours.
