:PROPERTIES:
:ID:       daa501b9-8bc9-4be9-a8d1-fa0ebe30baf1
:END:
#+title: Aisling Opens Art Installation on Emerald
#+filetags: :3301:galnet:

* Aisling Opens Art Installation on [[id:465800ad-1e27-44fa-9b4b-5ca23bcc36ce][Emeral]]d

/22 May 3301/

The People’s Princess made an appearance in [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] late last night to attend the opening of [[id:465800ad-1e27-44fa-9b4b-5ca23bcc36ce][Emeral]]d’s newest art installation, ‘Prism’s Shades’, a multi-sensory experience that uses experimental light and sound projection technology to stimulate a series of empathic responses from its audience. 

Aisling dazzled crowds by dressing in a long-sleeved ruby red evening gown, adorned with painite sparkles. She accessorised with an equally stunning tinted visor, fashionably stamped with Aisling’s personal crest. 

Surprisingly, the people’s princess only stayed at the installation for a little over an hour. Aisling left the show long before midnight, citing exhaustion from her recent activities in the [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]]s as the reason behind her early exit.
