:PROPERTIES:
:ID:       41a374b3-9e6e-4763-88ee-c3bb2a7c73f6
:END:
#+title: Olympus Corp Thanks the Fuel Rats
#+filetags: :galnet:

* Olympus Corp Thanks the Fuel Rats

/09 Oct 3301/

Commander F-Zlim was on the home stretch of a six-month galactic tour when a CO2 leak knocked him out. When he woke to the blare of alarms, his ship, the 'Korblah', was out of fuel. Using long-range comms, F-Zlim notified fellow Commanders at the exploration arm of the Olympus Corp. that he had exactly two minutes and 48 seconds of air remaining. Using the last of the ship's backup battery, he transmitted his final location via the captain's log module, and then he called the Fuel Rats. 

"I had 50 seconds of oxygen left when the first refuel drone arrived," said Commander F-Zlim. "It was the most exhilarating and frightening experience in the six months of my journey. The Fuel Rats saved me and I am eternally grateful." 

In recognition of for their valiant service, the Olympus Corporation has chosen to award the first-ever Korblah Medal to Commanders Orphius and Lokda Babybel of the Fuel Rats. 

Commander Soundwave
