:PROPERTIES:
:ID:       cc35718f-5e5e-4766-a060-619900373f28
:END:
#+title: Sirius Vows to Defend Alliance
#+filetags: :galnet:

* Sirius Vows to Defend Alliance

/25 Apr 3308/

Sirius Corporation has claimed that the recent [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] incursions prove the necessity of its strategic defence pact with the Alliance. 

The Didio, Novas and Sosong systems are currently withstanding a coordinated attack from large numbers of [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] vessels. Independent pilots have rushed to their aid while the three superpowers prepare their respective fleet responses. 

A press conference was held by Admiral Nikolas Glass, the liaison between [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Defence Force and the Sirius Navy: 

“This unexpected onslaught only underlines the Alliance’s need for military support. The [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] can strike anywhere at any time, and Allied systems such as Didio are vulnerable. Only with Sirius Corporation’s help can we ensure their safety.” 

Journalists pointed out that the Council of Admirals had selected Admiral Rachel Ziegler to lead their anti-xeno taskforce instead of Admiral Glass, despite that being his specific area of expertise. He replied: 

“Well, as you know, the pact is still within its trial period and hasn’t yet been ratified by the Assembly. So there are limits to how involved Sirius Corporation can be at this stage. I’m sure my colleague will do a fine job while I focus on providing broader support to the Didio system, such as additional secondments to Salvation’s fleet.”
