:PROPERTIES:
:ID:       dfeb0483-9b69-48a6-b2ef-19784de9f0f3
:END:
#+title: Congress Votes Against Hudson Contravention
#+filetags: :galnet:

* Congress Votes Against Hudson Contravention

/21 Mar 3309/

President Zachary Hudson’s motion to allow him to serve a second term of office has been defeated by congressional vote. 

The proposal would have temporarily repealed the 77th amendment of the Federal Accord, which sets a maximum presidential term of eight years. A narrow majority voted not to accept this change to the Federation’s constitution. 

President Hudson addressed Congress following the announcement of the result: 

“The Federation’s democratic principles are paramount, and so I accept the decision of this chamber. I only hope that the disruption caused by a shift in leadership does not weaken our ability to withstand the current challenges. It is with total conviction that I say the Republican party will achieve victory in the ongoing war and maintain security within our borders. I intend to support the next Republican candidate to the best of my ability.” 

This outcome confirms that President Hudson’s administration will officially end shortly after the election, which is expected to take place in June but with no official date set. However, considering his many commercial and military connections, Hudson will remain a powerful political figure with a loyal supporter base. 

Nominees for the Republican Party’s new presidential candidate have begun lobbying for support. The frontrunners are three senior members of Hudson’s cabinet: Vice President Jerome Archer, Secretary of State Lana Berkovich and Grand Attorney Edwin Espinosa. Congressman Thandeka Qwabe has also been nominated despite her relative inexperience. 

The Liberal Party’s candidates, Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] and her running mate Isolde Rochester, have launched their presidential campaign. Several independent candidates are challenging the two main political parties, but only the famous entrepreneur [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] is being viewed as a serious threat.
