:PROPERTIES:
:ID:       bac82eb0-bf8e-4472-8ca4-953008b07d93
:END:
#+title: Conditional Amnesty Agreed for Neo-Marlinists
#+filetags: :Alliance:galnet:

* Conditional Amnesty Agreed for Neo-Marlinists

/20 Apr 3307/

The Neo-Marlinist Order of Mudhrid has been granted sanctuary in the Marlinist Colonies in return for revealing the identities of the NMLA’s leaders. 

The faction’s survivors arrived in the Hyades Sector RO-P b6-2 system after being defeated by Imperial forces. The Marlinism Reformation Party agreed to offer political asylum, despite all three superpowers demanding the refugees’ arrest. 

Imperial Senator Lorcan Scordato, who was visiting the Colonies on a fact-finding mission, announced: 

“After meeting the Neo-Marlinists and the Marlinist Parliament, I have secured an agreement. The Landgrave of Mudhrid and his inner circle will cooperate fully with ACT to provide details on the senior leadership of the NMLA. In return, they will receive life imprisonment at a local detention facility.” 

“The Steel Majesty’s population will undergo security vetting by the Marlinist Constabulary to identify extremists. The remainder will be permitted to remain in the system and apply for citizenship.” 

Chancellor Blaine has approved the proposal, commenting that it was “precisely the sort of creative solution the Emperor requires”. Responses from the Alliance and Federation were mixed, but there was broad agreement that targeting the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] was the priority. 

Minister Aaron Whyte, elected leader of the Marlinism Reformation Party, publicly thanked Senator Scordato for negotiating a peaceful resolution.
