:PROPERTIES:
:ID:       3cc3f4f4-a784-4876-ad1a-1c023007fb18
:END:
#+title: Aegis: “Be Alert for Thargoid Counterattacks”
#+filetags: :Thargoid:galnet:
* Aegis: “Be Alert for Thargoid Counterattacks”

/10 Sep 3310/

*Pilots’ Federation Alert* 

Aden Tanner, special military advisor to the Aegis project, has warned of the potential for targeted Thargoid assaults on key military locations. 

Speaking during a recent graduation ceremony for the latest batch of Federal AX recruits, Tanner warned against complacency following the destruction of Titan Thor last month. 

“It may seem that we have the upper hand in this war. There’s no shame in taking pride in our accomplishments, and we’re certainly in a better place than when the Thargoid invasion started.” 

“But the Thargoids are just as dangerous as they’ve ever been. Entering a conflict zone with anything less than full focus would be a terrible mistake. Think of how hard you’d fight if you thought the Thargoids were driving our fleets back a little further each day. That’s the situation our enemy finds themselves in.” 

“In fact, while our forces push towards the remaining two Titans, Aegis is always watching for counter-attacking efforts behind our front lines. We know the Thargoids can travel via portal technology, allowing them to spring ambushes on our ports beyond any fleet blockades. What we're less clear on is how the aliens assign value to potential targets.” 

“Important systems are well protected, but we're playing catch-up when predicting the Thargoids’ next move. When you join our AX forces in combat for the first time, remember: look out for each other, and always expect the unexpected.”
