:PROPERTIES:
:ID:       6f789e5c-d6e8-4532-aaad-656f430696bf
:END:
#+title: Project Seraph Victim Seeks Revenge
#+filetags: :Thargoid:galnet:

* Project Seraph Victim Seeks Revenge

/10 Jun 3308/

The location of an INRA base in the DG Canum Venaticorum system was revealed by a survivor of the notorious Project Seraph. 

Professor Alba Tesreau, former head of research at Aegis, initially received the tip-off from an anonymous source but has now provided clarification: 

“Further communication with my source has revealed that she was once a ‘candidate’ of Project Seraph, a now-abandoned operation run by Azimuth Biochemicals several years ago. At the Oaken Point facility in the HIP 26176 system, scientists attempted to directly interface with Thargoid scout vessels by grafting neural and physiological implants into living subjects.” 

“Most of these horrific experiments ended in failure or death, but the subject classified as D-2 escaped from Oaken Point by stowing away on a trader’s ship. Since then she has used her inside knowledge to investigate Azimuth, confirming Aegis’s belief that the corporation is still active.” 

“D-2 asked me to make the following message public: ‘Tell the Witch that I remember everything. I want him to know that the [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]] came from me.’” 

The INRA base’s logs suggest that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s real name is Dr Caleb Wycherley, Azimuth Biochemicals’s vice-president of research at the time of recording. If D-2’s accusation is true, it would mean that Wycherley has survived for over two centuries and was conducting unauthorised xenological experiments under the pseudonym ‘The Witch’. 

Many supporters of [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] believe that the Project Seraph logs were fabricated by Aegis to undermine their rival’s anti-xeno operations. Neither Salvation nor his partners, Taurus Mining Ventures, have yet made an official statement.
