:PROPERTIES:
:ID:       985832d7-0bb0-4ecf-b37a-61bc33dfca12
:END:
#+title: Vitadyne Nanomeds Campaign
#+filetags: :Federation:Alliance:3305:galnet:

* Vitadyne Nanomeds Campaign

/24 Jan 3305/

Professor [[id:c39e36c5-83ba-4e22-8dc1-c5705b33910a][Katrien Rook]] of Vitadyne Labs has launched an initiative to establish a new pharmaceutical production facility.

In a statement, Professor Rook said:

“Vitadyne Labs lacks the infrastructure to mass-produce nanomedicines, so we have invited two pharmaceutical companies to bid for a distribution licence. The company that puts forward the most convincing proposal will secure the contract.”

The companies in question are Neomedical Industries, which supplies Alliance and independent systems, and the Vandermeer Corporation, which operates exclusively within Federal space. Both have requested advanced medicines, computer components and auto fabricators for the construction of nanomed manufacturing plants.

Deliveries for Neomedical Industries should be made to Alignak Jet Legal and Co at Piserchia Port in Alignak while shipments for the Vandermeer Corporation should be delivered to the Liberals of Kuma at [[id:2ad9d91c-0e3a-4d7b-837e-4d2509907f4d][Elion Dock]] in Kuma.

The competing initiatives begin on the 24th of January 3305. If either campaign meets its target earlier than planned, that campaign will end immediately.
