:PROPERTIES:
:ID:       a6bce3e0-1a41-440c-b140-58861e466c43
:END:
#+title: Community Goal: Diamond Frogs Campaign
#+filetags: :CommunityGoal:3303:galnet:

* Community Goal: Diamond Frogs Campaign

/08 Dec 3303/

The Diamond Frogs, a mercenary outfit based on the lawless fringes of the Capricorni sector, have announced plans to build a new installation in the 63 G. Capricorni system.

The faction’s current base of operations has become virtually uninhabitable, as its power and cooling systems have been pushed past their limits.

In support of this goal, the faction has placed an open order for Beer, Liquor, Coffee, Legal Narcotics, [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]], [[id:34acf2f1-676d-4e52-86f4-80dc606e435c][Power Generators]] and Superconductors. They have promised to reward pilots who deliver these commodities to Skvortsov Orbital in the 63 G. Capricorni system.

The campaign begins on the 7th of December 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
