:PROPERTIES:
:ID:       00a5a9c5-4c22-46ea-bc07-cc52dbbbbffb
:END:
#+title: Nova Imperium Targeted by Superpowers
#+filetags: :galnet:

* Nova Imperium Targeted by Superpowers

/03 May 3307/

The isolationist group faces attack by both Federal and Imperial factions, after accusations that Imperator Hadrian Duval is the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] mastermind. 

The League of Mandu arrived in the Paresa system last week and quickly established a foothold. Admiral Natalia Lee, commanding the Harmony’s Shield megaship, announced: 

“Our purpose is to eliminate the terrorists who slaughtered so many Federal citizens. We advise [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] to stand aside and allow us to deliver justice.” 

Magister Julius Halstrom of the Peraesii Empire Consulate declared: 

“In the name of the Emperor, we stand ready to purge the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] from the Paresa system – and [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] too, unless they withdraw.” 

Hadrian Duval has broadcast a message via Paresa News Network: 

“The [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] faked my identity when dealing with the Neo-Marlinist Order of Mudhrid, knowing the superpowers would do their work for them by killing another Duval. Nova Imperium will defend itself if necessary, but we are not responsible for any terrorist attacks.” 

ACT is still attempting to corroborate evidence provided by the Landgrave of Mudhrid. Praetor Leo Magnus, Nova Imperium’s security chief, is reportedly aiding their enquiries. 

The Senate has urgently requested direction from the Emperor, but Chancellor Blaine declared “Her Majesty cannot pass judgement upon a live investigation.”
