:PROPERTIES:
:ID:       be8a1ab5-b621-4044-9cfd-fe5f12eb2782
:END:
#+title: Aliens Kidnapped the President
#+filetags: :3301:Empire:Federation:galnet:

* Aliens Kidnapped the President

/14 Aug 3301/

Aliens Kidnapped the President 
 
The spectre of President Halsey’s disappearance in Starship One refuses to die down. Despite the findings of the official report some claim that the matter is far from closed. One such person is self-proclaimed conspiracy expert [[id:0766a856-8f47-43b8-9242-b40309dbf07f][Ricardo Bentonio]] on his investigative show ‘The Hidden World’: 

“They took her for their own purposes. Not the lizard people from [[id:0a33b305-8f49-4a9f-8c0a-177cab9cd72c][Andromeda]], that’s the Imperial Dynasty. She’s been taken somewhere different.” 

Federal Navy officials refused to comment on this allegation. One Congressman was overheard joking “Does anyone listen to that loon’s shows? Except his precious lizard people from [[id:0a33b305-8f49-4a9f-8c0a-177cab9cd72c][Andromeda]], of course!”
