:PROPERTIES:
:ID:       c80a4b02-21f2-4719-b79c-0c7c2a842cc8
:END:
#+title: Obituary: Prince Harold Duval
#+filetags: :galnet:

* Obituary: Prince Harold Duval

/21 Sep 3306/

The Imperial Herald has published an obituary of Prince Harold Duval, who was assassinated by NMLA terrorists. 

“Born in 3230 to Emperor Hengist, Harold Duval reacted against his father’s puritan lifestyle by filling his days with partying and debauchery, becoming the black sheep of the Duval family.” 

“It was probably accidental that Harold had a child with entertainer Imogen Gabrielini, but they married shortly before her narcotics-related death. His daughter, Princess Aisling Duval, has always spoken warmly of her loving father.”  

“Emperor Hengist eventually decreed that his son was not fit for the throne, despite being his only heir. Harold never contested this, perhaps relieved to allow half-sister Arissa Lavigny-Duval to take his place.” 

“In recent years Harold became a recluse on Capitol, suffering ill-health from a lifetime of excesses. But a father’s protective instinct motivated him to travel to Aisling’s home system after it was attacked. Tragically, despite always renouncing power, merely being a Duval made him a target to those same republican terrorists.” 

“As the Empire mourns Prince Harold, suspicions arise that the NMLA were aided by inside knowledge of his ship’s itinerary and security, throwing an uneasy shadow over the legacy of this eccentric, endearing man.”
