:PROPERTIES:
:ID:       a7879747-1673-4931-b33e-be0397359565
:END:
#+title: Spy Robot Investigation Redirected
#+filetags: :Federation:3304:galnet:

* Spy Robot Investigation Redirected

/03 Nov 3304/

The [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]] has abruptly terminated its investigation of The Mars Tribune regarding personal administration robots fitted with hidden surveillance programs. 

Although interviews with Tribune employees were underway, it has been alleged that a senior figure in the FSS ordered the task force to focus elsewhere. 

The Tribune’s owner, billionaire [[id:74cae77e-fab1-4a22-9c31-daaa15d8fd0e][Kingsley Cordova]], stated: 

“I’m pleased that our innocence has been accepted, and I’m confident that the guilty parties will soon be found.” 

An opinion piece in [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]] from chief editor Lena Ravenhill took an alternative view, however: 

“Last week, Cordova suggested the spy robots could share the many secrets they’ve gathered, and suddenly the FSS is ordered to leave The Mars Tribune alone. Does anyone really think this is coincidence? How many powerful people are frightened of what Cordova might reveal about them?”
