:PROPERTIES:
:ID:       55779fe3-1592-4ac2-a8c3-e65bf8ced40c
:END:
#+title: Battle of Summerland Ends NMLA Threat
#+filetags: :3308:Empire:Federation:galnet:

* Battle of [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]] Ends NMLA Threat

/24 Feb 3308/

*Pilots’ Federation ALERT*

The Empire has carried out reprisals against the [[id:caf0242f-7093-4322-9b3e-7a19a21f1b17][rogue]] faction
[[id:57907627-04a8-4987-96c2-535c101e958b][Darkwater Inc]] in the [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]] system.

The private military firm had trained [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terrorists and held Emperor
[[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] captive, on the orders of a cabal of senators
named the [[id:ffa239ce-f149-4c43-9455-26a4fa753e1c][Lords of Restoration]].

[[id:57907627-04a8-4987-96c2-535c101e958b][Darkwater]] mustered an impressive armada, but these were no match for a
combination of superpower forces and independent pilots. Colonel [[id:01f68135-e4ba-400b-856d-bd938dfd7cad][Ronan
Brock]], the mercenaries’ leader, was killed during the fighting when he
fled from the [[id:fdd32864-53fd-4eef-83ed-5cce54c199a7][Onyx Storm]] megaship and was shot down by Imperial
auxiliaries.

[[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Emperor Arissa]] praised all those who helped destroy [[id:57907627-04a8-4987-96c2-535c101e958b][Darkwater]], and
declared: “Let the Battle of [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]] mark the victorious end of our
bitter war against both the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] and the traitors who sought to
destabilise the Empire.”

[[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][ACT]] clarified that “Although there may always be Neo-Marlinist
extremists, the large-scale threat of the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] has finally been
nullified.” All data obtained from the terrorists’ [[id:22dfd239-84ed-4b35-aa95-bc955ca95e8b][Omega Grid]] network
has now been shared with the relevant security agencies.

With [[id:57907627-04a8-4987-96c2-535c101e958b][Darkwater]] eliminated, the Empire has installed a new controlling
faction into the [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]] system. The [[id:0198f05b-ee89-4d10-92ff-e5095c94e401][Praetorian Vigil]] will report
directly to the Emperor and govern in her name.

The [[id:d057639b-d0ac-49a5-a39e-3d44e3dd63a3][Summerland Patron’s Party]] will redeem [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][combat bonds]] and provide
other rewards at the starport [[id:97deaf9c-70be-4d96-943f-a0e6ab100712][Henry O’Hare’s Hangar]]. A [[id:b2b2d9ee-9c33-4a0b-b3ce-82cfa362577e][permit]]
exemption allowing all independent pilots to enter the [[id:ba152f8a-d8af-4611-b8ac-0b32f3258dd0][Summerland]]
system will remain active for the next two weeks.
