:PROPERTIES:
:ID:       385f0f57-c589-4e9d-961f-e0a95ea5ad76
:END:
#+title: Community Goal: Putting LP 339-7 on the Map
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: Putting LP 339-7 on the Map

/15 Dec 3302/

Dr [[id:246ac86d-4a96-4fdc-907d-d8a84b142e70][Lewis Chapman]], CEO of the Starship Enterprises Corporation, has announced plans to transform the LP 339-7 system into a popular tourist destination. 

To achieve this, the Starship Enterprises Corporation intends to establish a wildlife reserve on the planet LP 339-7 4 A. The reserve will be occupied by various cloned Earth animals, genetically tailored to suit their environments, created by the Starship Enterprises Corporation. 

In support of this project, the corporation has placed an open order for progenitor cells, animal monitors, aquaponic systems, atmospheric processors, land enrichment systems and advanced medicines. The organisation has also placed a kill order on all wanted ships operating in LP 339-7, to ensure that those contributing commodities to the campaign can do so safely. 

The campaign begins on the 15th of December 3302 and will run for one week.
