:PROPERTIES:
:ID:       3180c69e-5482-4831-bc5e-47a7a97bd71e
:END:
#+title: Thargoid Cultists Prepare for Religious Voyages
#+filetags: :galnet:

* Thargoid Cultists Prepare for Religious Voyages

/06 Aug 3307/

Three megaships are being populated by the Far God cult, part of their latest effort to recruit members and find their alien deity. 

The first vessel, the Testament, will serve as a missionary ship and journey throughout the core systems, attempting to convert new followers to the Thargoid-worshipping sect. 

While the mystical cult is typically secretive in nature, Vox Galactica obtained a quote from a member named the Second Witness of the Seventieth Chapter: 

“The masses are deaf to the voice of the Far God. What you see as alien monsters, we view as messengers from a very real multi-dimensional being. The Testament will help us carry the word of Its imminent arrival.” 

Two other megaships have been outfitted for long-range journeys. The Perdition and the Sacrosanct will carry many thousands of cultists on what they view as a pilgrimage to the Far God. 

Dr Alfred Ulyanov, a leading exotheologian and expert on the religion, commented: 

“This fringe creed, which has survived endless abuse and attacks, has now reached a surprising level of organisation. Most of us associate the Thargoids with death and destruction, making it all the more remarkable that these people see only divinity.”
