:PROPERTIES:
:ID:       c2bc7c09-4866-4d97-8826-d6d674a92e89
:END:
#+title: Winters Condemns Oppression of Thargoid Cult
#+filetags: :Thargoid:galnet:

* Winters Condemns Oppression of Thargoid Cult

/10 Oct 3308/

The Popontia conflict and the mass arrest of [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cultists have received civil and political criticism across the Federation. 

Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] delivered a statement to [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“It is logical that any organisation supporting the Thargoids should come under scrutiny. But this does not justify the harsh and oppressive treatment of our own citizens for their religious beliefs. The Federal Accord safeguards their right to worship, as long as no laws are transgressed.” 

“The Federal Navy Intelligence Office has accused the cult of disseminating classified material and damaging anti-xeno operations. I demand that their evidence be shared with the High Court, so that a legal ruling can be made.” 

“I also call upon Congress to reject the secretary of state’s proposal to outlaw the Order of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]]. This is nothing more than a blatant effort to prop up President Hudson’s waning powerbase.” 

A multiple-choice survey held by Sol Today resulted in the majority selecting ‘traitorous cowards’ to describe cult members, showing that Hudson’s order is not without support. However, a Federal Free Press opinion poll suggested that many citizens are uncomfortable with hostile acts against ‘deluded but essentially innocent people’. 

The Perdition and Testament megaships have now withdrawn from their standard patrol between the core system and the Pleaides, presumably to avoid further acts of hostility from the Federation. Dr [[id:2bf69df4-bf62-4877-87eb-5158254f5fcb][Alfred Ulyanov]] observed that Federal citizens of the cult, along with the few remaining True Chapters adherents, were now concentrated aboard these megaships. Orthodox [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] hive-chapels are believed to still operate in Allied and independent systems.
