:PROPERTIES:
:ID:       53dc220d-a969-4f16-b973-d37174a3f84b
:END:
#+title: Marlinist Exodus as Imperial Lockdowns Continue
#+filetags: :Empire:Federation:3306:3269:galnet:

* Marlinist Exodus as Imperial Lockdowns Continue

/16 Oct 3306/

[[id:77cf2f14-105e-4041-af04-1213f3e7383c][The Empire]] has locked down more systems as part of an anti-terrorism operation, causing millions of Marlinists to flee from their homes.

Following [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terror attacks, martial law was declared in regions where the political beliefs of Marlinism are prevalent.

Citizens in several systems including 234 G. Carinae, Baltah'Sine, Beatis, CD-39 3269, Chana, HIP 39470, Mazahuanses and Nahuatl have evacuated en masse to avoid arrest. There are eyewitness reports of people crammed into whatever vessels they can find, often in unsafe numbers.

Vox Galactica featured this statement from Dr [[id:71f78d3e-edc5-423c-8b74-0bad5470c6f5][Jenna Fairfax]], a Marlinist community leader and advocate of democratic reform:

“This isn’t a search for terrorists – it’s a crusade against anyone who shares Marlin Duval’s dream of a Republic. Such brutal persecution leaves us no choice but to risk our lives by seeking sanctuary elsewhere.”

In the Senate, a handful of senators voiced concerns about the treatment of Imperial citizens, to which [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] responded:

“The security of the Empire is paramount. These worlds harbour a ruthless enemy that has already slaughtered thousands. We will not rest until the Neo-Marlinist poison has been cleansed, even if that means tracking down everyone who may carry this infection.”

The [[id:e9becd28-9644-42aa-afc8-7bba3ce10076][Imperial Navy]] is searching for all ships transporting Marlinist refugees, but there is evidence that some have reached systems controlled by the Federation.
