:PROPERTIES:
:ID:       c02d78bc-13a6-41f3-8b2e-380852af06db
:END:
#+title: Anti-Guardian field project yields breakthrough - New modifications available
#+filetags: :Federation:Thargoid:galnet:

* Anti-Guardian field project yields breakthrough - New modifications available

/19 Apr 3310/

*Pilots’ Federation ALERT* 

The engineer [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] has discovered a method of immunising existing Guardian modules against the effects of anti-Guardian fields. 

Earlier this year, [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] discovered that certain Guardian relics revealed and activated nanite clusters when exposed to specific electromagnetic frequencies. These nanites proved disruptive to Thargoid technology on a molecular level and, importantly, were entirely unaffected by anti-Guardian fields unlike other Guardian technology. 

In an urgent press conference, Aegis leadership announced a breakthrough in researching that latter quality. 

The following statement was given by Professor [[id:c2623368-19b0-4995-9e35-b8f54f741a53][Alba Tesreau]]: 

“Our knowledge of the Thargoids’ ancient adversary, the Guardians, is still so very limited, and yet Guardian technology has once again paved a way forward for humanity.” 

“We urge pilots to use the modifications we are producing to utilise any powerful Guardian modules in their possession. Use them to push back against the Thargoid threat. Use them to win this war.” 

Aegis went on to announce that the modifications can now be made at Ram Tah’s workshop in the Meene system.
