:PROPERTIES:
:ID:       a8e517fa-f6cf-46f3-bc45-82284f84420b
:END:
#+title: Imperial Slave Association Audited
#+filetags: :galnet:

* Imperial Slave Association Audited

/21 Aug 3301/

Imperial Slave Association Audited 
 
A surprise audit of the Imperial Slave Association was recently conducted by a special committee of the Imperial senate. The records and practices of the ISA were meticulously examined to ensure compliance with laws governing the treatment and transportation of Imperial slaves. The committee found numerous violations of transportation regulations in systems near Imperial borders, and numerous border-security officers and pilots were subsequently indicted for these violations. 

No serious violations concerning the treatment of Imperial Slaves were uncovered, though many warnings were issued to those who were found holding slaves beyond their fixed term of service. Imperial slaves found in these circumstances were restored to full citizenship and reimbursed for the labour they performed beyond their established term. 

The ISA issued a statement following the audit: 

“We wish to reiterate that the sale of Imperial slaves to non-Imperials and to systems beyond Imperial space is strictly prohibited. Any who are found engaging in this illicit activity will be held accountable." 

Commander Corrigendum
