:PROPERTIES:
:ID:       c21c3300-fdc8-47bd-b78d-5c416602b0ba
:END:
#+title: Emperor Decides Hadrian Duval’s Status
#+filetags: :3300:Empire:galnet:

* Emperor Decides [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]]’s Status

/16 Nov 3306/

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]’s request for her cousin, Imperator[[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Augustus Duval]], to be accepted into the Imperial Family has been denied. 

Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]]’s decision was delivered to the Senate by Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]]: 

“Her Majesty acknowledges that Hadrian is a Duval by blood, and offers royal pardons to him and his followers for previous crimes against the Empire. However, she does not bestow upon him the title of prince, nor offer any formal position within the Imperial Family.” 

[[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]] both expressed disappointment, but agreed to accept the decree. The Senate has now ratified the Treaty of Paresa, which removes Nova Imperium’s outlaw status in return for accepting Emperor Arissa’s rule and contributing to operations against the NMLA. 

The Imperial Herald’s political journalist [[id:745efc38-c548-40c0-81d2-82973c604d37][Cassia Carvalho]] commented: 

“This surprisingly even-handed judgement is widely seen as bowing to pressure from the Senate, where there is much loyalty to [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]. Some interpret it as atonement – or regaining political goodwill – for the purge of Nova Imperium in 3305, which included the execution of several senators.” 

“The image this projects is of an Empire coming together against the greater threat posed by Neo-Marlinists. But there is speculation that an alliance between the two youngest Duvals may one day challenge the Emperor for the throne.”
