:PROPERTIES:
:ID:       e1a12f9a-488f-4f96-ae43-054b0d18fb57
:END:
#+title: Merchant Marines Launch Operation Papercut
#+filetags: :3301:Empire:Federation:galnet:

* Merchant Marines Launch Operation Papercut

/24 Apr 3301/

Reports coming in from Eotienses indicate that a group of Federal Commanders, known as the Merchant Marines, are currently engaged in a series of unauthorised attacks against Imperial traders in the employ of Senator Patreus.    

In a statement released to GalNet, the Merchant Marines had this to say: 

“The Merchant Marines have launched Operation Papercut. We plan to blockade the Eotienses system in an attempt to stop Imperial traders from supplying Parkinson Dock with industrial materials. The group fears that High Tech production could turn Eotienses into a catalyser for the Imperial war machine already fuelled by Denton Patreus.” 

“The Marines intend to interdict all traders in the system and thus halt economic growth. Traders will be given a single warning to leave the system. Any further action will result in more aggressive coercion.” 

GalNet reached out to President Halsey’s office to request an official statement in regards to the Merchant Marines' actions. At time of press, the President’s office had not yet chosen to reply.
