:PROPERTIES:
:ID:       30ff513b-83de-428c-9232-2ad526c16b5f
:END:
#+title: ACT Disbanded Following Defeat of NMLA
#+filetags: :3308:Empire:Federation:Alliance:galnet:

* ACT Disbanded Following Defeat of NMLA

/07 Mar 3308/

The Alliance, Empire and Federation, have agreed to close down the [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][Affiliated Counter-Terrorism]] unit. 

A joint statement from all three superpowers stated: “ACT’s primary mission to locate and destroy the Neo-Marlinist Liberation Army has been successfully accomplished.” 

ACT was formed in March 3307 following the Nine Martyrs attacks, when the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] simultaneously bombed multiple starports. The independent taskforce rapidly took the lead in investigating the terrorists, calling upon the resources of many agencies, specialists and freelance pilots. 

The co-leaders of ACT have now returned to their respective security services. Captain [[id:ccaf380d-14e8-4a1a-9458-8c3bad87b25c][Saskia Landau]] was personally awarded the [[id:62a98a5a-d736-437c-a9b0-b3efaff999e8][Achenar Service Cross]] by Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]], in recognition of her key role in identifying the [[id:ffa239ce-f149-4c43-9455-26a4fa753e1c][Lords of Restoration]]. Landau has now accepted overall command of [[id:45d78e5d-27b7-48cb-97b2-012934be3180][Imperial Intelligence]], reporting directly to the Emperor.  

Captain Milo Castile, Inspector Mara Klatt, Praetor Leo Magnus and Senior Agent [[id:fb74a286-1688-41e8-9bec-9ef14adaaf1f][Tanya Ramirez]] have all been similarly commended for their successes. The joint statement also paid tribute to those members who lost their lives in the fight against terrorism. 

ACT was formed under the Cornelius-Lasky Convention, which was ratified at the Galactic Summit. The treaty requires governments to cooperate against large-scale threats to civilian populations, and is now commonly viewed as a historic achievement. Since it remains in force, ACT could be reformed in future if a similar threat to the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] arises.
