:PROPERTIES:
:ID:       21e459ef-5555-42b8-afbd-4332da7fdd34
:END:
#+title: Galactic News: Palin Announces Development
#+filetags: :3302:galnet:

* Galactic News: Palin Announces Development

/26 Oct 3302/

Professor [[id:8f63442a-1f38-457d-857a-38297d732a90][Ishmael Palin]], founder and former director of the Palin Institute, has released a statement concerning his ongoing research into meta-alloys. 

"I have discovered previously unidentified properties that could make the meta-alloys ideally suited to the development of robust new materials – materials that could be used to great effect in combat starships." 

"My research is still at an early stage and I am far from developing a working prototype, but the early signs are very encouraging. This discovery could herald a major step forward in the development of defensive technologies." 

Professor Palin has been researching meta-alloys from his personal research base on [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] A 3 a since he resigned from the Palin Institute in April. He closed his statement with a promise to share his progress with the galactic community.
