:PROPERTIES:
:ID:       abbec415-0311-40ad-83cf-aa6600b6ef58
:END:
#+title: Mahon Reprimanded over Reorte Conflict
#+filetags: :3308:Alliance:galnet:

* Mahon Reprimanded over Reorte Conflict

/25 Feb 3308/

The Alliance Assembly has delivered an official rebuke to its prime minister following the recent skirmish in the Reorte system. 

There have been heated debates following the conflict between Reorte Mining Coalition and Sirius Corporation. This was triggered by the megacorp’s unpopular attempt to establish a presence in the system as an anti-xeno defence partner. 

Councillor [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]] led a motion to censure against Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]], which successfully passed with a plurality of votes after some abstentions. The strongly-worded reprimand focused on ‘disregarding the Alliance’s principles by unilaterally forcing cooperation with Sirius Corporation’. 

After Mahon formally accepted the reprimand, Councillor Kaine addressed the Assembly: 

“This body does not have the right to govern its member systems without their consent. The strategic defence pact must become civil legislation rather than a military contract, so it can be passed as law.” 

“I call upon [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] to agree to these terms, or else to abandon the pact and remove Sirius Corporation’s forces from the Alioth, Arimpox, Di Jian and Leesti systems.”
