:PROPERTIES:
:ID:       0a7f6381-0bdf-472f-96ba-86637a1e82e6
:END:
#+title: Thargoids Return to Pleiades Nebula
#+filetags: :Thargoid:galnet:

* Thargoids Return to Pleiades Nebula

/18 Jul 3305/

The Thargoids have returned to the Pleiades Nebula in large numbers, with several conflicts reported within hours. 

Professor [[id:c2623368-19b0-4995-9e35-b8f54f741a53][Alba Tesreau]] gave an update on behalf of Aegis Research: 

“The Thargoid forces that recently withdrew from the core systems have resurfaced in the Pleiades Nebula following a brief disappearance. An initial analysis of their movements suggests a subtle change to their tactics. I believe they are seeking to reassert themselves in their original nexus.”    

“A considerable number of Thargoid craft have gathered in the Maia system. With the Palin Research Centre facing an imminent attack, the decision was made to evacuate Professor Palin and his staff, thereby protecting a number of vital research projects. All work at Palin Research Centre has been suspended.” 

“Regrettably, however, a transmission from Palin’s megaship, Carson's Spring, indicates that it was assaulted by Thargoid vessels shortly after departure. With system security forces already under pressure, we urge independent pilots to head to Maia and protect Carson’s Spring.”
