:PROPERTIES:
:ID:       b49ec7ff-26da-45e6-8b63-a6784f1beec8
:END:
#+title: The Presidential Power Struggle
#+filetags: :3304:galnet:

* The Presidential Power Struggle

/21 Sep 3304/

With the Alliance presidential race gathering speed, political journalist Vanya Driscoll has published an analysis in The Alliance Tribune: 

“The election of a new president is usually a ceremonial matter, during which voters select a public ‘face’ for the Alliance, but this year is a genuine power struggle – one that may have major consequences.” 

“Elijah Beck is the only candidate who seems content with the status quo. By contrast, entrepreneur Fazia Silva promises to boost the economy and increase commerce. Her new financial policies have been welcomed by interstellar corporations and small businesses alike.” 

“President Gibson Kincaid is causing the most controversy, however. His proposal that the role of president should include executive powers is being taken seriously by the Assembly. Kincaid claims that having a single controlling voice will enable the Alliance to ‘challenge our rivals’ dominance’.” 

“There is a surprising amount of support for this combative rhetoric. Many agree that the Alliance could be stronger, and that Prime Minister Mahon is often hamstrung by bureaucracy. Rumours suggest that the Empire and Federation are watching this election far more closely than usual.”
