:PROPERTIES:
:ID:       730a90bd-a34b-4382-988c-f4946538af2b
:END:
#+title: Galactic News: Acrimony on Achenar
#+filetags: :3302:galnet:

* Galactic News: Acrimony on Achenar

/01 Oct 3302/

An anonymous source has indicated that the scandal surrounding former senator Kahina Tijani Loren has awoken latent animosity within the Imperial powerbase. 

The source claims that recent events have brought the affairs of Admiral Denton Patreus, Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and even Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] into the spotlight, and that much intrigue and politicking is taking place behind closed doors. 

Princess Duval, following an embarrassing story from The Imperial Citizen, said: "Isn't it interesting that this happens just as a crisis is developing on our borders? While the media is preoccupied with that psychopathic Loren woman, the real stories are being ignored!" 

Neither Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] nor Admiral [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] deigned to comment on the matter.
