:PROPERTIES:
:ID:       05707d56-717f-4ec5-9667-a74a94e50f66
:END:
#+title: Alliance-Sirius Pact Enters Approval Stage
#+filetags: :galnet:

* Alliance-Sirius Pact Enters Approval Stage

/08 Jun 3308/

The probationary period for the proposed anti-xeno partnership between [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] and Sirius Corporation has now ended. 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] made this public statement: 

“Documentation for the strategic defence pact has been submitted to the Assembly for debate and amendment. Council members will vote by the end of June to decide whether or not it should be ratified.” 

“In the last three months, Sirius Corporation has successfully increased security for Allied interests in the Coalsack and Witch Head Nebulas. It also did a splendid job arranging for crucial supplies to be delivered to the Didio system during the Thargoid invasion.” 

“The Council of Admirals does not wish to rely exclusively on Salvation to protect Allied systems, and I concur with their assessment. Combining our defence force with Sirius’s resources will be a huge step toward forming an Alliance Navy, thereby increasing our anti-Thargoid fleet capabilities on a par with [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] and Federation.” 

Councillor Nakato Kaine, Mahon’s political rival, also made a statement: 

“In my view, Sirius Corporation remains an untrustworthy partner and has exerted a disruptive influence on the Alliance. I continue to oppose the strategic defence pact, and urge my fellow council members to prevent it being adopted as policy.”
