:PROPERTIES:
:ID:       e9f7f287-0841-4ab8-97c1-450965836718
:END:
#+title: Independence Spreads from Azaladshu System
#+filetags: :galnet:

* Independence Spreads from Azaladshu System

/08 Jul 3307/

*Pilots Federation ALERT* 

The Azaladshu Free faction has defeated the forces of Neche Inc and retained independence from the Federation. 

As a result, the Azaladshu, LFT 824, LHS 277 and LTT 3919 systems have confirmed their independent status. The victory also inspired the Coalition of Uteran, Lp 726-6 Free and Gluscap Labour factions to secede from the Federation, affecting all systems under their control. 

Mayor Constanza Noguera, leader of Azaladshu Free, declared: 

“A Federation that abuses the rights of its people has no authority. With the help of our loyal supporters, we’ve made a stand for dignity and civil rights.” 

The situation has caused turmoil in Congress, with President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] being criticised for his inability to contain this rebellion.  

Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] responded to accusations that she orchestrated the seceding factions: 

“I support their rejection of our harsh surveillance laws, but not their methods of protest. I have no wish to see the Federation lose member systems for any reason.” 

Pilots who supported the Azaladshu Free faction can collect their rewards at Eratosthenes Ring station.
