:PROPERTIES:
:ID:       5b172c76-ae01-4131-b029-6ba8456d8051
:END:
#+title: Galactic News: Jaques Station Found!
#+filetags: :3302:galnet:

* Galactic News: [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station Found!

/29 Jun 3302/

Two weeks ago it was reported that [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station, the legendary travelling starport, had survived its attempt to jump from Gliese 1269 to Beagle Point. 

Unfortunately, however, the starport's location could not be verified due to problems with its communication systems. Fragmentary messages, picked up by a number of outposts, gave hints as to what had befallen the station, but the incomplete nature of the messages left recipients with no clear idea of where it might be. 

But a recent report indicates that, despite all odds, the starport has been found. An independent pilot by the name of Commander Cly happened upon the station while exploring the Eol Prou AA-A H89 Nebula. The pilot has confirmed that [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] is in the Eol Prou RS-T d3-94 system. Commander Cly also reported that the starport is still suffering from technical issues, presumably due to Unknown-Artefact related interference. 

It is hoped that [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] will make a statement soon.
