:PROPERTIES:
:ID:       220d5044-ad7e-4826-b36d-595e1874c2e0
:END:
#+title: Week in Review 02 Sep 3304
#+filetags: :Thargoid:3304:galnet:

* Week in Review

/02 Sep 3304/

Here are this week’s major stories. 

Independent pilots have engaged a previously unseen type of Thargoid vessel in both the Pleiades Nebula and the core systems. Admiral Aden Tanner, Aegis’s chief military liaison, confirmed that the new ship – classified as the Hydra – is a variant of the Thargoid Interceptor. 

Federal President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] has announced that Aegis Core is to relocate from Socho to the Federal home system of Sol. The move is a response to the criminal occupation of the Socho system, which led to the temporary immobilisation of Aegis’s Eagle Eye network, a system of orbital installations designed to determine potential Thargoid attack sites. 

Engineer [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] has detected unusual energy signatures in the NGC 2451A sector, the IC 2391 sector and the Synuefe EN-H region. While the precise nature of the signals is unclear, Ram Tah has encouraged independent pilots to investigate. 

In other news, the Colonia Council has announced that four engineers have established bases in the Colonia region, to provide services to independent pilots. According to a statement, the Council consulted with engineers in the core systems to identify individuals who could offer similar services in Colonia.  

The date of Princess Aisling Duval’s wedding to Federal Ambassador Jordan Rochester has passed without comment from either party. While Emperor Arissa and President Hudson are thought to be pleased with the cancellation of the wedding, the silence from [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and Jordan Rochester leaves questions about the legitimacy of their relationship unanswered. 

Maddox Hurd, owner of Herculean Machines, has publicly dismissed the efforts of rival company Supratech. Mr Hurd denounced the idea of wearable devices as ridiculous, prompting Supratech CEO Scorpio DeVorrow to describe him as a man of “limited imagination”. 

Meanwhile, Alliance President Gibson Kincaid has begun lobbying to invest the position of president with executive powers. He has also said that the incumbent should remain in office for six years, instead of a maximum of two one-year terms. Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has voiced his opposition to the proposal. 

Juanita Bishop, a leading campaigner against the Far God cult, has announced that she is running for Federal Congress. Mrs Bishop’s vocal condemnation of Thargoid worship has gained her a strong following in many Federal systems. She is now campaigning to be elected to Congress as an independent candidate. 

In related news, the Far God sect has issued a public request for Thargoid materials. It is understood that the objects will be revered as objects of worship, and will not be used in any xenobiological experiments. 

Finally, authorities in the Betel system have confirmed that the conflict between Betel Free and the Silver Creative Network has come to an end. Both factions received support from independent combat pilots, to whom generous rewards were promised, but ultimately there could be only one victor. It is hoped that the cessation of hostilities will preface a period of peace. 

And those are the main stories this week.
