:PROPERTIES:
:ID:       d7cf7759-a06e-49e9-b2ad-45cd8f5c3440
:END:
#+title: Federation Delivers Golconda’s New Home
#+filetags: :Empire:galnet:

* Federation Delivers [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s New Home

/24 Nov 3305/

The Federation has won the bid to provide the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s population with a permanent home, beating a rival effort by the Empire. 

Both campaigns received support from the galactic community, but the initiative to create a new orbital outpost for the generation ship’s inhabitants ultimately proved more popular than the construction of a planetary port. 

An official message from the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] confirmed that the colonists were impressed by the superpower’s success, and have agreed to migrate to the outpost once it has been completed. The outpost will be named Forester’s Choice to honour the captain of the Golconda, Jonathon Forester.  

The [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] crew have also accepted the status of a Federal partner while retaining their autonomy. 

Congressman Harlan Turk made this statement: 

“We are proud to offer a fresh start to a society descended from the Federation’s forebears. Their unique culture will continue to thrive among the stars at an outpost that enjoys Federal protection.” 

Imperial Senator Ava Cornelius sent a message of goodwill to Captain Forester and his crew. She admitted disappointment at the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s decision but wished the colonists peace and prosperity for the future. 

Supporters of the Imperial and Federal campaigns can now collect outstanding rewards from their respective megaships in the Upaniklis system.
