:PROPERTIES:
:ID:       6b0a7d9a-8616-4d31-a4e5-d4b969cc2606
:END:
#+title: Imperial Senator Visits Marlinist Colonies
#+filetags: :galnet:

* Imperial Senator Visits Marlinist Colonies

/09 Apr 3307/

Senator Lorcan Scordato has visited the Marlinist Colonies on a fact-finding mission as part of the Empire’s anti-terrorism operations. 

The Imperial Herald was permitted to publish this summary of his preliminary report: 

“Considering their recent refugee status, the Marlinist communities are remarkably well-organised. Their government works along republican lines but they have not abandoned Imperial culture, with many feeling homesick for their original worlds.” 

“However, their situation remains precarious, with three of their eight systems now under the control of external factions. Without increased support from the galactic community, further losses may be unavoidable.” 

“Regarding the NMLA, there is widespread anger that they have made all Marlinists look like monsters. Only rarely did I sense guarded approval, with the vast majority openly condemning the terrorists.” 

“The Marlinist Parliament is small but efficient, containing a spectrum of viewpoints. First Minister Fairfax is focused on cohesion and survival, Amrita Ross discussed future reintegration with the Empire, while Aaron Whyte sees Neo-Marlinism as a valid political movement if violence can be avoided.” 

“Months ago these were ordinary Imperial citizens, and our shared history still binds us. Generally, I feel that the Marlinist Colonies are closer to allies than enemies in our war against the NMLA.”
