:PROPERTIES:
:ID:       8d609bc7-3d93-4140-95a2-01080082b2da
:END:
#+title: Prototype Frame Shift Drive almost production ready, competitor sceptical
#+filetags: :galnet:

* Prototype Frame Shift Drive almost production ready, competitor sceptical

/04 Apr 3310/

Material gathered from the Titan Taranis wreckage has reportedly allowed [[id:6ebf2d4f-85a9-4251-82c9-406c9c06b5a1][Achilles Aerospace]] to complete the research on their prototype Frame Shift Drive. 

The recent initiative sponsored by Achilles Aerospace saw over 5000 independent pilots enter the hazardous wreckage of Titan Taranis, retrieving enough Titan Drive Components to allow Achilles to allegedly design a new type of Frame Shift Drive based on Titan technology. 

A spokesperson for Achilles Aerospace gave the following update: 

The Achilles Corporation would like to commend every brave pilot that responded to our request. The data we are gathering from the collected materials is staggering, and our work has progressed at an astonishing rate. Our teams are hard at work getting the prototype ready for production as I speak, and we are eager to show you all the fruits of our labour very soon. 

Sirius Corporation, the current sole manufacturer of Frame Shift Drives, was asked for comment on this research: 

“Sirius recognises Achilles’ claims of ‘revolutionising’ an extremely advanced technology in a relatively short span of time, but we remain unconvinced of their substance. If Achilles can produce something other than words we will be happy to comment further.”
