:PROPERTIES:
:ID:       14ad3f69-536f-47fb-9d82-79098dd75ed4
:END:
#+title: Rare Goods Required for Galactic Summit
#+filetags: :Empire:Alliance:galnet:

* Rare Goods Required for Galactic Summit

/18 Feb 3307/

*Pilots Federation ALERT* 

Sirius Corporation has requested deliveries of consumables to Luyten’s Star for the forthcoming diplomatic conference. 

The Galactic Summit will take place in the Sirius system and last for three weeks, beginning on Thursday the 25th of February. It will be attended by leaders from the Alliance, Empire and Federation, plus representatives from independent systems. 

Sirius Corporation has placed orders for these rare commodities: Eden Apples Of Aerial, Ethgreze Tea Buds, Gerasian Gueuze Beer, Giant Irukama Snails, Goman Yaupon Coffee, Karsuki Locusts and Lavian Brandy.  

All shipments are to be delivered to Ashby City in the Luyten’s Star system. They will then be ferried to Sirius before the conference begins. 

CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] discussed these preparations at a media event: 

“We will provide all honoured delegates with a comfortable, luxurious environment. This includes offering the finest cuisine from across the galaxy.” 

Several journalists pointed out that both the Alliance and Empire had registered official complaints about the Galactic Summit’s location being situated deep within Federal space. [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] responded: 

“I assure you that the Sirius system is politically neutral territory, and Sirius Corporation remains independent from the Federation. I can personally guarantee the safety and diplomatic immunity of all attendees.”
