:PROPERTIES:
:ID:       7120edbd-5c85-4eec-a076-22c81b5a160e
:END:
#+title: Mining Campaign in LHS 3872 Concludes
#+filetags: :galnet:

* Mining Campaign in LHS 3872 Concludes

/23 Nov 3309/

*Pilots’ Federation ALERT* 

Torval Mining Ltd has announced that sufficient quantities of mined resources were delivered to its subsidiary faction. 

The Aristocrats of Cuacocha, who control the LHS 3872 system, received the shipments of mined lithium hydroxide, painite, praseodymium and tritium. They have confirmed that all participating pilots can now collect their rewards at Curbeam Hub. 

Constantia Torval, the corporation’s recently appointed CEO, gave a statement: 

“With this successful event, Torval Mining Ltd advances toward even greater prestige and profitability. I offer sincere thanks to our partners and contributors.” 

The campaign’s background was discussed by Gwendolyn Nash, Empire correspondent for Vox Galactica: 

“Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] handing Torval Mining Ltd to her oldest daughter is the latest of several curious developments in recent years. She established the company by branching out from Mastopolos Mining, severing connections with more distant family members. She also transferred many investments to her other daughter Petra Torval, who is also a senator, and grandson Titus Torval, an [[id:45d78e5d-27b7-48cb-97b2-012934be3180][Imperial Intelligence]] captain.” 

“Coupled with the fact that she has missed several Senate meetings recently, speculation is rife that the 132-year-old has entered the twilight of her corporate and political careers. But as even her sternest opponents would attest, it is never wise to underestimate Zemina Torval’s willpower.”
