:PROPERTIES:
:ID:       3e7e3455-d13e-4cec-970c-fd0321dc8800
:END:
#+title: Thargoid Research Project Requires Meta-Alloys
#+filetags: :Thargoid:galnet:

* Thargoid Research Project Requires Meta-Alloys

/05 May 3308/

*Pilots’ Federation ALERT* 

Commanders have been asked to collect meta-alloys from Thargoid barnacles as part of a wider xenological study. 

The research project is being orchestrated by Professor Ishmael Palin, one of the most prominent experts in Thargoid technology: 

“With escalating Thargoid activity in the core systems, it is increasingly important that we learn as much as possible about this species. Only through scientific study can we better comprehend their biomechanical nature and, where possible, enhance our defences against it.” 

“The initial phase requires fresh samples of meta-alloys, the unique material used in the construction of Thargoid vessels. These can be harvested from barnacles that the Thargoids have seeded on selected planets.” 

Pilots can deliver meta-alloys to the starport James Sneddon in the Morten-Marte system. As part of the Federal Reclamation Co’s support for this initiative, the station’s market also offers an increased price for any Thargoid tissue samples. 

In addition to credit payments for all those delivering meta-alloys, class 4A, 5A and 6A corrosion resistant cargo racks will be available to selected contributors. The 5A and 6A versions have been exclusively manufactured for this project, and are not commercially available at present. 

Professor Palin stated that possessing these cargo racks will be of great benefit in the project’s planned second phase, scheduled to occur in the next few weeks.
