:PROPERTIES:
:ID:       273d7834-fe3f-4b12-b045-d5d8a62e719a
:END:
#+title: Faulcon DeLacy
#+filetags: :Federation:Empire:Alliance:Corporation:

* Faulcon DeLacy

#+begin_quote

  "Bridging the stars for half a millennium."

  --- Source
#+end_quote

[[id:6da1c424-2b8f-4612-9c68-415c9ce6aed7][Faulcon Manspace]], originally a small military supply company,
experienced an overnight reversal of fortune when it released the [[id:369150fa-848e-401e-9ce6-373f1453e405][Viper]]
fighter, which proved popular with governments and private citizens
alike. Indeed, demand was so high that [[id:6da1c424-2b8f-4612-9c68-415c9ce6aed7][Faulcon Manspace]] had to farm out
[[id:369150fa-848e-401e-9ce6-373f1453e405][Viper]] production to other companies under licence.

With wealth came innovation and a range of new designs. Like the [[id:369150fa-848e-401e-9ce6-373f1453e405][Viper]],
these new ships were named after dangerous snakes: the Cobra marked the
company's entry into the trader market, while the lightweight, versatile
[[id:0127a175-4bb8-4bf7-924c-37273661a623][Sidewinder]] was designed principally as a reconnaissance craft.

As the company's wealth grew, it began to absorb many of the companies
to which it had previously granted manufacturing contracts. In almost
all cases, the target companies' close working relationship with Faulcon
Manspace made such acquisitions frictionless and mutually beneficial. In
2982, the corporation merged with one of the largest such manufacturers,
[[id:2d15cbf6-9087-4a09-8e24-a31b6b404ad8][deLacy ShipWorks]], becoming Faulcon deLacy.

The company pioneered the now-standard modular system of ship design
that allows pilots to swap out components with ease. Significantly, the
company made the schematics for the modular system freely available to
its manufacturing rivals, broadening the choice of compatible modules
available to pilots and thus making the Faulcon deLacy marques more
popular.

Without this philosophy of component compatibility, spacecraft
maintenance might have become a nightmarish scenario in which being
unable to get the proper parts could leave a broken-down ship stranded
in drydock for weeks, or worse subject to bodged repair attempts.

Today, Faulcon deLacy stands out as one of the most enduring, widespread
and consistently admired corporations in colonised space. Public regard
for the company is so high that the Alliance. Empire and Federation have
all made attempts to secure exclusivity to Faulcon deLacy starships.
Thus far, their efforts have been unsuccessful.
