:PROPERTIES:
:ID:       fb150bfb-f5b2-4b39-9f35-b18967ba2866
:END:
#+title: Supplies Needed for Imperial Festivities
#+filetags: :Empire:3304:galnet:

* Supplies Needed for Imperial Festivities

/20 Dec 3304/

Imperial senator [[id:667b1421-4f11-4d0b-a701-154251e79522][Simone Leatrix]] has announced plans for a week of revelry at her palatial residence on Capitol in the Achenar system. 

The senator told the media: 

“We Imperials value the finer things, even during times of political upset. So I intend to celebrate the end of the year with a sumptuous party at my mountaintop retreat, which will be specially renovated for the occasion.” 

To feed the hundreds of high-profile guests and decorate the senator’s residence, Senator Leatrix has asked the [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] Imperial Society to organise deliveries of food and newly refined jewels to Mackenzie Relay in the Cemiess system. 

The initiatives begin on the 20th of December 3304 and will run for one week. If either initiative meets its targets earlier than planned, that campaign will end immediately.
