:PROPERTIES:
:ID:       ff25ede9-d296-49c5-9cc0-d7bd3c5a5717
:END:
#+title: Emperor Celebrates Imperial Strength
#+filetags: :Thargoid:Empire:galnet:

* Emperor Celebrates Imperial Strength

/17 Oct 3308/

Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] has expressed satisfaction with the Empire’s military and scientific progress since the Battle of HIP 22460. 

She delivered the public address following a recent tour of a Gutamaya shipyard: 

“The Imperial Navy is entering a period of revitalisation, with advances being made in multiple areas. We have been freed from the burden of external mismanagement, which hindered our military potential and diluted our naval strength.”  

“The Senate has worked tirelessly to generate funding and opportunities for this renewed focus. New ships and crews have replaced recent losses, making our naval fleets more powerful than ever. And many loyal corporations have replaced inferior imports from foreign worlds with the high-quality workmanship of Imperial artisans.” 

“Alongside increased military and commercial might, the Imperial Science Academy leads the way on xenological research to uncover the secrets of our Thargoid foe. We have seen the disastrous nature of Proteus Wave technology, but using alternative methods to develop our own anti-xeno options remains a priority.” 

“Imperial systems are better protected against our enemies than they have been in a generation. Never has the future looked so assured. Our glorious history, stretching over a thousand years, teaches us a [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]] that we must now relearn: The Empire stands stronger alone.”
