:PROPERTIES:
:ID:       b66bf04b-b13f-4f3f-b7f0-089d76d165ca
:END:
#+title: Week in Review 22 Dec 3304
#+filetags: :3304:galnet:

* Week in Review

/22 Dec 3304/

Here are this week’s major stories. 

Disgraced politician Juanita Bishop has called for a forthcoming book about the Far God sect to be banned. In a statement, Bishop described the book’s authors as alien sympathisers, and accused them of creating pro-Thargoid propaganda. Gethin Okonkwo, one of the book’s writers, suggested that Bishop’s desire to halt publication was an attempt to prevent a criminal investigation into her own activities. 

A range of new asteroid-mining equipment is expected to trigger an increase in the availability of ores and minerals. A spokesperson for the Industrial Mining Guild said the new tools would prompt a surge in private mining activity. 

In other news, Princess Aisling Duval has publicly rejected the isolationist group Nova Imperium and its figurehead, Hadrian Duval. Senator Zemina Torval publicly voiced agreement with Princess Duval, but Senator Pal Vespasian said that many senators were willing to recognise Hadrian Duval as Emperor-in-waiting. 

In other news, Clinical trials for nanomedicines developed by Vitadyne Labs have delivered outstanding results. Observers from the Interstellar Health Organisation said that the nanomedicines eliminated malignant cells, boosted immune systems and repaired damaged tissue, and said that the product represented a genuine breakthrough. 

Imperial senator Simone Leatrix has announced plans for a week of revelry at her palatial residence on Capitol in the Achenar system. In a statement, the senator said she intended to celebrate the end of the year with a sumptuous party at her mountaintop retreat, which would be specially renovated for the occasion. In support of the event, the Cemiess Imperial Society has placed an open order for various commodities. 

Finally, the conflict between two opposing factions in the Wally Bei system has ended. The fleets of both Wally Bei Technical and the Wally Bei Constitution Party were significantly reduced in a prolonged series of battles. The leaders of both organisations issued a joint statement, confirming that for humanitarian reasons they would bring hostilities to an end. 

And those are the main stories this week.
