:PROPERTIES:
:ID:       61832a23-0a2e-4c74-b206-94b23e179756
:END:
#+title: Community Goal: Terraforming Vennik 1
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: Terraforming Vennik 1

/17 Mar 3302/

For decades, the Revolutionary Party of Vennik has been terraforming the planet Vennik 1, slowly transforming it into a habitable world. With the ambitious project about to enter its final stage, the organisation has placed an open order for terrain-enrichment systems with which to prepare the planet's surface for agricultural development. 

A spokesperson for the Revolutionary Party of Vennik released a brief statement: 

"Terraforming a planet takes decades, so we're delighted to be entering the final stage. Our aim is to establish an agricultural economy on Vennik 1 so it can contribute to the production of food and medicine in the Vennik system. With the support of the galactic community, we will soon be able to reap the benefit of our efforts." 

The organisation has promised to reward those who deliver the much-needed commodities to Nixon Enterprise in the Vennik system. The campaign begins on the 17th of March 3302 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
