:PROPERTIES:
:ID:       4a893e6b-189e-4af7-80d0-0c6b12e0ff84
:END:
#+title: Military Strike Against Marlinist Faction
#+filetags: :galnet:

* Military Strike Against Marlinist Faction

/08 Oct 3306/

*Pilots Federation ALERT* 

Conflict between Regulatory State of Ackwada and Duduseklis Empire League in the Ackwada system. 

The Empire has targeted a Marlinist faction that is suspected of supporting the Neo-Marlinist Liberation Army (NMLA). It was recently placed into lockdown for its pro-Marlinist stance, during which time suspicions were raised of it having a direct connection to the NMLA.   

The Imperial Internal Security Service made this statement: 

“The Duduseklis Empire League is one of several organisations that publicly accepted the principles of Marlinism. Our intelligence suggests it is allowing the NMLA to radicalise its citizens into becoming activists for the paramilitary group.” 

“Operations to investigate this potential nest of terrorists have been met with armed resistance. Imperial auxiliaries and independent pilots are requested to assist the Regulatory State of Ackwada in defeating all pro-Marlinist forces in the Ackwada system.” 

The Duduseklis Empire League broadcast this message: 

“If NMLA members have been recruited from our people, it is certainly not with our knowledge. The Empire is using a terrorist hunt to justify persecuting millions of ordinary citizens, whose only crime is to believe in republican ideals.” 

“We remain loyal to the Emperor, but are forced to counter this unwarranted aggression to ensure these political refugees escape imprisonment. The stronger our resistance, the more megaships can flee this system. We desperately need help so we can transport thousands of innocent families to safety.”
