:PROPERTIES:
:ID:       64a75849-a979-4d77-ab3a-467970cc2b82
:END:
#+title: Sirius Gov Enters the Alioth System
#+filetags: :galnet:

* Sirius Gov Enters the Alioth System

/14 Jan 3308/

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has invited Sirius Corporation to establish a permanent presence within the Alliance. 

The Alliance Tribune’s political correspondent Vanya Driscoll reported: 

“Sirius Corporation’s new role as a strategic defence partner has expanded swiftly, with a Sirius faction established in the Alioth system to represent the megacorp. In addition, several megaships have arrived in other Allied systems to provide support.”  

“The Alliance Defence Force and some government departments now have official advisors from Sirius Corporation on their staff. Prime Minister Mahon announced that these developments will streamline joint operations with the Sirius Navy, and in turn provide effective countermeasures against [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] aggression.” 

“But Councillor Nakato Kaine claims that the presence of Sirius Gov is illegal as it was not ratified by the Assembly. She has pointed out that since the defence pact makes this a classified military matter, any civil action to reverse Mahon’s executive decision has been deliberately blocked.”
