:PROPERTIES:
:ID:       c9fb364c-03c4-4b2e-bbaa-4a524faff72c
:END:
#+title: 78 Ursae Majoris Increases Security Ahead of Presidential Visit
#+filetags: :Federation:Alliance:3301:galnet:

* 78 Ursae Majoris Increases Security Ahead of Presidential Visit

/15 May 3301/

Excitement is in the air in 78 Ursae Majoris, as millions of residents have begun preparing Seddon Gateway for the arrival of Federal President Jasmina Halsey. The exact date of the President’s arrival has yet to be announced, but residents haven’t let that stop them from arranging a week of festivities and cultural displays aboard the station. 

Another group preparing for the President’s visit is the Alioth Independents, who have today announced that they will be launching an initiative to increase security in the local cluster ahead of President Halsey’s visit. 

Andrew Bailey, the Mayor of Townsend Hub and local leader of the Alioth Independents had this to say about the new initiative: 

“We are very conscious that once President Halsey arrives, the whole galaxy will have its eyes on our little system. 78 Ursae Majoris has been nothing but peaceful and productive since electing to join the Alliance and the Alioth Independents will do everything in our power to ensure it remains that way throughout the President’s visit.” 

“Firstly, we will be running a cluster wide security campaign from Townsend Hub. As part of which, agents of the Alioth Independents will be offering a range of bonuses to bounty hunters who help clear out any unruly criminal elements in the sector.” 

“Secondly, members of the Alioth Independents and our allies will be launching a military campaign to finally rid the cluster of the criminal cartel known as the Sobek Boys. Military capable Commanders interested in assisting with the campaign can likewise signup for active duty aboard Townsend Hub.”
