:PROPERTIES:
:ID:       3b87394b-a873-4683-a599-78b225719d5c
:END:
#+title: Community Goal: Appeal for Construction Materials
#+filetags: :CommunityGoal:3303:galnet:

* Community Goal: Appeal for Construction Materials

/09 Mar 3303/

The Military Militia, an independent organisation based in the XI-2 Lupi system, has announced plans to establish an installation in its home system, and has issued an appeal for various commodities for use in the construction. Commander MiL1TiA SiX, the group's wing commander, elaborated on the nature of the appeal: 

"We need two resources to start construction – military grade fabrics and platinum – and we encourage all able and willing Commanders to assist us." 

"Resistance is expected, but the Military Militia and its allies stand at the ready. We will be patrolling the shipping lanes in order to keep criminals at bay and ensure no crime goes unpunished." 

The proposed installation, which will be known as Soldiers' Respite, will boast state-of-the-art communication relays, high-tech weapon systems and a combat training facility. 

The organisation has promised to reward pilots who deliver the requested commodities to Pellegrino Hub in the XI-2 Lupi system. The campaign begins on the 9th March 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
