:PROPERTIES:
:ID:       2dde3a6b-b10a-4f92-b690-228a669d24fd
:END:
#+title: Congressional Candidate Endorses Xeno-Peace Movement
#+filetags: :3308:Federation:Thargoid:galnet:

* Congressional Candidate Endorses Xeno-Peace Movement

/14 Oct 3308/

Dalton Chase, the Federal governor of Andavandul 1, is campaigning to become a member of Congress with support from the Thargoid Advocacy Project. 

A profile of Governor Chase was published in [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]] by political journalist Sofia Trevino: 

“Despite only being in his mid-thirties with a short political career, Dalton Chase has made a habit of beating the odds. He achieved a very strong following within his home system of Andavandul, eclipsing more experienced rivals to become a planetary governor.” 

“This is largely due to his willingness to reach beyond the mainstream. Many politicians claim the kind of exuberance and natural charisma that Chase possesses, but few would risk talking about the Thargoids using pointed phrases such as ‘communication not extermination’. Younger voters are drawn to his boldness, as are the [[id:a12cdcbc-fa10-474e-8654-d3d7da17a307][ICE-casters]] who routinely invite him onto their platforms.” 

“Following the unfortunate incident that recently befell Congressman Theodore Pachis , a rare vacancy has opened within the Federation’s grandest political body. Governor Chase should be the least likely candidate, except for the fact that he has become something of a poster boy for the xeno-peace movement. A key pledge of Chase’s electoral campaign is to pursue ways of opening human-Thargoid diplomatic channels.” 

“The Thargoid Advocacy Project is promoting Chase as the best chance to get Congress to take their ideas seriously. This in turn has fuelled a media backlash from some quarters, with Sol Today claiming he relies on ‘the alien-lover vote’. We will soon learn if Dalton Chase’s popularity among that demographic is enough to see him elected to high office.”
