:PROPERTIES:
:ID:       80127edd-ce41-4149-9a09-4e8879fa247a
:END:
#+title: Conspiracy Theorist Finds Network Home
#+filetags: :Thargoid:galnet:

* Conspiracy Theorist Finds Network Home

/20 Aug 3307/

Independent journalist Flint ‘Firemaker’ Lafosse has announced that the [[id:d06803e0-267c-4ffc-88f2-967058fce82e][Rewired]] network will broadcast Kit Fowler’s conspiracy-laden show End Times. 

Lafosse, notorious for his own sensationalist claims, announced: 

“Finally, someone else who sees things as they really are! Kit Fowler’s perceptive views match his technical genius. By retransmitting his End Times broadcasts, I’ll be helping people resist the narrative conditioning being pumped into our minds by the faceless elite.” 

Kit Fowler provides specialised engineering services from his workshop in the Capoya system. He has used his show to make many outlandish claims over the years. These include labelling the shadowy figure ‘Salvation’ an AI construct, accusing Utopia of secretly creating a new species of human, and arguing that the universe’s true shape is being concealed by superpower-sponsored holograms. 

Lafosse advertised Fowler’s content with an excerpt from the most recent End Times episode: 

“Years ago, a sinister group called Black Flight committed multiple crimes, including murder, to suppress evidence of Thargoid activity after the First War. The mainstream newsfeeds buried the story, of course. But the fearless [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]]-seekers among us have repeatedly named the Colonia, Neche and Wasat systems as locations where the Black Flight operated.” 

“There’s a real buzz in that region right now… something’s going on that they don’t want you to know about. Never give up our search for the right facts, people!”
