:PROPERTIES:
:ID:       dba995f2-26cc-449f-9a76-11614b92cb11
:END:
#+title: Jameson Memorial Starport Operational
#+filetags: :Thargoid:galnet:
* Jameson Memorial Starport Operational

/02 Oct 3310/

The famous megamarket Jameson Memorial is once again fully operational. 

A recent Thargoid incursion into Shinrarta Dezhra caught AX forces by surprise, overwhelming the system and knocking most ports offline. Only Jameson Memorial resisted as large numbers of independent pilots flocked to the defensive campaign. 

Florian Baljak, now officially installed as the starport commander for Jameson Memorial, offered this statement: 

“I am overwhelmed by the response to the recovery initiative for offline ports. The flow of resources and commodities to this great system reflects the importance that Jameson Memorial holds in the eyes of our pilots.” 

The Pilots’ Federation has confirmed the loss of over 1,600 licensed Commanders and Rescue Rangers during the attack. The initial resistance to the Thargoid fleet was upheld by these pilots until reinforcements arrived. Shinrarta Dezhra is the home of the elite pilot organization, with its headquarters situated on Founders World. 

Several military sources have mentioned that the Thargoid attack fleet in Shinrarta Dezhra was far larger than a typical system invasion force. The Thargoids suffered considerable losses as the conflict wore on, with confirmed Thargoid Scout kills noted as "particularly high". 

All services previously found at Jameson Memorial are now available for pilots with access to the system. The Shinrarta Dezhra temporary access permit granted to pilots will expire on Thursday 3rd October.
