:PROPERTIES:
:ID:       8dcee52a-b15d-40c9-8e61-8b775d465276
:END:
#+title: Tesreau Announces Bid to Reform Aegis
#+filetags: :3308:Empire:Federation:Alliance:Thargoid:galnet:

* Tesreau Announces Bid to Reform Aegis

/28 Sep 3308/

A media forum is being arranged that will officially propose reinstating the tri-superpower anti-xeno agency. 

The event is being organised by Professor Alba Tesreau, former head of research for Aegis. She delivered a statement to all newsfeeds: 

“As the war against the Thargoids intensifies, the need for centralised xenological research is more vital than ever. This press conference will put forward a case to convince leaders in the Alliance, Empire and Federation to review their decision to dismantle Aegis.” 

“The Baumann Report highlighted many of Aegis’s limitations, and we do not intend to ignore these. Improvements to several departments would have to be made. But the [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][Affiliated Counter-Terrorism]] Unit proved that cross-superpower collaboration can be efficient, flexible and effective. Aegis could be restructured along similar lines to prevent repeating its past mistakes.” 

Invitations to the conference have been sent to key political figures. Allied Deputy Prime Minister Angela Corcoran has agreed to attend. Federal Ambassador [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] has offered her support, but no members of Congress have responded publicly. The Imperial Senate acknowledged Professor Tesreau, but formally stated that the Empire has no interest in further cooperation with the other superpowers at this time. 

The three-day forum is scheduled to begin on Monday 3rd October in New Apollo City on the planet Biggs Colony.
