:PROPERTIES:
:ID:       517dbb4e-7816-47cc-be32-580806b286a7
:END:
#+title: Alliance Campaign Comes to an End
#+filetags: :3304:galnet:

* Alliance Campaign Comes to an End

/09 Feb 3304/

The Alliance has announced that its appeal for materials has reached a successful conclusion, having received the unalloyed support of the galactic community. Huge quantities of raw materials were delivered to Bulychev Hub over the past week, which will be used to build an Orbis starport in the Synuefai EB-R c7-5 system. 

As the campaign drew to a close, Alliance official Torvan Dast issued a statement, thanking those who supported the campaign and adding: 

“By providing Alliance convoys and independent pilots with a much-needed resupply point, we hope this new starport will be the first step in transforming what is currently an outlying enclave into a thriving community.” 

Construction of the new starport is expected to begin soon. Pilots who contributed to the initiative can now collect their rewards from Bulychev Hub in the LP 128-32 system.
