:PROPERTIES:
:ID:       ce9f6855-12ee-413a-a664-0fde3b53071f
:END:
#+title: A Distant Rendezvous – 43,000 Light Years from Home
#+filetags: :3300:3301:galnet:

* A Distant Rendezvous – 43,000 Light Years from Home

/01 Mar 3301/

On the fringe of the Scutum-Centaurus arm, on the far side of the galaxy, two lone deep space explorers rendezvoused at a star system called EACTAINDS GN-W C1-6. 

CMDR R4nger0's mission? To cross the galaxy in a Sidewinder. 

CMDR Kamzel's mission? Returning to Earth after an 8-week survey expedition along the galactic outer rim. 

CMDR Kamzel left the frontier on 16th December 3300, CMDR R4nger0 departed on 7th January 3301. The meeting was the first human contact both pilots had in the many weeks they'd been away from home. Both pilots jointly surveyed the rendezvous system, shared a bottle of Lavian Brandy, and parted ways to continue on their respective journeys. The event was recorded and a vlog data-packet was beamed back toward human space. Streams of the log can be viewed by searching for ‘A Distant Rendezvous’ via your local vlog service provider. 

Some observers have called for the EACTAINDS GN-W C1-6 star system to be renamed ‘Rendezvous Point’, to commemorate this historic event... the most distant deep space encounter ever recorded.
