:PROPERTIES:
:ID:       63d98784-8327-442d-8245-f360c3994e31
:END:
#+title: Rescue Megaships Scheduled to Redeploy
#+filetags: :Empire:Federation:Thargoid:galnet:

* Rescue Megaships Scheduled to Redeploy

/07 Sep 3309/

*Pilots’ Federation ALERT* 

The eleven megaships coordinating evacuation efforts from Thargoid-invaded systems are set to move over the next few weeks. 

Military analysis of the current front line has highlighted that the distance between active conflict areas and the megaships can be decreased with an acceptably low degree of risk. Vice Admiral Skylar Anderson, part of the Imperial delegation to Aegis, offered this comment: 

“Shortening the distance between systems which require humanitarian support and the megaships responsible for coordinating that support is important. Until now we have urged caution to maintain their current safe positions, since these vessels are obvious targets for Thargoid attack. But as our brave pilots continue to regain territory and push the alien forces back, we feel confident that this is the right decision.” 

From September 7th, the following megaships will temporarily cease offering new mission contracts. They will redeploy to new locations on September 14th, with missions offered once again: 

Rescue Ship Foerster 

Rescue Ship Hutner 

Rescue Ship Seacole 

Rescue Ship Yoshida 

Allied [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]ace 

From September 14th, the following megaships will temporarily cease offering new mission contracts. They will redeploy to new locations on September 21st, with missions offered once again: 

Rescue Ship Bertschinger 

Rescue Ship Cavell 

Rescue Ship Cornwallis  

Rescue Ship Kisseih 

Imperial Sanctum 

Federal Haven 

Any ships or modules stored on the rescue megaships will be transported safely to the new location.
