:PROPERTIES:
:ID:       d40af2d9-66be-4c79-9483-a389ee25a70b
:END:
#+title: Subject D-2 Rejects Azimuth
#+filetags: :galnet:

* Subject D-2 Rejects Azimuth

/11 Oct 3308/

Seo Jin-ae, the Project Seraph survivor, has refused to have any further contact with Azimuth Biotech following its offer of help. 

She is currently in the care of Professor Alba Tesreau, who stated: 

“It will come as no surprise that Ms Seo vehemently rejects Mr Rademaker’s proposal. She has relayed horrific details to me about her abduction years ago, and the invasive experimentation at Oaken Point. The fear that Azimuth operatives were hunting her never passed, resulting in total isolation from her former life to protect friends and loved ones. As things stand, she has no reason to trust the organisation responsible for her suffering.” 

“Ms Seo’s health has improved, but I’m informed that a significant neural implant grafted into her cerebral cortex – designed to interface with a Thargoid vessel – can never be removed. With her permission, we are working to better understand the manner of the surgeries inflicted upon Ms Seo, along with her claimed interpretation of the ‘Thargoid roar’. I have contacted both Professor Ishmael Palin and [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] for assistance.” 

Azimuth Biotech CEO Torben Rademaker expressed disappointment at the response, and cast doubt on Seo Jin-ae’s legitimacy: “In her fragile emotional state, D-2 may be vulnerable to coercion by Professor Tesreau and other ex-Aegis radicals. Our medical teams have access to records detailing the procedures Oaken Point surgeons were carrying out. It would be unwise of Tesreau to choose self-interest over the chance to truly heal D-2.” 

In related news, several newsfeeds have reported an initial bump in public support for the reinstatement of Aegis. Following her attendance at the symposium, Deputy Prime Minister Angela Corcoran told the Old Worlds Gazette:  

“Operation Tyndareus has been initiated, with forces engaged in protecting the Andecavi system. Yet [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] should not rely exclusively on Sirius Corporation for anti-xeno defence. I believe that the return of Aegis is an option deserving serious consideration.”
