:PROPERTIES:
:ID:       a5bddcfb-005e-47fb-b87b-6c3a0419858d
:END:
#+title: Freelance Report: Border Coalition Backs SEPP
#+filetags: :galnet:

* Freelance Report: Border Coalition Backs SEPP

/07 Jul 3302/

In an emergency meeting at Iren's Dock on the 3rd of July 3302, the Border Coalition presented the Manite-Piscium-Pact to an assembly of interested parties. The outcome was a unanimous decision to back the Social Eleu Progressive Party in the Rise to Power campaign. The vote was swayed by a personal intervention from Duke Tiberius of Mikunn, who said: 

"We believe in exploration, colonization and scientific discovery. These ideas are bigger than Mikunn or Manite, bigger than the Border Coalition, bigger even than the outer colonies. For this reason the Border Coalition will be backing the SEPP in its bid for power." 

The Border Coalition evidently hopes that the faction that triumphs in the Rise to Power share its belief in the value of peaceful exploration, colonization and scientific discovery – a view shared by a significant number of other influential factions. 

A diplomatic summit is scheduled for Wednesday the 13th of July 3302 to discuss which options would be considered in the event of a GalCop victory, including a full backing of the EG Pilots. 

Valentina Tereshkova
