:PROPERTIES:
:ID:       fba1b95a-2889-4de0-a2a8-d78b2193d4ed
:END:
#+title: Nova Imperium Demands New Emperor
#+filetags: :Thargoid:3304:galnet:

* Nova Imperium Demands New Emperor

/24 Nov 3304/

Isolationist group Nova Imperium has declared its intention to install a new Emperor. 

The group’s leader, recently identified as ex-navy admiral Duke Kaeso Mordanticus and known as the Imperator, said: 

“The Empire has been weakened by collaborating with its enemies. Aegis drains our resources to protect foreign systems from the Thargoids, our security forces are stretched thin defending non-Imperial systems, and Princess Duval sullies her honourable name by dallying with a Federal libertine.” 

“Our people demand stronger leadership. We will achieve this by installing a new Emperor – one who will restore the glory of the Empire!” 

Political journalist Cassia Carvalho commented in The Imperial Herald: 

“Naturally there has been no response from Arissa Lavigny-Duval. But for many citizens, Mordanticus has articulated their unease about inter-superpower cooperation. With support for Nova Imperium increasing rapidly, a silent minority may now have found a voice.”
