:PROPERTIES:
:ID:       c92dcd1d-a66a-4e7e-b523-3101fea56100
:END:
#+title: Week in Review 09 Sep 3304
#+filetags: :Thargoid:3304:galnet:

* Week in Review

/09 Sep 3304/

Here are this week’s major stories. 

The Alliance Assembly has agreed to vote on President Gibson Kincaid’s proposed changes to the constitution. Kincaid has lobbied for the role of president to be invested with executive powers, and for each presidential term to last six years. The vote will take place in mid-October, at the same time as the presidential election. 

A manufacturing complex owned by computer company Supratech has been destroyed by fire. All personnel managed to escape the blaze, but the fire has ruined the company’s main production complex. Company CEO Scorpio DeVorrow expressed incredulity at the failure of the facility’s fire-suppression system. 

Meanwhile, the Federal Intelligence Agency has increased arrests of potential Thargoid sympathisers, as it continues to investigate the Far God cult. Independent observers have confirmed that the FIA has discovered further empty Far God hive-chapels. The whereabouts of hundreds of adherents remains unknown. 

The Gnosis, flagship of the Canonn Interstellar Research Group, has been left stranded following a Thargoid attack. A message from the ship’s command crew confirmed that the incident caused severe internal damage to multiple systems, including the frame shift drive. The Gnosis is currently adrift close to the eighth planet of the Outotz ST-I d9-6 system. 

In other news, The Mars Tribune has revealed that actor Tomas Turai, husband of Jupiter Rochester, has been having an extramarital affair with Olympian athlete Reagan Lord. Tomas Turai and August Lord, husband of Reagan Lord, have both announced their intention to sue The Tribune for defamation. The publication’s owner, billionaire Kingsley Cordova, has confirmed that he will cover all legal costs in contesting both civil actions. 

Finally, a public appeal for Thargoid materials from the Far God sect has been enthusiastically received by the galactic community. Chancellor Reegan Tanner, speaking on behalf of the organising faction, said the success of the initiative was a victory for religious freedom. 

And those are the main stories this week.
