:PROPERTIES:
:ID:       5773692f-932c-4f3c-a91b-99f12eba695a
:END:
#+title: The Coming of Taranis
#+filetags: :3308:Thargoid:galnet:

* The Coming of Taranis

/21 Nov 3308/

As the rogue signal sources draw closer to human-occupied space, work is underway to initiate peaceful inter-species negotiations.

Dr Elias Pope  is a graduate of [[id:b0f0e40a-14e9-422d-aa9d-5ff6296f3421][Orion University]] with degrees in interstellar relations, political science and xenology. He has recently joined the Kingfisher [[id:751c84bc-ea85-495d-923c-7776da57803a][megaship]]’s crew to oversee the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] Advocacy Project’s diplomatic mission. In an interview with [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]], Dr Pope explained his role:

“Like most of the Kingfisher’s crew, I volunteered to take part in this operation. It feels like my whole professional life has been leading to this opportunity. Many of the fine people here feel the same way I do. If there’s even a chance that we might begin properly talking to the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]], well… it’ll be historic.”

“Luria , my assistant, tells me there are some media-friendly names for these anomalies now. As a scientific purist, she’s very unhappy about that! This first one has been labelled Taranis. It will transit through the [[id:73e6ac6c-6320-4370-a533-ac7d58baf91c][Hyades Sector YO-Q b5-1]] system at tremendous speed, so we won’t have long to snag its attention. But that’s what we’re aiming to do.”

“The megaship has an impressive suite of audio-visual, electromagnetic and [[id:f9515545-c736-42cc-88ec-f3f269afd1b8][hyperspace]] transmitters that will broadcast to Taranis as it approaches. We’ll be trying everything from flashing light patterns to multi-frequency data bursts. Establishing common ground is key to any negotiation, so I’ve composed messages that impart universally recognisable concepts such as mathematical formulae and star charts. These should illustrate our intellectual prowess and capacity for reasoning.”

“The best-case scenario is that whatever controls Taranis hears us and responds in kind. We must at least attempt to make peaceful overtures. Even if we fail, it would signify to humanity that there are many people willing to make the attempt, no matter how dangerous. Wish us luck.”
