:PROPERTIES:
:ID:       30b616cb-612b-4fcd-ac9c-bd5d96d58854
:END:
#+title: Vitadyne Nanomedicines Prompt Ethical Dilemma
#+filetags: :galnet:

* Vitadyne Nanomedicines Prompt Ethical Dilemma

/12 Jan 3305/

The Interstellar Health Organisation (IHO) is currently reviewing Vitadyne Labs’s nanomedicines, which the company has admitted are based on advanced technology developed by Utopia. 

Healthcare analyst Dr Himari Grey discussed the situation via Vox Galactica: 

“There are always ethical considerations when approving new medicines. But in this case the IHO has more to consider than usual, not least [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]]’s formal complaint that replicating Utopian technology without permission is tantamount to theft.” 

“Many in the medical community argue that it is selfish of Utopia to hoard such revolutionary medicines. As these nanomeds are capable of treating many illnesses and injuries, surely the potential health benefits outweigh questions of ownership.” 

“On the other hand, investors have already pumped millions of credits into Vitadyne Labs, convinced that profits will run into the billions if these nanomeds become the galaxy’s hottest new commodity. If that happens, only the very wealthy will be able to afford Vitadyne’s product.”
