:PROPERTIES:
:ID:       fb2a44cb-8933-40f9-8be9-588c9237302c
:END:
#+title: Salvation Strengthens Bonds with Superpowers
#+filetags: :3308:Empire:Federation:Alliance:Thargoid:galnet:

* [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] Strengthens Bonds with Superpowers

/18 Apr 3308/

The anonymous anti-xeno scientist [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] has received further military support from the Alliance, Empire and Federation. 

Multiple official sources have highlighted the increasing number of crew members being seconded from the Alliance Defence Force, Federal Navy and Imperial Navy. Previously, enlisted members had been forced to resign their commissions, but regulatory changes now permit temporarily serving on vessels owned by [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s commercial partner Taurus Mining Ventures. 

One of the recent volunteers, Lieutenant Andrew Jones, was quoted by Vox Galactica: 

“Most of us are here because it feels like [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] is the only one taking the fight to the Thargoids. Now that Aegis is as good as gone, he’s our best hope for stopping these aliens before they wipe us all out.” 

Other non-naval recruits from the superpowers are providing support in intelligence, logistics and security. A number of specialists are alleged to be working directly with [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] on his anti-xeno superweapons, which are derived from Guardian technology. 

In related news, scientific research journal The Empirical reported that no evidence of atypical radiation has been detected in the Synuefe CE-R C21-6 system. This has raised questions as to the purpose of Taurus Mining Ventures’s recent mining operation.
