:PROPERTIES:
:ID:       61ab7a07-4385-4bd9-9050-5ecb76d36a2d
:END:
#+title: Distant Thargoid Encounter Raises Questions
#+filetags: :galnet:

* Distant Thargoid Encounter Raises Questions

/14 Aug 3309/

An independent explorer has reported an unusual incident involving a Thargoid vessel, hundreds of light years away from the ongoing invasion. 

Commander Renia Rakowski  told her story to Vox Galactica: 

“I’d been gathering exploration data for weeks without seeing another soul. Boring, I know, but I like a quiet life. As I jumped out of the Wregoe GA-X B3-0 system, my ship rocked violently and I panicked, thinking the hyperdrive had failed. I barely saw it at first, black against the black of space, until its outline glowed. A Thargoid interceptor. Just like on the newsfeeds, but right outside my canopy.” 

“I’ve never been in combat before, and my ship carries no weapons anyway, so I thought this was the end of me. My heart was drumming as I stared at the alien, and it stared back like some giant lidless eye. A writhing light lashed out, this rasping howl came over the comms, and then… it left. I wasn’t dead, which was quite the surprise.” 

“I watched it gliding away, its petals rotating and revolving, sort of beautifully I suppose. It actually turned its back on me, like I was some insignificant speck unworthy of attention. I’ve never been so glad to be boring.” 

Commodore Emil Varga, the Alliance’s military liaison to Aegis, provided a follow-up statement: 

“This incident took place a considerable distance from the Maelstroms. Initially, we feared this was evidence that new Titans had arrived and were performing a flanking manoeuvre. However, if the interceptor had been part of the invasion fleets, it would have opened fire immediately after hyperdiction occurred.” 

“The immediate area around Wregoe GA-X B3-0 contains no barnacle sites or records of Thargoid activity that we’re aware of. Universal Cartographics confirmed we have some basic exploration data for that part of the Wregoe sector, but no previous Thargoid encounters. Civilians are warned to stay away from that region until we know more.”
