:PROPERTIES:
:ID:       ea647b14-f52f-4eec-b08d-7fa365cf28b2
:END:
#+title: Vodel Releases Scorpion SRV
#+filetags: :3307:galnet:

* Vodel Releases Scorpion SRV

/09 Dec 3307/

SRV manufacturer Vodel today announced the official release of its new vehicle, the Scorpion. 

The first new mass-production model offered by the company in many years, the Scorpion is designed for combat operations and troop support. It is widely understood that Vodel’s acquisition by [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] in 3305 triggered the development of the new model, with the parent company’s considerable financial resources made available to Vodel’s engineering teams. 

Vodel’s chief of design, Frank Endis, gave a speech at the company’s launch event at Levinson Orbital in Bhattra: 

“We are delighted to bring the Scorpion SRV to the market and are excited at its potential. Our marketing team anticipates huge interest from independent operatives and military forces alike, thanks to the Scorpion’s impressive specifications.” 

“A focus on survivability provides the Scorpion’s two-crew cabin with additional protection from harm. The plasma surge repeater and the proprietary Aculeus missile launcher work in perfect harmony when engaging shielded, armoured targets. Meanwhile, the Scorpion’s raw power offers exceptional torque, capable of handling harsh terrain and steep climbs.” 

Core Dynamics CEO [[id:167df18a-99f8-4279-bc55-a736f6af44c2][Owen McKenna]] also attended the event and was approached for comment: 

“I’m really happy with how hard the Vodel team has worked on this new vehicle. They had clear goals in mind from the start, took [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]]’ feedback on board and kept us updated regularly through the process. I think the acquisition of Vodel was one of the last good decisions [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] made as head of the company.” 

The Scorpion SRV is now available to purchase from military economy ports.
