:PROPERTIES:
:ID:       7d4b700b-5e84-44cd-a177-84470a07fd6c
:END:
#+title: Arissa Convenes Key Imperial Figures
#+filetags: :Empire:Alliance:galnet:

* Arissa Convenes Key Imperial Figures

/21 Mar 3308/

Various Imperial allies, ambassadors and nobles have been summoned to Capitol for a series of meetings with Emperor Arissa Lavigny-Duval. 

Political journalist Cassia Carvalho provided details for The Imperial Herald: 

“There are rumours of many behind-the-scenes changes among the upper echelons of power since Emperor Arissa returned. But this latest event was mostly in the public eye and seemed designed to reassure the citizens of her physical presence.” 

“Members from all echelons of the Imperial aristocracy arrived at the palace with their entourages. Court ceremonies were held to reaffirm their fealty to Emperor Arissa, all with as much spectacle and grandeur as possible.” 

“Less public were Arissa’s closed sessions with representatives from the Imperial Diplomatic Corps. Laurentin Sharpe, the Empire’s senior ambassador to the Alliance, said: ‘The purpose of these briefings is to update Her Majesty on political developments that occurred during her absence, and to receive guidance for the future.’” 

“Alongside the parade of familiar faces was one very unexpected figure: Prime Consul Kayode Tau of the Marlinist Consulate. His megaship, Fairfax Vision, was afforded full diplomatic immunity when it arrived in the Achenar system. Considering the turbulent history between the Empire and the Marlinist Colonies, what might Arissa be planning?”
