:PROPERTIES:
:ID:       6f7555b2-09d0-4835-abd1-3b253b2ad0b7
:END:
#+title: Thargoid War Update: January 3309
#+filetags: :Thargoid:galnet:

* Thargoid War Update: January 3309

/20 Jan 3309/

Vox Galactica reporter [[id:139670fe-bd19-40b6-8623-cceeef01fd36][Jade Sanderlyn]] has published a summary of the current situation in the conflict against the Thargoids. 

“Many of us who witnessed those terrifying events in HIP 22460 felt that it was both an ending and a beginning – that history had turned a page. Five months later, the Second Thargoid War has escalated to a point which may yet close the book altogether.” 

“The arrival of the eight Maelstroms resulted in 44 populated systems being completely overwhelmed by the Thargoids. Dozens of neighbouring regions were also attacked by their fleets, leaving starports and settlements ablaze. Billions were killed and billions more fled from their homes as panicked refugees, creating the greatest humanitarian crisis of all time.” 

“Despite the lack of coordination previously provided by Aegis and [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]], anti-xeno efforts have been herculean. Allied, Federal and Imperial warships rapidly responded to form a vanguard against the invaders, and thousands of independent pilots have valiantly fought the Thargoid swarms across multiple battlefields.” 

“Military experts believe that neutralising the Maelstroms will stem the endless waves of Thargoid vessels. Unfortunately, their caustic clouds and repulsing energy waves prevent our ships from exploring whatever resides within. They also generate the same disruptive field found in HIP 22460, which prevents any Guardian-based weapons from functioning within the system.” 

“But there is hope. A small but steady flow of unclassified relics, those strange artefacts recovered from Thargoid surface sites after the Proteus Wave fired, have made their way to Professor [[id:8f63442a-1f38-457d-857a-38297d732a90][Ishmael Palin]] and Ram Tah. A leading theory is that they share esoteric properties with several of the Thargoids’ recent technological advances, and may hold the key to developing countermeasures. Many other scientists are focusing on xenological research, striving to locate a weakness or develop an advantage.” 

“Until such a breakthrough occurs, we are reliant upon our spacefaring warriors to contain the most destructive adversary the human race has ever faced. This is [[id:139670fe-bd19-40b6-8623-cceeef01fd36][Jade Sanderlyn]] for Vox Galactica. Stay safe out there.”
