:PROPERTIES:
:ID:       c4a3a0f8-2430-4db3-b432-a617333e69be
:END:
#+title: Historical Sculptures Stolen
#+filetags: :Empire:3304:galnet:

* Historical Sculptures Stolen

/20 Sep 3304/

A collection of historically significant artworks has been stolen from the Imperial Museum of Culture on [[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]] A 3. 

A local media report stated: 

“The museum’s most popular exhibit is the New Dawn Collection, a sequence of sculptures by legendary artist Lal Candromir. These figures date back nearly a thousand years and commemorate the early settlers of [[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]] agreeing to join the Empire.” 

“This morning, visitors found the entire exhibit empty, with every single one of the Candromir statues gone. Painted onto the wall was a graphic of a winking cat. The museum cannot explain how its security systems were so completely circumvented.” 

Captain Madoc Evander of the Imperial Internal Security Service commented: 

“We are performing forensic analyses and interviewing all staff and visitors. As yet, we cannot confirm any connection between this theft and one that occurred three months ago in the [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] system, despite the identical ‘winking cat’ motif. We will make every effort to capture this criminal and recover these precious cultural artefacts.”
