:PROPERTIES:
:ID:       3af7aba7-a4a8-4be5-a0aa-52b9ed61bdfa
:END:
#+title: Week in Review 19 Jan 3305
#+filetags: :Empire:Thargoid:galnet:

* Week in Review

/19 Jan 3305/

Here are this week’s main stories. 

The conflict in the Paresa system has ended with Nova Imperium being defeated by Imperial forces. As the conflict drew to a close, Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] declared that the isolationists’ forces had been significantly depleted.  

In related news, Imperator Mordanticus, the leader of isolationist group Nova Imperium, has been captured by the Empire. His arrest was made during the conflict between Nova Imperium and the Empire in the Paresa system. The Imperator will be brought before the Senate on Friday the 25th of January to answer charges of treason against the Empire. 

The Interstellar Health Organisation (IHO) has approved Vitadyne Labs’s nanomedicines as a legal medical product. The IHO has lifted all restrictions, with the caveat that distribution must be handled by an established pharmaceutical company. 

The disappearance of famous actor Consuela Knight and the crew of her luxury yacht has sparked a flood of rumours. Independent reporter Flint ‘Firemaker’ Lafosse discussed the mystery on the [[id:d06803e0-267c-4ffc-88f2-967058fce82e][Rewired]] news feed, speculating that a Thargoid weapon could be responsible, among other theories.  

Finally, the Omega Mining Corporation has requested deliveries of raw materials for a new Orbis starport, to be built in the heart of the galaxy. The construction of this starport constitutes part of the ambitious Distant Worlds II expedition. Project leader Erimus Kamzel stated the objective to be humanity’s first starport in the Galactic Centre region. 

And those are the main stories this week.
