:PROPERTIES:
:ID:       351a9697-0812-42ba-bf4f-8eb1a1fbf938
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/5c37b210-72ff-4837-914c-3b62026bfd52?resourceVersion=id%3A4872
:END:
#+title: Thargoids Attack Coalsack and Witch Head Nebulas
#+filetags: :Federation:Alliance:Thargoid:galnet:

* Thargoids Attack Coalsack and Witch Head Nebulas

/31 Dec 3306/

*Pilots Federation ALERT* 

Large numbers of Thargoid vessels are swarming through multiple inhabited systems, leading to urgent calls for assistance. 

In what appears to be a coordinated strike, Thargoid scouts and interceptors have appeared throughout the Coalsack and Witch Head Nebulas. Local security ships have engaged them in combat, but report being overwhelmed. 

The Alliance has a considerable presence in these regions, with four starports recently constructed in the Coalsack Nebula. But the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] has not been able to mobilise in time to prevent some systems from becoming infested with Thargoids. 

Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], chief military liaison for Aegis, made this announcement: 

“This is a resurgence of Thargoid activity on a scale that we have not witnessed for a long time. Unfortunately, drastic reductions in funding and resources mean that Aegis is unable to provide adequate defensive measures.” 

“We urgently request support from independent pilots and anti-xeno squadrons. It is critical that we prevent the Thargoids from dominating these nebulas and wiping out many thousands of people.”
