:PROPERTIES:
:ID:       504e6a54-5f34-47b0-8e87-8196100f8fcb
:END:
#+title: Emperor’s Killer Not Working Alone?
#+filetags: :3301:Empire:galnet:

* Emperor’s Killer Not Working Alone?

/23 Aug 3301/

Emperor’s Killer Not Working Alone? 
 
While Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]] has provided almost daily updates on the investigation of Emperor Hengist Duval’s assassination there has been little progress of note until today. The breakthrough is reported to have originated from an investigation into the killing of Brendan Paul Darius’ family. 

The local investigator, Inspector Reeve, discovered encrypted data files hidden within the toys of the six year old girl killed in the attack. These files have revealed the existence of a secret group – calling themselves Emperor’s Dawn. They are an ultra-traditionalist movement fearing the erosion of imperial values. 

The exact reason why the Emperor was targeted is as yet unknown, but it was discovered that Princess Aisling has also been targeted by the group. In response to this threat her security has been increased. 

Chancellor Blaine concluded his update by saying: 

“This unexpected development has revealed a hideous cancer within our society. One that will be hunted down and eradicated with the utmost urgency.”
