:PROPERTIES:
:ID:       9448050d-03b7-4e80-857f-0fd4ac657928
:END:
#+title: Torval Offers Support to Patreus
#+filetags: :3301:Empire:galnet:

* Torval Offers Support to Patreus

/13 Aug 3301/

Torval Offers Support to Patreus 
 
Some of the more sordid elements of Imperial media have continued their campaign against Senator Patreus about his connection with Emperor Hengist Duval’s killer. 

Over the past week Senator Patreus and his followers staying on Capitol have endured abuse from their accusers whenever they appear in public. This escalated into violence today as the Senator visited the Hall of Martyrs for his own viewing of the Emperor’s body. When he arrived a mob formed and tried to prevent him entering the vestibule and reacted angrily when Patreus’ own guards attempted to force a passage. Imperial Naval infantry on the scene separated the parties and allowed Senator Patreus to enter the Hall. 

After the incident Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] was the first to condemn the behaviour in a statement to guests and press at an event with Mastopolos Mining: 

“This kind of insolent behaviour does not reflect well upon these groups or our beloved Empire itself. In this time of mourning we should all be mindful of our actions. The Emperor has been dead for only a few days and these rebels descend into near-barbarism. They should be cast out of the Empire.” 

When asked about the accusations she scornfully replied: 

“Denton represents what is strong within the Empire. His loyalty to the Emperor is unquestioned and anyone suggesting otherwise is a fool.”
