:PROPERTIES:
:ID:       fc4aaab7-2d55-4751-a33d-e305953b5f4e
:END:
#+title: Didiomanja Emperor’s Grace Academy Campaign Concludes
#+filetags: :3304:galnet:

* [[id:d508fb0f-0214-4133-829f-edb61e2681d0][Didio]]manja Emperor’s Grace Academy Campaign Concludes

/13 Jul 3304/

The [[id:d508fb0f-0214-4133-829f-edb61e2681d0][Didio]]manja Emperor’s Grace Academy has announced that its initiative has reached a successful conclusion. Large quantities of exotic food and drink, and mined resources, were delivered to Leydenfrost Dock over the past week, allowing the organisation to host a sumptuous banquet and construct a monument in honour of Admiral Mira Tiverion. 

A spokesperson for the [[id:d508fb0f-0214-4133-829f-edb61e2681d0][Didio]]manja Emperor’s Grace Academy released the following statement: 

“That was a banquet fit for an emperor. The food was sumptuous, the drink exquisite, and the revelry went on well into the early hours. I am certain Admiral Tiverion would have approved.” 

Pilots who contributed to the initiative can now collect their rewards from Leydenfrost Dock, in the [[id:d508fb0f-0214-4133-829f-edb61e2681d0][Didio]]manja system.
