:PROPERTIES:
:ID:       a4a79f07-e8bd-4d3c-b7d2-036939566346
:END:
#+title: Freelance Report: Officials Deny Funding 'Turbo Hour' Endurance Race
#+filetags: :3302:galnet:

* Freelance Report: Officials Deny Funding 'Turbo Hour' Endurance Race

/22 Jan 3302/

Officials at Kanwar Horizons in the Turbo system have strenuously denied allegations of involvement in an unsanctioned Buckyball Racing Club event known as the 'Turbo Hour Endurance Race', which will apparently run alongside the station's annual air show and starship exhibition. 

Station entertainment director Hector LeMans described as "preposterous" claims that the Turbo Blue Netcoms Exchange was secretly bankrolling the race in order to attract larger crowds. "Our air show is wholesome entertainment, and we don't want it ruined by these Buckyballers and their 'high-octane' shenanigans," he said. 

LeMans had a clear message for anyone tempted by rumours of free ship resprays for the winners: "I'm sure that authorities in the 49 D Orionis, Unkulcay and Vasak systems would agree that racers will find the same strictly-enforced speed limits and standard market prices for fuel and repairs at our stations as any other law-abiding pilot." 

The air show will run from the 25th of January to the 12th of February. 

Commander furrycat
