:PROPERTIES:
:ID:       70668c69-0329-426f-81c5-226fc250d4e0
:END:
#+title: Eotienses Rejuvenation Project Unveiled
#+filetags: :galnet:

* Eotienses Rejuvenation Project Unveiled

/21 Apr 3301/

In what many pundits are calling a clear attempt to consolidate his position as the most influential arms dealer in the Empire, Senator Denton Patreus has today announced an initiative to rejuvenate Parkinson Dock, in order to promote the development of High Tech goods in Eotienses. 

The initiative, which is being overseen by the Citizens’ Forum, aims to bring thousands of new jobs to the region. Imperial corporations are already engaged in a hot bidding war over rights to establish a presence on the newly reinvigorated Parkinson Dock, despite rumours that most of the available space has been reserved for businesses with established ties to the Senator.   

In order to properly repurpose the facilities aboard Parkinson Dock, the Citizens’ Forum has placed several sizable orders of Industrial Materials in the local market. Once those orders are filled, engineers will be able to start work on the rejuvenation process.
