:PROPERTIES:
:ID:       d1545e97-076b-4d7d-897c-0fc57741cd69
:END:
#+title: Jasmina Halsey Becomes Federal Ambassador
#+filetags: :galnet:

* [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] Becomes Federal Ambassador

/26 Mar 3307/

Former President [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] has joined the Federal Diplomatic Corps to become an ambassador to the Alliance.  

In recent years Halsey served as an advisor to Prime Minister Mahon, but returned to [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] in January to stand as a witness in the Starship One trial. She was a guest of Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] at the Galactic Summit, and both were evacuated back to Mars when it was cancelled. 

At a press conference, Ambassador Halsey said: 

“Being at the conference reminded me that the political arena is where I belong. My new responsibilities allow me to continue serving [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] while making use of my experience within the Alliance, and hopefully build stronger bridges between the two.” 

Elijah Beck, head of [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Office of Diplomatic Relations, sent this message: 

“Jasmina’s level-headed advice has calmed many tense political situations. This is the ideal role for a diplomat of her calibre, and I look forward to working with her again.” 

In related news, the Federal Diplomatic Corps confirmed that Ambassador Jordan Rochester had been recalled from duty to be reassigned. Most of [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] and Federation’s embassies in each other’s space have been closed since November 3306.
