:PROPERTIES:
:ID:       2cb2cc86-5816-4638-96b4-4cea7b2682b9
:END:
#+title: Freelance Report: GalCop Mobilizes to Aid Jaques Station
#+filetags: :3302:galnet:

* Freelance Report: GalCop Mobilizes to Aid [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station

/23 Jul 3302/

Since contact with [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station was re-established, a substantial effort from independent pilots to deliver meta-alloys to the stricken starport has returned it to partial functionality. 

With the commodities market now open, [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] has issued an appeal for the components needed to restore his station to full operational status. The Galactic Cooperative of Worlds has pledged to ensure the success of the initiative, having secured a logistical supply chain and established an operational beachhead in the surrounding sectors. 

Jahena Yar Savor, GalCop's Chief Executive Officer, said that the Cooperative would "establish a localised resource base in the systems surrounding [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] in order to offset the financial burden of securing these resources. Many of our pilots and member organisations acquired substantial wealth during the Dangerous Games, and we thought it would only be fair to use these assets to aid a friend." 

'Disc' Commander Felix Dyson - Radio Skvortsov
