:PROPERTIES:
:ID:       c3cb33c3-bd3d-4160-a164-b7bcb5743a1f
:END:
#+title: Rival Initiatives to Decide Reorte’s Future
#+filetags: :3308:Federation:Alliance:Thargoid:galnet:

* Rival Initiatives to Decide [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]’s Future

/24 Mar 3308/

*Pilots’ Federation ALERT* 

Deliveries to the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition or the Reorte Pro-Alliance League will help determine the system’s status. 

The system’s controlling faction wishes to declare independence, in protest against [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]’s proposed anti-xeno defence pact with the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]].  

The [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition’s CEO Fergus Cassidy announced: 

“Prime Minister Mahon’s insistence on working with [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] leads us to believe our interests are best served outside of the Alliance. To prepare for [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]’s potential transition to an independent system, we ask for shipments of advanced medicines, skimmer components and building fabricators to be delivered to Davies High starport.” 

It is expected that if [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition is successful, all systems currently under its governance would similarly be classified as independent. 

Another faction in the system, the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Pro-Alliance League, broadcast a statement in opposition by chief administrator Louisa Leblanc: 

“Severing [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]’s links with the Alliance over some misguided idealism would be hasty and short-sighted, given the Thargoid threat this pact is intended to prepare for. We believe that increasing supplies of advanced medicines, skimmer components and building fabricators will reassure the public of the benefits of membership.” 

“The [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] Independents faction has kindly provided a megaship, the Trobairitz, where pilots can deliver these commodities.” 

Although [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] is not officially involved with these competing initiatives, it is offering pre-engineered heat sink modules to independent pilots who make deliveries to the Trobairitz.
