:PROPERTIES:
:ID:       717ad70d-77c9-4f90-8f32-5c95cb82f36a
:END:
#+title: Archon Delaine Seeks to Destroy Pirate Rebels
#+filetags: :3308:Federation:galnet:

* [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] Seeks to Destroy Pirate Rebels

/19 May 3308/

*Pilots’ Federation ALERT* 

The Kumo Crew syndicate has engaged in open warfare on the pirate insurrectionists gathered in the HIP 10792 system. 

A recent coup attempt led by Arch-Corsair [[id:8d019f27-75a9-4758-8600-327aee0e2c41][Vidar Trask]], formerly one of the senior members of the Kumo Council, has failed. His forces were unable to eliminate Delaine and take control of the criminal organisation. 

The rebels’ vessels have concentrated in HIP 10792. Trask is commanding a coalition of loyalists, independent pirate gangs and as-yet unidentified mercenaries, collectively calling themselves the Trask Death Corsairs. 

Despite suffering from some visible wounds as a result of the assassination attempt, [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] broadcast this message: 

“Trask has betrayed all of us, and for that I want him crushed! I will pay well to wipe out every single traitor who fights in his name.” 

The Kumo Council faction will reward all independent pilots supporting its operation against the Trask Death Corsairs in the HIP 10792 system, which is being orchestrated from Crimson Exchange.
