:PROPERTIES:
:ID:       56546797-9fed-49c6-858b-62f71fff18eb
:END:
#+title: Galactic News: Treasure Hunt Comes to an End
#+filetags: :galnet:

* Galactic News: Treasure Hunt Comes to an End

/29 Mar 3302/

The treasure hunt organised by billionaire philanthropist Alfred Jeffress has come to an end, with a pilot by the name of Commander Oriza claiming victory. Thousands of people took part in the competition, but ultimately there could only be one victor. 

As with Jeffress's previous treasure hunts, competitors were required to solve a series of riddles to find the mystery object at the centre of the search – a relic from Earth's past. The clues took pilots to Persephone in the Avalon system, then to Arrhenius Terminal in Bard and finally to the Algol system. 

When the winner was announced, Alfred Jeffress released the following statement: 

"I would like to extend my sincere congratulations to the winner. One of my representatives will be in touch soon to give you the details of your prizes. As for the other competitors, I would like to offer my commiserations. But do not despair! There will be another Jeffress treasure hunt, and next time the winner could be you."
