:PROPERTIES:
:ID:       77f17fc2-eec3-4023-be08-7bc96367e034
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/ec8b71a6-b1dc-44fe-b76a-b64adba05ff3?resourceVersion=id%3A4890
:END:
#+title: Core Dynamics Insider Discusses Lakon Takeover
#+filetags: :Federation:galnet:

* Core Dynamics Insider Discusses Lakon Takeover

/13 Jan 3307/

An anonymous source within the shipbuilding corporation Core Dynamics has revealed details behind its hostile takeover of Lakon Spaceways. 

The nameless insider had previously stated that the acquisition of Lakon was the personal project of Core Dynamics CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]]. These additional claims were broadcast via Vox Galactica: 

“In the last few years, Rochester has purchased many companies based outside the Federation, such as Vodel. Lakon Spaceways is just the latest. It seems legal, but he manages these subsidiaries directly and installs his own people there. Some say he’s diversifying his family’s private holdings, rather than expanding the business.” 

“It’s well known that several departments only follow Rochester’s directives, and operate in silos unconnected with the rest of Core Dynamics. Staff refer to them as ‘Jupiter Division’. Some offices even started using that name, like they’re a separate company within a company.” 

“I’ve heard that some directors are unhappy with Rochester, but he’s too well-connected to ever get rid of. It’s thanks to him that we have so many military contracts. As always, the rich get away with anything.” 

Core Dynamics declined to comment on this statement. Naomi Landseer, former chairperson of the Lakon Spaceways board of directors, has asked the Independent Commission for Market Equality to investigate further.
