:PROPERTIES:
:ID:       16304a78-2405-4923-9fb3-7d550236e9e1
:END:
#+title: Galactic News: Colonia Council Initiative Concludes
#+filetags: :3302:galnet:

* Galactic News: [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Council Initiative Concludes

/03 Nov 3302/

The [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Council has announced that its appeal for palladium was a resounding success, with hundreds of pilots delivering materials to [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in response to the request. The materials will be used to support further colonisation of the Colonia Nebula, and address the needs of the growing Colonia community. 

A spokesperson for the organisation released a brief statement: 

"This material will help us bolster infrastructure in the system, and support the forthcoming colonisation programme. But more than that, it will help us lay the foundations of a better, brighter future." 

"The future is here, and its name is [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]." 

Pilots who contributed to the initiative are now free to collect their rewards from [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system.
