:PROPERTIES:
:ID:       8edb93c3-c356-470c-93ee-565da76482f8
:END:
#+title: Superpowers Respond to New Onionhead
#+filetags: :galnet:

* Superpowers Respond to New Onionhead

/03 Aug 3307/

The Alliance, Empire and Federation have clarified their official positions regarding the emergence of onionhead gamma strain. 

All variants of the popular psychedelic drug remain illegal within Federal space. Ambassador Jasmina Halsey, who was president in 3300 when the ruling was made, announced: 

“I am pleased that my decision to outlaw onionhead stands. I still maintain that it leads to experimentation with more dangerous narcotics, and we must steer our youth away from that path.” 

The Empire has also declared onionhead illegal, despite rumours that it is imported by the wealthiest citizens for private use. Princess Aisling Duval told the media: 

“It was insulting enough that Delaine was allowed into the Galactic Summit, but now he’s peddling filthy drugs and pretending it’s medicine! I only pray that nobody loses a loved one to such poison, as I have.” 

The Alliance has not made a broad ruling regarding onionhead, which is illegal in the majority of member systems but available in those classified as having anarchy governments. However, Deputy Prime Minister Angela Corcoran addressed the issue: 

“As with most trade, we defer to the legislation of local authorities. But we are in contact with the IHO and are keeping a close eye on the situation.” 

Onionhead gamma strain remains on sale in selected systems governed by industrial anarchy factions.
