:PROPERTIES:
:ID:       006e82f5-1a48-4c51-9ba9-7a7cc6efd3c3
:END:
#+title: Freelance Report: Looking for Peace, or War?
#+filetags: :galnet:

* Freelance Report: Looking for Peace, or War?

/13 May 3302/

Dr Derthek, a founding member of the Canonn Interstellar Research Group, has embarked on an ambitious project to map NGC 6357, also known as the War and Peace Nebula, in its entirety. 

Before departing, Dr Derthek gave a brief interview explaining his motivation: 

"I've examined the Unknown Artefacts, I've seen the barnacles, I've even completed a circumnavigation of the galaxy. But the estimated 13,000 systems of NGC 6357 have always fascinated me. It's one of the most prominent sites of massive-star formation close to the bubble." 

"I think there's something out there, although I don't know what. But it'll be my home until my ship, the RSV Canonn, has visited every single system. I might find more barnacles, more UAs, or something entirely new. Who knows?" 

Hundreds of fellow scientists have sent messages of support, and Universal Cartographics is understood to be eagerly awaiting Derthek's return. 

Commander Lord Zoltan
