:PROPERTIES:
:ID:       d5e7fbad-c061-4074-988b-25cc8745c5d4
:END:
#+title: Technical Trouble in 49 Arietis
#+filetags: :3301:galnet:

* Technical Trouble in 49 Arietis

/23 Oct 3301/

Amid news that the technical issues plaguing the Warkushanui system have worsened, reports are coming in that starports in the system of 49 Arietis are experiencing similar problems. According to Blake Fry, a commercial freight pilot who regularly traverses the 49 Arietis system, the starport of Gaiman Dock has been hit with a plethora of issues in recent hours, including power outages and system failures. Speaking to the Federal Times, Fry said: 

"I don't know exactly what's going on, but they've got problems popping up all over the place. Energy, infrastructure – everything's on the fritz. They're in a world of pain over there." 

When asked if he had any theories on what was happening at Gaiman Dock, Fry was unequivocal: 

"Hey, I read the news. I'm not stupid. First they take those alien pods there, and then there's a complete technical breakdown. Didn't they say those AEO things damaged machinery? Join the dots, man!" 

The issues in 49 Arietis are not believed to be affecting station services at this time.
