:PROPERTIES:
:ID:       ddb042a9-abaa-49cb-a470-7d443f98cf2a
:END:
#+title: Death of a Duval
#+filetags: :galnet:

* Death of a Duval

/17 Sep 3306/

Imperial news sources have confirmed that Prince Harold Duval was assassinated by NMLA terrorists while travelling incognito to the Cemiess system. 

Emperor Arissa Lavigny-Duval broadcast this address: 

“It is with great sadness that we announce the passing of our beloved Prince Harold. A state funeral at the Hall of Martyrs is being arranged and there will be a period of mourning, as is customary for esteemed members of the Imperial Family. There will be opportunities for all citizens to honour Harold’s memory in an appropriate manner.” 

Princess Aisling Duval, Harold’s daughter, appeared uncharacteristically distressed when she gave a brief statement to the media: 

“It’s a huge loss to us all that… I’m sorry… I can’t believe this has happened. He can’t be gone! I used to have some sympathy for the Marlinists, but now they… they took him from us. They took my daddy.” 

The NMLA also attacked starports in the Cemiess, Gabjaujis, LHS 4031 and Rabh systems.  

The Empire is now on heightened alert, and the Senate has approved new counter-terrorism initiatives proposed by Senator Denton Patreus.
