:PROPERTIES:
:ID:       edcee85e-14be-4f00-9829-53e6ef388a3b
:END:
#+title: Sirius CEO Faces Assembly Inquiry
#+filetags: :Alliance:Thargoid:galnet:

* [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] CEO Faces Assembly Inquiry

/08 Jan 3310/

[[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]], CEO of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]], has addressed the Alliance Assembly as part of its formal inquiry into the strategic defence pact. 

The inquiry was proposed by Councillor [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]], who highlighted the lack of military support provided by the megacorp against the Thargoids. 

When invited to explain why most of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]’s plans have not materialised, [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] said: 

“Many new anti-xeno ship configurations were designed for the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] and have been applied to thousands of ships. But we have encountered many obstacles along the way, which have severely undermined our progress.” 

“Usually these obstacles are bureaucratic in nature, but sometimes we simply cannot communicate effectively with the necessary individuals. I find it hard not to conclude that our progress is being deliberately impeded by forces within government departments. Sadly, not everyone shares Prime Minister Mahon’s vision of using our resources and expertise to enhance Alliance naval capabilities.” 

Councillor Kaine directly challenged this statement, accusing Yong-Rui of failing to honour his responsibilities. He responded: 

“May I remind the honourable councillor of her recent failed endeavour in the [[id:0b991a8e-234a-4888-8c0a-b3c64498f217][Tionisla]] system to ‘prove the Alliance doesn’t depend on [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]’. While the Alliance is a powerful entity with considerable resources, the lack of engagement in Kaine’s campaign suggests Sirius’s involvement remains vital. Our company now handles many of the ADF’s routine logistical supplies, far more efficiently than before. Like it or not, we are here to stay.” 

The inquiry into the strategic defence pact is expected to conduct more interviews within both [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] and relevant Allied organisations. Admiral [[id:2e8a3cd7-5f4e-47dc-ba7f-eb732bf8c7fa][Nikolas Glass]] and other members of the Council of Admirals have also agreed to submit their observations.
