:PROPERTIES:
:ID:       2163a6b0-51ca-43ec-98a8-bf842991eff0
:END:
#+title: Final Week for Colonia Bridge Project
#+filetags: :3308:Federation:galnet:

* Final Week for [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge Project

/03 Mar 3308/

*Pilots’ Federation ALERT* 

Delivery campaigns in the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] and [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] systems will complete the six starports along the Colonia Bridge. 

Months of work on developing the transportation infrastructure between the core systems and the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] region are now coming to an end. Brewer Corporation’s latest press release specified the requirements: 

“For this final week, we are asking pilots to deliver auto-fabricators, micro controllers and resonating separators to Macdonald Settlement in the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] system and [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system. These will allow us to install outfitting, shipyard and tech broker services, as we bring the starports to full operational status. There is also another opportunity to install Pioneer Supplies at Promium Relay, the bridge starport nearest to Colonia.” 

“Brewer Corporation is grateful to independent pilots for their dedication to constructing the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge. We are therefore pleased to offer various classes of pre-engineered, overcharged power plants as well as exploration decals to the top 75% of contributors to this concluding stage.” 

“Finally, this is the last chance for pilots to obtain a Brewer Corporation decal, which will be awarded to every contributor to any of the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge initiatives as a token of gratitude.” 

The top ten contributors for each of the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge initiatives will have the opportunity to be named in tourist beacons that will commemorate the project’s conclusion.
