:PROPERTIES:
:ID:       b7778eb2-d3b3-41fe-98ec-c20dcbc4e7f0
:END:
#+title: Rackham Hacked
#+filetags: :3304:galnet:

* Rackham Hacked

/18 Oct 3304/

Billionaire businessman Zachary Rackham has been targeted by a highly sophisticated hack that successfully withdrew 1 billion credits from his personal account. 

A spokesperson for Rackham Capital Investments informed shareholders: 

“We have reported the theft to the authorities, and are reviewing our computer security systems. The only clue as to the criminals’ identity is a message they left encoded in Mr Rackham’s account: ‘The Collective plays to win.’” 

Financial journalist Bryanna Blanco commented in [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“The purpose of the hack was evidently to reclaim the billion-credit prize that Rackham ‘won’ in the Federal Grand Lottery. What Rackham Capital Investments didn’t reveal was that the money was redistributed equally among several hundred of the company’s former employees, who were denied their company pensions years ago.” 

“There is a sweet irony to the old pirate Calico Zack having his money stolen by cyber pirates. Whoever the Collective might be, they seem to have both a sense of justice and a sense of humour.”
