:PROPERTIES:
:ID:       64a1ecf0-cc17-499c-b86b-49d8f46cfc05
:END:
#+title: Thargoids Repelled from Core Systems
#+filetags: :Thargoid:3304:galnet:

* Thargoids Repelled from Core Systems

/22 Jun 3304/

Aegis has confirmed that the Thargoid presence in the core systems has been significantly diminished, due largely to the efforts of the galactic community. 

Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], chief military liaison with Aegis, made this statement: 

“This is a very positive development. Using data from our Eagle Eye network, courageous members of the galactic community have formed a barrier of steel and fire, preventing Thargoid vessels from encroaching further. In doing so they have prevented several starports from being attacked, saving many thousands of lives.” 

“Furthermore, in many regions the Thargoid incursion has actually been reversed. Although they remain entrenched within the Pleiades, their forces in the core systems have been pushed back to the Bhal system, their initial beachhead.” 

“Aegis offers its sincere thanks and congratulations to every one of the Commanders who risked their lives by meeting our enemy in battle. These audacious pilots have proved that humanity’s spirit is far from broken. Victory against the Thargoids will be hard-won, but I am in no doubt that with defenders of this calibre, it will one day be achieved.”
