:PROPERTIES:
:ID:       5b5e3c5b-37fe-47c5-b7ed-0e4619c840bd
:END:
#+title: Community Goal: Expanding the Imperial Fleet
#+filetags: :Empire:CommunityGoal:3302:galnet:

* Community Goal: Expanding the Imperial Fleet

/21 Apr 3302/

Admiral [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] has announced plans to expand the Imperial Navy with a new Majestic-Class Interdictor. The formidable vessel will boast a range of imposing weaponry, including an array of modular interceptor guns. 

Lieutenant Severin, who is overseeing the ship's construction, issued a statement to the media: 

"I know there are some who would question the need for this vessel. To those individuals, I say this: just how safe do you feel? We live in an age in which even Emperors can be murdered. An age in which our enemies' faces are not known to us, and betrayal and deceit are encountered at every turn. The need for a strong, battle-ready navy has never been greater." 

"In order to complete production as swiftly as possible, we have placed an open order for supplies, and have authorised the Mundjiga Patrons of Law to reward pilots who deliver materials to our base of operations at Sagan Port. I implore all those who are loyal to the Empire to support this operation." 

The campaign begins on the 21st of April 3302 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
