:PROPERTIES:
:ID:       e8f922d1-5b2c-4b35-90f3-6f0d03f2fcb4
:END:
#+title: The Code Leaves Archon Delaine's Crew
#+filetags: :3301:galnet:

* [[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] Leaves [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]'s Crew

/24 Jul 3301/

[[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] Leaves [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]'s Crew 
 
Some months ago, Archon approaches Captain Anopheles of [[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] and says: 'Ano, you're my kind of guy. Your crew has been making waves as the most successful of all the pirate crews. Come over to me and make an alliance. I have my tech guys making some sweeeeeeeet tech and I'm running my own space. You can be one of my trusted lieutenants if you bring your guys over." 

That sounded good, so Anopheles took his boys over to [[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]]. Discontent started almost immediately when they learnt that running a couple of systems was less about scantily clad slave girls serving you rum and more about being a bureaucrat. 

When the new weapon was revealed, that was the last straw for [[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] as it wasn’t what they’d expected. 

Captain Anopheles met with Archon and they have a frank and lively debate with added knives. [[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] gave him two weeks for things to get better. Arechon refused to change for them, so [[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] left. 

[[id:c00dcd18-778c-4fca-acbd-cba6f2ded57e][The Code]] are going back to basics and going to be roaming the space lanes as "independent asset redistributors". In short, they have left the desk behind and have picked up their grappling hooks again.
