:PROPERTIES:
:ID:       97100d10-1cb5-488d-82eb-729e40a27e54
:END:
#+title: Experimental Weapons Stabiliser Becomes Available
#+filetags: :Federation:Thargoid:galnet:

* Experimental Weapons Stabiliser Becomes Available

/26 Jan 3309/

*Pilots’ Federation ALERT* 

The class 3 experimental weapon stabiliser is now available following [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]]’s delivery initiative in LHS 1163. 

The corporation’s PR division confirmed the release of its new product in a press release: 

“This variant of Azimuth’s experimental weapons stabiliser is now widely available for purchase. By redirecting and absorbing internal stresses, it allows a ship to carry a total of five AX weapons rather than the previous limit of four. The class 5 variant of the stabiliser, which permits two additional AX weapons, is scheduled to reach the market next week.” 

“Our manufacturing partners were able to begin this rapid production cycle thanks to receiving great quantities of meta-alloys, insulating membranes, HN shock mounts and beryllium. Pilots who delivered these materials can now collect their rewards from the Glorious Prospect megaship in the LHS 1163 system.” 

“Azimuth Biotech remains fully committed to supporting anti-xeno initiatives. Our team will continue playing a significant role in combating Thargoid aggression and protecting innocent lives.” 

Retail outlets have reported an increase in purchases for both AX missile racks and multi-cannons, including the enhanced designs recently produced by the engineers [[id:cb71ba02-e47b-4feb-a421-b1f2ecdce6f3][Liz Ryder]] and Zacariah Nemo. The class 5 variant of the experimental weapons stabiliser is expected to further boost sales of AX weaponry when released on Thursday 2nd February.
