:PROPERTIES:
:ID:       c165e88b-f466-4257-bbd1-a21a6a586074
:END:
#+title: Reorte System Remains Allied
#+filetags: :Federation:Alliance:Thargoid:galnet:

* Reorte System Remains Allied

/31 Mar 3308/

*Pilots’ Federation ALERT* 

The Reorte Pro-Alliance League’s success over the Reorte Mining Coalition means the system will stay in the Alliance. 

A greater quantity of advanced medicines, skimmer components and building fabricators were delivered to the Trobairitz megaship than to the opposing faction. As a result, Reorte will remain an Allied system. 

Pilots who contributed to the Reorte Pro-Alliance League’s initiative can now collect their rewards at the Trobairitz, along with the additional pre-engineered heat sink modules provided by Sirius Corporation. 

Chief Administrator Louisa Leblanc proclaimed: 

“I am deeply grateful to all those who helped convince our people that Reorte’s future is more secure with the Alliance. We look forward to working alongside Sirius Corporation on increasing defences against the Thargoids.” 

The Reorte Mining Coalition’s CEO Fergus Cassidy expressed his regret that their campaign to renounce membership of the Alliance failed to gather the necessary support. He thanked those who supported them, and confirmed that credit rewards for contributing pilots are now available at Davies High starport.
