:PROPERTIES:
:ID:       2cedd6d6-1a2d-4cbd-930c-7020da6aeaad
:END:
#+title: Far God Deportation Programme Approved
#+filetags: :galnet:

* Far God Deportation Programme Approved

/12 Jun 3309/

The Federation has agreed to the expulsion of all adherents of the Order of the Far God to the Alliance. 

President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] issued a statement alongside the government decision: 

“Any ideology that worships the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] is destructive and treasonous, especially now we are at war with that species. I believe that rather than waste taxpayers’ money keeping these deluded individuals incarcerated, [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] is better off without them.” 

“This morning I accepted Prime Minister Mahon’s proposal. All former citizens known to have pledged themselves to this toxic religion will be transported beyond our borders and into the care of the Alliance.” 

Security services have prioritised the True Chapters cultists currently imprisoned in the Popontia system, labelling them as high-risk compared to orthodox Far God followers. They will be escorted to Alliance space aboard the Dedicant, having agreed to provide full access to the megaship’s databanks and the Order’s sacred texts for Federal assessment. The Dedicant will then collect cultists held in other Federal penal facilities, ferrying them to Allied systems. 

Political correspondent Sofia Trevino wrote an opinion piece for The Federal Times: 

“Could there be an ulterior motive to this unexpected decision by the President? Perhaps Hudson is mindful of his legacy, with his term of office approaching its end. By tempering his ‘strong man’ reputation with a degree of leniency, he can better portray himself as a firm but fair leader in the Federation’s history books.”
