:PROPERTIES:
:ID:       3cfac0b1-0688-413b-971d-51ccd60d86f3
:END:
#+title: The View from Colonia
#+filetags: :galnet:

* The View from Colonia

/29 Oct 3307/

Vox Galactica’s culture correspondent Lishan Abara looks at the Colonia region, the largest enclave of humanity outside the core systems: 

“Colonia. A place that few ever see, which exists following a computer malfunction. The famed Jaques Station suffered a mis-jump on its scheduled journey to Beagle Point, relocating some 22,000 light years from Sol. The subsequent rescue effort led to the establishment of the first permanent base in what is now considered a new frontier for humanity.” 

“Over the last five years, courageous explorers have struck out to inhabit several dozen local systems. This, in turn, invited a steady stream of colonists seeking a fresh start. Nearly 13 million souls now count this remote area as their home.” 

“This is a place beyond the influence of the superpowers and mega-corporations, and most residents prefer it that way. The Colonia Council works hard to maintain order, helping local organisations function along cooperative lines. There have been a handful of regional conflicts, but generally you’re less likely to witness trouble out here.” 

“Having become self-sufficient early on, Colonia’s healthy economy encourages both traders and tourists to make the long journey. The scientific community maintains a notable presence, a notable example is the Holloway Bioscience Institute, which studies the many vacuum-dwelling life forms found in the Colonia Nebula.” 

“Independent and faction-aligned pilots are catered to, with shipyards and even a fleet carrier construction dock found in the area. Local engineers such as Baltanos, Eleanor Bresa, Rosa Dayette and Yi Shen also offer suit and personal equipment modifications to those who make a living working on low-atmosphere worlds.” 

“With the Colonia Bridge project well underway, it will soon be easier than ever to cross the interstellar gulf and reach this distant haven. Businesses, settlers and visitors alike may find themselves increasingly drawn to the Colonia experience.”
