:PROPERTIES:
:ID:       45597580-5548-4667-9a31-da62c8cf5fbc
:END:
#+title: Freelance Report: Fragile Unity in Federal Congress
#+filetags: :3303:galnet:

* Freelance Report: Fragile Unity in Federal Congress

/01 Jul 3303/

Following disturbing reports of attacks on Federal ships in the Pleiades Nebula, the partisan rancour that often characterises Federal Congress has faded into the background as both Republican and Liberal members of congress rally around President Zachary Hudson. Rumours that the attacks were perpetrated by the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] abound, prompting calls for increased military spending. 

Emerging in the wake of the no-confidence vote that resulted in the expulsion of former Federal president Jasmina Halsey, the bellicose Hudson administration was seen by many as emblematic of the Federation's uncertain path into the 34th century. But the possibility of an alien incursion is rapidly smoothing over the political sore points. 

Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] has been careful to neither endorse nor condemn Hudson’s militaristic rhetoric. Meanwhile, both the Republican and Liberal parties have remained silent on the post-presidential career of Jasmina Halsey, whose advocacy for galactic peace contrasts sharply with the hawkish leader who ordered planetary bombardments against onionhead growers in the Kappa Fornacis system. In the political press, attention has focused on the fact that Halsey has become a close confidante of Alliance Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] – another moderate voice on the intergalactic stage. 

Morrenwell
