:PROPERTIES:
:ID:       55980165-99c6-416f-a9cd-fd71c805a53d
:END:
#+title: Public Unnerved by Palin Announcement
#+filetags: :Thargoid:galnet:

* Public Unnerved by Palin Announcement

/15 Nov 3308/

The announcement that the rogue signal sources heading towards the core systems are Thargoid in origin has caused unease within the general public. 

Protests in systems on the edges of human space have taken place, demanding assurances from local governments about their safety. The failure to establish a collective human fleet to counter Thargoid incursions has left many concerned about what the future may hold. 

Casey Kilpatrick provided this report from Castellan Station in Lave: 

“Colleagues across multiple systems have confirmed that the impending arrival of the rogue signal sources – termed ‘stargoids’ by some in network media – has led to a shared sense of anxiety. [[id:a12cdcbc-fa10-474e-8654-d3d7da17a307][ICE]] networks are seeing high interest in topics related to Thargoids, with negative sentiment aimed at politicians and military figures seen as responsible for the Proteus Wave event which perhaps attracted the anomalies. Witnesses report families transporting all they own to ships bound for the opposite side of the bubble.” 

“Palin’s opinion that humanity may not be ready for what happens next has been criticised as needlessly alarming. While Palin is a brilliant scientist, his communication skills have been called ‘less than ideal’ in recent days. Yet his supporters, particularly among academics, have argued that it would be cowardly to hide the [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]]. If humanity is truly in danger, the statement at least could prompt a fresh allocation of resources to military organisations while also giving independents time to prepare.” 

“Vista Genomics has reportedly contacted the team working alongside Professor Palin with a proposal to share its genetic database with ongoing research projects. The potential importance of such data may precede an increase in payments to those who record and submit genetic samples.” 

“The news has also caused a stir across most financial markets. The main issue is the unpredictability of what this could mean for primary industries and their ability to maintain traditional supply and demand. The cost of goods and services may be impacted across clusters of systems. The Bank of Zaonce has announced it is monitoring the situation and is preparing several potential strategies in the event of an interstellar recession.” 

“In conclusion, most are left with a rather unpalatable course of action: To sit and wait. No superpower has announced a means to prevent the Thargoid anomalies from reaching us. Palin’s announcement has hypothesised on what the signals may be, but could not confirm what they will do. It appears that we will all find out together, for better or worse.”
