:PROPERTIES:
:ID:       43bda207-caa8-4485-82a1-5a03639f3a31
:END:
#+title: Galactic News: [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] Brought Out of Coma
#+filetags: :3302:galnet:

* Galactic News: [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] Brought Out of Coma

/26 Mar 3302/

Federal President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] has released a statement confirming that former president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] has been brought out of her induced coma. 

"The injuries [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] suffered in the destruction of Starship One were severe, but her escape pod preserved her vital functions. Having repaired her injuries, medical personnel at Leoniceno Orbital revived President Halsey from her coma this morning. I have been told that she is now sleeping peacefully, and is expected to wake in the next few days." 

Reporters were told that Halsey would need at least a week before she is likely to be able to talk to those outside her immediate family.
