:PROPERTIES:
:ID:       81b21808-fd06-4fd8-9055-82f9d3695fd4
:END:
#+title: Galactic News: Utopian Campaign Concludes
#+filetags: :3302:galnet:

* Galactic News: Utopian Campaign Concludes

/23 Jun 3302/

A spokesperson for the technologically progressive enclave Utopia confirmed that its appeal for exploration data has reached a successful conclusion. In a statement, the spokesperson confirmed that the campaign received the enthusiastic support of the galactic community, resulting in large quantities of fresh exploration data. 

Simguru [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]], leader of Utopia and architect of the initiative, released a brief statement to the media: 

"My thanks go to those who took the time to support this campaign. The data you have provided will now be analysed, and with luck it will tell us more about what happens to the many spacefarers who disappear every day, every week, every year. How many are abducted? How many run out of fuel, far from home? And how many simply disappear without explanation? Your data will help us answer these questions." 

Pilots who contributed to the initiative are now free to collect their rewards from Terry Port in the Garoku system.
