:PROPERTIES:
:ID:       0d05fb04-f655-4c70-9693-b3b9b47fd25d
:END:
#+title: Federal Citizens Approve Government Scrutiny
#+filetags: :3307:Federation:galnet:

* Federal Citizens Approve Government Scrutiny

/14 May 3307/

The Proactive Detection Bureau, which monitors all civil communications in the Federation, has received a boost from the galactic community.

President Hudson’s campaign for additional data proved so successful that the PDB has dramatically increased the range of its surveillance.

Deputy Director [[id:c70acbbe-4972-439d-927d-ca2ef56af6ae][Bethany Blake]] of the [[id:d75a6c3f-5c3a-418b-b639-5e14b487f568][Federal Intelligence Agency]] announced:

“We are now able to discreetly scan almost every private and public communications network used within Federal systems. As a result, arrest rates have soared and several organised crime rings have been dismantled.”

Shadow President Winters’s efforts to distribute methods of blocking the PDB received considerable support, but failed to eclipse Hudson’s initiative. This was interpreted by the Federal government as a mandate from the citizens to continue its surveillance programme.

[[id:5ad54d92-598e-4168-87d2-c20d079fba7a][Rhiannon Grady]], director of the civil rights organisation [[id:cae00172-0b5e-42f4-b9d7-8b4b37207881][Advocacy]], told the media:

“Since the vast majority of citizens will never receive a visit from the FIA for their activities, the public has no sense of what they have lost. But history teaches us how hard it is to regain freedoms once you’ve given them away. [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][The Federation]] has taken a large step toward becoming an interstellar police state with little regard for the individual.”
