:PROPERTIES:
:ID:       06676c16-edc8-4ea8-ac10-004ff17e4183
:END:
#+title: Hutton Mug Appeal Successful
#+filetags: :galnet:

* Hutton Mug Appeal Successful

/18 Sep 3301/

Hutton Mug Appeal Successful 
 
A few weeks ago, the novelties manufacturer BlipMagnet announced the release of the Hutton Mug – a commemorative beaker sporting the words “I made it to Hutton Orbital”. The item was designed to appeal to those completing the epic journey to Hutton Orbital, which lies approximately 0.22 light years from the nearest star. The concept proved highly appealing, and thousands of independent pilots made the trek to Hutton Orbital to deliver scrap materials for BlipMagnet’s first batch. Following the success of this event, the director of BlipMagnet, Chase Fulbright, released a statement: 

“You guys are awesome! I was so psyched by your response to our appeal. The good news is we’ve got more than enough material for our next run – the bad news is there are a few infrastructure issues we need to address before we can start production. So I apologise in advance for the wait, but rest assured that your Hutton mugs are coming, and as soon as they’re ready we’ll let you know. Peace out!”
