:PROPERTIES:
:ID:       1bf59259-e0ab-4993-a428-1b49e4f011af
:END:
#+title: Community Goal: More Imperial Warships
#+filetags: :Federation:Empire:CommunityGoal:3302:galnet:

* Community Goal: More Imperial Warships

/25 Aug 3302/

The latest development in the ongoing Federal-Imperial conflict takes the form of a statement from Admiral Denton Patreus, who has announced plans to add three new Majestic-class Interdictors to the Imperial fleet. The announcement comes only a week after the successful conclusion of a Federal campaign to amass material for three new Farragut-class Battlecruisers. 

In a candid statement, Admiral Patreus said: 

"We cannot stand idly by while the Federation attempts to establish a monopoly over the meta-alloys. And if the Empire does not oppose the Federation, who will?" 

"So as long as the Federation continues to expand its navy, we will continue to match it, ship for ship." 

The Empire has placed an open order for supplies and has authorised the Morai Nobles to reward pilots who deliver autofabricators, tantalum and superconductors to van de Hulst Vision in the Morai system. 

The campaign begins on the 25th of August 3302 and will run for one week. If the Empire's targets are met earlier than planned, the campaign will end immediately.
