:PROPERTIES:
:ID:       64ef74d4-fc8c-43b2-8b30-28b44b9898fe
:END:
#+title: Week in Review 26 Aug 3304
#+filetags: :3304:galnet:

* Week in Review

/26 Aug 3304/

Here are this week’s major stories. 

The wedding of Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and Ambassador Jordan Rochester has been cancelled. The announcement follows anti-slavery campaigner Jarl Toredo’s confession that he and Aisling Duval were romantically involved for several months. 

Meanwhile, Lakon Spaceways has announced that a new ship, [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Crusader, will go on general sale on Tuesday the 28th of August. The ship, which is based on the Alliance Chieftain, boasts three internal military compartments and a fighter bay. 

Rival technology companies Supratech and Herculean Machines have released press statements promoting new personal-computer designs. Both companies have also confirmed they will be at the Rackham Ultratech Expo on Wednesday the 3rd of October, where they will reveal fully functional prototypes of their new devices. 

In other news, the Federal Intelligence Agency has revealed that members of the Far God cult are disappearing in large numbers. While the FIA has speculated that adherents are abandoning the cult and attempting to return to normal life, there have been no reports of former Far God worshippers returning to their friends and families. 

An exposé published by The Mars Tribune has revealed that Federal Congressman Morgan Unwin has close ties to a criminal organisation. Information uncovered by the Tribune proves that Unwin used his influence to traffic drugs for the Red Family cartel in order to keep his own addiction secret. 

Recent reports from the Betel system indicate that an ongoing feud between the Silver Creative Network and Betel Free has escalated into violence. With system security forces stretched thin, both organisations are seizing the opportunity to settle old grudges, and have issued calls for support. 

Finally, the Colonia Council has announced that its campaign to build a new hydroponics facility has been warmly received by the galactic community. Large quantities of material were delivered to Templar Barracks over the past week, allowing the initiative to move to the construction phase. 

And those are the main stories this week.
