:PROPERTIES:
:ID:       fad698df-5d12-4c41-8113-536945fbba80
:END:
#+title: Alliance-Sirius Military Pact to be Decided
#+filetags: :galnet:

* Alliance-Sirius Military Pact to be Decided

/16 Jun 3308/

*Pilots’ Federation ALERT* 

The Di Jian system is hosting competing campaigns as the Alliance Assembly votes on the strategic defence pact. 

The Assembly is evenly split over formalising military ties with Sirius Corporation to enhance defensive options against the Thargoids, with a decision expected at the end of June. In advance of the vote, both pro-pact and anti-Sirius councillors are attempting to sway colleagues to their cause by securing a sizeable resource package for the Alliance Defence Force.  

Pro-pact councillors have established their initiative in Di Jian from the Sirius megaship Kumiho Sky, and are asking for shipments of computer components, reinforced mounting plates and synthetic reagents. These councillors have heavily promoted the need for enhanced fleet support in the face of increasing Thargoid activity. Noted engineer Marco Qwent recently confirmed his support for an Allied anti-xeno pact with Sirius. 

The anti-Sirius lobby has requested deliveries of the same commodities to Preuss Terminal in the Di Jian system. The system’s controlling faction, Sol’s Salutis Aeternum, is overseeing contributions. Engineers Uma Laszlo and Bill Turner have both expressed a hope that the anti-xeno pact with Sirius is denied. 

To encourage support from pilots, each campaign is offering extra incentives. The majority of contributors to the Kumiho Sky campaign will receive a pre-engineered high capacity AX fixed missile launcher, among other rewards, courtesy of Sirius Corporation. 

Sol’s Salutis Aeternum is instead offering a stock Alliance Chieftain to a limited number of Preuss Terminal campaign contributors. Other rewards are available for contributors outside this number.
