:PROPERTIES:
:ID:       9e766eaa-a15b-4bd5-aa29-e3c14b997e22
:END:
#+title: Galactic News: Former Slaves Receive Aid
#+filetags: :3302:galnet:

* Galactic News: Former Slaves Receive Aid

/11 Feb 3302/

The Paladin Consortium has announced that its recent appeal for water purifiers has been met with a positive response. The initiative was launched after the group freed the Imperial slaves of LFT 37, only to discover that the newly liberated slaves would not legally be able to obtain employment or housing for several weeks. With a potential humanitarian crisis looming, the Paladin Consortium turned to the galactic community for help, asking for deliveries of water purifiers to ensure the former slaves would have access to basic sanitation. 

Following the success of the initiative, authorities in the LFT 37 system released a statement to the media: 

"We are immensely grateful to all those who contributed to this campaign. The former slaves at Onnes Gateway will now be able to enjoy a basic standard of living while they wait for [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] to formally terminate their indenture contracts. Our thanks also go to the Paladin Consortium, which spearheaded this operation."
