:PROPERTIES:
:ID:       530d604f-5b34-45b7-94e3-81eceb0be472
:END:
#+title: Internal Strife Strikes Tanmark
#+filetags: :3301:galnet:

* Internal Strife Strikes [[id:267299e4-1a3f-4835-933d-7a1b30d7d43e][Tanmark]]

/03 Mar 3301/

News is coming out of the [[id:267299e4-1a3f-4835-933d-7a1b30d7d43e][Tanmark]] system of an ongoing conflict having broken out between the Defence Force of Tanmark and a local criminal gang known as the Tanmark Posse. The Tanmark Posse are reportedly the main driving force behind the recent cultivation of Lucan Onionhead in hidden facilities throughout Luca. 

So far, fighting between the two factions has remained confined to the surface of Luca. Security forces are currently in the process of raiding all known [[id:267299e4-1a3f-4835-933d-7a1b30d7d43e][Tanmark]] Posse holdings on the planet, which has caused all but the most loyal gang members to abandon the system in search of more hospitable surroundings.  

A source close to the two groups, who has asked to remain anonymous for their own safety, informed GalNet that the fighting is a direct result of the [[id:267299e4-1a3f-4835-933d-7a1b30d7d43e][Tanmark]] Posse misleading the Defence Force of Tanmark into believing that the cultivation of Onionhead on Luca would be a short term arrangement.  

Now that it’s become clear that Lucan Onionhead has been deliberately modified in order to stop it from being able to produce natural offspring,  the Defence Force of [[id:267299e4-1a3f-4835-933d-7a1b30d7d43e][Tanmark]] are taking pre-emptive steps to ensure that Luca doesn’t suffer the same fate as Panem.
