:PROPERTIES:
:ID:       ccf31bbe-3070-4ab2-83ef-ba1ae548dc84
:END:
#+title: Galactic News: No Sign of Jaques Station
#+filetags: :Federation:3302:galnet:

* Galactic News: No Sign of [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station

/26 May 3302/

Two weeks ago it was announced that [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station, the galaxy's most famous travelling starport, would make an incredible long-distance jump from Gliese 1269 to Beagle Point. The proposed expedition received enthusiastic support from the galactic community, which contributed thousands of tonnes of fuel to the ambitious campaign. 

But despite setting off almost a week ago, no communications have been received from [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station since it departed, and explorers at Beagle Point have reported no sign of the outpost. Dr Kaii, one of the leaders of the Distant Worlds Expedition, released the following statement: 

"I have received numerous updates from pilots in the vicinity of Beagle Point reporting 'no joy' on the Jacques jump. Members of the fleet have searched nearby systems, but there is no sign of the station. A full investigation should be launched as soon as possible." 

Kinsley Larson, an engineering specialist, offered this assessment to the Federal Times: 

"I can't say I'm surprised. A leap like that would be a remarkable feat for a starship, never mind a starport. Even if [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station survived the jump, there are countless things that could have gone wrong and caused it to veer off course. It could be almost anywhere in the galaxy. Assuming it's still in one piece, that is." 

A number of Unknown Artefacts had recently been sold at [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station, and the starport was experiencing technical issues at the time it departed for Beagle Point.
