:PROPERTIES:
:ID:       ea1e73c6-2f5f-4272-a66c-ae2452025b72
:END:
#+title: Federation Goes All In
#+filetags: :Alliance:Federation:3301:galnet:

* Federation Goes All In

/10 Jun 3301/

Federation Goes All In 
 
In late 3300, the small Federal system of Dahan found itself being used as a staging area for a prolonged military campaign against the independent nation of Eranin. Eventually, Eranin managed to force back the Federal invasion. Although not before heavy losses were incurred by both sides. 

This week that region once again became a hotbed, though this time of political activity, as both Federal and Alliance campaigners turned out in force in an attempt to exert their influence over the sector. 

Mahon supporters flooded the hallways of Dahan Gateway and Whitson Hub, choosing to focus their efforts on systems whose affections for the Federation could be called into question following the events of late last year. President Hudson’s supporters went head to head with the Alliance campaigners to support the Federation’s position aboard Dahan Gateway. With many an impassioned debate taking place between the two groups along the station’s promenade.  

Mahon supporters were successful in convincing many of the system’s residents that life within the Alliance did indeed sound better than having to send a large slice of their income off to Sol for little apparent return. Although in the end, typical Alliance bureaucracy (in the form of a lack of resources) means that Mahon’s supporters will be unable to capitalise on what appeared to be a sure-fire success. 

Therefore the real winner of the week’s campaigning currently looks set to be Shadow President Winters.  

Liberal and Republican Party members have been working around the clock to recruit new supporters in the Federal system of Aulin, with the liberals managing to just about take a lead in what has historically been a republican led state. Contracts are currently being drawn up to allow Shadow President Winters to set up a new command centre aboard Aulin Enterprise, and unless the republican party does something extraordinary to stop it, Friday will see the rise of a new liberal command centre in Aulin.
