:PROPERTIES:
:ID:       3e9a206f-b6d5-4ea9-b25e-1bffdb54d9e6
:END:
#+title: Galactic News: Specialists Respond to Latest Findings
#+filetags: :3303:galnet:

* Galactic News: Specialists Respond to Latest Findings

/06 Jul 3303/

Professor Ishmael Palin, leading authority on xeno-biological research, has commented on the discovery of functional technology at the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] structures. 

“This revelation is significant not only because it gives us an insight into [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] technology, but because it confirms the long-posited connection between the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] and the Unknown Artefacts and Probes. Unfortunately, we still do not know the exact purpose of these pieces of technology. Reconnaissance, surveillance, cartography? The specifics elude us, even while fresh discoveries are made.” 

Meanwhile, Ram Tah, the engineer leading research into the lost civilisation known as the Guardians, has commented on reports of interaction between Guardian and [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] technology: 

“The fact that Guardian artefacts react to the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] device certainly seems to suggest some kind of prior contact, and although we know very little about Thargoid history, interaction between the two races is entirely possible. But the negative nature of the reaction could be a sign that the relationship was not entirely peaceful.”
