:PROPERTIES:
:ID:       25971264-c9d0-4f01-af84-cf4ac4b7ce8d
:END:
#+title: Materials Delivered for Colonia Bridge Starports
#+filetags: :3308:Federation:galnet:

* Materials Delivered for [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge Starports

/13 Jan 3308/

*Pilots’ Federation ALERT* 

The third phase of Brewer Corporation’s [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] Bridge project has proven successful, according to a recent announcement. 

Shipments of ceramic composites, computer components and thermal cooling units were transported in large numbers to [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system and Macdonald Settlement in the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] system. As a result, several new starports will be constructed along the travel corridor to Colonia. 

Brewer Corporation released this statement regarding the initiative: 

“Once again, we owe a great deal to the pilots who brought us so many vital resources. We can now proceed with constructing one starport in the vicinity of [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] and 5 starports in systems branching out from [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]]. These will increase the value of the Colonia Bridge for travellers, tourists and commercial interests alike.” 

“The starport infrastructures are scheduled to be built by the 27th of January. Initially they will provide rearm, refuel and repair services, but will lack markets and other facilities. The distances involved in ferrying equipment to these locations means that these starports will become fully operational in stages over a period of weeks.” 

“Contributors will be able to collect their rewards from [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station and Macdonald Settlement from the 14th of January. The proposed engineered frame shift drives for those eligible will follow at a later date. The dedicated pilots who provided the most deliveries in [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] and [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] will receive invitations to submit suggestions to name the new starports, subject to review.”
