:PROPERTIES:
:ID:       3480ff77-ecbb-4f80-92d8-4686d84c6223
:END:
#+title: Week in Review
#+filetags: :3304:galnet:

* Week in Review

/13 Oct 3304/

Here are this week’s major stories. 

Journalist Gethin Okonkwo has shared more details about his time with the Far God cult. In a detailed article, Okonkwo expressed relief at Far God believers returning to their hive-chapels following weeks of persecution. The journalist said he would be collaborating with exotheologian Dr Alfred Ulyanov to produce a definitive account of the sect. 

The Federal Security Service has discovered more personal administration robots containing concealed surveillance programs, prompting hundreds of businesses and individuals to destroy their personal robots. It is understood that all the affected models are made by the Achilles Corporation. 

In other news, technology company Herculean Machines has begun mass production of its new device, the Duradrive personal computer. Following the successful performance of its prototype at the Rackham Ultratech Expo, the company has received corporate funding from a range of sources, including Rackham Capital Investments. 

The two remaining candidates in the Alliance presidential race have returned to the Alioth system to make their final campaign vows. Elijah Beck said that his focus as president would be on attracting more systems to the Alliance, while current president Gibson Kincaid renewed his plea to imbue the presidential role with executive powers. 

Meanwhile, the Close Encounters Corps has announced plans to construct a scientific megaship in the BD-12 1172 system. The new vessel will allow research teams to map and explore the planets of the surrounding nebula. The Close Encounters Corps has placed an open order for various commodities to facilitate construction of the megaship. 

Finally, Broadcast Cobra has announced that its appeal for commodities has reached a successful conclusion, having received an overwhelming response from the galactic community. The commodities contributed to the campaign will be used to construct a megaship, from which the organisation will broadcast its take on current events. 

And those are the main stories this week.
