:PROPERTIES:
:ID:       d01e8a3a-1281-4013-b1ac-fdd2f5174e6e
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/a8a3650c-60ea-4089-91f1-24d5821f1907?resourceVersion=id%3A4871
:END:
#+title: Lakon Spaceways Faces Financial Collapse
#+filetags: :Federation:Alliance:galnet:

* [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] Faces Financial Collapse

/29 Dec 3306/

Economic instability has caused the value of shares in [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] to drop to unprecedented lows, placing the company’s future in doubt. 

A hostile takeover bid by Federal corporation [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] has raised concerns in the Alliance over the loss of a major defence contractor. The Independent Commission for Market Equality has also reported irregularities in the recent transfer of share ownership, which may lead to criminal investigations. 

As a result, although [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] continues to manufacture and sell ships, its lack of reserves and a loss of confidence among investors may lead to insolvency and dissolution. 

[[id:88ac1950-caa0-4043-96c0-07e33ca7c049][Trent Delaney]], the newly appointed chairperson of Lakon’s board of directors, announced: 

“Financial mismanagement and a litany of poor business decisions have led to this situation. Rest assured that once formal negotiations with our new parent company are complete, Lakon’s stock will rise to new heights.” 

According to Federal business analysts, there are indications of displeasure among [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] senior directors regarding this takeover. An anonymous source from within the corporation told Vox Galactica: 

“The Lakon merger is entirely [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]]’s project. Frankly, it’s sheer greed. Our income has soared recently with new commissions from the Navy, but Rochester’s grabbing hands are always reaching for something. He runs the departments that are loyal to him like they’re his personal kingdom.”
