:PROPERTIES:
:ID:       65ae3149-1a10-493b-b413-8962d4a063a2
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/128b959a-e903-4b63-b0ec-d14eeeaa1d8d?resourceVersion=id%3A4910
:END:
#+title: Trial of Fleet Admiral Vincent Begins
#+filetags: :3301:3307:Federation:galnet:

* Trial of Fleet [[id:478137a2-59fc-4055-ba37-021ef7035652][Admiral Vincent]] Begins

/25 Jan 3307/

The Federal High Court on Mars has opened the trial of Fleet Admiral Lucas Vincent, who is charged with conspiracy to commit murder and treason. 

Vincent stands accused of organising the sabotage of Starship One in 3301, resulting in hundreds of deaths. 

The Federal Times’s crime correspondent Ethan Takahashi reported: 

“The trial began with the prosecution counsel outlining the case. Material evidence obtained from Chief Technician Rory Webster, whose testimony led to Vincent’s arrest, was presented before the jury.” 

“Vincent was questioned about a secure transmission from his office to the presidential vessel on the 24th of May 3301, ordering an unscheduled diversion to the Azaleach system for routine maintenance. This is where Webster’s engineering team followed Vincent’s orders to install the sabotaged hyperdrive component that caused the misjump.” 

“Evading the questions, Vincent claimed that the entire trial was a ‘Liberal Party cover-up’ and that Starship One was destroyed ‘to put Winters in charge’.” 

“With the loss of President Halsey and Vice President Naylor, [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] did indeed assume the role of acting president and became leader of the Liberal Party. However, the defence counsel played down these accusations, instead declaring that Webster’s recordings of Vincent’s orders could have been falsified.”
