:PROPERTIES:
:ID:       ba5c5e21-0852-423b-9804-3da9dca2f2dd
:END:
#+title: Los Chupacabras Campaign
#+filetags: :3304:galnet:

* Los Chupacabras Campaign

/25 May 3304/

Los Chupacabras, an independent faction based in the LFT 926 system, has announced plans for a musical event known as the Jailhouse Rock and Blues Music Festival. 

A spokesperson for the group issued the following statement: 

“Our hope is that this will be the greatest music festival this side of [[id:84d9b01d-a9d6-47d9-b9f9-f6154233e585][Sagittarius A*]]*. To quote Plato: ‘Music is a moral law. It gives soul to the universe, wings to the mind, flight to the imagination, and charm and gaiety to life and to everything’.” 

In support of the event, Los Chupacabras have placed an open order for quantities of beer, tobacco, coffee and narcotics, and have promised to reward pilots who deliver these commodities to Meredith City in the LFT 926 system. 

The campaign begins on the 24th of May 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
