:PROPERTIES:
:ID:       faaad8c4-c188-48f5-a990-1a326787be56
:ROAM_REFS: https://community.elitedangerous.com/galnet/13-DEC-3307
:END:
#+title: The Death of Theta Seven
#+filetags: :galnet:
* The Death of Theta Seven

/13 Dec 3307/

The [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]]’s de facto leader and his closest followers have sacrificed
themselves by destroying the [[id:9a8a2b74-f7e3-4d1b-abfd-82b91b1d6481][Far God]] cult’s megaship [[id:4701fafb-7040-4169-bfdb-9dc977a06e5f][Sacrosanct]].

The hijacked vessel had been taken to the Mudhrid system by the
remaining members of Theta Group, aiming to reunite with the
NMLA. After this failed, [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][ACT]] forces surrounded the Sacrosanct in the
hope of rescuing the several thousand cultists being kept as hostages.

[[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] broadcast a short video message, where he uttered a single
phrase:

“The future will remember us.”

He was then seen to manually detonate a series of bombs, which
ruptured the Sacrosanct’s hull and split the vessel in two. It is
believed that the weapons also distributed Thargoid caustic enzymes
throughout the megaship, thereby killing its entire population.

ACT has released a statement from co-leader Captain Saskia Landau:

“Tragically we were unable to save the lives of the Far God
worshippers, despite several attempts to negotiate their safe conduct
off the ship. Captain Castile’s commando unit could not gain entry to
the Sacrosanct in time, and we had no success trying to hack into its
onboard computers.”

“We can confirm that the most wanted terrorist in the galaxy is
dead. But ACT’s task is not yet complete, since there is much we still
don’t know about the NMLA. Our investigation will focus on learning
more about their background, as well as targeting any surviving cells
of activists.”
