:PROPERTIES:
:ID:       e98bf6a9-5c03-40f5-8eb9-e19eb6738274
:END:
#+title: Battle of Mudhrid Ends in NMLA Defeat
#+filetags: :galnet:

* Battle of Mudhrid Ends in NMLA Defeat

/02 Dec 3307/

*Pilots’ Federation ALERT* 

The Neo-Marlinist Order of Mudhrid has been defeated by the Epsilon Fornacis Empire Group in the Mudhrid system. 

With the aid of many independent pilots, the Imperial faction outmatched the NMLA-supporting forces who were attempting to rescue their leader Theta Seven. 

Captain Saskia Landau provided an update from ACT: 

“Using the fierce fighting as cover, Captain Milo Castile led a commando unit made up of specialists from Alliance, Federal and Imperial security forces to gain access to the Steel Majesty. After freeing and arming the crewmembers that were being held hostage, they overpowered the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] troops and retook the megaship.” 

“We have successfully prevented [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] and his followers from rejoining their fellow terrorists. But the Far God cult’s vessel, the Sacrosanct, is still in the system under his control. Until the man responsible for hundreds of thousands of deaths has been captured, our victory over the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] remains incomplete.” 

The Epsilon Fornacis Empire Group stated that those who supported its campaign can now receive their rewards from Payne-Scott City starport.  

The Imperial faction also agreed that independent pilots who fought for the Neo-Marlinist Order of Mudhrid will be permitted to collect payment from the Steel Majesty, which has been transferred to their ownership.
