:PROPERTIES:
:ID:       22a10ad9-e9b5-4910-95b3-1a436763967f
:END:
#+title: Far God Survivor Revived
#+filetags: :galnet:

* [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Survivor Revived

/30 Mar 3305/

The occupant of a cryogenic pod recovered from an abandoned outpost used by the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect has been revived successfully. 

17 year old Kiona O’Connor has been confirmed as the occupant. Following medical checks and an extended debriefing by the Federal Intelligence Agency, she made this statement to Vox Galactica: 

“I’d been homeless for a long time when the monks took me in. I never understood much about the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]], really…I just needed to get off the streets. A lot of people there were like me.” 

“Somehow I ended up at the outpost, where they put us all into suspended animation. I’ve no idea what happened after that. I’m just grateful to be alive. I hope the others are too…I hope they got whatever they were praying for.” 

The FIA has contacted Kiona’s father, John O’Connor, and arranged for her to be escorted to her family home.
