:PROPERTIES:
:ID:       6fa8ebd9-9fa9-4e03-881a-84b81c5ead2c
:END:
#+title: Sirius Corp.Makes Public Offer
#+filetags: :Guardian:3304:galnet:

* [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corp Makes Public Offer

/26 Oct 3304/

The [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] has publicly offered to work with engineer [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] in the development of further Guardian-human technology. 

Li Yong-Rui, the corporation’s chief executive officer, made this statement: 

“Ram Tah’s research into the Guardians is of central importance to humanity’s future, and I would therefore like to place the resources of the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] at his disposal.” 

“As the recent incident at Phoenix Base illustrates, [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]]’s operation is currently at risk. Not only can we guarantee his safety, but with our manufacturing capabilities we can bring the benefits of Guardian technology to the whole galaxy.” 

There has been a range of reactions from business analysts. Some have advised [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] to take advantage of the offer to mass-produce his designs, while others have warned that [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corp is seeking a monopoly over Guardian-human technology. 

As yet there has been no response from [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]]. Repairs to his base in the Meene system have been completed, following an attempted incursion by armed intruders.
