:PROPERTIES:
:ID:       e90d7888-bd4a-4efa-8a3a-5777821c0e2e
:END:
#+title: When Worlds Collide
#+filetags: :Federation:3301:galnet:

* When Worlds Collide

/10 Apr 3301/

Reports are coming in from all over the Federation of a resurgence in nightclubs catering to under-40s. Analysts are at a loss to explain why so many Federal youths have suddenly decided to abandon their artificial realities in favour of physical content, but the numbers don't lie. 

Over 30% of under-40s who responded to a recent GalNet poll said that they'd visited a physical nightclub in the last month, compared to just 12% during the same period last year. 

The shift has already seen billions of credits being poured into local Federal economies. This is causing a series of economic booms that are allowing some previously stagnant systems to begin a period of expansion, the likes of which they haven't experienced in years. 

It isn't all good news, though. Several dozen regions have reported an increase in violent crimes linked with various youth gatherings. So far most instances of violence have been self-contained, but political pundits are concerned about more widespread implications should the number of gatherings continue to grow.
