:PROPERTIES:
:ID:       5c3a627f-7028-41be-9524-71f9b540b4f9
:END:
#+title: Galactic News: Jaques Station Making a Comeback
#+filetags: :3302:galnet:

* Galactic News: Jaques Station Making a Comeback

/04 Aug 3302/

It has been two weeks since Jaques, the owner and operator of Jaques Station, issued an appeal for commodities to repair his beleaguered starport. Since then, scores of pilots from across the galaxy have made the long journey to the Eol Prou RS-T d3-94 system to deliver tantalum, power generators and other materials to Jaques. 

Although the campaign is scheduled to run for two more weeks, Jaques has confirmed that the materials received so far have allowed starport personnel to restore some of the station's facilities. 

"The moment supplies started arriving our teams were hard at work, making repairs and restoring facilities. So I'm very pleased to announce that we can now offer our guests refuelling, restocking, repair and outfitting services, as well as the option to purchase limpets and mining equipment from our commodities market." 

"But we're not out of the woods yet! We still need more material if we're going to give the old girl a clean bill of health."
