:PROPERTIES:
:ID:       386aa02f-3b1d-470f-ace1-f698647fbe89
:END:
#+title: Meet the Powers – Felicia Winters
#+filetags: :galnet:

* Meet the Powers – Felicia Winters

/29 Jul 3301/

Meet the Powers – Felicia Winters 
 
Continuing this GalNet exclusive series, political commentator Marcus Macmillan writes his opinion of some of the movers and shakers in 3301. In this fourth article he considers Shadow President Felicia Winters and her sudden rise to power. 

With the disappearance of President Halsey and the earlier the murder of President Nigel Smeaton, Felicia Winters found herself thrust in charge of the Liberal Party. She inherited a political party in crisis and has had to work quickly to try and restore people’s faith in her party. 

As someone born and raised on Taylor Colony, Felicia Winters learned early on that when presented with difficult choices, humanity can’t always be trusted to do the right thing. She sees it as her duty to push for the right choice, even if it's the hard choice. 

Felicia Winters has already proved to be a versatile opponent, and in many opinion polls is running level with President Hudson. Many voters are growing concerned by the President’s aggressive rhetoric and are turning to the Liberal Party to counter what they see as a road to war.
