:PROPERTIES:
:ID:       824f1a59-8773-4391-8e76-b0614892c963
:END:
#+title: Details of Aisling Duval’s Wedding Announced
#+filetags: :galnet:

* Details of Aisling Duval’s Wedding Announced

/14 Jul 3304/

The wedding of Princess Aisling Duval and Federal Ambassador Jordan Rochester is now in the advanced planning stages, and a date has been confirmed for the ceremony. 

An official proclamation was printed in both The Federal Times and The Imperial Herald: 

“Her Imperial Highness Princess Aisling Duval and the honourable Ambassador Jordan Rochester are pleased to announce the occasion of their wedding on Saturday 25th August 3304 at the Imperial Palace on Emerald in the Cemiess system.” 

“Invitations have been extended to representatives of every strata of society. An honour guard of vessels from both the Federal Navy and the Imperial Navy will be in attendance. The couple’s wish is for all citizens of the galaxy to join together in celebration of their union.” 

There has been criticism of Princess Duval’s choice of husband, with some Imperial citizens voicing dismay at the forthcoming nuptials. Senator Zemina Torval continued to publicly air her disapproval: 

“This is nothing but a PR exercise, designed purely for political and financial gain. The princess should not be undermining the Empire’s policies for her own personal benefit.” 

But there is equal support for what many consider a genuine romance. Former Federal President Jasmina Halsey, now acting as an advisor to the Alliance, stated: 

“I am very enthusiastic about the opportunities for peace that this marriage will bring. This relationship symbolises a new era of amity that will benefit all of humanity.”
