:PROPERTIES:
:ID:       0ee78115-417b-431f-9f66-91a6787cef24
:END:
#+title: Technical Trouble in the Warkushanui System
#+filetags: :galnet:

* Technical Trouble in the Warkushanui System

/16 Oct 3301/

Reports coming in from the Warkushanui system indicate that a number of starports in the region are currently experiencing technical issues. According to Sam Norris, a technician at Coats Hub, the system's inhabitants are dealing with a range of problems: 

"We've had power outages, intermittent problems with our communications, and issues with the docking systems, but I've reason to believe that things are worse at Gurragchaa Gateway. I haven't been able to establish a stable comms link with them for a while, though, so I don't know exactly what the situation is." 

Norris was asked what he thought might be causing the problems: 

"Beats the hell out of me. The generators are fine and I haven't identified any infrastructure issues, so we'll need to run some tests before we can be sure." 

The issues in Warkushanui are not believed to be affecting station services at this time.
