:PROPERTIES:
:ID:       29a37c40-cdc6-41ec-ac97-baade1caeec8
:END:
#+title: Freelance Report: Keeping an Eye on Naval Expansion
#+filetags: :3302:galnet:

* Freelance Report: Keeping an Eye on Naval Expansion

/29 Apr 3302/

On the popular independent talk show 'Affairs of State', political commentator Walter Astoria defended the recent construction of a new Alliance outpost while expressing concern about Federal and Imperial naval expansion. 

"Who cares if the new Alliance outpost is a listening post? [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][The Federation]] and Empire are building capital ships, and they feel threatened by an outpost? Give me a break!" 

"Federal shipyards have been running at maximum capacity since President Hudson's inauguration. Since then, the Federation's only noteworthy naval action was in Kausalya against Emperor's Dawn." 

"It may be less troubling to see [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] replenishing its forces, given its prolonged campaign against Emperor's Dawn, but a new battle group built around a new Majestic is clearly an attempt to maintain the status quo." 

"Review your history – there aren't many examples of arms races cultivating peace and mutual understanding. This doesn't bode well." 

Commander Corrigendum
