:PROPERTIES:
:ID:       efbb5d35-3c38-490a-aad5-04740becf043
:END:
#+title: Criminal Forces Crushed in Gliese 868
#+filetags: :3308:Federation:galnet:

* Criminal Forces Crushed in Gliese 868

/25 Mar 3308/

*Pilots’ Federation ALERT* 

Commanders have worked alongside Federal authorities to destroy criminal ships in the Gliese 868 system. 

The pirate gang was responsible for multiple raids while Federal security services were distracted by public protests around the Hudson Contravention. To help protect shipping and eliminate the threat, bounties were placed on all criminal vessels. 

Gliese 868 Services, which organised the counter-offensive against the pirates, announced: 

“The combat expertise of Federal Navy auxiliaries and independent pilots has succeeded in driving back these ruthless criminals. We will be pleased to reimburse bounty vouchers at Bacon Port in Gliese 868.” 

The Federal Times reported on the political repercussions from these events: 

“It is not just the security agencies that are embarrassed at relying on volunteers to protect trade in Gliese 868. Members of both the Republican and Liberal Parties have spoken out, claiming that this situation was completely unacceptable.” 

“This has led to fresh demands that President Hudson’s proposal to repeal the 77th amendment must be negotiated peacefully, without causing civil disturbance or placing citizens’ lives at risk. Congress is expected to make further statements soon.”
