:PROPERTIES:
:ID:       5f678790-30c2-4e61-9b0d-36d41d983199
:END:
#+title: Quivira Feels the Wrath of Patreus
#+filetags: :Empire:3301:galnet:

* Quivira Feels the Wrath of Patreus

/01 May 3301/

Deep in the heart of the Empire, a handful of nations stand defiantly independent from their neighbours. 

One such nation is Quivira. Home to 37.5 million residents, Quivira has managed to maintain its independence by acting as a major supplier of industrial goods to its neighbours.  

Early last year Quivira suffered from a period of deep recession, during which time it took out a series of bridge loans with Silver Universal Plc . A recent increase in rates left the People’s Quivira for Equality Party unable to pay off their debts, a fact which has caused the system to become the victim of legal action carried out on behalf of Senator Patreus. 

Quivira Electronics Plc, an Imperial corporation, has now been authorised to actively reclaim the debt owed to Senator Patreus by the system’s current leadership. As a first step towards that goal, Quivira Electronics Plc has taken ownership of Stepledon Dock. With the Senator’s blessing, Quivira Electronics is now hiring freelance reclamation agents to help extract the remaining debt. 

In response, the People’s Quivira for Equality Party have set up a defence fund with the [[id:e9439fe0-8637-4330-b5fd-b4f1643cf472][Bank of Zaonce]], the contents of which will be paid out to any independent pilots who come to Quivira’s aid in its time of need. The defence of Quivira is being organised aboard Godel Dock.
