:PROPERTIES:
:ID:       e889c410-ec1e-4685-9a5c-a68a909c6bed
:END:
#+title: Freelance Report: We Should Have Listened to Dr Lorax
#+filetags: :Federation:3302:galnet:

* Freelance Report: We Should Have Listened to Dr Lorax

/02 Sep 3302/

Six months have elapsed since Doctor Elana Lorax warned against the exploitation of the non-human structures commonly called barnacles. In her plea, she noted that aggressive harvesting could jeopardise efforts to produce a viable synthetic alternative to meta-alloys.  

Despite President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]]'s claim that the purpose of the Federal deputation in the Merope system is to protect the non-human structures, independent pilots report that the system's barnacles have been entirely depleted. 

Commander Vindicator Jones shared his observations: 

"Just went to Merope 5c to check out the barnacles. They've been destroyed. I've tried visiting several, but they're all barren." 

It is not known why the Federation has acted inversely to its stated objectives, particularly given President Hudson's acknowledgement that the barnacles may possess some form of sentience. 

Doctor Lorax could not be reached for comment, but it is becoming increasingly clear that we should have heeded her warnings. 

Commander Corrigendum
