:PROPERTIES:
:ID:       90b15e58-d920-4228-b690-733b81ea036f
:END:
#+title: Onionhead Sales Still Growing
#+filetags: :Federation:3301:galnet:

* Onionhead Sales Still Growing

/02 Apr 3301/

The Federal ban may have been enough to scare the Tanmark Defence Force into purging Lucan Onionhead plantations from their world, but Panem continues to stand defiant. 

It’s been only two weeks since the original Onionhead went back on sale in Harvestport, and already the supply has started flowing as far away as Berrivi and Aapelinja. 

So far the Federation has done little to stop the resurgence of Onionhead. Political pundits have been quick to suggest that this lethargy is most likely due to the fact that the President is paralysed by her (low) polling numbers. With her numbers so low, any mistake could cost the President her presidency.  

President Halsey’s indecision will come as good news for Georgio Algeria and the Kappa Fornacis Famers Union, who will doubtless continue growing credits as quickly as they can in preparation for any potential blowback from the Federation.
