:PROPERTIES:
:ID:       67e21237-3483-4c77-9726-e7dd45a6e24b
:END:
#+title: Kumo Crew Starports Open for Business
#+filetags: :3307:Federation:galnet:

* Kumo Crew Starports Open for Business

/30 Apr 3307/

*Pilots Federation ALERT* 

Five new starports constructed by [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]’s recent campaign have now become fully operational. 

The Orbis stations, which are run by the [[id:2dc1b92f-4bdc-4504-ad5f-a9c5794155dc][Kumo Council]] faction, are listed below: 

[[id:82a0f345-bc03-4564-897c-b00bcda5b74e][Kumo City]] in the [[id:93f55330-0ae5-42d5-bee2-368453bcd9e1][Pegasi Sector PN-T c3-14]] system (Harma region) 

[[id:9c28cea7-e9c6-41cd-901d-7a071dc5b406][California Freeport]] in the [[id:e8341944-ebda-4a16-9ad2-0b6e9405d8b7][HIP 18390]] system ([[id:6fee136e-381f-47a2-ba13-6d74c8798803][California Nebula]])  

Crimson Exchange in the HIP 10792 system (Sothis region)  

[[id:82800f08-27d3-48c8-a984-c8a2ff882cbb][Fort Xeno]] in the [[id:80076c05-2ff7-4655-aa14-02ccfcfb11c9][HIP 62154]] system ([[id:6f086af9-53a6-4d37-9800-b81d2537837c][Coalsack Nebula]])  

Delaine Terminus in the Eol Prou PC-K c9-91 system (Colonia region)  

The starports will provide a full range of services, although their low populations bring concerns that they may be under-staffed. Additionally, security agencies in nearby systems expressed fears that since they are operated by the Kumo Crew syndicate, they are likely to harbour black markets and promote illegal activity.  

Arch-Corsair [[id:a002575a-7b72-4d9b-8c76-e748073a8e3e][Kay Volantyne]], a senior member of the Kumo Council, addressed this when she told The [[id:dc25c5b7-381e-4e8a-8599-68be61b19bae][Pegasi Sentinel]]: 

“These starports exist solely to encourage trade, which is the lifeblood of our galaxy. Sometimes a little lifeblood can get spilled here and there, so I’m sure our new neighbours will welcome our protection, yes?” 

Other factions have appeared in the five systems, including subsidiaries of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]. Several newsfeeds have speculated about an ambiguous connection between the syndicate and the megacorp, whose financial support might explain how the Kumo Crew managed to extend so far beyond its territory.
