:PROPERTIES:
:ID:       d8b1fd78-32ea-476c-a8d3-389b9fdfaf6d
:END:
#+title: Galactic News: Orulas Campaign Reaches an End
#+filetags: :galnet:

* Galactic News: Orulas Campaign Reaches an End

/03 Mar 3302/

Rose Trebek, leader of the Joint Security Taskforce, has announced that the operation to clean up the Orulas system has been an overwhelming success. According to Trebek, hundreds of combat pilots supported the initiative to disrupt the operations of the criminal Blue Hand Gang. 

Trebek released a statement to the media in the wake of the campaign's success: 

"We had two primary objectives: to clear the spaceways of Orulas, and to liberate the escape pods the criminals were transporting through the system. Thanks to the many brave combat pilots who supported the initiative, both objectives were successfully completed. The recovered escape pods have been delivered to Wilkes Orbital, and the occupants will now be returned to their families." 

Asked about the system's future, Trebek was characteristically pragmatic: 

"The pilots who contributed to this initiative have done an outstanding job, but the Blue Hand Gang hasn't been completely destroyed. We've won the battle, but the war is far from over."
