:PROPERTIES:
:ID:       0585ac87-dc5a-4c6e-8130-2e3e83de8bf4
:END:
#+title: Alliance and Marlinists Address Refugee Crisis
#+filetags: :galnet:

* Alliance and Marlinists Address Refugee Crisis

/26 Oct 3307/

The Marlinist Colonies have offered to provide help for political refugees who sought sanctuary in Alliance space. 

In 3306, the Empire’s security forces began arresting followers of Marlinism, suspecting them of being linked to the NMLA. Many pro-republican Imperial citizens fled to the Federation, but some set course for [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] instead. 

The situation has been highlighted by Prime Consul Kayode Tau of the Marlinist Consulate: 

“Having made a desperate journey for survival, over a million Marlinists are now dispersed across Alliance territory. Most are clustered in small groups, lacking basic supplies and facing extreme deprivation. Some Alliance systems have offered citizenship, but others are attempting to expel them as illegal immigrants.” 

“The Empire wishes to repatriate these people, which means harsh interrogation for some and lifelong persecution for others. I hope to negotiate with [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] to arrange an alternative – transportation to the Marlinist Colonies. There they will be welcomed into the democratic society established by their brethren.” 

Ambassador Elijah Beck, head of [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Office of Diplomatic Relations, has agreed to meet with Prime Consul Tau to examine solutions. The Imperial Diplomatic Corps officially refused an invitation to join this discussion.
