:PROPERTIES:
:ID:       5fe28359-60ae-4113-b544-e0c0198dde3d
:END:
#+title: Yuri Grom Targeted by Federal Strike
#+filetags: :3307:Federation:galnet:

* [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] Targeted by Federal Strike

/30 Sep 3307/

*Pilots Federation ALERT* 

The Delta Pavonis political conference has erupted into conflict between EG Union and Delta Pavonis Galactic Interstellar. 

Yuri Grom, the ruler of EG Union, broadcast this message: 

“This conference was nothing more than a trap! My delegation was apprehended at gunpoint by a squad of undercover Federal agents. Sacrifices made by my loyal guards enabled us to escape from Kessler City, only to find our ships under attack. The Federation has declared war – I will respond in kind!” 

President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] gave an official statement: 

“Yuri Grom is a traitor and a dangerous threat to Federal security. We cannot ignore any opportunity to eliminate this ruthless tyrant.” 

Delta Pavonis Galactic Interstellar has asked for Federal auxiliaries to provide combat support to its forces. In return, the EG Union called for help from “allies of [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] and enemies of the Federation”. 

Grand Duke Simion Petrescu, the host of the political conference, has rejected claims that his faction was secretly working with the Federation to entrap [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]]. The Federal Diplomatic Corps has not yet commented on its role in these events.
