:PROPERTIES:
:ID:       b91d269b-3712-4403-bb92-9c1775f86644
:END:
#+title: Imperator Mordanticus Captured
#+filetags: :Empire:galnet:

* Imperator Mordanticus Captured

/18 Jan 3305/

Imperator Mordanticus, the leader of isolationist group Nova Imperium, has been captured by the Empire. His arrest was made during the conflict between Nova Imperium and the Empire in the Paresa system. 

Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]] made a pronouncement on behalf of Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]]: 

“With its fleet destroyed, Nova Imperium’s seditious agenda has been halted. The so-called Imperator, [[id:f6be5b58-fd8d-4233-8053-7ade4ca35aee][Duke Kaeso Mordanticus]], will be brought before the Senate on Friday the 25th of January to answer charges of treason against the Empire.” 

Political journalist [[id:745efc38-c548-40c0-81d2-82973c604d37][Cassia Carvalho]] commented in The Imperial Herald: 

“For the emperor to assemble the entire Senate is a rare occurrence. It seems likely that she will make an example of Mordanticus, perhaps with a public trial.” 

“Although Nova Imperium survives in the Paresa system, the loss of both its fleet and military commander may have delivered a mortal blow to the isolationist cause.”
