:PROPERTIES:
:ID:       8af6e642-0638-4822-9903-bb688e9fa641
:END:
#+title: Remlok
#+filetags: :3300:Empire:Corporation:
* Remlok

#+begin_quote

  "Above all, survive."

  --- Source
#+end_quote

Remlok is the galaxy's largest manufacturer of space suits. Led by CEO
Sebastien Croix, it is noted for its employee-centric ethos, which
offers workers generous benefits and competitive wages.

Perhaps unsurprisingly given the company's commitment to fair treatment,
it is vocally opposed to slavery. Croix, as the descendant of an
enslaved family, has repeatedly clashed with pro-slavery figureheads,
including Imperial Senator Zemina Torval.

In, 3300, Croix lambasted Torval for using excessive force to suppress a
slave rebellion in the Sorbago system. Describing her actions as a
"cruel response to people seizing their rightful freedom," Croix came
under fire from Torval's allies, with some threatening to boycott the
company until an apology was issued. Remlok's public relations
department issued a response, admitting that Croix's statement was
"intense", while maintaining the company's fundamental position.

More recently, the company has partnered with abolition charity Unchain,
pledging a portion of its profits to the organisation's cause.
Predictably, the move has attracted a certain amount of criticism, but
has done little to undermine Remlok's market position.


