:PROPERTIES:
:ID:       b69f0105-e6fc-49e9-99da-97d732e3941d
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/45327fdd-503d-4701-802f-9e29dbd96fa2?resourceVersion=id%3A4891
:END:
#+title: Xenological Samples Delivered to Colonia
#+filetags: :galnet:

* Xenological Samples Delivered to Colonia

/14 Jan 3307/

*Pilots Federation ALERT* 

The Holloway Bioscience Institute has rewarded pilots who delivered living matter extracted from space-dwelling organisms. 

Many shipments of seed pod tissue samples arrived at Jaques Station, from where they will be transported to the Holloway Biology Centre on Colonia 7 G. These will be used to replenish stocks used in the facility’s experimentation programme. 

Dr Roy Casimir, chief researcher at the centre, expressed his gratitude: 

“These vital supplies mean that we can resume our studies on the incredible organisms that float through the void. Here at Holloway we’re making many breakthroughs in the field of xenobiology, some with intriguing commercial possibilities.” 

The Holloway Bioscience Institute now plans to establish experimental habitats for vacuum lifeforms in the following systems: 

Eol Prou PC-K c9-221 

Eol Prou LW-L c8-99    

Eol Prou KW-L c8-301  

Eol Prou PC-K c9-154  

Pilots who contributed to this initiative can now collect their rewards from Jacques Station in the Colonia system.
