:PROPERTIES:
:ID:       fb3b7e8e-1786-4f13-8535-f6f305f2fae8
:END:
#+title: Week in Review 08 Dec 3304
#+filetags: :Federation:Alliance:3304:galnet:

* Week in Review

/08 Dec 3304/

Here are this week’s major stories. 

Two corporations have merged to form one of the largest pharmaceutical companies in the galaxy. Allied Medical Industries has united with Neosalve Inc. to create Neomedical Industries, which will sell drugs, equipment and services to both Alliance and independent systems. 

Independent company Vitadyne Labs has developed new pharmaceuticals that use nanoscale materials to repair cell damage on a molecular level. The company claims the nanomeds can heal injury in a fraction of the normal time, and even slow the ageing process. The Interstellar Health Organisation is reviewing the new medicines. 

Nova Imperium has revealed its choice for Emperor – an eighteen year old man named Hadrian Augustus Duval. The group claims that Duval is the grandson of former emperor Hengist Duval, and that he has a legitimate claim to the Imperial throne. The group’s leader, Imperator Mordanticus, has called for Hadrian to replace Arissa Lavigny-Duval. 

Journalist [[id:b9531f53-8bad-4eda-a0aa-46c72bb6ec9a][Gethin Okonkwo]] has commented on the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] outposts found in the Etain system, saying that the logs recovered from the outposts illustrated how the faith attracted people from varied backgrounds. Okonkwo also said that the book he is writing with Dr [[id:2bf69df4-bf62-4877-87eb-5158254f5fcb][Alfred Ulyanov]] would reveal much about the Far God religion. 

An obscure cult based in the Zlota system has requested a range of rare items for an arcane ceremony. A handwritten statement from Barnabas Cole, leader of a group named the Children of Tothos, elaborated on the nature of the ceremony. Zlota Federal Holdings, which is thought to have some connection to the cult, is overseeing the initiative. 

Finally, a goodwill initiative from the Achilles Corporation has concluded. Chairman Gus Weaver of Achilles confirmed that the company had acquired enough commodities to manufacture replacements for the robots destroyed in the wake of the spy robot scandal. He also reminded consumers that the surveillance program at the heart of the scandal was safely deleted by the company’s latest coreware update. 

And those are the main stories this week.
