:PROPERTIES:
:ID:       8314bf68-0d4e-4aa8-b31c-c1b4a7ef5313
:END:
#+title: Aisling Supporters Pledge to Legion
#+filetags: :galnet:

* Aisling Supporters Pledge to Legion

/06 Jul 3301/

Aisling Supporters Pledge to Legion 
 
Independent Commanders in support of the People's Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] have come together in recent weeks under Commander Andariel in the 'Thirteenth Legion'. One Commander reported: 

'I was tired of being interdicted every time I tried to run a crate of medicinal supplies in support of the Angels. I sold my cargo bays, fitted shield banks and upgraded my weapon system. Commander Andariel told me where to fight and how.' 

At least some Imperial nobility is supporting the pledge of Commander Andariel and others like him. Count Jeffrey Alexander Ryan of Ugain added, 'So many people want to support, few realise how to do it. Some want to trade, others run cargo specifically for my Princess. Some know how to fight, but until the Thirteenth was formed, few knew how to do it making each laser pulse count'. 

The Thirteenth Legion has built its base on Chona.
