:PROPERTIES:
:ID:       743ccfdf-ac28-4297-b985-6bc653597a88
:END:
#+title: Prism Senator Returns to Empire
#+filetags: :3301:galnet:

* Prism Senator Returns to Empire

/02 Apr 3301/

After completing her tour of the Sol system and meeting several high ranking officials within the Federation, Senator Kahina Tijani Loren has returned to the Empire. 

As expected a large flotilla of vessels accompanied Lady Kahina to the boundary of Federation influence, where she rendezvoused with the Imperial Interdictor Lucius. 

The Sol Herald asked Lady Kahina what she had thought of her first trip to Sol. She was reported as saying that she had found it “Most enlightening” and wanted to express her thanks to all who had helped her “navigate the fiendishly complicated Federation protocols.” 

Lady Kahina was then asked “Do you consider the docking officials at Mars High to be friends or rivals?” 

Her reply was greeted with laughter over wide-band comms. “Oh, that’s easy. Neither.” 

Representatives from Mars High could not be reached for comment.
