:PROPERTIES:
:ID:       54717576-241e-4d4e-9359-2420ffba77cb
:END:
#+title: Galactic News: Halsey Stages Anti-War Protest
#+filetags: :3303:galnet:

* Galactic News: Halsey Stages Anti-War Protest

/21 May 3303/

Former Federal president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] held a public demonstration in the Alioth system yesterday in protest of the ongoing conflict between the Empire and the Federation. 

More than 30,000 people attended the event, which lasted for several hours and occupied one of the main public plazas in Nerah City on Argent’s Claim. 

A number of high-profile speakers and activists addressed the crowd, although Alliance Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] was notable by his absence. Political commentators were quick to point out, however, that the demonstration could not have taken place without his foreknowledge, if not his explicit approval. 

In an address to the crowd, Halsey said: 

“As a 20th Century historian once wrote, ‘The underlying reason for war is always economic.’ This conflict has nothing to do with freedom or liberation – it is about resources. And I believe enough people have died to line the pockets of already wealthy individuals in the Federation and the Empire.” 

“I speak now directly to President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] and Emperor Arissa Lavigny-Duval: It is not too late for you to listen to reason.” 

Neither the Empire nor the Federation elected to respond to Halsey’s statement.
