:PROPERTIES:
:ID:       91b601ba-818c-443f-9171-f5d78f510350
:END:
#+title: Sirius Corp.ration Takes Aim at Pirates
#+filetags: :3301:galnet:

* [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] Takes Aim at Pirates

/22 Oct 3301/

Reports are coming in of pirate activity in the Robigo system, a seldom-visited region of space that was recently brought under the control of the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]. Fortunately for the people of Robigo Mines, the system's only outpost, the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp.]]ration has a history of taking a zero-tolerance approach to those who threaten its holdings. In fact, the company has already issued bounties on the pirates, offering generous rewards to anyone who helps clear them from the area. In a statement, [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]], the CEO of the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp]], said: 

"The [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] has a legal right to protect its assets, and a moral obligation to defend its people. The outpost of Robigo Mines is [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp.]]ration property, and we will not allow it to come to harm. To this end, I have set aside a substantial fund to reward pilots who help to eliminate the pirates operating in the Robigo system."
