:PROPERTIES:
:ID:       ee94527e-d41c-477c-8d84-6a1627f55657
:END:
#+title: Senator Patreus Calls for Senate Investigation
#+filetags: :3301:Empire:galnet:

* Senator Patreus Calls for Senate Investigation

/20 Sep 3301/

Senator Patreus Calls for Senate Investigation 
 
As Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] prepared to enter the Senate to continue the deliberations over the succession, he issued an angry demand for a full senate investigation into the reported links between Emperor’s Dawn and Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]’s office. 

“While I sympathise with the princesses’ situation, having experienced a similar shock, I cannot allow that sympathy to influence my judgement. When a member of my household committed the most heinous of deeds, I submitted myself to the security services and gave them every access they needed. 

 “We cannot wait to act, and I call upon the senate to commence an immediate and full investigation into any links between Princess Aisling and Emperor’s Dawn.” 

After the initial flurry of information from the Imperial Herald, no new facts were released today. Patron Damon Clarke remains at large, and the considered opinion is that he has fled the Empire.
