:PROPERTIES:
:ID:       1651c12d-062c-4dc5-8db5-e18fc42b95b1
:END:
#+title: Latest Powerplay Column
#+filetags: :3301:Empire:Federation:galnet:

* Latest Powerplay Column

/09 Jul 3301/

Latest Powerplay Column 
 
Another week has passed, and the great and powerful of the galaxy continue to vie for power and influence.  Who has prospered? Who has struggled? Read on to find out. 

[[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] continued to expand at a rapid pace despite the fact that having her forces stretched thin and has lost the systems of Nunus and Varka. With little actual enemy activity, it's this over-expansion that spells trouble for the Senator’s future plans. 

[[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] continues to see huge levels of Commander support, and very little hostile action within her space. She continues to expand her influence at a staggering rate. However, in a first such failure to date, her supporters' attempt to expand into Sounti has been countered by Federal pilots. 

Zachary Hudson continues to see extremely heavy enemy activity in the systems under his control, although countered by strong fortification. Hudson has attempted to secure four more systems this week, located within his current territory or in uncontested space. 

Felicia Winters again had her pledged supporters successfully secure her sphere of influence in the despite massive incursions by hostile fleets. On the expansion front, Winters' results are more mixed, with Lambla and Carnoeck secured, but attempts to expand towards Imperial space firmly countered. 

Zemina Torval continues to see a lot of enemy opposition to her expansion, particularly in the areas bordering Federation space. As a result, three of her expansion attempts have failed. However, [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]]'s influence has spread to several other systems, and her borders are well-fortified. 

Denton Patreus is no longer in as dire straits as he was two cycles ago, having managed to secure and fortify most of his claimed space. His space continues to see significant hostile action, mainly in border systems. As a result, several of his expansion attempts have failed, although the Senator has managed to secure four new systems. 

[[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] continued to shore up and expand his power base this cycle. While Mahon has seen extremely high levels of hostile activity in the strategically placed Bonitou, outside forces have not managed to compromise the security of his systems or stop his ambitious expansion attempts. 

Li Yong-Rui of Sirius Gov is building a power-base in an area of inhabited space just as fine or better than [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]]'s. While Akkadia and 39 Tauri, bordering the Federation, have seen high levels of hostile activity, overall this corporation continues to push its borders with little trouble. 

Archon Delaine, the leader of the Kumo Crew has been subject to an Imperial counter-offensive this cycle. While the attempts to undermine his systems have been resisted, the pirate conglomerate's growth has been stopped this week. An aggressive expansion attempt into Cuchua, in Patreus space, and another into Matlehi have both been firmly countered. 

Pranav Antal and his Utopia continue to have relatively modest political influence, slowly expanding in face of only minor enemy action and steadily shoring up the organisation's current borders. The exception is the Federation system of Ewah, where focused enemy response stopped the Utopian forces. 

CMDR Cadoc
