:PROPERTIES:
:ID:       ef68d168-54be-4268-9dcf-b2881c52ab92
:END:
#+title: Alliance Divided over Anti-Xeno Pact
#+filetags: :Thargoid:Alliance:galnet:

* Alliance Divided over Anti-Xeno Pact

/13 Jun 3308/

The proposed strategic defence partnership with Sirius Corporation is being hotly debated within the Alliance Assembly. 

Vanya Driscoll, political journalist with The Alliance Tribune, reported on the situation: 

“Sirius Corporation’s offer to provide support against the Thargoids has caused considerable disruption this year. There was a conflict and push for independence in the Reorte system, with a Sirius Navy representative joining the Council of Admirals.”  

“A three-month trial period ended with some achievements, including an increased military presence in the Coalsack and Witch Head colonies and logistical support of the recent Alliance Defence Force deployment to Didio. But it seems not enough was done to sway the majority of opponents.” 

“Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] is gambling that he has earned enough political capital to have the strategic defence pact ratified. Many government figures welcome the prospect of increased military strength. Mahon’s suggestion that this might result in an expanded Alliance was especially compelling.” 

“Councillor Nakato Kaine is taking the opposite view, successfully tapping into widespread concerns over Sirius Corporation’s motives. She argues that the megacorp has not proven capable of defending Allied systems against Thargoid attack, despite the terms of the trial period preventing Sirius from deploying its fleet to active Allied engagements.”  

“Council members are flocking to support either Mahon or Kaine, although dozens remain undecided. It’s clear that both sides will soon strive to sway public opinion, in order to influence the Assembly’s deciding vote at the end of this month.”
