:PROPERTIES:
:ID:       d3e0debf-76f4-48cb-82f4-97877188112c
:END:
#+title: Initiative to Counter Poor Harvests
#+filetags: :galnet:

* Initiative to Counter Poor Harvests

/10 Oct 3305/

Two coordinated trade initiatives have been launched, spearheading efforts to mitigate the impact of low crop yields in key systems. 

The initiatives have been organised by Crimson State Limited in the Diso system and Orerve Universal Limited in the Orerve system. The significant loss of crops in these agricultural centres is a primary cause for the low availability of staple foodstuffs. 

The initiatives received praise from Dr Genevieve Kane of the Interstellar Association for Agriculture: 

“This campaign is a step in the right direction, and with the help of the galactic community should stop the situation from becoming a full-scale crisis.” 

“The IAA is currently investigating the reasons for such poor harvests, and it seems that a new form of blight may be responsible for the rapid degeneration of crops. Scientific teams are analysing samples of diseased tissue, and we expect to know more soon.” 

Traders are asked to deliver pesticides, synthetic reagents and grain to Shifnalport in the Diso system and Watson Station in the Orerve system. 

The initiative is scheduled to run from the 10th to the 16th of October 3305. If the final targets are met earlier than planned, the campaign will end immediately.
