:PROPERTIES:
:ID:       c2592c91-b20a-42f0-b6bd-387fe189104a
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/248e19d3-8339-49af-9bf0-451884559bf5?resourceVersion=id%3A4867
:END:
#+title: Investors Take Control of Lakon Spaceways
#+filetags: :Federation:galnet:

* Investors Take Control of [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]]

/22 Dec 3306/

A coalition of [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] shareholders has voted to replace several members of the company’s board of directors with new management. 

At an emergency general meeting, investors put forward a resolution to remove selected directors, in accordance with Lakon’s articles of association. The majority vote was in favour of this resolution. 

New appointees to the board have already stated that the rejected bid by Federal shipbuilder [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] will be reappraised. [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]], the corporation’s CEO, has welcomed the opportunity for fresh discussions. 

Chairperson [[id:321b3694-38ea-481e-9899-77b5cb951f14][Naomi Landseer]], who is one of the directors being replaced, told Vox Galactica: 

“It’s no coincidence that the board members being voted out are the same ones who were against [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] owning the company. I am convinced that Rochester’s people are bribing or threatening our shareholders to make sure this hostile takeover goes through.” 

Lakon Spaceways is currently offering a 30% discount on sales of Asp Scouts, Diamondback Scouts, Keelbacks, Type-7 Transporters and Type-10 Defenders. 

Core Dynamics has applied a 30% markdown to sales of the Eagle MkII and the Vulture, with a 20% discount for Federal Assault Ships, Federal Dropships and Federal Gunships.
