:PROPERTIES:
:ID:       544fc98e-73a7-48c7-8739-8fea376bf232
:END:
#+title: Year’s End Festivities in Reorte
#+filetags: :Alliance:Thargoid:galnet:

* Year’s End Festivities in [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]

/12 Dec 3305/

The [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] system has been selected for the Alliance’s end-of-year festivities, prompting huge demand for commodities. 

Traders, performance artists and chefs throughout Allied space have already flocked to the system, where billions of attendees are expected. The planet Home is planning a synchronous firework display spanning every continent, while the habitation decks of Davies High will offer a culinary celebration featuring dishes from across the galaxy. 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] was the guest of honour at the commencement ceremony, and he offered these words to the gathered press: 

“As the year draws to a close we have a lot to be thankful for. There is peace between the superpowers. Thargoid encroachments on human space have ceased. Through hard work and cooperation, we have proven ourselves capable of rising together in response to significant challenges. This is something each and every one of us can be proud of.” 

“And so, the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] system will host a celebration to tell future generations about. We call upon the galactic community to ensure the system is well supplied, and look forward to rewarding these ever-reliable pilots for their continued service.” 

The [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition has elected to oversee the initiative. Units of fish, fruit and vegetables, animal meat and beer have been requested at Davies High in the Reorte system. More exotic traders are also encouraged to bring units of Lavian Brandy, Anduliga Fire Works and [[id:f38c2905-34c5-45c1-a2f5-2ec352b6630f][Eranin]] Pearl Whiskey. 

To ensure the celebration goes without a hitch, the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition has also offered to pay handsomely for all bounties collected on wanted ships in the system. 

The initiative is scheduled to run from the 12th to the 18th of December 3305. If the final targets are met earlier than planned, the campaign will end immediately.
