:PROPERTIES:
:ID:       5eef7afb-fa9a-4142-b9f9-42b88db09e1a
:END:
#+title: Freelance Report: Canonn to Make Deep-Space Rendezvous
#+filetags: :3302:galnet:

* Freelance Report: Canonn to Make Deep-Space Rendezvous

/19 Apr 3302/

An escape pod containing Canonn scientist Shannon Day has been miraculously recovered by an explorer named Commander Josh Hawkins, according to transmissions received from his ship. 

In his transmissions, Commander Hawkins revealed that he was able to extract Shannon Day's pilot log from her escape pod. From this he discovered that her ship had been sabotaged by Socha Korbemile, the former Canonn member who betrayed Dr Arcanonn. 

Now, the Canonn Interstellar Research Group has announced that two scientists – Commanders Bowen the Kotoc and Julian McCoy – have been dispatched to find Commander Hawkins and bring Day's escape pod home to Thompson Dock in the Varati system. 

When news of Day's rescue reached Dr Arcanonn, he requested that her escape pod be recovered as quickly as possible, but it is not yet known why she is so important to the scientist. 

Commander Lord Zoltan
