:PROPERTIES:
:ID:       81304c67-5e94-4de0-96fe-3a8a1251b797
:END:
#+title: [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] Prepares ‘Final Thargoid Battlefield’
#+filetags: :Thargoid:galnet:

* [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] Prepares ‘Final Thargoid Battlefield’

/30 Jun 3308/

*Pilots’ Federation ALERT* 

The HIP 22460 system will be the stage for a decisive strike against the Thargoids by Azimuth Biotech and the superpowers. 

The following message was broadcast across all public channels: 

“This is [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. Construction of the Proteus Wave has officially commenced. This version of my anti-xeno superweapon has been designed to bring absolute victory against our adversaries.” 

“HIP 22460 will serve as the final battlefield in the Thargoid war. As with previous superweapons, we anticipate that the Guardian-based technology incorporated within the Proteus Wave will once again attract the Thargoids. However, this time it will eradicate the alien threat not just from the system, but from the entire galaxy.” 

“Everyone who wishes to see this hostile species defeated once and for all should view this project as a call to arms. This is not a time for politics or debate. It is an opportunity to secure humanity’s continued survival.” 

Azimuth Biotech megaships have entered the HIP 22460 system. Commodore [[id:bcaa9222-b056-41cf-9361-68dd8d3424fb][Morag Halloran]] is coordinating the operation aboard the Bright Sentinel. The Heart of Taurus will serve as a delivery point for incoming resources. Two other megaships, Musashi and Glorious Prospect, are in the nearby Pleiades Sector CW-U B3-2 system to provide further logistical support. 

Alliance Defence Force, Federal Navy and Imperial Navy forces have also taken up positions in the HIP 22460 system. These ships have been modified for anti-xeno combat, as they expect to face Thargoid vessels in greater numbers than ever previously encountered. Military sources confirmed that although the ships’ experimental weaponry is being deployed somewhat prematurely, it should still prove effective.
