:PROPERTIES:
:ID:       eb07eefa-7817-4afc-9f62-d6393b06d039
:END:
#+title: Aegis Renegades Face Criminal Charges
#+filetags: :galnet:

* Aegis Renegades Face Criminal Charges

/29 Nov 3307/

Admiral Aden Tanner and the crew of the Musashi megaship will be placed on trial for attacking Salvation’s allies. 

The admiral disobeyed orders by attempting to gain access to Hind Mine starport, the headquarters of Taurus Mining Ventures. After failing to achieve this, most of the Musashi’s crewmembers were detained and repatriated to their respective home systems to face civil or military charges. 

The Federal Navy has published this official notice: 

“Admiral Tanner is formally accused of mutiny and unlawful military action while in command of the Musashi. He will stand trial in a general court-martial. If found guilty, he will be dishonourably discharged and imprisoned for life.” 

Dr Paul Baumann, chair of the independent board of inquiry into Aegis, commented: 

“Recent events in the T Tauri system clearly fall within the scope of our investigation. For Aegis’s chief military liaison to launch an unauthorised attack, at the cost of many lives, will weigh heavily against the organisation.” 

Admiral Tanner claims that the anti-xeno superweapon deployed by Salvation in the Cornsar system has triggered an increase in Thargoid attacks. Although there is no direct evidence of this, the Thargoids have performed coordinated strikes against several systems in the weeks since that event.
