:PROPERTIES:
:ID:       633d4f11-d4c3-4410-809e-8b1296431926
:END:
#+title: Federal and Imperial Campaigns End
#+filetags: :Empire:Federation:galnet:

* Federal and Imperial Campaigns End

/10 Jan 3305/

Supply campaigns for the Federal and Imperial navies have concluded successfully, with traders delivering large amounts of military provisions. 

The League of [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]], acting on behalf of the Federal Navy, stated: 

“Many thanks to all the pilots who came through for the Federation. You can now collect your rewards at Payson Hub in the [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]] system.” 

An announcement was also made by the Sirsir Co, which coordinated a similar supply campaign for the Imperial Navy: 

“You have performed a great service for the Empire. Payments have been authorised at Mitchell Hangar in the Sirsir system.” 

Marquis Felix Novantico, a retired military strategist, commented: 

“Tensions caused by Nova Imperium have triggered much activity of this kind. But for the Federation to do the same suggests concern about a potentially hostile Empire, should [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]] claim the throne.”
