:PROPERTIES:
:ID:       5890470a-5e8d-4a3e-8408-66f4bcb703bc
:END:
#+title: Community Goal: Sirius Corp. to Address Unknown-Artefact Issue
#+filetags: :3303:galnet:

* Community Goal: Sirius Corp. to Address Unknown-Artefact Issue

/19 Jan 3303/

It is widely understood that Unknown Artefacts have the ability to extract materials from their immediate environment as part of a complex self-repair process. Unfortunately, this can have disastrous effects on starships and other forms of machinery. 

Perhaps the worst affected by this phenomena have been the galaxy's starports, many of which have had to suspend services as a result of Unknown Artefact-related disruption. The high prices offered for Unknown Artefacts on the black market means many starports have been flooded with the mysterious objects. And although meta-alloys can be used to counter Unknown Artefact-related interference, the scarcity of the material means this potential salve has had little impact. 

But a recent announcement from the Sirius Corporation indicates that the company intends to tackle the issue by funding a major new research and development project. The purpose of the project is to make starports and other outposts more resistant to Unknown Artefact-related interference through the application of specific microresources. 

In support of this programme, the Sirius Corporation has placed an open order for unknown fragments, untypical shield scans and aberrant shield pattern analysis, and promised to reward pilots who deliver these materials to Cormack Hub in the Procyon system. 

The campaign begins on the 19th of January 3303 and will run for two weeks. If the final target is met earlier than planned, the campaign will end immediately.
