:PROPERTIES:
:ID:       58f6d0b0-74b1-4e68-b2dd-3d0bc72f9a2f
:END:
#+title: Seo Jin-ae Awake, Releases Unauthorised Warning
#+filetags: :Thargoid:Empire:3310:galnet:
* Seo Jin-ae Awake, Releases Unauthorised Warning

/24 Oct 3310/

Reports that [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] special advisor [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]] has woken from a
week-long coma were followed by a statement by Seo, which was sent to
all major newsfeeds.

[[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] medical personnel had confirmed earlier in the day that [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo]] had
abruptly woken from [[id:ad3a5cb7-c1d7-4315-8fec-d6d01fa17a68][unconsciousness]], following a significant [[id:758c0315-3359-45b0-8880-550f4bea806a][seizure]]
on October 18th. There were no long-term physical concerns, and she
was expected to make a full recovery.

However, less than two hours later, [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo]] released a statement via
[[id:a12cdcbc-fa10-474e-8654-d3d7da17a307][ICE-cast]]. The raw footage was self-recorded and is believed to have
been made without [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] command’s authorisation.

“I hate making these public announcements, so don’t expect it to be
good”, she explained. “But everyone keeps telling me how important I
am to the war effort, so why not test that and see if anyone listens?
There’s something everybody needs to know. What happened to me wasn’t
an accident or an illness.”

“Right before I passed out there was a noise in my head. It was like
someone plugged an amplifier straight into my brain. I couldn’t stop
it, and it hurt like you wouldn’t believe. It’s still echoing in my
skull somewhere. But more than that, I could feel it. Moving through
my consciousness.”

“My memories rushed past me in a blur. I couldn’t stop it. It felt
like everything I’ve ever known, learned or whatever... Just spinning
and spinning around. Even in a [[id:7ec102a9-059e-4a16-b89d-2450cb2b20ad][coma]], I could feel it. The Thargoids
had finally noticed my presence and tried to learn what they could
about me – which also means everything I know about humans. They
scraped it out of my mind. I’m sorry that I couldn’t stop it. I’m
sorry.”

“But I can still hear the Thargoid mind. I guess they’re done with
me. They’re planning something now. Listen to Aegis – they'll do
everything they can to fix this.”

[[id:878b6075-e168-4d0a-bb0f-9e6103c7f033][Ivano Colombera]], the Imperial research lead for the [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] project, has
speculated that the cortical implant which grants Seo the ability to
hear the Thargoid [[id:cf8efef4-6db7-4780-9b79-6321b738adfc][hive]] mind may have disrupted an attempt to [[id:980d793d-2073-4e0b-8eb9-65c8dbd33202][control]]
her like a drone. No other statement from Aegis has yet been made.
