:PROPERTIES:
:ID:       a59f3e0f-34bd-4ae7-93f4-77882a9ab8fb
:END:
#+title: Superpowers Commit to Salvation
#+filetags: :galnet:

* Superpowers Commit to Salvation

/02 Aug 3308/

The leaders of the Alliance, Empire and Federation have publicly confirmed their support for Azimuth Biotech’s anti-xeno operation in HIP 22460. 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] reiterated his position during an interview with the Old Worlds Gazette: 

“It is our duty to protect the peoples of the Alliance. Since we currently lack a dedicated naval fleet, we must rely on partnerships with key military providers. With Salvation’s advanced weaponry and Sirius Corporation’s large-scale logistical might, Allied worlds have never been safer from Thargoid attack.” 

The Imperial Senate discussed Professor Alba Tesreau’s accusations of criminality against Azimuth Biotech, to which Emperor Arissa Lavigny-Duval responded:  

“Professor Tesreau remains a respected member of the Achenar Research Council, but a single viewpoint cannot eclipse the strategic significance of the Proteus Wave project. Our military experts are confident that, should the weapon deliver on the promises Salvation has made, the Thargoid threat will be diminished. A review of the situation will then be conducted.” 

During a promotional tour of marine training centres in the Eta Cassiopeiae system, President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] told reporters: 

“Director Rademaker is absolutely correct: those who deliberately sabotage Azimuth Biotech’s operations are only helping the Thargoids, which is tantamount to treason. The Federation’s citizens have the right to live without fear of alien invasion, and Salvation’s ingenuity will help us preserve that right.” 

One Allied megaship, three Farragut-class battle cruisers and three Majestic-class interdictors are currently deployed in the HIP 22460 system to defend the Proteus Wave against the Thargoids.
