:PROPERTIES:
:ID:       9d00949d-a83f-4c04-94dc-cb5fd3f0326c
:END:
#+title: Thargoid War Update: September 3309
#+filetags: :Federation:Thargoid:galnet:

* Thargoid War Update: September 3309

/27 Sep 3309/

The race is on to develop technology which can recover humans from Thargoid Titans, reports Vox Galactica journalist Jade Sanderlyn. 

“Now we know the stomach-churning [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]]: the Thargoids are keeping people they abduct alive. The dramatic leak of a high-level conversation within Aegis confirmed that Thargoid tactics had shifted to incorporate the mass abduction of humans. [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]’s telepathic connection to the aliens revealed that captives are being stored inside pod-like structures aboard the Titans. She also sensed that the Thargoids considered these captives an important part of their invasion plan.” 

“Aegis took these visions seriously, releasing an update to the pulse wave xeno scanner that was designed to test her hypothesis. Sure enough, those pilots who dared make a close approach to the Thargoid motherships detected human life-signs beneath their hulls. This is where civilians from conquered systems are being held. For what purpose? We scarcely dare imagine.” 

“Demands to save these people from their unknown fate have rippled across every inhabited world. To their credit, the three superpowers have empowered Aegis to make this its top priority. Even Sirius Corporation has offered assistance, sharing designs for a modified sub-surface displacement missile that might be capable of extracting these pods from within the Titans. Time is of the essence, since not even [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]] knows for certain what the Thargoid intentions are for the prisoners.” 

“From the scientific community to the general public, there is enormous speculation. What state will the captives be in, assuming they can be recovered alive? Will they even be recognisably human? Some xenologists claim that the life-support chambers – to protect humans from the Thargoids’ toxic atmosphere – mean a stable physical condition is probably. But whether this is a necessity of their capture methods or an intentional step in a broader process remains unclear.” 

“Meanwhile, anti-xeno forces continue to achieve impressive results. The number of Thargoid-controlled systems has reduced significantly from only three months ago. Alien fleets are apparently struggling to expand their territory, with organised system defences supported by the Pilots’ Federation preventing the loss of new systems. What seemed like a near-hopeless task when the Maelstroms arrived has become a shining example of human courage and determination for future generations.” 

“This is [[id:139670fe-bd19-40b6-8623-cceeef01fd36][Jade Sanderlyn]] for Vox Galactica. Stay safe out there.”
