:PROPERTIES:
:ID:       b0e27f02-aaf9-4a82-87f2-40172f9795ee
:END:
#+title: Agricultural Industry Predicts Low Harvest
#+filetags: :galnet:

* Agricultural Industry Predicts Low Harvest

/13 Sep 3305/

The Interstellar Association for Agriculture has announced that below-average crop yields are expected in several key locations. 

Dr Genevieve Kane, writing on behalf of the organisation, published this statement: 

“Recent audits conducted on two primary agricultural worlds, located in Diso and Orerve, indicate that staple food harvests have been markedly lower in recent months.” 

“Broader data analysis suggests that crop returns in several other systems may also fail to meet projected quotas. An investigation is underway to identify the reasons for this drop in produce.” 

“To prevent a shortage of produce from impacting consumers, the IAA is reviewing options to enhance the fertility of cropland used for domestic consumption. These include newly proposed synthetic treatments that we hope will increase the sustainability of essential harvests.” 

The situation was first highlighted during [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Festival of Culture’s culinary week, when events in the Diso system were impacted by difficulties in sourcing fresh ingredients. Subsequent reports have indicated that these shortages are not unique to Allied space.
