:PROPERTIES:
:ID:       145e5214-fd7c-4d89-bf50-0e640bc50dee
:END:
#+title: Deliveries Requested to Commemorate Duval Family
#+filetags: :Empire:Federation:galnet:

* Deliveries Requested to Commemorate Duval Family

/25 Aug 3309/

*Pilots’ Federation ALERT* 

Shipments of precious materials are needed in the [[id:735abc3e-2370-4fd4-a38c-3796f0dfd536][Laedla]] system to build statues honouring the House of Duval. 

Archduke Otto Lombardo-Duval made a public announcement to launch the initiative: 

“We are all relieved that our beloved Imperial Mother is on the path to recovery. In such times, we must remember how much all citizens owe to the Duval dynasty, whose thousand-year reign has brought peace and prosperity to trillions.” 

“In honour of Her Majesty the Emperor and all those who came before her, I am arranging for mighty statues to adorn the public plazas of many Imperial worlds. Using the finest quality gold, jadeite and platinum, we will construct impressive monuments to the architects of our glorious Empire.” 

The Imperial Herald published a related piece by royal correspondent Gudrun Vestergaard: 

“Archduke Otto Lombardo-Duval is the son of Prince Baylor Duval, one of Emperor Hesketh’s brothers, who married into the House of Lombardo nearly a century ago. This offshoot branch of the Imperial Family are survivors of the mass assassinations perpetrated by the NMLA, as a result of which their prominence among the nobility has risen.” 

“Emperor Arissa has given the statues her personal blessing, but the mood within the palace is mixed. Some view Archduke Otto as having delusions of grandeur. Others consider him an opportunist looking to ingratiate himself with more prominent family members. But perhaps this is a simple gesture in good faith – a swift response to [[id:33f63de9-fd79-4790-a1a5-ebd87aaeea2d][Florence Lavigny]]’s request for unity within the royal family.” 

The required resources can be delivered to Kummer Acropolis in the [[id:735abc3e-2370-4fd4-a38c-3796f0dfd536][Laedla]] system. Laedla Empire Assembly, which is providing logistical support and security for the project, will redeem bounty vouchers for wanted ships in the system.
