:PROPERTIES:
:ID:       dd593d44-450d-4629-8281-40eab62b5ce5
:END:
#+title: Federal Times Reporter Named as Murder Suspect
#+filetags: :3301:galnet:

* Federal Times Reporter Named as Murder Suspect

/23 Aug 3301/

Federal Times Reporter Named as Murder Suspect 
 
Following news of the brutal murder of Agent Susan Monroe, the Federal Security Services upgraded [[id:c04cc538-f85c-4409-9751-9df8b3e56422][Elaine Boyd]]’s person of interest status to 'suspect', and called for any information regarding the reporter’s movements. 

“This was a particularly savage murder of a person who laid their life on the line. We believe that [[id:c04cc538-f85c-4409-9751-9df8b3e56422][Elaine Boyd]] was using her lover to access confidential information. While we haven’t yet ascertained the exact nature of the information she was trying to access or why she murdered the agent. It is also unknown whether Agent Monroe was a willing participant in the information retrieval, although we believe that her murder indicates that she was not. 

“We urge anybody who sees [[id:c04cc538-f85c-4409-9751-9df8b3e56422][Elaine Boyd]] to report her location immediately. At this time she is considered dangerous and should not be approached.” 

In a statement, the Chief Editor of the Federal Times said: 

“Having worked with Miss Boyd for seven years, I find it hard to imagine that she could commit the crime she is accused of. We are of course helping the security services with their inquiries, but I can confirm we have had no contact with Miss Boyd for several days.”
