:PROPERTIES:
:ID:       ad1feb90-09c1-47f4-869d-fe812e84f87f
:END:
#+title: Senate Blocks ACT Investigation
#+filetags: :galnet:

* Senate Blocks ACT Investigation

/17 Jan 3308/

There are claims that the Imperial Senate is preventing efforts to examine a potential link between the Empire’s security services and the NMLA. 

Captain Saskia Landau has publicly stated that the terrorists’ dark-comms network is closely related to the Omega Grid system used exclusively by Imperial Intelligence. She expanded on her theory in a statement to Vox Galactica: 

“Based on evidence and interrogation transcripts obtained by ACT, I believe that rogue elements within Imperial Intelligence were training and providing equipment to the NMLA. This would help explain the level of sophistication they achieved in coordinating their starport attacks and communicating without detection.” 

“There is certainly enough circumstantial proof to warrant a dedicated investigation. But the Senate is refusing to authorise this, which makes me wonder what they are trying to hide.” 

Senator Karl Nerva reiterated: “It is time for ACT to devolve and return much-needed resources to [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] where they belong.”  

However, Senator Caspian Leopold responded: “To alleviate any lack of confidence in our security services, we should examine Captain Landau’s allegation rigorously. Our citizens must be reassured that Imperial Intelligence exists solely for their protection.”
