:PROPERTIES:
:ID:       c3569725-d3a2-4b8a-8ecb-603662013d96
:END:
#+title: Dredger Clan Resumes Nomadic Travels
#+filetags: :3307:Federation:Guardian:galnet:

* Dredger Clan Resumes Nomadic Travels

/03 Dec 3307/

*Pilots’ Federation ALERT*

The Scriveners Clan dredger has departed from the Oochost PC-C c29-0 system to an unknown destination.

Freelance reporter [[id:270bb579-0fc7-430c-bc67-c200be1647a5][Casey Kilpatrick]] provided a report for [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]]:

“After a coalition of supporters helped them to bypass [[id:b0f0e40a-14e9-422d-aa9d-5ff6296f3421][Orion University]]’s override codes, the Scriveners Clan has finally resumed their nomadic lifestyle. To its credit, the university has finally taken stock of public opinion and agreed not to pursue its ownership claims over the ancient dredger.”

“Many in the scientific community have pointed out that the contents of the Knowledge Core, around which the Scriveners’ entire culture is based, will now remain a mystery. There are rumours that this tribe of academic researchers have acquired data about the [[id:f57cff55-3348-45ea-b76f-d0eaa3c68165][Guardians]] during their decades of wandering, which was perhaps the real prize sought by Orion University.”

“Concerns have also been raised about the Scriveners’ chances of survival if they encounter hostile forces. Had the Scientia Aeterna [[id:751c84bc-ea85-495d-923c-7776da57803a][megaship]] been allowed to accompany the dredger, it could have offered protection or at least called for assistance. Now that the Scriveners Clan have resumed a solitary existence, their fate is once again entirely in their hands.”
