:PROPERTIES:
:ID:       dae8c5c0-5ca6-40b8-b07e-32e8bd70f7ef
:END:
#+title: Coalsack Nebula Project Gathers Ammonia Worlds Data
(fset 'galnet\ import
   (kmacro-lambda-form [?\C-m ?\C-f ?\C-f ?\C-@ ?\C-e ?\C-\[ ?w ?\C-c ?r ?f ?\C-y ?\C-m ?\C-\[ ?x ?\C-\[ ?p ?\C-m ?\C-\[ ?p ?\C-m ?\C-\[ ?\[ ?8 ?^ ?\C-x ?o ?\C-x ?h ?\C-\[ ?w ?\C-x ?o ?\C-y ?\C-a ?\C-i ?\C-\[ ?\[ ?8 ?^ ?\C-m ?\C-c ?\C-c ?\C-x ?k ?\C-m ?\C-x ?k ?\C-m ?\C-n] 0 "%d"))

* Coalsack Nebula Project Gathers Ammonia Worlds Data

/10 Dec 3306/

*Pilots Federation ALERT* 

Explorers have catalogued many ammonia worlds for a Sirius Atmospherics terraforming project in the Coalsack Nebula. 

The subsidiary of Sirius Corporation is one of several companies that are working in partnership with the Alliance to commercially exploit the region.  

Project director Dr Maximilian North announced the successful completion of the initiative: 

“The data provided on planets with ammonia-based atmospheres will be invaluable to our terraforming simulations. With our new environmental techniques, some of these poisonous worlds within the nebula may one day become habitable.” 

Sirius Atmospherics has confirmed that payouts for all contributing pilots are now available at Betancourt Base in the Musca Dark Region PJ-P b6-1 system. 

As the expansion into the Coalsack Nebula progresses, Commodore Morag Halloran of the Alliance Defence Force commented on the possibility of further attacks from the Thargoids: 

“Anti-xeno security is not as stringent as we had planned, due to the low availability of ADF vessels and Aegis being impacted by Federal and Imperial defunding. It may be necessary to call upon the galactic community again, should we encounter further interference from the Thargoids.”
