:PROPERTIES:
:ID:       8fa044d7-e1f7-4a93-8f70-a9aff23c41c3
:END:
#+title: Victory for Federal Forces Against Jupiter Division
#+filetags: :3307:Federation:galnet:

* Victory for Federal Forces Against Jupiter Division

/18 Feb 3307/

*Pilots Federation ALERT* 

Jupiter Division, the breakaway faction from Core Dynamics, has been defeated in the HIP 54530 system. 

The independent corporate nation met armed resistance from a local faction, the Silver Legal Group, which defeated them in battle with the aid of independent ships. Director Theodore Sullivan announced: 

“Thanks to the courage of many pilots, we have crippled the military forces behind this illegal coup and taken control of the system.” 

Rewards for all who fought for the Silver Legal Group are available from the Iron Wings of Justice megaship in the Ts'ao Tach system. 

The Silver Legal Group has been awarded permit control to prevent any further compromise of Federal assets. Pilots without this permit can perform missions for the faction at the Iron Wings of Justice megaship in Ts'ao Tach to access the HIP 54530 system.  

Remnants of Jupiter Division confirmed that despite their defeat, all those who sided with them during the conflict will be reimbursed at the Victory’s Forge megaship in the HIP 55014 system. 

The Federal Intelligence Agency has taken [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] into custody, where he will be charged for his involvement in the destruction of Starship One in 3301. Thousands of his loyalist followers have also been apprehended, and the return of stolen Core Dynamics ships and resources is being arranged.
