:PROPERTIES:
:ID:       8114ff87-e11c-4470-acaf-3d371b2e74d2
:END:
#+title: Naval Academy Graduates join "Operation Davy Jones" in the Pegasi Sector
#+filetags: :3301:galnet:

* Naval Academy Graduates join "Operation Davy Jones" in the Pegasi Sector

/11 Jul 3301/

Naval Academy Graduates join "Operation Davy Jones" in the Pegasi Sector 
 
Speaking at the graduation ceremony of the prestigious Naval Academy of Achenar, Senator [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] announced her campaign to liberate the 5.6 billion Imperial citizens scattered throughout the Pegasi sector. 

"I wish to extend my personal congratulations for your commitment to personal excellence and to the Empire. As you begin your career in the Imperial Navy, I would draw your attention to a cause that has been neglected far too long. Nearly 6 billion Imperial Citizens are currently subject to the lawless Kumo Crew. An elite Imperial vanguard has engaged the forces of [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] in what we call "Operation Davy Jones." I invite all graduates who would uphold Imperial order to join the fleet and liberate the Pegasi sector. We will not abandon our people! We will bring these pirates to justice!" 

Cheers echoed through the auditorium as the Senator concluded her remarks. An astounding 73% of the 10,000 graduates joined the Imperial armada bound for the Pegasi sector.
