:PROPERTIES:
:ID:       5348e850-5e49-44a9-879d-d9fcb4d293b3
:END:
#+title: Arissa Addresses Problems in Persephone
#+filetags: :3301:galnet:

* [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa]] Addresses Problems in Persephone

/23 May 3301/

Speaking from the site of her new palace on Kamadhenu, Princess Lavigny-Duval today addressed the recent problems faced by residents of Persephone in the face of a plague outbreak which was brought to the system by the refugees from Quivira. 

“I understand the concerns of the citizens of Persephone, and I am sorry for their plight. However, the illness affecting the refugees, many of whom are malnourished and woefully lax in terms of adequate vaccination cover, is not something that should concern the locals.” 

“Of more concern to locals should be the increase in pirate activity, which I have been reliably informed is up by almost 600% since Patreus decided to start throwing his weight around.” 

“The people of Quivira certainly need help, but it is their patron’s responsibility to help them, not mine. I’m sure Aisling is more than capable of handling this problem herself. However, if she wishes for my help I will of course be happy to oblige. We are family, after all.”
