:PROPERTIES:
:ID:       55779fe3-1592-4ac2-a8c3-e65bf8ced40c
:END:
#+title: Battle of Summerland Ends [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] Threat
#+filetags: :galnet:

* Battle of Summerland Ends [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] Threat

/24 Feb 3308/

*Pilots’ Federation ALERT* 

The Empire has carried out reprisals against the rogue faction Darkwater Inc in the Summerland system. 

The private military firm had trained [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terrorists and held Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] captive, on the orders of a cabal of senators named the Lords of Restoration. 

Darkwater mustered an impressive armada, but these were no match for a combination of superpower forces and independent pilots. Colonel Ronan Brock, the mercenaries’ leader, was killed during the fighting when he fled from the Onyx Storm megaship and was shot down by Imperial auxiliaries. 

Emperor Arissa praised all those who helped destroy Darkwater, and declared: “Let the Battle of Summerland mark the victorious end of our bitter war against both the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] and the traitors who sought to destabilise the Empire.” 

ACT clarified that “Although there may always be Neo-Marlinist extremists, the large-scale threat of the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] has finally been nullified.” All data obtained from the terrorists’ Omega Grid network has now been shared with the relevant security agencies. 

With Darkwater eliminated, the Empire has installed a new controlling faction into the Summerland system. The Praetorian Vigil will report directly to the Emperor and govern in her name. 

The Summerland Patron’s Party will redeem combat bonds and provide other rewards at the starport Henry O’Hare’s Hangar. A permit exemption allowing all independent pilots to enter the Summerland system will remain active for the next two weeks.
