:PROPERTIES:
:ID:       d5382b1e-4bd9-4730-bcaf-8fcd3c80b546
:END:
#+title: Galactic News: Federation Addresses Rumours
#+filetags: :galnet:

* Galactic News: Federation Addresses Rumours

/22 Sep 3303/

Following news that a Federal convoy was destroyed by Thargoid vessels in the Pleiades Sector IR-W D1-55 system, Lieutenant Jarah Kael of the Federal Navy has addressed rumours that the Thargoids may have attacked in self-defence. 

“There has been speculation that the Thargoid attack was an act of self-preservation. Nothing could be further from the truth.” 

“It is true that Thargoid vessels typically scan human craft rather than attack, so I can understand how this misconception has taken root, but I assure you it is baseless. Data recovered from IR-W D1-55, including the black box from the Farragut-class Battlecruiser, proves beyond a doubt that the attack was initiated by the Thargoids. To suggest otherwise dishonours the memory of those who lost their lives in this tragedy.” 

A spokesperson for Aegis, which is coordinating research into the Thargoids, confirmed the veracity of Lieutenant Kael’s statement: 

“We have been analysing the data from the attack site in an effort to understand the Thargoids’ motives and military capabilities. While I cannot yet reveal the results of that analysis, I can confirm that the convoy was attacked without provocation by multiple Thargoid vessels.”
