:PROPERTIES:
:ID:       d029ece4-4abb-42c9-870a-8da49c72a6a7
:END:
#+title: The Dukes of Mikunn Unveil Mercenary’s Respite
#+filetags: :3301:galnet:

* The Dukes of Mikunn Unveil Mercenary’s Respite

/08 Jun 3301/

The Dukes of Mikunn Unveil Mercenary’s Respite 
 
Thanks to the efforts of the Mercenaries of Mikunn, who were assisted in their endeavour to colonise a previously uninhabited region of space by hundreds of independent commanders, the Dukes of Mikunn are pleased to announce the opening of a new station in the area previously known as COL 285 Sector VG-1 B24-6.  

Over 1 million tonnes of metal were collected in Kwatee last month to help construct “Mercenary’s Respite,” the Duke’s newest Coriolis station. Remoteness from major high-tech hubs and attempts at bureaucratic power plays by the Law Party of HR 7327 are blamed for the delay in opening the Duke’s latest military installation.  

The Law Party’s assistance in constructing the station was initially offered in order to forge a lasting peace with the Dukes as part a cease-fire agreement in regards to HR 7327. Ironically, the Law Party lost an election to the Dukes during the truce, leading to the Dukes gaining control of both HR 7327 and COL 285 Sector VG-1 B24-6.  

B24-6, as the locals call it, has been renamed “Sefrys” in honour of a fallen Mercs commander.  

The Dukes of Mikunn urge all those who may have business with either the Dukes or the Mercs to contact their agents aboard Mercenary's Respite in order to make the appropriate arrangements.
