:PROPERTIES:
:ID:       a6dcbaf5-ded0-4c8d-8ddc-3dfdd6fc84f8
:END:
#+title: Galactic News: Federal Exploration Programme in Disarray
#+filetags: :Federation:3302:galnet:

* Galactic News: Federal Exploration Programme in Disarray

/23 Dec 3302/

Last month, the Federation launched an appeal for exploration data from a number of remote locations. A competitive appeal was simultaneously launched by a mysterious group known as the Children of Raxxla, which succeeded in completely derailing the Federal initiative. Karl Devene, head of Astrocartography at Mars High, was forced to resign as a result. 

Federal exploration projects are currently on hold as a result of the failed initiative, and Devene's successor has not been announced. Meanwhile, the Children of Raxxla has yet to reveal any findings from the data it received, leading some to speculate that the organisation never intended to. 

"I believe it was a cynical attempt to sabotage Federal research," said a spokesperson for Mars High Astrocartography. "It was never about exonerating [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] – they just used her plight to gain the data at the expense of the Federation. Unfortunately, the galactic community proved itself easily manipulated." 

Other commentators have concurred with the analysis. Jackson Trent, associate editor of The Imperial Citizen, said: 

"I don't understand the allure of Raxxla. They attacked Patreus's flagship and have proved themselves to be criminals of the worst kind. Patreus dealt with Emperor's Dawn – perhaps it's time for him to deal with the Children of Raxxla." 

Salomé, known in Imperial circles as Kahina Loren, was killed when the convoy transporting her to Koontz Asylum was interdicted and destroyed. She had been convicted of the attempted assassination of Denton Patreus.                                                                                                                                                                                                                                                          

Meanwhile, independent pilots returning from the expedition have reported a series of curious beacons in deep space, but few details have surfaced.
