:PROPERTIES:
:ID:       970c6ab6-6847-456d-bc90-91b316d1b050
:END:
#+title: Guardian Artefact Campaign Concludes
#+filetags: :galnet:

* Guardian Artefact Campaign Concludes

/26 Jul 3308/

*Pilots’ Federation ALERT* 

The third phase of an initiative to acquire Guardian artefacts for the Proteus Wave has ended successfully. 

Commodore Morag Halloran, Azimuth Biotech’s military coordinator, announced: 

“Salvation has asked me to extend his sincere thanks to all pilots for exploring ancient Guardian sites and transporting their discoveries to the Bright Sentinel in HIP 22460. The quantity of artefacts delivered over the past three weeks has surpassed our targets.” 

“The most recent shipments are now being ferried down to the surface of HIP 22460 10b. The Proteus Wave’s core mechanism is mere days away from being fully assembled. Calibration tests will then begin within the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] structure, which will vastly amplify the superweapon’s disruptive frequencies.” 

“It is now mission critical to defend the project. The [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] appear frenzied by the system’s concentration of Guardian technology, which is drawing their vessels in ever-greater numbers. I am liaising closely with the Allied, Federal and Imperial taskforces, but we require even more volunteers to provide tactical support to their capital ships.” 

With the delivery initiative concluded, contributing pilots can now collect their rewards from the Bright Sentinel megaship in the HIP 22460 system.
