:PROPERTIES:
:ID:       8ce15aa4-79fc-42d8-83f1-a2f8c09dc56c
:END:
#+title: Community Goal: Total Eclipse
#+filetags: :CommunityGoal:3303:galnet:

* Community Goal: Total Eclipse

/22 Aug 3303/

The Kpelidoog Empire Assembly, an Imperial organisation based in the Kpelidoog system, has announced plans to build a new Wells-class Carrier to support astronomical research. 

In a statement, a spokesperson for the organisation said: 

"Many of the galaxy's scientific groups are currently focused on the Thargoids, but we think it's important to keep an eye on the bigger picture. Once complete, this new ship will gather data on stellar bodies and unusual celestial phenomena." 

The Kpelidoog Empire Assembly has placed an open order for titanium, semiconductors and power generators for use in the construction, and has promised to reward pilots who deliver these commodities to Hipparchus Terminal in the Kpelidoog system. 

The spokesperson went on to say: 

"The success of this initiative depends largely on the support of the galactic community. That's why we've decided to incorporate the name of the pilot who makes the largest contribution into the name of the new vessel." 

The campaign begins on the 21st of August 3303 and will run until the 24th of August 3303. If the final target is met earlier than planned, the campaign will end immediately.
