:PROPERTIES:
:ID:       00decb16-ddc9-4143-b334-25d6e3b8faf1
:END:
#+title: Zemina Torval and Florence Lavigny Join Patreus’ Campaign
#+filetags: :galnet:

* Zemina Torval and Florence Lavigny Join Patreus’ Campaign

/27 Aug 3301/

Zemina Torval and Florence Lavigny Join Patreus’ Campaign 
 
Senator Patreus has seen a resurgence of support since his declaration of war against the group responsible for Emperor Hengist Duval’s murder. Reports from the campaign have indicated that Emperor’s Dawn is now claiming responsibility for the regicide, although this hasn’t been independently confirmed as yet. 

In a Senate session, Senator Zemina Torval declared her support for the operation and instructed her loyal followers to join the campaign. 

Analysts have been keenly watching the political landscape shift in the weeks since the Emperor’s death. Many had written off Patreus as his influence waned with the dishonour of his association with the Emperor’s assassin, Brendan Paul Darius. However, his decisive action against Emperor’s Dawn has raised his profile. Some believe that it is a cynical ploy by Patreus, but none can argue that he has gained the support of the Senate heavyweights. 

Even Florence Lavigny has spoken out for unity and support for Patreus: 

“When I was much younger, and my first husband dear Aristide was sadly eaten by a Ling Lang in his own menagerie, there were conspiracy theories, none of which were true. The simple truth was he was foolish to keep so many dangerous animals as pets. I’ve known Denton for years, and I know he wasn’t involved in the Emperor’s murder. Hengist had many enemies, but Denton Patreus was not one of them.”
