:PROPERTIES:
:ID:       48d635d5-3b9a-4af2-b7fe-9643459a0ac2
:END:
#+title: Neo-Marlinist Forces Gather in Mudhrid
#+filetags: :3307:Empire:galnet:

* Neo-Marlinist Forces Gather in Mudhrid

/19 Nov 3307/

The megaship Steel Majesty has arrived in the Mudhrid system after being taken over by [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terrorists. 

Its original owning faction, the Neo-Marlinist Order of Mudhrid, has officially reclaimed the vessel. Margrave Corentin Delacroix, the faction’s new military ruler and the son of former Landgrave Arastin Delacroix, announced: 

“The Steel Majesty has returned home to fulfil its destiny. Be warned: should any ships attempt to board or attack, all the former crewmembers still onboard will be executed.” 

Senior Agent [[id:fb74a286-1688-41e8-9bec-9ef14adaaf1f][Tanya Ramirez]] gave a statement on behalf of ACT: 

“Unfortunately, we cannot take action while hundreds of innocent people remain captive. But the NMLA’s effort to assemble troops, supporters and resources must not succeed. Having the Steel Majesty as a mobile base will allow them to regroup for a new campaign of terror – especially if they manage to reach [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] before we do.” 

A spokesperson for the Epsilon Fornacis Empire Group, which controls the Mudhrid system, claimed: 

“The hostages should be considered lost as casualties of war. We are prepared to perform our duty for the Empire once again by destroying the Neo-Marlinist threat.”
