:PROPERTIES:
:ID:       483485e7-37a8-46e0-9149-3d29d900d17b
:END:
#+title: Freelance Report: Federal Expansion Brought to a Halt
#+filetags: :Federation:Empire:3302:galnet:

* Freelance Report: Federal Expansion Brought to a Halt

/11 Jul 3302/

The Federal expansion campaign has been brought to a complete standstill. 

Ramsbottom Hub in the Segovan system has entered a state of lockdown, and many independent Commanders who had loaded up on commodities are now unable to complete their deliveries. 

The Federation has yet to make an official announcement, but reports have been flooding in from the galactic community on possible causes for the lockdown. Some pilots claim they were attacked by Imperial vessels, while others maintain it was pirates. 

Almost 4,000 pilots have contributed over 3.5 million tonnes between them. Now those Commanders are stuck with nowhere to deliver the requested commodities, and are understandably frustrated. 

The Federation is receiving the brunt of the backlash. Some are saying that Federal expansion on this scale was always going to receive opposition from the Empire, while others maintain that the Federation should have prepared for this eventuality by offering multiple ports of delivery and better security. 

One Commander said: "I'm here to protect the barnacles – I don't care about Feds or Imps. This is a prime example of politics getting in the way of what's truly important. They need to get off their high horses and discuss how we can protect the barnacles." 

Commander BluWolve
