:PROPERTIES:
:ID:       a3563c4f-05f4-40e7-92d7-8796d9ea8bbe
:END:
#+title: Week in Review 27 May 3304
#+filetags: :3304:galnet:

* Week in Review

/27 May 3304/

Here are this week’s major stories. 

Terrorist group the League of Reparation has committed three further murders in Federation space. 

The victims include two members of the Pilots Federation. In both cases, the Commanders’ ships were laser-branded with the words ‘FOR JAMESON’. 

Commodore Riri McAllister of [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Defence Force has been appointed to the Council of Admirals, filling the vacancy left by the late Tulimaq Buchanan, who was killed by the League of Reparation. McAllister has pledged to support efforts against the terrorist group responsible for her predecessor’s death. 

Meanwhile, entertainment journalist Solomon Helios has been speculating about the romantic life of Princess Aisling Duval, who is understood to have spurned the advances of Admiral Denton Patreus. Three potential suitors have been identified: Senator Caspian Leopold, anti-slavery campaigner Jarl Toredo, and Federal Ambassador Jordan Rochester. 

In other news, Los Chupacabras, an independent faction based in the LFT 926 system, has announced plans for a musical event known as the Jailhouse Rock and Blues Music Festival. In support of the event, Los Chupacabras have placed an open order for quantities of beer, tobacco, coffee and narcotics, and have promised to reward pilots who deliver these commodities to Meredith City in the LFT 926 system. 

Authorities in the T’iensei system have reported a sharp increase in the number of criminals operating in the area. To counter this threat, the Autocracy of T’iensei has placed a kill order on all ships on its wanted list, and has promised to reward pilots who deliver bounty vouchers to Dzhanibekov Port. 

Finally, two community-led initiatives reached successful conclusions this week. In the core systems, an operation to recover survivors and salvage from a convoy attacked by pirates was supported by scores of independent pilots, while in Colonia, hundreds of Commanders delivered microresources to the Colonia Co-Operative, which is investigating the region’s potential to support larger populations in the future. 

And those are the main stories this week.
