:PROPERTIES:
:ID:       72eb9536-ef2e-4f23-bd89-a43d971d9273
:END:
#+title: Xeno-Peace Activists: ‘We Are The Invaders’
#+filetags: :galnet:

* Xeno-Peace Activists: ‘We Are The Invaders’

/14 Sep 3308/

The xeno-peace movement, which calls for communication with the Thargoids, has sought to rationalise the latest incursions. 

Despite ongoing conflicts in the 42 n Persei, Chun Pindit and Tekkeitjal systems, Thargoid aggression has been attributed to defensive measures. Reports by journalists in those systems, which have focused on the increasingly aggressive Thargoid craft, have been labelled ‘propaganda’ endorsed by major media corporations. 

The ‘Thargoid Advocacy Project’ - a label which many supporters of the movement use in calls to action - believes that the authorities must commit to establishing a dialogue with the aliens. Timothy Culver, a prominent activist for the xeno-peace cause, provided a statement to The Sovereign: 

“The Thargoids did not invade our space. We invaded theirs. Entire nebulas and other regions have been inhabited by them for over a million years, but our leaders arrogantly assume these regions are human conquests. Thargoid defensive acts were countered by destroying countless numbers of their vessels, stealing their meta-alloy resources, and a recent attempt to inflict widespread slaughter upon their fleet.” 

“These latest incidents are reprisals for the Proteus Wave, a weapon of mass destruction built within one of the Thargoids’ own surface sites. This was the second such attempt to massacre vast numbers of Thargoids, the first being the mycoid bioweapon used less than two centuries ago. Such acts of revenge are common in humanity’s own military past.” 

“The Thargoids are responding via the only language our leaders understand: warfare. It’s time that we spoke a new language. Let’s start talking to our neighbours instead of aiming our weapons at them.”
