:PROPERTIES:
:ID:       2edc9733-2eb0-4a58-896a-b26c89f2e508
:END:
#+title: Community Goal: Ishmael Palin Launches Appeal
#+filetags: :3301:CommunityGoal:3302:galnet:

* Community Goal: [[id:8f63442a-1f38-457d-857a-38297d732a90][Ishmael Palin]] Launches Appeal

/12 May 3302/

Last month, Professor [[id:8f63442a-1f38-457d-857a-38297d732a90][Ishmael Palin]] announced his intention to retire from The Palin Institute, the research organisation he founded in 3301. In a statement, the professor indicated that he would relocate to a small research centre on Maia A 3 a, where he would continue investigating the Unknown Artefacts and meta-alloys. Now, the professor has issued a further statement, announcing that he has placed an open order for building fabricators for the construction of the new outpost. 

"The galactic community has given me considerable support over the past few months – even going so far as to rescue me and my team from pirates in the Orulas system – and I would very much like for them to be part of this initiative. The new research centre will be relatively modest, but there is still a need for materials. I can promise that pilots who deliver the necessary supplies will be generously compensated!" 

The Defence Party of Nespeleve, which is coordinating the effort on behalf of Professor Palin, has promised to reward pilots who deliver building fabricators to Wilkes Orbital in the Nespeleve system. The organisation has also promised to reward Commanders who eliminate hostiles operating in the system, to ensure those delivering building fabricators can do so safely. 

The campaign begins on the 12th of May 3302 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
