:PROPERTIES:
:ID:       3aa2a044-ea2e-4d8a-b87c-fc53fd1d7c07
:END:
#+title: Pirate Rebels Coup Attempt Fails
#+filetags: :3308:galnet:

* Pirate Rebels Coup Attempt Fails

/16 May 3308/

An insurrection led by Arch-Corsair [[id:8d019f27-75a9-4758-8600-327aee0e2c41][Vidar Trask]] has failed to gain control of the Kumo Crew syndicate. 

Vox Galactica featured a report by freelance correspondent Karleen Troy: 

“As might be expected, it’s hard to obtain official data when conflict breaks out within a criminal organisation. But all the information I’ve gathered points to the same conclusion: [[id:8d019f27-75a9-4758-8600-327aee0e2c41][Vidar Trask]]’s coup attempt has failed.” 

“What is surprising, however, is how close he initially came to dethroning [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]. The Kumo Crew were almost overwhelmed by the sheer number of fighters following Trask’s banner. I’m told that nearly half of the rebelling forces have yet to be identified, and are suspected to be mercenaries.” 

“A second mystery is that Arch-Corsair [[id:a002575a-7b72-4d9b-8c76-e748073a8e3e][Kay Volantyne]], another senior member of the Kumo Council, has been declared missing. The [[id:dc25c5b7-381e-4e8a-8599-68be61b19bae][Pegasi Sentinel]] newsfeed believes that she was killed by Trask personally. The newest inner circle member, Callan Salamanca, is leading Delaine’s counter-attack against the insurrectionists.” 

“Most of the surviving rebels have now retreated to HIP 10792 and are attempting to drive out the Kumo Council faction in that system. Eyewitness reports regarding the ongoing firefights suggest that Delaine is in no mood to forgive his would-be usurpers.”
