:PROPERTIES:
:ID:       21929440-14ac-48f8-9b08-745c1c14be53
:END:
#+title: Hudson and Winters Confirmed for Galactic Summit
#+filetags: :3307:Federation:Empire:galnet:

* Hudson and Winters Confirmed for Galactic Summit

/22 Feb 3307/

President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] and Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] will both attend the diplomatic conference in the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system. 

The Federation will also be represented by ambassadors from the Federal Diplomatic Corps, as well as several civil and corporate interests. 

Political correspondent [[id:e660f840-caed-45ef-985e-f75170cf9ca8][Sofia Trevino]] reported for [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“President Hudson’s personal presence at the Galactic Summit sends the message that he still holds the reins of power. He clearly hopes that facing off against the Empire’s leaders will distract the public from the recent [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] scandals.” 

“In his absence, Vice President Brad Mitchell will oversee congressional matters. There are rumours that Mitchell is positioning himself to challenge Hudson as the Republican Party candidate in the next election.” 

“The conference also offers opportunities for [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] to appear presidential. She has eagerly agreed to meet the Marlinist Colonies delegation, having coordinated humanitarian aid for the refugees last year.” 

“Winters has not asked Shadow VP [[id:cdb2224f-eb0b-45d0-b37f-9daccae07c32][Isolde Rochester]] to accompany her, perhaps as a rebuke for the criminal actions of her son. Furiously working on damage control for her family’s name, the Rochester matriarch has taken Jupiter’s two children into her care after his husband, [[id:f3e29df5-154d-4f05-b659-36fa2da9be01][Tomas Turai]], filed for immediate divorce.”
