:PROPERTIES:
:ID:       be1de7fc-61d0-4943-b37a-8807e033a4b4
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/90f7be59-33cd-49b3-a999-1a5b731f5794?resourceVersion=id%3A4878
:END:
#+title: Thargoids Wreak Havoc in Nebulas
#+filetags: :3307:Federation:Empire:Thargoid:galnet:

* Thargoids Wreak Havoc in Nebulas

/07 Jan 3307/

Starports in the Coalsack and Witch Head Nebulas have been damaged during full-scale Thargoid incursions. 

An appeal by Aegis for anti-xeno support led to a concerted response from the galactic community. However, the Thargoid forces proved to be overwhelming and have attacked systems within the nebulas, with the loss of thousands of lives.  

Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], chief military liaison of Aegis, broadcast this message: 

“Despite the heroic efforts of many pilots, the alien ships have resisted being driven from the Witch Head Nebula.” 

“Aegis’s military capability and manpower are both severely limited as a result of curtailed funding from the Empire and the Federation. We have no choice but to rely on independent pilots and anti-xeno squadrons as the first line of defence against the Thargoid threat.”
