:PROPERTIES:
:ID:       3bc42d44-e744-44f5-a175-687a19ec8f0e
:END:
#+title: Ram Tah's Last Hurrah
#+filetags: :galnet:

* Ram Tah's Last Hurrah

/09 Feb 3304/

Ram Tah, the galaxy's foremost expert on the Guardians, has revealed that his research funding will soon end. In an effort to make the most of his remaining finances, the engineer has appealed to independent pilots to deliver Guardian artefacts to his base in the Meene system. 

In a statement, Ram Tah said: 

"Public interest in the Guardians may have waned, but I believe there is more to learn. Only through thorough investigation and analysis can we hope to fully understand the Guardians, their technology and their relationships to other species. This knowledge could be of great importance to humanity." 

The campaign has received a financial boost from Meene General Industries, which has promised to reward pilots who deliver artefacts from Guardian sites to Felice Dock in the Meene system. 

The campaign begins on the 8th of February 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
