:PROPERTIES:
:ID:       3ed8e3d6-4320-4203-a1b6-8305d756a656
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/49ffee89-da31-445e-a322-39f2acd6405b?resourceVersion=id%3A4932
:END:
#+title: Conflict Between Federal Forces and Jupiter Division
#+filetags: :galnet:

* Conflict Between Federal Forces and Jupiter Division

/11 Feb 3307/

*Pilots Federation ALERT* 

Jupiter Division ships have engaged in battle with rival Federal vessels in the HIP 54530 system. 

Loyalists to former Core Dynamics CEO Jupiter Rochester have built their own breakaway faction in HIP 54530. The FIA suspects that Jupiter Division agents first infiltrated the HIP 54530 Gold Universal Group years ago, and permit locked the system to conceal their efforts to overtake it from within. 

The self-appointed Supreme Executive Rochester declared: 

“The Federation is choking to death on its outdated bureaucracy – only corporate rule can save it! But first the galactic community must protect my followers, so I can establish a permanent base of operations.” 

Director Theodore Sullivan of the Silver Legal Group announced: 

“We will not tolerate these criminals illegally controlling this system. Once victory is won, the Federation will be able to bring Rochester to justice.” 

Jupiter Division has offered generous rewards to any pilots willing to help secure its presence in the HIP 54530 system. The Silver Legal Group has asked Federal auxiliaries to support its efforts to degrade Jupiter Division’s military force. 

The Pilots Federation has agreed to supply all ships participating in this conflict with temporary permits to access HIP 54530. These will expire early on Thursday the 18th of February 3307.  

However, neither permanent nor temporary system permits apply to fleet carriers, since they are capable of ferrying vessels which could evade detection and authorisation.
