:PROPERTIES:
:ID:       682a7224-ca6c-48f9-8f1a-c376faaef3ff
:END:
#+title: Azimuth Biotech: ‘We Can Serve Alliance’
#+filetags: :galnet:

* Azimuth Biotech: ‘We Can Serve Alliance’

/24 Nov 3309/

Azimuth Biotech has suggested that it can replace Sirius Corporation as the Alliance’s anti-xeno military partner. 

The move follows [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Assembly’s decision to reevaluate its strategic xeno defence pact with Sirius, amid concerns that the megacorp has not sufficiently protected Allied systems from the Thargoids. 

CEO Torben Rademaker offered the following statement during a recent shareholder presentation: 

“Azimuth Biotech is – and always has been – the only corporation to specialise in anti-xeno weapons tech. Sirius Corporation, once the trend-setter in so many fields, has become complacent and is now best described as a household goods manufacturer with delusions of grandeur. Aegis is a loosely connected gang of publicity-seekers playing war games with technology developed by uncredited researchers. But Azimuth specialists have been diligently researching the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] species ever since we made first contact with them two centuries ago.” 

“We can supply [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Defence Force with weaponry and defensive technology guaranteed to be a match for anything in the Thargoids’ arsenal. I’m prepared to meet with Prime Minister Mahon personally to work out the details of our proposal.” 

The Alliance Assembly has not yet formally responded, but Councillor Hildegard Dressler said: “Our vulnerability to [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] attacks means Azimuth should be seriously considered to reinforce our security.” Councillor Ainsley Niven took the opposite view: “There will be mass uprisings if we collaborate with the most notoriously immoral company in history, one soaked in the blood that Salvation spilled in his pursuit of greatness.” 

Leon Banerjee, science correspondent for Vox Galactica, observed: 

“It’s worth noting what Azimuth is not offering the Alliance: the anti-xeno superweapons that once cleared entire systems of Thargoids. Resurrecting Proteus Wave technology after HIP 22460 would cause a public outcry, but that wouldn’t greatly concern Rademaker. Therefore, we can deduce that Azimuth’s ability to weaponise Guardian artefacts died along with Salvation, leaving the corporation struggling for relevancy following his death.”
