:PROPERTIES:
:ID:       8e162ccf-57bc-474b-9325-a1413c0460b8
:END:
#+title: Week in Review 04 Mar 3304
#+filetags: :Federation:Thargoid:3304:galnet:

* Week in Review

/04 Mar 3304/

Here are this week’s major stories. 

Reports from independent pilots confirm that a new type of Thargoid vessel has been encountered, both in the Pleiades and on the fringes of the core systems. The ship, designated a Thargoid Scout Marauder by the Pilots Federation, are reported to be more manoeuvrable than the Thargoid Interceptor, but less resistant to weapons fire. 

Meanwhile, analytical reports released by Aegis have confirmed a pattern to the Thargoids’ recent starport attacks, which have left thousands dead and infrastructures crippled. Admiral Aden Tanner, Aegis’s chief military liaison, confirmed that the Thargoids are specifically targeting starports where Aegis laboratories are established. Defensive measures have been increased at all starports where Aegis has a presence. 

Authorities in Colonia have decided to step up security by building a new security installation in the region. The Arek Crimson Vision Corporation has launched a parallel campaign to boost Colonia’s military strength by providing the region with weapons. Both initiatives are a direct response to ongoing Thargoid hostility. 

Finally, Admiral [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] has announced that the joint Federal-Imperial operation in the Pleiades Sector OI-T c3-7 and Arietis Sector XE-Z b4 systems has succeeded in achieving its objectives. Scores of independent pilots supported the campaign by eliminating Thargoids, and by recovering black boxes and personal effects from Thargoid attack sites. 

And those are the main stories this week.
