:PROPERTIES:
:ID:       c54d1e56-37af-4177-a0e9-b79bdda15f93
:END:
#+title: Community Goal: Bringing Back the Bourbon
#+filetags: :Federation:CommunityGoal:3302:galnet:

* Community Goal: Bringing Back the Bourbon

/14 Apr 3302/

Rumours from the [[id:d40886f3-bc59-4f0d-8926-b125ee01c9bb][Epsilon Indi]] system suggest that the United Epsilon Indi Flag is recruiting independent Commanders for a campaign called 'Bribes 4 Bourbon'. In a series of illicit meetings with system officials, the organisation reportedly secured an agreement to revise the status of Indi Bourbon and make it a legal beverage. 

Yulia 'The Needle' Kuriakova, a spokeswoman for the organisation, said: 

"For almost a year, authorities in [[id:d40886f3-bc59-4f0d-8926-b125ee01c9bb][Epsilon Indi]] have prohibited the production of Indi Bourbon, which is classified as an illegal substance. Our plan is to bring vast quantities of illegal liquor Mansfield Orbiter to pay off the officials." 

The United [[id:d40886f3-bc59-4f0d-8926-b125ee01c9bb][Epsilon Indi]] Flag has requested that Burnham Bile Distillate, [[id:f38c2905-34c5-45c1-a2f5-2ec352b6630f][Eranin]] Pearl Whisky, Leestian Evil Juice and Wuthielo Ku Froth be smuggled into Mansfield Orbiter. A temporary black market has been established to accept these commodities. 

The Federation, meanwhile, has asserted that the campaign represents an act of economic malfeasance, and has accused the United [[id:d40886f3-bc59-4f0d-8926-b125ee01c9bb][Epsilon Indi]] Flag of inciting civil disobedience. But Epsilon Indi is no stranger to dissent: in November last year an explosive-smuggling operation organised by a group called Revolution Incorporated was uncovered. 

The United [[id:d40886f3-bc59-4f0d-8926-b125ee01c9bb][Epsilon Indi]] Flag has promised to reward pilots who deliver rare liquors to Mansfield Orbiter in the Epsilon Indi system. The campaign begins on the 14th of April 3302 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
