:PROPERTIES:
:ID:       fcac8d14-a34a-4b33-8427-9c7138b3cbd3
:END:
#+title: Galactic News: Fifth Aegis Campaign Concludes
#+filetags: :Thargoid:3303:galnet:

* Galactic News: Fifth Aegis Campaign Concludes

/01 Dec 3303/

An [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] spokesperson has confirmed that the organisation’s campaign in the Electra system has come to an end. The operation was designed to reduce the number of [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] operating in the system, and to gather [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] material for [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]]’s ongoing research and development programme.

The spokesperson released the following statement:

“The recovered Thargoid materials will be used to test larger versions of the AX dumbfire missile and AX Multi-Cannon, which will soon be made available to the galactic community at planetary military bases. Our thanks go to those who supported this operation.”

Pilots who contributed to the initiative can now collect their rewards from Cavalieri in the Electra system.
