:PROPERTIES:
:ID:       fb8b471b-5bcc-4bb3-a29e-06425d3dfc7e
:END:
#+title: Community Goal: Campaign to Develop i Sola Prospect
#+filetags: :galnet:

* Community Goal: Campaign to Develop i Sola Prospect

/28 Jan 3302/

The Imperial Inquisition is known for regularly organising competitive combat events, ranging from small-scale skirmishes to the popular 'Hunter Games', an intense 20-person gladiatorial competition. As one might expect, members of the organisation make frequent use of outfitting services, but they are constrained by the fact that their nearest outpost offers only a limited range of options. That's why the faction has launched a campaign to develop its local outpost of i Sola Prospect on Brestla A1. 

Central to the initiative is a request for industrial materials, which the Imperial Inquisition will use to upgrade the outpost. A spokesperson for the group released a brief statement: 

"Developing i Sola Prospect will mean that every type of weapon, ship and component needed to deliver the ultimate entertainment experience is always available. Naturally this will also be a huge boon to the galactic community." 

If the campaign is successful, i Sola Prospect will become the first planetary outpost to boast a complete range of services, including a comprehensive shipyard.
