:PROPERTIES:
:ID:       6f5a2761-9332-4b17-a107-a18629e6b950
:END:
#+title: Pirates Wiped Out in Amitrite
#+filetags: :3301:Empire:galnet:

* Pirates Wiped Out in Amitrite

/29 Sep 3301/

Pirates Wiped Out in Amitrite 
 
Officials from the Defence Force of Amitrite have praised the many pilots who helped clear the system of pirates this week. Hundreds of hostile ships were eliminated, and crime levels in the system subsequently dropped to new lows. 

Representatives of the Libertas Cooperative, speaking on behalf of resettled Pegasi Sector refugees, also extended their thanks to the pilots: "Many of the refugees in the Munshin system have been separated from their families. Now they can be safe in the knowledge that their loved ones can traverse the Empire safely. For the second time in recent weeks, the citizens of the Empire have proved they care about their fellow man. They have set an example for us all." 

Some segments of the media have speculated that the participation of independent pilots was especially high because of crime-deterrence policies introduced by Senator [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]]. The Defence Force of Amitrite dismissed these claims, calling them "a crass attack on brave men and women who risked their lives to help strangers". 

Commander Quade
