:PROPERTIES:
:ID:       09ec1614-0117-4c52-b097-ad31827788ad
:END:
#+title: Pharma Giant Victorious in the Haithis System
#+filetags: :3307:Federation:Alliance:galnet:

* Pharma Giant Victorious in the Haithis System

/16 Sep 3307/

*Pilots Federation ALERT*

The Haithis Purple Dynamic Group has fought off the [[id:2dc1b92f-4bdc-4504-ad5f-a9c5794155dc][Kumo Council]] assault, securing the completion of Neomedical Industries’ onionhead project.

The pharmaceutical corporation had received deliveries to Haithis to begin producing onionhead gamma strain for medicinal purposes. In response, the [[id:1dfc7c53-642a-4404-a8e8-16a8cc18482a][Kumo Crew]] syndicate attacked Neomedical’s corporate partner but failed to achieve its objectives.

Neomedical Industries confirmed that investment in its project to mass-produce onionhead gamma strain has increased following the conflict’s resolution. The news was eagerly received in many [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][Alliance]] and independent systems, which have expressed interest in the new healthcare treatment.

[[id:5e42db2b-b180-4e0a-af3a-dd5dcd45cf28][Olwyn Kendrick]], CEO of Neomedical Industries, told the media:

“We owe a huge debt to the galactic community for defending our operation. Large-scale manufacture of onionhead gamma strain can now commence. We will soon be able to improve the quality of life for millions of people.”

The Haithis Purple Dynamic Group is offering rewards to its supporters from Crippen Port in the Haithis system.
