:PROPERTIES:
:ID:       7f7907eb-6620-4300-97f8-22fe3fcd14ae
:END:
#+title: Freelance Report: Jacques Barnacle Search
#+filetags: :galnet:

* Freelance Report: Jacques Barnacle Search

/16 Jul 3302/

The discovery of Jacques Station has prompted many Commanders to load up on meta-alloys and start the long trek to Eol Prou RS-T d3-94. 

One group that has already made it has begun searching the area for barnacles. If the structures are found, they could provide Jacques with the meta-alloys needed to fix the station. 

Some Commanders remain sceptical, arguing that the barnacles are engineered and won't be found in the system, but that hasn't stopped the search from going ahead. For many it is not a question of 'if' barnacles will found it – it is a question of 'when'. One of the searchers said: 

"It makes sense there would be barnacles out here – the system has many of the conditions required. But searching for them is a big job. Any assistance from pilots in the area is welcome." 

Commander BluWolve
