:PROPERTIES:
:ID:       7907f9a3-6421-4d9f-a3d8-965866d0861f
:END:
#+title: Computer Designers’ Rivalry Escalates
#+filetags: :3304:galnet:

* Computer Designers’ Rivalry Escalates

/01 Sep 3304/

Maddox Hurd, owner of Herculean Machines, has publicly dismissed the efforts of rival company Supratech. Both companies are currently developing new computer designs. 

Mr Hurd referred directly to Supratech’s forthcoming product, the Torc, while addressing the media: 

“There’s a reason Herculean has never explored the concept of wearable devices – it’s a ridiculous idea! I bet a million credits that those fragile gizmos will break, or their holograms will start glitching, the moment you turn them on.” 

“If you want a reliable piece of tech, you need the Duradrive. Believe me, our device will keep on working whatever you throw at it…and even if you throw it.” 

When invited to comment, Supratech CEO Scorpio DeVorrow responded: 

“It’s regrettable that those with a clear vision of the future are often denigrated by individuals of limited imagination. We offer an elegant and revolutionary approach to personal computing – not just a rubber brick with a screen. I’m sure customers will make the intelligent choice.” 

Prototypes for both the Torc and the Duradrive will be unveiled at the Rackham Ultratech Expo on Wednesday the 3rd of October.
