:PROPERTIES:
:ID:       2d958757-7d66-4e92-9274-c1fce54e9bbc
:END:
#+title: Victoria Wolf VI and Commodore Stone launch Operation Augeas
#+filetags: :3301:Federation:Alliance:galnet:

* Victoria Wolf VI and Commodore Stone launch Operation Augeas

/23 Jul 3301/

Victoria Wolf VI and Commodore Stone launch Operation Augeas 
 
In a joint press conference, Victoria Wolf VI, First Merchantress of Wolf 406 Transport Co, and Commodore Helena Stone of the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] have announced the launch of Operation Augeas. This is a campaign to rid BD-22 3573 of criminal elements troubling local miners and traders. The Federation has acted swiftly after receiving the results of the investigations led by Commodore Stone. The local absolutistic factions, however, need to be dealt with more bluntly. 

Wolf and Stone, who besides their main responsibilities also have seats on the board of the Alliance Elite Diplomatic Corps, explained that they have secured the funds to pay out a bonus for all bounties cashed in Planck Orbital. 

Stone was eager to point out that this is not a military operation. The ADF will observe the situation and only intervene in case of escalation as “the system does not fall under the jurisdiction of the Alliance”.
