:PROPERTIES:
:ID:       c6e70c80-8782-4cbb-a5f3-b54ca2c1a148
:END:
#+title: A Warning from the Imperator
#+filetags: :Empire:Federation:Thargoid:3304:galnet:

* A Warning from the Imperator

/09 Nov 3304/

The isolationist group Nova Imperium has broadcast a message to Imperial citizens via public media. 

The organisation’s leader, known only as the Imperator, said: 

“Imperial citizens, your ruler’s weakness has put you in great danger. If we are to survive the Thargoid onslaught, we must sever ties with the Federation and other, inferior powers, and concentrate on protecting our own systems.” 

“I call upon those who care about their Imperial birthright to support Nova Imperium. We vow to restore the Empire’s purity and strength, and to lead it into a glorious future.” 

Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] responded with the following comment: 

“These extremists and their seditious agenda are not worthy of attention. So far we have been lenient with them, but this so-called Imperator would be wise not to test our patience any further.”
