:PROPERTIES:
:ID:       b62347bf-3053-4a6a-877d-5da7bcdc8210
:END:
#+title: Superpowers Compete over [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s Future
#+filetags: :Federation:Empire:galnet:

* Superpowers Compete over [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s Future

/18 Nov 3305/

The Empire and the Federation have announced rival initiatives to provide a new home for the crew of the generation ship [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]. 

During the aid appeal by Upaniklis Vision Incorporated, engineering experts confirmed that the ancient vessel can no longer meet the colony’s needs. While the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] was designed for long-term habitation, it lacks adequate facilities for the current population levels. 

After lengthy discussion, the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s leaders have reluctantly decided to abandon the vessel. But the ship’s captain, Jonathon Forester, has insisted that its population remain together in one location. 

The Empire has vowed to help the colonists complete the ship’s original mission by establishing a planetside home. Senator Ava Cornelius summarised the campaign: 

“After generations in an artificial environment, we want to reward these travellers with a world to call their own, fulfilling their destiny after a millennium of adventure. Contemporary agricultural techniques will enable them to become a self-sustaining colony with full Imperial support.” 

The Federation has taken a different approach, offering to create an outpost where the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s spacefaring traditions can continue. This was outlined by Congressman Harlan Turk: 

“These people have the inalienable right to continue their current way of life. A modern outpost will offer vastly superior amenities while allowing their culture to remain intact, with facilities for new trade relationships within Federal market guidelines.” 

Both superpowers have asked the galactic community to support their campaigns. Pilots can deliver polymers, CMM composites, titanium, beryllium and thallium to either of the megaships in the Upaniklis system: The Lucent Embrace for the Empire or Keller’s Resolve for the Federation. 

The initiative is scheduled to run from the 18th to the 26th of November 3305. If the final targets are met earlier than planned, the campaign will end immediately.
