:PROPERTIES:
:ID:       5bc95a8f-2bda-447a-a0b2-99395649699d
:END:
#+title: Secret Research Outpost Attacked
#+filetags: :Federation:galnet:

* Secret Research Outpost Attacked

/08 Feb 3305/

A Federal Navy vessel has reported the discovery of an unregistered outpost with all occupants murdered, following a response to an automatic distress signal. 

The incident is being investigated by the Federal Intelligence Agency. Senior Agent [[id:1900b0bf-bf32-4102-8cba-e9f2143ebedc][Rochelle Karim]] made the following statement: 

“This remote lunar base was designed to prevent detection, and yet it has been located and invaded by unknown forces who chose to gun down its inhabitants. It appears access codes were used to bypass security systems, as there are no signs of forced entry.” 

“Initial findings suggest the outpost was dedicated to advanced nuclear research. This may have been a targeted attack in order to steal a power source, a weapon, or valuable data.”  

“We are conducting a thorough examination of the site, and expect to learn more soon.”
