:PROPERTIES:
:ID:       3e61c364-81e5-4d52-bcc3-6f132581b57f
:END:
#+title: Alliance Bales Out Lakon Spaceways
#+filetags: :3307:Federation:Alliance:galnet:

* Alliance Bales Out [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]]

/16 Feb 3307/

The Alliance Assembly has approved purchasing a majority sharehold in [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]], gaining partial ownership of the shipbuilding company. 

An acquisition attempt by Federal corporation [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] was recently revoked due to illegal practices by its former CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]]. The Alliance has now rescued Lakon from possible insolvency, using government funding to buy shares and increase investment. 

[[id:321b3694-38ea-481e-9899-77b5cb951f14][Naomi Landseer]], the reinstated chairperson of Lakon’s board of directors, announced: 

“We welcome becoming closer partners with the Alliance, which we see as a natural progression following successful collaboration on past projects. I’m pleased to inform customers that the manufacture of Lakon vessels will continue uninterrupted.” 

Although some Assembly members voted against the decision, including election candidate [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]], there is broad public and industry approval. The Council of Admirals has expressed gratitude that a key defence contractor will not be controlled by another superpower or corporation. 

Much of Lakon’s personnel and resources will migrate to Alliance space, although its range of ships will remain available for purchase across the galaxy. Plans to construct a new headquarters for [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] within the [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] system are well underway.
