:PROPERTIES:
:ID:       8de67b1f-8e6d-45be-9dc4-82aa6ce979f3
:END:
#+title: Meta-Alloys Reportedly Growing Scarce
#+filetags: :galnet:

* Meta-Alloys Reportedly Growing Scarce

/04 Jul 3305/

Aegis Research has issued a statement amid growing concerns that meta-alloy harvests in the Pleiades Nebula have slowed dramatically. A number of sources claim that Thargoid barnacle sites have recently ceased producing materials. 

The situation was addressed by Professor Alba Tesreau of Aegis Research: 

“Thargoid structures remain poorly understood, so we can only theorise why the barnacles in most Pleiades systems have grown barren. Our leading hypothesis is that these sites have been over-exploited in recent years, and humanity has simply exhausted this resource.” 

“What is certain is that meta-alloys are both a valuable commodity and a vital component of anti-xeno technology. It is of paramount importance that we maintain the supply of this material.” 

“Therefore, Aegis Research is spearheading an initiative to identify an alternative source. We ask the galactic community to support us by providing exploration data, in the hope this leads us to undiscovered barnacle sites.” 

Independent pilots who wish to participate can do so by handing in survey scans at The Oracle in the Delphi system between the 4th and the 10th of July.
