:PROPERTIES:
:ID:       6ea46bb6-5408-47e8-abde-8b0a93b24d0f
:END:
#+title: Hadrian Duval Refutes NMLA Allegations
#+filetags: :galnet:

* Hadrian Duval Refutes NMLA Allegations

/28 Apr 3307/

ACT has confirmed receiving evidence that NMLA attacks were orchestrated by Imperator Hadrian Augustus Duval, who immediately denied the claim. 

Landgrave Delacroix of the Neo-Marlinist Order of Mudhrid provided details to ACT that the isolationist group Nova Imperium is at the heart of the NMLA. In response, Hadrian Duval made this statement: 

“These accusations are completely false. Our political stance is the exact opposite of Marlinism, since we believe in restoring the Empire’s traditions. Nova Imperium forces even fought against the terrorists in Mudhrid, as required by the Treaty of Paresa.” 

“As for Lady Astrid being a ‘top NMLA agent’, my wife has been a loyal Imperial Commander since she first piloted a ship.” 

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] has publicly decried the allegation and offered support to Hadrian Duval. However, Senator Zemina Torval told the Senate: 

“Should we be surprised that an extremist organisation performs extreme acts? That this arrogant boy who declares himself ‘Imperator’ should turn to violent rebellion once again? Enemies of the Empire must be punished, even those with Duval blood.” 

ACT is fully investigating the Landgrave’s evidence and has asked for patience, despite urgent demands for action from the Alliance, Empire and Federation.
