:PROPERTIES:
:ID:       6183ccae-9705-49f9-88ff-afe97f55f45a
:END:
#+title: Marlinist Colonies Receive Starport Resources
#+filetags: :galnet:

* Marlinist Colonies Receive Starport Resources

/21 Apr 3308/

*Pilots’ Federation ALERT* 

The construction of new Marlinist starports has begun after materials were delivered to the HIP 22550 system. 

Enough shipments of aluminium, computer components, power generators and titanium were received at Stillman Hub to facilitate the building of 2 orbital stations. These are expected to become operational by the 5th of May 3308. 

The campaign’s conclusion was marked by a statement from First Minister Octavia Volkov: 

“Not for the first time in our turbulent history, we are indebted to all pilots who have shown support for the Marlinist Colonies. With these additional starports, we can increase local commerce and contribute to the wider economy.” 

“It is my sincere hope that our handful of systems will one day form the nucleus of a Marlinist Republic, which can peacefully co-exist alongside our Imperial cousins.” 

The Free Marlinists of Carinae faction is now rewarding all pilots who took part in this initiative at Stillman Hub in the HIP 22550 system. 

In related news, Prime Consul Kayode Tau has been invited to establish an office of the Marlinist Consulate on Capitol. This is being widely viewed as a sign of increased diplomatic tolerance from the Emperor.
