:PROPERTIES:
:ID:       639ccb9a-378d-428d-89cb-04f73a561e01
:END:
#+title: Smuggling on the Rise in Conflict-Strewn Pegasi Sector
#+filetags: :3301:galnet:

* Smuggling on the Rise in Conflict-Strewn Pegasi Sector

/31 Jul 3301/

Smuggling on the Rise in Conflict-Strewn Pegasi Sector 
 
"Let's just say I'm not flying a small ship anymore!" laughed one Commander, pledged to the Kumo Crew, when asked about the ongoing conflict in the Pegasi sector. "We all know that these Imperial types have been flying around and ransacking ships in our space, but what have they actually achieved? Archon Delaine has consistently shown us that, under his leadership, we can repel any fleet and make an absurd number of credits in the process. Who is really losing this fight?" 

It is certainly hard to argue with the Commander’s logic. The combined Imperial fleets have continually undermined Kumo Crew territory, but they are yet to make any significant headway into smuggler-controlled space. Reports indicate that illegal contraband has risen at alarming rates since the conflict began, and an unusually large quantity of credits has made its way into Kumo Crew space from their aggressors' territory. 

When asked where these seemingly never-ending credits were flowing from, the Commander had this to say: "I'm a supplier of goods, some legal and some...not-so legal. People don't care about a line in the sand – they want their trinkets and toys. War is good for business, and business is good." 

With no end in sight, it certainly seems one group will be making the most of the situation while it lasts. 

Commander Shadewarlock
