:PROPERTIES:
:ID:       50ad3377-d30c-4ee5-9226-a0e86b4a4676
:END:
#+title: Community Goal: The Battle for Jotunheim
#+filetags: :3303:galnet:

* Community Goal: The Battle for Jotunheim

/02 Jun 3303/

Recent reports from Jotunheim indicate that the Autocracy of Jotunheim, an Imperial-aligned organisation, has entered the system with a remit to bring it under Imperial control. 

Regional authorities have opposed the incursion, and have authorised the Revolutionary Jotunheim Resistance to drive the Autocracy of Jotunheim from the system. The Revolutionary Jotunheim Resistance has also issued a call to independent combat pilots for support, promising to reward those who lend their aid. The Autocracy of Jotunheim has issued a similar plea. 

Meanwhile, peace activist [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] has surprised commentators by placing an open order for performance enhancers, armour and military grade fabrics, which she has pledged to donate to the Revolutionary Jotunheim Resistance in support of its operation. The Yum Kamcabi Purple Life Industry is coordinating Halsey’s appeal. 

Anticipating the furore her decision would cause, Halsey released the following statement: 

“I know I will be criticised for intervening in this conflict. But if those who oppose this war believe it can be stopped through peaceful protest alone, they are mistaken. If we do not help the people of Jotunheim, they will lose their homeland. We cannot stand idly by.” 

All three campaigns begin on the 1st of June 3303 and will run for one week. If any of the factions involved meets its targets earlier than planned, its campaign will end immediately.
