:PROPERTIES:
:ID:       a6dfd201-9000-47ab-83b4-ba6440ed7fd7
:END:
#+title: Core Dynamics Bids to Purchase Lakon Spaceways
#+filetags: :galnet:

* Core Dynamics Bids to Purchase Lakon Spaceways

/24 Nov 3306/

An official bid for complete ownership of Lakon Spaceways has been made by Core Dynamics, a major shipbuilding corporation in the Federation. 

The announcement caused ripples in the manufacturing sector, particularly as Lakon has been in partnership with [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] for several years. 

The newsfeed Sol Today featured a statement by Jupiter Rochester, the CEO of Core Dynamics: 

“Lakon Spaceways has made a name for itself with its practical and well-respected ship designs – the workhorses of the galaxy. Core Dynamics can help the company reach greater heights, and be even more successful.” 

“This can only be a positive move for both corporations. As with our acquisition of Vodel last year, Lakon will retain its talented engineers and production facilities while operating under our guidance.” 

There has been no response yet from the board of directors at Lakon Spaceways. Some industry specialists have speculated that the company may have financial difficulties, after investing heavily in [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Chieftain and its sister ships. 

Questions have been raised in [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Assembly about the legality of inter-superpower corporate mergers. However, neither the Federal Commerce Authority nor the Independent Commission for Market Equality have disapproved of the proposal.
