:PROPERTIES:
:ID:       a64918ae-096c-454f-bdd7-310525fb6583
:END:
#+title: President Misses Meeting
#+filetags: :galnet:

* President Misses Meeting

/26 May 3301/

Reports coming in from Saga indicate that the President has missed her scheduled meeting with delegates aboard Zudov Terminal. Maisy Stevenson, the leader of the Saga Republic Party, expressed her concern to GalNet in the following statement: 

“We were expecting Starflight One to arrive a little under 38 hours ago. An escort was sent to meet Starflight One at the prearranged location, but the ship simply didn’t appear. We informed Mars and were told that the President had decided to take a last-minute detour.” 

“I understand the President’s time is precious, but it would have been nice to get a little bit of advance notice. The people of Saga spent a not inconsiderable amount of time and credits preparing to greet the President, and now their hard work appears to have gone to waste. I do hope that the President manages to find time for us in her seemingly busy schedule. I would hate to think that the people of Saga had in some way been snubbed by Halsey.”
