:PROPERTIES:
:ID:       54665a8e-9e01-43cb-94a7-dc7e95e20fac
:END:
#+title: Galactic News: Halsey's Campaign Concludes
#+filetags: :3303:galnet:

* Galactic News: Halsey's Campaign Concludes

/06 Apr 3303/

Former Federal president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] has announced that her campaign to provide relief for those at Dirichlet Orbital has been a resounding success. Hundreds of pilots supported the campaign by eliminating agitators in Yum Kamcabi and delivering supplies to the starport. 

As the campaign drew to a close, [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] released a statement: 

"This was a huge humanitarian effort on behalf of thousands of refugees caught in the crossfire of war. I cannot thank the contributing pilots enough. I know they have the gratitude of every man, woman and child at Dirichlet Orbital." 

Pilots who contributed to the initiative can now collect their rewards from Dirichlet Orbital in the Yum Kamcabi system.
