:PROPERTIES:
:ID:       4337ce11-0a99-4f1e-87b3-b66ccf4de517
:END:
#+title: Community Goal: Further Superpower Expansion
#+filetags: :3303:galnet:

* Community Goal: Further Superpower Expansion

/16 Jun 3303/

As the Empire and Federation continue to consolidate their presence in the Pleiades star cluster, both superpowers have announced new expansion initiatives centred in the region. 

The Empire has declared its intention to bolster its Navy with a new Well-class Carrier, one of the largest vessels of its kind, while the Federation has announced plans to establish an asteroid base among the rings of HIP 17692 A4 in the HIP 17692 system. 

Both superpowers have placed open orders for construction materials, promising to reward those who support their respective campaigns. The Merope Expeditionary Fleet has been authorised to coordinate the Imperial campaign, while the Pleiades Resource Enterprise has agreed to oversee the Federal initiative. 

Both campaign begin on the 15th of June 3303 and will run for one week. If either superpower meets its targets earlier than planned, its campaign will end immediately.
