:PROPERTIES:
:ID:       42cce986-d3ac-45b1-843a-6b7f8d66e85a
:END:
#+title: Winters: ‘Federation Must Protect Independents’
#+filetags: :Thargoid:Federation:galnet:

* Winters: ‘Federation Must Protect Independents’

/26 Dec 3308/

Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] has called for the Federal Navy to help defend independent systems being invaded by the Thargoids. 

She outlined her viewpoint during an interview with the Federal Free Press: 

“The Thargoid fleets emerging from the Maelstroms have inflicted anguish and loss on millions. Our military forces have responded magnificently, and continue to fight hard against appalling odds. But while they are saving lives in Federal-aligned systems, independent systems are left to suffer.” 

“Surely this cannot be right? These are our neighbours, our trading partners, our historic cousins. Their populations cry out for help, and the mighty Federal Navy chooses to ignore them, claiming orders to prioritise saving our own. Is that who we are now? No better than the Empire?” 

“I have argued in Congress that we have a duty of responsibility to protect any independent systems lacking the ability to defend themselves from Thargoid attacks. The Federal Navy’s resources are finite, I understand that. But we are fighting to determine the future of the human race. We lack proof that the Thargoids have any concept of our politics, borders or allegiances. Why would they care which systems claim allegiance to whom? Every one of us is a target.” 

“And for those whose hearts are hardened to the suffering of others, think on this: the threat is moving closer each day. Leaving non-Federal factions to fend for themselves – and most likely become conquered – will only hasten the Thargoids’ advance. Before long, nowhere within the Federation will be safe. We will all pay the price for such callousness.”
