:PROPERTIES:
:ID:       b92c8f5b-d6e0-4c21-9d80-de8566ea48a8
:END:
#+title: Freelance Report: Taskforce Athena Locks Down Segovan
#+filetags: :Federation:3302:galnet:

* Freelance Report: Taskforce Athena Locks Down Segovan

/11 Jul 3302/

In a move likely to further inflame relations between the superpowers, a coalition of Empire-aligned Commanders has declared the Segovan system a no-fly zone. Ramsbottom Hub, the site of an ongoing Federation construction project, has been placed in security lockdown, and traders have been advised that services are currently unavailable. 

Commander Kyrthak, a spokesman for Taskforce Athena, the coalition imposing the no-fly zone, made the following statement: 

"The actions of the Future of Segovan represent an unbridled attempt to project force into the Pleiades and further exploit the region's Unknown Artefacts and meta-alloys. Taskforce Athena is actively combating Federal security services in order to halt construction of these new Federal outposts. If the Federation continues down this path, it will cost them dearly." 

The Federation has placed heavy bounties on the offending Commanders. 

Commander Corrigendum
