:PROPERTIES:
:ID:       8decef3c-7f9c-4c5b-a0a3-a467aeece20d
:END:
#+title: Federal System Resists Imperial Takeover
#+filetags: :galnet:

* Federal System Resists Imperial Takeover

/12 Nov 3306/

*Pilots Federation ALERT* 

The Federation has successfully maintained control of the LTT 1935 system, following a battle against local Imperial forces. The conflict was caused by an Imperial investigation that traced deliveries of bomb-making materials from this system to an NMLA workshop.  

Colonel Ernest Harris of the LTT 1935 Confederacy stated:  

“The LTT 1935 system remains part of the Federation, now that we have defended against the Empire’s attempt to take control. Our citizens have been saved from the indignities of Imperial interrogation.” 

“In gratitude to the Federal auxiliaries and independent pilots who helped support our freedom, rewards are now available at Wolf Port .” 

There was also a message from Captain Axel Cyprian of the L.Y.S Corp: 

“This is a serious setback in our war against the NMLA terrorists, who the Federation seem eager to protect. Nevertheless, for all those courageous pilots who flew on our behalf, we can offer generous payments from Strength of Purpose.”
