:PROPERTIES:
:ID:       80bd439d-4ea6-44c0-bab2-63866be3901e
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/5c13a0e2-4121-4bf9-89fc-53c19239c48e?resourceVersion=id%3A4933
:END:
#+title: Empire and Marlinists Prepare for Galactic Summit
#+filetags: :galnet:

* Empire and Marlinists Prepare for Galactic Summit

/12 Feb 3307/

Delegations have been formed by the Empire and the Marlinist Colonies to take part in the forthcoming diplomatic conference. 

Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] will not attend in person, but will be directly represented by Chancellor Anders Blaine. During the conference, Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] will temporarily assume chancellor duties and act as head of the Senate. 

In addition, Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] will be in attendance. They will be accompanied by experienced ambassadors from the Imperial Diplomatic Corps.  

The Marlinist Colonies have also finalised their delegation, which includes First Minister Jenna Fairfax and Minister Aaron Whyte. A spokesperson for the Marlinist Parliament said: 

“The Galactic Summit offers us an opportunity to engage with the Empire diplomatically, and we sincerely hope our voices will be heard. We also aim to establish mutually beneficial relations with other governments.” 

There is widespread speculation on how the Empire will respond to political overtures from its own ex-citizens, who were persecuted for following the democratic ideology of Marlinism. However, most societies within the Marlinist Colonies still remain culturally Imperial in nature, despite their republican governance. 

The Galactic Summit is being hosted by Sirius Corporation and will officially commence on Thursday the 25th of February 3307.
