:PROPERTIES:
:ID:       8f522a61-d764-4b92-9099-7b258845a80f
:END:
#+title: The Nevermore Not Ready for Duty
#+filetags: :3301:galnet:

* The Nevermore Not Ready for Duty

/19 Mar 3301/

Core Dynamics has been put in the deeply embarrassing position of having to further postpone the maiden voyage of the FNS Nevermore. Representatives of Core Dynamics have confirmed that this most recent delay is due to faulty sensor and turret targeting arrays.  

The faults first came to light when engineers began running the FNS Nevermore through its standard weapon diagnostic checks late last week. According to Core Dynamics, the FNS Nevermore’s weapon systems gave engineers the all clear, but upon attempting to fire on the target drone ship, the FNS Nevermore instead released a massive volley into Hudson Dock.  

The dock’s defence systems then returned fire, causing the Nevermore’s automated battle systems to kick in, resulting in an all-out fight between the two stellar titans.  

It took engineers three hours to regain control of the ship. During this time dozens of people were killed, and hundreds of millions of credits in damages were done to both structures. 

Commander Lokquine, a member of Hudson Dock’s Shipyard Union, had this to say on the matter: 

“Well honestly, what do you expect to happen when you build a ship like that out of so much Copper? I told them they should have used Gold, cheap << censored >>.”  

Core Dynamics is now looking for traders to help bring a variety of Metals to Hudson Dock to assist in the repair efforts.
