:PROPERTIES:
:ID:       657d8bb2-3fae-46c5-90f2-d0f249f02453
:END:
#+title: Origins of the Velites Squadron
#+filetags: :3301:galnet:

* Origins of the Velites Squadron

/15 Jul 3301/

Origins of the Velites Squadron 
 
The ancient proverb, “necessity is the mother of all invention,” remains true, even in 3301. 

Commander Na’Qan came from humble beginnings as a miner in distant Imperial colonies. Piracy being rife in those systems, he found himself in their sights regularly. Knowing he could not outrun them in his unshielded Type-6, he learned to elude them. Like Br’er Rabbit’s briar patch, the asteroid fields offered him shelter. He learned to manoeuvre silently among the chaotic rocks and metals. 

When war broke out in the Pancienses system, Na’Qan joined the fray. He recounted being interdicted by three Fer-de-Lances, and noticed they could not get weapons lock on his craft. Immediately recognizing the relevance of his mining experience, Na’Qan approached his superiors with an idea. Shortly thereafter, Na’Qan began training wings for what would become the Velites Squadron. The stealthy, precision strikes of the Velites are already becoming legend. 

For his service to the Empire, Commander Na’Qan is to be awarded the Imperial Order of Merit, First Class, from Senator Arrissa Lavigny-Duval at her headquarters in Kamadhenu this weekend.
