:PROPERTIES:
:ID:       bb54f2d1-1bea-40b5-a9b5-4e7ed6b9f63e
:END:
#+title: Federation Targets Narcotics Syndicate
#+filetags: :galnet:

* Federation Targets Narcotics Syndicate

/06 Jul 3308/

The Federal Intelligence Agency has launched a multi-system crackdown against the organised crime network known as Red Family. 

Synchronised raids are currently taking place in over a dozen systems across Federal space. Multiple ships, properties and manufacturing plants connected to Red Family’s illegal operations are being seized. 

FIA Deputy Director Bethany Blake provided a statement to The Federal Times: 

“For decades the Red Family cartel has trafficked colossal quantities of dangerous drugs to our citizens, leaving a trail of death and misery behind them. The FIA dealt a severe blow to the syndicate in 3305, but its kingpin Oberon Church escaped justice and remains one of the most wanted criminals in the Federation.” 

“This current operation was only possible thanks to the Proactive Detection Bureau. Our algorithms intercepted key messages that identified Red Family’s allies within local security forces and legal businesses.” 

“Field agents are now making mass arrests, despite armed resistance at many locations. This time we will locate Church and take him into custody, which will cause his organisation to crumble.” 

The Proactive Detection Bureau monitors all communications within the Federation to identify illegal activity and prevent terrorism. It was established in 3307 when new public surveillance laws were passed in the wake of large-scale attacks by the NMLA.
