:PROPERTIES:
:ID:       91736f5e-5de8-4bcc-8e29-ec115e366aaa
:END:
#+title: Further Migration to Witch Head Nebula
#+filetags: :galnet:

* Further Migration to Witch Head Nebula

/06 Aug 3305/

The human enclave in the Witch Head Nebula has attracted thousands of migrants looking for a fresh start.  

One of those heading to the area is Chloe Sedesi, a former apprentice of Professor Ishmael Palin. She gave an interview to Leon Banerjee for Vox Galactica:  

“I’ve been working with the professor for years now, and he’s taught me so much about rejigging modules to improve their function. He might come across as a bit serious, but Ishmael’s actually a total sweetheart. Although he’ll probably frown at me for saying that.” 

“I’d been thinking about striking out on my own for a while, and the creation of the Witch Head enclave seemed like a good opportunity to do just that. All those independent pilots have done so much for the new enclave, I thought it’d be good to offer a little support.” 

Sedesi is currently overseeing the installation of a facility at Cinder Dock in Witch Head Sector DL-Y d17, which will offer engineering services similar to those previously offered at the Palin Research Centre. 

It has also been confirmed that a tech broker and a material trader will be offering their services in the Witch Head Nebula, once the region’s starports have been returned to full functionality.
