:PROPERTIES:
:ID:       2a4390c3-4771-4236-94c7-5079fd1bdcc3
:END:
#+title: Crashed Ship of Missing ACT Agent Located
#+filetags: :galnet:

* Crashed Ship of Missing ACT Agent Located

/31 Mar 3307/

*Pilots Federation ALERT* 

The vessel of Captain Niamh Seutonia, who vanished on an anti-NMLA mission, has been found with its crew dead. 

Following a widespread search by independent pilots, Commander TheRealFlame was the first to discover the wreckage of the Valkyrie in the Trianguli sector GW-W B1-0 system. It was apparent that the ship crashed after sustaining weapons fire, and that all crewmembers died on impact. 

ACT co-leader Senior Agent Tanya Ramirez gave this statement to the media: 

“We owe a debt to every pilot who joined our efforts to find the Valkyrie. It’s an emotional blow for us to lose one of ACT’s guiding lights, along with her courageous team.” 

“However, Captain Seutonia managed to secure her mission logs moments before the ship’s destruction. This allowed vital information to be recovered.” 

“We now have evidence confirming that a Neo-Marlinist faction in the Mudhrid system was directly involved in the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] starport bombings. We have shared our findings with Imperial authorities, and the Order of Mudhrid is being investigated.” 

Captain Niamh Seutonia rose to prominence as part of the tri-superpower taskforce that eliminated the League of Reparation in 3304. The Imperial Internal Security Service confirmed that she will be posthumously awarded the Achenar Service Cross.
