:PROPERTIES:
:ID:       b4d5c99b-05ef-4592-b77c-5b6601f37e97
:END:
#+title: Galactic News: Previously Unseen Thargoid Ships in Electra
#+filetags: :Federation:Thargoid:3303:galnet:

* Galactic News: Previously Unseen Thargoid Ships in Electra

/16 Nov 3303/

Recent reports indicate that a new kind of [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] vessel has been encountered in the Electra system. The previously unseen ships were encountered by independent pilots investigating the wreckage of the Aida, a Hogan-class cargo vessel that was apparently attacked by [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]].

The Thargoid ship has been classified as a ‘Basilisk’ Interceptor by the [[id:131aabdf-0ed8-4ce2-beec-94c77a8c41d2][Pilots Federation]].

System security forces in Electra offered the following assessment:

“The Basilisk hits harder than the Cyclops, and it’s tougher too. It also deploys a denser swarm of Thargons. Interestingly, all the Basilisks we’ve encountered are heavily scarred, almost as if they’ve been around longer, taken more punishment.”

Authorities in Electra have warned those living in the system to exercise extreme caution, and not to engage Thargoid ships under any circumstances.
