:PROPERTIES:
:ID:       62f7ff04-980d-4b1b-bdc8-039a7bdb77f1
:END:
#+title: Soontill Relics Test Results Queried
#+filetags: :3301:galnet:

* Soontill Relics Test Results Queried

/18 May 3301/

As further alien artefacts claiming to be from Soontill are being sold on the open market, the results of the initial scientific tests have been revealed. 

“We were looking for key markers,” explains Chief Xeno-Chemist Lyran Betar.  “Elemental make up, crystalline structure, anything that indicates it could have originated from human hand.” 

And the results? Inconclusive. The research team’s results clearly state that no known human technology could have created the relics, yet they do not quite align with known Thargoid materials. Whatever they are, they are indeed very old, with isotopic dating indicating that they could well be tens of thousands of years old. 

Jean Molyneaux, a historian from France, Earth, suggests we look back at our own past to determine the home of these relics.  “Imagine an alien travelling back two thousand years into mankind’s past.  The varied culture, arts and building materials of the Aztecs, Greeks, the Shang dynasty, what have you, the alien could think they were all different species, if that was his way of thinking…” 

The community seems wary of awarding these artefacts any title yet, given the fifty years of false hopes since Soontill was first mentioned by the Thargoids. However, reports indicate that these relics have now arrived at labs on both Mars and Capitol for further testing, and with any luck, we may soon finally agree on what these relics are, or are not.
