:PROPERTIES:
:ID:       59f08bf6-d556-4ca2-a6e5-defb34e073ed
:END:
#+title: Theta Seven Traced to Panjabell System
#+filetags: :galnet:

* [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] Traced to Panjabell System

/16 Nov 3307/

*Pilots’ Federation ALERT* 

A decrypted message suggests that the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] leader [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] avoided capture by infiltrating the Far God cult. 

ACT publicly requested help to decode a message received by Theta Group, the bomb-making engineers of the NMLA. The cipher key was cracked and the decoded message submitted by Commander Therion Cygni. It revealed that [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] and his closest aides fled to the Panjabell system on the 31st of July. 

Captain Milo Castile, one of ACT’s co-leaders, provided an update: 

“Our theory is that [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] and his crew were travelling undercover as Far God worshippers, who were gathering in the Panjabell system in huge numbers at that time. Since all members of this religious order renounce their past identities, this would have helped the terrorists to avoid detection.” 

“The Pleiades Concordat and other factions in Panjabell are cooperating with our investigation. But it seems likely that [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] is currently hiding aboard one of the three Far God megaships that were launched from the system on the 6th of August.” 

“ACT agents have attempted to contact the Perdition, Sacrosanct and Testament megaships to alert them of the danger. Unfortunately the cultists consider themselves to be on a sacred pilgrimage that cannot be impeded, and that their vessels are ‘sanctuaries from further persecution by hostile security services’.”
