:PROPERTIES:
:ID:       4256db84-316e-4133-ab60-cf0dd20ad072
:END:
#+title: Operation Tomahawk Aims to Rid Lave of CODE Threat
#+filetags: :3301:Alliance:galnet:

* Operation Tomahawk Aims to Rid [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] of CODE Threat

/03 Apr 3301/

As the war in [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] continues between CODE and Cosmic State, reports have emerged to suggest that Cosmic State have chosen Adle's Armada as unlikely allies in what's being called Operation Tomahawk. 

The accusation is that CODE are charging traders and others passers-by for "travel passes" in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] system, which are valid only for a set period, and will provide protection against CODE attacks. 

These reports would seem to indicate that no visitor to [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] is safe unless a travel pass has been purchased from CODE. It is not clear at this stage what the Alliance reaction is to this policy, but it seems that as long as the funds aren't being channelled into the Lavian economy, they are unlikely to take a high view of this practice. 

Galnet reached out to both CODE and Cosmic State for comment, and although no word has been received from CODE, Cosmic State asserted that CMDRs Silk and Kudach were heading Operation Tomahawk, aiming to free [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]], and now potentially Leesti also, from the perceived CODE threat.
