:PROPERTIES:
:ID:       37323003-012a-4beb-97ac-2291dfa7b811
:END:
#+title: Manticore
#+filetags: :Corporation:
* Manticore

#+begin_quote

  "Finish the fight."

  --- Source
#+end_quote

Established in 2990, Manticore was for many years associated solely with
ship-based technology, making a name for itself as a manufacturer of
cannons, missiles and limpets. In 3303, the company widened its remit to
encompass personal defence. When asked about the change, company
director Karisa Neuman cited "a clear gap in the market for quality
plasma and laser weaponry" as the motivator.

The move attracted criticism from competitors Takada and Kinematic
Armaments, who suggested that Manticore was rushing to enter a market it
did not fully understand. Neuman responded by poaching superstar
designer Elin Yu from Kinematic Armaments.

The development led to a jump in Manticore share prices as commentators
speculated about the impact that Yu -- whose work at Kinematic produced
some of the corporation's fiercest weaponry -- would have on Manticore.

Manticore soon released a line-up of personal weaponry characterised by
punchy handling and substantial damage output. Critics hailed the
release as 'the future of plasma weaponry,' giving both investors and
consumers ample hope for the company's future.

Since then, Manticore has cemented its presence in the personal weapon
market and acquired a reputation for shrewd decision making. The recent,
successful launch of the company's first combat suit design has
demonstrated its potential for further growth. Manticore may choose to
present itself as guided by little more than instinct and good fortune,
but in reality it is as tactical -- and, when necessary, as ruthless --
as any of its rivals.


