:PROPERTIES:
:ID:       00e74832-8b0f-43d1-b755-0b54716378cd
:END:
#+title: Taranis Unleashes Thargoid Invasion Fleets
#+filetags: :galnet:

* Taranis Unleashes Thargoid Invasion Fleets

/29 Nov 3308/

*Pilots’ Federation ALERT* 

The Taranis anomaly has arrived in Hyades Sector FB-N b7-6, triggering a ferocious wave of Thargoid attacks in the region. 

Multiple inhabited systems are experiencing wide-scale invasions by countless numbers of Thargoid vessels, with casualties expected to number millions in the coming days. Several systems have already reported a complete loss of human control, with ports abandoned amid heavy losses.  

The Alliance Defence Force and Federal Navy have responded by sending capital ships, which will support independent pilots and anti-xeno squadrons. Neither superpower has entered the Hyades Sector FB-N b7-6 system, from which the Thargoid fleets seem to be emanating. 

There have been conflicting descriptions of the rogue signal source itself, which finally slowed to a halt after weeks of faster-than-light travel. Dr Remy Leroux, a xenologist working for Professor Palin, transmitted a garbled report describing Taranis as “not a single object but a colossal swirling maelstrom of some kind”, before all contact was lost. 

These initial reports have not been verified, and many authorities consider them to be unreliable or exaggerated. However, warnings have been issued that the Hyades Sector FB-N b7-6 system is extremely dangerous and should be avoided at all costs. 

Speaking to The Alliance Tribune, Admiral Rachel Ziegler remarked: “Our focus at present is on defending the populated systems from swarms of highly aggressive Thargoids. Whatever this ‘maelstrom’ actually is, it’s clearly been sent with the purpose of eradicating human influence in the region.”
