:PROPERTIES:
:ID:       13a9fd12-f29a-4e87-a742-313586573bfb
:END:
#+title: [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] Cartel Raids Successful
#+filetags: :galnet:

* [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] Cartel Raids Successful

/19 Jul 3305/

The [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] cartel has suffered enormous losses following a series of strikes carried out by the Federal Intelligence Agency. 

Crime correspondent Ethan Takahashi summarised his report in [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“In a coordinated operation spanning multiple systems, FIA troops raided hidden [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] bases and manufacturing plants. Dozens of cartel members were killed in combat and thousands more arrested, while vast amounts of illegal substances were seized.” 

The narcotics kingpin Oberon Church spent decades establishing his empire, but with such catastrophic losses it has been virtually dismantled. Members of Federal Congress have congratulated the FIA for ‘removing this blight on Federal society’. 

Executive Agent Viola Trask suggested that “this success was only possible due to the detailed information volunteered by Jan Sandoval, one of the [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]]’s founders.” It is widely assumed that Church’s arrest will follow soon, effectively eliminating the cartel.
