:PROPERTIES:
:ID:       2a1a67b2-2d30-4034-9c1d-92b8d5f33e37
:END:
#+title: An Audience with the Preceptor
#+filetags: :Thargoid:galnet:

* An Audience with the Preceptor

/23 Jun 3309/

The Order of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] has reached out to [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]], offering information on the possible fate of the Dedicant. 

The megaship was due to transport members of the True Chapters sect from the Popontia system to the Alliance-governed Mullag system, but made a hyperspace jump ahead of schedule and disappeared. The Federal Intelligence Agency has interrogated cult members still waiting in Federal prison cells, but reportedly obtained no useful information. 

Days later, Aegis was directly contacted by chapters of the Order within independent space. They volunteered to discuss the Dedicant but only with [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]], whom they refer to as ‘the Preceptor’ for her ability to interpret to the Thargoid hive mind. 

After meeting [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] representatives at a secure location, [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]] made a public statement: 

“The meeting wasn’t as productive as the FIA hoped. I asked the cultists for information, but they wouldn’t stop jabbering about their religion. They wanted me to share ‘divine commandments’ from the Titans, and kept asking when the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] would arrive to cleanse the galaxy. I’ll always be grateful to these people for rescuing me a few months ago, but it’s hard work convincing them I’m not a prophet.” 

“During the brief period I got them talking about the Dedicant, they admitted knowing nothing about a True Chapters scheme to retake the megaship. And they certainly have no clue where it is now. The meeting was mostly a waste of time.” 

“One thing was possibly useful, though. Apparently, the interiors of [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] megaships are remodelled to make them ‘deliberately confusing for heretics’. Corridors like insect tunnels, rooms turned into hive cells – that sort of thing. When I told them the FIA had already examined the ship’s layout while it was in custody, one cultist argued they hadn’t found the ‘secret doors’. They explained how [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] failed to get the hyperdrive working after he gained control of the Sacrosanct, and claimed the crew of that ship rigged the thing with traps. Maybe that’s how the FIA agents lost control of the Dedicant.”
