:PROPERTIES:
:ID:       8c1a515a-798b-4b0b-aa14-5d81d8786e99
:END:
#+title: Galactic News: Problems at MetaDrive?
#+filetags: :3302:galnet:

* Galactic News: Problems at MetaDrive?

/27 Aug 3302/

Independent auditor BigSix has reported various anomalies in the accounts of MetaDrive Inc., a company based in the Chi Orionis system specialising in hyperdrive research. 

Reviewing the company's financial records, assessors found evidence of a series of payments to undisclosed suppliers but none of the corresponding checks and balances. 

"It's a big mess," said the senior auditor of BigSix. "The company is being placed in receivership. It needs a buyer, and quickly." 

Femi Dakarai, the chairman of MetaDrive Inc., was not available for comment. 

Following the news, shares in MetaDrive Inc. plummeted. But a short time later, Sirius Corp unexpectedly volunteered to prop up the company. 

"We've been interested in collaboration for a while," said the marketing manager of Sirius Corp's hyperdrive research division, "and were in talks over licensing MetaDrive's exciting new technology. We have no desire to see them go under."
