:PROPERTIES:
:ID:       148e19e6-1cbe-4868-9f46-d21da7ca85ad
:END:
#+title: New Thargoid Assaults in Three Systems
#+filetags: :3308:Federation:Thargoid:galnet:

* New Thargoid Assaults in Three Systems

/11 Feb 3308/

*Pilots’ Federation ALERT* 

The HIP 12314, Dan and Nauni systems have come under heavy attack by Thargoid vessels. 

Vox Galactica featured this report by freelance war correspondent [[id:139670fe-bd19-40b6-8623-cceeef01fd36][Jade Sanderlyn]]: 

“The Thargoids have been unusually aggressive in recent months, as attested by the drifting wreckages of many independent ships. When [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] repelled their forces from the [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]], [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] and [[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]] systems in December, some believed it was only a matter of time before the aliens retaliated. It appears that time has come.” 

“Although the Thargoid species is often viewed as territorial, on this occasion they have pushed further towards human space. Authorities in all three systems were unprepared for the incursions and have sent out a general call for assistance.” 

“The superpowers are still in the process of forming their anti-xeno taskforces, and thus unable to help. Fortunately, despite Aegis being officially defunct, some of its support megaships have yet to be decommissioned. These have been staffed with emergency crews and rushed into service in all three systems.” 

“As pilots race into combat once more, many must be wondering if the risks are now even greater. Have the Thargoids extended their reach into human space? Which systems might they strike at next? And is further escalation a price to be paid every time [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s superweapon is deployed?”
