:PROPERTIES:
:ID:       f51a748b-b761-4fa6-8591-258cbf9ebe50
:END:
#+title: Community Goal: Alliance Outpost Campaign
#+filetags: :Federation:Empire:Alliance:CommunityGoal:3303:galnet:

* Community Goal: Alliance Outpost Campaign

/05 May 3303/

The Alliance has announced plans to construct a new outpost in the [[id:6fee136e-381f-47a2-ba13-6d74c8798803][California Nebula]] and placed an open order for construction materials. 

An Alliance spokesperson outlined the nature of the initiative: 

“With the Federation and the Empire mired in hostility, it falls to the Alliance to pursue a more exploratory agenda. This new outpost will further that agenda by supporting our ongoing research in the [[id:6fee136e-381f-47a2-ba13-6d74c8798803][California Nebula]].” 

“The [[id:f76ba965-89ab-484f-8e67-b1996174a4a8][Turner Research Group]] has generously offered to support this initiative, allowing us to reward pilots who deliver Geological Equipment, Micro-Weave Cooling Hoses, Building Fabricators and Energy Grid Assemblies to our base of operations at [[id:b191bbd1-f2ed-4371-9aae-f17f76db44b3][Darwin Research Facility]] in the [[id:cba54e17-62e5-4dc8-be29-a425cd07e6cf][California Sector BV-Y c7]] system.” 

The campaign begins on the 4th of May 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
