:PROPERTIES:
:ID:       c11c1434-1733-4d19-8efa-3cf2428b244b
:END:
#+title: Hunt the League of Reparation
#+filetags: :Empire:Federation:3304:galnet:

* Hunt the League of Reparation

/20 Jul 3304/

A tri-superpower taskforce has launched a campaign to track down and eliminate members of terrorist group, the League of Reparation. 

Captain Niamh Seutonia of the IISS, who is a prominent member of the taskforce, made this announcement: 

“With the arrest of Riri McAllister, otherwise known as Nexus, we now hold the main coordinator of the League of Reparation in custody. Furthermore, decrypted information has revealed the location of League strongholds in two separate systems, one in Imperial and one in Federal space.” 

“We are determined to eliminate these terrorists before they can wreak any more havoc, but fully expect tough resistance. Therefore we ask the galactic community to provide support in wiping out these dangerous extremists.” 

The operation in Zibal will be coordinated by Zibal Power Co. Likewise, military action in Ienpalang will be supported by Ienpalang Corporation. 

The campaign begins on the 19th of July 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
