:PROPERTIES:
:ID:       dc8a7c09-975f-4e60-b620-b0773e4c3869
:END:
#+title: Week in Review 24 Nov 3304
#+filetags: :Federation:Empire:Alliance:3304:galnet:

* Week in Review

/24 Nov 3304/

Here are this week’s major stories. 

Admiral [[id:090377a7-402e-4f38-8bad-b9b56230a846][Frederick Yamamoto]] has been announced as the sixth member of the Alliance Council of Admirals. The position had been vacant for months after the previous appointment, Riri McAllister, was discovered to be the coordinator of terrorist group the League of Reparation. The decision has ruffled some feathers, not least because Admiral Yamamoto is a close personal friend of President [[id:8520e75f-0479-42c5-9083-f9abfbad721e][Gibson Kincaid]]. 

The Mars Tribune has been closed and its owner arrested in the wake of the spy robot scandal. The announcement was made by Detective Captain [[id:67e55dd5-7840-4133-9111-566a0008b121][Ramesh Thorne]], who was recently reinstated to, and promoted by, the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]]. Thorne assured the public that the surveillance program installed in some Achilles Corporation PA912 robots had been removed. 

In other news, the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] has responded to the revelation that members of its private fleet conducted a mercenary raid on the Meene system. [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]], CEO of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp.]] confirmed that a cabal of junior officers had orchestrated an illegal operation to gain access to Phoenix Base. The officers now face multiple charges. 

Isolationist group Nova Imperium has declared its intention to install a new Emperor. The group’s leader, recently identified as ex-navy admiral [[id:f6be5b58-fd8d-4233-8053-7ade4ca35aee][Duke Kaeso Mordanticus]] and known as the Imperator, said that the superpower had been weakened by collaborating with its enemies, and that the new Emperor would restore the glory of the Empire. 

Meanwhile, a long-standing rivalry between two factions in the Loha system has erupted into full-scale conflict. Relations were already strained when Loha Holdings accused its rivals of hijacking transport ships and murdering their crews. After the New Loha Party claimed this was a false flag operation designed to discredit them, diplomacy was replaced by weapons fire. Since neither side has an extensive fleet, both have appealed for support. 

Finally, a spokesperson for [[id:b604827a-7183-4f81-8623-191fc2173db1][Olelbis]] Holdings has announced that its appeal for commodities has reached a successful conclusion. Hundreds of pilots supported the campaign by delivering goods to Polyakov Orbital, and by eliminating agitators in Olelbis, thereby ensuring the safety of traders. 

And those are the main stories this week.
