:PROPERTIES:
:ID:       45b2683c-3c88-4dc9-8785-1fe5e5187ba5
:END:
#+title: Galactic News: Theft at Darnielle's Progress
#+filetags: :3303:galnet:

* Galactic News: Theft at Darnielle's Progress

/24 Feb 3303/

A carefully orchestrated heist, involving the theft of a large quantity of meta-alloys, has taken place at Darnielle's Progress in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system. 

Security personnel at the starport confirmed that an unidentified Cobra-class vessel was involved in the robbery. After the ship docked at the starport, the pilot and four other passengers disembarked before the ship was serviced and refuelled. 

Later, the pilot requisitioned the largest available quota of meta-alloys, whereupon the automated units inexplicably loaded it to maximum capacity. The Cobra immediately departed, breaking speed limits and ignoring hails. 

Attempts were made to track the ship, but no trace of it was found. 

Investigations are ongoing. Pilots are asked to report any sightings of a Cobra with the callsign 'lima uniform charlie'.
