:PROPERTIES:
:ID:       71f3f3e9-b763-40d5-b6ab-eb70193223b8
:END:
#+title: Delta Pavonis Hosts Political Conference
#+filetags: :3307:Federation:galnet:

* Delta Pavonis Hosts Political Conference

/17 Sep 3307/

Delegations from the Federation and the dictator [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] are meeting to determine the Delta Pavonis system’s future. 

Both are on a diplomatic mission to convince its controlling faction to either swear allegiance to [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] or become a Federal member state. Delta Pavonis was one of the original signatories of the Federal Accord in 2242, but has recently been governed by an independent autocracy. 

Yuri Grom himself is present, having arrived on the megaship Indomitable. Grom was once a respected admiral in the Federal Navy, before defecting with huge numbers of ships and followers. They established the independent EG Union, which he presides over as a military dictatorship. 

The rival delegation is led by Ambassador Delphine Dumont of the Federal Diplomatic Corps. They were transported on the Freedom’s Foundation megaship courtesy of Delta Pavonis Galactic Interstellar, which formerly controlled the system. The ambassador invited newsfeeds to witness her initial introduction to [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]], who seemed slightly taken aback by her warm greeting. 

Grand Duke Simion Petrescu, ruler of the Autocracy of Delta Pavonis, told attending journalists: 

“The conference will take place in Kessler City on Reagan’s Legacy, where our distinguished guests will enjoy our famous hospitality. I look forward to learning more about their respective proposals.” 

This is the first time that the Federation has diplomatically engaged with [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]]. Political observers noted that this tactful approach may be due to several Federal factions recently declaring independence.
