:PROPERTIES:
:ID:       4cf84552-2532-44a2-b518-3e76f214b4a7
:END:
#+title: Galactic News: Imperial Inquisition's Campaign Successful
#+filetags: :Empire:3302:galnet:

* Galactic News: Imperial Inquisition's Campaign Successful

/05 Feb 3302/

Mavia Kain, leader of the Imperial Inquisition, has announced that the group's campaign to develop the planetary outpost of i [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]a Prospect on Brestla A1 has been enthusiastically received by the galactic community. Members of the organisation were motivated to launch the campaign after becoming frustrated with i Sola Prospect's limited service options. Having received significant quantities of material, the organisation is now in a position to begin developing the outpost. A spokesperson for the group released a statement to the media: 

"Mavia Kain and the Imperial Inquisition would like to thank the galactic community for its support. Thanks to you, i [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]a Prospect will soon be the best-equipped planetary outpost in the galaxy, rivalled only by Jameson Memorial." 

Improvements to the outpost are expected to begin immediately.
