:PROPERTIES:
:ID:       27ba233b-9511-43da-b5af-968006f64810
:END:
#+title: Tributes Gathered to Honour Duval Heir
#+filetags: :galnet:

* Tributes Gathered to Honour Duval Heir

/09 Dec 3307/

*Pilots’ Federation ALERT* 

The birth of Hadrian Duval’s son has been celebrated in grand fashion in the Paresa system. 

Praetor Leo Magnus, the new leader of Nova Paresa, publicly thanked pilots for delivering Chateau De Aegaeon, HR 7221 Wheat, Indi Bourbon and Yaso Kondi Leaf to support these highly exclusive proceedings. Payment is now available from Dyson City starport.  

Political journalist Cassia Carvalho discussed the arrival of Hector Mordanticus Duval in The Imperial Herald: 

“As Emperor Hengist’s illegitimate grandson and former enemy of the state, Hadrian Duval has always been the outsider. Indeed, his newborn son’s middle name seems deliberately chosen to remind the Emperor that she ordered Hadrian’s mentor, Imperator Mordanticus, to be shot in cold blood.” 

“But over the last two years, Hadrian’s position has gradually shifted from isolationist rebel to legitimised ally. He appeals to citizens who are unhappy with a female monarch, even more so now that he has a male heir. And he remains closest to the Imperial bloodline, with most other Duval family members having been assassinated by the NMLA.” 

“Therefore, unless Arissa Lavigny-Duval or Aisling Duval produce children, it’s entirely possible that Hadrian’s child might inherit the throne. Despite only being a few days old, Hector Duval’s impact upon the Empire could be measured in centuries.”
