:PROPERTIES:
:ID:       7c1e1b7e-858b-4f59-a801-c4f9316c7623
:END:
#+title: Azimuth Claims ‘Thargoid Doomsday’ Imminent
#+filetags: :3308:Federation:Empire:Alliance:Thargoid:galnet:

* Azimuth Claims ‘Thargoid Doomsday’ Imminent

/08 Aug 3308/

*Pilots’ Federation ALERT* 

Salvation’s anti-xeno superweapon is now complete and final preparations are underway in the HIP 22460 system. 

Commodore [[id:bcaa9222-b056-41cf-9361-68dd8d3424fb][Morag Halloran]], [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]]’s military coordinator, broadcast this announcement from the Bright Sentinel megaship: 

“Salvation has confirmed that the Proteus Wave core mechanism is fully active. Calibration inside the Thargoid structure on the surface of HIP 22460 10b has successfully concluded. Power sources derived from Guardian designs are building to the required levels, and a final series of safety checks are currently underway.” 

“Upon detonation, the energy pulse generated by the Proteus Wave will cause catastrophic disruption to all Thargoid biomechanical technology within range. Every alien vessel in HIP 22460 will immediately cease to function. [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] predicts that the wide-ranging impact of the superweapon will drive all Thargoids out of the core systems. In practical terms, tomorrow will be their doomsday.” 

“This is the culmination of years of research, coupled with [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s revolutionary technology. The project could not have been realised without the military support of the Alliance, Empire and Federation. Azimuth is also grateful to those pilots who delivered vital materials and risked their lives to hold back the Thargoid fleet. Take pride in the knowledge that your courage and dedication will help bring an end to the Second Thargoid War.” 

The superpowers’ anti-xeno taskforces have sent out urgent calls for emergency support to prevent Thargoid forces from attacking the Proteus Wave site in these critical final hours.
