:PROPERTIES:
:ID:       451b9ff6-9e5b-41ec-a63b-a94ea38ff7fd
:END:
#+title: Arissa Addresses the Empire
#+filetags: :3308:Empire:galnet:

* Arissa Addresses the Empire

/26 Jan 3308/

The Imperial Senate has shared a personal message from Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]], who has been in a secure location for nearly a year. 

The brief statement was broadcast on all public channels: 

“Citizens of the Empire, be assured that your Emperor is alive and well. I regret that my temporary seclusion has lasted for so long, but I have remained in contact with the Senate during this time.” 

“I was advised to depart from Capitol when [[id:45d78e5d-27b7-48cb-97b2-012934be3180][Imperial Intelligence]] warned me about a legitimate [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] assassination attempt, and of Marlinist sympathisers within the highest levels of our government. Once the work of this loyal agency is complete, I will continue my work in leading us toward a prosperous future.” 

Eye on [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]] reported that this address was “welcomed by a relieved Empire”, adding that it was vital to “root out all Marlinist traitors”. The Imperial Herald noted that the Emperor seemed to absolve [[id:45d78e5d-27b7-48cb-97b2-012934be3180][Imperial Intelligence]] of the allegations that it was secretly enabling the NMLA. 

However, a caution was sounded by Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]]: 

“Arissa has communicated with the Senate in the same manner for months, so this changes nothing. Only a public appearance will alleviate my concerns regarding her wellbeing. I would be delighted to host a suitable event if she will accept my invitation to attend in person.”
