:PROPERTIES:
:ID:       35131488-b534-4ac6-a94a-bc84e78884f4
:END:
#+title: Thargoid Incursion Repelled in Witch Head Enclave
#+filetags: :Federation:Alliance:Thargoid:3306:galnet:

* Thargoid Incursion Repelled in Witch Head Enclave

/21 Oct 3306/

*Pilots Federation ALERT*

Thargoid forces defeated in an Alliance-controlled system within the Witch Head Nebula.

The galactic community has responded to a call for aid from the Witch Head Enclave and successfully resisted an attack by the Thargoids. The majority of the alien vessels were destroyed, forcing the remainder to retreat.

Captain Warren Lamar, head of security for the [[id:f9e96dfd-3161-46b0-a9bc-0335447c4693][Alliance Expeditionary Pact]], announced:

“Everyone in [[id:2b846add-6e61-41aa-9ad6-3bf02898e6e0][Onoros]] and our neighbouring systems owes an enormous debt to the courageous pilots who met the Thargoids in battle. The whole of the Witch Head Enclave is breathing a sigh of relief that this resurgence was prevented from spreading any farther.”

[[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][The Alliance]] Expeditionary Pact offered financial rewards for those who took part in the system’s defence, and these payments can now be obtained at the Golden Stag.

To help celebrate this victory, the technology broker at Bray Landing in the Yuanjia system confirmed that access to Guardian weapons and modules will stay reduced for one more week.
