:PROPERTIES:
:ID:       6215230e-1b3e-4e43-adc6-c4996b306cfc
:END:
#+title: Galactic News: Federation Blockades Maia A 3 a
#+filetags: :3302:galnet:

* Galactic News: Federation Blockades Maia A 3 a

/27 Oct 3302/

Independent reports from the Maia system indicate that a Farragut-class Battlecruiser has taken up position over Maia A 3 a, not far from the personal research base of Professor Ishmael Palin. The Federal vessel is apparently redirecting pilots who stray too close to the site. 

The news comes only a day after Professor Palin announced a breakthrough in his research into meta-alloys. 

The purpose of the deployment is not immediately apparent, but rival political powers have been quick to condemn the act. Alliance Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] described it as "an egregious act of oppression" while Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] said, "The Federation has an obligation to immediately curtail any restriction of Professor Palin's personal freedoms." 

Attempts to contact Professor Palin have been unsuccessful.
