:PROPERTIES:
:ID:       b722f2d6-7f87-4b6f-a287-b7a96f1f8c03
:END:
#+title: Aegis Investigates Missing Populations
#+filetags: :galnet:

* Aegis Investigates Missing Populations

/10 Aug 3309/

An analysis of survivors from recent [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] conflicts and invasions has raised the possibility of human abductions on a colossal scale. 

Professor Alba Tesreau, head of Aegis, delivered a personal statement to the media: 

“A few months ago I was contacted by Zuri Afolayan , a senior analyst for Safeguard Interstellar. Her job involves collating civil and military data to determine where emergency aid is most needed. She had identified consistent discrepancies between the registered populations of Thargoid-occupied systems and all confirmed deaths, refugees and stranded survivors.” 

“Aegis performed detailed comparisons of Ms Afolayan’s findings with other sources. This led to one inescapable conclusion: tens of millions of people have vanished since the start of the war.” 

“No doubt many deaths have gone unrecorded, and many others have fled into deep space. But the recent appearance of the Scythe-class hunter, coupled with events aboard the Dedicant megaship, suggest that at least some have been taken into captivity.” 

“I am very conscious that this statement may be seen as alarmist and speculative. But our xenologists and strategists are considering the implications of a mass abduction programme by the Thargoids. Any opportunity to recover these lost souls will be explored as a priority.” 

Field correspondent Ernesto Rios published his observations via Vox Galactica: 

“It’s a well-documented fact that [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] vessels occasionally take onboard occupied escape pods. But Aegis now believes that the aliens are no longer just attacking humanity – they are attempting to capture us alive en masse.” 

“What are we to them? Prisoners of war? Food for their young? Fuel for their biomechanical technology? Or is this just misinterpreted data and battlefield rumours? In my career I have heard many of these, and in this instance I’m praying that is the case.”
