:PROPERTIES:
:ID:       f82a8f49-3a7f-46ce-8c2e-8027a75adb8c
:END:
#+title: Neo-Marlinists Expose Hadrian Duval as NMLA Leader
#+filetags: :3307:Empire:galnet:

* Neo-Marlinists Expose Hadrian Duval as NMLA Leader

/26 Apr 3307/

Imperator Hadrian Augustus Duval of Nova Imperium is the mastermind behind the NMLA, according to classified information leaked from within ACT. 

Independent journalist Flint ‘Firemaker’ Lafosse published the details on the [[id:d06803e0-267c-4ffc-88f2-967058fce82e][Rewired]] network: 

“Hadrian Duval: the illegitimate embarrassment of the Imperial Family, or their secret terrorist nemesis? That’s the story being told by survivors from the Neo-Marlinist Order of Mudhrid, who gave up their secrets to save their own skins.” 

“According to my source, Landgrave Delacroix confessed to ACT that his faction transported enzyme bombs and Nova Imperium assassins to their targets on the direct orders of Hadrian Duval, who promised rewards and political power in return.” 

“Delacroix also revealed that Hadrian was converted to Neo-Marlinism a year ago by his consort Astrid Minerva, a top [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] agent. She convinced him that becoming Emperor would be much easier if all the other Duvals were dead!” 

“As for the NMLA’s attempt on Hadrian’s life last October, that was faked in order to gain the Imperial Family’s trust. Just another false flag operation – which, as we [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]]-seekers know, can be found everywhere.” 

As yet this information has not been verified, and its source remains anonymous. There has been no comment from either ACT or Nova Imperium.
