:PROPERTIES:
:ID:       690226b3-e33e-47bf-836e-f8f1fce07e03
:END:
#+title: Date Set for Imperial Wedding
#+filetags: :3301:galnet:

* Date Set for Imperial Wedding

/22 Jul 3301/

Date Set for Imperial Wedding 
 
The Office for the Emperor has published details of the wedding between Emperor Hengist Duval and Florence Lavigny. The wedding will take place at midday on Wednesday 29th July. Invitations have already been sent out and this reporter is one of the lucky few to provide news updates from the wedding entourage itself. 

Senators and some prominent patrons together with well known celebrities from all over the Empire have accepted invitations from the Imperial Palace, and have flooded the Emperor’s communications team with their responses. The Emperor himself took a few minutes from his busy schedule to give his thanks: 

“The well wishes both for my recovery and upcoming marriage have warmed my heart. I am strengthened by the love that senators, patrons, clients and citizens of this great empire have shown me.” 

With the news of the wedding date being set, the newsfeeds have erupted with speculation of the outfits for the Emperor and his new Regent. Those boutiques who most closely match the actual attire are likely to see a windfall as everyone celebrates by purchasing the latest trend in fashion.
