:PROPERTIES:
:ID:       2634e55a-68c9-430e-bddb-4b0b21c67e2b
:END:
#+title: Week in Review 06 Oct 3304
#+filetags: :Federation:Alliance:Thargoid:3304:galnet:

* Week in Review

/06 Oct 3304/

Here are this week’s major stories. 

[[id:e46779af-a26e-45fb-a784-21e970eeaae1][Fazia Silva]], one of the three candidates in the Alliance presidential race, has been found dead. There has been speculation that the murder was a political killing, motivated by Silva’s proposed changes to Alliance financial policy. Condolences have been delivered by Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] and both of Ms Silva’s election rivals, [[id:8520e75f-0479-42c5-9083-f9abfbad721e][Gibson Kincaid]] and Elijah Beck. 

Technology company [[id:46e9f326-2119-4d5b-a625-a32820a44642][Herculean Machines]] dominated the recent [[id:9d064da0-7be3-4c7b-99ad-0edd1585d4ca][Rackham Ultratech Expo]], which took place on Wednesday 3rd October. Billionaire [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] was delighted with Herculean’s Duradrive, and agreed to authorise preliminary funding for the device. The Torc, a rival product from [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]], had a less successful showing. 

In other news, the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]] has discovered more administration robots fitted with secret surveillance programs. In each case, the robot was a PA912 model, manufactured by the [[id:04ba4637-336a-46c7-bab0-3ac12f16b2f9][Achilles Corporation]]. The company has announced that it is cooperating with the FSS investigation. 

Juanita Bishop has failed to be elected to Federal Congress. Many of Bishop’s followers have abandoned her in the wake of [[id:b9531f53-8bad-4eda-a0aa-46c72bb6ec9a][Gethin Okonkwo]]’s investigation, which found no connection between the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect and the Thargoids, while Congress members have taken a stand against Mrs Bishop for cultivating civil unrest. 

Meanwhile, media organisation Broadcast Cobra has announced its intention to build a megaship in the HIP 16038 system. The organisation, which specialises in politics and current events, aims to reach a wider audience with the construction of this mobile studio, and has placed an open order for materials to facilitate construction. 

Finally, Mould Federal Mining Incorporated has confirmed that its appeal for commodities to supply an Oktoberfest celebration in the Bhagui system has been enthusiastically received by the galactic community. Hundreds of pilots supported the campaign by delivering commodities to Leavitt Port, and by protecting traders in the Bhagui system. 

And those are the main stories this week.
