:PROPERTIES:
:ID:       2124786a-81e4-4ad2-9cfe-9b0071d4f116
:END:
#+title: Distant Worlds Campaign Concludes
#+filetags: :galnet:

* Distant Worlds Campaign Concludes

/14 Mar 3305/

The Distant Worlds II expedition has gathered resources for a megaship and installation to be constructed in the Galactic Centre. 

Contributors delivered huge amounts of materials to the [[id:35fe6a51-9492-44a7-9dc5-4a5395ae732f][Stuemeae FG-Y d7561]] system. Deep Space Surveys also defended miners by placing a kill order on all wanted ships. 

Commander Michael Darkmoor of the Rock Rats stated: 

“The newly built astrophysics station will enable us to observe high-detail changes to the gravimetric field surrounding [[id:84d9b01d-a9d6-47d9-b9f9-f6154233e585][Sagittarius A*]]*. We hope to better understand the deeper relationships between extreme gravity and multi-dimensional space.” 

The Distant Worlds II exploration fleet will continue its journey across the galaxy, towards Beagle Point. 

Those who took part in the campaign can now collect their rewards from Explorer's Anchorage in the [[id:35fe6a51-9492-44a7-9dc5-4a5395ae732f][Stuemeae FG-Y d7561]] system.
