:PROPERTIES:
:ID:       94e127d1-87b3-43cb-8091-e45fa7f478ca
:END:
#+title: Seo Jin-ae: ‘The Thargoids Know We’re Coming’
#+filetags: :Empire:Thargoid:galnet:

* [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]: ‘The Thargoids Know We’re Coming’

/04 May 3309/

A warning about entering the Maelstroms has been offered by [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]], whose unique cortical implant offers glimpses into the Thargoid hive mind. 

[[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], who is currently working with Aegis, released a personal statement: 

“Seo Jin-ae approached me in a state of distress shortly after the first tests of the Thargoid pulse neutraliser. She claimed that, as the probes passed through Taranis’s energy wave, she perceived a change among the Thargoid voices. ‘Like being woken up by insect bites,’ was how she described the sensation.” 

“‘The Thargoids aren’t as oblivious to our tests as it sometimes seems,’ she told me. I pressed her for more details, but there was only one thing she was convinced about: ‘They understand we’ve found a way to push deeper into the Maelstrom. They know we’re coming.’” 

“Now, this might mean nothing at all, and it’s not verifiable data. But it prompted Professor Tesreau to pass on Seo’s concerns to the superpowers. Likewise, I feel a sense of duty to share this with the galactic community. Any pilots who plan to explore the Maelstrom cores should not assume that they’ll have the element of surprise.” 

Vice Admiral [[id:dce2491e-fa32-458a-90b1-3a2e0bede702][Skylar Anderson]], the Empire’s military liaison to Aegis, commented: 

“I have personally reviewed all recent tactical reports, but found no evidence of any changes in the Thargoids’ behaviour or strategy. We are proceeding with our plans to mass-produce the Thargoid pulse neutraliser and send crewed ships into the Maelstroms. Tanner’s concern is noted, however, and we urge extreme caution in these early expeditions.”
