:PROPERTIES:
:ID:       36deb532-8216-43db-a450-963ec5444999
:END:
#+title: Rival Corporations Compete in LTT 198
#+filetags: :3307:Empire:galnet:

* Rival Corporations Compete in LTT 198

/16 Aug 3307/

Torval-Mastopolos Mining and Wreaken Construction have both established a presence in the LTT 198 system. 

Marlon Royce, business analyst for Vox Galactica, reviewed the situation: 

“It is highly unusual for two megacorps to set up new headquarters in the same place. But Mastopolos Mining and Wreaken Construction have always competed aggressively for mining and transportation contracts, so it seems a new chapter in their rivalry has begun.” 

“This permit-locked system is controlled by the independent faction LTT 198 State Ltd. Insiders claim that it demanded a fortune from both corporations in return for granting passage to its ships and allowing construction of industrial complexes on the planet Dini.” 

“This is the first significant move from Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]]’s new company, an autonomous offshoot of Mastopolos Mining. It may be that Wreaken Construction’s presence is an effort to crush their old enemy before she can acquire further corporate strength.” 

The Imperial Herald reported that Constantia Torval, one of [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]]’s daughters, has travelled from the Synteini system to LTT 198. It is believed Constantia has taken command of Torval-Mastopolos Mining’s operations.
