:PROPERTIES:
:ID:       3d612921-919d-49af-ae60-c4b8d93a9ac8
:END:
#+title: Pilots’ Federation Establishes Regulated Zone
#+filetags: :Thargoid:galnet:

* Pilots’ Federation Establishes Regulated Zone

/20 Apr 3305/

The Pilots’ Federation has revealed plans to establish a restricted area of space for newly licensed Commanders.  

In a statement, spokesperson Gabriel Sanchos gave the following details:  

“Following discussions with the three superpowers, representatives have acknowledged that independent pilots are a mainstay of the galactic community. As such, a Pilots’ Federation District will be created for new Commanders, offering combat exercises and tailored assignments within several designated systems." 

“The intention is to offer pilots an opportunity to complete contract assignments without exposing them to opportunistic criminals. Access to the district will depend on the possession of a permit granted to new Commanders alongside their Pilots’ Federation license. This permit will be revoked once a certain level of experience has been acquired.” 

Representatives of the Alliance, Empire and Federation each confirmed their approval. Their statements underscored the positive contributions made by licensed Commanders with regards to the galactic economy, exploration initiatives and the Thargoid threat.
