:PROPERTIES:
:ID:       c0c01fc4-1480-4994-8abb-bf784521ef02
:END:
#+title: Aegis Announces Engineering Supply Commitment
#+filetags: :Empire:Alliance:Thargoid:galnet:
* Aegis Announces Engineering Supply Commitment

/06 Aug 3310/

An announcement by Head of Aegis, Alba Tesreau, has revealed a new opportunity for pilots engaged in anti-xeno operations. 

During her monthly communication with representatives of all three superpowers which fund the Aegis project, Tesreau discussed a recent agreement to provide AX pilots with additional support: 

“The military fleets and operatives of the Alliance, Empire and Federation have proven vital to resisting the Thargoid war machine. But independent pilots have also sacrificed so much in defense of humanity’s sovereignty. By funding their own vessels and equipment, they earn their keep via combat, trade and humanitarian dedications.” 

“It is clear we need to do more to reward these pilots leading the charge towards the remaining Titans, liberating systems and protecting billions along the way. After discussing options with Professor Palin and Ram Tah, Aegis has agreed to arrange a supply of materials which can be applied to various engineering blueprints.” 

“We hope these contributions will improve the effectiveness of our AX efforts, while recognising the incredible efforts of our brave pilots.” 

A follow-up statement provided further clarification. Independent pilots active in systems harvested or controlled by Thargoids will be tracked by Aegis comms networks. When a Thargoid force has been eliminated from a system, Aegis will review this data and provide engineering materials based on each pilot’s individual contribution. 

Tesreau stressed that all activities which aided the defense of a system would be contained in this review, including non-combat efforts. 

Pilots that contributed to clearing a system of Thargoids will receive a direct message from Aegis with details of any earned engineering materials. The initiative will begin on Wednesday 7th of August, 3310.
