:PROPERTIES:
:ID:       a5724e5b-f954-4c9f-b34e-6b64d281aea4
:END:
#+title: Militaries Prepare for Further Thargoid Strikes
#+filetags: :galnet:

* Militaries Prepare for Further Thargoid Strikes

/30 Sep 3308/

The prospect of more systems being invaded by Thargoids has placed the Alliance, Empire and Federation on high alert. 

Ernesto Rios, field correspondent for Vox Galactica, summarised the situation: 

“Following the Battle of HIP 22460, there was anticipation that the Thargoids would expand into neighbouring regions. Swarms of hostile vessels did indeed arrive in the 42 n Persei, Chun Pindit and Tekkeitjal systems, although – in a notable change to their former tactics – no starports suffered a direct attack.” 

“The Federal Navy quickly responded by deploying Farragut-class battle cruisers. President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] proclaimed that these successfully drove out the invaders, but many observers suspect that the Thargoids’ withdrawal when the fighting remained fierce was intentional.” 

“In the Empire, Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] considered these events ‘an indication that the Thargoids are probing humanity’s defensive capabilities’. But details of the Imperial Navy’s anti-xeno strategy remained confidential, a sign of the Empire shift away from military coordination with other superpowers.” 

“The Alliance has claimed to be in a position of readiness. Admiral Nikolas Glass reported: ‘Operation Tyndareus, backed by Sirius Corporation, is now active. The Alliance Defence Force is ready to deploy anti-xeno taskforces, should the Thargoids dare to launch an assault within Allied space.’ Meanwhile, critics of the strategic defence pact have observed that only two megaships currently possess AX weaponry, casting doubt over the ADF’s effectiveness.” 

“Elsewhere, many independent systems are doing whatever they can to bolster their local security forces. Too many worlds are acutely aware that should Thargoid fleets darken their skies, they would be forced to rely on mercenaries and independent pilots for protection.” 

“Popular opinion on continued military actions against Thargoid vessels remains primarily favourable, but the ‘xeno-peace’ discussion continues to grow. In the Aiabiko system, leading ICE personality Joy Senne has released a ‘beacon drop’ package in an effort to promote the idea of peace to independent pilots. Ships scanning the beacon will receive a xeno-affirmative ship nameplate set and decal - paid for by Senne - along with clips of a recent discussion with Sovereign Times anchor Heimar Borichev about the so-called ‘Thargoid Advocacy Project’.”
