:PROPERTIES:
:ID:       a3165180-dc0e-465c-8dac-c0ef49acc0c2
:END:
#+title: Salvation Warns of Thargoid Strike
#+filetags: :Thargoid:galnet:

* [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] Warns of Thargoid Strike

/14 Sep 3307/

The anonymous figure known as [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] claims that Thargoid forces will shortly launch an assault in the Cornsar system. 

The following message was received by all major newsfeeds: 

“This is [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. Authorities in the Cornsar system must evacuate the local population immediately. I believe a Thargoid invasion of the system is imminent.” 

“I became aware of this danger while developing a new interstellar xeno-detection network, which will be far superior to Eagle Eye. Although the network is not fully complete, we cannot dismiss this report as a false reading. Cornsar must act now.” 

Carter Armstrong, a chief administrator with Aegis, delivered an official statement: 

“Aegis cannot validate this claim. There is no indication of a Thargoid presence in the vicinity, and Cornsar is too far from their known territories to be a viable target. As most of our operations are suspended due to the public inquiry, we cannot dedicate any resources to investigate further.” 

There was also a response from Marshal Noah Sharrow, who governs the Cornsar system on behalf of the Allied Cornsar Constitution Party: 

“We have no interest in the games of one-upmanship between Aegis and [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. Nor do we believe for a moment that the Thargoids would go out of their way to harass us.”
