:PROPERTIES:
:ID:       040a7d4d-ec14-4dd1-a911-d7ce45eff3eb
:END:
#+title: Empire Celebrates Newborn Duval
#+filetags: :3307:Empire:Federation:galnet:

* Empire Celebrates Newborn Duval

/02 Dec 3307/

*Pilots’ Federation ALERT* 

A new chapter in the [[id:bce02e51-c68c-4594-86fe-88dda4915a74][Duval family]]’s history has begun with the birth
of [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Augustus Duval]]’s son.

The announcement was made by The [[id:626a18d7-ad16-4093-b9be-d9dc1940594b][Imperial Herald]]: 

“Lady [[id:ef9ddb06-8cb2-4c3f-a688-469be3149aa9][Astrid Minerva-Duval]], wife of [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]], has delivered a
baby boy at an undisclosed secure location while under senatorial
protection.”

“The child has been named [[id:c51145ab-32ee-42ec-a884-bbbc263b06dd][Hector Mordanticus Duval]]. This is in honour
of Hadrian’s late father [[id:8d725ff3-3036-473a-b339-09e4da4e43d0][Hector Jansen]], who was Emperor [[id:3cb0755e-4deb-442b-898b-3f0c6651636e][Hengist]]’s
illegitimate son, as well as Imperator [[id:f6be5b58-fd8d-4233-8053-7ade4ca35aee][Kaeso Mordanticus]], who played a
major role in both [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian]] and [[id:ef9ddb06-8cb2-4c3f-a688-469be3149aa9][Astrid]]’s lives.”

“Despite [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian]] not being an official member of the [[id:85e6fd5f-69a0-4f7c-95d0-ddb89ef150e9][Imperial Family]],
many citizens are jubilant at the arrival of a new Duval. The [[id:7210d36a-25f5-4c8e-8cf2-069de549d438][Imperial
Palace]], Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] and Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]] have all
sent messages of congratulation.”

Praetor [[id:3fdf3f05-e7b5-436f-906e-e67dafa5d254][Leo Magnus]], who was [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]]’s head of security, has
resigned his temporary commission from [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][ACT]] to assume leadership of
[[id:1922c60c-fe76-49f4-ae46-e3e70d19514b][Nova Paresa]]. The faction has organised an initiative to gather rare
commodities for its former leader to celebrate the historic occasion.

Pilots are asked to deliver [[id:a8e39d40-99a9-4f9a-982c-82895e20f5e4][Chateau De Aegaeon]], [[id:3e97a232-8596-4e01-9c73-2859b0add0b2][HR 7221 Wheat]], [[id:ffcc8c23-1721-41cb-9cb7-c849292c8b38][Indi
Bourbon]] and [[id:91faf122-5fcc-4d6d-b4b2-1b420faac9a7][Yaso Kondi Leaf]] to [[id:f45acd08-6a6f-46c8-94b2-3a0453211248][Dyson City]] in the [[id:9147b1a8-a73f-4144-b614-8e876943c10e][Paresa]] system. All
shipments will be subject to security scanning before being redirected
to a suitable location.
