:PROPERTIES:
:ID:       ea126758-5df3-49b5-af45-af1c77be5eea
:END:
#+title: Xeno-Peace Champion Elected to Congress
#+filetags: :Thargoid:Federation:galnet:

* Xeno-Peace Champion Elected to Congress

/07 Nov 3308/

Dalton Chase, the former governor of Andavandul 1, has become a Federal congressman following victory in the recent special election. 

Despite his relative youth and inexperience, many voters within the congressional district were influenced by Chase’s charm and positive campaign message. His enthusiasm for opening diplomatic relations with the Thargoids resonated with younger voters. The Liberal Party also ran a creative PR campaign across social channels, which was amplified by many counter-cultural ICE-casters. 

After formally swearing in and taking his oath of office, Congressman Chase proclaimed: 

“I’m conscious that some view me as unorthodox or contrarian, perhaps even ‘soft on Thargoids’. But I take the security of the Federation as seriously as any of my honourable colleagues. Achieving peace with another species, and thereby saving the lives of countless Federal citizens, would be considered the great moral victory of our generation.” 

Congratulations were offered by Shadow President Felicia Winters, who referred to Chase as a “spirited addition to our ranks”. Political analysts observed that she made no mention of his affiliation with the xeno-peace movement. Although some in the Liberal Party have expressed sympathy with its intentions, the majority consider it too radical to ever be officially endorsed. 

Key members of the Thargoid Advocacy Project have thanked Congressman Chase for helping to establish the pro-peace megaship, Kingfisher. This is currently being outfitted with specialist technology designed to transmit signals of various types, in the hope of being able to effect two-way communication with the Thargoids.
