:PROPERTIES:
:ID:       1d19e251-b4a8-4130-8c6b-b0c44f78cda9
:END:
#+title: Lakon Spaceways Discusses Supercruise Overcharge Challenge
#+filetags: :galnet:
* Lakon Spaceways Discusses Supercruise Overcharge Challenge

/30 Jul 3310/

A shareholder's function hosted by Lakon Spaceways has revealed further details of its recently announced Type-8 trader. 

Several hundred individuals with significant financial ties to the ship development corporation gathered at Lakon Spaceways Central on Alioth 1 a. The stylish presentation of the Type-8 was met with enthusiastic applause, with one attendee claiming the ship should prove ‘remarkably capable’ in its position as a specialised medium freighter. 

Chairperson Naomi Landseer discussed the design challenges posed by the recently released SCO Frame Shift Drive: 

“Lakon invested heavily in research and design initiatives to incorporate Achilles’ frame shift drive variant. The drive's potential to accelerate in-system travel goes beyond anything previously imagined. We had to ensure Lakon could provide a design capable of minimising the incredible stress placed on ships by the supercruise overcharge tech.” 

“So, with the Type-8 just weeks away from the prototype stage, we moved the project back to the theoretical stage and invited solutions from our industry-leading engineers and technicians. Our adjustments resulted in the largest ship frame to retain a size classification of medium. I'm incredibly thankful to Lakon's remarkable staff for the countless hours worked over the past couple of months, adapting the hull within deadline for our initial test batch.” 

"It is pleasing to say that the SCO frame shift drive will function far more effectively in the Type-8 than with any other dedicated trade vessel on the market today. I look forward to announcing the Type-8's official release soon.”
