:PROPERTIES:
:ID:       4bcb9f12-c4ac-4b3d-9319-9b3fe59432d9
:END:
#+title: Positive Response to Explorers' Association Request
#+filetags: :3301:galnet:

* Positive Response to Explorers' Association Request

/04 Nov 3301/

The Explorers' Association has released a statement confirming that the pirates operating in the [[id:3ceec3b8-48ce-40e3-8b24-ba6fe065d56c][Kaushpoos]] system have been eliminated. Hundreds of pilots responded to the organisation's appeal, taking to their ships to battle the agitators disrupting the assembly of Kaushpoos's new Ocellus starport and deliver palladium for use in its construction. A spokesperson for the Explorers' Association released a brief statement: 

"By coming to the aid of this important initiative, the galactic community has once again demonstrated its belief in the value of this starport. The Explorers' Association extends its sincere gratitude to all those who helped to rid the [[id:3ceec3b8-48ce-40e3-8b24-ba6fe065d56c][Kaushpoos]] system of pirates, and also to those who delivered palladium for the next phase of construction. Thanks to you, we can continue with our work." 

A further statement is expected from the Explorers' Association soon, announcing its third and final public appeal for resources.
