:PROPERTIES:
:ID:       9de954d5-94b1-4d2b-b28f-89a4ac8e31e5
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/c4e444c0-4336-4828-b806-60d548a3b4f1?resourceVersion=id%3A4892
:END:
#+title: New Marlinist Systems Request Emergency Food Supplies
#+filetags: :galnet:

* New Marlinist Systems Request Emergency Food Supplies

/14 Jan 3307/

*Pilots Federation ALERT* 

The newly settled Marlinist Colonies have asked for urgent deliveries of foodstuffs. 

Millions of Marlinists have relocated to eight systems colonised for them by the Sirius Corporation, thereby reducing tension between [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] and the Federation. They have asked Universal Cartographics to delay a census of the systems’ populations, while the refugees lay the infrastructure for their new societies. 

The Marlinist factions are holding democratic elections to select their leaders. However, the transitional parliament has declared an emergency due to the shortage of food stocks. 

Community spokesperson Dr Jenna Fairfax announced: 

“We are grateful to the galactic community and Sirius Corporation for providing homes. However, we need further help to feed our people in the short term, until we can become self-sufficient.” 

“The more supplies we can stockpile, the faster our economies will develop. This in turn will allow us to offer greater commodity discounts, to encourage the establishment of regular trade routes.” 

Pilots are asked to deliver animal meat, fish, fruit and vegetables, and grain to Stillman Hub in the HIP 22550 system.  

As this system’s defence forces are still being formed, the Free Marlinists of Carinae have offered bounties on all wanted ships to secure these initial trade runs to the Marlinist Colonies.
