:PROPERTIES:
:ID:       4cd4fb1c-7473-4614-808e-22fe569d37eb
:END:
#+title: Galactic News: Construction Convoy Assembled
#+filetags: :3302:galnet:

* Galactic News: Construction Convoy Assembled

/18 Nov 3302/

A large convoy of heavy construction ships and associated support vessels has been assembled by Wreaken Construction in the Zearla system.  

Wreaken does not have an exclusive contract with any of the galaxy's superpowers, and there has therefore been significant speculation over the purpose of the convoy. 

Requests for information have been met with blank rebuttals, and recent press statements from Wreaken make no mention of the convoy. Long-range reconnaissance has revealed a well-defended operation, and approaches are greeted with patrol ships and warning shots. 

Meanwhile, shares in Wreaken have gone up by five per cent as speculation grips the financial markets. Some commentators believe this is directly linked to Admiral [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]]'s recent comments concerning the London Treaty.
