:PROPERTIES:
:ID:       41f3a2a6-59bf-4503-81f2-ad64e59b0699
:END:
#+title: Community Goal: Repair Jaques Station
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: Repair [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station

/21 Jul 3302/

Jaques, the owner and operator of [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station, has issued an appeal for commodities to repair his beleaguered starport. 

The station has been in poor shape ever since [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] made an unsuccessful attempt to travel to Beagle Point. Since then, a number of independent pilots have voluntarily delivered meta-alloys to the station, resulting in the reopening of the starport's commodities market. But to restore the starport to full functionality, a full-scale campaign is needed. In a statement, Jaques said: 

"We're very grateful to all the pilots who brought us meta-alloys over the past few weeks. But to get the station back online, we're also going to need power generators, tantalum, structural regulators and energy grid assemblies. So we're asking all pilots to deliver whatever they can." 

Jaques has promised to reward pilots who deliver the requested materials to [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the Eol Prou RS-T d3-94 system. The campaign begins on the 21st of July 3302 and will run for four weeks. If Jaques's targets are met earlier than planned, the campaign will end immediately.
