:PROPERTIES:
:ID:       14b168fd-b572-4362-93d2-159d9ee8349b
:END:
#+title: Mars Tribune Refutes Allegations
#+filetags: :Federation:3304:galnet:

* Mars Tribune Refutes Allegations

/25 Oct 3304/

As the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]] continues its investigation into The Mars Tribune for illegally obtaining the private information of Federal citizens, the newsfeed’s parent company, the Cordova Group, has filed a formal complaint.  

The FSS has established that the administration robots of dozens of public figures and wealthy individuals have been fitted with hidden surveillance programs, and that these programs may be the source of several scandals exposed, exclusively, by The Mars Tribune. 

Kingsley Cordova, billionaire owner of The Mars Tribune, addressed the situation in an editorial: 

“These accusations are an insult to our journalistic integrity. Are we to be punished for uncovering liars and criminals? Our readers have always been grateful to us for shining a light into Sol’s murky corners.” 

“I suggest that the FSS treads more cautiously. These robots apparently have access to very sensitive data. Imagine if they publicly broadcasted everything they’d learned about their owners.”
