:PROPERTIES:
:ID:       c40c696e-bd5a-4c64-9409-ccbd2abd27c3
:END:
#+title: Federal and Imperial Forces Engage in Battle
#+filetags: :Federation:Empire:galnet:

* Federal and Imperial Forces Engage in Battle

/05 Nov 3306/

*Pilots Federation ALERT* 

The Empire’s counter-terrorism operation in the LTT 1935 system has triggered armed resistance from the Federation. 

The Imperial Internal Security Service’s investigation into the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terrorist group led its agents to LTT 1935, a Federation-controlled system in neutral space. Military vessels were called in for support, only to be met in combat by Federal forces. 

A declaration was made by Colonel Ernest Harris of the LTT 1935 Confederacy: 

“The Empire cannot dominate and arrest our citizens as it did with the Marlinists. We claim the right to defend the Federation’s territory from such aggressive tactics.” 

Captain Axel Cyprian of the L.Y.S Corp responded: 

“The IISS has confirmed that the Neo-Marlinists have secret bomb-making factories concealed within LTT 1935. To prevent future atrocities, it is vital that we take control of this system and shut down the NMLA’s source of weapons.” 

The LTT 1935 Confederacy has requested help from independent pilots to defend LTT 1935 from occupation by the Empire.  

The L.Y.S Corp has also asked for auxiliaries to assist in gaining control of the system.
