:PROPERTIES:
:ID:       2028dfb0-0ae5-441b-8e2f-9c7173646bf1
:END:
#+title: Rackham Announces Presidential Candidacy
#+filetags: :3300:Federation:galnet:

* Rackham Announces Presidential Candidacy

/27 May 3308/

The trillionaire entrepreneur [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] has officially confirmed that he will stand as a candidate in the 3309 Federal election. 

Mr Rackham finally stated his intentions following several weeks of speculation. At a press conference, he said: 

“I know what you’re all thinking. That guy as president? Isn’t he just a common businessman, who used to survive on scraps by trading trinkets in a rusty old Sidewinder?” 

“But despite my humble origins, many good people have convinced me that my experience with running corporations would prove useful to the Federation. I feel like everyone’s tired of the same empty words from the two big political parties. It’s time to hear from the little guy!” 

Mr Rackham added that it will take several weeks to prepare his manifesto and campaign team. It is unknown whether he intends to form a new political party or stand as an independent candidate. 

There has been no comment from President Hudson or Shadow President Winters. However, several congressmen remarked that the media attention accompanying Mr Rackham’s efforts might attract more public interest in next year’s presidential race. Only 65% of eligible voters took part in the last election in 3300. 

The Tau Ceti Journal noted that the value of shares in [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]] has soared to an all-time high, making many investors extremely wealthy overnight.
