:PROPERTIES:
:ID:       6dad938c-1dae-4acb-83d2-1c498cd5dda2
:END:
#+title: Colonia Bridge Gains Further Resources
#+filetags: :3307:Federation:galnet:

* Colonia Bridge Gains Further Resources

/11 Nov 3307/

*Pilots Federation ALERT* 

Successful campaigns in the Alcor and Colonia systems will result in new megaships being added to the Colonia Bridge. 

Large quantities of ceramic composites, computer components and thermal cooling units were provided at either end of the route between the core systems and the distant Colonia region. 

Brewer Corporation provided an update on the project:  

“Once again, the galactic community has provided the vital materials required to construct dockable megaships. These additional ports should be operational by the 25th of November, making journeys to and from Colonia easier and safer.” 

“Pilots can now collect their rewards from Macdonald Settlement in the Alcor system and [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the Colonia system. We shall also be awarding an engineered frame shift drive with long range and fast boot to the majority of contributors.” 

The top ten pilots who delivered materials to Alcor and Colonia will shortly be invited to submit suggestions to name the new megaships. Submissions will be subject to review by the Brewer Corporation board of directors. To ensure a variety of choice, only pilots who have not yet submitted names for the Colonia Bridge megaships will be eligible.
