:PROPERTIES:
:ID:       6b21a683-6627-4a32-af0d-2a23e0ae5202
:END:
#+title: Class 5 Experimental Weapons Stabiliser Released
#+filetags: :galnet:

* Class 5 Experimental Weapons Stabiliser Released

/01 Feb 3309/

*Pilots’ Federation ALERT* 

Azimuth Biotech has commercially launched a new module that allows two additional AX weapons to be added to large ships. 

The experimental weapons stabiliser increases the number of AX weapons which can be installed on a ship. The class 3 variant released last week increases the limit to five, whereas the class 5 variant released yesterday increases it to six.  

Both versions entered mass production following Azimuth Biotech’s highly successful resource drive in the LHS 1163 system. CEO Torben Rademaker issued a statement to accompany the product launch: 

“Our proprietary technology has bypassed the inherent design flaws of Aegis’s AX weaponry. The experimental weapons stabiliser will play a vital role in the ongoing defence of the core systems.” 

“I can only assume that the current chatter about reforming Aegis is due to misplaced nostalgia. How quickly people forget the Baumann Report, which laid bare the organisation’s inefficiency and incompetence. The logical path to victory is to employ the most accomplished anti-xeno specialists, such as those found here at Azimuth Biotech.”
