:PROPERTIES:
:ID:       0c819854-8ac9-41f4-8b2b-aba0136fe1d9
:END:
#+title: The Bulwark Project
#+filetags: :Thargoid:3304:galnet:

* The Bulwark Project

/16 Feb 3304/

The Federation has launched an initiative to develop autonomous military hardware with which to fight the Thargoids. 

Federal Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] shed further light on the initiative, which has been christened the Bulwark Project: 

"As the Thargoids' aggression escalates, it's essential that we find ways to minimise casualties while continuing to protect ourselves. Aegis is doing commendable work, but it needn't be our only line of defence." 

Imperial commentators have criticised the initiative, however, drawing attention to long-standing conventions against the development of artificial intelligence. Shadow President Winters was quick to dismiss such concerns, saying: 

"The purpose of the Bulwark Project is to investigate alternative defence strategies, not to develop machine intelligence." 

The operation has received financial support from the Momoirent Central and Co, which has placed an open order for various commodities for use in the campaign. 

The campaign begins on the 15th of February 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
