:PROPERTIES:
:ID:       9724a888-2e4d-47ca-8d96-2b692a406889
:END:
#+title: Trial Period Agreed for Alliance-Sirius Pact
#+filetags: :Alliance:galnet:

* Trial Period Agreed for Alliance-Sirius Pact

/09 Mar 3308/

The Alliance and Sirius Corporation have negotiated a three-month probationary period for its proposed anti-xeno defence agreement. 

In response to a summons by Councillor Nakato Kaine, CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] appeared in person before the Assembly. As part of a longer speech he stated: 

“I fully understand that, in order to be effective, the strategic defence pact requires broader political support. But to share its details before the Alliance can experience its benefits may lead to hasty decisions.”  

“Instead, we propose that Sirius Corporation is provided with an opportunity to demonstrate how we can enhance Allied security against the Thargoids. At the end of a contractually defined period of time, the Assembly can review the pact and decide whether or not to continue with our partnership.” 

Following further discussions, Yong-Rui accepted that the probationary period would be reduced to three months from the originally suggested six. Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] expressed his gratitude that a solution had been reached.  

Councillor Ainsley Niven, representing the Reorte system, sounded a cautionary note: 

“Frankly, some Allied factions won’t tolerate Sirius’s presence for three minutes let alone three months. I fear that this will not be enough to convince all of our member systems to cooperate.”
