:PROPERTIES:
:ID:       7907f9a3-6421-4d9f-a3d8-965866d0861f
:END:
#+title: Computer Designers’ Rivalry Escalates
#+filetags: :3304:galnet:

* Computer Designers’ Rivalry Escalates

/01 Sep 3304/

Maddox Hurd, owner of [[id:46e9f326-2119-4d5b-a625-a32820a44642][Herculean Machines]], has publicly dismissed the efforts of rival company [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]]. Both companies are currently developing new computer designs. 

Mr Hurd referred directly to [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]]’s forthcoming product, the Torc, while addressing the media: 

“There’s a reason Herculean has never explored the concept of wearable devices – it’s a ridiculous idea! I bet a million credits that those fragile gizmos will break, or their holograms will start glitching, the moment you turn them on.” 

“If you want a reliable piece of tech, you need the Duradrive. Believe me, our device will keep on working whatever you throw at it…and even if you throw it.” 

When invited to comment, [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] CEO [[id:b62c9e2e-8079-44bc-a30d-d192076162e6][Scorpio DeVorrow]] responded: 

“It’s regrettable that those with a clear vision of the future are often denigrated by individuals of limited imagination. We offer an elegant and revolutionary approach to personal computing – not just a rubber brick with a screen. I’m sure customers will make the intelligent choice.” 

Prototypes for both the Torc and the Duradrive will be unveiled at the [[id:9d064da0-7be3-4c7b-99ad-0edd1585d4ca][Rackham Ultratech Expo]] on Wednesday the 3rd of October.
