:PROPERTIES:
:ID:       78e00036-1f88-4f84-b487-db14fadcd107
:END:
#+title: Progress Between Federation and Yuri Grom
#+filetags: :3307:Federation:galnet:

* Progress Between Federation and [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]]

/24 Sep 3307/

Negotiations between the Federation and self-styled dictator [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] are underway to determine the Delta Pavonis system’s allegiance. 

Political correspondent Conrad Sterling published an update for Vox Galactica: 

“In recent years, [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] has developed a degree of mystique. He was one of the few leaders not to attend the Galactic Summit, and news from within his dominion was scarce. But now he is visibly relishing the opportunity to confront Federal representatives under the protection of diplomatic immunity.” 

“Initial exchanges were belligerent as both sides argued over who would be the most beneficial partner. This was to be expected since Delta Pavonis is one of the Federation’s founding systems, and it would be a significant coup for EG Union to establish a presence so close to Sol.” 

“What was unexpected was the mutual respect that gradually developed between [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] and Ambassador Delphine Dumont. Her charming manner clearly appealed to the dictator, even bringing forth his thunderous laughter on occasion.” 

“A deal is now being discussed that would allow the Autocracy of Delta Pavonis to have trade and political ties with both parties while remaining independent. Perhaps the Federation has learned some lessons from the recent rebellion, and perhaps [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]]’s hatred of the superpower he once served is finally abating.”
