:PROPERTIES:
:ID:       bcdfd642-c922-4ca1-8d10-21a6d1f1a20c
:END:
#+title: League of Reparation Implicated in Historic Deaths
#+filetags: :Alliance:Federation:3304:galnet:

* League of Reparation Implicated in Historic Deaths

/15 Jun 3304/

A recent report suggests that terrorist organisation the League of Reparation may be responsible for many more deaths than previously suspected. 

Independent journalist Flint ‘Firemaker’ Lafosse shared his theories on the [[id:d06803e0-267c-4ffc-88f2-967058fce82e][Rewired]] newsfeed: 

“We know these League guys are wiping out people whose grandfolks used to work for the INRA, and it seems like things started when they poisoned that Imperial senator. But what if that wasn’t their first murder, merely the first time they claimed responsibility? What if they’ve been active for years and nobody noticed?” 

“I’ve been digging through old records of unsolved homicides. There’s a dozen in the Federation alone where the cause of death was some kind of ‘nerve agent’ – just like with the senator and a few others. Not all the victims were identified, but I found four who definitely had the INRA in their past. These people didn’t die recently but between one and five years ago. Coincidence?” 

“The League also likes to blast its targets out of the sky. Think of all those unexplained shipwrecks found drifting in space over the years. How many were because one of the crew had some long-forgotten INRA connection? Dozens…hundreds? How long has the League been hiding among us, silently taking out ordinary people? And who’s next?” 

Chief Inspector Kay Kilbride of Alliance Interpol responded on behalf of the united taskforce investigating the League: 

“We cannot verify that these cold cases have any link with the League of Reparation. We’d also like to caution against this kind of baseless conjecture, which only serves to spread confusion. We are still pursuing more concrete leads, and hope to make a breakthrough very soon.”
