:PROPERTIES:
:ID:       3bb3e024-e316-462d-ae10-d2c0004f056b
:END:
#+title: An Interview with [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]
#+filetags: :galnet:

* An Interview with [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]

/04 May 3308/

Sol Today hosted an interview with the multi-billionaire [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]], who is rumoured to be moving into politics. 

From his villa at Lake Rackham, overlooking Homeland’s famous Singing Geysers, the entrepreneur spoke at length on various topics. 

On the rise of his business empire: 

“The hard-working folk at [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]] have done me proud in recent years. We’re currently holding financial talks to acquire a major starport company, so watch this space!” 

On his role with the Beta Hydri Corporation: 

“It’s a privilege to support my people in Beta Hydri, by helping to run their government. Things are already running smoother after I streamlined a few departments.” 

On suggestions that he will take part in the Federal presidential election: 

“I’m deeply flattered by calls to stand as an independent candidate. But really, an ordinary guy like me as president? I suppose it indicates that people are looking for something different to what Hudson and Winters offer.” 

On Bryanna Blanco’s claims that he was once a pirate: 

“Ah, you have to admire Ms Blanco’s tenacity! But ‘Calico Zack’ sounds like a character from an Olav Redcourt novel, doesn’t he? I should thank her for making me look a lot more impressive than I ever was.”
