:PROPERTIES:
:ID:       7c3b8d89-efd5-4b4e-8e03-a6dc50bb9305
:END:
#+title: Red Family Operation Concludes
#+filetags: :Federation:galnet:

* [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] Operation Concludes

/02 Aug 3305/

The Federal Intelligence Agency has declared that its campaign against the [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] cartel is drawing to a close. 

As observed by Ethan Takahashi, crime correspondent for [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“In terms of effective action, this has to be considered a great victory for the FIA. A series of coordinated strikes against the [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] delivered a mortal blow, and the cartel’s super-addictive narcotic was destroyed before it could be mass-produced.” 

“While kingpin Oberon Church remains at liberty, it is unlikely that he could ever rebuild his empire. Still, losing one of the most wanted criminals in the Federation must be frustrating for the agency.” 

Internal investigations continue regarding Jan Sandoval’s death in custody. No conclusive evidence has been uncovered, but many believe that Sandoval could not be reached without the assistance of FIA personnel. 

“It is not unreasonable to assume that individuals within the FIA have been bought by Church,” said Takahashi.
