:PROPERTIES:
:ID:       2277d600-a60b-4078-bd1b-fd0005ab2b85
:END:
#+title: Securing the Old Worlds
#+filetags: :3301:Federation:galnet:

* Securing the Old Worlds

/02 May 3301/

For months now, the Old Worlds have been terrorised by roaming gangs of psychopaths and thieves. Residents’ pleas for help have been rejected by the Council of Admirals, who maintain that matters of internal security are the sole responsibility of member states. Many see this rise of lawlessness as an opportunity. Pilots on both sides of the law are now flocking to the sector in the hope of making their fame and fortune. 

Inspired by the recent changes brought about by independent members of the Pilots Federation, a network of local business leaders have banded together to improve conditions in the Old Worlds. They are sponsoring the formation of a new coalition, and though they have yet to officially announce the group’s manifesto, support for the movement is already spreading. 

One member of the new coalition, Silver United Solutions, has announced that they are currently in the process of recruiting experienced security professionals to help protect the residents of Zaonce from the various gangs operating in the sector. Potential recruits are asked to report to Ridley Scott in Zaonce for assessment.
