:PROPERTIES:
:ID:       f125201e-7b84-4694-b3d2-0fe890384474
:END:
#+title: Freelance Report: Fuel Rats Complete 20,000th Rescue
#+filetags: :3303:galnet:

* Freelance Report: Fuel Rats Complete 20,000th Rescue

/12 Jan 3303/

On the 7th of January 3303, the Fuel Rats successfully completed their 20,000th rescue since their foundation in June 3301. The milestone was reached during a busy weekend that saw the group complete a total of 230 rescues. Sources at Fuel Rats headquarters in the Fuelum system linked the spike in cases to curiosity surrounding reported sightings of non-human spacecraft. 

The Fuel Rats Mischief, an auxiliary wing of the Fuel Rats, revealed that the 20,000th rescue took place in the Alrai Sector, with Commanders Esxste, FightingCookie and Hillbillypolenta flying out to rescue the stranded pilot. The group also paid tribute to Commander Termite Altair, who has completed an unprecedented 750 successful rescues. 

When asked about reports of alien ships, a Fuel Rats spokesperson said the group would remain true to its policy of neutrality and give fuel to non-human vessels if requested. 

Tivec
