:PROPERTIES:
:ID:       92f8f7a7-6273-4665-9648-4b86ed5a5016
:END:
#+title: Chancellor Blaine Confirms Senate Investigation
#+filetags: :galnet:

* Chancellor Blaine Confirms Senate Investigation

/21 Sep 3301/

Chancellor Blaine Confirms Senate Investigation 
 
At the start of the day’s deliberations, Chancellor Anders Blaine declared that a Senate investigation into the claimed connection between Princess Aisling Duval’s office and the insurgent group Emperor’s Dawn was to be undertaken. The investigation will begin immediately, despite the Senate being in closed session until the succession is decided. 

In response, Aisling Duval stated that she would comply in any way she could with the investigation. She also said that her own security teams had discovered some alarming information that she would share with the investigation committee. 

Meanwhile, the hunt for Patron Damon Clarke continues. Several of his associates were arrested by the Internal Security Service in the early hours of the morning and subjected to questioning.
