:PROPERTIES:
:ID:       69c5ee29-4256-4a19-9d90-15cdd89da8d0
:END:
#+title: Azimuth A Historical Perspective (Part Five)
#+filetags: :Thargoid:galnet:

* Azimuth A Historical Perspective (Part Five)

/29 Jun 3308/

The concluding article in this series examines events leading to the resurrection of Azimuth and Salvation’s plans for the future. 

During February and March 3308, Aegis suffered a slow death as its operations were shut down by the superpowers. Its leaders continued calling for its reinstatement, not just to battle the Thargoids but also to oppose Azimuth Biochemicals. They claimed that this sinister corporation was still performing unlicensed xenological research and was responsible for thousands of deaths.  

Meanwhile, the number of Thargoid incursions was increasing, perhaps in response to Salvation’s Guardian-based superweapon. This culminated in a simultaneous invasion of the Didio, Novas and Sosong systems in April 3308. These were major population centres for the Alliance, Empire and Federation respectively, with over ten billion lives at risk. 

Salvation and the superpower militaries responded in concert. Allied, Imperial and Federal capital ships were deployed to coordinate system defences, and also host the construction of three new superweapons. Interviews with the admirals in charge of the anti-xeno taskforces provided an insight into how much they now relied on Salvation. 

The superweapons were successfully detonated in all three systems, but this time there were no wreckages left behind. It was unclear if these particular weapons were less effective, or if the Thargoids had anticipated their use and retreated before their vessels could be disrupted. 

This was nevertheless hailed as another victory for Salvation. He announced that he was working on the next generation of the devices, which would “deliver a truly overwhelming strike against the Thargoid species”. Increased amounts of personnel, supplies and equipment were provided to Taurus Mining Ventures to hasten development of the superweapon. 

In May 3308 came a shocking revelation. Professor Alba Tesreau, former head of research at Aegis, received a tip-off leading to an abandoned outpost in the DG Canum Venaticorum system. This turned out to be a previously undiscovered base for INRA, the Intergalactic Naval Reserve Arm, which was formed to combat the Thargoids during the 32nd and 33rd centuries. 

The base provided evidence that INRA had contracted Azimuth Biochemicals to aid development of the mycoid virus. This was a highly controversial bioweapon used in 3151 to infect the aliens’ mothership, and which helped bring about the end of the First Thargoid War.  

Logs recorded by Dr Caleb Wycherley, the corporation’s vice-president of research, explained how he gained the nickname ‘the Witch’ after being half-blinded by a live Thargoid specimen. He then vowed that under his guidance, Azimuth would devote itself to the destruction of the Thargoids “If I must be humanity’s salvation, then so be it.” 

The former leaders of Aegis claimed that this verified their theory Salvation and ‘the Witch’ were the same person, and Azimuth had been operating in the shadows for decades. Professor Tesreau later revealed that the tip-off came from Subject D-2, the only survivor of the Project Seraph experiments to create a human test pilot for Thargoid ships. 

Some believed Aegis had fabricated these logs, since Dr Wycherley would now be over 200 years old. But although Salvation did not overtly confirm his true identity, Aegis’s suspicions were validated when Taurus Mining Ventures rebranded itself as Azimuth Biotech. Salvation described how Azimuth’s research division had survived as an independent organisation under his control, focused exclusively on Thargoid research and preparing for inter-species conflict. 

There was a public outcry that the man claiming to be humanity’s saviour was also responsible for the mycoid bioweapon, Project Seraph, the attack on the Alexandria, and other illegal or unethical activities. And yet there was little reaction from the Alliance, Empire or Federation, whose militaries were now fully committed to working with Salvation to defeat the Thargoids. 

In the past week, there have been signs that Azimuth Biotech is mobilising its forces and preparing for a large-scale operation of some kind. This may well tie in with Salvation’s promise to unveil a more powerful type of anti-xeno superweapon. We may soon learn if Azimuth can repeat history and deliver the decisive blow to end to the Second Thargoid War.
