:PROPERTIES:
:ID:       14354377-ec3f-4c5b-8402-f9b82ef86335
:END:
#+title: Xenological Project Receives Thargoid Artefacts
#+filetags: :Federation:Thargoid:galnet:

* Xenological Project Receives Thargoid Artefacts

/16 Jun 3308/

*Pilots’ Federation ALERT* 

A range of alien objects have been delivered to the Arque system for Professor [[id:8f63442a-1f38-457d-857a-38297d732a90][Ishmael Palin]]’s study of the Thargoids. 

The conclusion of the project was announced by Professor Palin: 

“I am highly impressed with the number of Thargoid probes, resin and sensors that were delivered to Abel Laboratory. Collecting and transporting these items can be a hazardous task, so I deeply appreciate the effort made by pilots to obtain them.” 

“It is becoming increasingly urgent to improve our understanding of the Thargoids’ biomechanical technology. There is no sign that hostilities are about to end, so the need to produce defences has become paramount. Only through ensuring our research focuses on up-to-date samples can we be sure that we are working as efficiently as possible.” 

Contributors can now collect their rewards from Baird Gateway in the Arque system. This includes Grade 5 engineered Heavy Duty Hull Reinforcement Packages for eligible contributors.
