:PROPERTIES:
:ID:       de026d2c-5e61-4804-a197-31bd6b3df11c
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/bb133a10-302d-44f0-bcee-982bfb17e436?resourceVersion=id%3A4895
:END:
#+title: Galactic Summit Proposal from Sirius Corporation
#+filetags: :3307:Federation:Empire:Alliance:galnet:

* Galactic Summit Proposal from Sirius Corporation

/18 Jan 3307/

Utopia’s ability to host a diplomatic conference for all three superpowers has been challenged by the Sirius Corporation. 

The megacorp’s counter-proposal was announced by CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]]: 

“With all due respect to Simguru Antal, his commune cannot match our level of resources. Sirius is far better placed in terms of logistics and security, and our navy will be able to ensure the safe transportation of all delegates.” 

“Furthermore, we already have excellent commercial relationships with the Alliance, Empire and Federation, and can therefore guarantee neutrality. Our recent philanthropic gesture at creating the Marlinist Colonies proves that we are an impartial, stabilising force for the whole galaxy.” 

Discussions regarding the conference have been ongoing in superpower and independent systems alike. Some leaders have decried it as a pointless exercise, while others view it as a rare opportunity for political cohesion. 

Sirius Corporation and Utopia’s propositions for a Galactic Summit are now being compared by potential attendees. However, [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]’s offer to host the conference at the actual galactic summit of Rackham’s Peak is not being seriously considered.
