:PROPERTIES:
:ID:       689a19b0-2ea7-441d-9a03-88a50d79102b
:END:
#+title: Community Goal: The Fight for Thoreau Orbital
#+filetags: :Empire:CommunityGoal:3302:galnet:

* Community Goal: The Fight for Thoreau Orbital

/15 Sep 3302/

Federal intelligence operatives have uncovered an Imperial plot to destabilise the Thoreau Orbital outpost in Obotrima. The starport is a major manufacturing centre for autonomous defence drones, more commonly known as skimmers. 

According to a leaked report, the Imperial organisation Chimechilo Empire League plans to disrupt skimmer production at Thoreau Orbital by flooding it with explosives. The Chimechilo Empire League has asked Imperial pilots to support the operation by delivering explosives to Thoreau Orbital. 

To counter this threat, the Obotrima Organisation has asked Federation-aligned pilots to deliver skimmer components and robotics to the outpost in order to manufacture new skimmers. 

Both operations are scheduled to run for one week from the 15th of September 3302.
