:PROPERTIES:
:ID:       f7fadb76-c5fa-4f32-8239-d90d218c9be0
:END:
#+title: Colonia Bridge Project Faces Possible Changes
#+filetags: :galnet:

* Colonia Bridge Project Faces Possible Changes

/19 Nov 3307/

Brewer Corporation is enhancing the travel corridor to Colonia, but details about the project’s next phase remain uncertain. 

Business-related newsfeed The Tau Ceti Journal published this feature: 

“There’s no doubt that Brewer Corporation always thinks big. It has enjoyed huge commercial success as a manufacturer of starports and outposts, and its Drake-class fleet carrier has been enormously popular.” 

“The Colonia Bridge is the megacorp’s most expensive undertaking yet, investing hundreds of billions of credits on the transportation infrastructure between the core systems and Colonia. More than one analyst predicted that the project might financially destabilise them.” 

“The first two phases proceeded on schedule. Before the end of this month, there will be a chain of 56 stationary megaships along systems between Alcor and Colonia.” 

“But there are rumours of a change of plans for phase three, which may be early next year. It is believed that Brewer Corporation is revising its plans based on the unexpectedly high levels of participation from the galactic community.” 

“In support of this, one company insider did reveal that more engineered frame shift drives are being manufactured, to be offered as incentives to contributing pilots in the third phase.”
