:PROPERTIES:
:ID:       d341e135-84c0-4511-9987-a0912c6da435
:END:
#+title: NMLA Megaship Becomes Marlinist Flagship
#+filetags: :3307:Empire:galnet:

* NMLA Megaship Becomes Marlinist Flagship

/16 Dec 3307/

The megaship Steel Majesty has travelled from Mudhrid to the HIP 22550 system and been renamed as Fairfax Vision. 

The Wells-class carrier was originally owned by the Neo-Marlinist Order of Mudhrid and used as a base for the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] terrorist group. After a military defeat, the vessel’s crew sought political asylum in the Marlinist Colonies.  

The Steel Majesty later became the hub for Minister Aaron Whyte’s followers during the Marlinist Civil War. More recently, [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] activists retook the ship and unsuccessfully tried to rescue their leader [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]]. 

The Marlin Standard published this statement from First Minister Octavia Volkov: 

“I am delighted that the Marlinist Consulate has negotiated with the Epsilon Fornacis Empire Group to arrange for this megaship to be returned to us. We are renaming it in honour of my predecessor Dr Jenna Fairfax, who led millions to safety after our mass exodus from the Empire.” 

“The Fairfax Vision is now controlled by the Free Marlinists of Carinae faction, but will represent the colonies’ parliamentary and diplomatic interests abroad. I hope that true Marlinism, and our progressive republican society, can now flourish peacefully.”
