:PROPERTIES:
:ID:       9727c0f1-d575-4841-9bb7-b1df79ab3171
:END:
#+title: Imperial Veteran Sceptical about Patreus’s Campaign
#+filetags: :galnet:

* Imperial Veteran Sceptical about Patreus’s Campaign

/09 Sep 3301/

Imperial Veteran Sceptical about Patreus’s Campaign 
 
Imperial senator Denton Patreus has taken a strong stance on Emperor’s Dawn, condemning the organisation and vowing to eradicate it from the galaxy, but responses to his statements have so far been mixed. Some have speculated that he is simply trying to curry public favour, while others have suggested he is attempting to draw attention away from his connection to Brendan Paul Darius, the emperor’s assassin. 

Now, the senator’s assertions have been questioned by a source from within the Empire itself - General Anthony Corvus of the Imperial Navy. In a statement given to the Imperial Herald, the general said: 

“We are clearly dealing with a well-organised and highly motivated cell organisation, and despite Denton Patreus’s optimism, in my opinion it is too early to make any predictions about its suppression. I have dealt with similar organisations in the past, and they can be surprisingly hard to extinguish. No sooner have you dealt with one cell, another appears somewhere else.” 

Senator Patreus was approached for a response to the general’s words, but declined to comment.
