:PROPERTIES:
:ID:       fc401bb3-8ea5-45e6-9f4c-78dff6a8085b
:END:
#+title: The Fate of the Dedicant
#+filetags: :Empire:Federation:Thargoid:galnet:

* The Fate of the Dedicant

/03 Aug 3309/

*Pilots’ Federation ALERT* 

The lost megaship Dedicant has been located in [[id:53a2feaa-72e3-40b0-ac54-624f2e33e305][HIP 19600]], with signs of Thargoid attack and all inhabitants missing.  

The Dedicant was being prepared by Federal authorities to deport imprisoned members of the Order of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] when it unexpectedly jumped into hyperspace. Pilots who helped decipher its fragmented distress call were informed of the recent discovery by the Imperial Navy. 

Executive Agent Jalen Locke of the Federal Intelligence Agency issued a statement: 

“We can confirm that the Dedicant has been discovered adrift in the [[id:53a2feaa-72e3-40b0-ac54-624f2e33e305][HIP 19600]] system. There is evidence that the Thargoids penetrated the hull in multiple locations, and thousands of escape pods were launched. Unusually, there are no bodies onboard and we have not been able to locate any of the escape pods. The whereabouts of all three FIA security teams and over 8,000 [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cultists cannot be determined.” 

“A series of personal logs, portraying some harrowing experiences, are helping us to piece together what happened during the Dedicant’s disappearance. We are liaising with military intelligence to learn more.” 

In related news, Aegis made an announcement on all public channels: 

“Independent observers have detected a new type of Thargoid vessel operating within the Maelstroms. Little is known of their capabilities as yet. They have been provisionally classified as a ‘hunter’ due to their size, which is similar to the Glaive.” 

“Aegis has only corroborated sightings of these ships in close proximity to the Thargoid Titans. However, we have received reports that they may be active elsewhere. Pilots are advised to exercise maximum caution if they encounter these vessels.”
