:PROPERTIES:
:ID:       2a13469a-ee0c-4e55-9cc7-38b7e2ed8a8f
:END:
#+title: Controversy at Film Festival
#+filetags: :Alliance:galnet:

* Controversy at Film Festival

/03 Aug 3305/

The [[id:e7c94b38-cdfb-48da-a1c4-cdad10c3371a][Leesti]] system played host to the second week of the [[id:b7d159ab-0ea2-454e-a22f-476c1e10ed5e][Alliance Festival of Culture]], where a new film production has caused minor controversy. 

The Alliance Tribune’s cultural correspondent Corinne Macintyre offered these details: 

“A grand celebration of cinematic art took place at George Lucas station, featuring a wide range of traditional and interactive media from dozens of systems.” 

“The talking point was undoubtedly ‘Unity’, a historical drama from award-winning director Hal Raskin. It portrays Alliance founders [[id:c46f5348-be85-4d06-bf04-12a9b812d0ad][Mic Turner]] and [[id:932c4921-da8d-4652-ab70-a19bdd49a8a3][Meredith Argent]] as rivals who faked their romance to rally political support.”  

“More traditionalist audiences – and not a few critics – took issue with the suggestion that the couple’s love was fraudulent, while others applauded it as bold and challenging. But this lively debate did nothing to dampen spirits at the event, which drew appreciative crowds.” 

The Alliance Festival of Culture is scheduled to continue over the next five weeks.
