:PROPERTIES:
:ID:       835e1aff-7445-4b0e-bd85-45a0e64553ff
:END:
#+title: Caine-Massey Wins Mining Contract
#+filetags: :galnet:

* Caine-Massey Wins Mining Contract

/20 Jan 3308/

*Pilots’ Federation ALERT* 

The Caine-Massey corporation has beaten Torval Mining Ltd to retain a mining contract in the Dulos system. 

Competing campaigns were waged by the two rivals for the rights to supply ore and mined materials to many local subsidiaries. 

Johann Fleischer, vice president of Caine-Massey, declared their victory: 

“We wish to thank the large number of pilots who delivered bromellite, samarium and gallite. Thanks to your hard work, our contract has been renewed for another decade. I like to think that we have also secured the honour of [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] by stalling the Empire’s plans.” 

Rewards for contributors to Caine-Massey are now available for collection at Smith Port in the Dulos system. 

Torval Mining Ltd also received many deliveries of materials but in insufficient quantities to secure the contract. Constantia Torval has confirmed that the pilots who supported their initiative can collect payment at the Pride of Bitterwood megaship.
