:PROPERTIES:
:ID:       e9fcd6de-9808-4c04-bce6-30dbbd993008
:END:
#+title: NMLA Attacks Marlinist Starports
#+filetags: :3307:Federation:galnet:

* NMLA Attacks Marlinist Starports

/29 Jul 3307/

*Pilots Federation ALERT* 

The [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] has bombed two starports in the HIP 22550 and Hyades Sector RO-P b6-6 systems in the Marlinist Colonies. 

Explosive devices were detonated at both Stillman Hub and Tilman Point stations. As is characteristic of weapons used by the NMLA, caustic enzyme payloads caused widespread corrosive damage. 

The combined death toll is in the tens of thousands, with many more injured. There are unconfirmed reports that First Minister Jenna Fairfax is among the fatalities. 

The following message was broadcast via [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] propaganda channels: 

“Why are they bombing their own homes? Why would [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] kill his own people? Because they are not our homes! Not my people! They are prisons, not colonies, where traitors to the cause beg for scraps from those who exiled them. True Marlinists will never stop fighting until the Republic of [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]] is restored.” 

The attacks are believed to be in response to Verity Dexter failing to win a public vote to lead the Marlinist Consulate, where she would have represented the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] political wing.  

Prime Consul Kayode Tau, the elected candidate, announced: 

“I call upon the galactic community to provide humanitarian aid to Stillman Hub in HIP 22550 and Tilman Point in Hyades Sector RO-P b6-6. We urgently require ships to evacuate the people trapped within these starports to safety.”
