:PROPERTIES:
:ID:       e680b626-889a-4f75-92db-049265a4ad1d
:END:
#+title: The Adamastor Enigma
#+filetags: :galnet:

* The Adamastor Enigma

/19 Apr 3307/

*Pilots Federation ALERT* 

Commanders have reported receiving anonymous instructions regarding the 200 year old derelict megaship orbiting Chukchan 5 b. 

A communications beacon stored onboard the Adamastor began receiving and rebroadcasting an encrypted signal on the 8th of April. Efforts by authorities to trace and decipher the signal proved unsuccessful. 

However, a number of independent pilots claim to have been contacted by an anonymous source, who provided an access key to decode the Adamastor signal. 

Commander Rex Trevelyan gave this statement to Vox Galactica: 

“Not long after arriving in the Chukchan system, my ship received a message from someone calling himself ‘Salvation’. He provided a decryption key, and when I downloaded the signal from the Adamastor it became readable. It seems to be an automatic SOS from its sister ship, the Hesperus.” 

“I’ve heard that some Commanders have made sense of the navigational data in the signal. It feels like pilots are being recruited for something, but who exactly are we working for?” 

The Pilots Federation has begun an inquiry into the situation. The identity of ‘Salvation’ remains unknown, but there are reports that the Adamastor signal contains data that has led to its sister ship.
