:PROPERTIES:
:ID:       1018df14-9c51-4fbc-8ce0-4492b5942f3e
:END:
#+title: Faction Issues Appeal for Onionhead
#+filetags: :Empire:Federation:3301:galnet:

* Faction Issues Appeal for Onionhead

/19 Nov 3301/

A faction known as the Drug Empire of Xelabara has issued a request for the controversial narcotic onionhead. The drug was once a significant trade commodity, but it suffered a setback last year when former Federal President [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] declared it illegal in Federal space. Rooney 'Rush' Romero, a spokesperson for the Drug Empire of Xelabara, explained that the appeal is partly intended to revitalise the market: 

"The fact is that people want onionhead. The Federation might not like it, but that's their problem – our organisation is well within its rights to establish a trading operation in Xelabara. Trouble is, although we've got the money, we don't have the merchandise. That's why we're offering generous incentives to pilots who deliver onionhead to our base of operations in Xelabara." 

The Drug Empire of Xelabara is not believed to be connected to the Farmer's Cooperative of the Kappa Fornacis system, onionhead's main producer. The Federation has not released an official statement concerning the request.
