:PROPERTIES:
:ID:       f0b5c220-d295-4d3e-aa48-af660980db08
:END:
#+title: Maelstrom Protection Technology Undergoes Testing
#+filetags: :Thargoid:galnet:

* Maelstrom Protection Technology Undergoes Testing

/20 Feb 3309/

Aegis has produced a prototype module that increases a ship’s ability to survive within caustic environments. 

Professor Alba Tesreau, head of the newly reformed agency, published this statement: 

“The blueprints provided by [[id:7af58443-6856-4aa9-89ff-89c94bd63aa7][Petra Olmanova]] have been rapidly developed by Aegis’s newly acquired chemical engineers, metallurgists and ship technicians. Utilising their combined skills, they have constructed a working prototype.” 

“This new module functions along similar lines to a heatsink launcher. It is designed to channel the corrosive reaction experienced within a Thargoid Maelstrom to specific replaceable anodes prior to ejection, thereby extending a ship’s range and operating time. We hope this will allow more data to be acquired about these mysterious objects.” 

“Aden Tanner has volunteered to personally pilot the ship in the live tests taking place this week. Time is of the essence, since the humanitarian cost of the Thargoid invasions rises every day.” 

Rear Admiral Daniel Parry, the Federal Navy’s military liaison to Aegis, commented: 

“I’ve served under Admiral Tanner, and his involvement with these test flights doesn’t surprise me one bit. He takes pride is never sending personnel on assignments he wouldn’t undertake personally. But he’s also sending a message: Aegis will no longer rely so heavily on independent pilots risking their lives. While Commanders of the Pilots’ Federation are still our most adaptable and reliable field agents, Aegis will seek to work alongside them wherever possible.”
