:PROPERTIES:
:ID:       a1bf5caa-a944-48c4-a0cf-3ad4bbcd4ce1
:END:
#+title: Lugh Prepares for War
#+filetags: :3301:galnet:

* Lugh Prepares for War

/10 Mar 3301/

Crimson State Group representatives who were still present on Alioth were forced to make a hasty departure earlier today, as reports of Federal checkpoints being established around local exit points began to hit [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] blogosphere.  

It would appear that [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] means to finally show its hand in what has been a long and arduous game of poker between the Federal goliath and a small but proud people willing to defy the domination of their oppressors.  

In the wake of his unsuccessful attempts to reach a favourable conclusion with representatives of the Alliance, Ambassador Éamonn Uí Laoghaire had this to say: 

"Lugh is a sovereign state. This is an undeniable truth. An error does not become truth by multiplied propagation, nor does truth become error because nobody sees it! Though the storm clouds gather around us, it has been written in our ancient 'Leabhar Gabhála Lugh' that the Sons of Conn will come to Lugh’s aid at his time of direst need. That also is a universal truth."
