:PROPERTIES:
:ID:       f8d10ff1-769f-4b7f-b375-723a37d2b6aa
:END:
#+title: Marlinists Reject Accusations of Terrorist Links
#+filetags: :3307:Empire:galnet:

* Marlinists Reject Accusations of Terrorist Links

/23 Mar 3307/

The Marlinist Parliament has refuted widespread allegations of supporting or concealing members of the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] paramilitary group. 

Fuelled by media speculation, many political and military leaders have suggested that the Marlinist Colonies should be occupied or destroyed to take revenge for the recent bombings. However, there is no evidence that these systems have any direct connection to the NMLA. 

First Minister Jenna Fairfax gave this statement to Vox Galactica: 

“The starport attacks were as sickening and terrifying to us as to the rest of the galaxy. The Neo-Marlinist Liberation Army follows a twisted creed that has no bearing on true Marlinism.” 

“We have sent our own intelligence team to join [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][ACT]], led by Captain Milo Castile of the Marlinist Constabulary. It is vital that we all work together to end the NMLA’s campaign of terror.” 

There was also a comment from fellow parliamentarian Aaron Whyte: 

“I understand it’s human nature to seek a villain, but we should remember that the Neo-Marlinist cause has sound political foundations. The Empire suppressed all republican movements for centuries, imprisoning and executing far more people than those who died in the ‘Nine Martyrs’.”
