:PROPERTIES:
:ID:       cda382bb-500b-4ae1-8210-cc68aa5e49ad
:END:
#+title: Superpowers Plan to Replace Aegis
#+filetags: :galnet:

* Superpowers Plan to Replace Aegis

/18 Jan 3308/

The Alliance, Empire and Federation have accepted the Baumann Report’s recommendation to permanently shut down Aegis. 

The independent inquiry’s findings on the organisation’s failings will result in Aegis being immediately shut down. However, Chief Administrator Carter Armstrong has cautioned that “full demobilisation of staff, ships and resources might take several months”. 

Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] has successfully obtained senatorial approval for an increased military budget, to allow the Imperial Navy to directly take on the role played by Aegis. 

Fleet Admiral Tayo Maikori likewise confirmed that the Federal Congress has ordered the creation of a new naval strike force. On his own authority he has also commissioned an investigation into Salvation, following Ram Tah’s testimony regarding the nature of the anti-xeno superweapon. 

Admiral Nikolas Glass, who was recently appointed to the Council of Admirals, stated that the Alliance Defence Force and Sirius Navy will work in conjunction to fulfil Aegis’s purpose. 

Xenological research laboratories set up by Professor Alba Tesreau will now transfer their work to specialist departments in the Holloway Bioscience Institute, Imperial Science Academy and Olympus Village University. In 3304 the Thargoids made targeted strikes against Aegis’s labs, but all three institutions have made assurances that the new locations will have the highest security.
