:PROPERTIES:
:ID:       dd732ad6-cf06-47b1-a09f-55d6746f9dc4
:END:
#+title: The Talons of Justice
#+filetags: :3301:Empire:galnet:

* The Talons of Justice

/15 Apr 3301/

During an exclusive interview with the popular Imperial politics programme, ‘Question Everything’, Senator [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] provided some new insight into the ongoing investigation into the attempted assassination of Emperor [[id:3cb0755e-4deb-442b-898b-3f0c6651636e][Hengist Duval]]. 

“The fact that anyone would attack the Emperor, in his own palace, when for all intents and purposes he’s already on his deathbed, is symptomatic of a very serious sickness within our society.” 

“Certain elements, criminal and otherwise, see the current situation as an opportunity to advance their own agendas. At a time when we should be standing together as one nation, one voice, instead we find ourselves fractured and alone.” 

“It doesn’t need to be this way. Together we are stronger than those who wish to seek to tear us down. “ 

“As proof of that, information provided by Imperial citizens loyal to the ideals upon which our nation was founded has proven invaluable in the hunt for those who sought to strike against us. In particular, agents of the Imperial Court have uncovered two potential locations which may well hold the answers we seek.”  

“I call on any pilot who has ever dreamed of honouring the legacy of our great Empire. Assist me in teaching the Emperor’s wayward sons exactly what it means to truly be a member of the greatest nation in the galaxy.” 

Following the interview, word arrived at GalNet that citizens wishing to work with the Princess’s new investigative task force can sign up to do so at either of the following locations: 

Xuesen Orbital in Nehet 

Kowal Dock in Mictlan
