:PROPERTIES:
:ID:       4f3edd30-e48f-4655-9d59-66c15052d351
:END:
#+title: Worshipping the Thargoids
#+filetags: :Thargoid:3304:galnet:

* Worshipping the Thargoids

/16 Jun 3304/

A fringe religion that worships the Thargoids has come under the spotlight in a new academic article. 

The author, Dr Alfred Ulyanov, is a leading expert in exotheology. He summarised his work for the media: 

“A recent report by Gethin Okonkwo highlighted the emergence of doomsayer cults in response to the return of the Thargoids. But few are as strange as my current object of study – an organisation that considers the Thargoids to be not merely alien, but divine.” 

“This mysterious sect doesn’t have a formal name. The central tenet of its faith is that the Thargoids we have encountered so far are messengers – dark angels sent to prepare us for the true sacred presence, which will soon enter our plane of existence from another universe. They refer to this as the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]].” 

“As with many monotheistic belief structures, this cult considers the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] to be unknowable and omnipotent, but also apocalyptic. Only true believers such as themselves will survive its manifestation.” 

“Visiting one of the cult’s hive-chapels is an unsettling experience. Aside from a few pulsing green lights they are very dark, and most surfaces are covered in a black coral-like substance. The congregation’s prayers are directed toward an altar resembling the starfish shape of Thargoid vessels, almost like an octagonal crucifix. It’s impossible to ignore that the entire place reeks of ammonia.” 

“Cult members tend to wear simple hooded robes with no markings. They are intense and resolute, but many look unhealthy. It seems that this lifestyle attracts those on the very edge of society, whose low self-esteem leaves them vulnerable to beliefs that erode their identity.” 

“As an exotheologian, I am of course fascinated by the sociological impact of non-human influences. But even for a scientist, it is difficult not to feel pity, and perhaps a little revulsion, for those who identify more with a hostile species than with their own people.”
