:PROPERTIES:
:ID:       34c2a995-41ba-4ff6-afc6-ec2592b56995
:END:
#+title: Head of Aegis Makes Public Address
#+filetags: :Empire:Federation:Thargoid:3309:galnet:

* Head of Aegis Makes Public Address

/23 May 3309/

Professor [[id:c2623368-19b0-4995-9e35-b8f54f741a53][Alba Tesreau]] has broadcast a formal statement discussing the past, present and future of [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]].

Independent journalist Allan Mantle reported on the declaration for [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]]:

“The tremendous escalation of the Thargoid war makes [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] more open to scrutiny than ever. By delivering a personal message to the public, Professor Tesreau exhibits the transparency and accountability that the agency previously lacked. Indeed, it’s to her credit that the mistakes of the past are not glossed over.”

“Some will also consider it noble that Tesreau avoids mentioning how she opposed the superpowers shutting down [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] in favour of working with [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]]. Others will recognise her moral high ground as mere politics. The Allied, Federal and Imperial coordinators for [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] are all duly applauded, a tip of the hat to those who helped her resurrect the organisation.”

“Recent Thargoid discoveries are mentioned, with two having been formally classified since her speech was recorded: the Glaive-class hunters that pursue human ships, and the Revenant-class drones patrolling settlements in conquered systems. Naturally, [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]]’s top priority are the Thargoid motherships, which Tesreau formally assigns the designation of ‘Titan’. The statement reveals that work is underway to modify Professor Palin’s xeno scanner to gather data on these alien capital ships.”

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] also delivered a statement:

“I have nothing but praise for Professor Tesreau’s leadership of [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]]. She has transformed a once-failing initiative into the vanguard of humanity’s defence. I am impressed and inspired by her tireless determination, which is why I sought the position of Imperial representative in the organisation. My discussions with Tesreau have convinced me that the new iteration of [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] has addressed the concerns I once held over its strategic direction.”

“I also want to take this opportunity to honour those who made the ultimate sacrifice when resisting the Thargoids’ military might. These courageous souls will never be forgotten. We all still have much work to do to protect those we care for.”

Pilots will find the [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] Statement waiting in their ship's inbox service.
