:PROPERTIES:
:ID:       a096245c-e5f5-456d-8ef6-a8513af8ef29
:END:
#+title: Pleiades Rescue Operation
#+filetags: :3304:galnet:

* Pleiades Rescue Operation

/10 Aug 3304/

After sustained [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] attacks on civilian targets in the Pleiades Nebula, system authorities have launched a rescue operation to locate and recover survivors.  

The operation is being coordinated by Superintendent Marla Poulsen of Aegis Research, who made this announcement: 

“System authorities in the Pleiades have been channelling their resources into combating the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] menace. As a result, search-and-rescue initiatives have been neglected, but we are determined to plug that gap. That means a lot of civilians rescued from escape pods, which also means a lot of hungry mouths to feed, so we’ll need to bolster our current food stocks as a precautionary measure.” 

Pilots are requested to recover occupied escape pods and damaged escape pods. In addition, the following food resources are also required: fruit and vegetables, grain and food cartridges. Both recovered pods and food stocks should be delivered to Donar's Oak in the Pleiades Sector IR-W d1-55 system. 

The campaign begins on the 9th of August 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
