:PROPERTIES:
:ID:       d6f23e53-bac5-4a6c-9741-2cda3e070996
:END:
#+title: Fire Destroys Supratech Facility
#+filetags: :3304:galnet:

* Fire Destroys [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] Facility

/08 Sep 3304/

A manufacturing complex owned by computer company [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] has been destroyed by fire. 

All on-site personnel managed to escape the blaze without injury. Emergency crews were soon in attendance, but were unable to prevent the fire from swiftly consuming the facility. 

Supratech CEO [[id:b62c9e2e-8079-44bc-a30d-d192076162e6][Scorpio DeVorrow]] made this statement: 

“I regret to announce that the fire has ruined our main production complex. Dozens of prototype Torc units were also irreparably damaged. This is a severe setback in the development of our new design.” 

“Investigators have been unable to pinpoint the cause of the blaze, or to explain why the fire-suppression system in our state-of-the-art complex malfunctioned so completely. Along with the security cameras, internal alarms and thermal sensors.” 

Maddox Hurd, head of rival company [[id:46e9f326-2119-4d5b-a625-a32820a44642][Herculean Machines]], commented: 

“I’m glad to hear that everyone made it out okay. But I have to say, if [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]]’s facilities are that poorly designed, I’d hate to imagine what their products are like.” 

Both companies are due to unveil new personal computing devices at the [[id:9d064da0-7be3-4c7b-99ad-0edd1585d4ca][Rackham Ultratech Expo]] in October, although it is now unclear if [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] will take part in the trade show.
