:PROPERTIES:
:ID:       0b121dd8-4675-437f-b98b-10fb66c2b229
:END:
#+title: Securing the Borders in the Ceti Sector
#+filetags: :Federation:3301:galnet:

* Securing the Borders in the Ceti Sector

/24 May 3301/

The return of Onionhead to Panem may be a blessing for the farmers of Kappa Fornacis, but for their neighbours, the Fornacian dream has turned into a living nightmare. 

“It’s not right,” one concerned resident of the nearby BD-18 394 system told GalNet. “Sure, they’re doing alright over there in Kappa F, but what about us? What do we get? I’ll tell you, smugglers and pirates, that’s what.” 

Crime has spiralled out of control throughout the Ceti Sector, with many locals echoing the sentiment that the Farmers Union of Kappa Fornacis should be held responsible for attracting such unsavoury characters to what was once a peaceful area. 

In an attempt to clean up the sector, the Independent Autahenetsi Labour Party are currently offering a range of bonus payments to any Bounty Hunters who sign up to act as Federal Ceti Sector Security Services Agents at Artyukhin Ring in Autahenetsi.
