:PROPERTIES:
:ID:       9d2bccb7-572f-4b90-8961-771704fe7231
:END:
#+title: [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] Turn Attention to Inhabited Systems
#+filetags: :galnet:

* [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] Turn Attention to Inhabited Systems

/12 Sep 3308/

*Pilots’ Federation ALERT* 

Swarms of [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] vessels have invaded the 42 n Persei, Chun Pindit and Tekkeitjal systems in an apparently coordinated attack. 

Vox Galactica published this report by field correspondent Ernesto Rios: 

“Since the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] conquered HIP 22460 a month ago, their presence has gradually expanded in all directions. But these are the first inhabited systems to be invaded since the Proteus Wave incident, threatening a combined population of over seven million people.” 

“The governing factions of these systems – Sirius Inc, SI Terraforming and Tekkeitjal Public Corporation, respectively – are expected to host defensive operations against the Thargoids. None are aligned to any superpower, and so have no formal navy to support these efforts.” 

“As yet, none of the starports in 42 n Persei, Chun Pindit or Tekkeitjal have been directly attacked. Civilians have been instructed to remain calm but many are evacuating, fearful of the stations suffering caustic enzyme bombardment.” 

“This is a notable difference from previous [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] incursions, and has led some military figures to theorise on the alien’s new strategic objectives.” 

Defensive operations are being orchestrated from the starports Bennington's Rest, Samuda Terminal and Riemann Colony. [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] combat bonds can be handed in at these locations for increased credit rewards.
