:PROPERTIES:
:ID:       4772f941-824e-4e75-b11d-af1390984980
:END:
#+title: Kincaid Granted Command of Zaonce Fleet
#+filetags: :Alliance:galnet:

* Kincaid Granted Command of Zaonce Fleet

/18 May 3305/

President Gibson Kincaid has been named commander-in-chief of the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] fleet in the Zaonce system. 

Journalist Vanya Driscoll reported on the development for The Alliance Tribune:  

“Admiral Frederick Yamamoto has announced that the Zaonce fleet now takes orders directly from the president, in direct breach of the existing ADF command structure.” 

“The move is widely perceived to be a deliberate show of strength from President Kincaid, who is currently under investigation for illegal campaign funding. Admiral Yamamoto is known to be a personal friend to Kincaid, from the latter’s time as governor of Zaonce.” 

“The Council of Admirals has demanded that Yamamoto rescinds this decree. Admiral Rachel Ziegler condemned the decision as ‘political grandstanding that borders on treason’.” 

While President Kincaid has accepted the authority, he has yet to issue any orders to the ADF fleet stationed in Zaonce.
