:PROPERTIES:
:ID:       137db438-138a-436d-bfd4-adc1ce35a9a4
:END:
#+title: Jokers’ Deck Hit by Art Thief
#+filetags: :galnet:

* Jokers’ Deck Hit by Art Thief

/12 Oct 3307/

The secretive gambling circle of the super-rich has been raided by the notorious criminal known only as the Winking Cat. 

The information was revealed by Francesca Wolfe of the Wallglass Investigations Agency, who infiltrated the event. Her report, which was relayed from an unidentified location, has been published by her fellow detective Erik Gunnarson. 

“I’m not sure this will reach Gunnarson, but I must try. After the security alert the staff started getting their IDs checked, which might have revealed mine to be fake. I managed to slip out of the warehouse and into an abandoned industrial district. I still don’t know what planet I’m on, but I’ve found an old comms transmitter to send this message.” 

“Before I escaped, I learned what had caused the alert. There was a VIP ceremony involving the group’s most precious possession: an ancient Joker playing card. Apparently this has been passed between senior members of Jokers’ Deck for centuries, always held by the current host. But when Lexi October publicly unveiled the card, she found it had been replaced by one showing a different graphic – a winking cat.” 

“It’s two years since we’ve heard from the galaxy’s greatest larcenist, but there’s no doubt that only the Winking Cat’s legendary skills could have circumvented their security systems. I’m fascinated that a battered scrap of card has greater value than any of the billion-credit items being wagered here.” 

“Guards are searching for the thief now. I hope I can get off-world before they find me instead. They’re armed to the teeth and not in the mood to talk…”
