:PROPERTIES:
:ID:       ce59bea4-504e-4c8e-a5cc-b1e49f7a69c8
:END:
#+title: Aisling Duval Rejects Nova Imperium
#+filetags: :galnet:

* Aisling Duval Rejects Nova Imperium

/21 Dec 3304/

Princess Aisling Duval has publicly rejected the isolationist group Nova Imperium and its figurehead, Hadrian Duval: 

“These extremists cause only division. Hadrian may well be the grandson of Hengist Duval, but that hardly makes him suited to the throne. Arissa has been silent for too long – she must act quickly to resolve this volatile situation.” 

Senator Zemina Torval responded: 

“Much to my surprise, I find myself in agreement with Princess Duval. The notion of an independent pilot becoming ruler of the Empire is preposterous. I am confident that the Emperor will respond accordingly.” 

Despite this united front, Senator Pal Vespasian stated: 

“Many senators are willing to recognise Hadrian Duval as Emperor-in-waiting. Nova Imperium is now a legitimate political movement with several million supporters. The only way the Empire will survive is by accepting the Imperator’s proposals.”
