:PROPERTIES:
:ID:       50f40ec2-169d-4b5b-8305-4a0c701b7c5b
:END:
#+title: Galactic News: Kahina Loren Implicated in Patreus Assassination Attempt
#+filetags: :3301:Empire:3302:galnet:

* Galactic News: Kahina Loren Implicated in Patreus Assassination Attempt

/19 Sep 3302/

Sources close to the Imperial Senate have released a statement indicating that Lady Kahina Tijani Loren, erstwhile senator of the Prism system, has been charged in connection with the attempted assassination of Admiral [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]]. 

Prior to this development, Lady Kahina had not been heard from since mid 3301. Details of her recent activities are shrouded in mystery, although under the alias Commander [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] she has been linked to various revolutionary organisations, including the Children of Raxxla, the Phoenix Group, the Dark Wheel and now Emperor's Dawn. 

After Lady Kahina went missing in the [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] system last month, the Children of Raxxla attempted to destabilise the system's economy to force system authorities to reveal her whereabouts. 

"Her intentions are clear," said a reporter for The Imperial Citizen. "She hates Patreus for his takeover of the Prism system – which I might point out was entirely legal – and harbours ridiculous delusions of becoming Emperor. She's been sowing seeds of discontent everywhere she goes. As we reported last month, she is dangerously unstable and an irresponsible warmonger. Now that she's been caught, she should be dealt with harshly. The same applies to the factions loyal to her." 

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] also addressed the arrest, saying: "I was always suspicious about her. Now her true colours have been revealed. I hope she receives a just punishment for her atrocious crimes. I wouldn't be surprised to discover she was behind the instability of the past year. My thanks go to our loyal Imperial security services for their diligence." 

Lady Kahina has reportedly been moved to the Achenar system to await trial.
