:PROPERTIES:
:ID:       4131e17b-7899-45ed-8b58-f53be28405d8
:END:
#+title: Patreus Highlights [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] Tactics
#+filetags: :galnet:

* Patreus Highlights [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] Tactics

/13 Sep 3308/

Senator Denton Patreus, fleet admiral of the Imperial Navy, has discussed the Empire’s new priorities following the Battle of HIP 22460. 

During an exclusive interview with the Eye on Achenar newsfeed, Patreus said: 

“Her Majesty the Emperor has decreed that our military priority is to defend systems within the Empire. The Imperial Navy’s production and training facilities have increased their efforts to redress the loss of three Majestic-class interdictors, along with tens of thousands of naval crew.” 

“I’ve conducted my own tactical analysis of what took place in the HIP 22460 system. Salvation’s interest in the area with historic [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] ruins was no coincidence, I feel. He was something of a showman, and planning a final victory in the aliens’ own territory fits what we know of his ambition.” 

“The [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] attacked human fleets with ferocious intent, but the fact they never assaulted the Proteus Wave site strikes me as remarkable. Even when considering the stout resistance, we offered. There is saying among military strategists: Never interrupt your enemy when he is making a mistake.” 

“In hindsight, it seems possible that the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] allowed the Proteus Wave to be installed at their surface site, with the foreknowledge that they could turn the superweapon against us. Perhaps Salvation unknowingly constructed his own execution chamber.” 

“I’m convinced that we face an alien intelligence with a strategic competence to match any human opponent. [[id:77cf2f14-105e-4041-af04-1213f3e7383c][The Empire]] cannot underestimate this enemy ever again.”
