:PROPERTIES:
:ID:       3216f71e-30b3-4556-96df-1d9c146ef2d5
:END:
#+title: Community Goal: Free the Slaves
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: Free the Slaves

/18 Feb 3302/

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] has announced the creation of new a colony for former slaves in the Uibuth system. According to a statement from the princess' press liaison, all slaves admitted to the colony will be liberated and re-educated, and offered the protection of forces loyal to Her Royal Highness. 

A spokesperson for the [[id:8da12af2-6006-4e7e-a45e-7bf8b2c299c8][Prism]]atic Imperium, which is overseeing the initiative, revealed more about the historic campaign: 

"This morning our most noble lady Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] returned from [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]] to [[id:1cfcec06-5ac3-40b6-b08a-13086eb88466][Cubeo]] III. Upon arrival she immediately requested a private meeting with the leadership of the [[id:8da12af2-6006-4e7e-a45e-7bf8b2c299c8][Prism]]atic Imperium. During the meeting, the princess emphasised her enduring wish to bring an end to slavery within the empire." 

"To this end, Princess Duval instructed Lord Corwin Ryan Head of the [[id:8da12af2-6006-4e7e-a45e-7bf8b2c299c8][Prism]]atic Imperium and Count Vickershaft of the Navigators Guild to make preparations for the founding of a new colony, where freed slaves could live in comfort and safety. With the support of independent factions at D'Arrest Station in the Uibuth system, the colony was duly established." 

The spokesperson went on to outline how the galactic community could support the new colony: 

"At the behest of the Princess, the [[id:8da12af2-6006-4e7e-a45e-7bf8b2c299c8][Prism]]atic Imperium is asking pilots to transport slaves of all types to the new colony, where they will be emancipated and re-educated. Significant rewards have been promised to pilots who contribute to the initiative." 

The initiative begins on the 18th of February 3302 and is expected to run for one week.
