:PROPERTIES:
:ID:       d549db5e-022a-4dcc-846f-56aa3a17a70b
:END:
#+title: Presidential Candidate Murdered
#+filetags: :3304:galnet:

* Presidential Candidate Murdered

/05 Oct 3304/

Fazia Silva, one of the three candidates in [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] presidential race, has been found dead. She is believed to have been murdered. 

Inspector Erin Sangster of Alliance Interpol informed the media: 

“Ms Silva’s body was found in a room at Hume Orbital, where she was staying during her presidential campaign. Medical teams detected traces of poison, making this a suspected homicide.” 

There has already been speculation that this was a political killing, motivated by Silva’s proposed changes to Alliance financial policy. The entrepreneur also had fierce rivals in the business world. 

Her sister Tashmira Silva, who has been overseeing the Silva corporate empire, stated: 

“Our family is devastated – we can’t believe that Fazia has been taken from us. I will honour her by continuing to run the companies that she made so successful.” 

Condolences have been delivered by Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] and both of Ms Silva’s election rivals, Gibson Kincaid and Elijah Beck. President Kincaid said: 

“This tragedy constitutes a direct attack on our democracy. The Alliance’s enemies will do anything they can to destabilise us, including murder. If we are to fight back, we will need strong leadership.”
