:PROPERTIES:
:ID:       592b9b99-7198-4029-979d-e19d08bd0c06
:END:
#+title: Arissa Rescued from Year-Long Captivity
#+filetags: :galnet:

* Arissa Rescued from Year-Long Captivity

/09 Feb 3308/

Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] has been found alive after being secretly imprisoned by the private military firm Darkwater Inc. 

The Imperial Herald published a special report on recent events: 

“The absence of the Emperor from public life for over a year has prompted much speculation. The Senate claimed that she was being kept safe from assassination attempts by the NMLA, and that they remained in contact with her.” 

“In truth, she was being held captive by the NMLA’s secret benefactors. This group of Imperial senators referred to themselves as the Lords of Restoration. They were revealed only after ACT recruited independent pilots to help decipher the terrorists’ dark-comms network.” 

“Chancellor Blaine immediately ordered the Imperial Guard into battle against Darkwater soldiers. A ship fleeing from the Summerland system was intercepted, aboard which was a cryogenic pod containing the Emperor herself. She was swiftly returned to Capitol, and is currently under the care of the Imperial Palace medical team.” 

“The IISS has launched a security operation based on ACT’s information. This reveals that groups within the Senate, Darkwater and Imperial Intelligence formed a long-running conspiracy to fund and empower the NMLA. Senators Alberto Gereon, Karl Nerva, Ursula Torquatus and several others have been placed under arrest.”  

“ACT has stated that it will provide additional information soon.”
