:PROPERTIES:
:ID:       fc4a2e23-78d8-49b9-a740-c65bdb1d64fd
:END:
#+title: Galactic News: Federal Campaign Resumes
#+filetags: :Empire:Federation:3302:galnet:

* Galactic News: Federal Campaign Resumes

/11 Jul 3302/

Four days ago, the [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][Federation]] launched a campaign to construct a new [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][Federal]] outpost in the Segovan system. Federally aligned pilots were invited to contribute construction materials to the campaign, but the request proved controversial, with various sections of the galactic community asking why the Federation was expanding towards the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] sector.

Not long after the campaign began, [[id:77cf2f14-105e-4041-af04-1213f3e7383c][Imperial]] pilots began targeting traders delivering cargo to the Ramsbottom Hub starport. As the situation escalated, system authorities imposed a system-wide lockdown in an attempt to maintain order. Ramsbottom Hub was closed, and pilots wanting to deliver materials were left with no way of contributing to the campaign. Authorities insisted that the lockdown was intended to keep the system's inhabitants safe, but Federal pilots were understandably frustrated.

Recent reports from Segovan indicate that the Federation has now despatched a deputation to the system – including two [[id:3146c49e-4aa8-4061-9ab2-1d9da2b0bff5][Farragut]]-class Battlecruisers – and convinced system authorities to lift the lockdown. A Federal spokesperson said:

"The lockdown had a negative impact on our campaign, certainly, but the huge quantity of material delivered to Ramsbottom Hub prior to the lockdown means we are still confident we can meet our baseline targets."

"With the lockdown now removed, we would like to renew our plea to Federally aligned pilots to support this vitally important initiative."
