:PROPERTIES:
:ID:       e3dd85c2-5249-42c9-86c1-31069194f93d
:END:
#+title: New Onionhead Variant Reaches the Market
#+filetags: :3307:Federation:galnet:

* New Onionhead Variant Reaches the Market

/23 Jul 3307/

*Pilots Federation ALERT* 

Onionhead gamma strain is now available in selected industrial anarchy systems. 

Following the Kumo Council’s initiative, enough product was manufactured to supply approximately 10% of all industrial-based markets controlled by anarchic factions. Unlike previous versions of onionhead, this variant is not listed as a rare commodity. 

Adalyn Cross, a journalist for Vox Galactica, reported: 

“Onionhead gamma strain is being marketed to the public for medicinal use, but most customers are under no illusions regarding its real benefits. The Coalition for Legalisation claims that it is ‘no more harmful or addictive than alcohol or coffee, with potential psychological and palliative benefits’.” 

“This has not prevented many authorities, especially in the Federation, from demanding that it remain universally outlawed. It is currently illegal in all but anarchy jurisdictions. There are serious concerns that it may act as a gateway drug to more harmful substances. Security services are also unhappy about the extra revenue flowing into [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]’s coffers.” 

“Some logistics experts noted that onionhead gamma strain was distributed with surprising speed. It is already being reported as available from the following systems: Alici, Baraswar, Kishpakho, [[id:f99cc815-f736-48e1-863d-7e50b14b7273][Nastrond]] and Nocori. It’s been suggested that [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] is secretly ferrying shipments of the drug via its freight transportation network, and is part of the deal between the Kumo Crew and the Blue Viper Club. Sinclair Faraldo, VP of Corporate Marketing, rejected this claim as ‘absurd and libellous’.”
