:PROPERTIES:
:ID:       554cd284-d876-4e70-b7b1-76929a8005fa
:END:
#+title: A Profile of Jordan Rochester
#+filetags: :Empire:3304:galnet:

* A Profile of Jordan Rochester

/07 Jul 3304/

Responding to public interest in Princess Aisling Duval’s fiancé, Federal Ambassador Jordan Rochester, political journalist Cassia Carvalho has compiled a profile for The Imperial Herald: 

“Jordan Rochester is now a household name throughout the Empire, though few were aware of him prior to his engagement to Princess Duval. But in the Federation, the Rochesters have been associated with success for over two hundred years.” 

“The Rochester name can be traced back to self-made tycoon Apollo Rochester, who was the biggest landowner on Biggs Colony in the Altair system. Each generation since has strived for fame and wealth, and the expression ‘as rich as a Rochester’ has become common parlance.” 

“The family matriarch is Isolde Rochester. She is a member of Congress, an influential figure in the Liberal Party and a staunch supporter of Shadow President Felicia Winters. Isolde raised five children, including Jordan, and it was her accomplishments that inspired her son to enter politics.” 

“Jordan’s siblings chose different paths. The eldest, [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]], is an executive with Core Dynamics, with a personal fortune in the billions. Fifteen years ago he had his own celebrity marriage, to actor [[id:f3e29df5-154d-4f05-b659-36fa2da9be01][Tomas Turai]]. They now have two teenage children, daughter Kali and son Kalen.” 

“Jordan’s sisters, Juno and Jocasta, have impressive Navy careers, holding the ranks of Vice Admiral and Post Captain respectively. Only Jordan’s younger brother, Jonah, has no title. He is believed to be the black sheep of the family.” 

“Despite being just 34, Jordan has already made his mark. He has overseen several high-level negotiations on behalf of the Federal Diplomatic Corps and is now a trusted envoy, noted for his charm and tact.” 

“His future will be interesting, to say the least. How will he balance being both a Federal statesman and an Imperial consort? And what are the wider ramifications of the Rochester dynasty aligning with the House of Duval? Even more so than his predecessors, Jordan Rochester has already ensured that history will remember his family’s name.”
