:PROPERTIES:
:ID:       50c6d5d4-d2c1-4f9b-a9b4-fb01b6608f93
:END:
#+title: Galactic News: Federal-Imperial Conflict in Merope
#+filetags: :Empire:Federation:3303:galnet:

* Galactic News: Federal-Imperial Conflict in [[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]]

/29 Apr 3303/

Authorities in the [[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]] system have reported conflict between the Pleiades Resource Enterprise, a Federal organisation, and the Merope Expeditionary Fleet, an Imperial organisation. The clash represents the latest development in the ongoing proxy war between the Empire and the Federation. 

Significantly, the two factions were until recently embroiled in conflict in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system. It is understood the Pleiades Resource Enterprise withdrew from the conflict specifically so it could engage [[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]] Expeditionary Fleet forces in Merope. This has led to speculation that the Pleiades Resource Enterprise was ordered to enter Merope and by the Federation. 

Security forces in [[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]] have confirmed that the fighting is localised at present, with no significant impact on civilian settlements. 

Freelance journalist Katherine Ryder commented on the development: 

“As long as the fighting remains contained, there’s no cause for alarm. There’s a world of difference between inter-faction skirmishes and all-out war between the galaxy’s two largest superpowers. Full-scale conflict between the Empire and the Federation might never happen.”
