:PROPERTIES:
:ID:       8c3e13e8-a1b0-4ea6-9c3e-afe4e6ff807c
:END:
#+title: Imperial Crackdown on Marlinists
#+filetags: :galnet:

* Imperial Crackdown on Marlinists

/30 Sep 3306/

Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] has mobilised Imperial military forces in response to terrorist acts committed by the Neo-Marlinist Liberation Army (NMLA). 

The Empire has declared martial law and a lockdown in Ackwada, Beatis Chana and Nahuatl, where the republican ideals of Marlinism are known to be popular. Imperial Army troops have replaced local security forces, and potential [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] sympathisers are being arrested for interrogation. 

Senator Patreus received applause in the Imperial Senate when he vowed: 

“There will be justice for the murder of Prince Harold Duval and justice for those citizens who perished in flames. The Marlinists will pay dearly for these atrocities!” 

In related news, the Imperial Internal Security Service issued a report regarding the NMLA’s recent attacks on starports: 

“Forensic results confirm that much of the station damage was caused by Thargoid caustic enzymes. Fragments indicate that the bombs were of advanced design but definitely man-made, not Thargoid in origin. Their payloads were identical in composition to enzyme missile rack warheads.” 

“Our deduction is that the portable explosives were smuggled onto all four starports, then remotely detonated as one coordinated strike. We are interviewing station personnel and analysing recent traffic to identify any patterns.”
