:PROPERTIES:
:ID:       701ff369-4602-43b0-a85c-56b2d3e31c85
:END:
#+title: Zende Partners Transport Service Operational
#+filetags: :galnet:

* Zende Partners Transport Service Operational

/09 May 3305/

A megaship service offering transport to Guardian space from Zende is now in operation. 

The CEO of Zende Partners, Freya Taine, announced: 

“Following the recommendation of the galactic community, my company has established an outpost in Synuefe EN-H d11-96 that will serve as the termination point for this new ferry service. Our two megaships, Sadler’s Song and The Conduit, will make weekly trips to the selected location.” 

“This first step of our initiative should encourage activity at nearby Guardian ruins. In addition, we have now finalised the design of an advanced military module based on Guardian technology, and we hope to begin manufacture of this design very soon.” 

Among the feedback from the technology industry was a statement by Cedrik Stone, CEO of rival arms manufacturer Segnen Exchange:  

“While Zende Partners’ recent efforts to promote Guardian-human research are admirable, I would like to remind Ms. Taine that she does not hold a monopoly on Guardian artefacts from that region of space. Segnen Exchange has a proven track record in this field, and we hope that Zende Partners are able to secure the acquisition of Guardian commodities for the benefit of all.”
