:PROPERTIES:
:ID:       929b78f4-12c8-4b07-8b3f-df9331bb504c
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/da747bdc-42e9-4d14-be66-e72712e6ee96?resourceVersion=id%3A4879
:END:
#+title: Xenological Samples Required by Colonia Scientists
#+filetags: :3307:Federation:galnet:

* Xenological Samples Required by Colonia Scientists

/07 Jan 3307/

*Pilots Federation ALERT* 

The [[id:3d9b071c-c232-431f-8f63-5c3a594b9909][Holloway Bioscience Institute]] in [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] is offering high payouts
for delivering samples from space-dwelling lifeforms.

The Holloway Biology Centre on [[id:d64c384b-5e85-44ef-ae31-a11e9577ce5f][Colonia 7 G]] is the organisation’s
primary [[id:112b5795-655f-4cc1-9995-b7aa39cb27c4][research]] laboratory, which specialises in [[id:4e827915-3759-4040-97d0-346eac70fb5e][xenological
studies]]. [[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]], which is also in the Colonia system, has
agreed to serve as the delivery point for this initiative.

Chief researcher Dr [[id:d5ca99a6-ded7-43fb-bc1e-83a622b49c50][Roy Casimir]] outlined the requirements: 

“There is still a huge amount to learn about the fascinating
structures that grow within the vacuum of space. As our stock of
specimens is running low, we require fresh [[id:fc24f273-2a74-4ff1-b845-245e9b91e21e][tissue samples]] from living
organisms to continue our experimentation programme.”

“I appreciate that our facility is located a considerable distance
from the core systems, but we’re willing to offer generous
reimbursement for those who make the journey.”

Pilots are requested to extract any type of tissue sample, including
[[id:81578d77-9559-4772-9b47-dcc45b190cbc][pod mesoglea]], from any type of [[id:4269a79f-0650-4e3e-b12d-723cd8ddf873][seed pod]]. These are to be delivered to
Jaques Station in the Colonia system.
