:PROPERTIES:
:ID:       bda9191c-3f86-4476-bfc2-129aa2940675
:END:
#+title: Galactic News: New Superpower Bases in the Pleiades
#+filetags: :3303:galnet:

* Galactic News: New Superpower Bases in the Pleiades

/07 Jul 3303/

Last month, the Empire and the Federation launched initiatives to bolster their presences in the Pleiades star cluster. Following the successful conclusion of both campaigns, the superpowers set to work on their respective construction projects. These projects have now come to an end. 

In the HR 1185 system, Imperial Senator Zemina Torval presided over the maiden voyage of the Indra, a massive Wells-class Carrier. She concluded the launch with a brief statement, saying “Space is by nature hostile. The Indra will make this particular system less so.” 

Meanwhile, the Federation announced the completion of Blackmount Orbital, an asteroid base sited among the rings of HIP 17692 A4 in the HIP 17692 system. A Federal spokesperson confirmed the outpost would offer a wide range of services to independent pilots.
