:PROPERTIES:
:ID:       f6a39ddb-7228-41f0-8022-d084292e6269
:END:
#+title: Underground Racers Spotted In and Around Sol
#+filetags: :3301:Federation:galnet:

* Underground Racers Spotted In and Around [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]

/14 Feb 3301/

Word has spread that a group of CMDRs piloting Core Dynamics' Eagle Fighters were spotted conducting high speed races near the [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]] system. Traders visiting Ashby City in Luyten's Star report that they spotted the pilots engaging in dangerous manoeuvres through the docking slot and around the station. Similar reports came from the [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]] System where patrons of the Solo Orbiter Station were met with several colorfully-painted Eagles upon arrival.  

  

“The pilots made it clear they meant no harm, their hardpoints were retracted and subsystem scans indicated that the spacecraft were not equipped for combat.” 

  

Rumour has it that this underground racing circuit began around the Earth-Moon System in nearby [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]. It seems that for now the Federation are willing to turn a blind eye to these events, as Federal Security Forces have made no attempts to intervene.  

  

-CMDR FatHaggard
