:PROPERTIES:
:ID:       f28c5386-cde6-42fe-9f07-7dd70b38c9f9
:END:
#+title: Thargoid-Sympathiser Arrests Increase
#+filetags: :Thargoid:3304:galnet:

* Thargoid-Sympathiser Arrests Increase

/08 Sep 3304/

The Federal Intelligence Agency has increased arrests of potential Thargoid sympathisers, as it continues to investigate the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult.  

Independent reporter Gethin Okonkwo, who first raised awareness of doomsayer cults in the core systems, has been reported missing and is assumed to have been arrested. Many others who were researching the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect remain in custody, including leading exotheologian Dr Alfred Ulyanov. 

The FIA has also shut down the Galactic Interfaith Commune and apprehended its spokesperson, Dr Jameelah Griffin. Several similar organisations, including the Spiritual Freedom Movement, have been closed down. 

Independent observers have confirmed that the FIA has discovered further empty [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] hive-chapels. The whereabouts of hundreds of adherents remains unknown. In an effort to uncover clues, arrests of associates and family members of Far God worshippers has intensified. 

Senior Agent Micah Whitefield gave a brief statement: 

“We will leave no stone unturned in our mission to identify Thargoid influences. The disappearance of [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] chapters is clearly a coordinated operation of either human or alien design. We warn anyone who may be harbouring cult members that they are impeding a Federal investigation, and will face criminal charges.”
