:PROPERTIES:
:ID:       1d7a30f5-1d9d-4b0d-88a7-1897d772912a
:END:
#+title: Hudson Set to Target Traffickers
#+filetags: :3301:Federation:galnet:

* Hudson Set to Target Traffickers

/09 Jun 3301/

Hudson Set to Target Traffickers 
 
In the face of President Hudson’s recent rise to power, the value of illicit goods has skyrocketed throughout the galaxy in anticipation of a crackdown on illegal commodities that are traditionally transported via the Federation. Dealers of all stripes have seen their profits soar over the last week, with hundreds of new millionaires being minted off the back of President Hudson’s perceived stance against criminal commodities. 

With the President’s appointment of his new administration now complete, sources close to Hudson have revealed to GalNet that an increase in security spending is very high on his agenda.  

“Things are about to get very difficult for traffickers,” one anonymous aide told the Mars Tribune.  

“The President’s ordered a bunch of those new Diamondback Scouts to act as short range interceptors for local security services. They don’t pack much of a punch on their own, but you try and outrun a swarm of angry Diamondbacks followed up by a couple of Viper wings and see how well you do.” 

“’Course if you do outrun them, say hello to the Navy. A month from now, two months top, the war against drugs will be done and dusted. You mark my words.”  

Prices of illegal narcotics had just started to stabilise after a week of frantic black market trading, and this latest news could well send prices spiking up again as dealers across the galaxy try to unload their stash before the expected galaxy-wide lockdown begins.
