:PROPERTIES:
:ID:       7d63b02a-24fa-40eb-9c63-dfa59e70263b
:END:
#+title: Galactic News: Empire to Retake Facece
#+filetags: :Empire:3302:galnet:

* Galactic News: Empire to Retake [[id:73e31493-0c88-4fd7-9f49-9f3f1c92db41][Facece]]

/04 Feb 3302/

A little over two weeks ago, the [[id:73e31493-0c88-4fd7-9f49-9f3f1c92db41][Facece]] system was occupied by an independent faction known as the Allied Facece Order. The news sent shockwaves through the Empire, with many asking how such a small organisation could take control of the second most important system in Imperial space. The consternation felt by Imperial citizens was compounded by the Empire's apparent lack of urgency regarding the issue, with many directing their frustration at Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]], who was until recently the system's primary administrator. 

Colm Tornquist of the Imperial Herald seemed to encapsulate the views of many when he asked: "What is Chancellor Blaine waiting for? Every day that passes is another day in which the people of [[id:73e31493-0c88-4fd7-9f49-9f3f1c92db41][Facece]] labour under the dictatorial rule of the Allied Facece Order. Action must be taken!" Almost as soon as this complaint was aired, Clearly Chancellor Blaine announced plans to retake the Facece system: 

"I apologise for what some have perceived as a lack of alacrity. I know the Imperial people are eager to see these opportunists removed from Imperial space, but it was essential that we plan our operation carefully to minimise the danger to the people of [[id:73e31493-0c88-4fd7-9f49-9f3f1c92db41][Facece]]. Now the planning is over, and order will soon be restored. I implore the people of Facece to remain calm. And to the Allied Facece Order I say this: your days are numbered."
