:PROPERTIES:
:ID:       915fa3bf-e980-4716-bc4c-3a7a0303b1bf
:END:
#+title: Rackham Consolidates in Beta Hydri
#+filetags: :3308:Federation:galnet:

* Rackham Consolidates in Beta Hydri

/22 Apr 3308/

The Beta Hydri system has become the commercial and political headquarters of wealthy entrepreneur [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]. 

The Tau Ceti Journal reported that [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]] owns a majority of shares in the Beta Hydri Corporation, the system’s controlling faction. As a member of its board of directors, Rackham has had a role in governing the system for many months. 

At a press conference, a spokesperson for [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]] said: 

“Mr Rackham was born on the planet Homeland, so he is enthusiastic about giving back to his former community. For example, building Rackham’s Spire helped revive the construction industry in Los Pioneros. We have also invested in several local companies, such as the Luxe Somptueux hotel chain – now rebranded as Rackham’s Rooms – and MacArthur Mining Ltd.” 

Several newsfeeds asked if Rackham’s political position in Beta Hydri paved the way for running as an independent candidate in next year’s presidential election. However, the spokesperson declined to comment. 

The Federal Times’s coverage of the story included an observation by financial journalist Bryanna Blanco: 

“As far as my research can tell, [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]’s citizenship documents have never been made public or independently verified. My guess is that [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Calico Zack]] wasn’t born in the Federation at all, but hails from some anarchic backwater where piracy is a way of life.”
