:PROPERTIES:
:ID:       73831d6c-2999-4d55-b478-78d174292ca7
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/4297c660-5724-498d-a797-47c3355ad657?resourceVersion=id%3A4875
:END:
#+title: Core Dynamics Purchases Lakon Spaceways
#+filetags: :Alliance:galnet:

* Core Dynamics Purchases Lakon Spaceways

/05 Jan 3307/

The shipbuilding company Lakon Spaceways has officially accepted a bid for ownership from Federal corporation Core Dynamics. 

The proposal from Core Dynamics CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] was ratified following a majority vote by Lakon’s board of directors, many of whom were recently appointed following resignations demanded by shareholders. 

Trent Delaney, the new chairperson, confirmed the merger in a public statement: 

“We are overjoyed that Lakon Spaceways will join the Core Dynamics family, thereby overturning the mistakes of the previous management and setting us on course for a bright future.” 

“The transfer of ownership will take another two months to formalise. In that time, it will be business as usual for the manufacture and sale of our ships.” 

The Federal Commerce Authority has approved the corporate takeover. However, the Independent Commission for Market Equality is still investigating reports of irregularities. 

The Council of Admirals has expressed concerns that a military supplier for the Alliance Defence Force should be owned by a Federal defence contractor. Admiral Rachel Ziegler informed the Assembly: 

“Regardless of our cordial relationship with the Federation, security issues will inevitably arise if the Alliance Chieftain and her sister ships are constructed by a foreign power. The ADF is already woefully underfunded, and this places extra strain on our ability to defend our interests.”
