:PROPERTIES:
:ID:       f46c3c84-94a0-4c26-99d2-c56d7923a439
:END:
#+title: Support Required for New Marlinist Starports
#+filetags: :galnet:

* Support Required for New Marlinist Starports

/14 Apr 3308/

*Pilots’ Federation ALERT* 

A delivery campaign in the HIP 22550 system will help build additional starports for the Marlinist Colonies. 

First Minister Octavia Volkov delivered this public address: 

“The Marlinist Colonies were born out of desperation, but we have evolved into a fully fledged society. Emperor Arissa has formally accepted our status as an autonomous democracy, albeit one that retains cultural and historical ties with the Empire.” 

“To celebrate and consolidate our independence, we have launched an initiative to construct up to six new orbital stations. For all those who wish to take part, we require shipments of aluminium, computer components, power generators and titanium to be transported to Stillman Hub starport.” 

“I am also delighted to announce that Universal Cartographics has approved our petition to rename the original eight systems of the Marlinist Colonies. These are expected to officially change in the near future.” 

The Free Marlinists of Carinae faction has confirmed that it will offer rewards to pilots who deliver the necessary materials to Stillman Hub in the HIP 22550 system.
