:PROPERTIES:
:ID:       6d2c0bf8-939c-4cda-96a7-f2676f20fa73
:END:
#+title: Reorte Resists Sirius Corporation
#+filetags: :3308:Alliance:Thargoid:galnet:

* Reorte Resists Sirius Corporation

/24 Jan 3308/

The presence of Sirius Corporation in the Reorte system at the Alliance’s invitation has been challenged by the controlling faction. 

In its new role as a strategic defence partner, Sirius Corporation recently established itself in several Alliance systems. But its megaship in Reorte, Chariot of Rhea, has found itself blockaded by system security and refused permission to offload cargo or personnel. 

A broadcast was made by Fergus Cassidy, CEO of the Reorte Mining Coalition: 

“Councillor Kaine is right to say that Sirius is acting illegally. The prime minister did not consult us or any other Allied faction on working with them, and there’s good reason to be sceptical of their motives. We regard the Chariot of Rhea as an intruder and insist that it leaves immediately.” 

Li Yong-Rui has assured Alliance leaders that Sirius Corporation will only be collaborating on anti-Thargoid defence projects. He stressed that there will be no disruption to any local civil or commercial activity. 

The Alliance Tribune commented on the situation: 

“Many Allied systems welcomed the news that our military is being bolstered by Sirius Corporation. But others expressed disapproval, particularly among the Old Worlds where the populations tend to be more sceptical of change. What happens in Reorte could determine whether or not the new defence pact becomes widely accepted.”
