:PROPERTIES:
:ID:       0e4b537d-a69b-4950-8c08-e3bc2051373e
:END:
#+title: Support for Aisling Duval
#+filetags: :galnet:

* Support for Aisling Duval

/13 Apr 3304/

Princess Aisling Duval’s recent comments about the effectiveness of Aegis have attracted a measure of support. 

One of the most prominent figures to express solidarity is Imperial Senator Pal Vespasian, who said: 

“One cannot accuse Aegis of being completely ineffective, but perhaps Her Highness has correctly gauged the mood of the people. A handful of minor victories is simply not enough to allay widespread fear of conquest. There can be no half measures in this situation – if we do not defeat the Thargoids, our civilisation could fall.” 

Meanwhile, Commodore Riri McAllister of the Alliance Defence Force said: 

“I can certainly refute Princess Duval’s suggestion that the other powers have not made equal contributions to Aegis. She makes a good point, however, with regard to military strategy. Greater transparency around Aegis’s long-term plans would lead to a more coordinated effort in resisting Thargoid forces.” 

Jast Fernández, chief editor of an independent media outlet, focused on how the public might be starting to view the princess differently: 

“We know that Aisling is widely seen as the stereotypical heiress – materially prosperous but intellectually deficient – but could this have been a public mask that she is now discarding? Or perhaps the young princess is finally maturing, and developing some genuine critical faculty? Either way, it’s no surprise that she’s found an audience – something she has always excelled at.”
