:PROPERTIES:
:ID:       d2580487-e42b-4fe9-8a9e-0befbb6e53ca
:END:
#+title: Galactic News: Engineers’ Campaign Concludes
#+filetags: :3303:galnet:

* Galactic News: Engineers’ Campaign Concludes

/29 Sep 3303/

A spokesperson for Aegis has announced that its appeal for Thargoid-related materials has reached a successful conclusion. Huge quantities of material were delivered to Awyra Flirble and Obsidian Orbital over the past week, following an enthusiastic response from the galactic community. They will now be delivered to the engineers [[id:cb71ba02-e47b-4feb-a421-b1f2ecdce6f3][Liz Ryder]] and Ishmael Palin so they can start work on new technologies to address the mounting Thargoid threat. 

As the campaign drew to a close, the spokesperson issued a brief statement: 

“Initiatives of this kind are a mainstay of the galactic economy, but this campaign is of singular importance. Humanity is faced with a clear threat to its safety, and we must do everything we can to oppose it.” 

“Furthermore, if we are to successfully resist the Thargoids, we will need to develop more advanced technologies. This will not be the last campaign of this kind.” 

Pilots who contributed to the initiative can now collect their rewards from Awyra Flirble in the Eurybia system and Obsidian Orbital in the Maia system.
