:PROPERTIES:
:ID:       e46ace6c-f5c4-4074-8d97-3154f38afecf
:END:
#+title: Catastrophic Earthquakes Strike Rhea 3
#+filetags: :galnet:

* Catastrophic Earthquakes Strike Rhea 3

/13 Feb 3310/

A series of high-magnitude earthquakes on the planet Rhea 3 have caused widespread devastation and millions of casualties. 

Massive seismic activity across the northern continent has effectively shattered dozens of towns and cities, including the capital New Greenacre. The intense tremors also triggered tsunamis in the surrounding oceans, which have wrecked coastal regions on other land masses. 

Local journalist Len Kennelly  published a summary for Vox Galactica:  

“The only disaster on this scale that we’ve seen in Rhea was when NMLA terrorists bombed Ito Orbital. This time, however, the death toll could run into tens of millions. Urban skylines have crumbled like sandcastles, with vast jagged pits opening up to swallow entire neighbourhoods.” 

“Federal Liberal Command has declared the highest state of emergency, calling for volunteers to help rescue trapped citizens. We’re seeing direct support from other factions in the system, and Federal Navy specialists are coordinating relief efforts. The humanitarian organisation Safeguard Interstellar is also here in force, providing supplies and temporary shelters for survivors.” 

Sofia Trevino, political correspondent for The Federal Times, reported: 

“As soon as this news broke, President-elect Felicia Winters – a native of Rhea 3 and the system’s representative in Congress – immediately cancelled her schedule and travelled to her homeworld. Unverified reports claim that contact has been lost with members of her family, most of whom lived in the capital.” 

“Speculation has already begun that this might cause further delays to the beginning of Winters’s term of office. Vice President-elect Isolde Rochester made a statement asking for patience, claiming: ‘Our focus right now should be on aiding those affected by this tragedy.’”
