:PROPERTIES:
:ID:       5acbe405-eb65-4f4e-abc6-1c9e3ed7138e
:END:
#+title: Retrial Requested for Admiral Tanner
#+filetags: :Thargoid:galnet:

* Retrial Requested for Admiral Tanner

/26 Aug 3308/

The Federal Attorney’s Office has called for the conviction of former admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]] to be reviewed in light of events in HIP 22460. 

Following a distinguished career in the Federal Navy, Tanner served as the chief military liaison for Aegis. In November 3307, while in command of the Aegis Defense megaship Musashi, he attempted to take control of Hind Mine starport. He believed it held evidence that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] intentionally attracted the Thargoids to the Cornsar system in order to test his superweapon. 

Tanner’s attack failed and the Musashi was overtaken, largely due to superior numbers of independent pilots supporting the former Taurus Mining Ventures, now [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]]. He was court martialled, dishonourably discharged, and found guilty of mutiny and unlawful military action. But his sentencing was postponed by request of Fleet Admiral Tayo Maikori, who considered Tanner’s intel to be crucial to his own investigation into [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. 

The Federal Times published this statement from Senior Attorney Fiona Logan: 

“It is now a proven fact that the Guardian-based nature of the Proteus Wave was intended to attract the Thargoid fleet to HIP 22460. Component analysis by [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] has verified that its forerunner superweapons were almost certainly designed to do likewise.” 

“This substantiates Tanner’s allegation that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] deliberately invited Thargoid incursions in inhabited systems. Furthermore, Salvation originally claimed that his anti-xeno detection network alerted him to the aliens’ approach, but there is no evidence that this network exists.” 

The Federal Navy Criminal Court confirmed that a formal application for a judiciary review was received. A special panel has been convened to reassess Tanner’s case.
