:PROPERTIES:
:ID:       2bd87127-eaab-41cb-a027-475ad9b6758e
:END:
#+title: Far God Cult Investigation Ends
#+filetags: :3304:galnet:

* [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Cult Investigation Ends

/29 Sep 3304/

The Federal Intelligence Agency has terminated its investigation into the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult. 

Senior Agent Micah Whitefield informed the media: 

“The information provided by Gethin Okonkwo on the inner workings of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect has been verified as genuine. In the absence of any evidence regarding communication with the Thargoids, our investigation is concluded. All worshippers who were detained have now been released.” 

“We are indebted to Mr Okonkwo for his highly detailed report. We had hoped to gain similar insights via our own undercover agent, who infiltrated the sect, but we are still awaiting his report.” 

The exotheologian Dr Alfred Ulyanov, who was arrested due to his research into the religion, commented: 

“I offer the highest praise to Gethin Okonkwo, whose dedication has confirmed the innocuous nature of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] faith. Sadly, this experience illustrates that intolerance and fear of the ‘other’ remain deeply embedded in human nature, no matter how advanced our species becomes.”
