:PROPERTIES:
:ID:       bb0dfdc8-8bf2-4d5e-b1a1-b359eee4b994
:END:
#+title: Zachary Hudson Becomes the New President of the Federation
#+filetags: :3301:galnet:

* [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] Becomes the New President of the Federation

/02 Jun 3301/

The results are in and [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] is the overwhelming choice for the new President of the Federation. 

A record number of attendees appeared in Congress on Mars to take part in yesterday's Vote of No Confidence against the Liberal Administration, with almost every member of Congress appearing in person to cast their vote. 

In the end, a shocking 66% of Congress voted to remove the Liberal Administration from office, a clear indicator that the collected Federal worlds feel a change in leadership style is necessary. Surprisingly, a large number of known Liberal supporters voted to remove their own leadership from power. Most commentators agree that this is a reflection on Halsey’s actions and the current unpopularity of Federal government among frontier systems. Winters needs to build her own supporter base before she can bring power back to the Liberals. 

President Hudson will be officially sworn into office later today, after which he is expected to spend the remainder of the week finalising his administration. Most of the previous Shadow Cabinet are expected to be included, although as always some change is inevitable. 

The Federal Republican Association has gained a massive swell of support over the last year. Now that President Hudson is officially in office, we can expect a much more aggressive stance on decision-making coming from Mars once the new administration is fully established.
