:PROPERTIES:
:ID:       96ba97a4-2199-434b-a0a9-0a126d7f0888
:END:
#+title: Pirates Lead Counter-Attack Against Thargoids
#+filetags: :galnet:

* Pirates Lead Counter-Attack Against Thargoids

/02 Feb 3309/

*Pilots’ Federation ALERT* 

The Kumo Crew is marshalling the defence of the California Nebula by offering rewards for eliminating Thargoid vessels. 

The Kumo Council, the syndicate’s ruling body, assumed control of several systems that were recently invaded by Thargoid fleets. Independent pilots have been asked to take part in anti-xeno initiatives within the region, which are being coordinated from The Mictlan megaship.  

Harrison Gladstone of the Turner Research Group, which represents [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] in the California Nebula, made a formal protest: 

“We are not happy about defence initiatives being funded by a ruthless criminal gang. These pirates are using the Thargoid attacks to expand their illegal activity, thus jeopardising our faction’s scientific and commercial interests. Several of our ports in the area are now under Kumo Crew ‘emergency protections’, as they’ve termed it. This is an illegal occupation of Allied territory!” 

In response, [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] claimed: 

“Taking charge of local security forces is necessary to form an effective anti-xeno militia. If [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] cares so much about this region, where are their warships? We’re doing Mahon’s job for him. The colonists here will soon understand our decision is the correct one.” 

The Kumo Council has agreed to reimburse all Thargoid combat bonds handed in at The Mictlan in California Sector HR-W d1-28.
