:PROPERTIES:
:ID:       9ed6ee3a-2b27-45b7-ab29-808483c214f8
:END:
#+title: Megaship Materials Boost Alliance Defence Force
#+filetags: :Alliance:Thargoid:galnet:

* Megaship Materials Boost Alliance Defence Force

/25 Aug 3308/

*Pilots’ Federation ALERT* 

Sirius Corporation has gathered resources in the Leesti system to help improve the Alliance’s anti-xeno defences. 

The campaign’s conclusion was announced by Captain Delfina Dominguez, commanding officer of the Chariot of Rhea megaship: 

“Many pilots docked with us over the past week to deliver shipments of energy grid assemblies, magnetic emitter coils, power transfer buses and titanium. On behalf of Sirius Corporation and the Allied Defence Force, I thank you for such encouraging support.” 

“I am informed that these will be sufficient to outfit 2 sentry megaships, each armed with experimental AX weaponry. These will be placed in key systems across the Alliance, ready to respond to potential Thargoid incursions.” 

“Admiral Glass has outlined his long-term plans to senior officers in the Sirius Navy. It’s clear that these are exciting times for the Alliance Defence Force. If the Thargoids come, we will be better prepared to repel them.” 

The Council of Admirals has stated that the new megaships are expected to become operational by September 15th.  

Pilots who contributed to the initiative can now collect payment from the Chariot of Rhea in the Leesti system.
