:PROPERTIES:
:ID:       a172c8b5-7c87-4877-ba91-cf06b965dc1f
:END:
#+title: Community Goal: Canonn Launches Outpost Campaign
#+filetags: :CommunityGoal:3302:galnet:

* Community Goal: Canonn Launches Outpost Campaign

/10 Mar 3302/

The Canonn Interstellar Research Group has launched a campaign to construct a state-of-the-art research outpost in the Col 285 Sector IX-T d3-43 system to support its ongoing research into the Unknown Artefacts. As part of this initiative, the organisation has placed an open order for palladium, promising to generously reward pilots who deliver the necessary materials to Thompson Dock in the Varati system. 

A spokesperson for the Canonn released a statement to the media: 

"Given the failure of Professor Palin's recent attempt to establish a research outpost in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system, I am aware that certain sections of the galactic community may receive our request with scepticism. But the fact is that the study of the Unknown Artefacts is still of great importance, and it is essential that a dedicated research outpost be established, far from the civilian population, where they can be safely investigated." 

The campaign begins on the 10th of March 3302 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
