:PROPERTIES:
:ID:       94bb3e03-0e3e-4a4d-b2ad-3f1613386d30
:END:
#+title: Further Disturbances in Mourners' Line
#+filetags: :3301:Empire:galnet:

* Further Disturbances in Mourners' Line

/17 Aug 3301/

Further Disturbances in Mourners' Line 
 
Imperial Naval infantry have once again intervened as protesters – who have taken issue with Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]]’s connection to Brendan Paul Darius, the Emperor’s murderer – attempted to prevent access to some of Senator Patreus’s allies late last night. This time the agitators resisted the soldiers’ efforts to maintain peace. After several attempts to peacefully resolve the situation, a riot squad was deployed to restore order. 

The action was efficiently completed, but smaller disturbances and protests flared up throughout the night. All were pacified by the troops but many mourners were forced to flee. Calm was eventually restored and an Imperial Guard company has now been stationed to secure the entrance to the Hall of Martyrs. A full regiment of Naval infantry has also been moved into the city.
