:PROPERTIES:
:ID:       38cdf814-7127-49b4-af35-560d41eecc23
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/f02bde59-abc0-4831-8531-95fb48a4f568?resourceVersion=id%3A4841
:END:
#+title: Outpost Planned for ‘The Roof of Space’
#+filetags: :galnet:

* Outpost Planned for ‘The Roof of Space’

/11 Dec 3306/

Multi-billionaire Zachary Rackham is constructing a permanent outpost at the farthest system above the galactic plane. 

The orbital outpost will be located within the HIP 58832 system. This is commonly held to be at the galactic zenith, one of the highest locations that can practically be reached.  

The project is funded by the corporation Rackham Capital Investments, with the close involvement of Universal Cartographics and several other scientific organisations. The outpost’s location will make it ideal for gathering astronomical data on the overall structure of the galactic spiral. 

This historic scientific endeavour was remarked upon by Mr Rackham from his private villa complex on the Rhea Archipelago: 

“Back in my days of plying the trade routes in a second-hand Sidewinder, the idea of standing on the roof of space was an idle daydream. This new generation of pilots and ships will make my vision a reality.” 

“No doubt many important scientific observations will be made once the outpost is up and running, but more importantly, there’ll be a bar – and the drinks are on me!” 

A spokesperson for Rackham Capital Investments later confirmed that the outpost in the HIP 58832 system would be operational on the 17th of December 3306, but clarified that there was no legal guarantee for beverage reimbursement.
