:PROPERTIES:
:ID:       cd6a7f23-722b-49ea-8f44-0cc0504523ae
:END:
#+title: Anti-Slavery Support Grows in Synteini System
#+filetags: :3301:galnet:

* Anti-Slavery Support Grows in Synteini System

/08 Mar 3301/

The Future of Synteini party is calling on all Commanders to protest the actions of the Imperial Slavers Association in the Synteini system. 

“Today marks the anniversary of the ‘Act Prohibiting Importation of Slaves’, one of two acts that helped end the Atlantic slave trade in the early 19th century,” said a party representative. “And now a new slaving facility is opening up in our own backyard?” 

The party offers their own station as a potential solution. “The Future of Synteini party will not abide by slavery, Imperial or no. I make the call to commanders: give your business to the Future of Synteini, not to the ISA. Do business at William Sargent, and starve Lagerkvist. 

“Let’s hit Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] where it counts - and kick her out of Synteini!” 

Lagerkvist Gateway orbits the second planet in the Synteini A system, while William Sargent Vision orbits the fourth. 

-CMDR Boter
