:PROPERTIES:
:ID:       ca48152f-c37b-4eb1-b732-b1beb1058ebd
:END:
#+title: Final Maelstroms Advance Thargoid Occupation
#+filetags: :Thargoid:galnet:

* Final Maelstroms Advance Thargoid Occupation

/16 Dec 3308/

*Pilots’ Federation ALERT* 

A further 13 systems have fallen under Thargoid control as the last of the Maelstroms materialise. 

The three rogue signal sources – designated Thor, Raijin and Hadad – entered human-occupied space yesterday. As with the previous five anomalies, they manifested as colossal clouds of corrosive gas over 100 kilometres in diameter.  

Pilots who attempt to investigate the Maelstroms have been warned that the highly caustic nature of the clouds can disable and destroy ships. Xenologists have speculated that the cloud is a defensive asset, maintained by the huge numbers of caustic generators clustered within. 

All eight Maelstroms are now established at their destinations, positioned in a broad semi-circle along the fringe of the core systems. Each of these entities has become the centre of an expanding Thargoid sphere of influence. Populated systems in the surrounding regions have been dominated by extremely hostile Thargoid vessels, causing enormous casualties and catastrophic damage. Many more inhabited systems are at risk of invasion.  

Eleven rescue megaships have entered service at key locations to aid and process the millions of refugees fleeing these attacks. These ships also act as hubs for defence operations to support those systems struggling to resist the Thargoid fleets. 

The Alliance, Empire and Federation have deployed capital ships equipped with anti-xeno weaponry to defend their respective territories. As yet there appears to be no technology or strategy capable of engaging the ominous power of the Maelstroms directly.
