:PROPERTIES:
:ID:       e69a1305-3c2c-4e75-baa7-c126db84a36e
:END:
#+title: Positive Results from Maelstrom Probes
#+filetags: :Thargoid:galnet:

* Positive Results from Maelstrom Probes

/27 Apr 3309/

Aegis’s prototype Thargoid pulse neutralisers have succeeded in allowing transit through the energy surge at the centre of a Maelstrom. 

Professor [[id:c2623368-19b0-4995-9e35-b8f54f741a53][Alba Tesreau]] made the official statement: 

“Several remote-controlled probes outfitted with Thargoid pulse neutralisers were launched into the Taranis Maelstrom. The colossal electromagnetic pulse generated within the clouds should have repulsed them, but feedback confirms the probes were insulated from its effects.” 

“The method used to protect the probes was discovered through research on unclassified relics recovered from Thargoid surface sites. These alien artefacts were vital to the devices’ development. Initial research conducted by [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] and Professor Palin proved that when receiving a modulated electrical charge, the unclassified relics emitted an energy field on similar frequencies to the Maelstrom’s pulse.” 

“Unfortunately, broadcasts from the probes were lost shortly afterwards. It hasn’t been possible to verify what happened to them at this stage. We will repeat this experiment with other Maelstroms, but we believe that only skilled human pilots will be able to uncover what awaits within.” 

Aden Tanner, who is supporting Aegis as a freelance tactical specialist, provided a supplemental report: 

“My team has been conducting secondary tests with the new module installed on a manned vessel. I can confirm that when in combat against Thargoid interceptors, it protects against ship system disruption in a similar way to the existing shutdown field neutraliser. But its weight and power draw are both greater, meaning that the new module is best suited to Maelstrom exploration.” 

Aegis has confirmed that it is working on establishing a production schedule for the Thargoid pulse neutraliser and intends to provide an update in the next few days.
