:PROPERTIES:
:ID:       ba8b153c-a2e3-4c45-93e1-081e15db06bf
:END:
#+title: Eurybia Blue Mafia Resists Imperial Forces
#+filetags: :galnet:

* Eurybia Blue Mafia Resists Imperial Forces

/08 Oct 3306/

*Pilots Federation ALERT: For the attention of all Commanders* 

Conflict between Keltim Empire League and Eurybia Blue Mafia in Eurybia has ended. 

The Eurybia Blue Mafia has successfully fought off an attempt by the Empire to take the Engineer Liz Ryder into custody.  

Spokesperson Ana Westergard made this announcement on behalf of the anarchist faction: 

“This is a victory against the Empire’s arrogance! There was never any evidence that Liz Ryder or our organisation are involved with terrorists, and this invasion was based entirely on supposition.” 

“We are extremely grateful to everyone who helped us defend Liz Ryder and maintain our independence. Rewards to all those brave Commanders are available at Awyra Flirble starport, modules will be placed in storage by the 10th of October 3306”. 

Captain Rocco Gandara of the Keltim Empire League announced: 

“Despite the anarchists having the upper hand on this occasion, I can confirm that we will honour all of our supporting pilots by making rewards available at Prelude to Victory.”
