:PROPERTIES:
:ID:       0dbd70f3-26a5-4e12-adad-571fe5dae58d
:END:
#+title: Where's Walden Now?
#+filetags: :3301:Empire:galnet:

* Where's Walden Now?

/10 Aug 3301/

Where's Walden Now? 
 
Today marks 36 years since the last ‘Walden Day’, the annual celebration of the great leader across all four continents of [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]], where prefects, primes and factors would try to outdo each other with how much love they could show the planet’s ruler. 

Lave in 3301 does its best to forget the past. Years of relative prosperity and capitalist competition between the LFO, the Defence Party and the Workers of Lave reflect the different social classes of the planet’s regions. Each formed out of different parts of the old regime and its adversaries. But the question remains, what actually happened to Doctor [[id:0b41fd3c-7d4e-4f61-b375-c96b99990d01][Hans Walden]]? 

The holovid footage of his execution has been replayed countless times on hundreds of programmes. Some preach conspiracy, others see tampering, but most agree that Walden’s clone research, journals, and the numerous patents sold to Imperial contractors bearing his name point to his having experimented with the duplication of his own genetics. 

Since 3265, the government has released no evidence of hidden scientific laboratories on Lave or any of the plotted asteroids in the system. Rumours of a secret colony on Lave II have never been confirmed, either, but the rumours keep resurfacing. Yes, Walden was executed during a live vidscreen broadcast...but was that the only Walden? Could there be others, lurking out there on a nearby planet, waiting to return? If there are any clones left, forgetting the past won’t help us deal with the future.
