:PROPERTIES:
:ID:       d62855d5-a3d9-4cf2-a1cd-5f1d3336ff4d
:END:
#+title: Week in Review 10 Nov 3304
#+filetags: :3304:galnet:

* Week in Review

/10 Nov 3304/

Here are this week’s major stories. 

A mercenary group has been intercepted by security forces in the Meene system. It is understood that the mercenaries’ primary target was Phoenix Base, home of the engineer Ram Tah. Li Yong-Rui, CEO of Sirius Corporation, said the attack demonstrated the precariousness of Ram Tah’s situation. 

In related news, security forces in Meene are launching an operation to capture enemy agents. Security Chief Harper Vargas said his forces intended to detain any surviving mercenaries and interrogate them, so they could identify the individuals behind the incursion. 

Meanwhile, Lieutenant Inspector Ramesh Thorne, who has been leading an investigation into The Mars Tribune, has been suspended from the Federal Security Service. The news came less than an hour after Thorne made a public appeal for information regarding admin robots fitted with secret surveillance programs, citing the unwillingness of his superiors to pursue the matter. 

The isolationist group Nova Imperium has broadcast a message to Imperial citizens. The organisation’s leader, known only as the Imperator, implicitly criticised Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] for ‘weakness’, and said that [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] would only survive the Thargoid onslaught by severing ties with the other superpowers. 

The family and colleagues of author Olav Redcourt have reported him missing. A police investigation has so far failed to determine his whereabouts. Redcourt recently hit the headlines when he terminated his relationship with his publisher, Bonespire Publishing, midway through a promotional tour. 

Finally, authorities in the Geras system have confirmed that the conflict between Geras First and Ndozins State Inc has come to an end. Both factions received support from independent combat pilots, to whom generous rewards were promised, but in the end there could be only one victor. 

And those are the main stories this week.
