:PROPERTIES:
:ID:       9f1fd5b6-6f5d-4f78-811e-fb02d4efc59c
:END:
#+title: Freelance Report: Commander [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] Hijacked in Cemiess
#+filetags: :3302:galnet:

* Freelance Report: Commander [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] Hijacked in Cemiess

/23 Aug 3302/

Recent articles published by the Imperial Citizen may have inspired an act of violence in the Cemiess system over the weekend. Commander Nodus Cursorius of the Chapterhouse of Inquisition reported a transmission from Commander [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] of the Children of Raxxla, indicating that her ship had been attacked by unknown forces. 

A transcript of Commander Salomé's distress call follows: 

"Heavy fire...mayday! Imperial markings! Traitors... Shields are down, we're taking damage...it's... I thought I sensed his arrogance! How dare... We're being boarded. I only have moments. Please get word to the Children of Raxxla, tell them I have new information. The Rift, Hawkin's Gap and the Conflux are connected with strange happenings in the Pleiades. They must find out before..." 

At that point Commander Salomé's transmission was silenced. Despite a thorough search, no sign of her has yet been found. 

The Imperial Citizen had suggested that Commander [[id:2f09bc24-0885-4d00-9d1f-506b32464dbe][Salomé]] is in fact Senator Kahina Tijani Loren of the Prism system. The publication also implied that she had engineered the events that led to her family's death in order to position herself as heiress of the Loren family dynasty. 

Jaiotu
