:PROPERTIES:
:ID:       ddba44cc-3c53-4243-89fd-900d2e1b383d
:END:
#+title: Galactic News: Engineers Reduce Requirements
#+filetags: :galnet:

* Galactic News: Engineers Reduce Requirements

/16 Jun 3302/

The 'Rewired' news feed is known for its prodigious output, sometimes releasing hundreds of stories a day. But balancing such productivity with thorough fact checking is a tall order, and the feed's critics sometimes claim that at least half its output consists of redactions, corrections and apologies. 

But despite these jibes, only the most obdurate critic would deny that Rewired has broken major stories in the past, its guerrilla style approach allowing it to react faster than some of its larger, more established rivals. 

The channel's latest report will interest many of the galaxy's independent pilots: 

"Word is that Broo Tarquin will now work with pilots who can bring him 50 units of Fugin Tea, instead of the 100 he used to ask for. And Didi Vatermann's only asking for 50 units of Lavian Brandy, which is a damn sight less than the 200 she previously insisted on. Seems it just got a whole lot easier to spec your ship."
