:PROPERTIES:
:ID:       07000dba-2e45-4643-ac5e-cc44fb3fe954
:END:
#+title: Ammonia World Survey Concludes
#+filetags: :Empire:Federation:Thargoid:galnet:

* Ammonia World Survey Concludes

/16 Mar 3309/

*Pilots’ Federation ALERT* 

Aegis and Universal Cartographics have announced that the project to survey ammonia worlds has ended satisfactorily. 

Special mention goes to Commander aRadish, Commander Lone WolfPack and Commander T'Verez for their efforts. 

The exploration initiative was praised by Congressman Tom Gillespie, who oversees Federal contributions to Aegis: 

“An impressive number of terrestrial planets with ammonia-based atmospheres were scanned and catalogued over the last two weeks. Universal Cartographics certainly considers the project to be a great success, and I know our xenological scientists do too.” 

“This is the kind of task for which independent Commanders are absolutely unmatched in dedication and expertise, and they remain our indispensable allies.” 

Vice Admiral [[id:dce2491e-fa32-458a-90b1-3a2e0bede702][Skylar Anderson]], the Imperial military liaison to Aegis, added: 

“This information is of considerable strategic value. Each system containing an ammonia world will be monitored using concealed sensor buoys. This will alert Aegis to the presence of Thargoid vessels or Maelstrom manifestations. Advance warnings will provide increased time to evacuate systems or mount pre-emptive strikes.” 

Pilots can receive payment for their exploration data at Angus Manwaring starport in the [[id:ed325fe8-22a1-4d07-9af9-5a9f8f056377][Eta Cassiopeiae]] system.  The promised x3 multiplier on exploration data profits for the next two weeks has also commenced, with Universal Cartographics providing this through its starport contacts.
