:PROPERTIES:
:ID:       2780bc96-8e3e-4633-a504-b38804fc19fe
:END:
#+title: Ancient Alien Battleground Discovered
#+filetags: :galnet:

* Ancient Alien Battleground Discovered

/17 Aug 3309/

*Pilots’ Federation ALERT* 

Wreckage from a past conflict between the Guardian and Thargoid races has been found in the Wregoe BU-Y b2-0 system. 

The crashed remains of Thargoid vessels, alongside structures of Guardian origin, are located on Wregoe BU-Y b2-0 1 c. Conflict between the two species occurred millions of years ago, but physical evidence of this is extremely rare. The only comparable site, in the Trapezium Sector YU-X c1-2 system, was initially found two centuries ago by the Azimuth Biochemicals ship Proteus and rediscovered in 3307. 

Wregoe BU-Y b2-0 was one of several systems under investigation following a report by Commander Renia Rakowski, who encountered a Thargoid interceptor in nearby Wregoe GA-X B3-0. 

The Holloway Bioscience Institute has sent teams into the area to explore the possibility of xenoarchaeological research. Dr Jeong-Hui Shin gave a statement to The Sovereign newsfeed: 

“It is fascinating that none of the Thargoid vessels operating in this region are immediately aggressive. One of our theories is that they are still following million-year-old orders to attack the Guardians. Therefore, from their perspective, humans are an unknown species and not identified as an enemy. Alternatively, they may be pursuing non-combat functions such as meta-alloy harvesting, as with the Thargoids that can still be found in some nebulas.” 

Prominent xeno-peace advocates including Timothy Culver, Bernadette Wells and Dev Venkatesh  have called for further study of the area. They claim that this is “an opportunity for non-hostile interactions with the Thargoids,” who may have developed “an autonomous subculture that is more amenable to coexistence with humanity, providing certain boundaries are respected.” 

Other pro-peace groups have demanded that naval forces should not be sent into the region, as the Thargoids may view this as a provocation. At present, Aegis is focused entirely on gathering information and is not aware of any anti-xeno deployments against Wregoe BU-Y b2-0.
