:PROPERTIES:
:ID:       22f41823-1643-440d-a959-a7c279ec199b
:END:
#+title: Starport Bombing Casualties Include Federal Vice President
#+filetags: :Federation:Empire:galnet:

* Starport Bombing Casualties Include Federal Vice President

/12 Mar 3307/

Vice President Brad Mitchell and a number of Federal Cabinet members have been killed in the recent terrorist attack on a starport orbiting Earth. 

The [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] planted caustic enzyme explosives at Li Qing Jao station, where a government meeting was taking place. The VP and Cabinet members were confirmed to be among tens of thousands of casualties. Eight other starports across all three superpowers were simultaneously bombed. 

President Zachary Hudson, who was attending the Galactic Summit during the attack, made this statement: 

“This atrocity is nothing less than a declaration of war, and we will respond accordingly. For now, we mourn the loss of my close friend Brad Mitchell and other heroes of the Federation. I will personally appoint replacements to their positions soon.” 

The Federation has directly accused the Empire of being responsible, by allowing Neo-Marlinist bomb-makers to escape from a secret prison facility. The Imperial Senate reiterated that ‘Serene Harbour’ does not exist and is part of a Federal disinformation campaign. 

Followers of Marlinism have also received much public criticism. The Marlinist Colonies have repeatedly stressed that they do not support the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] and are unconnected to the attacks. 

Independent pilots have been asked to assist rescue and repair operations in the Achenar, Alioth, Eotienses, Gateway, Kamadhenu, Lave, Nanomam, Rhea and Sol systems.
