:PROPERTIES:
:ID:       84b08fd5-a53b-4144-bf69-580ed401a4a6
:END:
#+title: Galactic Summit Begins with Defence Request
#+filetags: :3307:Federation:Empire:galnet:

* Galactic Summit Begins with Defence Request

/25 Feb 3307/

*Pilots Federation ALERT* 

The Federation is working with Sirius Corporation to offer bounty hunting opportunities to protect the diplomatic conference. 

The first Galactic Summit has officially opened at Patterson Enterprise station in the Sirius system. Temporary permits have been issued to all arriving delegates and Commanders for the three weeks of its term, although these do not apply to fleet carriers. 

 Sirius Corporation’s CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] announced: 

“The data supplied to us in January revealed several unanticipated threats, putting additional strain on our navy and security forces. Working with the generous support of the Federation, we have placed bounties on all wanted ships to ensure delegates’ safety. Pilots defending the Sirius system will be rewarded for handing in bounty vouchers at the Spirit of Laelaps.” 

The joint initiative will run for one week, after which Sirius Corporation will partner with the Empire to provide for the needs and security of the conference.   

In related news, Core Dynamics, Gutamaya and Lakon Spaceways are celebrating the political gathering of all three superpowers with a 10% discount on their ships during the next three weeks. 

Delegations have begun to arrive and formal introductions are taking place, with much media attention. This is the first time that universally recognised figures such as President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]], Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] and Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] have been seen side by side.
