:PROPERTIES:
:ID:       21fc2551-1f83-4b2d-a41f-a5d87a0fd459
:END:
#+title: Admiral Tanner Receives Presidential Pardon
#+filetags: :Thargoid:galnet:

* Admiral Tanner Receives Presidential Pardon

/09 Jan 3309/

The court martial verdict of Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]] has been officially overturned by an executive order from President Zachary Hudson. 

In November 3307, Tanner attempted to take control of Hind Mine starport while in command of the Musashi megaship. He claimed that databanks at the headquarters of Taurus Mining Ventures – as Azimuth Biotech was then known – contained evidence that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s anti-xeno superweapons were designed to attract the Thargoids into populated systems before they were deployed.  

A legal review last September, after the Proteus Wave was used to entice Thargoids to HIP 22460, substantiated Tanner’s claims. His sentence was commuted to time served, but his dishonourable discharge was upheld. This granting of clemency by President Hudson quashes the convictions of mutiny and unlawful military action. 

The Office of the Federal President published the following: 

“Aden Tanner has an impressive and honourable record of service to the Federation, including a key role as chief military liaison to Aegis. His brief violation of protocol has since been accepted as based on sound intelligence. President Hudson therefore believes that Tanner’s in-depth experience in combating Thargoid forces is too valuable to disregard, considering the current situation.” 

A brief statement was also made by Fleet Admiral Tayo Maikori: 

“I fully support this presidential pardon, which is in the best interests of all citizens. Admiral Tanner has been formally reinstated and is already being briefed on strategic plans regarding the Thargoids.” 

“I’d like to stress that I believe the Federal Navy Criminal Court’s original verdict was just and fair, given all available information at the time. This executive action does not undermine the court’s crucial role in maintaining order among enlisted personnel.”
