:PROPERTIES:
:ID:       6c960023-3adb-4c0e-972f-358878c6c69d
:END:
#+title: Federation Secession Crisis
#+filetags: :3301:galnet:

* Federation Secession Crisis

/27 Jul 3301/

Federation Secession Crisis 
 
Debate continues to rage in local governments throughout the Pegasi sector over Senator Lavigny-Duval's invitation to become Imperial citizens. The debate has reached a fevered pitch in some systems. 

"Our petitions for assistance from [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] have fallen on deaf ears for months now. I’m tired of the demonizing epithets cast at “Imperial slavers” while Federation citizens are being forcibly carried away into slavery by the Kumo Crew. Hudson and Winters are nothing but spineless cowards and hypocrites,” spat the enraged governor of the Wudjal system. “The Wudjal system is home to more Federation citizens than the entire Imperial population occupied by the Kumo Crew. Until the Federation honours its commitments to us, we will not send a single credit to Sol. I recommend that every governor in the Pegasi sector open an Imperial embassy. At least Imperial citizenship means something." 

Commander Corrigendum
