:PROPERTIES:
:ID:       a70d8dac-ade3-4843-84a1-608e4d248f4e
:END:
#+title: [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][The Federation]] Unites in the Face of Tragedy
#+filetags: :3301:galnet:

* [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][The Federation]] Unites in the Face of Tragedy

/09 Jun 3301/

The Federation Unites in the Face of Tragedy  
 
Despite some fear that the recent change in leadership would lead to further destabilisation of the Federation, it seems that on the whole, the majority of Federal worlds are content to wait and see what kind of President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] turns out to be. 

Political pundits and sociologists alike had expressed concerns that since the disappearance of former President Jasmina Halsey, [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] would almost certainly go through a period of internal strife while the landscape of Federal power adjusted to the new reality.  

To everyone’s surprise, the situation on the ground has actually stabilised since President Hudson assumed office. It would seem that in the face of tragic loss, personal politics have been put aside, and the overwhelming majority of Federal organisations have chosen to stand united for the good of the Federation. 

How long this new coalition will last remains to be seen, but for now at least, Federal residents can rest easy knowing that for this brief moment in time, [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] stands united for the good of all mankind.
