:PROPERTIES:
:ID:       4a5ea5e5-79ae-446d-8efe-9443c864fabc
:END:
#+title: Sirius Corporation Programme Ends Today
#+filetags: :3301:galnet:

* [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] Programme Ends Today

/18 Nov 3301/

Last week, the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] launched an initiative to boost the economy of the HIP 8396 system, which was recently brought under its control. The initiative was underpinned by an open contract for osmium, which contractors were asked to deliver to Stepping Stone Base. The response to the appeal was positive, with hundreds of miners taking to their ships to gather resources for the people of HIP 8396. [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]], the CEO of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp.]], expressed his satisfaction at the response: 

"The pilots who contributed to this initiative have performed a great service, and proved that the people of this galaxy are motivated as much by altruism as by the promise of reward. We are all humanitarians at heart." 

It is expected that the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] will announce the next initiative in its multi-system revitalisation programme soon.
