:PROPERTIES:
:ID:       dd8b7c5f-3e5a-4e35-a64a-6b37c345f22f
:END:
#+title: The Winking Cat’s Return
#+filetags: :galnet:

* The Winking Cat’s Return

/31 Aug 3305/

The notorious art thief known as the Winking Cat has resurfaced in the Alioth system during the Alliance Festival of Culture. 

For the festival’s sixth week, Garden City Gallery on Turner’s World hosts an exhibition of the visual arts. Advanced security measures have been employed to prevent a repetition of the high-profile incident that occurred in June 3304, where the unique work ‘Youscape’ was stolen from a gallery vault. 

Local correspondent Daron Warmack reported for The Alliance Tribune: 

“When gallery staff noticed a painting hanging in a previously empty room, they were shocked to recognise it as ‘Penance Street’, the long-lost masterpiece of famous artist Megan Madigan.” 

“Experts have verified that this is the original artwork, which vanished in transit 60 years ago. A graphic of a winking cat was also discovered on the wall behind the picture.” 

“The Winking Cat has returned one of the Alliance’s greatest art treasures – a personal contribution to the festival, perhaps, or maybe an act of penance.” 

The Alliance Festival of Culture will conclude next week in the Diso system.
