:PROPERTIES:
:ID:       4b7f8fa1-fcf7-4324-8092-82d603f9a03c
:END:
#+title: Hadrian Duval Accepts Senate Protection
#+filetags: :3307:Empire:galnet:

* [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]] Accepts Senate Protection

/02 Nov 3307/

The Empire has officially proclaimed[[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Augustus Duval]] and his wife Lady[[id:ef9ddb06-8cb2-4c3f-a688-469be3149aa9][Astrid Minerva-Duval]] to be wards of the Senate. 

The offer of senatorial protection was made following an [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] attempt to assassinate them and their unborn child by bombing Dyson City starport. 

Prior to being transported from the Paresa system to a secure location, [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]] sent this message: 

“Lady Astrid and I accepted this offer with enormous reluctance. Neither of us wish to abandon our home or loyal followers. Yet we feel it is a matter of duty to protect our family and ensure future generations of the Duval bloodline.” 

“Nova Imperium will henceforth be known as Nova Paresa. It will continue to serve as a staunch ally of the Empire, as per the Treaty of Paresa. To all those who fought for our cause over the years, I assure you that history will never forget us. Memento Mordanticus!” 

There has been public support for Praetor[[id:3fdf3f05-e7b5-436f-906e-e67dafa5d254][Leo Magnus]] to assume leadership of Nova Paresa. [[id:c4f47591-9c52-441f-8853-536f577de922][Hadrian Duval]] has endorsed his former head of security taking his place, but confirmed that the title of Imperator is now defunct. 

In related news, [[id:a152bfb8-4b9a-4b61-a292-824ecbd263e1][ACT]] stated that its investigation into the Dyson City attack has yielded results. Although details remain embargoed for security reasons, a significant breakthrough is expected to be announced soon.
