:PROPERTIES:
:ID:       6d2c0bf8-939c-4cda-96a7-f2676f20fa73
:END:
#+title: Reorte Resists Sirius Corporation
#+filetags: :3308:Alliance:Thargoid:galnet:

* [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Resists [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]

/24 Jan 3308/

The presence of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] in the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] system at the Alliance’s invitation has been challenged by the controlling faction. 

In its new role as a strategic defence partner, [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] recently established itself in several Alliance systems. But its megaship in [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]], Chariot of [[id:6da9023a-ccb6-444a-be77-626dfb552eb1][Rhea]], has found itself blockaded by system security and refused permission to offload cargo or personnel. 

A broadcast was made by Fergus Cassidy, CEO of the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] Mining Coalition: 

“Councillor Kaine is right to say that [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] is acting illegally. The prime minister did not consult us or any other Allied faction on working with them, and there’s good reason to be sceptical of their motives. We regard the Chariot of [[id:6da9023a-ccb6-444a-be77-626dfb552eb1][Rhea]] as an intruder and insist that it leaves immediately.” 

[[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] has assured Alliance leaders that [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] will only be collaborating on anti-Thargoid defence projects. He stressed that there will be no disruption to any local civil or commercial activity. 

The Alliance Tribune commented on the situation: 

“Many Allied systems welcomed the news that our military is being bolstered by [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]. But others expressed disapproval, particularly among the Old Worlds where the populations tend to be more sceptical of change. What happens in [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] could determine whether or not the new defence pact becomes widely accepted.”
