:PROPERTIES:
:ID:       277588cd-d5c8-4b76-a355-4d0e969422f4
:END:
#+title: Galactic News: New Research Centre at Thargoid Site
#+filetags: :Thargoid:3303:galnet:

* Galactic News: New Research Centre at Thargoid Site

/15 Jul 3303/

As the number of newly discovered [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] structures continues to grow, reports from the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] Sector IR-W D1-55 indicate that the Oracle, an Ocellus starport, has relocated to the system in order to study the region’s Thargoid structure.

Governor Ahmed, the starport’s principal administrator, released the following statement:

“The Oracle has long been a hub for scientific research, and in recent years many of our researchers have started focusing on [[id:d17a9775-b9b5-4d26-b69f-16ced04f52a9][Unknown Artefacts]] and Probes. The Thargoid structures are ripe for further study, and I therefore believe it is essential that we have a dedicated research centre at one of these sites.”

“We need to know more about the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] – what they want, why they’re here and ideally how to communicate with them. My hope is that the Oracle will help us answer some of these questions.”

The Oracle is expected to arrive in the Pleiades Sector IR-W D1-55 within the next few days.
