:PROPERTIES:
:ID:       6c8925a0-2006-49e3-92b5-8cfc1aa6ec3e
:END:
#+title: Alliance Initiative
#+filetags: :Alliance:3304:galnet:

* Alliance Initiative

/02 Feb 3304/

The Alliance has announced plans to build an Orbis starport in the Synuefai EB-R c7-5 system, between the core systems and the Alliance’s outposts in the California Nebula. 

Alliance official Torvan Dast issued the following statement: 

“The remoteness of our California Nebula outposts makes reaching them a potentially dangerous proposition. This new starport will bridge the gap between the settlements and the galactic core, and lessen the risk to ships journeying to and from the California Nebula.” 

The initiative is being overseen by the LP 128-32 Corporation, which has placed an open order for various raw materials for use in the construction. The organisation has also placed a kill order on all ships on its wanted list, to ensure that those contributing material to the campaign can do so safely. 

The campaign begins on the 1st of February 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
