:PROPERTIES:
:ID:       138ecaf6-f6da-4ec7-a5fb-e621e585935e
:END:
#+title: Aisling Duval’s Secret Relationship Revealed
#+filetags: :3304:galnet:

* Aisling Duval’s Secret Relationship Revealed

/18 Aug 3304/

Anti-slavery campaigner Jarl Toredo has disclosed that he and Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] have been conducting a secret romantic relationship, despite her betrothal to Federal Ambassador Jordan Rochester. 

Entertainment journalist Solomon Helios gave full details on his programme: 

“Following Jarl Toredo’s resignation from Unchain, I offered to tell his side of the story. Although he declined a formal interview, he did disclose that he could no longer bear working alongside Princess Duval.” 

“He admitted that he has been romantically involved with the princess since their first meeting several months ago. It seems they both felt it wise to keep the relationship a secret.” 

“According to Toredo, the princess claimed not to have any romantic feelings for Ambassador Rochester, and insisted that the marriage was merely a means to advance her political plans. Initially Toredo accepted this, but it seems that after her engagement the princess became unreachable.” 

“Toredo says that his and Aisling’s love has been sidelined by her political schemes. Quite simply, he feels betrayed.” 

Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] gave this response to the media: 

“I am shocked that my good friend Solomon could believe such lies. It’s obvious that Mr Toredo is being used by those who want rekindle the hostility between [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] and the Federation. My relationship with Jordan Rochester is entirely genuine.”
