:PROPERTIES:
:ID:       38d900f2-69f5-4135-a72b-57fb318b1195
:END:
#+title: Successful Initiatives to Produce New Starports
#+filetags: :galnet:

* Successful Initiatives to Produce New Starports

/21 Sep 3306/

*Pilots Federation ALERT: For the attention of all Commanders* 

New starports to be constructed in 10 systems. 

Two projects to resource the upgrading of refinery outposts into starports have concluded. The aim is to increase efficiency for fleet carrier owners who use large ships for transporting tritium fuel. 

Kavanagh Spaceframes Ltd published this statement from CEO Susannah Haynes: 

“Thanks to a generous number of deliveries, we will have in place fully functioning Orbis starports for the start of October in the Fjorgyn, HR 4979, Wolf 294, Lambda-2 Tucanae and Potriti systems.” 

“All participating traders can now collect their rewards at Blaauw Hub in the Tenche system.” 

A similar announcement came from Dean Bradigan, director of Steel Castle Inc: 

“The many shipments that we received will enable us to provide new Coriolis stations in the LHS 4058, Chakpa, Gally Bese, Eta Cephei and Ninabin systems by the beginning of October. We hope these will provide services to travellers for many years to come.” 

“Rewards for all pilots who delivered these minerals are now available at Teng-hui Station in the Nagasairu system.”
