:PROPERTIES:
:ID:       c0bd22fe-247a-4565-a6eb-479eba371f4c
:END:
#+title: Dredger Clan Faces Possible Extinction
#+filetags: :galnet:

* Dredger Clan Faces Possible Extinction

/15 Nov 3307/

Orion University has been informed that its ownership claim of the Scriveners Clan dredger is placing its population at great risk. 

In the Oochost PC-C c29-0 system, the university’s megaship Scientia Aeterna has used override codes to prevent the dredger from departing. But the nomadic tribe’s refusal to abandon their home has placed them under great pressure, as observed by freelance reporter Casey Kilpatrick: 

“Dredger-class bulk cruisers are the sharks of space – they must always keep moving, constantly gathering raw materials to synthesize into fuel, air and other resources. The Scriveners Clan remained stationary for months while salvaging the Hesperus, but in this system they are trapped without such vital intakes.” 

“Independent observers are now reporting malfunctions in the vessel’s power and life support systems. If the Scriveners maintain their siege mentality, further mechanical failures are inevitable. Orion might inherit the dredger after all, but it will be a ship of the dead.” 

Professor Elizabeth Perez, Orion University’s head of anthropology, responded: 

“The last thing we wish is for any harm to befall these people. My colleagues are urgently discussing ways to convince the Scriveners Clan that we have their best interests at heart. After all, as fellow scientists and researchers, they are a living embodiment of our university’s core values.”
