:PROPERTIES:
:ID:       bf1f6045-a17d-4d00-af54-514d58e95c4c
:END:
#+title: Identity of Nexus Confirmed
#+filetags: :Alliance:3304:galnet:

* Identity of Nexus Confirmed

/19 Jul 3304/

Deputy Inspector Mara Klatt of Alliance Interpol has broken her silence regarding the League of Reparation. 

At a special press conference, she made this announcement: 

“Prior to her death at the hands of the League of Reparation, I worked closely with my predecessor Chief Inspector Kay Kilbride. She revealed how Fleet Admiral Buchanan’s assassination could only have been arranged by a senior figure within the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]]. She was patiently amassing evidence pertaining to this – a task that I inherited when she died.” 

“Information decrypted from the League’s comms network has confirmed Kilbride’s suspicions. I can also confirm that the arrest of Admiral George Varma was due to false leads – misdirection on the part of Varma’s protégé within the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]], Rear Admiral Riri McAllister.” 

“Rear Admiral McAllister is Nexus, the League’s central coordinator. She has now been arrested and formally charged with conspiracy to commit terrorism. We have released Admiral Varma with our apologies.” 

“The decrypted data has also revealed the location of two major League enclaves. The taskforce is organising an operation to eradicate these groups, which we hope will be supported by the galactic community.” 

Council Member Jed Trager was also present at the conference, and remarked: 

“We all owe a debt of gratitude to Inspector Klatt and the late Chief Inspector Kilbride. Thanks to their dedication, Nexus has at last been unmasked. Hopefully this marks the end of the League’s reign of terror.”
