:PROPERTIES:
:ID:       adcf4bcc-ba71-41e0-bb8d-20758033d3bb
:END:
#+title: The Worlds Beyond
#+filetags: :3302:galnet:

* The Worlds Beyond

/12 Jan 3302/

Utopian delegates returned today from the first symposium of the Pioneers Cooperative, a group dedicated to supporting expansion into uninhabited space. Also attending were representatives from Loren's Legion, Communism Interstellar, the Black Birds Squadron, Aisling's Angels, the Canonn, the Independent Pilots Consortium, Emperor's Grace, the Mercs of Mikunn, United German Commanders, EXO, the First Great Expedition, the Code, Adle's Armada, [[id:f57cff55-3348-45ea-b76f-d0eaa3c68165][the Guardians]] of Harmony, CHIMERA, the Distant Worlds Admins and the Hutton Orbital Truckers. 

"To live is to grow, and mankind must push ever outwards", said one attending Utopian explorer. "Humanity has come here today, unified, under a banner of progress, and Utopia is proud to add its support to this noble venture. Our commune in Takurua demonstrated that expansion beyond the core systems is possible, and the success of Obsidian Orbital in Maia shows that mankind has a shared desire to expand the frontiers of human space and scientific understanding." 

Commander Gan 

Utopia News Network | Interstellar Press
