:PROPERTIES:
:ID:       14c3f7a9-258a-4a35-9413-d313e27208f8
:END:
#+title: Congressman’s Criminal Ties Exposed
#+filetags: :Federation:3304:galnet:

* Congressman’s Criminal Ties Exposed

/24 Aug 3304/

An exclusive exposé published by The Mars Tribune has revealed that a member of Federal Congress has close ties to a criminal organisation. 

The extensive feature began with this summary: 

“Congressman [[id:44f9cf85-8fb2-4e37-9b8a-8834faf80728][Morgan Unwin]] has been in debt to the notorious [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] cartel for nearly a decade. Information uncovered by our reporters proves that he has used his influence to traffic enormous quantities of the cartel’s drugs in order to keep his own addiction secret.” 

Following publication of the feature, Mr Unwin was arrested by the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]], and now faces expulsion from Congress. An investigation into [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]]’s narcotics operation in Olympus Village is also underway. 

A spokesperson for Congress made this statement: 

“We are indebted to The Mars Tribune for uncovering a criminal conspiracy that might otherwise have continued undetected. This highlights the value of investigative journalism to the Federation.” 

The Tribune’s billionaire owner, [[id:74cae77e-fab1-4a22-9c31-daaa15d8fd0e][Kingsley Cordova]], has been invited to a special event by Congress to express its gratitude. As well as The Mars Tribune, his conglomerate Cordova Group runs many small companies in the Sol system.
