:PROPERTIES:
:ID:       f6a68b68-c01c-42be-a49a-1632602ae4df
:END:
#+title: Initiative to Eradicate Rockforth Fertiliser
#+filetags: :galnet:

* Initiative to Eradicate Rockforth Fertiliser

/16 Oct 3305/

The Rockforth Corporation’s EX7 fertiliser has been linked to the blight affecting crops in a number of systems, prompting an initiative to remove the product from the market.  

Dr Genevieve Kane of the Interstellar Association for Agriculture delivered an urgent message: 

“Comparative analysis has confirmed that the blight is caused by the EX7 fertiliser. The original poor harvests have been attributed to natural factors, and it is now thought that the situation could have been contained had the fertiliser not exacerbated the problem.” 

“Initial food shortages were offset by a recent trade appeal in the [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] and Orerve systems, but the blight’s symptoms have since been reported in hundreds of systems. While we investigate the reasons for this rapid spread, preventing further fertiliser distribution is vital.” 

Rockforth fertiliser can now be collected at zero cost from the following markets: 

Sharon Lee Free Market, Orrere 

Lave Station, [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] 

Warinus, [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] 

Shifnalport, [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] 

Davies High, [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] 

Watson Station, Orerve 

Roentgen Hub, LFT 37 

Macedo Station, Lei Zi 

Phillips [[id:e179ecca-9ab3-4184-b05e-107b2e6932c2][Gateway]], Ensoreus 

Baird [[id:e179ecca-9ab3-4184-b05e-107b2e6932c2][Gateway]], [[id:d4b595af-536d-4575-af11-f07f3ac3ff40][Arque]] 

La Soeur du Dan Ham, Riedquat 

The Teveri Progressive Party has arranged for the safe disposal of the fertiliser and has offered to compensate pilots for their efforts. The fertiliser should be delivered to Wiley Port in the Teveri system. 

To expedite this initiative, Lakon Spaceways has agreed to lower the cost of the Type-6 Transporter, Type-7 Transporter and Type-9 Heavy. Cargo rack prices have also been reduced in all starports. 

The initiative is scheduled to run from the 16th to the 22nd of October 3305. If the final target is met earlier than planned, the campaign will end immediately.
