:PROPERTIES:
:ID:       b593e3a1-faaa-4eae-adfa-e311bba797ec
:END:
#+title: Florence Lavigny Calls for Calm
#+filetags: :3301:galnet:

* Florence Lavigny Calls for Calm

/18 Aug 3301/

Florence Lavigny Calls for Calm 
 
In her first public appearance since the death of her fiancé Emperor [[id:3cb0755e-4deb-442b-898b-3f0c6651636e][Hengist Duval]] on their wedding day, Florence Lavigny made a short statement in the Imperial Palace press hall and answered a few questions. Her comments come amongst rising tensions on Capitol. 

“We must remember proper decorum in this sad time. Our beloved Emperor would not want his death to be used as an excuse for some of the unpleasantness seen in our city. We should mark his passing with proper quiet reflection and respect for our fellow citizens.” 

Although clearly devastated by the loss of her long-time friend, she maintained an air of regal dignity, providing a glimpse of what she might have been as Empress Regent. As well as calling for calm, she recalled earlier times with the Emperor in his youth, even some events while her first husband Prince Aristide Lavigny was still alive. These anecdotes forced smiles from even the most sombre reporters gathered there.
