:PROPERTIES:
:ID:       7391f3b6-8546-4942-9d34-eed18418da82
:END:
#+title: Upgraded Xeno Scanner Requires Resources
#+filetags: :Federation:Alliance:Thargoid:galnet:

* Upgraded Xeno Scanner Requires Resources

/07 Sep 3309/

*Pilots’ Federation ALERT*  

Aegis aims to provide an update to the pulse wave xeno scanner that can locate captive humans on Thargoid Titans. 

Dr Maximo Fonseca, the Alliance’s scientific liaison to Aegis, informed the media about the project: 

“Information provided by [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]] suggests that people abducted by the Thargoids are being kept alive aboard the Titan motherships inside ‘pods’. This theory makes sense - since Thargoid atmospheres are toxic to humans, any captives are surely sealed in an environment that meets their respiratory and nutritional needs.” 

“The pulse wave xeno scanner has been modified by Allied, Federal and Imperial technicians, working in concert using Aegis’s communications protocols. The module’s electromagnetic pulse technology aims to identify these pods by detecting several key markers generated by living humans.” 

“A broader effort to prepare for humanitarian rescue efforts is underway, but we have encountered a shortage of neofabric insulation, polymers and thallium. Shipments of these materials are urgently required to support the crews onboard rescue megaships in its vital work.” 

Contributors are asked to transport these commodities to Muller Terminal in the Rabh system. The CD-51 1447 Imperial Society has agreed to coordinate the enterprise on behalf of Aegis, and will protect deliveries by redeeming bounty vouchers for all wanted ships in the system.
