:PROPERTIES:
:ID:       f388e066-365e-4204-9303-d5aa40041f42
:END:
#+title: The Emperor Speaks out for Unity
#+filetags: :galnet:

* The Emperor Speaks out for Unity

/18 Jul 3301/

The Emperor Speaks out for Unity 
 
Although the Emperor showed some signs of frailty when he appeared before the Senate earlier today, his voice was firm as he called upon the assembled senators to work together and not against each other for the good of the Empire. 

“We live in times that hold great promise for our beloved Empire. The uncertainty of the past months has weakened our resolve and this cannot be allowed to continue. For too long some leaders of our society have vied against each other and squandered resources over a matter which will be guided by tradition. 

“As Emperor it is my duty to ensure the success of the Empire and its continuation long into the future. To that end the previously announced marriage with my good friend Florence Lavigny will proceed at the earliest opportunity. As the wedding has already been announced we will not have to wait the customary thirty days to conduct the ceremony, but we will still give time for wellwishers to attend. Preparations are in the process of being finalised and will be announced by the middle of next week.” 

His speech continued for thirty minutes and covered a range of topics including praising his long term friend  Chancellor Anders Blaine for his stalwart support. The Emperor left the senate to a standing ovation and cheers from the normally businesslike senators.
