:PROPERTIES:
:ID:       1dac56c9-e33d-4da6-9c71-eba6b2185cd0
:END:
#+title: Galactic News: Halsey Talks to the Media
#+filetags: :Alliance:3302:galnet:

* Galactic News: Halsey Talks to the Media

/04 Apr 3302/

Former Federal president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]] spoke to select reporters at Leoniceno Orbital today, answering the questions many have wanted to ask since she was recovered from the wreckage of Starship One. When asked about Starship One's destruction, Halsey replied: 

"I remember very little, really. A thunderous noise, then silence. Being thrown across the bridge in my chair, and then being unable to breathe. I remember one of my bodyguards getting me to the pod as things floated about silently, like a dream. The last thing I remember is a terrible pain in my ears and a very loud noise as the pod filled with what looked like steam." 

The former president's voice was distant, and she seemed to drift off between sentences. She certainly did not sound like the forceful leader from last year. 

A reporter from the Alliance Tribune asked President Halsey what it was like to drift through space for so long: 

"It was wonderful. Amazing. I saw the universe, and our galaxy within it, as I'd never seen it before, and I felt the presence of the real caretakers of our galaxy. The paradox of their existence – tiny yet gargantuan, fleeting yet eternal. They spoke to me as I drifted in the void. It was amazing. I must share their message." 

This unorthodox statement prompted a flurry of further questions, but Halsey's escorts promptly led her from the room.
