:PROPERTIES:
:ID:       f367e784-4743-42db-88cb-f0071621974d
:END:
#+title: Community Goal: New Federal Outpost
#+filetags: :Federation:Empire:CommunityGoal:3302:galnet:

* Community Goal: New Federal Outpost

/28 Jul 3302/

Three weeks ago, the Federation ignited controversy with its decision to establish a series of outposts in the Pleiades sector. The development triggered a decisive response from Empire-aligned pilots, who made repeated attempts to destabilise the campaign. Ultimately, the Federation was able to complete the operation, but the Federation's opponents had made their feelings clear – the superpower's military expansion would not proceed unopposed. 

Now the Federation has announced plans to establish a new planetary outpost in the [[id:acffcea9-44ae-4689-8bc9-74f65c75e0ae][HIP 17225]] system, which it claims will serve as "a trade and resource-processing hub". Those familiar with HIP 17225 A 1 will be all too aware that the planet is home to a number of barnacle sites. 

The Federation has placed an open order for tantalum, building fabricators and energy grid assemblies with which to construct the new base, and has authorised the Future of Segovan to reimburse pilots who deliver these materials to Obsidian Orbital in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system. 

The campaign begins on the 28th of July 3302 and will run for one week. If the Federation's targets are met earlier than planned, the campaign will end immediately.
