:PROPERTIES:
:ID:       b4817ba9-b746-4585-8b72-335669824c95
:END:
#+title: ACT Exposes the Lords of Restoration
#+filetags: :galnet:

* ACT Exposes the Lords of Restoration

/14 Feb 3308/

The Affiliated Counter-Terrorism unit has unveiled a secret cabal of Imperial senators who masterminded the NMLA’s terrorist activity. 

The information was obtained after ACT successfully penetrated the NMLA’s dark-comms network. Captain Saskia Landau provided this summary to the media: 

“Senators Gereon, Jourdain, Nerva, Scordato and Torquatus were at the heart of a powerful conspiracy to permanently remove the position of Emperor. They called themselves the Lords of Restoration, based on their aim to restore executive power to the Senate.” 

“The NMLA became their terroristic agents, weaponised to assassinate the Duvals and other obstacles. Its members were militarised at Darkwater training camps and provided with sophisticated equipment by corrupt Imperial Intelligence agents. But the Lords could never fully control the terrorist figurehead Theta Seven, whose attacks against non-Imperial starports were not part of their original plan.” 

“Marlinism was also exploited as a political lever. The hope was that, compared to this democratic ideology, citizens would view a senator-led Empire as a moderate compromise once the Imperial Family was gone. While this led to the establishment of the Marlinist Colonies, the Lords’ later attempts to influence those systems via puppet politicians did not succeed.” 

“Following the assassinations of Prince Harold and other Duvals, the Lords abducted Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] in January 3307. She was kidnapped en route to a secure location, with Senator Nerva falsifying confirmation of her safe arrival. This allowed the Lords to engineer communications with the Senate via a virtual doppelganger, which were accepted as genuine since they were verified by Imperial Intelligence agents.” 

ACT is working closely with Imperial security agencies to identify all those who collaborated with the Lords of Restoration.
