:PROPERTIES:
:ID:       b7a41212-dbd6-42b2-ba45-f6668fa69c80
:END:
#+title: An Undercover Report on Jokers’ Deck
#+filetags: :3307:Alliance:galnet:

* An Undercover Report on Jokers’ Deck

/05 Oct 3307/

[[id:43e76135-cf13-47bf-9a0c-4d46dbdfa19a][Francesca Wolfe]] of the [[id:b40c2b11-1199-4276-8f40-30cfcef498fa][Wallglass Investigations]] Agency provides an
inside view of the Jokers’ Deck gambling circle.

“[[id:0367ce6a-a18b-4bca-a6d1-da93c2dd200f][Gunnarson]]’s intel was correct. The latest host is multi-billionaire
investor [[id:63f2962b-371f-4475-bbd1-0314201d15c0][Lexi October]], the lady who rescued [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] from
bankruptcy. We’re in one of [[id:1133e15f-59dd-42b3-aaa9-12a0bf3a3287][October Consortium]]’s disused warehouse
complexes, which looks derelict on the outside but is a fabulous
glittering palace within. I don’t actually know what planet I’m on,
since all the servants – including me with my fake ID – were
transported here in total secrecy.”

“[[id:d6578a29-4aa4-47d9-b3b2-22d0bc6c2234][Jokers’ Deck]] is exactly what you’d expect of a luxury casino for the
super-rich. Exquisite food, sumptuous clothes, and dozens of games
from deadlock poker to [[id:892b733c-6ed2-405d-858b-af15e74e1f7d][Giant Verrix]] racing. Wagers are made using
billion-credit chips, precious gemstones and even land deeds to an
entire continent. And that’s not counting the VIP rooms that I can’t
get into.”

“I’ve served exotic drinks to several famous faces, such as [[id:46e97ef5-1771-432a-bec5-dda16f258fe9][Duchess
Rouncival]] and [[id:b62c9e2e-8079-44bc-a30d-d192076162e6][Scorpio DeVorrow]]. I’ve seen [[id:667b1421-4f11-4d0b-a701-154251e79522][Senator Leatrix]] talking
earnestly to [[id:81c5c161-1553-44f0-b5fb-c4a58f1f71d7][Ambassador Rochester]] about a princess they both
know. Arch-Corsairs Trask and Volantyne from the [[id:2dc1b92f-4bdc-4504-ad5f-a9c5794155dc][Kumo Council]] are
here, taking on [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] at the roue mortelle tables. And
there’s no mistaking the voice of Alliance megastar [[id:0a5d1273-0610-43a3-ac86-5d4adce021a7][Xiona]] whenever she
wins big.”

“Oh, and who should walk in just now but… wait, I can hear an
alarm. Looks like a security alert. Damn it, have they detected me? I
should – ”

The message was published by [[id:0367ce6a-a18b-4bca-a6d1-da93c2dd200f][Erik Gunnarson]], who added this coda:

“I’ve heard nothing more from Wolfe since receiving this, and she
didn’t check in at a scheduled rendezvous point. I’ve decided to share
her report as a warning to Jokers’ Deck. If anything happens to her,
just remember we know who you are.”
