:PROPERTIES:
:ID:       d156c569-313f-4401-b6f2-cdba5fd0c63f
:END:
#+title: Core Dynamics has Links to VP’s Death?
#+filetags: :3301:Federation:galnet:

* Core Dynamics has Links to VP’s Death?

/01 Sep 3301/

Core Dynamics has Links to VP’s Death? 
 
In another shocking revelation the Federal Times today posted a story highlighting possible links between a non-exec member of the board of Core Dynamics and Vice President [[id:4bbbdc51-22ca-4f2c-b775-0e4d3b86bb4a][Nigel Smeaton]]’s death. They first referenced an interview on January 28th with Congressman [[id:a52957f3-c3b8-4821-80b9-81db21637b70][George Fallside]] who appeared to have early knowledge of the Vice President’s death.  The Congressman refused to comment on the article, but it is public knowledge of his non-executive directorship of Core Dynamics and several other major arms manufacturers. 

More damning was the evidence concerning one of the crew of the Starship One, Flight Engineer Nick Baron, who had previously worked at Core Dynamics before joining the President’s Crew. From the information package sent by [[id:c04cc538-f85c-4409-9751-9df8b3e56422][Elaine Boyd]] after her death, the Federal Times published extracts of financial records of the flight engineer. 

When tracing these records through a convoluted series of transfers, one of these transfers was through a shell corporation , in which  Congressman Fallside was involved. The trail of the payments revealed that Boyd must have obtained a high level clearance access, possibly provided by Agent Monroe. 

When asked about today’s story, the Chief Editor for the Federal Times commented: 

“There does appear to have been a conspiracy on several levels. We believe that the destruction of the Highliner Antares so many years ago may not have been an accident. When the Vice President was investigating the death of his relative, he must have discovered some of these details, and possible the dark forces killed him, and when our reporter [[id:c04cc538-f85c-4409-9751-9df8b3e56422][Elaine Boyd]] did the same, she too was silenced. We are still not clear how it relates to the present day. Our reporters continue to investigate. 

“At the Federal Times we always seek the [[id:7401153d-d710-4385-8cac-aad74d40d853][truth]] and we will discover the truth here.”
