:PROPERTIES:
:ID:       8baf0cf5-0500-47c4-a196-7a8c4612c9d0
:END:
#+title: Medical Supplies Needed for Starport Bombing Survivors
#+filetags: :Empire:Alliance:galnet:

* Medical Supplies Needed for Starport Bombing Survivors

/18 Mar 3307/

*Pilots Federation ALERT* 

Safeguard Interstellar requires deliveries of medicines to treat casualties from the NMLA’s recent terrorist attack. 

The humanitarian aid organisation is helping to coordinate relief efforts for the starports in the Alliance, Empire and Federation that were bombed last week. CEO Noel Beaumont announced: 

“Hundreds of thousands of civilians still require urgent medical attention after being evacuated from the damaged stations. Many have severe caustic burns inflicted by the corrosive enzyme payload of the explosives. We have already exhausted the majority of supplies in nearby systems.” 

“To reinforce overstretched health services, we request shipments of basic medicines and advanced medicines. These can be delivered to three starports being used as staging areas:  Krylov Ring in the He Bo system, Mackenzie Relay in the [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] system, and Davis Terminal in the Duamta system.” 

Safeguard Interstellar has partnered with three local factions – Perez Ring Brewery, Lavigny's Legion and the Duamta Gold Creative Corp – to reward pilots and distribute the medicines within each superpower. 

Pilots can provide further help by directly delivering repair materials to damaged starports in the Achenar, Alioth, Eotienses, Gateway, Kamadhenu, Lave, Nanomam and Rhea systems. Li Qing Jao station in the Sol system remains an active disaster zone, with civilians still requiring evacuation.
