:PROPERTIES:
:ID:       7d7b3280-d06c-4d9b-a6ea-f5e3a3e4917d
:END:
#+title: Colonia Bridge Project Enters Phase Two
#+filetags: :3307:Federation:galnet:

* Colonia Bridge Project Enters Phase Two

/04 Nov 3307/

*Pilots Federation ALERT* 

Brewer Corporation requests deliveries in the Alcor and Colonia systems for the next phase of the Colonia Bridge project. 

A successful initiative in October resulted in the placement of 30 dockable megaships at intervals of several hundred light years, providing services such as refuelling and repairs. The second phase seeks to establish this support for the full route between the core systems and the Colonia region. 

A press release from Brewer Corporation stated: 

“We are now ready to continue work on the Colonia Bridge, by constructing additional megaships to fill the middle of the planned route. As before, we require shipments of ceramic composites, computer components and thermal cooling units at Macdonald Settlement in the Alcor system or [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]] Station in the Colonia system.” 

“Should deliveries reach sufficient levels, the top 75% of contributors will be awarded an engineered frame shift drive with increased range and faster boot sequence. Our hope is that this encourages deep space explorers and long-distance haulers to take part in the Colonia Bridge project.” 

As an additional reward, the top ten contributors at Alcor and Colonia will be invited to submit naming suggestions for the new megaships. Submissions will be subject to review by the Brewer Corporation board of directors. To ensure a variety of choice, only pilots who have not yet submitted names for the Colonia Bridge megaships will be eligible.
