:PROPERTIES:
:ID:       e6a06ce8-15c3-4370-98dd-828fdcbbe9c1
:END:
#+title: Poor Harvests Impact Core Systems
#+filetags: :galnet:

* Poor Harvests Impact Core Systems

/03 Oct 3305/

The impact of low crop yields in key agricultural systems has reached civilian populations, prompting public concerns over food availability. 

Freelance journalist Adalyn Cross published this report on Vox Galactica: 

“The scarcity of fresh fruit and vegetables has become a major concern. Despite the efforts of agricultural bodies and corporations to prevent shortages from affecting the general public, the availability of produce is believed to have fallen further in recent weeks.” 

“With fear of a widespread food shortage rising, stockpiling of staple foods by markets and citizens has increased. Prices have fluctuated as opportunistic suppliers take advantage of the situation.” 

“It’s clear that the situation is more complicated than a mere bad harvest, but as yet there has been little effective response from local governments.” 

In related news, the Rockforth Corporation has publically responded to the Interstellar Association for Agriculture, following requests for compliance documentation related to its new fertiliser. Rockforth marketing director Rex Whitlock made this statement: 

“We see it as our duty to lead the recovery of affected farming communities, and our revolutionary fertiliser will play a big role. I have full confidence that our new product meets the IAA’s standards, and we will fulfil their request at the earliest opportunity.”
