:PROPERTIES:
:ID:       fe9e43cb-5f73-4c43-8be3-21981fd7e694
:END:
#+title: Standoff for ACT and Theta Seven
#+filetags: :3307:Thargoid:galnet:

* Standoff for ACT and Theta Seven

/07 Dec 3307/

Terrorist ringleader [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] is defying capture by holding thousands of [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cultists hostage in the Mudhrid system. 

Vox Galactica published an on-the-scene report from freelance journalist Redmond O’Hara: 

“Although the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] has been defeated in Mudhrid, the Theta Group bomb-makers remain in control of the Sacrosanct megaship. With so many lives at stake, ACT has focused all its efforts to resolve this tense situation.” 

“We’ve heard that Senior Agent Ramirez and Inspector Klatt have both tried to open negotiations directly with Theta Seven. It is hard to imagine what they might offer him in terms of clemency, but they’re obviously determined to prevent further deaths at the NMLA’s hands.” 

“After speaking to one of ACT’s tactical advisors, I can reveal that Captain Castile’s commando unit tried and failed to board the Sacrosanct as it did the Steel Majesty. This is apparently because the vessel is specially modified to prevent external access, in order to provide the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cultists with a sanctified environment during their pilgrimage.” 

“Speaking of the cultists, they may not have accepted their predicament quite as passively as expected. Internal power failures detected within the Sacrosanct’s hyperdrive systems may well be a result of sabotage, and would explain why it hasn’t left the Mudhrid system. Perhaps in their own way, the Thargoid-worshippers are seeking justice for those murdered by Theta Seven’s appropriation of their deity’s ‘holy’ caustic enzymes.”
