:PROPERTIES:
:ID:       af86a899-2e4b-4e70-b40e-25d6ca10fbfc
:END:
#+title: An Heir to the Imperial Throne?
#+filetags: :3304:galnet:

* An Heir to the Imperial Throne?

/27 Dec 3304/

Imperial senators supporting the isolationist group Nova Imperium have demanded that Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] acknowledge its figurehead, Hadrian Augustus Duval. 

Senator Eloise Winterstone proclaimed to the Senate: 

“The Imperial family must officially recognise Hadrian Duval as one of its own. Given that the Emperor has no children, such an act would secure the future of the Duval bloodline.” 

Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]] replied: 

“Our official position is that Nova Imperium is a fringe organisation with no right to determine policy. We have no more to say on the matter.” 

Political journalist Cassia Carvalho wrote in The Imperial Herald: 

“With the possibility of civil war increasing, the suggestion that Arissa accept Hengist Duval’s grandson as an heir feels like a reasonable compromise. Her lack of response so far has led to accusations of weakness, with many calling on her to step down and for Hadrian Duval to be instated as sovereign ruler.”
