:PROPERTIES:
:ID:       8716203e-452f-4de0-a20c-c350e00522b3
:END:
#+title: Pirate POWs Pack Prisons
#+filetags: :3301:Empire:Federation:galnet:

* Pirate POWs Pack Prisons

/17 Aug 3301/

Pirate POWs Pack Prisons

The [[id:454e8f51-71d3-46a9-ab3b-52b47f4b72b2][Pegasi Pirate War]] stemming from the United [[id:77cf2f14-105e-4041-af04-1213f3e7383c][Imperial]] Offensive has taxed the logistical prowess of the [[id:77cf2f14-105e-4041-af04-1213f3e7383c][Empire]]. Supplies, ships, and personnel must be transported up to hundreds of light years from their source to the Pegasi Sector. Provisioning the Imperial fleet over such distances is a monumental task in itself, but the steady stream of prisoners of war extradited to Imperial space must also be provisioned, guarded, and accommodated. Many prisoners await judgement by the Pilot’s [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][Federation]] for their crimes, while others face judgement in Imperial courts.

With many thousands of prisoners now in custody, accommodation is becoming an issue. Prisoners are currently held in hundreds of locations, creating additional logistical problems. Sources within Empire have indicated that a search for a suitable penal station, capable of holding all the prisoners, has begun.

Commander [[id:5d20aa03-3b1f-46b1-bf38-981cc212ed57][Corrigendum]]
