:PROPERTIES:
:ID:       52166ddb-b0af-49de-a57d-2e7459f9bd6c
:END:
#+title: Galactic News: Economic Turmoil Ahead?
#+filetags: :Empire:3302:galnet:

* Galactic News: Economic Turmoil Ahead?

/12 Aug 3302/

According to the Galactic Finance Times, analysis of the largest corporations in [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] and the Empire reveals evidence of a significant economic downturn in the coming years. 

"We're seeing poor revenue forecasts for a wide range of corporations, including big names like Sirius, Gutamaya and Core Dynamics," said a correspondent for the Galactic Finance Times. "They should be concentrating on marketing to leverage new product ranges, but instead they're diverting resources into intensive research and development. They're ignoring the traditional sales cycle, and we don't know why. It's perplexing." 

Shareholders have seen poor returns on their investments in recent months, with stock prices dropping across multiple sectors, although this has given others a chance to pick up stock at bargain prices. Several of the pertinent corporations were contacted by the Galactic Finance Times, but none deigned to respond. 

Despite the GFT's report, some commentators blame the downturn on the London Treaty, which was signed by the galaxy's three major powers in 3278 following the introduction of the frame shift drive. The treaty enforces strict tonnage limitations for capital ships, and was aimed at preventing an arms race, but in recent years it has come to be perceived as a barrier to economic development. 

One option for investors looking for a risky but possibly lucrative venture is a start-up called MetaDrive Inc., a small company based in the Chi Orionis system specialising in hyperdrive research. The company is reported to be seeking investment.
