:PROPERTIES:
:ID:       e42a2e30-8b0f-4f6f-bb14-0afe2dfbb94f
:END:
#+title: Engineers Boost Ship Module Upgrading
(fset 'galnet\ import
   (kmacro-lambda-form [?\C-m ?\C-f ?\C-f ?\C-@ ?\C-e ?\C-\[ ?w ?\C-c ?r ?f ?\C-y ?\C-m ?\C-\[ ?x ?\C-\[ ?p ?\C-m ?\C-\[ ?p ?\C-m ?\C-\[ ?\[ ?8 ?^ ?\C-x ?o ?\C-x ?h ?\C-\[ ?w ?\C-x ?o ?\C-y ?\C-a ?\C-i ?\C-\[ ?\[ ?8 ?^ ?\C-m ?\C-c ?\C-c ?\C-x ?k ?\C-m ?\C-x ?k ?\C-m ?\C-n] 0 "%d"))

* Engineers Boost Ship Module Upgrading

/17 Dec 3306/

*Pilots Federation ALERT* 

The effectiveness of engineers’ upgrading for ship modules will be boosted until the 7th of January 3307. 

During this time, engineered weapons and modules will receive increased augmentation for the same amount of materials. This will apply to every workshop in Alliance, Imperial, Federal and independent space. 

Lori Jameson, an engineer based in the Shinrarta Dezhra system, provided details to Vox Galactica on how this collaboration came about: 

“After the Eurybia incident, some of us contacted Liz Ryder and offered our support. It was horrifying how her expertise had been abused by the NMLA, leaving her unfairly maligned as a terrorist supporter. There were concerns that her situation might reflect badly on engineers in general.” 

“We soon established communication links between every workshop, and agreed to offer a universal boost to upgrades. Hopefully this will remind pilots how much we value their custom, and that we remain a trustworthy resource.” 

Mel Brandon, one of four engineers in the Colonia Region, commented: 

“It’s about time that we all started talking to each other. Our services are valuable to the whole galaxy. We deserve better protection. Maybe we have to start protecting ourselves.”
