:PROPERTIES:
:ID:       dac28808-7ac7-420c-8307-ac30e036de45
:END:
#+title: Galactic News: Reports Surface of Mysterious Attacks
#+filetags: :Federation:3303:galnet:

* Galactic News: Reports Surface of Mysterious Attacks

/20 May 3303/

Reports have surfaced of mysterious attacks in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system, where eyewitnesses claim to have found the remains of a number of Federal vessels. 

According to reports, the damage to the ships’ hulls was not consistent with any known form of weaponry. Furthermore, several observers claim to have seen the so-called unknown ships at the wreckage sites. Attempts to intercept the ships were unsuccessful. 

Chief of Federal Security Admiral [[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], who is understood to be investigating the mysterious ships, addressed the reports: 

“These claims are certainly troubling, but I would remind you their veracity has not yet been verified, and I would urge the public to remain calm. Rest assured that we are investigating the matter.”
