:PROPERTIES:
:ID:       83fe2ea8-cf35-4a13-8aba-5240ec5512e3
:END:
#+title: Galactic News: Imperial Ships Deployed to Pleiades Sector AB-W B2-4
#+filetags: :galnet:

* Galactic News: Imperial Ships Deployed to Pleiades Sector AB-W B2-4

/08 Sep 3302/

For much of the past week, the galactic community has been captivated by the mysterious shipwreck discovered in the Pleiades Sector AB-W B2-4 system. The wreck, which was found on one of the system's moons, is believed by many to be the remains of a non-human starship. 

Given the magnitude of the discovery, it was only a matter of time before one of the superpowers took action. That action has come in the form of an Imperial deputation, which was despatched to the system within the past twelve hours. Eyewitness reports indicate that a Majestic-class Interdictor has taken up position directly over the shipwreck site. 

The Empire has not commented on the deployment, but Federal President Zachary Hudson was quick to condemn the act. 

"It is no surprise that the Empire is attempting to control the site, but the fact is that they have no authority in AB-W B2-4, and no right to lay claim to this discovery. If the Empire makes any effort to prevent access to the site, be assured that the Federation will respond appropriately."
