:PROPERTIES:
:ID:       e7eb9085-2ba8-474f-ae75-ffe78ddce159
:END:
#+title: Galactic News: Alliance Campaign Concludes
#+filetags: :Alliance:3304:galnet:

* Galactic News: Alliance Campaign Concludes

/05 Jan 3304/

The Alliance has announced that its operation to reclaim the supply lines connecting its California Nebula bases with the core systems has reached a successful conclusion. 

The campaign received the support of hundreds of independent pilots, who eliminated the pirates targeting the supply lines and recovered escape pods from ships destroyed by the agitators. Those rescued from the shipwrecks are now recovering at [[id:b191bbd1-f2ed-4371-9aae-f17f76db44b3][Darwin Research Facility]]. 

As the campaign drew to a close, the Alliance released a statement: 

“We are immeasurably grateful to those who participated in this operation – you have saved our allies from a terrible fate.” 

“A pertinent question remains unanswered, however. Where did these criminals come from? Alliance intelligence has surmised that they may have been driven out of their home systems by a second group of agitators. If this is the case, this latter group could represent an even greater threat to civilised space.” 

Pilots who contributed to the initiative can now collect their rewards from [[id:b191bbd1-f2ed-4371-9aae-f17f76db44b3][Darwin Research Facility]] in the [[id:cba54e17-62e5-4dc8-be29-a425cd07e6cf][California Sector BV-Y c7]] system.
