:PROPERTIES:
:ID:       de81fe58-bccc-4d0e-8fb4-19dbfb83998f
:END:
#+title: Community Goal: Conflict in Colonia
#+filetags: :CommunityGoal:3303:galnet:

* Community Goal: Conflict in [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]

/20 Oct 3303/

Since it was founded in July 3302, the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] community has become a bastion of peace, seen by many as an island of calm in a sea of conflict. 

But the region is not impervious to occasional outbreaks of violence, and as [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]’s population grows, such outbreaks look likely to become more frequent. 

The latest such incident involves The Nameless, a criminal faction based in the Carcosa system, which has started attacking ships in [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]. In an effort to restore order, the Colonia Council has issued a call to aid, pledging to reward pilots who help reduce the criminals’ numbers. The Nameless has responded in kind, promising generous incentives to those who help fight the Colonia Council’s peacekeepers. 

Both factions have set out week-long operations to achieve their aims, which will begin on the 19th of October 3303.
