:PROPERTIES:
:ID:       cfeae5f0-ab72-4c42-bbfa-9982085a50ca
:END:
#+title: Galactic News: Second Mysterious Wreck Discovered
#+filetags: :3302:galnet:

* Galactic News: Second Mysterious Wreck Discovered

/05 Nov 3302/

A shipwreck bearing strong similarities to that recently found in the Pleiades Sector AB-W B2-4 has been discovered in the HIP 17862 system. 

The wreck was found by one Commander Denneb on the airless planetoid 6 C A. 

Images of the site, shared by the many independent explorers and scientists who flocked to investigate it, show an unconventional-looking vessel with a distinctly organic quality. Like the shipwreck found in the Pleiades Sector AB-W B2-4, the wreckage encompasses a number of vaguely wing-like elements roughly arranged around an octagonal core. 

The discovery has stimulated considerable debate among scientists and xenobiologists. So far, as with the previous shipwreck, no concrete information about the vessel's origin has emerged. 

Commentators have observed that the ship bears no apparent signs of weapons damage, and that the concentrated debris field suggests the vessel was still intact when it hit the planet's surface.
