:PROPERTIES:
:ID:       488137ee-6e22-47f6-93b1-05f2a26e2780
:END:
#+title: Sothis Crystalline Gold
#+filetags: :3301:galnet:

* Sothis Crystalline Gold

/25 Sep 3301/

Sothis Crystalline Gold 
 
Scientists based at Newholm Station in the Sothis system have made a startling announcement – the discovery of an entirely new metalloid. The material, called Sothis Crystalline Gold, is produced by exposing ordinary gold to the thermal vents that line the seabed of the planets Sothis A5 and Sothis A6 – or, more specifically, to the submarine gas emitted by these vents. Exactly how the gas transforms the gold is not yet fully understood, but the scientists claim that the resultant metal is completely unique. 

Given the emergent nature of the discovery, the scientists of Newholm Station have yet to find any applications for Sothis Crystalline Gold, but they are optimistic about finding constructive uses for the material. They are also offering entrepreneurial pilots and explorers an opportunity to earn a quantity of the rare material by delivering gold to Newholm Station in the Sothis System, thereby allowing the scientists to produce more Sothis crystalline gold and conduct further tests.
