:PROPERTIES:
:ID:       bb7c7486-aa01-41dc-a582-df3dd6c43c8e
:END:
#+title: [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] Receives Vital Supplies
#+filetags: :galnet:

* [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] Receives Vital Supplies

/09 Jun 3308/

*Pilots’ Federation ALERT* 

Shipments delivered to the Upaniklis system have enabled the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] generation ship to resume its millennia-long voyage. 

Tritium, medical diagnostic equipment and power generators were needed to finalise the retrofit of the ancient vessel. Bounties were placed on all wanted ships in the system to protect traders from pirates targeting the flow of traffic to the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]. 

A statement was provided by Captain Jonathon Forester:  

“The [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] has now achieved full operational status, and for the first time is capable of faster than light travel. I offer my deepest gratitude to all those who made this possible. It will be my honour to once again lead my people on our journey among the stars.” 

The majority of the original population have begun to migrate back to the generation ship, which nurtured their isolated micro-civilisation for over a millennium. A few thousand [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]ns have elected to remain at Forester’s Choice outpost, under the guidance of the ship’s former custodian Erin Grey. 

Itsuko Harada, CEO of Upaniklis Vision Incorporated, announced: 

“When the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] first arrived in our space, we were pleased to play a part in rescuing its people. I am likewise overjoyed that we could aid its historic rebirth. Rewards for all pilots who made deliveries, and those who defended them against criminals, are now available at Fozard Port.” 

The [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]’s transformation was achieved thanks to the advanced engineering skills of the Artificers Clan, who performed repairs and updates at great speed. The clan’s dredger has now left the Upaniklis system, having been provided fresh food supplies by the Golconda Union.
