:PROPERTIES:
:ID:       1ed7194d-c80c-456f-8599-348e69771828
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/a336cc5c-55fe-47a7-aa45-2ea293699187?resourceVersion=id%3A4924
:END:
#+title: Fleet Admiral Vincent Pronounced Guilty
#+filetags: :3307:Federation:galnet:

* Fleet Admiral Vincent Pronounced Guilty

/08 Feb 3307/

A Federal High Court jury has found Fleet Admiral Lucas Vincent guilty of conspiracy to commit murder and treason. 

The court heard how Vincent worked with Core Dynamics CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] to sabotage Starship One and assassinate then-President Jasmina Halsey, in order to increase military contracts. 

The Federal Times’s crime correspondent Ethan Takahashi observed: 

“Within minutes of Vincent receiving a life sentence, Federal Intelligence Agency teams arrested several co-conspirators in the Federal Navy along with some government officials.” 

“Jupiter Rochester himself has evaded arrest by fleeing to the HIP 54530 system, where loyalists within Core Dynamics are establishing a breakaway faction named Jupiter Division. Industry analysts believe that this corporate split has long been planned, but is being accelerated because of the trial.” 

“Rochester’s responsibility for the Starship One tragedy raises many questions, especially for his powerful family. It will certainly fuel the conspiracy theory that he is a member of a covert group of powerful figures, who manipulate events to benefit the military/industrial complex.” 

“However, a more plausible theory – that [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] was responsible – now seems to have been debunked. Nothing presented in court suggested that the president had any involvement in, or knowledge of, the plan to eliminate his predecessor.”
