:PROPERTIES:
:ID:       3b4deceb-7ece-435b-a1d6-b0fa4ce62089
:END:
#+title: A Vintage to Remember
#+filetags: :galnet:

* A Vintage to Remember

/26 Jan 3304/

Angeli Imperial Enterprises has announced an initiative to construct an orbital family restaurant in the Wangal system. The eatery, which will be named DaMorg's Bar and BBQ, will allow spacers to enjoy the finest food and drinks that Wangal has to offer. 

In support of this initiative, Angeli Imperial Enterprises has issued an open order for various construction and outfitting materials, and has pledged to pay well above the market rate for these commodities. Independent pilots who want to support the initiative are instructed to deliver the requested goods to Nelder City in the Wangal system. 

A spokesperson for Angeli Imperial Enterprises released the following statement: 

"We are eager to share our fine produce with the galaxy at large. 'When there is plenty of wine, sorrow and worry take wing.' Let's bring that joy to Wangal…and beyond!" 

The campaign begins on the 25th January 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
