:PROPERTIES:
:ID:       6e35cc4e-6e84-4a03-af9c-e4f7758a6f95
:END:
#+title: Week in Review 27 Oct 3304
#+filetags: :Empire:Federation:Alliance:Thargoid:3304:galnet:

* Week in Review

/27 Oct 3304/

Here are this week’s major stories. 

The Alliance Assembly has decided not to adopt President [[id:8520e75f-0479-42c5-9083-f9abfbad721e][Gibson Kincaid]]’s proposed changes to the constitution, and has ruled against imbuing the role of president with executive powers. The Assembly has agreed to update the role, however, with the creation of a new non-political department known as the Office of the Alliance President. The presidential term has also been extended to three years. 

The [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corporation has publicly offered to work with engineer [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] in the development of further Guardian-human technology. Some business analysts have advised [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] to take advantage of the offer to mass-produce his designs, while others have warned that Sirius Corp is seeking a monopoly over Guardian-human technology. As yet there has been no response from Ram Tah. 

Several digital crimes, including the theft of a billion credits from [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]], have now been attributed to a mysterious criminal organisation known only as the Collective – a band of anti-authority ‘hacktivists’ who believe that all information should be publicly available. Security forces have launched investigations into the group. 

Meanwhile, as the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]] continues its investigation into The Mars Tribune, the newsfeed’s parent company, the Cordova Group, has filed a formal complaint. [[id:74cae77e-fab1-4a22-9c31-daaa15d8fd0e][Kingsley Cordova]], billionaire owner of The Mars Tribune, said the accusations were an insult to the publication’s integrity. 

Imperial Senator [[id:1d3d8a69-609b-4e83-b1a1-a46cb23ba195][Caspian Leopold]] has launched an appeal to help those affected by Thargoid attacks. While the senator’s rehabilitation centre has helped hundreds of thousands of refugees, it seems further aid is needed to avert a humanitarian crisis. 

Finally, the Palin Institute’s appeal for Thargoid materials has been enthusiastically received by the galactic community. Professor Cora Shaw thanked those who supported the institute’s latest scientific initiative, which will aim to advance understanding of the Thargoids. 

And those are the main stories this week.
