:PROPERTIES:
:ID:       d598b13e-1b99-47b3-a1d5-8e91674e5861
:END:
#+title: Azimuth Resurgent
#+filetags: :3308:Thargoid:galnet:

* Azimuth Resurgent

/20 Jun 3308/

Salvation has announced that his partner organisation Taurus Mining Ventures is a modern incarnation of [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biochemicals]]. 

The revelation came via a public statement across all media channels: 

“This is [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. In light of recent speculation, we are rebranding Taurus Mining Ventures as [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]]. My intent is to prove that Azimuth has no further need to conceal its operations.” 

“Two centuries ago, Azimuth’s pioneers first acquired evidence of the alien creatures now referred to as Thargoids. My research division focused exclusively on studying this life form and preparing for the inevitable inter-species conflict. When [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biochemicals]] was commercially overtaken by Pharmasapien over a century ago, I ensured key assets and personnel were removed from company records prior to the acquisition. We continued our research in secret, free from shareholders and corporate espionage.” 

“Since then, my team has led multiple projects to develop necessary advancements for the inevitable war. Our work with INRA on the [[id:0ffe3814-d246-41f3-8f82-4bb9ca062dea][mycoid]] virus was one early success. More recently, locating the Proteus in Trapezium Sector YU-X c1-2 provided us with a key breakthrough in weaponising Guardian technology.” 

“My anti-xeno superweapon has already saved billions of lives. [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]] is currently developing the next generation of this weapon, with which I intend to permanently cripple the Thargoid war machine.” 

“Caleb Wycherley is no more, but his accomplishments laid the foundations for the man I have become. A man whose life goal has always been to save humanity from extinction.”
