:PROPERTIES:
:ID:       a5424d9d-fa37-4213-ba95-be8c616b9c64
:END:
#+title: Assembly to Vote on Proposed Changes
#+filetags: :Alliance:3304:galnet:

* Assembly to Vote on Proposed Changes

/07 Sep 3304/

The Alliance Assembly has agreed to hold an internal vote on President [[id:8520e75f-0479-42c5-9083-f9abfbad721e][Gibson Kincaid]]’s proposed changes to the constitution. 

Kincaid has lobbied for the role of president to be invested with executive powers, and for each presidential term to last six years. 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] told the media: 

“After much discussion, the Assembly has agreed to vote on President Kincaid’s proposals in mid-October, at the same time as the presidential election. We will announce any amendments to the constitution shortly afterwards.” 

Milo Vesper, editor of The Alliance Tribune, discussed this development: 

“President Kincaid’s proposals are seen by some as a long-overdue restructure of the political system. Compared to the current bureaucratic procedure, having a single person make all executive decisions has an obvious appeal. But some in the Assembly are concerned that such changes could imbue the president with emperor-like levels of authority.” 

“Prime Minister Mahon is playing down such fears, but the words ‘constitutional crisis’ have already been heard in Parliament. Whatever happens, this could be the most significant election in the Alliance’s history.”
