:PROPERTIES:
:ID:       df686227-47ea-4857-aba3-e0ced6c8ba41
:END:
#+title: Memorial in the Heavens
#+filetags: :3301:galnet:

* Memorial in the Heavens

/06 Sep 3301/

Memorial in the Heavens 
 
Commander Sataris, a member of the East India Company, was recently honoured by an anonymous benefactor. To commemorate his mother’s recent passing, the rights to register a planet in her name were purchased from Universal Cartography. 

Cynthia Sideris, chairwoman of Universal Cartography, read a statement from the anonymous benefactor: 

“Commander Sataris has served with distinction, valour and honour in all his duties, regardless of the circumstances. In honour of his late mother, rights have been purchased to rechristen a world in the BD+26 2184 system as ‘Kathy McBrayer’. Any mother capable of rearing a son like Sataris is well deserving of such a memorial. Kathy is an example to us all.” 

Commander Sataris responded by saying: "I invite all members of the Pilots Federation to visit the memorial planet Kathy McBrayer in BD+26 2184.” 

Chairwoman Sideris said that Universal Cartography will finalize the change to the planet’s name in the coming weeks. 

Commander Corrigendum 

Jameson Memorial Review | Interstellar Press
