:PROPERTIES:
:ID:       c4ea8ef3-0aac-4774-ac95-6c499c4e4eee
:END:
#+title: Coalsack Nebula Reports Thargoid Activity
#+filetags: :3308:Federation:Alliance:Thargoid:galnet:

* Coalsack Nebula Reports Thargoid Activity

/15 Nov 3308/

The human colonists in the [[id:6f086af9-53a6-4d37-9800-b81d2537837c][Coalsack Nebula]] has raised the alarm after Thargoid forces appeared several systems. 

Following recent attacks on systems and vessels in the [[id:6fee136e-381f-47a2-ba13-6d74c8798803][California Nebula]], it appears that the Thargoids have again sought to occupy systems where [[id:b41c0ea3-93f4-4aef-8c9c-db0b140719c0][barnacle]] fields are present on planet surfaces. 

Councillor [[id:79539fa9-400a-44d7-9e31-37ca9ab4863d][Lewis Laychurch]], representing the [[id:f9e96dfd-3161-46b0-a9bc-0335447c4693][Alliance Expeditionary Pact]] in [[id:80076c05-2ff7-4655-aa14-02ccfcfb11c9][HIP 62154]], provided the following to the Alliance Tribune: 

“Our security craft regularly patrol between the populated systems in this region. We had the first reports of nonhuman signals this morning. Obviously we’ve seen Thargoid activity in the Coalsack Nebula several times before, but this time was different. It’s not an attack as much as a presence.” 

“We witnessed a huge upsurge in these signals in multiple systems. Over a couple of hours, it felt like Thargoid activity was visible on scanners wherever our ships looked. It’s exclusively in areas with barnacle sites, too.” 

Now, there’s no secret that the Thargoids aren’t happy with our interest in the meta-alloys those sites produce. But this time they’re not attacking ports, or either the Spirit of Nysa or Song of Mecchi megaships. It’s like they’re waiting for something.” 

The described behaviour matches similar Thargoid incursions into other populated systems in recent weeks. Researchers in the nebula have withdrawn from ongoing field studies of barnacle sites, citing safety concerns. 

In other news, [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]] has announced that the Glorious Prospect will distribute the [[id:a5427e6e-e2f5-4c09-b595-97bbc14894ee][Mbooni]] permit from the LHS 1163 system, instead of the T-Tauri system as planned. Federal authorities offered protection to the megaship to reduce the travel time between the two locations, granting combat pilots swift access to the anti-xeno weaponry offered at Prospect’s Deep.
