:PROPERTIES:
:ID:       a16c9543-ec2e-4388-9b64-b9f2882e2292
:END:
#+title: Utopia: More Than a Cult?
#+filetags: :3301:galnet:

* Utopia: More Than a Cult?

/03 Sep 3301/

[[id:058a658d-e1ce-4364-a92b-b9607495c73f][Utopia]]: More Than a Cult?

Spokespeople for Utopia have responded to recent accusations that dissidents in systems under their control are being roughly treated.

"I've been saddened by recent publications that describe the [[id:ff7259da-5b38-486b-8a3b-61ba9adca854][Utopia movement]] as a cult or oppressive theocracy," Utopia futurologist Dr Saeed McNamara said. "All societies have disruptive elements who threaten the stability of the whole, but I like to think we take a more humane approach to dealing with them than others.

“Rather than enslaving or oppressing disruptive elements, or shipping them off to penal colonies to break rocks for the rest of their lives, we introduce our problem citizens to revolutionary simulation technology designed to increase their empathy for their fellow men and women. Criminals and dissidents aren't evil – they've just become disconnected from society. We've proved time and again that seeing the world through the eyes of others, through technology, can be a healing experience."

Dr McNamara declined to elaborate further on the nature of Utopia's corrective sims, or to address rumours that those subjected to these treatments manifest radically altered personalities.

Commander Jendrassik
