:PROPERTIES:
:ID:       bf5a5d2e-fbe0-4e24-a60f-a331528107af
:END:
#+title: Kaine Launches Alliance Resource Drive
#+filetags: :Federation:Alliance:Thargoid:galnet:

* Kaine Launches Alliance Resource Drive

/30 Nov 3309/

*Pilots’ Federation ALERT* 

Councillor [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]] has requested deliveries to the [[id:0b991a8e-234a-4888-8c0a-b3c64498f217][Tionisla]] system in protest against the anti-xeno defence pact. 

Pilots are asked to deliver shipments of hazardous environment suits, micro controllers and titanium to Brett High. The Alliance Rapid-reaction Corps, which is hosting the initiative, will protect participants by redeeming bounty vouchers for the destruction of any wanted ships. 

The campaign was personally arranged by Councillor [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]], the representative for [[id:0b991a8e-234a-4888-8c0a-b3c64498f217][Tionisla]] in the Alliance Assembly. Speaking to the Old Worlds Gazette, Kaine stated: 

“I aim to prove that the Alliance’s military fleet is not as dependent upon [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] as many believe. This campaign demonstrates our capability to stockpile vital resources for the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]]. And we have plenty of researchers, mechanics and manufacturers ready to develop our own defences against the Thargoids.” 

“It’s clear to me that [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] never intended to honour his anti-xeno commitments. I’ve seen evidence of [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] negotiating favourable contracts with Allied tech and military corporations. Their special access to the Alliance’s markets, plus the endorsement of our prime minister, have provided them with unfair leverage. The true cost of the pact has yet to be revealed, but you can bet that Allied citizens will pay the price while Sirius’s profits soar.” 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has not commented on the [[id:0b991a8e-234a-4888-8c0a-b3c64498f217][Tionisla]] campaign, other than to confirm: “A formal inquiry into the strategic defence pact is ongoing, and the Assembly will study its findings carefully.”
