:PROPERTIES:
:ID:       85fe563f-31ad-47be-a390-6eec741ee80b
:END:
#+title: Alliance Initiative Concludes
#+filetags: :Alliance:3304:galnet:

* Alliance Initiative Concludes

/03 Aug 3304/

The Alliance has announced that its appeal for mined resources has reached a successful conclusion, having received an overwhelming response from the galactic community. Huge quantities of raw material were delivered to California [[id:e179ecca-9ab3-4184-b05e-107b2e6932c2][Gateway]] over the past week, which will be used to construct an Ocellus starport in the MEL 22 Sector GM-V C2-8 system. 

With the campaign at an end, Alliance official Torvan Dast issued the following statement: 

“We are grateful for the efforts made by those pilots who helped bring this initiative to fruition. Construction of this starport will make the long journey to the California Nebula safer for traders and colonists alike.” 

Construction of the new starport is expected to begin soon. Pilots who contributed to the initiative can now collect their rewards from California [[id:e179ecca-9ab3-4184-b05e-107b2e6932c2][Gateway]] in the Synuefai EB-R C7-5 system.
