:PROPERTIES:
:ID:       d9b65140-35c7-4ced-b70e-f13c8389110e
:END:
#+title: Marlinist Refugees Flee to the Federation
#+filetags: :galnet:

* Marlinist Refugees Flee to the Federation

/20 Oct 3306/

The Empire has formally demanded that the Federation extradites all Marlinist political refugees that have fled into their space. 

Hundreds of thousands of believers in the republican ideology evacuated their homes following anti-terrorism lockdowns. The Imperial blockade in Ackwada prevented ten megaships from escaping, but others carrying huge numbers of Marlinists have appeared in the Federal systems Charunder, Ennead, HIP 36081, LTT 1935, LTT 3607 and Thetis. Many smaller vessels are also thought to have spread far and wide. 

Imperial Ambassador Imogen Luciana sent the formal request: 

“The Federation is harbouring potential criminals who are connected to the NMLA terrorists. We insist that they are detained and returned to us to face justice.” 

Federal Ambassador Jordan Rochester, who was once engaged to Princess Aisling Duval, provided an official response: 

“There is no extradition treaty for unconvicted citizens, and these people have claimed political asylum. I have requested that Congress grant them sanctuary within the Federation, and that we offer protection to all Marlinists seeking to escape discrimination by the Empire.” 

Although there is no indication that Marlinist emigrants have set course for Alliance space, Prime Minister Edmund Mahon confirmed that they will be welcomed. Some independent systems are also offering assistance, while others have warned that any influx of refugees will be resisted.
