:PROPERTIES:
:ID:       b0215832-e24b-42a3-b2dd-cb6eb29c16c3
:END:
#+title: Galactic Summit Cancelled – NMLA Attacks Superpowers
#+filetags: :3307:Empire:Federation:Alliance:galnet:

* Galactic Summit Cancelled – NMLA Attacks Superpowers

/11 Mar 3307/

The conference in the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system has ended prematurely after terrorist bombings against nine starports across the Alliance, Empire and Federation. 

Sirius Corporation confirmed that the cancellation was due to fears that Patterson Enterprise station may be the next target. All scheduled business, including finalising the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Treaty, has been halted. The delegations are returning to their home systems under high security.  

Temporary permits for the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system will remain in place for one week. Pilots who contributed to the security and trade initiatives held in partnership with the Empire can collect their rewards at the Spirit of Laelaps. [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]], Gutamaya and [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] will continue to offer a 10% discount on all their ships for one more week. 

The Neo-Marlinist Liberation Army has claimed responsibility for the simultaneous attacks in nine systems, including superpower capitals [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]], [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] and [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]].  

The following message was broadcast on [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] propaganda channels: 

“I no longer have a name. Nor a family. Nor a future. Each taken by the Empire. Now all I have is the dehumanising number printed on my uniform in their torture chambers. Now all I am is [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]].” 

“The Alliance and Federation’s rulers have revealed themselves as imperialist supporters of the Duval dynasty, which has crushed our ideals for a thousand years. Peoples of the galaxy – you can change this. We give you your own Nine Martyrs. Use them to retake control and regain your power.” 

Media newsfeeds are detailing the impact and implications of the attacks. There is speculation that [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] activists were concealed among Marlinist refugees that fled to Alliance and Federation space to escape Imperial persecution.  

The Marlinist Parliament has officially stated it has “no connection to Neo-Marlinist extremists”, and that it will cooperate with security and emergency services during this crisis.
