:PROPERTIES:
:ID:       aef4597c-ecd5-473f-9da7-0db0b300a8d5
:END:
#+title: Galactic News: We Have a Winner!
#+filetags: :3302:galnet:

* Galactic News: We Have a Winner!

/09 Sep 3302/

A pilot by the name of Commander [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Falchion]] has won the Melee Masters arena competition.

In a tense final bout, Commander [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Falchion]] appeared to give up right on the cusp of victory, but it was revealed to have been a ruse designed to bring his opponent into firing range.

A reporter from Sports Zeta Weekly commented: "I had no fingernails by the end of that one. The sheer moxie of Commander [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Falchion]], to sucker in his opponent like that! Big risk, big payoff. The crowds loved it! A worthy winner."

Commander [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Falchion]] was not available for interview and appears to maintaining a cloak of anonymity, although it is known that he or she is from the [[id:2a4e7539-b87c-4ce9-8012-b2690fa3b618][Chi Orionis]] system.
