:PROPERTIES:
:ID:       36e624da-9a5b-4126-8127-fd02556075d4
:END:
#+title: Imperial Inquisition and Emperor's Grace to Hold Meeting
#+filetags: :3301:galnet:

* Imperial Inquisition and Emperor's Grace to Hold Meeting

/14 Aug 3301/

Imperial Inquisition and Emperor's Grace to Hold Meeting 
 
Mavia Kain, the High Inquisitor and leader of the Imperial Inquisition, is scheduled to pay a visit to Admiral Varrwen Mako Brennus, leader of Emperor`s Grace. The meeting will be held in the Emperor's Grace stronghold of Rishair at Lindblad Port. Both leaders will discuss a number of Imperial issues, including the assassination of Emperor Duval and the present military operations in the Pegasi sector. 

Rumours about the groups’ cooperation have been circulating since the start of the united Imperial offensive in the Pegasi sector. Both factions are presently engaged in a peacekeeping operation against the Kumo Crew, which began when [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] illegally invaded Imperial space and took Imperial citizens into slavery. Emperor`s Grace and Imperial Inquisition pilots are fighting together against this notorious crime lord, as both groups see him as a threat to galactic peace. 

Sources close to Admiral Brennus revealed that the factions share the same traditional Imperial values. A senior official noted that: "We both care about the Empire, the Imperial way of life, and Imperial citizens. We are natural allies. [[id:77cf2f14-105e-4041-af04-1213f3e7383c][The Empire]] is going through tough times - we need to support each other." 

Commander Raf von Thorn
