:PROPERTIES:
:ID:       62c15550-7082-4f30-8f13-5b43681c5bf2
:END:
#+title: Galactic News: Sirius Corporation Responds to Calls for Clarity
#+filetags: :3302:galnet:

* Galactic News: [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] Responds to Calls for Clarity

/25 Jan 3302/

Since the wreckage of the Highliner Antares was recovered several weeks ago, the families of those who lost their lives aboard the ship have been lobbying the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] for more information. Specifically, questions have been asked about where the wreckage was found, and if any human remains were recovered. The corporation, evidently aware that the public is hungry for information, has now released a statement: 

"We are aware that some sectors of the galactic community believe we have not been sufficiently transparent regarding our research into the Antares. Please be assured that any lack of clarity is in no way indicative of a desire to withhold information – it is simply a reflection of our focus on our research." 

"In light of this, we can confirm that the remains of the Antares were found in the Luyten 205-128 system, and that no organic remains were recovered. As for the cause of the explosion, we can only reiterate our earlier statement that a cascade failure in the hyperdrive's internal containment systems triggered an explosion within the drive. Although the precise cause of the explosion is not yet known, we believe any additional information will only corroborate our assessment that the destruction of the Antares was nothing more than a tragic accident." 

"We would like to take this opportunity to extend our condolences to those who lost loved ones aboard the Antares."
