:PROPERTIES:
:ID:       23579302-527d-48c8-a6cb-1da3e1984b09
:END:
#+title: Week in Review
#+filetags: :galnet:

* Week in Review

/20 May 3304/

Here are this week’s major stories. 

A member of the Council of Admirals, which commands the Alliance Defence Force, has been murdered. The League of Reparation has claimed responsibility. It has been confirmed that an ancestor of the victim, Fleet Admiral Buchanan, was a senior commander in the INRA. It has also been suggested that the League’s assassins are being aided by sympathetic individuals in positions of influence. 

Meanwhile, an increasing number of religious movements in the core systems are proclaiming that humanity is on the verge of destruction. The return of the Thargoids has led to the emergence of dozens of radical groups, and although their nature varies, the message is the same: the apocalypse is coming. Authorities have responded by restating that the Thargoid threat is being controlled. 

Scientists in Colonia are investigating the region’s potential to support larger populations in the future. Professor Alexei de la Vega, who is leading the research, published this statement: “Over the past few years the region’s population has expanded ferociously, so it has become a priority to investigate how Colonia might support even greater numbers, and what kind of infrastructure would be required. This research requires a range of specialised materials, for which we’re prepared to pay handsomely.” 

In other news, a convoy travelling through the core systems has come under attack from a pirate group, and local authorities are requesting assistance in finding survivors. Search-and-rescue teams have been despatched, but the volume of debris is significant, and independent pilots in the area have been asked to lend their support. 

Finally, a spokesperson for the Moritasgus Imperial Corporation has announced that its appeal for commodities has been enthusiastically received by the galactic community. Hundreds of pilots supported the initiative by delivering commodities to Vaucouleurs Vision, and by protecting traders in the Veroklist system. 

And those are the main stories this week.
