:PROPERTIES:
:ID:       97121f9d-ba1c-4ccb-aea6-d022e3396b29
:END:
#+title: Famous Author Missing
#+filetags: :3304:galnet:

* Famous Author Missing

/11 Nov 3304/

The family and colleagues of author [[id:103de6dd-c4ec-4687-8b3c-24f57fa309f7][Olav Redcourt]] have reported him missing. A police investigation has so far failed to determine his whereabouts. 

Redcourt recently hit the headlines when he terminated his relationship with his publisher, Bonespire Publishing, midway through a promotional tour. 

In the wake of the author’s disappearance, Bonespire released the following statement: 

“We can only assume that Mr Redcourt is trying to avoid paying his fine for contract violation, which runs to several million credits. Of course, should he agree to continue writing the bestselling Corsair King series, we would be happy to waive the damages.” 

Literary critic Kayla Shah offered an alternative explanation: 

“Obsessive readers of the Corsair King series have sent death threats to Redcourt for not delivering exactly what they wanted. Now that he’s turned his back on the series, might he have been kidnapped by a rabid fan and forced to write more novels, or even murdered as an act of revenge?”
