:PROPERTIES:
:ID:       8fa1990f-fc61-47ef-bcea-e4a0ae147162
:END:
#+title: Federal Congress Grants Emergency Surveillance Powers
#+filetags: :Federation:galnet:

* Federal Congress Grants Emergency Surveillance Powers

/30 Mar 3307/

Vice President Jerome Archer has successfully proposed a new public surveillance law designed to prevent future terrorist attacks in the Federation. 

The Domestic Counter-Terrorism Act was debated in Congress before being approved by a majority vote. It is considered to be emergency legislation that replaces all previous laws regarding monitoring civilian activity and intercepting personal communications. 

Vice President Archer, who personally drafted much of the new statute, announced: 

“This will allow the government to actively seek out any terrorist agents and sympathisers lurking within our communities. We will never again allow so many families and friends to be taken from us.” 

Shadow President [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] responded: 

“Nobody wants another ‘Nine Martyrs’, and it’s vital that security is increased across the Federation. But this is an outrageous violation of civil liberties. For this administration to grant itself access to every citizen’s private life makes it resemble a dictatorial regime.” 

VP Archer later confirmed that he is already working with the heads of security services on practical applications of the new law. As a former director of the Federal Intelligence Agency, he is expected to make rapid progress.
