:PROPERTIES:
:ID:       f7ed5182-4d22-4b66-acb0-5e7085204035
:END:
#+title: The Golconda Resurrection
#+filetags: :3308:galnet:

* The [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] Resurrection

/31 May 3308/

With the generation ship [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] being repaired by the Artificers Clan, its former population are considering resuming their journey.   

Commander [[id:f5a998c2-26d4-4318-8f34-d85846b71d92][Javi Alvarado]], a local trader who befriended the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]ns, offered this insight for Vox Galactica: 

“Following a prompt from the Artificers Clan, I transported Captain Forester and other community leaders from Forester’s Choice to the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]. They were visibly awed at the changes made to their ancient home, with modern interface panels and machinery expertly entwined with thousand-year-old technology.” 

“The newly installed frame shift drive was powered up, which brought Forester close to tears. We also visited the habitation rings, now sustained by updated environmental systems but otherwise unchanged.” 

“There were Artificers Clan members bustling back and forth. Each wore grime-stained overalls, criss-crossed with belts and bandoliers dangling with tools, and diagnostic scanners of some kind covering their eyes. They chattered to each other in a rapid dialect that was hard to follow, as they performed engineering work on whatever they could lay their hands on.” 

“The chieftain explained to Captain Forester that the clan retrofitted the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] mainly because ‘tech-love’ was their ‘life-duty’. But the clan also asked for supplies of fresh food for their dredger, which Forester agreed to provide.” 

“As we flew back to the outpost, I could tell that most of the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]ns were deeply affected. I can’t blame them – the only world many of them knew for decades has been transformed. The leaders spoke of an unexpected opportunity to resume their old way of life, and questioned whether a stationary existence honours their ancestors’ dream. I get the feeling that change is in the wind.”
