:PROPERTIES:
:ID:       b7c723e0-654f-4a62-ace5-e23398dc61fd
:END:
#+title: Far God Cult Under Federal Scrutiny
#+filetags: :galnet:

* [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Cult Under Federal Scrutiny

/20 Sep 3308/

The Order of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] is facing an official investigation and increased public maltreatment within the Federation. 

Freelance journalist Alexei Keel published a special report via Vox Galactica: 

“The Thargoid-worshipping cult has always been a controversial faith on Federal worlds. But it is currently causing a civil backlash of the sort not seen since 3304.” 

“A recent exposé by the Federal Free Press proves that naval intelligence operatives are investigating all chapters of the cult established in Federal space. Allegedly, there are suspicions that cultists may be undertaking acts of espionage to sabotage anti-xeno operations.” 

“As more details of the Battle of HIP 22460 become public knowledge, the pacifistic cultists have become an easy target for ordinary people seeking some kind of revenge against overtly pro-Thargoid ideologies. Although security forces claim to be responding to these vigilante attacks, widespread prejudice means that local police rarely act when such crimes are reported.” 

Antipathy to the religion has increased to the point where prominent figures in the Federal government are calling for it be outlawed. As Secretary of State Lana Berkovich put it: “Humanity is at war with the Thargoids. To allow an army of crazed alien sympathisers within our society is to invite disaster.” 

All of this has driven thousands of worshippers to abandon their hive-chapels and join the more radical True Chapters sect. Welcoming the new converts, the First Apostle proclaimed: “We must defend our faith and ourselves, so we may witness the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]]’s manifestation with our own eyes.” 

The exotheologian Dr [[id:2bf69df4-bf62-4877-87eb-5158254f5fcb][Alfred Ulyanov]] has remarked on this as “a fundamental shift from the fatalism of their conventional beliefs”. Keel raises the question in his report: what happens if [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cultists stop tolerating these hostile acts and start fighting for survival?
