:PROPERTIES:
:ID:       35e7224e-6216-4cbd-9f51-26c984d216b1
:END:
#+title: Torval Orbital Established
#+filetags: :galnet:

* Torval Orbital Established

/03 Sep 3307/

*Pilots Federation ALERT* 

A new starport has become operational in the LTT 198 system, following Senator Zemina Torval’s mining initiative. 

Torval Orbital will serve as the administrative headquarters for Torval-Mastopolos Mining. The company successfully competed against Wreaken Corporation to establish a presence within LTT 198. 

Marlon Royce, business analyst for Vox Galactica, observed: 

“Mastopolos Mining should be boasting about the positive start for its new subsidiary. Instead, its reaction has only confirmed the widening rift between the Mastopolos family and their corporation’s majority shareholder, Zemina Torval.” 

“CEO [[id:7344d4cd-7b21-4aa2-895b-98a4acefe96f][Gabriella Mastopolos]] officially distanced herself from the offshoot company, claiming it ‘hijacked our name with the intention of luring our clients’. And speaking to Imperial media, both Adrian and Elena Mastopolos criticised Constantia Torval’s suitability to act as operations director.” 

“Speculation persists as to why the families have become estranged. For now, Zemina Torval seems to be focusing solely on her direct descendants. With her youngest daughter Petra Torval becoming a fellow senator, and grandson Titus Torval promoted to a senior role in Imperial Intelligence, the future seems bright for the Torval dynasty.”
