:PROPERTIES:
:ID:       5c5c5184-c7b8-417a-80f7-2ef13acdb7e0
:END:
#+title: Imperial Commanders Closing in on Secret Smuggling
#+filetags: :3301:galnet:

* Imperial Commanders Closing in on Secret Smuggling

/03 Aug 3301/

Imperial Commanders Closing in on Secret Smuggling 
 
Rumour has it that several Imperial Commanders are closing in on a well-known smuggling route between the Torval and Delaine owned systems. Imperial slaves are illegal in Delaine space but sell for a small fortune on the black market. The Empire hates this because it takes what they consider indentured servants and citizens from a life of Imperial service to a life of forced labour. Commanders who use the secretive route have plenty to say about the prospect of impending Imperial intervention, with Commander Infinity+1 saying: 

"Ain't it funny how we're s’posed to be the bad guys, but the Empire has so many slaves they're practically giving them away!" 

When pressed to reveal the systems he runs between, Infinity stated, "I'm not telling you about my favorite route, but let me just say thank you to the honorable Zemina Torval" 

Profits allegedly run towards 4,000 credits per slave. Only time will tell if the Imperials can break the back of this illegal trade route and round up the smuggling ring, but one thing is certain – until the Empire fixes the problem of Archon Delaine, there will be other runs to take its place.
