:PROPERTIES:
:ID:       02cee327-9747-4713-acdf-a51efab7e748
:END:
#+title: Community Goal: The Rise to Power Concludes
#+filetags: :galnet:

* Community Goal: The Rise to Power Concludes

/14 Jul 3302/

The third and final stage of the Rise to Power campaign is about to begin. 

For this heat, pilots have been asked to salvage precious gems and deliver them to Laura Elizabeth in the Meropis system. But the event organisers have chosen to complicate matters by refusing to reveal the precise whereabouts of the salvage site. Pilots participating in the event have been given just one clue to its location - the following signal: 

353133313639313835 3432313232313132 31393235313932303531333139 A6B1D4H1I4K1L1M2N1O2R1U1V1Y1Z1 3132313533313132 373131323134353230 32353133313531343139 

The group that manages to accumulate the most precious gems will be declared the winner of the final Rise to Power event. At the close of the event, the results of each heat will be reviewed. The faction that has garnered the most support over the course of the campaign will join the ranks of the galaxy's major power players. 

The event begins on the 14th of July 3302 and will run for one week.
