:PROPERTIES:
:ID:       428ecf3c-89be-440e-b412-9b99ebcb76a2
:END:
#+title: Rackham Fundraiser Secures Political Backing
#+filetags: :Federation:galnet:

* Rackham Fundraiser Secures Political Backing

/01 May 3309/

Independent presidential candidate [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] held a gala ball for some of the Federation’s wealthy and influential elite. 

The Federal Times published a report from political correspondent [[id:e660f840-caed-45ef-985e-f75170cf9ca8][Sofia Trevino]]: 

“The extravagant gathering at Fort Rackham (formerly Fort Falkenrath) on Taylor Colony felt more like a party than a fundraiser, but its ambitions were clear. Campaign finance laws forbid [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] from using his own wealth to pay for his presidential bid, and so connections are being forged to entice donations and other types of support.” 

“Mr Rackham’s campaign manager – and the originator of his ‘Just Like Me’ slogan – was revealed to be celebrity PR consultant [[id:464bcd90-c51a-4650-b5bb-83011a9dc5de][Anya Blackriver]]. She organised many famous attendees including media barons Elias Metaxas and Neive McFarlane, the youthful but popular [[id:a12cdcbc-fa10-474e-8654-d3d7da17a307][ICE-caster]] [[id:f3e0128c-f8fd-4b90-a2c0-0ae5a5e487d0][Sura Oyekan]], and flamboyant business magnate ‘Sir’ Randolph Plaskett of the Knights of Enterprise.” 

“The biggest surprise was the announcement that Congressman Harlan Turk, the highly respected representative for the Duamta system, has resigned from the Republican Party to serve as Mr Rackham’s running mate. Four independent congressmen also declared that they are joining his campaign, giving the entrepreneur some genuine political clout.” 

The newsfeed Sol Today published a related editorial: 

“President Hudson has served with honour, and deserves our respect for keeping citizens safe in recent years. But perhaps it’s time for some fresh blood at the Federation’s heart? Could [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]]’s infallible business instincts be what’s needed to boost our economy to new heights of prosperity?”
