:PROPERTIES:
:ID:       f1907a63-b1fb-4fc7-ba9b-1b051ebfd31f
:END:
#+title: Community Goal: Alliance Appeals for Help
#+filetags: :CommunityGoal:3303:galnet:

* Community Goal: Alliance Appeals for Help

/26 Jan 3303/

The Alliance Council of Admirals has announced that an Alliance convoy has been attacked in the Fedmich system. 

According to a statement, the convoy was transporting personnel and military equipment to a secure Alliance outpost. It is understood the attack was executed by criminals operating in Fedmich. 

Most personnel were safely evacuated, but many of the ships comprising the convoy had to be abandoned. Furthermore, a number of occupied escape pods remain among the wreckage. 

A spokesperson for the Council of Admirals released a statement: 

"It is imperative that all personnel and material carried by this convoy be recovered as soon as possible." 

"To that end, we have authorised Fedmich Electronics Partners to coordinate a rescue operation, and will gladly reward those who deliver occupied escape pods and wreckage components to Roberts Port in the Fedmich system. Combat pilots are also needed to neutralise agitators operating in Fedmich and thus ensure the safety of those recovering material from the convoy." 

The operation begins on the 26th of January 3303 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
