:PROPERTIES:
:ID:       2f14f66d-2c1a-4840-8fb0-7fa1364e911f
:END:
#+title: Kappa Fornacis Calls Federal Freedom Into Question
#+filetags: :galnet:

* Kappa Fornacis Calls Federal Freedom Into Question

/18 Jun 3301/

Kappa Fornacis Calls Federal Freedom Into Question 
 
It has been some time since the Kappa Fornacis Farmers Union has dared to draw attention to itself beyond its home system. However, following a reported trade deal with one of Senator Zemina Torval’s corporations, the farmers of Panem look a good deal more confident. 

Georgio Algeria, spokesman for the Kappa Fornacis Farmers Union, had this to say on the subject: 

“Even with a new President, they won’t win. What we have is great, and you can’t keep greatness down. That Hudson guy is too uptight. He needs to chill, and I’ve got just the thing for him!” 

“Everything in moderation, my friends. Sims are cool. Hudson’s kids don’t need to win no prizes for proving who’s the best at killin’. They need to chill, to care about each other, get in touch with their roots.” 

“The Empire’s cool with us. Slavery’s not cool, but at least they’re doing something about it. These Fed kids signing up to the Navy. Bombing our children. How is that not slavery? Which is better?”
