:PROPERTIES:
:ID:       22ee3465-fdaf-4d20-9b8b-82083c54dbae
:END:
#+title: Galactic News: [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] Receives Promotion
#+filetags: :3302:galnet:

* Galactic News: [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] Receives Promotion

/22 Feb 3302/

Emperor [[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] has announced that Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] is to be promoted to Admiral of the Fleet, following his triumph over the insurgent organisation Emperor's Dawn. In a statement, the Emperor praised Patreus's recent military success: 

"Denton Patreus exhibited remarkable resolve in the campaign against Emperor's Dawn, and demonstrated his ability to act with conviction in the face of an often unpredictable enemy. I can think of no more appropriate person to assume command of the Imperial Navy. It is with great pride that I confer upon him the title of Admiral of the Fleet." 

The senator is expected to assume his new role next week following a formal inauguration ceremony on Capitol.
