:PROPERTIES:
:ID:       cdbc4d86-8865-4e67-b8d5-bb75d4620eb4
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/e2b1210f-8021-4438-a1c0-a1514baacd00?resourceVersion=id%3A4874
:END:
#+title: Countdown to Alliance Election Begins
#+filetags: :Thargoid:galnet:

* Countdown to Alliance Election Begins

/04 Jan 3307/

The Alliance has entered a period of political campaigning prior to the election of a new prime minister. 

The appointment of a head of government takes place every six years, with the forthcoming vote scheduled for the 25th of February 3307. 

Unlike the Federation, there are no political parties in the Alliance. The Assembly is comprised of councillors who each represent the ruling faction of a member system. Electoral votes will be cast by these individuals rather than the public, but councillors tend to abide by the majority views of their constituencies. 

[[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] is the current prime minister, having been in office since 3301, and is campaigning for re-election. If successful, he will be the first to serve more than one term.  

There are several rivals challenging Mahon, but the greatest support is for Councillor [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]] of [[id:0b991a8e-234a-4888-8c0a-b3c64498f217][Tionisla]]. She has become a rallying point for discontent among the Assembly, speaking out against the Alliance’s increasing dependence upon corporations and other superpowers. 

At an emergency debate regarding the current wave of Thargoid attacks, Councillor Kaine stated: 

“Can we be surprised that the Thargoid race is launching fresh assaults against us, when we brazenly invade their territories? Our obsession with [[id:da2f167d-0157-4deb-afb2-98bf6518cf01][meta-alloys]] has turned us into the aggressor! This is not the same Alliance that I pledged to serve. It’s time for a new direction.”
