:PROPERTIES:
:ID:       3fff4e52-a910-4d23-b688-410f4108194d
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/6647b38b-800f-43db-81fb-507c5f91de77?resourceVersion=id%3A4927
:END:
#+title: Jupiter Rochester Goes Rogue from Core Dynamics
#+filetags: :galnet:

* [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] Goes Rogue from Core Dynamics

/09 Feb 3307/

Several departments loyal to the Core Dynamics CEO have seceded to form an independent corporate republic called Jupiter Division. 

During the recent trial of Fleet Admiral Vincent, [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] was named as the paymaster behind the sabotage of Starship One. This hastened long-term plans to abscond from Core Dynamics along with many ships and personnel.  

In the permit-locked HIP 54530 system, the HIP 54530 Gold Universal Group has been renamed as Jupiter Division. It is assumed to have long been infiltrated by Rochester’s loyalists. 

Using the new self-appointed title of Supreme Executive Rochester, he broadcast this statement across all Federal media channels: 

“For many years, I helped Core Dynamics become one of the galaxy’s strongest companies, but petty laws and bureaucracy restricted me at every turn. I have always felt that people should not be ruled by politicians, but by those holding true economic power – the corporations.” 

“It will be a long time before I can act on my commercial plans, but I will prove that corporate rule is the most beneficial system of governance for the Federation.” 

Jupiter Rochester is the eldest son of Shadow Vice President Isolde Rochester, and a key member of the influential Rochester family. As yet there have been no public statements from his mother or siblings.
