:PROPERTIES:
:ID:       49d56721-ae77-4e2d-ad23-08193fefb097
:END:
#+title: ACT Continues to Hunt [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] Terrorists
#+filetags: :galnet:

* ACT Continues to Hunt [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] Terrorists

/14 Jun 3307/

The Affiliated Counter-Terrorism unit has published an update on its investigation into the Neo-Marlinist Liberation Army. 

Senior Agent Tanya Ramirez, one of ACT’s joint leaders, gave a statement to the media: 

“ACT is currently pursuing multiple lines of enquiry, which must remain classified for reasons of security. Our agents are gathering evidence from sites across the Alliance, Empire and Federation.” 

“As yet we cannot report any significant breakthroughs. [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] activists appear to use a dark-comms network that defies detection. They also compartmentalise their operations, so individual cells have little knowledge of each other.” 

“In recent months, [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] incidents have been restricted to minor strikes against Imperial authorities, which were dealt with by local police forces. There has been no activity by Theta Group, the hardcore extremists responsible for the ‘Nine Martyrs’ starport bombings.” 

“The collapse of the Neo-Marlinist Order of Mudhrid may have deprived the [[id:dbfbb5eb-82a2-43c8-afb9-252b21b8464f][NMLA]] of their logistical capability to deliver large-scale attacks. But it remains possible that a new wave of terrorist atrocities is being planned.” 

ACT later confirmed that it has recruited additional personnel from Alliance Interpol, the Federal Intelligence Agency, the Imperial Internal Security Service, the Marlinist Constabulary, Nova Imperium’s Praetorian Guard and the Wallglass Investigations Agency.
