:PROPERTIES:
:ID:       e7328b85-e189-4709-b21b-1db71c696719
:END:
#+title: Utopia Shares Update on [[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis Failsafe]]
#+filetags: :galnet:

* Utopia Shares Update on [[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis Failsafe]]

/11 Dec 3309/

Simguru [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] has discussed Utopia’s analysis of the designs
for a Guardian-based device allegedly constructed by [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]].

The schematics for the [[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis Failsafe]] were unearthed by [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]],
who believed that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] had developed a way to digitise and
relocate his mind upon physical death. Following concerns that Utopia
was involved, Aegis shared these designs with the commune to confirm
that there was no connection with their [[id:83b3ed4c-f0b1-4311-a4df-34bdfa742126][Sim-Archive]] technology.

[[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] recently sent a message to Aegis, which has been made
public with Utopia’s permission:

“After studying the designs intensively, our neurosmiths have gained
some insights into the [[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis Failsafe]]. [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s unique knowledge
of Guardian energy particles and their applications exceeds even our
understanding. But we have formulated a theory about what happened
when the ‘[[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis protocol]]’ was activated aboard the Bright Sentinel
megaship, shortly before its destruction in [[id:55088d83-4221-44fa-a9d5-6ebb0866c722][HIP 22460]].”

“I would like to discuss this matter in person with [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]. Her
unique experience with [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s methods and independent research
into his character may help me resolve some remaining questions.”

[[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]]’s science correspondent Leon Banerjee reported:

“The [[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis Failsafe]] question is generally viewed with scepticism, if
not outright mockery, among leading exoneurologists. Nobody disputes
[[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s expertise at weaponising Guardian artefacts, but few
believe that a living mind could be converted into electromagnetic
pulses, even using alien technology.”

“[[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]] is also dismissive, not just about the science but
the very idea that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] may have survived. [[id:78d58f4a-e080-4548-a2f0-9506b7b73674][Torben Rademaker]] has
referred to it as ‘inappropriate and disrespectful to the memory of
our founder [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Caleb Wycherley]].’ Nevertheless, Aegis has agreed to
transport [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]] to meet [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]], if she accepts his
invitation.”
