:PROPERTIES:
:ID:       166251a5-f954-4273-9e99-08cccb70525d
:END:
#+title: Galactic News: Galactic Leaders Trade Blows
#+filetags: :Empire:Federation:Alliance:3303:galnet:

* Galactic News: Galactic Leaders Trade Blows

/03 Feb 3303/

The leaders of the galaxy's three superpowers have released further statements concerning reports of mysterious spacecraft. 

Emperor Arissa-Lavigny Duval, responding to the recent statement from Federal President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]], said: 

"Once again, President Hudson has shown himself to be little more than a warmonger. I say again: we must not jump to conclusions. We have not yet acquired any reliable information about these vessels. We must be patient." 

No sooner had the Emperor made her statement than President Hudson responded. Speaking at a rally on Mars, he said: 

"Some believe that aliens have infiltrated the Empire. An improbable claim? Maybe. But then again, maybe not. After all, we are almost certainly dealing with an extremely advanced species. Who knows what they are capable of?" 

Alliance Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] did not release a statement, but former Federal president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]], who has become one of Mahon's most trusted advisors, made an announcement in which she seemed to address the ongoing Federal-Imperial conflict as much as the mysterious ships: 

"Understanding. Cooperation. These must be our watchwords. We have to go beyond party politics and petty point scoring. Only by working together can we hope to avoid bloodshed."
