:PROPERTIES:
:ID:       4903c1de-eb22-4948-a4c3-af34f8a3347a
:END:
#+title: Titan Cocijo Devastates Sol System
#+filetags: :Federation:Thargoid:3310:galnet:
* Titan Cocijo Devastates Sol System

/05 Dec 3310/

The Thargoid [[id:ba5ecc8d-cf87-4cf8-9d33-beb5d214e323][Titan]] [[id:fbe81b20-15a4-466e-85a6-50816c6e2a99][Cocijo]] has arrived in the [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]] system, positioning
itself in orbit around [[id:5b0f485f-4793-468d-a1a1-483606f44e0e][Earth]].

[[id:fbe81b20-15a4-466e-85a6-50816c6e2a99][Cocijo]]’s arrival unleashed a devastating regional assault by the
remaining Thargoid invasion fleet. In [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]], only [[id:871145fd-18d8-4711-9b61-db685d5a72c0][Mars High]], [[id:1b20ef5c-0d66-4378-9d42-518890589fe3][Galileo]] and
[[id:274cfe98-c748-4d9e-ad84-08dd06b1d540][Haberlandt Survey]] remain functional, albeit damaged, with all other
ports knocked offline by Thargoid attack. [[id:3146c49e-4aa8-4061-9ab2-1d9da2b0bff5][Farragut]] battlecruisers [[id:71357d75-9471-4084-a9fc-a23cfa3436df][FNS
Nero]] and [[id:6018a6e9-5775-4816-ac1e-341797de7b5d][FNS Erebus]] have been destroyed, while [[id:7dd6c56b-c257-47bc-8d2a-d195563e103d][FNS Victory]] and [[id:80da1601-0ac8-444c-9c11-8e62e1db9ad3][FNS
Trander]] are marshaling system defence efforts. Thousands of [[id:56ad8af3-baa1-4d0a-acd8-750400d280f4][AX]] fleet
vessels have been lost to the initial conflict.

16 other systems were assaulted near [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]], triggering a massive refugee
crisis as billions of civilians remain stranded in the region. [[id:182c575c-e759-4f7e-ad38-cf8424926490][Rescue
megaships]] are en route to support evacuation efforts.

[[id:85fdc9c8-500b-4e91-bc8b-70bcb3c05b0f][Starship One]] has successfully arrived in [[id:ed325fe8-22a1-4d07-9af9-5a9f8f056377][Eta Cassiopeiae]], with
[[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][President Winters]] and members of her cabinet on board.

[[id:7bca1ccd-649e-438a-ae56-fb8ca34e6440][Aden Tanner]], military advisor for [[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]], provided the following statement: 

“This is it, folks. The Thargoids have made their final attempt at
checkmate. The birthplace of humanity and the centre of the
Federation: [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]. [[id:ba5ecc8d-cf87-4cf8-9d33-beb5d214e323][Titan]] [[id:fbe81b20-15a4-466e-85a6-50816c6e2a99][Cocijo]] has chosen to bring the fight to the
core of human space.”

“This is a fight like nothing we’ve ever seen. The Thargoids are
hitting us aggressively and in huge numbers, with a Titan directly
leading the attack. I don’t know what the future holds, but I do know
that we’ve got a war to win. Civilians need our help, and Federal AX
forces need our support. If you’ve got a ship and you’re willing to
get involved, do so now. Humanity is going to remember this fight
forever.”
