:PROPERTIES:
:ID:       f15e4c31-8cde-4c82-aa4a-f9796ae04afc
:END:
#+title: [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]-Utopia Link Raises Concerns
#+filetags: :galnet:

* [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]-Utopia Link Raises Concerns

/10 Apr 3309/

Similarities between the Nemesis Failsafe and Utopia’s Sim-Archive have led to questions being asked about a possible connection. 

Independent journalist Flint ‘Firemaker’ Lafosse reported on Seo Jin-ae’s recent discoveries: 

“We all knew that [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] had a messiah complex, so it’s no surprise that he planned to keep his colossal ego alive after his ancient body died. We also know that [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] has been digitising his followers’ brains for years.” 

“My question is: did [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]] modify Antal’s system for his own private use, rather than reverse-engineer Guardian technology? Or maybe Azimuth and Utopia were secretly working together all this time, and the Sim-Archive has always been Guardian-based? It would explain how Utopia is able to maintain funding for its little tech-bohemian commune.” 

This theory was critiqued by [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]’s technology correspondent [[id:81ba02cb-f405-4079-9207-63afc71263df][Harlow Nassry]]: 

“It is a fact that most of Utopia’s scientific development remains opaque. But the few inventions that have been examined – such as the nanomedicines acquired by Vitadyne Labs – contain no molecular markers of Guardian origin. The Sim-Archive’s memory-recording techniques are based on exoneurological research conducted over hundreds of years.” 

Dr Maximo Fonseca, the Alliance’s scientific liaison to Aegis, gave a statement to the media: 

“Since successful applications in this field are so rare, we cannot ignore the potential relation between the Nemesis Failsafe designs and the Sim-Archive. I have made contact with Simguru [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] and explained the situation. He kindly invited me and my staff to visit Utopia and discuss the matter. Our findings will determine whether a formal investigation into [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s current status is warranted.”
