:PROPERTIES:
:ID:       195a5a32-863a-4750-bab8-0e8d1f9afb82
:END:
#+title: Week in Review 17 Nov 3304
#+filetags: :Empire:3304:galnet:

* Week in Review

/17 Nov 3304/

Here are this week’s major stories. 

A [[id:ac5f768f-d3e5-428e-b416-882e4f30b5ca][leaked]] [[id:01980efc-1b06-4f55-bf18-fa6c7e56f1eb][Imperial Internal Security Service]] report on [[id:64e89e89-f7fe-4f90-bc29-1cd90497e1f1][Nova Imperium]]
has revealed that the group’s leader is one [[id:f6be5b58-fd8d-4233-8053-7ade4ca35aee][Duke Kaeso Mordanticus]], a
former naval admiral from a long line of decorated veterans. The
report reveals that Mordanticus still has contacts and influence in
the [[id:e9becd28-9644-42aa-afc8-7bba3ce10076][Imperial Navy]], and that Nova Imperium’s ships are mostly run by
ex-naval crews.

Meanwhile, an [[id:04ba4637-336a-46c7-bab0-3ac12f16b2f9][Achilles Corporation]] engineer who helped design the
[[id:0c43c44c-33fe-4b99-a5e0-2f2be9dc67b0][robots]] at the heart of the [[id:6af6a805-9a23-4ba8-9676-b6bba2278f2a][spy robot scandal]] has given evidence to
former [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][FSS]] inspector [[id:67e55dd5-7840-4133-9111-566a0008b121][Ramesh Thorne]]. The engineer claims she was
[[id:f1778ba6-dab1-442b-88ff-1dfe06ee2616][blackmailed]] by [[id:74cae77e-fab1-4a22-9c31-daaa15d8fd0e][Kingsley Cordova]], owner of the Mars Tribune, into
installing surveillance programs on [[id:0b7fcbab-6e37-401a-8d52-4d2dee8e5c1e][PA912]] administration robots. All
the affected robots have now been made safe.

In other news, the Independent HIP 29241 Green Party[[id:706c70bc-7bb0-4b7a-ad90-04112bffaf73][Independent HIP
29241 Green Party]] operation to recover escape pods in the [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]] system
has reached a successful conclusion. The captured mercenaries were
interrogated by the [[id:f36afa96-d3df-40d8-bf67-13cbe388e889][Meene Defence Force]], leading to the realisation
that several of them were junior officers in [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corp]]’s private
fleet. The engineer [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]], who operates from [[id:1129599f-efa9-4186-969e-eb09ae9d3c2d][Phoenix Base]] in the
Meene system, has claimed that Sirius is trying to obtain his research
by force. The Sirius Corporation has refuted any allegations of
[[id:d686af2f-d947-4f3b-ba19-d57c93d29d99][criminal]] activity.

Finally, [[id:8aecd3c5-ac33-42fe-8c12-2e6062c32da3][Olelbis Holdings]], an organisation based in the Olelbis
system, has announced an elaborate social function at Polyakov
Orbital, the faction’s base of operations. In support of this event,
Olelbis Holdings has placed an open order for various rare
commodities, and has pledged to reward pilots who deliver these
commodities to [[id:25ecfc87-f6b2-428e-b23e-9490dcd37d26][Polyakov Orbital]] in the [[id:b604827a-7183-4f81-8623-191fc2173db1][Olelbis]] system.

Popular author [[id:103de6dd-c4ec-4687-8b3c-24f57fa309f7][Olav Redcourt]], who was recently reported missing, has
been [[id:91eb4627-e391-44d1-8a89-f4151a8aa3be][found]] alive and well at a writers’ retreat at a remote
outpost. The writer is apparently hard at work on his new book, a
science fiction novel.

And those are the main stories this week.
