:PROPERTIES:
:ID:       b1c489f9-5f09-44f0-a8db-684c09a97122
:END:
#+title: Criminals Crushed by Federal Campaign
#+filetags: :3308:Federation:galnet:

* Criminals Crushed by Federal Campaign

/21 Jul 3308/

*Pilots’ Federation ALERT* 

A Federal operation in the Andowatye system has finally brought down the [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] crime syndicate. 

Executive Agent Faisal Sacranie of the Federal Intelligence Agency announced the successful conclusion: 

“I am pleased to confirm that FIA agents were able to capture Oberon Church, the so-called ‘man of smoke’, as well as his surviving lieutenants. With its kingpin’s arrest and most remaining forces destroyed, the [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]] organisation no longer exists as a functional crime organisation.” 

“On behalf of the FIA, I am grateful to all pilots who helped eliminate these felons. The United Andowatye Democrats  will redeem bounty vouchers for all contributors at Bosch Station in the Andowatye system.” 

Vice President Jerome Archer gave a statement to [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]: 

“One of the Federation’s most notorious organised crime networks has been eradicated, largely due to vital information obtained by the Proactive Detection Bureau. Its ability to unearth enemies of the Federation and bring them to justice remains unparalleled.” 

The Proactive Detection Bureau was created when Vice President Archer successfully passed public surveillance legislation in 3307. Political commentators have theorised that Archer’s presidential campaign next year will stress the PDB’s role in high-profile victories such as the defeat of Jupiter’s Wrath and [[id:792ffce8-85dc-4147-8ea3-8e5feb26ba94][Red Family]].
