:PROPERTIES:
:ID:       0305be17-dffa-4a7a-88c4-b5e105335b82
:END:
#+title: Onionhead’s Medical Benefits Verified
#+filetags: :galnet:

* Onionhead’s Medical Benefits Verified

/24 Aug 3307/

The Interstellar Health Organisation has validated the Kumo Crew’s claim that onionhead gamma strain, also known as ‘helix’, has medicinal properties. 

Dr Nisha Devi, one of the IHO’s senior researchers, told the media: 

“We have analysed user data in the independent systems where onionhead gamma strain is on sale. Unexpectedly, the initial marketing claims that ‘helix’ can be used for medicinal purposes have been authenticated.” 

“A significant percentage of customers are believed to be using the drug for healthcare reasons rather than recreational use. Reports show that it is a successful treatment for many psychological disorders, bringing faster results than conventional neuroleptics. It may also provide effective symptomatic relief for patients with musculoskeletal conditions.” 

“Several research facilities are now running clinical trials on the viability of using onionhead gamma strain in medical practice. The IHO is monitoring these studies and will publish the results.” 

Vandermeer Corporation, the largest pharmaceutical company in the Federation, published a statement from its head of marketing Ronan Roscoe: 

“These conclusions are biased and informed by inaccurate data. We maintain that all forms of onionhead are dangerous narcotics with long-term detriments to health. Vandermeer’s antipsychotic treatments are effective without the side effects of mild psychedelic experiences.”
