:PROPERTIES:
:ID:       178bec35-43da-477d-ac6f-7e3dcfa765dd
:END:
#+title: The People’s Princess Speaks
#+filetags: :3301:galnet:

* The People’s Princess Speaks

/11 Sep 3301/

The People’s Princess Speaks 
 
At a public charity event in which several dozen slaves were granted their freedom, Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] took the opportunity to speak about the succession. 

“It seems peculiar that as the closest living relative of our beloved Emperor, I am not involved in the process of selecting his successor. It is even stranger that there is a process at all - after all, I am the natural heir.” 

Her attempt to gloss over the legality of her claim has sparked angry rebuttals from legal experts and the camps of the other likely candidates. When we spoke to people on the street, however, we encountered almost universal support for the Princess. One Capitol resident told us: 

“I’m all for tradition, but we have to move with the times. Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] understands what we need to do, and has the youthful vigour to make that happen.”
