:PROPERTIES:
:ID:       022a38cb-f333-4473-9432-db79d5c831a9
:END:
#+title: Author Abandons Interstellar Book Tour
#+filetags: :galnet:

* Author Abandons Interstellar Book Tour

/02 Aug 3304/

Celebrated author Olav Redcourt has abandoned the promotional tour for his latest novel, halfway through a two-month circuit of fifty systems. 

Reporters managed to catch Mr Redcourt as he was storming off the passenger liner where he has spent the last four weeks. He told them: 

“I’m sick of churning out historical-romance garbage, especially now that readers can change the damn story to suit themselves! I’m going to write the book I’ve always wanted to write – a science-fiction saga set in the future.” 

A statement was released by Bonespire Publishing: 

“Unfortunately this incident constitutes a breach of contract, as Mr Redcourt has only produced fourteen Corsair King novels, rather than the twenty-five we agreed. We hope we can convince him to resume the tour and continue with the series.” 

Margaux Hist, the author’s agent, commented: 

“Olav’s a true artist, so I’m sure fans will understand that he wants a little creative freedom. I can’t tell you anything about the new title yet, but science-fiction is a niche genre with a tiny audience, so I hope it sells well enough to pay Olav’s legal bills.”
