:PROPERTIES:
:ID:       34b5696a-2d23-4aa2-b14b-791d84a330fb
:END:
#+title: Distant Worlds Initiative
#+filetags: :3305:galnet:

* Distant Worlds Initiative

/17 Jan 3305/

The Omega Mining Corporation has requested deliveries of raw materials for a new Orbis starport, to be built in the heart of the galaxy.

The construction of the starport constitutes part of the ambitious [[id:f176c68d-cc7a-4db2-8305-81f6771c7e9f][Distant Worlds II]] expedition. Project leader [[id:0250dc51-7007-47d9-92e3-db41de666cbc][Erimus Kamzel]] told the media:

“The [[id:dbb9956e-5ae2-4c27-94f7-670f0a4719f9][Distant Worlds]] fleet is privileged to be at the forefront of this ambitious industrial and scientific initiative – humanity’s first starport in the Galactic Centre region.”

Independent miners are invited to deliver shipments of Indite, Gallite, Praseodymium and Cobalt to [[id:c9a8428d-c6ed-4493-859f-0654c5784a5c][Omega Mining Operation]] in the Omega Sector VE-Q b5-15 system.

In order to protect traders, the Omega Mining Corporation has also placed kill orders on all ships on its wanted list.

The initiative begins on the 17th of January 3305 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
