:PROPERTIES:
:ID:       db4aeb81-9466-4777-8c66-4cdffb3e991f
:END:
#+title: ‘Imperial Assassin’ Stokes Superpower Tensions
#+filetags: :galnet:

* ‘Imperial Assassin’ Stokes Superpower Tensions

/04 Apr 3309/

Federal mining corporation Caine-Massey has accused Senator [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] of assassinating its CEO Johann Fleischer. 

An update from the Federal Intelligence Agency prompted a remarkable declaration from Philippa Barlow-Lyons, the company’s acting CEO: 

“Thanks to the FIA’s assembled security footage, we now know that the man who murdered Johann Fleischer departed from Olympus Village Spaceport using a false Federal ID. He then transferred to the Tavgi system under another alias, claiming to be a prospector for Torval Mining Ltd. And so, the trail leads directly to the culprit.” 

“It is very clear that [[id:d8e3667c-3ba1-43aa-bc90-dac719c6d5e7][Zemina Torval]] ordered Johann’s death as an act of revenge, after he defeated her efforts in January 3308 to obtain one of Caine-Massey’s most lucrative mining contracts. Analysis of the hitman’s weapon and other equipment matches those typically used by Imperial Intelligence. And who is a senior officer in that ruthless spy network? Zemina’s own grandson, Titus Torval.” 

Senator Torval has not acknowledged or responded to the accusation. A formal statement was delivered directly to Congress by the Imperial Senate: 

“We categorically reject the suggestion that any members of this august body, or of Imperial Intelligence, are connected to these events. [[id:77cf2f14-105e-4041-af04-1213f3e7383c][The Empire]] no longer has any political or commercial involvement with the Federation, and remains focused on its extensive anti-xeno operations.” 

President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] publicly assured Caine-Massey, which is known to be a long-standing corporate donor to the Republican Party, that further resources will be directed to the investigation. He added:  

“This is a timely reminder that all citizens should be vigilant against the enemy within. If we discover that Imperial assassins and sleeper agents are responsible for this heinous crime, [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] will be expected to act in a manner we find satisfactory.”
