:PROPERTIES:
:ID:       eb7eb8a6-01d2-4918-b542-eb9e092f1003
:END:
#+title: Thargoid Research Project Phase Two Begins
#+filetags: :Thargoid:galnet:

* Thargoid Research Project Phase Two Begins

/09 Jun 3308/

*Pilots’ Federation ALERT* 

Professor Ishmael Palin has requested deliveries of Thargoid artefacts to the Arque system for scientific study. 

The first phase of the project took place last month and focused on meta-alloys. In a public announcement, Professor Palin outlined the second phase: 

“My ongoing analysis of the Thargoids’ biomechanical technology has reached a point where fresh material is needed. Specifically, I require large supplies of Thargoid probes, resin and sensors.” 

“I appreciate that there are risks involved in transporting such dangerous alien artefacts. Hopefully, the corrosion resistant cargo racks that were provided following this project’s initial phase will prove useful.” 

“As well as payment in credits, I am pleased to offer Grade 5 engineered Heavy Duty Hull Reinforcement Packages as an additional reward.” 

Pilots are asked to deliver Thargoid probes, Thargoid resin and Thargoid sensors to Baird Gateway on the planet Arque 4 E.
