:PROPERTIES:
:ID:       ce5eac07-e082-4fb4-a5ec-e46bd8413c1c
:END:
#+title: Restoring Sanity to Anarchy in Banki and BD+03 2338
#+filetags: :3301:galnet:

* Restoring Sanity to Anarchy in Banki and BD+03 2338

/13 Feb 3301/

As the Federal Navy begins to move into position around Banki and BD+03 2338, independent Commanders from all corners of the galaxy have started gathering at Antonio De Andrade Vista in Banki and Matteucci Terminal in Khasiri in preparation for the final set of engagements against the Federal rebels.   

The Federal Navy has issued a warning calling for all civilians to evacuate the areas around Banki and BD+03 2338 immediately. The official policy being that any unidentified ships caught in the coming conflict will be treated as enemy combatants, meaning they will most likely be destroyed on sight. 

All loyal members of the Federation are requested to report to either Antonio De Andrade Vista in Banki or Matteucci Terminal in Khasiri to receive orders as to how they can best lend their support to the Federal Navy. Non-combat roles are available for conscientious objectors.
