:PROPERTIES:
:ID:       053c7d4b-75b5-437b-93f9-2a6006b9c3b0
:END:
#+title: Official Period of Mourning Begins
#+filetags: :3301:Empire:Federation:galnet:

* Official Period of Mourning Begins

/06 Aug 3301/

Official Period of Mourning Begins 
 
Chancellor [[id:e9679720-e0c1-449e-86a6-a5b3de3613f5][Anders Blaine]] held a press conference in front of the entrance to the Hall of Martyrs and declared the beginning of the official period of mourning for Emperor Hengist Duval: 

“It is my solemn duty to officially mark the first day of the four-week period of mourning for our beloved Emperor. As is customary, the body of the Emperor will be placed in the vestibule of the Hall of Martyrs for public viewing and the paying of respect.” 

The Chancellor refused to answer questions from the assembled reporters concerning the investigation into the assassination. When asked about the succession, he replied that the matter will be handled in the Senate once the funeral has taken place. 

Following tradition, the Chancellor and invited dignitaries wore the black sash of mourning. These will be worn throughout the mourning period and then burned during the internment ceremony. 

The Hall of Martyrs was constructed over 600 years ago following the victory against the Federation in the first conflict between the two superpowers. It is open to the public only during the mourning period of those who are to be entombed there. The vast and exquisitely crafted hall beneath the Imperial Palace contains 16,032 obsidian pillars, and only the most honoured members of Imperial society are laid to rest there.
