:PROPERTIES:
:ID:       e347e998-5fcf-4b6b-9740-e7c1a74616b1
:END:
#+title: Theft Ruins New Year Celebration
#+filetags: :galnet:

* Theft Ruins New Year Celebration

/01 Jan 3305/

The theft of a spectacular work of art has soured New Year festivities for thousands of Federal citizens. 

Kioko McGrath, culture correspondent for [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]], reported: 

“A colossal holo-sculpture was due to be unveiled at midnight to mark the start of 3305. Inspired by the Federal insignia, the intention was for the sculpture to be visible above Olympus Village, and seen by millions of people.” 

“But upon activation, the image that materialised was a gigantic cat's face, winking repeatedly. The original holo-sculpture code was later discovered to have vanished.” 

The [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]] believes the culprit to be the same art thief who stole valuable works on Alioth and Eotienses A 3, both of which were marked with an identical ‘winking cat’ motif. 

There are no leads at present.
