:PROPERTIES:
:ID:       bafb1c97-9b9a-4717-af13-81a0ccfb1765
:END:
#+title: President Halsey Denounces Patron’s Principles
#+filetags: :Empire:Federation:3301:galnet:

* President Halsey Denounces Patron’s Principles

/27 Apr 3301/

This weekend saw the outbreak of a skirmish between Imperial and Federal forces in the small but significant system of Volungu. Reports indicate that the conflict was started by the Patron’s Principles, an Empire-aligned organisation based in the nearby Liaedin region. 

For years Liaedin was caught in almost constant civil war as the Faveol and Blossom families fought to gain control of the region. The two sides eventually settled their differences, with the Imperial Faveol family ultimately being given governorship of the system. 

Now it looks as if the feud could be starting up again, as the Faveol family-run Patron’s Principles have made the seemingly rash decision to attempt to expand their influence beyond Liaedin’s borders. 

President Halsey has denounced the move by Patron’s Principles, calling it ‘a reckless abandonment of years of hard-won peace’. The Federal Navy has launched a small fleet to repel the invasion, and has requested that any Commanders interested in securing Volungu should sign up for active duty aboard Jemison Refinery. 

When asked for comment, Chancellor Blaine’s office stated that the Patron’s Principles were acting without the support or knowledge of the Imperial Senate. Imperial sources close to the region noted that members of the East India Company have been dispatched to the area to try to resolve the matter peacefully.
