:PROPERTIES:
:ID:       3dd85392-8fd3-4839-bc79-5a805dea86c2
:END:
#+title: Far God Cult Condemns Salvation
#+filetags: :3308:Empire:Thargoid:galnet:

* [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] Cult Condemns Salvation

/04 Jul 3308/

Azimuth Biotech’s operation in the [[id:55088d83-4221-44fa-a9d5-6ebb0866c722][HIP 22460]] system has been publicly denounced by the Thargoid-worshipping fringe religion. 

A video message from a hooded young woman aboard the Testament, the cult’s missionary vessel, was transmitted directly to the newsfeed Vox Galactica: 

“This plan to entrap and destroy the heralds of the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] must cease immediately. As the newly appointed First Apostle of the True Chapters, I beseech those in authority not to support [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s evil crusade. To slaughter these holy beings is a monstrous act of deicide.” 

Dr [[id:2bf69df4-bf62-4877-87eb-5158254f5fcb][Alfred Ulyanov]], a leading authority on the enigmatic sect, commented: 

“It is extremely unusual for [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] believers to make any kind of announcement or acknowledge current events. They accept their own deaths with equanimity, believing as they do that all life will be extinguished when the Far God emerges from hyperspace. But they are clearly incensed by [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s intention to eliminate the Thargoid fleet, viewing it as a blasphemous attack against their deity.” 

“We cannot identify the messenger, although her Imperial accent is a surprise considering the cult has been outlawed in the Empire. ‘First Apostle’ is an unexpected new rank among their leaderless hierarchy, and suggests she has been elevated to spokesperson status. ‘True Chapters’ is likewise a departure from their usual sequential numbering, raising the possibility that this is a sub-sect branching off from the orthodox faith.”
