:PROPERTIES:
:ID:       94b069a4-f0c5-4e3b-bcce-04ebdfd1f503
:END:
#+title: Emperor's Grace Reaffirms Loyalty to Patreus
#+filetags: :3301:galnet:

* Emperor's Grace Reaffirms Loyalty to Patreus

/08 Jun 3301/

Emperor's Grace Reaffirms Loyalty to Patreus 
 
On the personal order of Varrwen Mako Brennus, all members of Emperor's Grace are instructed to extend their support to Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] where possible. 

Senator Patreus demonstrated support for Emperor's Grace during recent unpleasant circumstances when senior members of Emperor's Grace stood accused of Treason. This unfounded and scurrilous accusation was disproven before the Imperial Senate. Moreover, Emperor's Grace was instrumental in finding the criminals behind the recent assassination attempt on Emperor Duval.  

Explaining the decision to extend support to Senator Patreus, Admiral Brennus declared to a packed audience that "we never forget our friends and we always remember our enemies." 

Commander Light Fingers 

Imperial Security Service Lead 

Emperor's Grace
