:PROPERTIES:
:ID:       761b2196-c1c8-4f47-96f7-2272b86f39b7
:END:
#+title: President Kincaid Illegal Funding Allegations
#+filetags: :galnet:

* President Kincaid Illegal Funding Allegations

/04 May 3305/

President Gibson Kincaid has been accused of receiving illegal campaign funding via the Bank of Zaonce. 

Councillor Elijah Beck presented evidence to a special session of the Alliance Assembly: 

“During September 3304, President Kincaid’s re-election campaign received several billion credits worth of undeclared funds. I have received data suggesting that these transactions were secretly arranged by a senior figure within the Bank of Zaonce.” 

“Regrettably I cannot reveal the source of this evidence since it constitutes part of an ongoing investigation. However, I call upon the Assembly to open an official inquiry to establish if there was any violation of campaign finance law.” 

Councillor Beck’s proposal was approved by a majority vote, after which Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] authorised the inquiry to begin immediately. 

As yet there has been no comment from President Kincaid.
