:PROPERTIES:
:ID:       ce11947d-03e0-4bd7-8bca-5e5ac917e9a5
:END:
#+title: Imperial Slave Regulations Proposed
#+filetags: :3301:Empire:galnet:

* Imperial Slave Regulations Proposed

/14 Sep 3301/

Imperial Slave Regulations Proposed

Following the recent audit of the Imperial Slave Association, the [[id:6b539fa1-7ebe-44d3-874b-41a3bd400af9][Imperial Senate]] Audit Committee has recommended the introduction of further regulations governing the treatment and transportation of Imperial slaves.

The proposed regulations centre on improved vetting of commanders permitted to transport Imperial slaves, and include the suggestion that pilots must hold the rank of ‘Master’ in the [[id:e9becd28-9644-42aa-afc8-7bba3ce10076][Imperial Navy]] as a minimum requirement. It is also suggested that resources be set aside for the recovery of Imperial slaves transported and sold outside the Imperium.

Svetlana Zhukov, chairwoman of the ISA, voiced her support for the regulations:

“It is our duty to ensure that Imperial citizens serving terms as slaves remain within the borders of the Empire until they are returned to full citizenship. Our hope is that these new regulations will ensure the rights of [[id:02df3938-8684-467d-b46e-cd60621e1fd3][Imperial Slaves]] are not trampled on by those unscrupulous enough to sell people for quick credits."

Political commentators have expressed doubt that the proposed regulations will be approved, but many remain hopeful.

Commander Corrigendum

Capitol Herald | Interstellar Press
