:PROPERTIES:
:ID:       d068d2f4-03ef-49d0-ade6-d2290aae0bfd
:END:
#+title: Vitadyne Admits Nanomeds of Utopian Origin
#+filetags: :3305:galnet:

* Vitadyne Admits Nanomeds of Utopian Origin

/03 Jan 3305/

Professor [[id:c39e36c5-83ba-4e22-8dc1-c5705b33910a][Katrien Rook]] has responded to [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]]’s claim that her company’s nanomedicines are of Utopian origin:

“I confess that [[id:77d8c368-863a-42f1-af95-99fc0b7bd5c3][Vitadyne Labs]] did not invent the nanomeds, but neither did we steal them. We were approached by independent pilots who discovered a crashed Utopian transport ship. The recovered cargo canisters were clearly medical in nature, so the foragers sold them to us as legitimate salvage.”

“I would be happy to return the original cargo to Utopia with our apologies. The new nanomeds that we have created are our property, however, and I insist that we be allowed to continue their manufacture.”

[[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] swiftly issued a reply:

“Any derivative nanomedicines must also be returned to us, and production must cease. Our technology cannot be used outside Utopia.”

The [[id:50320afd-f184-4f90-a94b-802400bb39a8][Interstellar Health Organisation]] has said that it will review the case and make a decision.
