:PROPERTIES:
:ID:       11f35420-822f-4a66-a51d-b2ba04134f41
:END:
#+title: Freelance Report: CIMA Honours Contest Winners
#+filetags: :3302:galnet:

* Freelance Report: CIMA Honours Contest Winners

/06 May 3302/

Benjamin Gorrister, founder of the Carmack Intergalactic Mining Association, has honoured winners of the CIMA prospectors competition at a prize-giving ceremony at Wasden Colony in Halbara. 

"It is a great pleasure to acknowledge the pilots who found the most pristine metallic rings," said Gorrister. "The first prize, of 50 million credits, goes to Commander Kjnpbr who found 200 new systems. The second prize, of 30 million credits, goes to Commander Irisa Nyira who found 100 new systems. And the third prize, of 18.5 million credits, goes to Commander Gonzoid who found 85 new systems."  

Prior to the ceremony, Commander Kjnpbr was seen giving a data matrix containing information on even more pristine metallic ring systems to CIMA's chief engineer, Maxim Kammerer. 

Karen Keish 

Theta Wave News
