:PROPERTIES:
:ID:       9e8de8c5-c2ee-4f34-a1f5-83db43690b0f
:END:
#+title: Community Goal: New Imperial Base in Pleiades Sector Ab-W B2-4
#+filetags: :Empire:CommunityGoal:3302:galnet:

* Community Goal: New Imperial Base in Pleiades Sector Ab-W B2-4

/22 Sep 3302/

The Merope Expeditionary Fleet has been tasked with constructing a new forward operating base in the Pleiades Sector Ab-W B2-4 system on behalf of the Empire. The new outpost will support the Empire's ongoing operations in the Pleiades Nebula. 

A spokesperson for the Merope Expeditionary Fleet released a statement: 

"I realise some might perceive this as an attempt to assert Imperial dominion over the Pleiades Nebula, but establishing a strong military presence in the Pleiades is the only way we can oppose Federal attempts to establish a monopoly on meta-alloys." 

In support of this initiative, the Merope Expeditionary Fleet has placed an open order for Power Generators, Tantalum and Auto Fabricators, and has promised to reward pilots who deliver these commodities to its base of operations at Obsidian Orbital in the Maia system. 

The campaign begins on the 22nd of September 3302 and will run for one week. If final targets are met earlier than planned, the campaign will end immediately.
