:PROPERTIES:
:ID:       7793cde3-8038-4bfc-976f-793a072fcd94
:END:
#+title: Prime Minister Mahon announces open trade agreement for Lave cluster
#+filetags: :3301:Alliance:galnet:

* Prime Minister Mahon announces open trade agreement for [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] cluster

/28 Jun 3301/

Prime Minister Mahon announces open trade agreement for [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] cluster 
 
During a press conference in [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] earlier today, Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has expressed his gratitude towards the independent pilots who supported his initiative to strengthen the economical bonds with the Old Worlds in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] cluster. Mahon assured his declared intention to keep the cluster open for traders of all affiliations and has announced an open trade agreement that will grant any trader safe passage. 

To ensure the safety of trader ships in the sector, he has commissioned the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] to establish a permanent presence in the sector, to counter the growing threats to civilian traders from piracy and crime. The Council of Admirals has announced that the deployment of such forces will begin soon.
