:PROPERTIES:
:ID:       fadf9409-0584-4d2a-a868-46bcb780a821
:END:
#+title: The Lessons of the Blight
#+filetags: :galnet:

* The Lessons of the [[id:1cffca4e-480b-46bf-b6c5-0af48c7292d3][Blight]]

/02 Nov 3305/

The blight that laid waste to vast areas of cropland over the past month has now officially been contained. 

Reports from the Interstellar Association for Agriculture confirm that the blight has been eliminated from all affected systems. The new agronomic treatment has rejuvenated emaciated fields, with the remaining harvests once again viable. 

Journalist Adalyn Cross published a review of recent events on Vox Galactica: 

“As the availability of staple foodstuffs begins to return to something like a normal level, many pundits are asking what lessons can be learned from this catastrophe. The IAA has pledged to intensify screening regulations for agricultural commodities. The speed with which the blight spread caught many by surprise, and it is vital that this does not happen again.” 

“Intelligence agencies have pledged to review their strategies for tackling interstellar terrorism. The Scythe of Panem extremists who engineered the blight have been dealt with, but who else might be planning a biochemical attack?” 

Meanwhile, the Rockforth Corporation’s PR department is working hard to reassure customers and shareholders. Critics have underscored the role of the EX7 fertiliser as a primary delivery system for the pathogen, but a Rockforth source argued that the product’s sabotage by Scythe of Panem agents could not have been anticipated. 

Nevertheless, the company’s haste to increase profits has been highlighted as a contributing factor in the blight’s impact. Rockforth is expected to release a statement in the next few days, pending an internal review.
