:PROPERTIES:
:ID:       2260bfcc-8bb4-437f-9e1d-f46167e84577
:END:
#+title: Pegasi Intervention Sparks Debate at Home
#+filetags: :galnet:

* Pegasi Intervention Sparks Debate at Home

/30 Jul 3301/

Pegasi Intervention Sparks Debate at Home 
 
Unaffiliated supporters of Arissa Lavigny-Duval have today voiced concerns at rumours of an escalating intervention in the Pegasi Sector on the part of Lavigny's Legion. 

Discussion of the the highly publicised plight of Imperial citizens living in volumes of space controlled by Archon Delaine's Kumo Crew dominated newsfeeds and social media throughout Kamadhenu over the weekend. Opinion is split on the humanitarian value of an intervention in a region perceived by some as extremely remote. 

Speaking anonymously one commander said: "I don't understand why the Legion is wasting time with a foreign backwater like the Pegasi Sector. I'd never even heard of it before. We've got our own problems with corrupt Dictatorships and greedy Corporations right here at home. We need to clean up the Empire before we try cleaning up the whole Galaxy!". 

Anger erupted when it was revealed that diplomatic overtures had been made towards the Federation in regards to confronting the Kumo Crew. 

It was later made clear that Lavigny's Legion itself took no part in any talks with envoys of Shadow President Felicia Winters or President Zachary Hudson. A diplomat for Aisling Duval's Aisling's Angels confirmed their own attendance at talks. 

The suggestion that Arissa Lavigny-Duval's supporters might be pulled into joint operations with either Hudson or Winters has resurfaced deeply held anti-Federation sentiment, with reports of at least one commander plotting a course to Sol in a well armed vessel in response to the rumours. 

Commander Edgar Starwalker
