:PROPERTIES:
:ID:       cec7f687-0bf0-41f1-8b98-00079be3ea9d
:END:
#+title: New Prisoner Facilities in Veroklist
#+filetags: :galnet:

* New Prisoner Facilities in Veroklist

/11 May 3304/

The Empire has announced plans to construct a new Riker-Class Prison Ship in the Veroklist system. 

Once complete, the ship will house criminals who accepted a period of Imperial slavery in lieu of a jail sentence, but who have proved to be too dangerous or unstable for such corrective punishment. 

The Moritasgus Imperial Corporation, which is overseeing the initiative, has placed an open order for Imperial slaves and non-lethal weapons, promising to reward pilots who deliver these commodities to Vaucouleurs Vision in the Veroklist system. The organisation has also placed a kill order on all ships on its wanted list, to ensure those contributing commodities to the campaign can do so safely. 

Moritasgus Imperial Corporation spokesperson Superintendent Arnold Cochran released the following statement: 

“We are pleased the Empire has awarded us this contract, and we look forward to the first ships arriving with our new guests.” 

The campaign begins on the 10th May 3304 and will run for one week. If the final target is met earlier than planned, the campaign will end immediately.
