:PROPERTIES:
:ID:       e41179fe-912b-4eff-9304-48bd3562dd25
:END:
#+title: Onionhead Legality Sparks Debate
#+filetags: :3307:Empire:Federation:Alliance:galnet:

* Onionhead Legality Sparks Debate

/13 Aug 3307/

The introduction of onionhead gamma strain by the Kumo Crew has reignited long-running arguments around the popular psychedelic drug. 

An interview with Zander Lachance, spokesperson for the Coalition for Legalisation, was published by Vox Galactica: 

“I have yet to see evidence that onionhead is more harmful than common recreational substances. Open-minded people in independent systems are now discovering this for themselves.” 

In response, other newsfeeds featured a range of opinions. 

Eye on [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]]: “Foppish rogues of the Federation such as [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] and Sir Randolph Plaskett may feel comfortable wooing trade tycoons with the outlawed weed, but legalising low-cost onionhead would risk the whole Empire collapsing into a stupor!” 

The [[id:dc25c5b7-381e-4e8a-8599-68be61b19bae][Pegasi Sentinel]]: “The popularity of ‘helix’ is steadily growing, and the revenue it generates will undoubtedly benefit those fortunate to live within [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]]’s dominion.” 

Sol Today: “Imperial hedonists such as Senator Leatrix and Duchess Rouncival may offer such illicit treats at their decadent parties, but bombarding the masses with this cheap narcotic will have the entire Federation chasing unicorns!” 

The Sovereign: “Tourists from many independent worlds are booking holidays to the Alici, Baraswar, Kishpakho, [[id:f99cc815-f736-48e1-863d-7e50b14b7273][Nastrond]] and Nocori systems, where the gamma strain of onionhead is legal. There is no shortage of Alliance citizens following suit, which may pressure the Assembly to formally legislate one way or the other.”
