:PROPERTIES:
:ID:       216cb831-808b-4ec4-9d0f-1b4c8af9d71d
:END:
#+title: Cerberus Plague Spreads to the Bastes, Maheou Ti and Ochoeng Systems
#+filetags: :3301:galnet:

* Cerberus Plague Spreads to the [[id:ba9787a7-583f-4fb0-b9e1-3c0c0096b485][Bast]]es, [[id:68089c1e-578f-4f8a-9c0d-7417a55013ee][Maheou Ti]] and [[id:641d5a2f-9417-469c-a004-c9588ca558e8][Ochoeng]] Systems

/23 Jul 3301/

Cerberus Plague Spreads to the [[id:ba9787a7-583f-4fb0-b9e1-3c0c0096b485][Bast]]es, [[id:68089c1e-578f-4f8a-9c0d-7417a55013ee][Maheou Ti]] and [[id:641d5a2f-9417-469c-a004-c9588ca558e8][Ochoeng]] Systems 
 
News of fresh cases of the Cerberus Plague has caused mass panic among the populations of Shepherd Hub in the [[id:ba9787a7-583f-4fb0-b9e1-3c0c0096b485][Bast]]es System, Yegorov Station in the [[id:68089c1e-578f-4f8a-9c0d-7417a55013ee][Maheou Ti]] system and Roddenberry [[id:e179ecca-9ab3-4184-b05e-107b2e6932c2][Gateway]] in the [[id:641d5a2f-9417-469c-a004-c9588ca558e8][Ochoeng]] system. Even though the number of cases reported so far is relatively low, the medical services and hospitals have been overwhelmed by citizens desperate for treatment, despite not being infected. 

Station authorities have appealed for calm and restricted movement to only the most essential travel. States of emergency have been declared and open contracts for urgent medical and aid supplies are being issued for these systems.
