:PROPERTIES:
:ID:       bf2d3366-2a78-42f4-af62-258de4378de6
:END:
#+title: Galactic News: Former Federal President Found
#+filetags: :Federation:3302:galnet:

* Galactic News: Former Federal President Found

/26 Feb 3302/

The recent Federal operation to search for survivors from Starship One was eagerly supported by the galactic community, resulting in the safe recovery of thousands of escape pods, many of them containing living survivors. As the task of identifying the pod's occupants continues, Federal President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] has made a surprising announcement: one of the escape pods taken to Leoniceno Orbital contains former Federal president [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]]. 

"When we started searching for the remains of Starship One it was with the aim of discovering what happened to the ship. I never imagined we would find survivors, and certainly not that one of them would be [[id:a9ccf59f-436e-44df-b041-5020285925f8][Jasmina Halsey]]." 

Asked about Halsey's condition, Hudson said: 

"The medical team at Leoniceno has described Halsey's condition as critical but stable. It appears her escape pod was damaged and she sustained some injuries, so she's being kept in an induced coma until her wounds have healed. This is likely to take weeks. If her condition changes I will be immediately notified."
