:PROPERTIES:
:ID:       b39575a5-06e1-4f15-9e4f-6917ad32cdf1
:END:
#+title: Meet the Powers – Aisling Duval
#+filetags: :3301:galnet:

* Meet the Powers – Aisling Duval

/24 Jul 3301/

Meet the Powers – [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] 
 
In this new series, exclusive to GalNet, the popular political commentator Marcus Macmillan looks at some of the movers and shakers in 3301. In this first article he examines the life of the popular darling of Imperial politics: Princess Aisling Duval. 

Aisling Duval is Prince Harold’s eldest child, but has gained a substantial following on her merits. She appears to be a canny operator, although many would argue that her advisors provide her with a veneer of acumen. She is young at only 25, and very visible in the media. Her claim to the throne is technically nullified by the fact that her parents were not married, but her claim is no weaker than some of the other contenders. 

The people’s princess (as she is sometimes known) is extremely popular with many citizens, clients and patrons. She regularly appears on lightweight chat shows, but tends to avoid anything where she might have to face tough questions. 

At heart Aisling is a populist, taking many of her views from the public mood. She splits her time between managing her brand from Cemiess, and spending time with her father in Achenar. Her mother died of a drugs overdose when she was young which, combined with her father’s unfortunate legacy from a hedonistic life, has left Aisling with a passion for helping those whose lives have taken a turn for the worse. 

Despite her youth, she enjoys considerable support from the people and also from elements who would benefit from shaking up Imperial society.
