:PROPERTIES:
:ID:       9f0904cb-36a7-4867-b147-22fed0491515
:END:
#+title: Freelance Report: The Demands of Supply
#+filetags: :galnet:

* Freelance Report: The Demands of Supply

/15 Jul 3302/

"Commanders are advised to search within nebulae for rocky or high-metal content worlds with a composition of between 66.5% and 99.1% rock and 8.9% and 33.5% metal, with 0% ice. Temperatures between 194K and 451K should be sought. To narrow the field, Commanders should also seek bodies with gravity between 0.06g and 0.3g." 

This text is taken from 'Barnacle Search Criteria', a recent publication from the Canonn Interstellar Research Group. 

Commentators are divided on what impact, if any, this information will have on the increasingly volatile situation in and around the Merope system. But many agree that if the barnacles are being viewed as a finite resource, the Canonn's data may serve to defuse tensions, at least temporarily. 

The publication of the criteria is believed to have followed a private conference between Dr Arcanonn and Professor Cora Shaw, director of the Palin Institute. Dr Arcanonn commented: 

"We must not let the drums of war drown out the fact that the stated positions of the Federation and the Empire are, upon review, far from irreconcilable." 

Commander Nicholas Powell
