:PROPERTIES:
:ID:       4629e58c-4917-413a-bd68-fa41bc541790
:ROAM_REFS: https://cms.zaonce.net/en-GB/jsonapi/node/galnet_article/e9a7fd6a-aecf-46e7-8e60-3f1d8f80bd59?resourceVersion=id%3A4882
:END:
#+title: Aegis Supports Galactic Summit
#+filetags: :galnet:

* Aegis Supports Galactic Summit

/08 Jan 3307/

The organisation Aegis has expressed support for Utopia’s offer to host a Galactic Summit for all three superpowers. 

Aegis was jointly formed by the Alliance, Empire and Federation to study the Thargoids, and develop new methods of monitoring and combating their forces. 

Professor Alba Tesreau, head of research at Aegis, gave this statement: 

“Humanity’s focus on petty internal conflicts has blinded us to the existential threat of the Thargoids. Their recent horrific attacks should be a wake-up call to the fact that defunding has crippled Aegis’s ability to offer protection.” 

“We strongly entreat our founders to come together and channel resources toward Aegis, and particularly into research. There can be no hope of coexistence with this alien species unless we increase our understanding of them.” 

No official responses to Utopia’s proposal have been made as yet. However, Prime Minister Edmund Mahon, Princess Aisling Duval and Shadow President Felicia Winters have all signalled broad approval of the idea. There are reports that many congressmen, councillors and senators are pressuring their respective leaders to attend the diplomatic conference. 

Simguru Pranav Antal has confirmed that the governments of independent systems will also be welcome to send delegates to the Galactic Summit. However, Utopia’s primary aim is to provide neutral territory for the Alliance, Empire and Federation to debate policies.
