:PROPERTIES:
:ID:       4e2ab42c-e747-4ef2-a693-4843425bac2c
:END:
#+title: Rumours Circulate Around Seo Jin-ae
#+filetags: :Thargoid:galnet:

* Rumours Circulate Around [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]

/20 Mar 3309/

An anonymous source has leaked information regarding [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]
suggesting that she may be in serious jeopardy.

[[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]], the individual once known as [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Subject D-2]], voluntarily
departed from a private medical facility in January, where she was
under the care of former Aegis members. She left a message stating: “I
have unfinished business with [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]].”

The engineer [[id:d8266505-5aa0-40a3-aa84-4b6519a16b24][Kit Fowler]] discussed the recent rumours during his End
Times broadcast:

“Something is definitely going on, people. The interstellar grapevine
is buzzing with gossip about [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]. That cortical implant in her
head, which provides some weird insight into Thargoid behaviour, makes
her pretty much most valuable person in the galaxy right now.”

“Some say that a black ops teams have either kidnapped or assassinated
her. Maybe it’s Azimuth. Maybe it’s a dead man’s switch group
belonging to [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. One pilot tells me he spotted an Aegis patrol
in the Ngaruayanka system, and thinks it was sent to recover poor
Seo’s body. And a hacktivist from the Collective has intercepted comms
fragments containing the words ‘[[id:f55dd9f1-52aa-4ca9-93c4-27175612c59a][Bright Sentinel]]’ and ‘[[id:e2b09f7f-0440-49ff-980c-6dc0e9a5b0b9][Nemesis
protocol]]’. What secrets did Seo uncover? And is she still alive to
share them?”

[[id:85d9e888-3f5b-40ed-b8af-2eb87e42b0d0][Aegis]] has been approached for comment, but only reiterated that they
are currently investigating [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo Jin-ae]]’s whereabouts.

Director [[id:faef4471-b502-4f68-b139-c663b0b00ce3][Nassim Qadir]], head of medical research at [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biotech]],
provided a statement:

“Aegis’s amateurish efforts to examine Ms Seo have clearly resulted in
some form of dissociative disorder and paranoid delusions. This
explains her obsessive vendetta against a man whose death was
independently verified. If Ms [[id:6bcd90ab-54f2-4d9a-9eeb-92815cc7766e][Seo]] can be located, she should be
returned to Azimuth’s specialist laboratories for her own wellbeing.”
