:PROPERTIES:
:ID:       c20adf38-e281-4d04-ab1d-392a1f8bd850
:END:
#+title: Week in Review 29 Sep 3304
#+filetags: :Federation:Alliance:3304:galnet:

* Week in Review

/29 Sep 3304/

Here are this week’s major stories. 

The three candidates for the Alliance presidency have spent much of the past week delivering their campaign messages. While incumbent president [[id:8520e75f-0479-42c5-9083-f9abfbad721e][Gibson Kincaid]] has demanded radical change to the constitution, rival candidates [[id:e46779af-a26e-45fb-a784-21e970eeaae1][Fazia Silva]] and Elijah Beck have adopted more conservative stances, focusing on economic growth and civil liberty respectively. The new president of the Alliance will be announced in October. 

The Federal Intelligence Agency has terminated its investigation into the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult. In a statement, the FIA confirmed that information provided by undercover reporter [[id:b9531f53-8bad-4eda-a0aa-46c72bb6ec9a][Gethin Okonkwo]] had cleared the sect of any suspicion. All worshippers who were detained have now been released. 

In other news, rival companies [[id:46e9f326-2119-4d5b-a625-a32820a44642][Herculean Machines]] and [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]] have resumed development of their new personal computers, following successful requests for public support. Both companies have now returned their attention to the [[id:9d064da0-7be3-4c7b-99ad-0edd1585d4ca][Rackham Ultratech Expo]], where they will unveil prototypes of their new designs. It is suspected that the amount of commodities each company received might be the deciding factor in their commercial success. 

Meanwhile, the personal administration robot of business magnate [[id:618fc109-cba3-4782-b24d-e4440f5894d4][Lloyd Hardacre]], which recently revealed evidence of his criminal activity, has been found to contain a concealed surveillance program. The revelation came from the [[id:0ba9accc-93ad-45a0-a771-e26daa59e58f][Federal Security Service]], which found a surveillance program within the robot’s coreware that was covertly copying certain types of data. The FSS now believes that Mr Hardacre was the target of an undercover spy operation. 

Finally, citizens of the Bhagui system are attempting to resurrect the ancient Oktoberfest celebration, an annual event based on a centuries-old Earth tradition. Mould Federal Mining Incorporated has agreed to finance the event, and has placing an open order for various commodities. A spokesperson for the organisation promised the festival would be “a party like no other.” 

And those are the main stories this week.
