:PROPERTIES:
:ID:       6f4dc53c-1157-4419-b109-944f2b49435d
:END:
#+title: Week in Review 05 Aug 3304
#+filetags: :Federation:Alliance:Thargoid:3304:galnet:

* Week in Review

/05 Aug 3304/

Here are this week’s major stories. 

An attempt to assassinate Princess [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] has been prevented by the Imperial Internal Security Service. The attempt occurred in the Zhao system during a fundraising event. The IISS is analysing the explosives used in the attempt to determine their origin. 

Meanwhile, former rear admiral Riri McAllister has been shot. She is currently undergoing medical treatment. The incident took place at the Alliance Chamber of Justice on Turner’s World in the Alioth system. McAllister was on trial for organising acts of terrorism as Nexus, founder of the League of Reparation.  

The Federal Intelligence Agency has launched an investigation into the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult. Several members of the sect have been arrested. An FIA agent said that the purpose of the investigation was to confirm that the sect was not in contact with Thargoid forces, or being influenced by them. 

In other news, Aranbarahun Purple Creative, an independent organisation based in the Aranbarahun system, has announced plans to build a massive cargo ship to transport goods out of the booming system. In support of this goal, the organisation has placed an open order for various commodities, and has promised to reward pilots who deliver these commodities to Barnes Terminal in the Aranbarahun system. 

Celebrated author Olav Redcourt has cancelled the promotional tour for his latest novel. In a statement, the author said he was abandoning the historical-romance genre in favour of a new science-fiction saga. The author’s agent responded by underscoring that science-fiction is a niche genre with a tiny audience. 

Finally, the Alliance has announced that its appeal for mined resources has reached a successful conclusion, having received an overwhelming response from the galactic community. Huge quantities of raw material were delivered to California Gateway over the past week, which will be used to construct an Ocellus starport in the MEL 22 Sector GM-V C2-8 system. 

And those are the main stories this week.
