:PROPERTIES:
:ID:       e96ede7a-f5e3-4160-b59f-394f1916199f
:END:
#+title: Patreus and Aisling Attend Benefit Gala
#+filetags: :Empire:3301:galnet:

* Patreus and Aisling Attend Benefit Gala

/22 Apr 3301/

Denton Patreus and [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] were spotted in attendance at ‘A Dinner to Defeat Dementia’ in Capitol last night. The Empire’s favourite power couple spent several hours mingling with Senators, CEOs and a few of the charity’s lucky patrons, before dazzling the crowd with a rather energetic display on the dance floor. 

Aisling was dressed in an unusually demure, long necked, floor length red gown with flowing sleeves. The Senator was dressed casually in an open necked navy blue shirt with stylish silver trimming along the collar and cuffs.  

The couple were accompanied by Aisling’s new entourage, a dozen young orphans, dubbed Aisling’s ‘Cherubs’ by the attendees. The children delighted the crowd by singing, dancing and reciting several epic works of Imperial poetry.
