:PROPERTIES:
:ID:       4e2ab42c-e747-4ef2-a693-4843425bac2c
:END:
#+title: Rumours Circulate Around Seo Jin-ae
#+filetags: :Thargoid:galnet:

* Rumours Circulate Around Seo Jin-ae

/20 Mar 3309/

An anonymous source has leaked information regarding Seo Jin-ae suggesting that she may be in serious jeopardy. 

Seo Jin-ae, the individual once known as Subject D-2, voluntarily departed from a private medical facility in January, where she was under the care of former Aegis members. She left a message stating: “I have unfinished business with [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]].” 

The engineer [[id:d8266505-5aa0-40a3-aa84-4b6519a16b24][Kit Fowler]] discussed the recent rumours during his End Times broadcast: 

“Something is definitely going on, people. The interstellar grapevine is buzzing with gossip about Seo Jin-ae. That cortical implant in her head, which provides some weird insight into Thargoid behaviour, makes her pretty much most valuable person in the galaxy right now.” 

“Some say that a black ops teams have either kidnapped or assassinated her. Maybe it’s Azimuth. Maybe it’s a dead man’s switch group belonging to [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]. One pilot tells me he spotted an Aegis patrol in the Ngaruayanka system, and thinks it was sent to recover poor Seo’s body. And a hacktivist from the Collective has intercepted comms fragments containing the words ‘Bright Sentinel’ and ‘Nemesis protocol’. What secrets did Seo uncover? And is she still alive to share them?” 

Aegis has been approached for comment, but only reiterated that they are currently investigating Seo Jin-ae’s whereabouts. 

Director Nassim Qadir, head of medical research at Azimuth Biotech, provided a statement: 

“Aegis’s amateurish efforts to examine Ms Seo have clearly resulted in some form of dissociative disorder and paranoid delusions. This explains her obsessive vendetta against a man whose death was independently verified. If Ms Seo can be located, she should be returned to Azimuth’s specialist laboratories for her own wellbeing.”
