:PROPERTIES:
:ID:       7a64eba5-fa74-45a9-9f53-726b95a6b8d9
:END:
#+title: ximilian North, Sirius Atmospherics’s project director, outlined the requirements: 
#+filetags: :Federation:Alliance:galnet:

* Explorers Needed for Coalsack Nebula Project

/03 Dec 3306/

*Pilots Federation ALERT* 

Sirius Atmospherics has requested help from independent pilots to provide exploration data focusing on ammonia worlds for terraforming purposes. 

The subsidiary of Sirius Corporation is working in partnership with the Alliance to establish colonies within the Coalsack Nebula, and to identify sites of commercial and scientific interest. 

Dr Maximilian North, Sirius Atmospherics’s project director, outlined the requirements: 

“We have developed revolutionary new terraforming procedures for terrestrial planets with ammonia-based atmospheres. Our collaboration with the Alliance is the perfect opportunity to try and put these to practical use, with the goal of transforming the region into a more human-friendly place.” 

“Sirius Atmospherics offers rewards for explorers who can provide us with exploration data. We are particularly interested in detailed scans focusing on the composition of ammonia worlds, not just in the Coalsack Nebula but elsewhere. Gathering wide-ranging data will enable us to determine the most suitable targets for environmental conversion.”  

Pilots are requested to deliver exploration data to the Sirius Atmospherics research facility at Betancourt Base in the Musca Dark Region PJ-P b6-1 system.
