:PROPERTIES:
:ID:       4f1ee6fe-38ff-48e2-8cb3-513deb3d44a4
:END:
#+title: ‘Ghost Ship’ Leads Alliance to New Resources
#+filetags: :galnet:

* ‘Ghost Ship’ Leads Alliance to New Resources

/09 Nov 3306/

Discoveries made two hundred years ago by an abandoned megaship have revealed untapped sources of meta-alloys within the Coalsack Nebula. 

The Adamastor, which was launched in 3111, returned to the Chukchan system from the Coalsack Nebula on autopilot with no traces of its crew. [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] barnacle sites were found in the nebula by independent pilots. 

The Alliance Assembly has announced an expedition to thoroughly explore the nebula, with the primary goal of securing fresh sources of meta-alloys. A press release stated: 

“Recent [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] activity in the Witch Head Nebula and over-exploitation of that region mean that this latest discovery has come at an opportune time. The Coalsack Nebula will now be the focus of an initiative to identify sites of commercial and scientific interest. To achieve this, we have established new partnerships with several corporations including Sirius Atmospherics.” 

“Although the mystery of the Adamastor may never be fully resolved, we hope it will leave a positive legacy for the people of the Alliance.” 

Mention of corporate partnerships caused ripples in certain industries, with speculation that these have been in the pipeline for months. Political commentators also observed that 3307 will be an election year for the Alliance, placing pressure on Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] to secure economic stability.
