:PROPERTIES:
:ID:       c3b27b3b-3921-413e-b398-6aa679045e2e
:END:
#+title: Galactic News: New Aegis Initiative
#+filetags: :3303:galnet:

* Galactic News: New Aegis Initiative

/02 Dec 3303/

Aegis has announced plans to dramatically expand its research division with the creation of over twenty new laboratories, situated at starports across the galaxy. 

Professor Alba Tesreau, Aegis’s chief scientific advisor, gave the following statement to The Imperial Herald: 

“We must do everything we can to further our understanding of the Thargoids. That’s why these new research centres are so important. Everything we can learn about the Thargoids’ history, biology and psychology is of potential value.” 

“If we could understand the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoids]] – really understand them – perhaps we could broker some kind of truce. I, for one, have not given up on the idea of peace.” 

“Over the past few months, we have conducted a massive recruitment drive to secure some of the galaxy’s best and brightest minds. Now it’s time to find out what those minds can accomplish.” 

The starports involved in the initiative include: 

Arc's Faith, HR 1183 

Armstrong Enterprise, Bhal 

Artemis Lodge, Celaeno 

Asami Orbital, Pleiades Sector JC-V D2-62 

Bao Landing, HIP 17497 

Beaufoy Vision, Nauni 

Bennington's Rest, 42 N Persei 

Borrego's Vision, Pleiades Sector IH-V C2-7 

Cavalieri, Electra 

Cleaver Prospect, Pleiades Sector HR-W d1-57 

Copernicus Observatory, Asterope 

Cyllene Orbital, Atlas 

Exodus Point, Hyades Sector AB-W B2-2 

Gaiman Dock, 49 Arietis 

Hudson Observatory, HIP 17694 

Kamov Survey, HIP 17892 

Kipling Orbital, Pleiades Sector KC-V C2-11 

Liman Legacy, HIP 16753 

Malthus Terminal, Pleiades Sector HR-W D1-41 

Obsidian Orbital, Maia 

Reed's Rest, Merope 

Rix Depot, Pleiades Sector IH-V C2-5 

The Oracle, Pleiades Sector IR-W D1-55 

Titan's Daughter, Taygeta 

Weyn Dock, 64 Arietis
