:PROPERTIES:
:ID:       752d7f77-88af-4146-a34a-4dd4f104330c
:END:
#+title: Community Goal: The Battle of Daramo
#+filetags: :Federation:Empire:CommunityGoal:3302:galnet:

* Community Goal: The Battle of Daramo

/23 Jun 3302/

The Daramo system is currently under Federal control, but recent reports indicate that both Imperial and independent forces – the latter under the rule of Pirate King [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] – are attempting to wrest power from the Federation. 

The Federation is evidently not about to capitulate. In a statement, Admiral Yorke of the Federal Navy said: 

"The Daramo system is of considerable strategic value to the Federation, and we will not surrender it without a fight. We have issued an emergency call to all Federation-aligned pilots – you are needed in Daramo!" 

The Empire, predictably, has responded in kind. Captain Danvers of the Imperial Navy said: 

"In the interest of the wellbeing of the citizens of Daramo, it is imperative that Imperial law be instated as soon as possible. If the Federation is allowed to retain control of the system, the people of Daramo will be sure to suffer." 

The Independents of Daramo have stepped in to coordinate operations on behalf of the Federation, while the Vaka Citizens of Tradition have been authorised to oversee the Imperial campaign. Both factions have set out week-long operations to take control of the system, which will begin on the 23rd of June 3302.
