:PROPERTIES:
:ID:       922d2ad8-5853-49c5-825d-ca2b6f8be1da
:END:
#+title: Galactic News: Chairman of MetaDrive Inc. Passes Away
#+filetags: :3302:galnet:

* Galactic News: Chairman of MetaDrive Inc. Passes Away

/23 Sep 3302/

Sad news from the [[id:2a4e7539-b87c-4ce9-8012-b2690fa3b618][Chi Orionis]] system this morning with reports that [[id:9752d776-cd68-44a0-84fe-18132d8b5e74][Femi Dakarai]], chairman of the hyperdrive-research company [[id:f778f4fa-9cd0-4e2c-b3f4-6ee7adac4d03][MetaDrive]] Inc., has passed away following a short illness.

Dakarai was taken ill last week after working tirelessly to secure financial backing for the company. Board members reported that he was working long hours and had been showing signs of stress for several months. An assessment of [[id:f778f4fa-9cd0-4e2c-b3f4-6ee7adac4d03][MetaDrive]] Inc. by independent auditor [[id:68956273-c433-4aac-aac3-1ebe826337e5][BigSix]] appears to have been the final straw.

"We should have acted sooner, but we were working extremely hard," said [[id:4a385f89-7be7-426b-aba4-1206a2e5f345][Rosaline Merden]], company secretary. "With the company set to deliver on some very exciting technology in the coming year, it's particularly tragic. We will carry on in his memory."

Board members were quick to pay their respects, and according to unofficial sources have made a generous payment to the Dakarai family on behalf of [[id:f778f4fa-9cd0-4e2c-b3f4-6ee7adac4d03][MetaDrive]] Inc.

In related news, [[id:4ab3e632-de21-44bc-a834-83b808a737ec][Raan Corsen]], a junior employee of [[id:f778f4fa-9cd0-4e2c-b3f4-6ee7adac4d03][MetaDrive]] Inc., was recently suspended from the company after auditors detected account irregularities. Security forces in the [[id:2a4e7539-b87c-4ce9-8012-b2690fa3b618][Chi Orionis]] system, recently brought under the control of the [[id:81738027-bf28-48e1-982e-001c2b404c83][Earth Defence Fleet]], have asked the public to report any sightings of Corsen.

[[id:f778f4fa-9cd0-4e2c-b3f4-6ee7adac4d03][MetaDrive]] Inc. has become something of a poster child for the depression currently affecting stock markets. Economic forecasts remain gloomy, with little prospect of improvement on the horizon.
