:PROPERTIES:
:ID:       bfd48ec0-751d-41a2-8c8b-097dcb9ad05a
:END:
#+title: Community Goal: Superpower Expansion
#+filetags: :galnet:

* Community Goal: Superpower Expansion

/21 Apr 3303/

For several months, the Maia system has been a focal point in the ongoing hostility between the Empire and the Federation. 

Now, the Empire and the Federation have announced plans to expand their presence in Maia by constructing new outposts. But with a shortage of reliable supply lines into the system, the superpowers are relying on the galactic community for help in compiling the necessary materials. Both are keenly aware that the finite nature of resources and support means only one will be able to proceed with its plans. 

Both the Empire and the Federation have promised to reward pilots who contribute construction materials to their respective campaigns. The Federal campaign is being coordinated by the Pleiades Resource Enterprise, while the Merope Expeditionary Fleet has been authorised to oversee the Imperial initiative. 

The rival campaigns begin on the 20th of April 3303 and will run for one week. If either faction achieves its aims earlier than planned, the campaign will end immediately.
