:PROPERTIES:
:ID:       9500654b-b860-402a-b276-94887421a0d3
:END:
#+title: Wallglass to Probe Rackham’s Past
#+filetags: :Federation:galnet:

* Wallglass to Probe Rackham’s Past

/05 Sep 3309/

The Federal Times has hired the Wallglass Investigations Agency to prove that presidential candidate [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] was once a pirate lord. 

Financial journalist Bryanna Blanco has long claimed that the business magnate obtained his initial fortune via piracy. Wallglass, an independent firm that is much respected in the intelligence community, is seeking evidence to validate this accusation. 

Harlan Turk, Rackham’s running mate in the election, has lobbied for Congress to halt the investigation. He asserted: “The Federal Times is breaching the impartiality rules of journalism, and violating the security measures afforded to all presidential candidates.”   

Political [[id:a12cdcbc-fa10-474e-8654-d3d7da17a307][ICE-caster]] [[id:f3e0128c-f8fd-4b90-a2c0-0ae5a5e487d0][Sura Oyekan]] also voiced her objections: “This is an outrageous attack on the reputation of a respected public figure, a great man who has contributed so much to Federal commerce and culture.” 

There was a more speculative approach from independent journalist Flint ‘Firemaker’ Lafosse: 

“Hiring the Wallglass Investigations Agency to dig up dirt on [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] is a smart move, albeit an expensive one. They’ll already have insights from their own detectives Gunnarson and Wolfe, who infiltrated the Jokers’ Deck gambling circle and found Rackham was a member. Or was he really there to quietly fund the coup against [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] by two of his own arch-corsairs? I think we all know the answer.” 

“Wallglass might also have access to the finance systems of [[id:83c8d091-0fde-4836-b6bc-668b9a221207][Rackham Capital Investments]], which were originally acquired by a hacktivist group known as the Collective. These nameless geniuses stole a billion credits – the same amount suspiciously won by Rackham in the Federal Grand Lottery – and distributed it to former employees whose pensions had been illegally withheld. Bravo!” 

“The latest rumours are that Wallglass has tracked down fellow pirate Taja Gavaris, the ex-CFO who attempted a corporate takeover. Allegedly she fled Federal space after Rackham counter-blackmailed her, but if anyone knows where the bodies are buried, it’s Gavaris. I’m expecting some juicy revelations soon.”
