:PROPERTIES:
:ID:       833832b9-60b8-4cd1-9044-48d3a32c91f1
:END:
#+title: Alliance and Federation React to Nova Imperium
#+filetags: :3304:galnet:

* Alliance and Federation React to Nova Imperium

/29 Dec 3304/

The leaders of [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] and [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] have commented on the rise of the isolationist group Nova Imperium. 

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] told [[id:1d726aa0-3e07-43b4-9b72-074046d25c3c][the Alliance]] Assembly: 

“The civil unrest in [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] is an internal matter, but it would be a major concern if it resulted in a policy change regarding inter-superpower cooperation. We are therefore watching the situation closely.” 

In Congress, President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] said: 

“If Nova Imperium comes to power and [[id:77cf2f14-105e-4041-af04-1213f3e7383c][the Empire]] ceases contributions to Aegis, our combined defences against the [[id:09343513-2893-458e-a689-5865fdc32e0a][Thargoid]] threat will be jeopardised. In such a case, [[id:d56d0a6d-142a-4110-9c9a-235df02a99e0][the Federation]] would be forced to intervene in order to safeguard humanity’s future.” 

Independent sources have confirmed that Federal Navy resupplies have increased in frequency. Fleet manoeuvres have also taken place in regions bordering Imperial territory.
