:PROPERTIES:
:ID:       dfa179f4-f41b-4dce-9799-99113689073b
:END:
#+title: Brewer Corporation Trailblazer Fleet Upgraded
#+filetags: :3311:galnet:
* Brewer Corporation Trailblazer Fleet Upgraded

/06 Mar 3311/

The campaign to update [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]]’s [[id:454c41b7-95ca-4e7e-94d4-c8a3f9d61d0e][Trailblazer]] fleet has concluded in the [[id:33b581d0-b31c-4177-9e70-9b478ad70e34][Minerva]] system.

Thanks to the efforts of independent pilots ferrying shipments to
Minerva, a total of 5 additional [[id:454c41b7-95ca-4e7e-94d4-c8a3f9d61d0e][Trailblazer]] megaships will be placed
in strategic locations on the fringes of the core systems, providing a
hub of tradable materials and services for early colonies.

[[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer]] COO [[id:9b2b1a6d-3645-4776-aeee-4e2db897b988][Mark Rennik]] remarked on the campaign’s success:

“Once again, we have received widespread support and confirmation of
our efforts, which is both humbling and inspiring. It is obvious that
there is great appetite for breaching the latest frontier to establish
new colonies, further expanding humanity’s sphere of influence in our
section of the galaxy.”

The Trailblazer megaships are expected to be deployed in the coming
weeks.

Participants can now collect their rewards from the initiative.
