:PROPERTIES:
:ID:       95772d84-e854-4b7d-938c-31ae87ec1346
:END:
#+title: Anti-Xeno Blockade Contains HIP 22460
#+filetags: :3308:Thargoid:3311:galnet:
* Anti-Xeno Blockade Contains HIP 22460

/10 Jan 3311/

A squadron of [[id:56ad8af3-baa1-4d0a-acd8-750400d280f4][AX]] pilots have planned to sustain pressure on the
lingering Thargoid presence in the [[id:55088d83-4221-44fa-a9d5-6ebb0866c722][HIP 22460]] system.

Led by the respected [[id:191fb0ed-5a88-4a49-a98d-e25794c5b36b][AXI]] and [[id:795e99a1-cd10-4768-8155-0d5cd0af6e10][XSF]] combat fleets, the blockade seeks to
push Thargoid craft from the area from January 12th.

HIP 22460 was the staging ground for [[id:106b62b9-4ed8-4f7c-8c5c-12debf994d4f][Salvation]]’s [[id:38143d4a-d8a5-4978-a62c-8b64a0c75969][Proteus Wave]] weapon,
which sought to end the [[id:9a246121-0c2e-4f21-9877-ee333d6b0d6c][Second Thargoid War]] in August 3308 but
resulted in disaster. Prior to this it is believed to have hosted
several clandestine research operations hosted by [[id:e68a5318-bd72-4c92-9f70-dcdbd59505d1][Azimuth Biochemicals]]
and protected by the notorious [[id:42b6a882-f396-4017-87de-9080d6291940][Black Flight]].

More updates will be provided as the story develops.
