:PROPERTIES:
:ID:       9d811045-5454-40af-bc23-76947d19aafd
:END:
#+title: Brewer Corporation to Fund Survey Initiative
#+filetags: :3311:galnet:
* Brewer Corporation to Fund Survey Initiative

/30 Jan 3311/

A new planetary survey initiative has been announced by [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer
Corporation]], calling for pilots to scan locations around the core
systems.

Following the recent deployment of the megaship [[id:454c41b7-95ca-4e7e-94d4-c8a3f9d61d0e][Trailblazer Echo]], CEO
[[id:0a249cc4-6f5d-4467-bf34-d6419b838581][Madelyn Teague]] made the following announcement from the megaship’s
bridge:

“Recent events have accelerated plans to explore a new age of system
colonisation efforts. Brewer Corporation has proudly supported
ambitious projects such as the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]], and worked with other
corporations to improve and increase starports across the galaxy. Now
we take another step forward in the continued march across the stars.”

“[[id:2fb00d7f-7234-45fa-8e3c-af685aa8f0d8][Universal Cartographics]] has partnered with us to collect, analyse and
process the very latest exploration data, to help calibrate our
metrics for optimal colonisation targets.”

Brewer Corporation, which constructs [[id:dfcd3273-3589-4725-a75f-5f1a08adc662][Coriolis]] and [[id:d5cc8c3e-9887-4c30-9a1d-08008ab36675][Orbis]] starports, has
supported localised expansion efforts in the past. But, until today,
it had given shareholders no sign that it would endorse widespread
colonisation plans.

Some media analysts have claimed that Brewer Corporation has been in
significant talks with superpower lobbyists in recent weeks, which
could explain the change of heart. The level of influence the
superpowers had on this announcement is unconfirmed.

Explorers who wish to contribute to the initiative can hand in
exploration data to the Trailblazer Echo in the [[id:0a9dd112-c2a6-47d8-9056-a334912820bf][HIP 90578]]
system. Contributions will be valued by thoroughness, with full FSS
scans and planetary probing completions rewarded higher.
