:PROPERTIES:
:ID:       ab97ccc2-bf08-43f5-8af6-69770170a595
:ROAM_REFS: file:../references/Community%20Goals/Protecting_Traders_in_Zlota.md
:END:
#+title: Community Goal: Protecting Traders in Zlota
#+filetags: :CommunityGoal:3304:Federation:

* Location

Nusslein-Volhard Settlement | Zlota

* Objective

Hand in Bounty Vouchers

* Progress

Tier 4/8

* Contributors

3,325

* Contributions

4,294,967,295

* End

13 Dec 2018, 3:58pm

* Status

Finished

An obscure cult based in the Zlota system has requested a range of rare
items for an arcane ceremony.

A handwritten statement from Barnabas Cole, leader of a group named the
Children of Tothos, was submitted to the media:
This is the rite that will unmask us and allow us to see the path -- the
path we will all take, together, toward freedom.

Zlota Federal Holdings, which is thought to have some connection to the
cult, has requested various rare goods to be delivered to
Nusslein-Volhard Settlement in the Zlota system. It has also placed a
kill order on all ships on its wanted list, to protect those delivering
these rare commodities.

Notice: In the system Turberamoan is a Haz Res onsite the planet 5.
Distance ca. 1,7k ls. The Bounties of the (federal party) LTT 4696
League are counted by the CG.
