:PROPERTIES:
:ID:       12836b42-5708-4787-a3d1-534d3e449051
:ROAM_REFS: file:../references/Community%20Goals/Arming_Colonia.md
:END:
#+title: Community Goal: Arming Colonia
#+filetags: :CommunityGoal:3304:Thargoid:Colonia:

* Location

Gold Hub | Arek

* Objective

Earn rewards by delivering [[id:6f8b14ec-06ee-4f36-b646-15146a0ca81b][Battle Weapons]], [[id:85a9f73a-636f-459f-8a46-d93b1a3dca16][Reactive Armour]] and [[id:2b461b7b-10e3-49fd-ba61-bce15a046809][Landmines]]

* Progress

Tier 3/8

* Contributors

3,781

* Contributions

4,952,295

* End

08 Mar 2018, 3:59pm

* Status

Finished

The Arek Crimson Vision Corporation has launched a campaign to boost
[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]'s military strength by providing the region with weapons. The
initiative is a direct response to ongoing Thargoid hostility.

A spokesperson for the organisation elaborated on the nature of the
campaign:

"Several members of our organisation have friends and family in
[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]], so we've decided to divert some cash into protecting the
region. If the Thargoids come knocking, we don't want the people of
[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] to be caught with their pants down."

The Arek Crimson Vision Corporation has placed an open order for a range
of weapons, and has promised to reward pilots who deliver the requested
goods to Gold Hub in the Arek system.

The campaign begins on the 1st of March 3304 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.
