:PROPERTIES:
:ID:       53771f66-2fc5-4fdb-9347-c16af0eb23f6
:ROAM_REFS: file:../references/Community%20Goals/Oppose_the_Sirius_Alliance_Defense_Pact.md
:END:
#+title: Community Goal: Oppose the Sirius-Alliance Defense Pact
#+filetags: :CommunityGoal:3308:Alliance:Thargoid:

* Location

Preuss Terminal | [[id:25537b36-1d83-4354-afeb-482bf891d85d][Di Jian]]

* Objective

Deliver [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]], [[id:1f762d71-c751-461c-a308-f2e33862e748][Synthetic Reagents]] and Reinforced Mounting
Plate

* Progress

Tier 2/5

* Contributors

1,725

* Contributions

14,553,754/79,000,000 (18.42%)

* End

23 Jun 2022, 7:00am

* Status

Finished

The [[id:25537b36-1d83-4354-afeb-482bf891d85d][Di Jian]] system is hosting competing campaigns as the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]]
Assembly votes on the strategic defence pact.

The Assembly is evenly split over formalising military ties with [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation to enhance defensive options against the Thargoids, with a
decision expected at the end of June. In advance of the vote, both
pro-pact and anti-[[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] councillors are attempting to sway colleagues
to their cause by securing a sizeable resource package for the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]]
Defence Force.

The anti-[[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] lobby has requested deliveries asking for shipments of
computer components, reinforced mounting plates and synthetic reagents
to Preuss Terminal in the [[id:25537b36-1d83-4354-afeb-482bf891d85d][Di Jian]] system. The system's controlling
faction, [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]'s Salutis Aeternum, is overseeing contributions. Engineers
[[id:132a80d4-8dcb-46d5-bb30-7621c30f9d5c][Uma Laszlo]] and [[id:f3426d7a-dfd4-4e6c-8f29-f53c7e31d071][Bill Turner]] have both expressed a hope that the anti-xeno
pact with [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] is denied.

To encourage support from pilots, [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]]'s Salutis Aeternum is offering a
stock [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] Chieftain to the top 25 Preuss Terminal campaign
contributors only. Other rewards are available for contributors outside
this number.

Top 75%: [[id:5c4e0227-24c0-4696-b2e1-5ba9fe0308f5][Alioth]] Permit
Top 50%: Access to [[id:f3426d7a-dfd4-4e6c-8f29-f53c7e31d071][Bill Turner]]'s Workshop
Access to [[id:132a80d4-8dcb-46d5-bb30-7621c30f9d5c][Uma Laszlo]] Workshop
Top 25 CMDRs: [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] Chieftain

The campaign will run until the 23rd June 3308. If the final target is
met earlier than planned, or the opposing campaign is completed first,
the campaign will end immediately.
