:PROPERTIES:
:ID:       89b41b6e-5981-4e4e-b14b-916f8201b7dc
:ROAM_REFS: file:../references/Community%20Goals/The_Lave_Radio_Conference.md
:END:
#+title: Community Goal: The Lave Radio Conference
#+filetags: :CommunityGoal:3304:Thargoid:

* Location

[[id:10b9df10-b4c7-449a-9c50-4ad011256417][Lave Station]] | [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]]

* Objective

Deliver Power Converters, Energy Grid Assemblies and [[id:34acf2f1-676d-4e52-86f4-80dc606e435c][Power Generators]] to
[[id:10b9df10-b4c7-449a-9c50-4ad011256417][Lave Station]] in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] system.

* Progress

Tier 4/8

* Contributors

2,954

* Contributions

8,670,374

* End

14 Jun 2018, 4:33pm

* Status

Finished

The [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio Network, an independent organisation based in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]]
system, has announced plans to broadcast its annual conference, which
this year will take place in the [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] system from the 24th to the 25th
of June.

To ensure they can share the event with the entire galaxy, the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]]
Radio Network has placed an open order for various commodities, and has
promised to reward pilots who deliver these commodities to [[id:10b9df10-b4c7-449a-9c50-4ad011256417][Lave Station]]
in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] system.

But not everyone is enthusiastic about the event. The [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Jet Family
has responded with a rival campaign expressly designed to undermine the
[[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] Radio initiative, and has invited pilots to deliver commodities to
help construct a signal jammer.

The two organisations have set out week-long operations to achieve their
aims, which will begin on the 7th of June 3304.

To be eligible for rewards you must sign up as an active participant
before delivering Power Converters, Energy Grid Assemblies and Power
Generators to [[id:10b9df10-b4c7-449a-9c50-4ad011256417][Lave Station]] in the [[id:ff595332-6a13-4f69-ae2f-cc0a0df8e741][Lave]] system.

Be aware that faction-state changes, [[id:8ddf8e00-4541-4857-a609-5f6c5849dded][Thargoid Sensor]]-related
interference and other disruptive events can negatively impact markets
and station services, and could prevent the initiative from running
smoothly.
