:PROPERTIES:
:ID:       6b05a9c9-8a5f-4479-9a18-620f99d0002f
:ROAM_REFS: file:../references/Community%20Goals/Defending_Traders_in_Narri.md
:END:
#+title: Community Goal: Defending Traders in Narri
#+filetags: :CommunityGoal:3304:Thargoid:

* Location

[[id:958d3b04-bbb5-4d7e-b0f0-0208abfea93c][Bobko City]] | Narri

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 8/8

* Contributors

7,849

* Contributions

4,294,967,295

* End

09 May 2018, 8:22pm

* Status

Finished

The [[id:058a658d-e1ce-4364-a92b-b9607495c73f][Utopia]] commune has launched a project to build a military
installation in its home system to defend the [[id:83b3ed4c-f0b1-4311-a4df-34bdfa742126][Sim-Archive]] from potential
Thargoid attack.

Dr [[id:78f7348c-44af-40bf-8f60-ff0e4d3425d0][Leigh Constantinides]], a spokesperson for [[id:058a658d-e1ce-4364-a92b-b9607495c73f][Utopia]], made this
announcement:
Following recent observations by the respected strategist Marquis
Novantico, we accept that the [[id:83b3ed4c-f0b1-4311-a4df-34bdfa742126][Sim-Archive]] requires increased protection
to prevent its knowledge from falling into the wrong hands. Our partner
organisation, the Narri Justice Party, is therefore overseeing the
construction of a new security installation. We beseech the galactic
community to support this worthy endeavour.

To support this initiative, the Narri Justice Party has launched an
appeal for various construction materials. To protect traders delivering
goods to [[id:958d3b04-bbb5-4d7e-b0f0-0208abfea93c][Bobko City]], they have placed a kill order on all ships on its
wanted list operating in the system.
