:PROPERTIES:
:ID:       2660eeb5-0a3d-46fb-b927-6404d975f6ff
:END:
#+title: Migration and Economic Boom in Newly Colonised Systems
#+filetags: :3311:galnet:

* Migration and Economic Boom in Newly Colonised Systems

/30 Apr 3311/

Migrants are flocking from the core systems to begin new lives in the
thousands of recently established colonies.

A wave of independent [[id:d1f19609-fdb7-4991-bcb2-e93435f013d0][colonisation]]
efforts over the past few months have increased human territory
considerably. While many of these star systems have been classified as
‘waypoints’, with singular docking outposts for journeys between systems
with wider infrastructure, a significant number have been expanded with
multiple starports and settlements.

It is these that billions of people are now heading towards in the hope
of starting fresh. Workers and their families are starting to arrive in
large numbers, bringing with them a major boost to economic output.

With the influx of population, the new colonies will be more capable of
producing their own colonisation-related commodities, with economies now
driven by linking installations and markets placed throughout the
system. Analysts believe that, over time, this ability to self-sustain
expansion efforts will prove vital if the colonies are to be successful
in the long term.

Professor [[id:38f84d9a-08fd-41fe-a514-85fd8854ec73][Irene Ralston]], head
of political history at
[[id:f0ff8ab8-beec-480c-9b04-41279c11a1ee][Olympus Village University]], wrote
for [[id:be5df73c-519d-45ed-a541-9b70bc8ae97c][The Federal Times]]:

“It is fair to say that, in terms of scale, this is the largest
migration event in human history. This migration appears to be fuelled
by a hope for a new chapter — the chance to become part of a ‘new
frontier’. No doubt the upheaval of the recent
[[id:9a246121-0c2e-4f21-9877-ee333d6b0d6c][Second Thargoid War]] had some
influence in the decision making, but the sheer numbers involved are
fascinating.”

It is expected that, when economies and populations begin to settle,
[[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]]’s
[[id:454c41b7-95ca-4e7e-94d4-c8a3f9d61d0e][Trailblazer fleet]] of megaships
which currently supply many colonies will be repurposed for other
duties.

[[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] also revealed
that it has prepared a variety of custom layouts and decorative suites,
allowing [[id:2547515c-389e-450d-893c-435b62436fc4][system architects]] to
visually tailor their new constructions. This latest innovation from
the industrial giant is available for deployment from today.
