:PROPERTIES:
:ID:       76bb20f0-8d46-416f-a832-534ef60a69a0
:ROAM_REFS: file:../references/Community%20Goals/Fight_for_the_Silver_Legal_Group.md
:END:
#+title: Community Goal: Fight for the Silver Legal Group
#+filetags: :CommunityGoal:3307:Federation:

* Location

[[id:e65ce81f-ab99-4166-9d96-8315e4f762dc][Iron Wings of Justice]] | [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]]

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for [[id:46db368a-cb8f-4246-9663-96bd2d3b0402][Silver Legal Group]] in Conflict
Zones​

* Progress

Tier 2/5

* Contributors

12,610

* Contributions

139,328,705,339/600,000,000,000 (23.22%)

* End

17 Feb 2021, 7:00am

* Status

Finished

[[id:a35c5eb2-0697-4ef3-9a11-950791952e2d][Jupiter Division]] ships have engaged in battle with rival Federal vessels
in the [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]] system.

Loyalists to former [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] CEO [[id:c33064d1-c2a0-4ac3-89fe-57eedb7ef9c8][Jupiter Rochester]] have built their
own breakaway faction in [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]]. The FIA suspects that Jupiter
Division agents first infiltrated the [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]] Gold Universal Group
years ago, and permit locked the system to conceal their efforts to
overtake it from within.

Director [[id:98555862-d2af-4b4a-be86-672f289e1b73][Theodore Sullivan]] of the [[id:46db368a-cb8f-4246-9663-96bd2d3b0402][Silver Legal Group]] announced:

"We will not tolerate these criminals illegally controlling this
system. Once victory is won, the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] will be able to bring
Rochester to justice."

The [[id:46db368a-cb8f-4246-9663-96bd2d3b0402][Silver Legal Group]] has asked Federal auxiliaries to support its
efforts to degrade [[id:a35c5eb2-0697-4ef3-9a11-950791952e2d][Jupiter Division]]'s military force by handing in
[[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at the [[id:e65ce81f-ab99-4166-9d96-8315e4f762dc][Iron Wings of Justice]] megaship in the [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]]
system.

The Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] has agreed to supply all ships participating in
this conflict with temporary permits to access [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]]. These will
expire early on Thursday the 18th of February. However, neither
permanent nor temporary system permits apply to fleet carriers, since
they are capable of ferrying vessels which could evade detection and
authorisation.

If victorious, each tier beyond Tier 1 will provide a 5% reduction to
outfitting at Northrop Enterprise in [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]] to those with access to
the system, lasting for one month starting on Friday the 19th of
February 3307.

The top 75% of contributors will be allocated a permanent system permit
for [[id:e1b0c446-0ced-475c-9031-a57e5e3c414f][HIP 54530]] by Friday the 19th of February 3307.

Early on Thursday the 18th of February 3307, the [[id:e65ce81f-ab99-4166-9d96-8315e4f762dc][Iron Wings of Justice]]
megaship controlled by the [[id:46db368a-cb8f-4246-9663-96bd2d3b0402][Silver Legal Group]] will move to the Ts'ao
Tach system. If victorious, it will be authorised to issue permanent
system permits to those who meet their requirements.

The two factions have set out six-day campaigns, which will end early on
Wednesday the 17th of February 3307.
