:PROPERTIES:
:ID:       77116244-1011-4933-a236-25e502d7e23b
:ROAM_REFS: file:../references/Community%20Goals/More_bang_for_buck.md
:END:
#+title: Community Goal: More bang for buck
#+filetags: :CommunityGoal:3302:

* Location

Buckey Hub | Cherets

* Objective

Earn Rewards by delivering [[id:9368cc59-3e4d-4693-b5a7-e28b72c03da7][Anduliga]] Fireworks to Buckey Hub in the
Cherets system. Find the Fireworks @ [[id:53a0db77-20c6-48ca-9b60-1b6b2c64f153][Celsius Estate]] - [[id:9368cc59-3e4d-4693-b5a7-e28b72c03da7][Anduliga]]

* Progress

Tier 5/5

* Contributors

2,947

* Contributions

0

* End

04 Jan 2016, 9:10am

* Status

Finished

To celebrate the new year- a tradition from [[id:5b0f485f-4793-468d-a1a1-483606f44e0e][Earth]]'s ancient past- the
Independent Cherets Labour has issued a request for [[id:9368cc59-3e4d-4693-b5a7-e28b72c03da7][Anduliga]] Fireworks
to help make sure they see out 3301 with a bang. The Fireworks, which
can only be purchased at [[id:53a0db77-20c6-48ca-9b60-1b6b2c64f153][Celsius Estate]] in the [[id:9368cc59-3e4d-4693-b5a7-e28b72c03da7][Anduliga]] system and are
to be delivered to Buckey Hub in the Cherets system will be part of a
series of system wide firework displays.

- Buckey Hub has Large landing pads

- [[id:53a0db77-20c6-48ca-9b60-1b6b2c64f153][Celsius Estate]] has NO!! large landing pads and is 600,000 ls from the
beacon.

5% - 15,000,000
15%- 10,000,000
30% - 7,500,000
60% - 5,000,000
90% - 2,500,000
100% - 500,000
