:PROPERTIES:
:ID:       6a32474a-c2a5-4c8d-97b5-225bb2c84391
:ROAM_REFS: file:../references/Community%20Goals/Preparing_For_Repairs___Work_Dammit.md
:END:
#+title: Community Goal: Preparing For Repairs - Work Dammit
#+filetags: :CommunityGoal:3301:

* Location

Hudson Dock | BD+03 2338

* Objective

Sell Metals to Hudson Dock

* Progress

Tier 3

* Contributors

490

* Contributions

0

* End

26 Mar 2015, 3:00pm

* Status

Finished

[[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] has been put in the deeply embarrassing position of having
to further postpone the maiden voyage of the FNS Nevermore.
Representatives of [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] have confirmed that this most recent
delay is due to faulty sensor and turret targeting arrays.

The faults first came to light when engineers began running the FNS
Nevermore through its standard weapon diagnostic checks late last week.
According to [[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]], the FNS Nevermore's weapon systems gave
engineers the all clear, but upon attempting to fire on the target [[id:dd5c81e6-b181-445f-a15d-45fe9a788561][drone]]
ship, the FNS Nevermore instead released a massive volley into Hudson
Dock. The dock's defence systems then returned fire, causing the
Nevermore's automated battle systems to kick in, resulting in an
all-out fight between the two stellar titans.

It took engineers three hours to regain control of the ship. During this
time dozens of people were killed, and hundreds of millions of credits
in damages were done to both structures.

[[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] is now looking for traders to help bring a variety of
Metals to Hudson Dock to assist in the repair efforts.
