:PROPERTIES:
:ID:       ce8c6e54-f463-4304-9c30-b80eac5229d6
:ROAM_REFS: file:../references/Community%20Goals/Protecting_Traders_in_the_Zavijah_System.md
:END:
#+title: Community Goal: Protecting Traders in the Zavijah System
#+filetags: :CommunityGoal:3304:Alliance:Thargoid:

* Location

Wheelock Ring | Zavijah

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 5/8

* Contributors

4,574

* Contributions

4,294,967,295

* End

06 Sep 2018, 3:56pm

* Status

Finished

The Thargoid-worshipping sect that reveres an entity known as the 'Far
God' has issued a request for Thargoid materials.

Chancellor [[id:95ef16fb-42db-4eb4-8f8b-816d2be4ddd0][Reegan Tanner]], speaking on behalf of the LHS 2541 [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]]
Combine, which is supporting the campaign, released the following
statement:
To maintain their privacy and avoid further persecution, members of the
[[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] sect have approached us to facilitate the collection of Thargoid
materials. They have made it explicit that these materials will be
revered as objects of worship, and will not be used as part of any
xenobiological experiments. In the interests of religious freedom, we
have decided to fulfil their request.

In support of this campaign, the [[id:eca6d498-8664-43f8-9db7-ec9bf38a50b1][LHS 2541 Alliance Combine]] has placed a
kill order on all ships on its wanted list, to ensure that those
delivering commodities to Wheelock Ring can do so safely.
