:PROPERTIES:
:ID:       7b4751f6-1880-4afb-a288-d979056fa845
:ROAM_REFS: file:../references/Community%20Goals/Protect_Deliveries_for_Neomedical_Industries.md
:END:
#+title: Community Goal: Protect Deliveries for Neomedical Industries
#+filetags: :CommunityGoal:3307:Alliance:

* Location

Crippen Port | Haithis

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]​

* Progress

Tier 2/5

* Contributors

1,733

* Contributions

34,269,573,292/80,000,000,000 (42.84%)

* End

09 Sep 2021, 7:10am

* Status

Finished

[[id:d8c4bbec-5bea-43d7-bad6-0ec97600cac3][Neomedical Industries]] has requested deliveries to produce onionhead
gamma strain for [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] and independent systems.

The new variant of the popular psychedelic drug is currently sold in a
handful of independent systems by the [[id:1dfc7c53-642a-4404-a8e8-16a8cc18482a][Kumo Crew]] syndicate. The IHO has
confirmed that the product does have many medical applications.

[[id:5e42db2b-b180-4e0a-af3a-dd5dcd45cf28][Olwyn Kendrick]], CEO of [[id:d8c4bbec-5bea-43d7-bad6-0ec97600cac3][Neomedical Industries]], outlined the initiative:

"Our goal is to gather sufficient resources for the manufacture of
onionhead gamma strain as a medicinal treatment. Target markets will
include both independent and [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] systems, should enough commodities
be delivered."

"Security experts have advised that criminal elements may try to
disrupt this project. Therefore we are offering bounty vouchers on all
wanted ships to protect these deliveries. Reimbursements will be
arranged by our corporate partner, Haithis Purple Dynamic Group."

To help protect [[id:d8c4bbec-5bea-43d7-bad6-0ec97600cac3][Neomedical Industries]]'s initiative, hand in Bounty
Vouchers at Crippen Port in the Haithis system.

As well as credits, the following rewards are on offer:

The top 75% of contributors will receive the [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] 1 decal.
The top 50% of contributors will also receive the [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] 2 decal.
The top 25% of contributors will also receive the [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] 3 decal.
The top 10% of contributors will also receive the [[id:83299a14-b6b0-4670-ba39-2914e05ed2f5][Cobra Mk III]] [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]]
skin.

The campaign begins on the 2nd of September 3307 and will run for one
week. If the final target is met earlier than planned, the campaign will
end immediately.
