:PROPERTIES:
:ID:       6df5857e-f1f6-4d9c-aa3d-948a12fc3a58
:ROAM_REFS: file:../references/Community%20Goals/Appeal_for_Toxandji_Virocide.md
:END:
#+title: Community Goal: Appeal for Toxandji Virocide
#+filetags: :CommunityGoal:3302:

* Location

[[id:a443f49b-b347-4aec-8e3d-96932a23046d][Wright City]] | [[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]]

* Objective

Earn rewards by delivering [[id:1c68e942-6f27-44f7-a8a5-b458c544a9fd][Toxandji Virocide]] to [[id:a443f49b-b347-4aec-8e3d-96932a23046d][Wright City]] in the [[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]]
system

* Progress

Tier 6/8

* Contributors

1,702

* Contributions

0

* End

10 Nov 2016, 4:46pm

* Status

Finished

A mysterious organisation known as [[id:8ec6df28-592d-4db6-bc07-84ab2a3882ec][Revolution Incorporated]] has issued an
appeal for [[id:1c68e942-6f27-44f7-a8a5-b458c544a9fd][Toxandji Virocide]], a rare pesticide.

The chemical is commonly used in industrial-scale agriculture, and can
be 'programmed' to target specific parasites.

The reason for the request is not clear, but [[id:8ec6df28-592d-4db6-bc07-84ab2a3882ec][Revolution Incorporated]] has
promised to generously reward those who deliver the requested commodity
to [[id:a443f49b-b347-4aec-8e3d-96932a23046d][Wright City]] in the [[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]] system.

The campaign begins on the 5th of November 3302 and will run until the
10th of November 3302. If the final target is met earlier than planned,
the campaign will end immediately.

To be eligible for rewards you must sign up as an active participant
before delivering [[id:1c68e942-6f27-44f7-a8a5-b458c544a9fd][Toxandji Virocide]] to [[id:a443f49b-b347-4aec-8e3d-96932a23046d][Wright City]] in the [[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]] system.

The project is scheduled to run for one week, but if the final target is
met earlier than planned the campaign will end immediately.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

Current Global Progress: 105,305 tones collected

Current Participation Rewards:
Top 10 CMDRs: 14,688,000 CR
Top 10%: 11,750,400 CR
Top 25%: 8,812,800 CR
Top 50%:5,875,200 CR
Top 75%:2,936,600 CR
Top 100%: 600,000 CR

[Notes:\\\\](Notes:\\)

-   Toxiandji Virocide is available only from [[id:27737d4e-aaa5-40e5-89a7-0ea3814f1992][Tsunenaga Orbital]] ( 7,749
    Ls

from main star, Large pads available) in [[id:2ba6f216-ed6d-4b05-9b5f-ab42c938df0d][Toxandji]] (116.8 Ly from [[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]]);

- To sign up for the Appeal For [[id:1c68e942-6f27-44f7-a8a5-b458c544a9fd][Toxandji Virocide]] CG, you need to go to
[[id:b555bc13-0686-4eb7-b73f-a1116908fad9][Elli]] \[[[id:a443f49b-b347-4aec-8e3d-96932a23046d][Wright City]]\] to be able to see & sign up for this CG at that
stations Mission Board.
