:PROPERTIES:
:ID:       f0a640d6-c020-43e9-b887-c4e2d1f768aa
:ROAM_REFS: file:../references/Community%20Goals/Colonia_Bridge_Project_Third_Phase___Colonia.md
:END:
#+title: Community Goal: Colonia Bridge Project Third Phase - Colonia
#+filetags: :CommunityGoal:3308:Colonia:

* Location

[[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]] | [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]

* Objective

Deliver [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]], [[id:0b64653e-4cad-4f00-bf49-d88ae6049a11][Ceramic Composites]] and Thermal Cooling
Units

* Progress

Tier 1/2

* Contributors

1,406

* Contributions

5,784,671/100,000,000 (5.78%)

* End

13 Jan 2022, 7:02am

* Status

Finished

[[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] intends to improve the travel corridor between the
[[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] and [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] systems by constructing several new starports.

The previous two phases of the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] project established
stationary megaships in 56 systems. These provide rest, refuel and
repair facilities for vessels making the 22,000 light year journey to
and from the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] region.

A press release from [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] outlined this latest
initiative:

"Phase three aims to enhance the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] by building permanent
starports in key locations along the route. These will offer a wide
range of services to travellers, and also serve as homes for the many
new communities that we expect to spring up around them."

"Our plan is to construct one starport in the vicinity of [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]. The
starport structure will be assembled by the 27th of January, with
additional services scheduled for implementation at a later date."

"Pilots are asked to deliver ceramic composites, computer components
and thermal cooling units to [[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]] in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system."

"Should deliveries reach sufficient levels, the top 75% of contributors
will be awarded an engineered frame shift drive with increased range and
faster boot sequence. These will be placed in storage at [[id:f37f17f1-8eb3-4598-93f7-190fe97438a1][Jaques]]
Station."

The highest contributor in [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] will be invited to submit naming
suggestions for the new starport. Name submissions will be subject to
review by the [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] board of directors.

Achieving the first tier target will enable [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] to begin
construction of a starport close to the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system. All three module
reward classes will be made available at this tier.

Tier 1: One starport husk Modified 3A 4A and 6A Frame Shift Drives
Tier 2: All additional commodities delivered will count toward personal
contribution totals

The campaign begins on the 6th of January 3308 and will run for one
week.
