:PROPERTIES:
:ID:       0d91b3f5-ef47-4b2a-9519-68e681df8c85
:ROAM_REFS: file:../references/Community%20Goals/Federal_Initiative_for_Golconda_Outpost.md
:END:
#+title: Community Goal: Federal Initiative for Golconda Outpost
#+filetags: :CommunityGoal:3305:Federation:Empire:

* Location

Keller's Resolve | [[id:361a46f2-79c4-40bf-9781-4066763914f3][Upaniklis]]

* Objective

Deliver [[id:87f58744-f7fe-46da-b824-fb089a150705][Polymers]], CMM Composites, [[id:d727fb19-8dc0-4d94-bcd4-da1cb5c090f0][Titanium]], [[id:bd0fe4ab-145e-431c-b06e-3433e2618bff][Beryllium]] and [[id:cf391eb1-f332-4044-9bc6-814ca24c52b1][Thallium]]

* Progress

Tier 8/8

* Contributors

3,828

* Contributions

15,000,061

* End

22 Nov 2019, 11:51pm

* Status

Finished

[[id:1047d7bb-a08d-430d-a445-4ec9a1b2daa3][The Empire]] and the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] have announced rival initiatives to
provide a new home for the crew of the generation ship [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]].​
​
During the aid appeal by [[id:f3e9c36a-0e5d-493b-8fff-b86cdb2a3dcb][Upaniklis Vision Incorporated]], engineering
experts confirmed that the ancient vessel can no longer meet the
colony's needs. While the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]] was designed for long-term
habitation, it lacks adequate facilities for the current population
levels.​
​
After lengthy discussion, the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]'s leaders have reluctantly
decided to abandon the vessel. But the ship's captain, Jonathon
Forester, has insisted that its population remain together in one
location.​
​
The [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] has taken the approach of offering to create an outpost
where the [[id:fce1d147-f900-41ec-a92c-3ce3d1cae641][Golconda]]'s spacefaring traditions can continue. This was
outlined by Congressman [[id:5b4096e4-1099-475e-8e2a-03376015d895][Harlan Turk]]:​

"These people have the inalienable right to continue their current way
of life. A modern outpost will offer vastly superior amenities while
allowing their culture to remain intact, with facilities for new trade
relationships within Federal market guidelines."

The [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] has asked the galactic community to support their
campaign. Pilots can deliver polymers, CMM composites, titanium,
beryllium and thallium to the megaship Keller's Resolve in the
[[id:361a46f2-79c4-40bf-9781-4066763914f3][Upaniklis]] system​
