:PROPERTIES:
:ID:       d4101f08-3f90-4f39-97bc-e97d931675e9
:ROAM_REFS: file:../references/Community%20Goals/Conflict_in_Hehe___Corporate__Combat_.md
:END:
#+title: Community Goal: Conflict in Hehe - Corporate (Combat)
#+filetags: :CommunityGoal:3303:Federation:

* Location

Rutherford Hub | Hehe

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for Hehe Federal Interstellar in
conflict zones

* Progress

Tier 8/8

* Contributors

9,316

* Contributions

0

* End

09 Aug 2017, 8:59pm

* Status

Finished

Description

Authorities in the Hehe system have reported that conflict has erupted
between Hehe Federal Interstellar and Hehe Camorra. System security
forces have confirmed that the fighting began several hours ago and has
escalated rapidly since then.

The conflict is understood to be territorial in nature, with both
factions eager to take control of Hehe. The Hehe Federal Interstellar
has issued a call for support, and have pledged to reward combat pilots
who rally to its cause.

The faction has set out week-long operations to take control of the
system, which will begin on the 3rd of August 3303.

To be eligible for rewards you must sign up as an active participant
before handing in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Rutherford Hub in the Hehe system.

Please note that if you have any crew members, a portion of your combat
bonds will be automatically assigned to them. These combat bonds will
not count towards your personal contribution total, and your crew will
receive the reward for their bonds when they are handed in. The
proportion of combat bonds assigned to your crew will depend on their
rank.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)
- Competing with Hehe Camorra CG (if one finishes early, both goals end
and the loosing side gets paid at their current tier)
- [[id:4ed9ac75-9ddc-4533-bc21-00a775fbc0ee][Powerplay]]: [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] control system
- Station services:
Commodities Market, Shipyard, Outfitting, Repair, Restock, Refuel, Black
Market
- Available CZs in system: HEHE A 1 A (High Intensity)
Will be added as reported in the thread

- PvP: Even in the Mobius private groups, this is allowed within the
conflict zones
- Remember folks, all evidence to the contrary, this is no laughing
matter - pilots, grab your guns!
