:PROPERTIES:
:ID:       e7f6abd5-64a9-4247-b203-2950d8516d82
:ROAM_REFS: file:../references/Community%20Goals/Zosi_Major_Corporation_Issues_Request__Materials___Data_.md
:END:
#+title: Community Goal: Zosi Major Corporation Issues Request (Materials & Data)
#+filetags: :CommunityGoal:3302:

* Location

Citi Enterprise | Zosi

* Objective

Deliver [[id:24b2d77a-a699-4a0d-ae27-3754e2130101][Thermic Alloys]], [[id:98454801-e9ab-4ec7-b930-cc3d66911636][Chemical Manipulators]] and Cracked Industrial
Firmware

* Progress

Tier 4/8

* Contributors

1,426

* Contributions

0

* End

18 Nov 2016, 1:42am

* Status

Finished

[[id:38f26d86-43fb-4de8-a212-388dc5f3b752][Zosi Major Corporation]], an independent organisation based in the Zosi
system, has placed an open order for thermic alloys, chemical
manipulators and cracked industrial firmware. According to the
organisation's spokesperson, the resources will be used in an
unspecified research and development project.

Dr [[id:bbcc7637-001c-4185-a66c-53049c94e657][Arkady Cole]], the organisation's chief research scientist, released
the following statement:

"We want the resources, yes? Very useful to us. Process is simple.
Deliver the resources and be paid. Yes."

Despite the opaque nature of the request, it is likely the generous
reimbursements offered by the [[id:38f26d86-43fb-4de8-a212-388dc5f3b752][Zosi Major Corporation]] will ensure its
orders are met. Participating pilots have been instructed to deliver the
requested commodities to Citi Enterprise in the Zosi system.

The campaign begins on the 10th of November and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before delivering thermic alloys, chemical manipulators and industrial
firmware to Citi Enterprise in the Zosi system.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\) Where to find materials...
- [[id:24b2d77a-a699-4a0d-ae27-3754e2130101][Thermic Alloys]]: Ship salvage from combat ships, mission rewards
- [[id:98454801-e9ab-4ec7-b930-cc3d66911636][Chemical Manipulators]]: Ship salvage from transport ships, Surface
POIs
- [[id:fe68ebe2-a42c-4693-be35-73df6407432a][Cracked Industrial Firmware]]: Surface data points, mission rewards

Current Global Progress: 27,195 tonnes collected

Current Participation Rewards:
Top 10 CMDRs:13,953,600 CR
Top 10%: 11,628,000 CR
Top 25%: 9,302,400 CR
Top 50%: 6,976,800 CR
Top 75%: 4,651,200 CR
Top 100%: 700,000 CR
