:PROPERTIES:
:ID:       28c071ea-fe77-4c53-a041-fb32d7080a5d
:END:
#+title: A Light In The Black
#+filetags: :Tourist:beacon:
* 0640 A Light In The Black
[[id:9445759e-8ea4-497d-9d36-140bb7680f9a][Byao Ain GG-Y E7]]

Commander Sand dan Glokta suggests this gem for celestrial sightseeing: This [[id:7fec1142-ab20-47e1-b746-36edee889cc3][Earth-like]] planet is the furthest one above the galactic plane that I've found, and for an added bonus is in orbit about a neutron star.  It may be worthwhile mounting scientific expeditions to find out what sort of life-forms could survive in such a heavily irradiated environment as well as the mystery of how life managed to evolve on such a planet in the first place.  Furthermore it is way above the galactic plane so the chance of an extrasolar capture is very low, therefore it's likely that the planet became life-bearing after it fell into orbit about the neutron star.  Temperature, pressure and atmospheric oxygen are all tolerable for humans but radiation-proof clothing is strongly advised.
