:PROPERTIES:
:ID:       0703ca0a-abc9-4ac6-82a5-090b7884f731
:ROAM_REFS: file:../references/Community%20Goals/Evangeline_s_Elite_Expeditionary_Force_Appeal.md
:END:
#+title: Community Goal: Evangeline's Elite Expeditionary Force Appeal
#+filetags: :CommunityGoal:3305:Federation:

* Location

Chu City | Shana Bei

* Objective

Deliver [[id:94637eec-3dd2-478f-9f38-8930b96a15fe][Superconductors]], [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]] and Insulating Membranes

* Progress

Tier 4/8

* Contributors

2,010

* Contributions

7,919,365

* End

19 Jun 2019, 2:00pm

* Status

Finished

Evangeline's Elite Expeditionary Force has revealed plans to build a
megaship in the Shana Bei system.​
​
Archangel Evangeline, commander of the faction, made the following
announcement:​

"The successful construction of the megaship EFS Archangel will serve
not only the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] but the entire galactic community. EFS Archangel
will provide a hub for our military operations, allowing us to bring the
fight to our enemies and defend imperilled systems. Together, we will
make EFS Archangel a safe place to trade and share knowledge. Long live
humanity!"

​
To ensure completion of the project, the organisation has requested
[[id:94637eec-3dd2-478f-9f38-8930b96a15fe][Superconductors]], [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]] and Insulating Membranes from the
galactic community. Pilots who contribute these resources to the Force
at Chu City in Shana Bei will be rewarded at the conclusion of the
project.​
​
The campaign will take place between the 13th and 19th of June 3305. If
the final target is met earlier than planned, the campaign will end
immediately.​
