:PROPERTIES:
:ID:       5be08441-01b7-4dda-b516-7d75277ac9f4
:END:
#+title: Third Distant Worlds Expedition Requests Materials for Deep-Space Infrastructure Project
#+filetags: :3305:3312:galnet:

* Third Distant Worlds Expedition Requests Materials for Deep-Space Infrastructure Project

/08 Jan 3312/

The [[id:dbb9956e-5ae2-4c27-94f7-670f0a4719f9][Distant Worlds working group]] has issued a call for mined and manufactured materials to support the construction of a new deep-space facility, intended to aid future exploration of remote galactic regions far beyond established survey routes.

[[id:f1e8e9e3-3fcb-403f-ad6c-7c92d236d9ec][Hermine Delarue]], Executive Operative for [[id:51896752-85c1-4c4c-8fc0-814386d4447d][Deep Space Surveys]], stated:

“[[id:51896752-85c1-4c4c-8fc0-814386d4447d][DSS]] has longstanding experience in supporting large-scale exploration efforts, most notably the construction of [[id:1c6bdbbd-527a-4533-abac-81eade19c059][Explorers’ Anchorage]] during the [[id:f176c68d-cc7a-4db2-8305-81f6771c7e9f][Distant Worlds II]] initiative in 3305.”

“This new [[id:b1b57ce2-5c91-46b6-87aa-c3f1fa29838c][project]] focuses on preparing a remote site for long-range scientific operations. We aim to establish essential infrastructure for survey crews venturing into seldom-charted regions. Independent pilots are invited to help lay the foundations for the next era of deep-space discovery.”

[[id:8f462e69-bbdc-479f-95f6-4e2794069d6a][Timotheus Haddard]], quartermaster for an affiliated [[id:dbb9956e-5ae2-4c27-94f7-670f0a4719f9][Distant Worlds]] support carrier, added:

“Initial requirements centre on core construction needs. We’re currently prioritising [[id:1cbb99d3-bda9-462d-9314-51bab7c41e3c][bromellite]], [[id:34acf2f1-676d-4e52-86f4-80dc606e435c][power generators]] and [[id:3392ce5d-db80-4085-8821-57b2ec3ddf36][thermal cooling units]] to begin establishing the primary framework.”

All interested parties have been invited to head to [[id:8c06b988-9dc6-471b-9e10-42068f677353][Alrai]] and register at [[id:8be92ba6-94e2-4dfa-a6f8-7af69c0da9f3][Surveyor’s Reach]] before delivering the required commodities. [[id:51896752-85c1-4c4c-8fc0-814386d4447d][DSS]] are reportedly offering a class 5 pre-engineered cargo rack to project contributors.

The [[id:b1b57ce2-5c91-46b6-87aa-c3f1fa29838c][expedition]] itself begins on the 18th of January, and organisers have issued an open invitation to any Commanders that wish to join the adventure.
