:PROPERTIES:
:ID:       94e7768b-e3c8-4b7e-abf8-b598d73a378c
:ROAM_REFS: file:../references/Community%20Goals/Trouble_in_Maia___Imperial_Pilots.md
:END:
#+title: Community Goal: Trouble in Maia - Imperial Pilots
#+filetags: :CommunityGoal:3302:Federation:Empire:

* Location

[[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] | [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]

* Objective

Earn rewards by handing in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at [[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]
system

* Progress

Tier 8/8

* Contributors

1

* Contributions

0

* End

01 Nov 2016, 7:18pm

* Status

Finished

Earlier this month, the [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] entered [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] and
rapidly started cementing its presence in the system. In response, the
[[id:c8cf3da4-154e-49a2-98ff-039aaab3b1dd][Ant Hill Mob]] - [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]'s current controlling faction - launched an
offensive against the [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]].

With the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] having recently stationed a [[id:3146c49e-4aa8-4061-9ab2-1d9da2b0bff5][Farragut]]-class
Battlecruiser at [[id:43ff9480-fe9a-43a0-a6fb-edbdc1ef3d7d][Maia A 3]] a, there is speculation that the appearance of
the [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] represents an effort to bring [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]
under Federal control.

A spokesperson for the [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] gave a brief
statement:

"The [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] has every right to establish a
presence in [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]. If the [[id:c8cf3da4-154e-49a2-98ff-039aaab3b1dd][Ant Hill Mob]] wants a fight, it's going to get
it."

The [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] has appealed to the galaxy's Federal
pilots for help, promising to generously reward those who support their
operation.

The campaign will begin on the 27th of October 3302 and will run for one
week.

To be eligible for rewards you must sign up as an active participant
before handing in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at [[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]] system.

The [[id:268dd81e-54f9-447a-9a47-11b2f7242e81][Pleiades Resource Enterprise]] has set out week-long operation to
resist the [[id:c8cf3da4-154e-49a2-98ff-039aaab3b1dd][Ant Hill Mob]], but if either side is defeated before the end
of the week, the conflict will end immediately.

Please note that crew members will take a percentage cut of combat bonds
when they are handed in. This percentage is based on their rank and
their cut of the combat bonds will not count towards your community goal
contribution.

Global progress: 542,958,556 credits earned

\*\* COMPLETE \*\*

Current Participation Rewards:
Top 10 CMDRs: 4,500,000 CR
Top 10%: 3,600,000 CR
Top 25%: 2,700,000 CR
Top 50%: 1,800,000 CR
Top 75%: 900,000 CR
Top 99%: 400,000 CR
