:PROPERTIES:
:ID:       7547e096-0f81-401c-a472-9e77df526e58
:ROAM_REFS: file:../references/Community%20Goals/Deliver_Jewels_for_Imperial_Festivities.md
:END:
#+title: Community Goal: Deliver Jewels for Imperial Festivities
#+filetags: :CommunityGoal:3304:Empire:

* Location

Mackenzie Relay | Cemiess

* Objective

Deliver mined Rhodplumsite, Serendibite, Monazite, Musgravite,
Benitoite, Grandidierite, Bromellite and Alexandrite

* Progress

Tier 5/8

* Contributors

815

* Contributions

173,806

* End

27 Dec 2018, 3:58pm

* Status

Finished

Imperial senator Simone Leatrix has announced plans for a week of
revelry at her palatial residence on Capitol in the Achenar system.

The senator told the media:
We Imperials value the finer things, even during times of political
upset. So I intend to celebrate the end of the year with a sumptuous
party at my mountaintop retreat, which will be specially renovated for
the occasion.

To decorate the senator's residence for the festivities, the Cemiess
Imperial Society is coordinating deliveries of newly refined jewels to
the Cemiess system.
