:PROPERTIES:
:ID:       f6bd9446-e420-49b9-9c16-08de2fd1f335
:ROAM_REFS: file:../references/Community%20Goals/Medical_Supplies_for_Imperial_Starport_Bombing_Survivors.md
:END:
#+title: Community Goal: Medical Supplies for Imperial Starport Bombing Survivors
#+filetags: :CommunityGoal:3307:Empire:

* Location

Mackenzie Relay | [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]]

* Objective

Deliver [[id:1c200888-6acc-404b-8d9e-9ad834389782][Basic Medicines]] and [[id:5af29dcf-3079-46c2-a594-d2559c830744][Advanced Medicines]]

* Progress

Tier 3/5

* Contributors

9,584

* Contributions

39,253,955/96,000,000 (40.89%)

* End

25 Mar 2021, 6:59am

* Status

Finished

Safeguard Interstellar requires deliveries of medicines to treat
casualties from the NMLA's recent terrorist attack.

CEO [[id:ad2a739e-6229-4c8b-8ab1-f4375f5dbcc1][Noel Beaumont]] announced:

"Hundreds of thousands of civilians still require urgent medical
attention after being evacuated from the damaged stations. Many have
severe caustic burns inflicted by the corrosive enzyme payload of the
explosives. We have already exhausted the majority of supplies in nearby
systems."

"To reinforce overstretched health services, we request shipments of
basic medicines and advanced medicines. These can be delivered to
Mackenzie Relay in the [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] system."

Safeguard Interstellar has partnered with [[id:d5617bfc-ed9f-4b4c-9bf1-6143fb9f7068][Lavigny's Legion]] to reward
pilots and distribute the medicines.

If Tier 1 is reached, the top 75% of participants will receive a
permanent [[id:bed8c27f-3cbe-49ad-b86f-7d87eacf804a][Achenar]] system permit and a fully engineered class 3 rating A
Shield Generator with thermal and kinetic resistance. The module will be
placed in storage at Mackenzie Relay in the [[id:360ae21e-63f2-43ba-a2fd-a47e5e49951e][Cemiess]] system by the 26th
of March 3307.

The joint initiative will run for one week. If the final target is met
earlier than planned, the initiative will end immediately.
