:PROPERTIES:
:ID:       0316dd0c-df71-47f6-b095-a7926c7966f7
:ROAM_REFS: file:../references/Community%20Goals/Defend_Tekkeitjal_from_the_Thargoids.md
:END:
#+title: Community Goal: Defend Tekkeitjal from the Thargoids
#+filetags: :CommunityGoal:3308:Federation:Thargoid:

* Location

Riemann Colony | Tekkeitjal

* Objective

Hand in Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] Combat bonds from destroying Thargoid ships

* Progress

Tier 7/8

* Contributors

2,497

* Contributions

488,575,333,238/550,000,000,000 (88.83%)

* End

22 Sep 2022, 7:59am

* Status

Finished

Swarms of Thargoid vessels have invaded the 42 n Persei, Chun Pindit and
Tekkeitjal systems in an apparently coordinated attack.

[[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]] published this report by field correspondent Ernesto
Rios:

"Since the Thargoids conquered [[id:55088d83-4221-44fa-a9d5-6ebb0866c722][HIP 22460]] a month ago, their presence
has gradually expanded in all directions. But these are the first
inhabited systems to be invaded since the [[id:38143d4a-d8a5-4978-a62c-8b64a0c75969][Proteus Wave]] incident,
threatening a combined population of over seven million people."

Defensive operations are being orchestrated by Tekkeitjal Public
Corporation from the starport Riemann Colony in the Tekkeitjal system.
Thargoid combat bonds can be handed in at this location for increased
credit rewards.

The first part of the campaign begins on the 12th September and will run
until further notice. If the final target is met earlier than planned,
the situation will be re-assessed.
