:PROPERTIES:
:ID:       f2722b6a-b684-41c2-ae8c-83372e1bbd45
:ROAM_REFS: file:../references/Community%20Goals/The_Art_Of_War.md
:END:
#+title: Community Goal: The Art Of War
#+filetags: :CommunityGoal:3301:Empire:

* Location

Parkinson Dock | [[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]]

* Objective

Sell Industrial Materials to Parkinson Dock

* Progress

Tier 4

* Contributors

2,267

* Contributions

0

* End

28 Apr 2015, 6:00pm

* Status

Finished

Over the years Senator Patreus has amassed an impressive collection of
private military industrial companies and corporations. As a result the
Senator's interests are spread across the length and breadth of the
[[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]], positioning Patreus as one of the premier suppliers of Imperial
Armaments in the entire galaxy.

Traditionally [[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]] has been left untouched by the Senator's
business, but now the time has finally come for an upgrade. Senator
Patreus has pledged to spend billions of credits in rejuvenating
[[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]]'s economy over the next month, with the ultimate aim being to
turn [[id:9fa174ce-7273-40ba-a0e6-1225bcda40b6][Eotienses]] in to a high tech hub that will be the envy of the entire
[[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]].

In order to help facilitate the rejuvenation effort, Senator Patreus has
placed a series of order which require several millions units of
Industrial Materials be brought to his agents on Parkinson Dock. All
citizens that take part in the rejuvenation programme will be well
rewarded for their efforts.
