:PROPERTIES:
:ID:       a52a1f8e-9399-4b17-8782-4585bee02fa7
:ROAM_REFS: file:../references/Community%20Goals/Fight_for_the_Empire_with_the_L_Y_S_Corp.md
:END:
#+title: Community Goal: Fight for the Empire with the L.Y.S Corp
#+filetags: :CommunityGoal:3306:Federation:Empire:

* Location

Strength of Purpose | LTT 1935

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for L.Y.S Corp in Conflict Zones​

* Progress

Tier 2/5

* Contributors

3,678

* Contributions

14,003,522,200/60,000,000,000 (23.34%)

* End

12 Nov 2020, 5:11am

* Status

Finished

[[id:1047d7bb-a08d-430d-a445-4ec9a1b2daa3][The Empire]]'s counter-terrorism operation in the LTT 1935 system has
triggered armed resistance from the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]].

The [[id:01980efc-1b06-4f55-bf18-fa6c7e56f1eb][Imperial Internal Security Service]]'s investigation into the NMLA
terrorist group led its agents to LTT 1935, a [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]-controlled
system in neutral space. Military vessels were called in for support,
only to be met in combat by Federal forces.

A declaration was made by Colonel Ernest Harris of the LTT 1935
Confederacy:

"[[id:1047d7bb-a08d-430d-a445-4ec9a1b2daa3][The Empire]] cannot dominate and arrest our citizens as it did with the
Marlinists. We claim the right to defend the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]'s territory
from such aggressive tactics."

Captain Axel Cyprian of the L.Y.S Corp responded:

"The IISS has confirmed that the Neo-Marlinists have secret bomb-making
factories concealed within LTT 1935. To prevent future atrocities, it is
vital that we take control of this system and shut down the NMLA's
source of weapons."

The L.Y.S Corp has asked for auxiliaries to assist in gaining control of
the system. Through an Imperial edict championed by Senator Patreus, the
top 75% of participating Commanders will be raised one military rank,
the top 25% will be raised two ranks and, should victory be secured, the
top 10 Commanders will be elevated to the highest military rank by the
14th of November 3306.

The two factions have set out week-long campaigns, which will begin on
the 5th of November 3306.
