:PROPERTIES:
:ID:       ec6ad641-8f47-46b4-bb9f-91b278ef739b
:ROAM_REFS: file:../references/Community%20Goals/Defend_Sirius_Corporation_in_Reorte.md
:END:
#+title: Community Goal: Defend Sirius Corporation in Reorte
#+filetags: :CommunityGoal:3308:Alliance:

* Location

Chariot of [[id:6da9023a-ccb6-444a-be77-626dfb552eb1][Rhea]] | [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]

* Objective

Hand in Combat bonds

* Progress

Tier 2/6

* Contributors

974

* Contributions

15,071,592,561/80,000,000,000 (18.84%)

* End

29 Jan 2022, 9:50pm

* Status

Finished

The [[id:83d61aae-150c-4a38-81aa-0443046505c3][Reorte Mining Coalition]] has declared its intent to remove the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation presence from its home system.

The megaship Chariot of [[id:6da9023a-ccb6-444a-be77-626dfb552eb1][Rhea]] arrived in [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] as part of [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation's new role as the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]]'s strategic defence partner.
But the system's controlling faction ordered it to withdraw. The
megaship's non-compliance has resulted in skirmishes targeting [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
forces.

Captain [[id:589b78d1-5587-40e5-a16e-969a30d06a4a][Delfina Dominguez]] of the [[id:3dd2f3c7-3ddf-4900-aa28-580344edd509][Sirius Navy]], who commands the Chariot
of [[id:6da9023a-ccb6-444a-be77-626dfb552eb1][Rhea]] released a statement:

"Our presence is authorised by the military contract between [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation and the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]]. If local forces continue to
attack, we will have no option but to defend our assets."

The fighting is not believed to have reached surface level and is
expected to remain a ship-based conflict.

To rally support from independent pilots, the [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] will
authorise a permit to the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system for the top 75% of supporters.

Prime Minister [[id:da80c263-3c2d-43dd-ab3f-1fbf40490f74][Edmund Mahon]] has ordered the [[id:83d61aae-150c-4a38-81aa-0443046505c3][Reorte Mining Coalition]] to
cease hostilities immediately. However, Councillor [[id:e19c4963-67d3-4204-bd00-5f11b266f67a][Ainsley Niven]] -- who
represents [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] in the Assembly and is a political supporter of Nakato
Kaine -- claims that the faction has the right to protect its territory,
since it was not invited to ratify the defence pact.

The two factions have set out seven-day combat operations, which will
begin on the 27th January 3308.
