:PROPERTIES:
:ID:       aac96fda-2c32-49d3-a46f-fcb7af212101
:ROAM_REFS: file:../references/Community%20Goals/Breaking_The_Outbreak.md
:END:
#+title: Community Goal: Breaking The Outbreak
#+filetags: :CommunityGoal:3301:Empire:

* Location

Lombardelli's Legacy | Persephone

* Objective

Sell Medicines to Lombardelli's Legacy

* Progress

Tier 7

* Contributors

2,502

* Contributions

0

* End

24 May 2015, 9:00pm

* Status

Finished

It seems that good things just don't last long for the People's
Quivira for Equality Party. On the tail of their military defeat, a
generous act of goodwill by the supporters of Aisling Duval helped them
back on their feet, and Patreus pardoned them for the failures of their
government.

Unfortunately, limited access to medical care during their flight has
lead to an outbreak of treatable diseases among the populace.

As such, Aisling's Angels are calling on all loyal Imperial citizens to
help our brethren in the People's Quivira for Equality Party rebuild
their lives. They have suffered enough.

In an effort to encourage the delivery of some much needed Basic
Medicine, the Angels are currently offering a bonus incentive scheme
which is open to all pilots willing to help combat the spread of this
horrific outbreak.
