:PROPERTIES:
:ID:       0aeb5705-42b6-436c-ade5-dd8917a8e8f9
:ROAM_REFS: file:../references/Community%20Goals/Medical_Supplies_for_Alliance_Starport_Bombing_Survivors.md
:END:
#+title: Community Goal: Medical Supplies for Alliance Starport Bombing Survivors
#+filetags: :CommunityGoal:3307:Alliance:

* Location

Krylov Ring | He Bo

* Objective

Deliver Basic Medicines and Advanced Medicines

* Progress

Tier 2/5

* Contributors

6,487

* Contributions

23,250,716/96,000,000 (24.22%)

* End

25 Mar 2021, 7:00am

* Status

Finished

Safeguard Interstellar requires deliveries of medicines to treat
casualties from the NMLA's recent terrorist attack.

CEO Noel Beaumont announced:

"Hundreds of thousands of civilians still require urgent medical
attention after being evacuated from the damaged stations. Many have
severe caustic burns inflicted by the corrosive enzyme payload of the
explosives. We have already exhausted the majority of supplies in nearby
systems."

"To reinforce overstretched health services, we request shipments of
basic medicines and advanced medicines. These can be delivered to Krylov
Ring in the He Bo system."

Safeguard Interstellar has partnered with Perez Ring Brewery to reward
pilots and distribute the medicines.

If Tier 1 is reached, the top 75% of participants will receive a
permanent Alioth system permit and a Lakon Spaceways Type-6 Transporter.
The ship will be delivered and stored at Krylov Ring in the He Bo system
by the 26th of March 3307.

The joint initiative will run for one week. If the final target is met
earlier than planned, the initiative will end immediately.
