:PROPERTIES:
:ID:       0dbd1323-f47a-48fa-a6e6-eaf72f1fd47a
:ROAM_REFS: file:../references/Community%20Goals/Protect_the_traders_in_Arawere.md
:END:
#+title: Community Goal: Protect the traders in Arawere
#+filetags: :CommunityGoal:3302:Empire:

* Location

Tanaka Gateway | Arawere

* Objective

Earn Rewards by delivering [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] to Tanaka Gateway in the
Arawere system.

* Progress

Tier 3/5

* Contributors

2,135

* Contributions

0

* End

21 Jan 2016, 3:00pm

* Status

Finished

Following its request for [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]], the Arawere [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] League is in
need of experienced combat pilots to eliminate the agitators operating
in the system, and protect those delivering [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]]. Any combat pilots
who contribute to this initiative by eliminating agitators in Arawere
will be generously rewarded.

EDIT: Tanaka Gateway is an outpost and therefore can only host ships up
to medium size landing pad!
EDIT: Tanaka Gateway has no REARM function and cannot refill your ammo.
Suggest lasers.
EDIT: "Arawere [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] League" Bounty vouchers count toward tiers
only.
EDIT: [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] bounty vouchers now count as well.

5%: 8M + Global Rewards
15%: 5M + Global Rewards
40%: 2.5M + Global Rewards
70%: 120K + Global Rewards \< 120k is probably a mistake and should be
1.2M but in game it states 120k
100%: 600K + Global Rewards
