:PROPERTIES:
:ID:       6458edae-a43f-4a01-8ffd-a814d4f2417e
:ROAM_REFS: file:../references/Community%20Goals/Ram_Tah_s_Last_Hurrah.md
:END:
#+title: Community Goal: Ram Tah's Last Hurrah
#+filetags: :CommunityGoal:3304:Guardian:

* Location

Felice Dock | [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]]

* Objective

Deliver Guardian Artefacts

* Progress

Tier 2/8

* Contributors

2,273

* Contributions

154,169

* End

15 Feb 2018, 5:36pm

* Status

Finished

[[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]], the galaxy's foremost expert on the Guardians, has revealed
that his research funding will soon end. In an effort to make the most
of his remaining finances, the engineer has appealed to independent
pilots to deliver Guardian artefacts to his base in the [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]] system.

In a statement, [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]] said:
Public interest in the Guardians may have waned, but I believe there is
more to learn. Only through thorough investigation and analysis can we
hope to fully understand the Guardians, their technology, and their
relationships to other species. This knowledge could be of great
importance to humanity.

The campaign has received a financial boost from [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]] General
Industries, which has promised to reward pilots who deliver artefacts
from Guardian sites to Felice Dock in the [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]] system.
