:PROPERTIES:
:ID:       1dd82839-5f47-457d-8c1c-caf0a65b1793
:ROAM_REFS: file:../references/Community%20Goals/Supplies_for_the_Federal_Navy.md
:END:
#+title: Community Goal: Supplies for the Federal Navy
#+filetags: :CommunityGoal:3305:Federation:

* Location

Payson Hub | [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]]

* Objective

Deliver [[id:6f8b14ec-06ee-4f36-b646-15146a0ca81b][Battle Weapons]], [[id:2b461b7b-10e3-49fd-ba61-bce15a046809][Landmines]] and [[id:1f1b3c4c-ab13-4a0e-929f-92b2f3d37d28][Performance Enhancers]] to Payson
Hub

* Progress

Tier 3/8

* Contributors

1,825

* Contributions

3,704,029

* End

10 Jan 2019, 3:59pm

* Status

Finished

An open order for military supplies has been placed on behalf of the
[[id:3d268496-1d95-49bc-aca6-49d16a4337c8][Federal Navy]] by the League of [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]]. A spokesman for the organization
gave the following statement:

"The [[id:3d268496-1d95-49bc-aca6-49d16a4337c8][Federal Navy]] urgently requires shipments of [[id:6f8b14ec-06ee-4f36-b646-15146a0ca81b][Battle Weapons]],
[[id:2b461b7b-10e3-49fd-ba61-bce15a046809][Landmines]] and [[id:1f1b3c4c-ab13-4a0e-929f-92b2f3d37d28][Performance Enhancers]] to be delivered to the Payson Hub in
the [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]] system."

The campaign begins on the 3rd of January 3305 and will run for one
week. If the final target is met earlier than planned, the campaign will
end immediately.

To be eligible for the rewards you must sign up as an active participant
before delivering [[id:6f8b14ec-06ee-4f36-b646-15146a0ca81b][Battle Weapons]], [[id:2b461b7b-10e3-49fd-ba61-bce15a046809][Landmines]] and [[id:1f1b3c4c-ab13-4a0e-929f-92b2f3d37d28][Performance Enhancers]] to
Payson Hub in the [[id:bb8ac014-a3ac-4564-9c3a-7aaff6536d59][Zearla]] system.

Be aware that faction-state changes and other disruptive events can
negatively impact markets and station services, and could prevent the
initiative from running smoothly.
