:PROPERTIES:
:ID:       ec6a52c0-5f70-4da9-a253-e5f3276f4858
:ROAM_REFS: file:../references/Community%20Goals/Utopia_Research_Appeal__Materials_donation_.md
:END:
#+title: Community Goal: Utopia Research Appeal (Materials donation)
#+filetags: :CommunityGoal:3303:

* Location

Cenker City | Gucumadhyas

* Objective

Deliver [[id:7d1728bb-333a-470d-8038-769ad1cce208][Zirconium]], [[id:d12b6560-fbeb-4d96-8970-587bbbede4c5][Conductive Ceramics]] and [[id:2b06db3f-ce23-4a4c-9a88-6b6f5388f94a][Strange Wake Solutions]]

* Progress

Tier 1/8

* Contributors

2,112

* Contributions

0

* End

21 Apr 2017, 5:17am

* Status

Finished

The [[id:058a658d-e1ce-4364-a92b-b9607495c73f][Utopia]] Commune has issued a request for various commodities to be
used in a forthcoming research and development programme.

The enclave has placed an open order for [[id:7d1728bb-333a-470d-8038-769ad1cce208][Zirconium]], [[id:d12b6560-fbeb-4d96-8970-587bbbede4c5][Conductive Ceramics]]
and [[id:2b06db3f-ce23-4a4c-9a88-6b6f5388f94a][Strange Wake Solutions]], and has promised to reward pilots who
deliver these commodities to Cenker City in the Gucumadhyas system.

Simguru [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]], leader of the Utopian movement, released a
statement outlining the nature of the initiative.

"We are well aware that independent pilots accumulate large quantities
of material over the course of their travels. Fortunately, [[id:058a658d-e1ce-4364-a92b-b9607495c73f][Utopia]] is
willing to pay above-market prices for these materials, which will play
a central role in our forthcoming programme."

The campaign begins on the 13th of April 3303 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before delivering [[id:7d1728bb-333a-470d-8038-769ad1cce208][Zirconium]], [[id:d12b6560-fbeb-4d96-8970-587bbbede4c5][Conductive Ceramics]] and Strange Wake
Solutions to Cenker City in the Gucumadhyas system.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)
Current Global Progress: 69,860 tonnes collected

Current Participation Rewards:
Top 10 CMDRs: 1,200,000 CR
Top 10%: 1,000,000 CR
Top 25%: 800,000 CR
Top 50%: 600,000 CR
Top 75%: 400,000 CR
Top 100%: 200,000 CR
