:PROPERTIES:
:ID:       1b85af7a-50a5-496e-b8c9-71d8dd442209
:ROAM_REFS: file:../references/Community%20Goals/Engineers_Appeal_for_Thargoid_Material___Professor_Palin.md
:END:
#+title: Community Goal: Engineers Appeal for Thargoid Material - Professor Palin
#+filetags: :CommunityGoal:3303:Federation:Thargoid:

* Location

[[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] | [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]

* Objective

Deliver Unknown Technology Samples, Unknown Resin, [[id:66b0f0aa-4387-46f9-9abe-a3dbe1033c6f][Computer Components]]
and [[id:0c4bfccc-2597-4f26-a8fe-bcd003e6f9c3][Resonating Separators]]

* Progress

Tier 3/5

* Contributors

7,862

* Contributions

14,395,838

* End

28 Sep 2017, 3:00pm

* Status

Finished

Following news that the Thargoids have attacked a Federal convoy in the
[[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] Sector IR-W d1-55 system, Aegis has recruited two of the
galaxy's foremost independent engineers to immediately begin developing
new defensive and offensive technologies.

[[id:8f63442a-1f38-457d-857a-38297d732a90][Professor Ishmael Palin]], a leading authority on xenobiology, has been
recruited to the programme. He said:

My first task will be developing a scanner that can provide us with
meaningful data on the Thargoids' ships. Of course, to properly
calibrate these new technologies we will need large quantities of
Thargoid material.

Aegis has placed an open order for a range of Thargoid materials for use
in the programme. [[id:3808ab0e-fcff-4299-b882-f8c3946f272d][Aegis Research]] has promised to reimburse Commanders
who deliver Unknown Technology Samples, Unknown Resin, Computer
Components and [[id:0c4bfccc-2597-4f26-a8fe-bcd003e6f9c3][Resonating Separators]] to [[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]
system for Ishmael Palin.

The campaign begins on the 21st of September and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before delivering Unknown Technology Samples, Unknown Resin, Computer
Components and [[id:0c4bfccc-2597-4f26-a8fe-bcd003e6f9c3][Resonating Separators]] to [[id:4223b99a-7e0c-44fa-b7e9-afeca7e0c031][Obsidian Orbital]] in the [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]]
system.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

Current Participation Rewards:
Top 10 CMDRs: 14,535,000 CR
Top 10%: 12,790,800 CR
Top 25%: 10,465,200 CR
Top 50%: 7,558,200 CR
Top 75%: 3,488,400 CR
Top 100%: 500,000 CR
