:PROPERTIES:
:ID:       100d2e6b-394f-4055-b61e-3a41de9adb68
:ROAM_REFS: file:../references/Community%20Goals/Debilitating_disease_devastating_Cantjarisni.md
:END:
#+title: Community Goal: Debilitating disease devastating Cantjarisni
#+filetags: :CommunityGoal:3301:

* Location

Cochrane Enterprise | Cantjarisni

* Objective

Sell Medicines to Cochrane Enterprise

* Progress

Tier 0/1

* Contributors

0

* Contributions

0

* End

06 Aug 2015, 3:05pm

* Status

Finished

A terrifying disease is currently working its way through Cantjarisni.
So far the illness has defied attempts to contain it, despite the best
efforts of medical staff aboard Cochrane Enterprise.

Many people have already been placed in quarantine, with many more
thought to have already been infected. Doctors are concerned that the
pathogen responsible may have already begun to spread to other systems.
To assist medical staff aboard Cochrane Enterprise, the Cantjarisni
Solutions are offering a series of incentives to any pilots that provide
medicines to Cochrane Enterprise market until such time as the crisis
has been averted.
