:PROPERTIES:
:ID:       1f93f64d-3fad-4500-8c0e-92a364586cfc
:ROAM_REFS: file:../references/Community%20Goals/Colonia_Bridge_Phase_Four___Week_Four___Alcor.md
:END:
#+title: Community Goal: Colonia Bridge Phase Four - Week Four - Alcor
#+filetags: :CommunityGoal:3308:Colonia:

* Location

Macdonald Settlement | [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]]

* Objective

Deliver [[id:5d99c688-f21a-41e1-9ebb-00b626b4c31f][Auto-Fabricators]], [[id:0c4bfccc-2597-4f26-a8fe-bcd003e6f9c3][Resonating Separators]] and [[id:e87b8a83-ecc1-4d17-917a-964e6196526b][Micro Controllers]]

* Progress

Tier 3/4

* Contributors

8,599

* Contributions

142,546,092/1,000,000,000 (14.25%)

* End

10 Mar 2022, 7:00am

* Status

Finished

Delivery campaigns in the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] and [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] systems will complete the
six starports along the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]].

Months of work on developing the transportation infrastructure between
the core systems and the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] region are now coming to an end. Brewer
Corporation's latest press release specified the requirements:

"Phase four of the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] project has finally reached its
conclusion. Thanks to the many shipments provided by contributors, all
six starports now offer bartender, material trader and mission
services."

"For this final week, we are asking pilots to deliver auto-fabricators,
micro controllers and resonating separators to Macdonald Settlement in
the [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]] system. These will allow us to install outfitting, shipyard
and tech broker services as we bring the starports to full operational
status."

"[[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] is grateful to independent pilots for their
dedication to constructing the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]]. We are therefore pleased
to offer various classes of pre-engineered, overcharged power plants as
well as exploration decals to the top 75% of contributors to this
concluding stage."

"Finally, this is the last chance for pilots to obtain a Brewer
Corporation decal, which will be awarded to every contributor to any of
the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] initiatives as a token of gratitude."

Each tier reached will enable [[id:d9459015-dae3-4233-9eb7-a2fb11344097][Brewer Corporation]] to establish a further
service to five starports branching out from [[id:eb11ab9d-aab7-4d9b-aeaf-a228ef33d4da][Alcor]], as follows:

Tier 1: Outfitting
Tier 2: Shipyard
Tier 3: Human Tech Broker

If Tiers 1, 2 and 3 are successfully reached, the top 75% of
participants will be awarded a 3A, 4A and 5A Pre-Engineered Overcharged
Power Plant respectively.

The Exploration decals are available for participating in this final
initiative only. The decal colours provided are based on contribution as
follows:

Top 75%: Emissive Red, Emissive White and Emissive Blue
Top 50%: Bronze
Top 25%: Silver
Top 10%: Gold

These decals will be awarded cumulatively.

The top ten contributors for each of the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] initiatives will
have the opportunity to be named in tourist beacons that will
commemorate the project's conclusion. Every Commander who has
contributed to any of the [[id:97a8c7e5-9399-4ebe-9457-8029ce809303][Colonia Bridge]] initiatives will receive a
Brewer Corp decal.

This campaign begins on the 3rd of March 3308 and will run for one week.
