:PROPERTIES:
:ID:       24896375-b9b8-4873-a075-5abcc1f53869
:ROAM_REFS: file:../references/Community%20Goals/Protect_the_Sirius_Corporation_Campaign_to_Establish_Marlinist_Colonies.md
:END:
#+title: Community Goal: Protect the Sirius Corporation Campaign to Establish Marlinist Colonies
#+filetags: :CommunityGoal:3306:Federation:Empire:

* Location

Ellis Gateway | BD+05 1146

* Objective

Hand in Bounty Vouchers​

* Progress

Tier 5/5

* Contributors

7,690

* Contributions

160,001,960,496/160,000,000,000 (100.00%)

* End

16 Dec 2020, 4:10am

* Status

Finished

Sirius Corporation has offered to resolve the current standoff between
superpowers by establishing colonies where the refugees can live
independently.

Li Yong-Rui, CEO of Sirius Corporation, summarised his proposal:

"It is clear that the Marlinists cannot return to the Empire, and are a
destabilising presence within the Federation. We offer an alternative by
constructing permanent habitats for their population. These will be
self-governed and may freely trade with the galactic community."

"Sirius cannot stand by while the risk of interstellar war increases. I
sincerely hope this leads to a more stable and profitable period for us
all."

After intense debate, both Congress and the Senate accepted the
proposal, with the proviso that any refugees identified as NMLA members
will be returned to the Empire.

Dr Jenna Fairfax, a Marlinist community leader, also offered her
approval:

"We were forced to abandon our entire lives because of our political
beliefs. This at least gives us a chance to have homes again."

Sirius Corporation has requested the support of independent pilots to
counter any piracy or other acts that may interfere with the supply of
commodities, and will handsomely reward such efforts.
Hand in your bounties to the Omega Merchant Command at Ellis Gateway in
the Bd+05 1146 system.

The initiative begins on the 10th of December 3306 and will run for one
week. If the final target is met, the campaign will end immediately.
