:PROPERTIES:
:ID:       4f576d02-5494-4288-8e4e-8a8427b583da
:ROAM_REFS: file:../references/Community%20Goals/Sagittarius_Eye_Appeal.md
:END:
#+title: Community Goal: Sagittarius Eye Appeal
#+filetags: :CommunityGoal:3305:

* Location

McMullen Ring | Millese

* Objective

Deliver [[id:3de49bff-8041-45b0-a713-d3646334efd9][Cobalt]], [[id:d10c0435-4bc8-42ac-bea6-228d2f02604c][Tantalum]] and [[id:d727fb19-8dc0-4d94-bcd4-da1cb5c090f0][Titanium]]

* Progress

Tier 6/8

* Contributors

2,690

* Contributions

14,813,491

* End

12 Jun 2019, 1:59pm

* Status

Finished

Sagittarius Eye has announced plans to construct an asteroid station in
the Millese system.

A spokesperson for the faction provided the following statement:

"We've found a lovely asteroid in Millese that we can hollow out to
build our print works in. We don't have a great deal of experience with
building, but our intern has an engineering degree and tells us that
we'll need specific materials. Bring us those and we'll reward you
handsomely!"

In support of this initiative, the organisation has placed an open order
for cobalt, titanium and tantalum, with rewards available to pilots who
deliver these commodities to McMullen Ring in the Millese system.

The campaign will take place between the 6th and 12th of June 3305. If
the final target is met earlier than planned, the campaign will end
immediately.
