:PROPERTIES:
:ID:       22f03b05-7382-4e19-ad7a-3eb2c310aa38
:ROAM_REFS: file:../references/Community%20Goals/Imperial_Operation_against_the_League_of_Reparation.md
:END:
#+title: Community Goal: Imperial Operation against the League of Reparation
#+filetags: :CommunityGoal:3304:Federation:Empire:Thargoid:

* Location

Brundage City | [[id:a1a95018-50f7-4017-936f-273f4c2ae58e][Ienpalang]]

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for [[id:a1a95018-50f7-4017-936f-273f4c2ae58e][Ienpalang]] Corporation in CZs

* Progress

Tier 4/8

* Contributors

2,170

* Contributions

4,294,967,295

* End

26 Jul 2018, 3:59pm

* Status

Finished

A tri-superpower taskforce has launched a campaign to track down and
eliminate members of terrorist group the [[id:f5c4ef7c-7a40-4d9f-87e1-904f11efda2f][League of Reparation]].

Captain [[id:cdaa5220-8f79-47dc-b160-a5d3d1ca30a0][Niamh Seutonia]] of the IISS, who is a prominent member of the
taskforce, made this announcement:
With the arrest of [[id:315a2182-7266-45f9-ac87-5f0f42c5cf12][Riri McAllister]], otherwise known as Nexus, we now
hold the main coordinator of the [[id:f5c4ef7c-7a40-4d9f-87e1-904f11efda2f][League of Reparation]] in custody.
Furthermore, decrypted information has revealed the location of League
strongholds in two separate systems, one in Imperial and one in Federal
space.

We are determined to eliminate these terrorists before they can wreak
any more havoc, but fully expect tough resistance. Therefore we ask the
galactic community to provide support in wiping out these dangerous
extremists.
The operation in [[id:a1a95018-50f7-4017-936f-273f4c2ae58e][Ienpalang]] will be supported by [[id:a1a95018-50f7-4017-936f-273f4c2ae58e][Ienpalang]] Corporation.

The campaign begins on the 19th of July 3304 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

To earn rewards you must sign up as an active participant before handing
in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Brundage City in the [[id:a1a95018-50f7-4017-936f-273f4c2ae58e][Ienpalang]] system.

Please note that if you have any crew members, a portion of your combat
bonds will be automatically assigned to them. These combat bonds will
not count towards your personal contribution total, and your crew will
receive the reward for their bonds when they are handed in. The
proportion of combat bonds assigned to your crew will depend on their
rank.

Be aware that faction-state changes, [[id:8ddf8e00-4541-4857-a609-5f6c5849dded][Thargoid Sensor]]-related
interference and other disruptive events can negatively impact markets
and station services, and could prevent the initiative from running
smoothly.
