:PROPERTIES:
:ID:       eb5b78d6-7a8a-4355-88f0-8fbdcb25ccc7
:ROAM_REFS: file:../references/Community%20Goals/Debilitating_disease_devastating_Bastes.md
:END:
#+title: Community Goal: Debilitating disease devastating Bastes
#+filetags: :CommunityGoal:3301:

* Location

Shepherd Hub | [[id:a6410be1-99d2-4e1f-924b-4ec4dca8dfe9][Bastes]]

* Objective

Sell Medicines to Shepherd Hub

* Progress

Tier 0/1

* Contributors

70

* Contributions

0

* End

30 Jul 2015, 4:14pm

* Status

Finished

A terrifying disease is currently working its way through [[id:a6410be1-99d2-4e1f-924b-4ec4dca8dfe9][Bastes]]. So far
the illness has defied all attempts to contain it, despite the best
efforts of the medical staff aboard Shepherd Hub.

Many people have already been placed in quarantine, with many more
thought to have already been infected. Doctors are concerned that that
pathogen responsible may have already begun to spread to other systems.
to assist medical staff aboard Shepherd Hub, the Jet Comms PLC are
offering a series of incentives to any pilots that provide medicines to
Shepherd Hub market until such time as the crisis has been averted.
