:PROPERTIES:
:ID:       7d78613c-67ac-469e-a432-9100a9daf457
:ROAM_REFS: file:../references/Community%20Goals/Prepare_for_peace__Protect_deliveries_for_the_Kingfisher_megaship.md
:END:
#+title: Community Goal: Prepare for peace! Protect deliveries for the Kingfisher megaship
#+filetags: :CommunityGoal:3308:Thargoid:

* Location

Blenkinsop Hub | Andavandul

* Objective

Hand in Bounty vouchers​

* Progress

Tier 3/5

* Contributors

2,572

* Contributions

57,082,212,886/250,000,000,000 (22.83%)

* End

22 Nov 2022, 7:59am

* Status

Finished

  Tier           Contributions                   Reward
  -------------- ------------------------------- ---------------
  Top 10 CMDRs   \~ 327,308,244 to 574,066,523   12,500,000 Cr
  Top 10%        \~ 57,463,474 to 327,308,243    7,000,000 Cr
  Top 25%        \~ 26,800,601 to 57,463,473     4,600,000 Cr
  Top 50%        \~ 8,767,002 to 26,800,600      3,000,000 Cr
  Top 75%        \~ 2,098,478 to 8,767,001       2,200,000 Cr
  Top 100%       \~ 1 to 2,098,477               1,400,000 Cr

[]{#goalprogresschart247710_legend}

[]{#goalprogresschart247710note}

The [[id:094dc5da-c38d-48aa-9fc7-fc5f60e5365d][Kingfisher]] megaship has requested supplies for its planned journey
to greet the first rogue signal source.

Congressman [[id:ce508d31-48d2-411d-9056-6b451fc66cf3][Dalton Chase]] gave a press statement regarding the
initiative:

"Now that we know the approaching anomalies are Thargoid, many are
concerned that hostilities between our species will escalate. However, a
brave group of volunteers see this as an opportunity to prove that
diplomacy can work. An alien race has sent emissaries toward humanity's
space, and it is our duty to meet them with words rather than
weapons."

"The first of the anomalies, which we have named [[id:f62776a6-64be-4794-b138-109ce4687622][Taranis]], is predicted
to pass through [[id:73e6ac6c-6320-4370-a533-ac7d58baf91c][Hyades Sector YO-Q b5-1]]. Using the high-level protocols
available to Congress, I have successfully obtained a temporary access
restriction that grants an exclusive permit to the [[id:094dc5da-c38d-48aa-9fc7-fc5f60e5365d][Kingfisher]]. A range
of broadcasts using multiple techniques will try to attract the
Thargoids' attention. Hopefully, the entity will slow down long enough
to give some acknowledgement of these attempts."

In order to protect deliveries to Blenkinsop Hub, Deutsche Elite Piloten
Interstellar is offering increased payouts on bounty voucher
redemptions.

If the final target is met earlier than planned, the campaign will end
immediately.
