:PROPERTIES:
:ID:       c2cf6cc4-9fc8-4a0a-aec9-6a477dbf703b
:END:
#+title: The Cat's Eye
#+filetags: :Tourist:beacon:
* 0648 The Cat's Eye
[[id:bacd80ef-8bd3-415e-98b0-7fa0c0a5a1f3][Pyraleau AA-A H39]]

This location was recommended by Commander Henry Passionfruit.

I've heard people talk about the Space Cat. Space Cat this, Space Cat that - yeah, yeah. But have they seen it? Have they been caught in its gaze; that colossal Eye staring at you; judging you. I've seen it; and it has seen me.

I was way out; heading for [[id:79eced12-4b6a-4f24-8673-fa0d509a452e][Sagittarius A*]], but far off track. I saw a system from afar, blazing in the ultra-violet bands. I locked on and jumped. I came out of the jump, the radiation alarm went nuts! A lethal wash of xrays and gammas was pounding on the shields; but my old [[id:2588102a-6025-451e-bd68-22906a8a09e0][Cobra MkIII]] ?Syntax Error? held together. The scanner sent out its pulse - triple black holes! Three of hte monsters... I could see one straight ahead, bending gravity; but where were the other two? I rolled the Cobra around and there it was! THE EYE OF THE SPACE CAT! I said a prayer to any gods I knew - Buddha, Hendrix, Bastet - I even vowed to serve the Simguru [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]] all my days if I could just get away from that giant alien feline Eye... I must have, because I'm here now. And I know - I KNOW that it's still out there... watching...
