:PROPERTIES:
:ID:       033768df-89f1-4b89-a8b2-ace98dd4ba10
:ROAM_REFS: file:../references/Community%20Goals/Caine_Massey_Mining_Initiative.md
:END:
#+title: Community Goal: Caine Massey Mining Initiative
#+filetags: :CommunityGoal:3308:

* Location

Smith Port | Dulos

* Objective

Deliver [[id:19346f59-fa1a-4ba2-8373-5b4d90f26662][Gallite]], [[id:1cbb99d3-bda9-462d-9314-51bab7c41e3c][Bromellite]] and [[id:699175f3-27b8-43ca-a463-2896e147de16][Samarium]]

Hint: Nearest metal rich pristine rings

* Progress

Tier 2/5

* Contributors

1,458

* Contributions

485,271/1,600,000 (30.33%)

* End

20 Jan 2022, 7:00am

* Status

Finished

Caine Massey and [[id:62ab96ef-615e-4fd5-a2b1-68167557baa1][Torval Mining Ltd]] are running rival campaigns to
deliver mined commodities to the Dulos system.

For the past decade, the megacorp Caine Massey has supplied ore and
other raw materials to several subsidiaries in the region. But with the
contract up for renewal, [[id:62ab96ef-615e-4fd5-a2b1-68167557baa1][Torval Mining Ltd]] is making a bid for the
lucrative business.

Caine Massey published a request from its vice president, Johann
Fleischer:

"The citizens within this region deserve a high standard of service,
and we aim to continue meeting their needs. The Green Party of Dulos,
acting on our behalf, shall offer generous rewards for shipments of
mined bromellite, samarium and gallite delivered to Smith Port in the
Dulos system."

The corporate distributors within the region have agreed that whichever
candidate is able to provide the greatest amount of materials will be
awarded the contract for the next decade.

Should Caine Massey be successful, an initial 10% price reduction will
be applied to all mining modules offered at Smith Port. A further 5%
reduction will be applied per tier reached. This discount will be
available for two weeks.

The two factions have set out seven day campaigns, which will end early
on Thursday 20th January 3308. If one faction meets its objectives
earlier than planned, the initiatives will end immediately.
