:PROPERTIES:
:ID:       969cc57b-15e4-45fd-bf03-b8c5e9d9ae64
:ROAM_REFS: file:../references/Community%20Goals/Feeding_the_Galactic_Summit.md
:END:
#+title: Community Goal: Feeding the Galactic Summit
#+filetags: :CommunityGoal:3307:Empire:Alliance:

* Location

Spirit of Laelaps | [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]

* Objective

Deliver [[id:33adaaf7-4206-4047-bbd9-81be1fc169c0][Animal Meat]], [[id:17e9c920-2c60-4aad-975a-c52e81030b1e][Coffee]], [[id:6aec48eb-daf1-45ff-92d2-0ba46d6347f8][Fish]], [[id:9dbf5564-8fe2-46f3-930f-f3f1dbfecd26][Fruit and Vegetables]], and [[id:f94bf0ea-483b-4148-bc0a-5c3d77eea8d3][Wine]]

* Progress

Tier 4/8

* Contributors

11,072

* Contributions

106,285,435/192,000,000 (55.36%)

* End

11 Mar 2021, 6:59am

* Status

Finished

[[id:1047d7bb-a08d-430d-a445-4ec9a1b2daa3][The Empire]] is aiding [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] by offering bounty hunting and
trade opportunities to support the [[id:c19cec97-cb93-4049-be5d-1abcaa6023a5][Galactic Summit]].

The diplomatic conference is now entering its second week, with
superpower and independent leaders gathered at Patterson Enterprise in
the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system.

[[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]]'s CEO [[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]] announced:

"For the coming week, we are working with the [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] to maintain the
security operation by offering bounties on all wanted ships. [[id:1047d7bb-a08d-430d-a445-4ec9a1b2daa3][The Empire]]
will also pay generously for extra supplies of animal meat, coffee,
fish, fruit and vegetables, and wine that are delivered to the Spirit of
Laelaps."

If Tier 1 is reached, the top 75% of participants will receive a
permanent [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] system permit and the [[id:83299a14-b6b0-4670-ba39-2914e05ed2f5][Cobra Mk III]] Acceleration White
paint job. The top 25% will additionally receive the [[id:83299a14-b6b0-4670-ba39-2914e05ed2f5][Cobra Mk III]]
Acceleration Gold paint job. These should be processed and accessible by
the 13th of March 3307.

Thanks to the generosity of the [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]], the top 10 participants will
receive an Imperial Clipper. The ship will be delivered and stored at
Ashby City starport in the [[id:5817a2f2-d8af-4c78-9401-490abe32564b][Luyten's Star]] system by the 13th of March
3307.

The joint initiative will run for one week, after which [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation will partner with the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] to provide for the needs and
security of the conference.

If the final target is met earlier than planned, this phase will end
immediately.
