:PROPERTIES:
:ID:       9b71ab2e-6c6f-4ff8-84cb-3469bf4cc4fa
:END:
#+title: Battle Rages On Across HIP 87621 Enclave
#+filetags: :3311:Empire:galnet:

* Battle Rages On Across HIP 87621 Enclave

/11 Dec 3311/

Conflict continues across the 49-system enclave surrounding [[id:64e3ad83-30b5-41fc-bde5-8eb63c38ab83][HIP 87621]],
with military forces from all major powers showing no signs of a
ceasefire after two weeks of heavy fighting.

[[id:9aac4d99-35c1-4f2e-91c1-b84cb73d54f8][Ernesto Rios]], a freelance war correspondent for [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]], reported:

“Although the Empire appears to be the dominant force across the
enclave after this initial campaign, it's becoming clear that this
conflict concerns far more than territorial influence. [[id:e77720ef-95cb-445c-8b48-0c7ddf11e9eb][Radicoida unica]]
has been confirmed by [[id:e7e9a4cd-8be3-4ce9-a034-9d7f6551f4f2][Vista Genomics]] as a wholly unique species, with
early genetic indicators suggesting potential advancements once fully
understood.”

“Given the scale of the mobilisation across the enclave, it is
possible that certain details of its properties are known only to a
select few within senior leadership circles.”

Military analysts note that the strategic and tactical situation
shifts daily. The first week saw aggressive offensives from all sides,
placing all fortified positions at risk as few efforts were directed
into defensive action. Rapid strategic adjustments soon followed, with
most Powers reinforcing key footholds to avoid being overrun.

By the second week, a more balanced pattern of defensive and offensive
operations had emerged, alongside rumours of temporary concords
between smaller Powers against larger rivals within the enclave.

All Powers involved in the enclave battle have issued urgent calls for
pledged supporters to participate, while encouraging unaffiliated
pilots to align themselves to a cause.

Leaked internal communications suggest the conflict will continue
until one Power secures dominance across the 49-system enclave,
confirming some analyst reports that the Powers wants strategic
control over [[id:64e3ad83-30b5-41fc-bde5-8eb63c38ab83][HIP 87621]] for themselves. Powers are now targeting each
other, regardless of their superpower alignment.

According to [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]]’s most recent assessment by [[id:8a3f6489-2b06-4494-89ce-5094392c7a99][Conrad Sterling]], the following three Powers currently control the largest number of systems in the opening phase:

Rank 1: [[id:b402bbe3-5119-4d94-87ee-0ba279658383][Aisling Duval]] – 6 systems

Rank 2: [[id:0d664f07-640e-4397-be23-6b52d2c2d4d6][Nakato Kaine]] – 5 systems

Rank 3: [[id:05ab22a7-9952-49a3-bdc0-45094cdaff6a][Pranav Antal]]/[[id:34f3cfdd-0536-40a9-8732-13bf3a5e4a70][Arissa Lavigny-Duval]] – 3 systems

[[id:7bdfd887-d1db-46bc-98c4-2fb39bfcc914][Jerome Archer]] has lost their foothold in the enclave and are now eliminated from contention for control of the region.

Pilots who contributed during the initial two-week phase may now collect rewards from the megaship where they registered participation.
