:PROPERTIES:
:ID:       221834bd-28f1-4d70-af5b-3d8558884da0
:END:
#+title: Burnham Bile Distillate
#+filetags: :Commodity:rare:

#+begin_quote
The use of 'donated' human bodily fluids in the distillation process
for this potent liquor causes a strong variation in flavours from
vintage to vintage, and widespread outcry about the ethics of the
production. The producers of the drink report that each slave used
agrees to the extraction process, but this has not stopped some
having a bitter taste left in their mouths. This rare good is legal
in all Anarchy, Imperial, Independent and Alliance systems except
Prison systems and Alliance Confederacy systems. Please note that if
a system's controlling faction changes, some formerly legal rare
goods may become illegal in that system. If this happens, the rare
goods in question will no longer be available for sale or purchase.
#+end_quote

Sold as a rare commodity at [[id:996a3f90-87d1-42bb-a2f9-9d83a15d4976][Burnham Beacon]], [[id:0aa9e721-b00b-4be6-b08f-45c88ef5e00e][HIP 59533]].

Sources: in-game commodity description, mirrored at [[https://inara.cz/elite/commodity/10097/][Inara: Burnham Bile Distillate]]
