:PROPERTIES:
:ID:       9b8a8f73-492a-4b80-8a02-07d1b76ddf71
:ROAM_REFS: file:../references/Community%20Goals/Protect_Rare_Booze_Traders_in_Harma.md
:END:
#+title: Community Goal: Protect Rare Booze Traders in Harma
#+filetags: :CommunityGoal:3303:

* Location

[[id:8c659354-ea2b-4fd2-aeb9-874346ff07c1][Gabriel Enterprise]] | [[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]]

* Objective

Deliver [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] to Station

* Progress

Tier 8/8

* Contributors

13,225

* Contributions

0

* End

02 Aug 2017, 10:03pm

* Status

Finished

The [[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] Silver Cartel has announced that it intends to bring back a
beverage that has been lost for several hundred years: rum. The Cartel
has placed an open order for a range of rare alcohols that will be used
to create the new beverage.

A spokesperson for the organisation released a brief statement:

"We will create the finest rum since the days of piracy on the seas of
[[id:5b0f485f-4793-468d-a1a1-483606f44e0e][Earth]]. After all, a pirate isn't a pirate without rum!"

But the announcement has antagonised other pirate organisations in the
[[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] system, many of which have threatened to blockade the Cartel's
base of operations and attack pilots delivering alcohols to Gabriel
Enterprise.

To counter this threat, the [[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] Silver Cartel has asked the leading
[[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] Law Party to place a kill order on all ships on its wanted list,
and promised to reward pilots who deliver bounty vouchers to Gabriel
Enterprise.

The initiative begins on 27th of July 3303 and will run for one week. If
the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before handing in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] at [[id:8c659354-ea2b-4fd2-aeb9-874346ff07c1][Gabriel Enterprise]] in the [[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]]
system. Only bounty vouchers handed in after signing up will count
toward your personal contribution total.

Please note that if you have any crew members, a portion of your bounty
vouchers will be automatically assigned to them. These bounty vouchers
will not count towards your personal contribution total, and your crew
will receive the reward for their vouchers when they are handed in. The
proportion of bounty vouchers assigned to your crew will depend on their
rank.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.
-----

[Notes:\\\\](Notes:\\)

-   Available RES in system:

•[[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] A 1: 1 x Low RES
•[[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] A 2: 2 x RES, 1 x Low RES 1 x Hazardous RES
•[[id:1c48b668-227f-4973-a6a9-7638e35c02c2][Harma]] A 3 A: 1 x RES, 1 x Low RES 1 x Hazardous RES
