:PROPERTIES:
:ID:       f2cdd6b9-3df3-4c7a-8681-5b493919451e
:ROAM_REFS: file:../references/Community%20Goals/The_Hand_Gang.md
:END:
#+title: Community Goal: The Hand Gang
#+filetags: :CommunityGoal:3301:

* Location

Lu Hub | Gandii

* Objective

Submit combat bonds to the Hand Gang of Gandii at Lu Hub

* Progress

Tier 1/6

* Contributors

1,562

* Contributions

0

* End

12 Jun 2015, 4:20pm

* Status

Finished

## Unauthorised Transmission \*\* Terminal Compromised \*\* Unauthorised

Transmission \*\*

Earlier in the week the Hand Gang of Gandii launched a devastating
attack against the Gandii Interstellar Corporation, their intention, to
deliver a warning to those who refuse to pay [[id:7aae0550-b8ba-42cf-b52b-e7040461c96f][Archon Delaine]] his due. In
response, the Gandii Justice Party has initiated a campaign to remove
the Hand Gang from Gandii once and for all.

Emboldened by their recent success, the Hand Gang is more than willing
to meet the Justice Party on the field of battle. The two groups are now
locked in a fierce fight for survival, with both sides swearing that the
war will continue until one group remain.

The only problem is... the Hang Gang isn't looking ot win this fight
fairly. They've put the world out that any independent pilot who fights
for their cause will earn themselves a lion's share of the spoils. A
promise that the Justice Party is unable to match.
