:PROPERTIES:
:ID:       375785f8-0c57-49f5-9818-4bb1d6047de9
:ROAM_REFS: file:../references/Community%20Goals/Operation_Tyndareus_Reacts_to_Thargoid_Fleet.md
:END:
#+title: Community Goal: Operation Tyndareus Reacts to Thargoid Fleet
#+filetags: :CommunityGoal:3308:Alliance:Thargoid:

* Location

Kumiho Sky | Andecavi

* Objective

Hand in Combat bonds

* Progress

Tier 7/8

* Contributors

4,656

* Contributions

1,487,402,235,091/1,500,000,000,000 (99.16%)

* End

13 Oct 2022, 7:59am

* Status

Finished

[[id:1c4d53a2-d81f-4cfa-8001-eb77f2c79b5f][The Alliance]] has deployed a reactionary task force to defend the
Andecavi system from the Thargoids.

An anti-xeno taskforce, titled Operation Tyndareus, was recently
prepared by the [[id:17d9294e-7759-4cf4-9a67-5f12b5704f51][Alliance Defence Force]] in conjunction with [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation. This followed the ratification of the strategic defence
pact between the superpower and the megacorp.

Admiral [[id:2e8a3cd7-5f4e-47dc-ba7f-eb732bf8c7fa][Nikolas Glass]], the [[id:3dd2f3c7-3ddf-4900-aa28-580344edd509][Sirius Navy]] representative on the Council of
Admirals, announced:

"The Thargoids have encroached upon Allied territory, providing an
opportunity for Operation Tyndareus to put this newly legislated
partnership to the test. The megaships provided by [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Corp are on
combat readiness for just such an event, and Kumiho Sky has jumped
directly to the Andecavi system to act as a mobile base of operations.
The ADF will spearhead our counter-attack against the alien forces."

"These are still early days for our unified anti-xeno efforts, so we
are requesting additional support from independent pilots. [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation will award its pre-engineered heatsink module to those who
destroy adequate numbers of Thargoid vessels."

The Andecavi system reported the presence of Thargoids over the past
forty-eight hours. However, as with recent incursions into other
populated systems, no starports have yet been attacked. [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation will reimburse Thargoid combat bonds delivered to the Kumiho
Sky over the next seven days.

The campaign begins on the 6th October 3308 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.
