:PROPERTIES:
:ID:       2a2b4bc0-0b2d-4885-a582-b77d80e866d3
:ROAM_REFS: file:../references/Community%20Goals/Pleiades_Supply_Initiative.md
:END:
#+title: Community Goal: Pleiades Supply Initiative
#+filetags: :CommunityGoal:3304:Thargoid:

* Location

Donar's Oak | [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]]

* Objective

Deliver [[id:4cc7cde6-24f6-4bcc-b403-0f4cc90cde80][Grain]], [[id:a137e655-317f-4e24-8580-abed3b915119][Food Cartridges]], and [[id:9dbf5564-8fe2-46f3-930f-f3f1dbfecd26][Fruit and Vegetables]]

* Progress

Tier 2/8

* Contributors

1,323

* Contributions

1,799,946

* End

16 Aug 2018, 3:59pm

* Status

Finished

After sustained Thargoid attacks on civilian targets in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]]
Nebula, system authorities have launched a rescue operation to locate
and recover survivors.

The operation is being coordinated by Superintendent Marla Poulsen of
[[id:3808ab0e-fcff-4299-b882-f8c3946f272d][Aegis Research]], who made this announcement:

System authorities in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] have been channelling their resources
into combating the Thargoid menace. As a result, search-and-rescue
initiatives have been neglected, but we are determined to plug that gap.
That means a lot of civilians rescued from escape pods, which also means
a lot of hungry mouths to feed, so we'll need to bolster our current
food stocks as a precautionary measure.

Pilots are requested to recover occupied escape pods and damaged escape
pods. In addition, the following food resources are also required: fruit
and vegetables, grain, and food cartridges. Both recovered pods and food
stocks should be delivered to Donar's Oak in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] Sector Ir-W
D1-55 system.

The campaign begins on the 9th of August 3304 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before delivering [[id:4cc7cde6-24f6-4bcc-b403-0f4cc90cde80][Grain]], [[id:a137e655-317f-4e24-8580-abed3b915119][Food Cartridges]], and Fruit and Vegetable to
Donar's Oak in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]] Sector Ir-W D1-55 system.

Be aware that faction-state changes, [[id:8ddf8e00-4541-4857-a609-5f6c5849dded][Thargoid Sensor]]-related
interference and other disruptive events can negatively impact markets
and station services, and could prevent the initiative from running
smoothly.
