:PROPERTIES:
:ID:       a87b8ccf-932d-42ec-be08-b91e33f332e2
:END:
#+title: Lakon Spaceways Launches Type-11 Prospector
#+filetags: :3311:galnet:

* Lakon Spaceways Launches Type-11 Prospector

/29 Sep 3311/

[[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon Spaceways]] has announced the early release of the [[id:63529529-bb50-4c71-9fd8-cbc7ed723347][Type-11 Prospector]], a new mining vessel designed specifically for laser mining operations.

The [[id:63529529-bb50-4c71-9fd8-cbc7ed723347][Prospector]] builds on [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon]]’s reputation for industrial reliability and functionality. Featuring an exclusive Large Mining Hardpoint and the Mk II Mining Multi-Limpet Controller, the Type-11 can extract higher yields per asteroid than any previous mining vessel. Engineers confirm that its optimised loadout and expanded limpet capacity make it ideal for laser mining, setting a new standard.

A [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon]] senior design engineer commented:

“From the very first prototype, the [[id:63529529-bb50-4c71-9fd8-cbc7ed723347][Type-11 Prospector]] was designed to deliver results. The new mining tool debuting with the Type-11, with its enhanced targeting system, offers pin-point precision when excising fragment yields via laser mining.”

The [[id:63529529-bb50-4c71-9fd8-cbc7ed723347][Type-11 Prospector]] also includes a dedicated fighter bay, giving pilots an extra layer of defence in hazardous systems or pirate-infested rings.

To coincide with the launch, [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon]] announced sponsored mining trials with [[id:d17b2062-68b1-43ea-8852-ab04b591c6ba][Alioth Independents]] to validate the Prospector’s capabilities in the field.

The two parties have jointly issued a call for independent pilots to deliver a wide range of mined commodities. [[id:906c77b7-7fe4-48c1-ace5-1265023c2ebf][Lakon]] noted that the Prospector’s advanced extraction features make it particularly well-suited for the task but stressed that all ships equipped for both laser and core mining may participate in the initiative. The ship’s debut follows earlier advances in asteroid extraction equipment described in [[id:4c6f9dca-f596-4b29-8b1b-4d2a69cc2fc1][New Mining Tools Released]].

Initially an early-release purchase, the new ship is expected to rapidly become a staple of the galaxy’s booming mining industry and will transition to standard shipyard inventories at a later date.
