:PROPERTIES:
:ID:       f43f997e-e79f-41ef-8d82-e90f6830ba9e
:ROAM_REFS: file:../references/Community%20Goals/Macrosphere_Component_Requisition.md
:END:
#+title: Community Goal: Macrosphere Component Requisition
#+filetags: :CommunityGoal:3305:

* Location

Grandin Terminal | DS Leonis

* Objective

Deliver [[id:94b9dcf4-6a45-48d6-96b9-a343eeeb4ec1][Aluminium]], [[id:5d99c688-f21a-41e1-9ebb-00b626b4c31f][Auto-Fabricators]], [[id:e87b8a83-ecc1-4d17-917a-964e6196526b][Micro Controllers]]

* Progress

Tier 3/8

* Contributors

906

* Contributions

2,703,812

* End

07 Mar 2019, 3:57pm

* Status

Finished

Technology company [[id:ff8b148e-2112-447f-8256-e160e7ee24f3][Macrosphere]] is developing a specialised scanning
device to detect illicit interference with personal robots.

[[id:ff8b148e-2112-447f-8256-e160e7ee24f3][Macrosphere]] CEO [[id:a5eacd1c-edf2-48d7-bfd4-034ce25e9168][Taniyah Sharpe]] provided the details:

"The recent [[id:a5b054ac-dff0-434b-ade6-09d5f81228a1][Mars Tribune]] scandal proved that the illegal reprogramming
of robots is a genuine concern. Our Mech Scanner will allow robot owners
to discover if their trusted servants have been compromised."

"A components drive is being organised by our partners, DS Leonis
Industries. As well as shipments of micro controllers, auto fabricators
and aluminium, we also require newly mined jewels, to channel the
micro-lasers used by the Mech Scanner to detect interference. Deliveries
should be made to Grandin Terminal in the DS Leonis system."
