:PROPERTIES:
:ID:       9ce86b32-6e84-4b07-8e1e-fef3f90fe71f
:ROAM_REFS: file:../references/Community%20Goals/Fight_for_the_Neo_Marlinist_Order_of_Mudhrid.md
:END:
#+title: Community Goal: Fight for the Neo-Marlinist Order of Mudhrid
#+filetags: :CommunityGoal:3307:Empire:

* Location

Fairfax Vision | [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]]

* Objective

Hand in Combat bonds

* Progress

Tier 4/6

* Contributors

1,342

* Contributions

75,546,464,873/160,000,000,000 (47.22%)

* End

30 Nov 2021, 5:29pm

* Status

Finished

The Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]] Order of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] and the Epsilon Fornacis [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] Group
have declared war in the [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] system.

The [[id:5736dd4c-6645-4a96-b30b-7a56277decab][Steel]] Majesty megaship is serving as the base of the Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]]
forces. These include many surviving NMLA terrorist cells that gathered
to overtake the vessel from the [[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]] Colonies.

Also in the system is the [[id:04ae001b-eb07-4812-a42e-4bb72825609b][Far God]] cult megaship [[id:4701fafb-7040-4169-bfdb-9dc977a06e5f][Sacrosanct]], where the
NMLA's de facto leader [[id:7878ad2d-4118-4028-bfff-90a3976313bd][Theta Seven]] and the remnants of Theta Group have
been in hiding for months. Margrave Corentin Delacroix, ruler of the
Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]] Order of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]], broadcast a call to arms:

"All those who seek to topple the Duval dictators must fight alongside
us here and now. [[id:ec1cb30c-2e72-410b-a664-0d609a352100][Neo-Marlinism]] has no future unless its believers defend
it."

In an effort to draw support from independent pilots, the Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]]
Order of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] is offering a uniquely augmented unmodifiable Class 2
Rating B enzyme missile rack with increased caustic damage and capacity.
The module will be delivered to the top 25% of contributors providing
Tier 1 is reached.

The two factions have set out seven-day campaigns, which will end when
the top tier is reached by either faction or early on Thursday the 2nd
of December 3307.
