:PROPERTIES:
:ID:       ab97ccc2-bf08-43f5-8af6-69770170a595
:ROAM_REFS: file:../references/Community%20Goals/Protecting_Traders_in_Zlota.md
:END:
#+title: Community Goal: Protecting Traders in Zlota
#+filetags: :CommunityGoal:3304:Federation:

* Location

[[id:014990fb-678e-47fe-9898-8b27f633c001][Nusslein-Volhard]] Settlement | [[id:5849073c-4bb5-4d8e-8d9f-991a1a8dad06][Zlota]]

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 4/8

* Contributors

3,325

* Contributions

4,294,967,295

* End

13 Dec 2018, 3:58pm

* Status

Finished

An obscure cult based in the [[id:5849073c-4bb5-4d8e-8d9f-991a1a8dad06][Zlota]] system has requested a range of rare
items for an arcane ceremony.

A handwritten statement from [[id:05a4b221-ceba-499f-aa92-d379b8189c7a][Barnabas Cole]], leader of a group named the
[[id:4bc224d4-a885-4911-829e-2c8a70cc478d][Children of Tothos]], was submitted to the media:
This is the rite that will unmask us and allow us to see the path -- the
path we will all take, together, toward freedom.

[[id:5fa4a7bd-96ee-4321-91b6-4ef6b1b594fe][Zlota Federal Holdings]], which is thought to have some connection to the
cult, has requested various rare goods to be delivered to
[[id:014990fb-678e-47fe-9898-8b27f633c001][Nusslein-Volhard]] Settlement in the [[id:5849073c-4bb5-4d8e-8d9f-991a1a8dad06][Zlota]] system. It has also placed a
kill order on all ships on its wanted list, to protect those delivering
these rare commodities.

Notice: In the system Turberamoan is a Haz Res onsite the planet 5.
Distance ca. 1,7k ls. The Bounties of the (federal party) LTT 4696
League are counted by the CG.
