:PROPERTIES:
:ID:       62a0f77d-df9e-4bfb-b312-e2ebf54c4107
:ROAM_REFS: file:../references/Community%20Goals/Protecting_Traders_in_Kamadhenu.md
:END:
#+title: Community Goal: Protecting Traders in Kamadhenu
#+filetags: :CommunityGoal:3303:Federation:Empire:Alliance:Colonia:

* Location

Shajn Market | [[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]]

* Objective

Earn rewards by handing in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 7/8

* Contributors

12,486

* Contributions

0

* End

31 Aug 2017, 2:58pm

* Status

Finished

The [[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]] [[id:11216b9a-43a6-4242-9355-1c6227e48db8][Chapterhouse of Inquisition]] has announced plans to
establish a series of starports along the route to [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] to make the
20,000 light-year trek less daunting.

The organisation has issued an open order for various commodities for
the first of these starports, and has placed a kill order on all ships
on its wanted list so traders contributing material can do so safely. It
has promised to reward pilots who deliver bounty vouchers to Shajn
Market in the [[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]] system.

The campaign begins on the 24th of August and will run for one week. If
the final target is met earlier than planned, the campaign will end
immediately.

To be eligible for rewards you must sign up as an active participant
before handing in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] at Shajin Market in the [[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]]
system. Only bounty vouchers handed in after signing up will count
toward your personal contribution total.

Please note that if you have any crew members, a portion of your bounty
vouchers will be automatically assigned to them. These bounty vouchers
will not count towards your personal contribution total, and your crew
will receive the reward for their vouchers when they are handed in. The
proportion of bounty vouchers assigned to your crew will depend on their
rank.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)

-   Available RES in system:

•No RES available in [[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]]
•[[id:11216b9a-43a6-4242-9355-1c6227e48db8][Chapterhouse of Inquisition]] control the following local systems:
Nemgla, Sauraratec, Arapa, Lambayeque, Hisaaka, Zhongwe, Kurians, Baedi
Di

- Bounties that count towards the goal:
[[id:6762f716-7e24-4a03-af96-2af0fd55f8c7][Kamadhenu]] [[id:11216b9a-43a6-4242-9355-1c6227e48db8][Chapterhouse of Inquisition]], [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]]

- Bounties that don't count towards the goal:
All other local faction bounties, [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]], [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]

Top 10 CMDRs: 25,893,504Cr
Top 10%: 23,901,696 Cr
Top 25%: 17,926,272 Cr
Top 50%: 11,950,848 Cr
Top 75%: 5,975,424 Cr
Top 100%: 700,000 Cr
