:PROPERTIES:
:ID:       1a8db93a-e417-474d-bd2c-a2384006e8ed
:END:
#+title: Mining Rivalry Sparks Conflict in LP 855-34
#+filetags: :3311:Federation:galnet:

* Mining Rivalry Sparks Conflict in LP 855-34

/08 May 3311/

Tensions between [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] and [[id:b9fe58a3-dfb7-480c-afd6-92c3be841be7][Felicia Winters]] have erupted into open
conflict around the mining system of [[id:cf096cc3-59af-46ca-a0ea-a57c4c30c90e][LP 855-34]]. The system’s [[id:045f7139-ac68-453c-b97f-b61c8a9c370d][platinum]]
rush, triggered by local construction demands, has drawn forces from
both Powers. [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]]'s representative accused Federal factions of
"cornering the market" unfairly, urging loyal supporters to counteract
the Federation's aggressive tactics. Combat Zones have appeared
throughout the region as pilots clash over strategic mining sites.
Pilots supporting [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] are encouraged to report to [[id:4dfda537-e644-4848-b6ec-ad0a3f7cfceb][The Undeniable]]
station in [[id:cf096cc3-59af-46ca-a0ea-a57c4c30c90e][LP 855-34]] to assist in industrial mining operations and
help push back the Federal forces.
