:PROPERTIES:
:ID:       2a78ba36-a381-48a6-be67-b05e3d1d226a
:ROAM_REFS: file:../references/Community%20Goals/Supply_Salvation_s_Anti_Xeno_Superweapon_in_Delphi.md
:END:
#+title: Community Goal: Supply Salvation's Anti-Xeno Superweapon in Delphi
#+filetags: :CommunityGoal:3307:Thargoid:

* Location

[[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]] | [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]]

* Objective

Deliver [[id:794c8962-b58d-40d2-be55-c7d3c98e0f30][Classified Experimental Equipment]]

* Progress

Tier 1/1

* Contributors

1,820

* Contributions

500,045/500,000 (100.00%)

* End

11 Dec 2021, 8:55pm

* Status

Finished

Salvation requires vital materials to deploy an anti-xeno superweapon in
the [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]] system.

A message was transmitted from the [[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]] megaship by its new
commanding officer, Commodore [[id:bcaa9222-b056-41cf-9361-68dd8d3424fb][Morag Halloran]]:

"The Thargoids have invaded three key systems, as Salvation
anticipated. Preparations have been made to halt their advance in [[id:0ee60994-364c-41b9-98ca-993d041cea72][Maia]],
[[id:70fa34ea-bc98-40ff-97f0-e4f4538387a6][Merope]] and [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]], but there is an urgent requirement to collect
classified experimental equipment from the [[id:f10f7c83-9d29-470c-a640-1a3e5334b686][Heart of Taurus]] in the
Qaratos system."

"Pilots must then deliver these shipments to the megaship [[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]] in
the [[id:846bfbc7-75e7-4d8d-8716-7fe0346026f4][Delphi]] system in preparation of the superweapon's activation."

"It is crucial that all deliveries are made by early on Tuesday the
14th of December. Without these components, Salvation's superweapon
will be not be able to affect enough Thargoid vessels to turn the
tide."

As a reward for this support, the top 75% of contributors will receive a
pre-engineered Class 1 burst fire Gauss Cannon with increased reserve
ammo and reduced falloff range. These will be placed in storage at the
[[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]] by the 18th of December 3307.

The initiative begins on the 9th of December 3307 and will run until the
14th of December.
