:PROPERTIES:
:ID:       66badb14-ff82-4ce8-94cd-35f83a07229b
:ROAM_REFS: file:../references/Community%20Goals/Colonia_Project_Requests_Microresources.md
:END:
#+title: Community Goal: Colonia Project Requests Microresources
#+filetags: :CommunityGoal:3304:Colonia:

* Location

Foster Terminal | Coeus

* Objective

Deliver Rhenium, Germanium and Molybdenum

* Progress

Tier 6/8

* Contributors

310

* Contributions

335,018

* End

24 May 2018, 3:56pm

* Status

Finished

Scientists in Colonia are investigating the region's potential to
support larger populations in the future.

Professor Alexei de la Vega, who is leading the research, published this
statement:
Over the past few years the region's population has expanded
ferociously, so it has become a priority to investigate how Colonia
might support even greater numbers, and what kind of infrastructure
would be required.

This research requires a range of specialised materials, for which
we're prepared to pay handsomely. With these, we can evaluate
Colonia's true potential.

The campaign is being run by Colonia Co-Operative, one of Colonia's
partner organisations, which has asked pilots to deliver micro-resources
to Foster Terminal in the Coeus system.
