:PROPERTIES:
:ID:       fa292aae-b823-444b-9ef2-c2417c86a2a2
:ROAM_REFS: file:../references/Community%20Goals/Protect_the_refugees.md
:END:
#+title: Community Goal: Protect the refugees
#+filetags: :CommunityGoal:3301:Empire:

* Location

Dhawan Port | Amitrite

* Objective

Earn rewards by handing in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] at Dhawan Port

* Progress

Tier 5/5

* Contributors

2,541

* Contributions

0

* End

02 Oct 2015, 3:01pm

* Status

Finished

Pirates operating in the Amitrite system have begun targeting transports
carrying refugees from the war-torn Pegasi sector. The refugee
transports have been stopping in Amitrite to refuel en route to a
resettlement centre in the Munshin system, leaving them vulnerable to
attack.

The [[id:e9becd28-9644-42aa-afc8-7bba3ce10076][Imperial Navy]] and the Defence Force of Amitrite have placed bounties
on these pirates in an effort to eliminate the danger to the refugees.
Independent pilots with combat experience are encouraged to travel to
the Amitrite system and make the spaceways safe again.
