:PROPERTIES:
:ID:       969cc57b-15e4-45fd-bf03-b8c5e9d9ae64
:ROAM_REFS: file:../references/Community%20Goals/Feeding_the_Galactic_Summit.md
:END:
#+title: Community Goal: Feeding the Galactic Summit
#+filetags: :CommunityGoal:3307:Empire:Alliance:

* Location

Spirit of Laelaps | Sirius

* Objective

Deliver Animal Meat, Coffee, Fish, Fruit and Vegetables, and Wine

* Progress

Tier 4/8

* Contributors

11,072

* Contributions

106,285,435/192,000,000 (55.36%)

* End

11 Mar 2021, 6:59am

* Status

Finished

The Empire is aiding Sirius Corporation by offering bounty hunting and
trade opportunities to support the Galactic Summit.

The diplomatic conference is now entering its second week, with
superpower and independent leaders gathered at Patterson Enterprise in
the Sirius system.

Sirius Corporation's CEO Li Yong-Rui announced:

"For the coming week, we are working with the Empire to maintain the
security operation by offering bounties on all wanted ships. The Empire
will also pay generously for extra supplies of animal meat, coffee,
fish, fruit and vegetables, and wine that are delivered to the Spirit of
Laelaps."

If Tier 1 is reached, the top 75% of participants will receive a
permanent Sirius system permit and the Cobra Mk III Acceleration White
paint job. The top 25% will additionally receive the Cobra Mk III
Acceleration Gold paint job. These should be processed and accessible by
the 13th of March 3307.

Thanks to the generosity of the Empire, the top 10 participants will
receive an Imperial Clipper. The ship will be delivered and stored at
Ashby City starport in the Luyten's Star system by the 13th of March
3307.

The joint initiative will run for one week, after which Sirius
Corporation will partner with the Alliance to provide for the needs and
security of the conference.

If the final target is met earlier than planned, this phase will end
immediately.
