:PROPERTIES:
:ID:       3216d3fa-2bfe-4ad1-9f3b-0259d752371f
:ROAM_REFS: file:../references/Community%20Goals/Onionhead_Research_Campaign__Support_the_project_to_legalise_the_narcotic_.md
:END:
#+title: Community Goal: Onionhead Research Campaign: Support the project to legalise the narcotic.
#+filetags: :CommunityGoal:3302:Federation:

* Location

Tereshkova Dock | [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]]

* Objective

Deliver pure [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]]

* Progress

Tier 3/8

* Contributors

1,661

* Contributions

0

* End

07 Apr 2016, 3:00pm

* Status

Finished

An organisation known as the [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]] Purple Mob has launched a campaign
to prove that the drug is harmless, with the ultimate aim of having it
reclassified as a non-toxic plant. Like the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]], the organisation
has issued an appeal for quantities of the drug, but unlike the
[[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]], the [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]] Purple Mob intends to study the plant rather than
destroy it. A spokesperson for the organisation said:

"Legalising [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] would decriminalise its users, provide the Federal
government with a new revenue stream, and destabilise the criminal
network through which the drug is currently bought and sold. It's a
no-brainer."

No matter which side of the [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] debate you're on, fly safe out
there, Commanders! o7

Global Progress: 50,068 Tonnes Collected

-----
NOTE: You will get \~20.000 Cr profit per run
NOTE: Only available on [[id:1615a78c-73ab-4e84-a21a-3843b927551a][Harvestport]] in [[id:b634e896-9d3d-4f44-9783-cfb8fd6d0c56][Kappa Fornacis]]
NOTE: Only 8T of [[id:b160f4b1-1751-41c2-b0bd-e7c6e8dc2f2d][Onionhead]] are available per cargo run
NOTE: [[id:b634e896-9d3d-4f44-9783-cfb8fd6d0c56][Kappa Fornacis]] is 76.52 LY from [[id:144149ef-21cd-4e52-afea-dcf379d12d18][Altair]] (3 jumps with Diamond
Explorer)
NOTE: Tereshkova Dock is Outpost too
-----
AA Top 5 = 4,000 000 Cr
A Top 10% = 2,000 000 Cr
B Top 25% = 1,000 000 Cr
C Top 50% = 600 000 Cr
D Top 75% = 400 000 Cr
E Top 99% = 300 000 Cr
