:PROPERTIES:
:ID:       85187f98-519a-4d8b-81a6-9eb8033cfabc
:ROAM_REFS: file:../references/Community%20Goals/Supply_Federation_Capital_Ship_production.md
:END:
#+title: Community Goal: Supply Federation Capital Ship production
#+filetags: :CommunityGoal:3306:Federation:

* Location

Schweickart City | Parutis

* Objective

Deliver [[id:0f1939e4-1ab1-4f9c-8b73-ebc572081433][Building Fabricators]], [[id:8c12828c-5756-4b81-b742-6d52bb3c77f5][Microbial Furnaces]] and Energy Grid
Assembly

* Progress

Tier 5/5

* Contributors

7,391

* Contributions

40,000,633/40,000,000 (100.00%)

* End

02 Dec 2020, 11:39pm

* Status

Finished

The [[id:3d268496-1d95-49bc-aca6-49d16a4337c8][Federal Navy]] has requested commodities for the construction of new
capital ships in Parutis.

President [[id:02322be1-fc02-4d8b-acf6-9a9681e3fb15][Zachary Hudson]] has convinced Congress to increase funding for
the [[id:3d268496-1d95-49bc-aca6-49d16a4337c8][Federal Navy]], and to advance the construction programme for
[[id:3146c49e-4aa8-4061-9ab2-1d9da2b0bff5][Farragut]]-class Battle Cruisers. In a powerful address, he said:

"Defending the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] is our highest priority in these uncertain
times. It is vital that we reinforce our capability to protect the
people from all threats."

The [[id:3d268496-1d95-49bc-aca6-49d16a4337c8][Federal Navy]] urgently requires additional resources to meet the new
shipbuilding timetable. Deliveries of [[id:0f1939e4-1ab1-4f9c-8b73-ebc572081433][Building Fabricators]], Microbial
Furnaces and Energy Grid Assemblies are requested by Labour Of Parutis
at Schweickart City in the Parutis system.

Should the initiative be successful, each tier will provide enough
commodities to complete a new capital ship. Alongside this, Schweickart
City will be improving stock and providing a two-week discount on a
range of modules starting on the 4th of December.

Tier 1 is 5% off Laser weapons
Tier 2 increase to 10% and adds Defensive modules such as ECMs
Tier 3 increase to 15% and adds Shields, Armour and Hull reinforcement
Tier 4 increase to 20% and adds Projectile weapons
Tier 5 increase to 30% and adds Missiles and other explosives

If successful, decals will be rewarded to the top 75% of participants by
the 5th of December 3306.
