:PROPERTIES:
:ID:       f0d697db-0138-4de2-8c8a-90ce3106c5a4
:ROAM_REFS: file:../references/Community%20Goals/Ram_Tah_s_Study_of_Salvation_s_Anti_Xeno_Superweapon.md
:END:
#+title: Community Goal: Ram Tah's Study of Salvation's Anti-Xeno Superweapon
#+filetags: :CommunityGoal:3307:Thargoid:

* Location

Felice Dock | [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]]

* Objective

Deliver [[id:794c8962-b58d-40d2-be55-c7d3c98e0f30][Classified Experimental Equipment]]

* Progress

Tier 1/2

* Contributors

1,516

* Contributions

950,775

* End

16 Dec 2021, 6:58am

* Status

Finished

Tesreau has expressed her continued faith in Aegis, recognising the
organisation is not perfect while maintaining that its efforts are
well-intentioned. With the help of chosen pilots and [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]]'s
expertise, she hopes to prove that Salvation cannot be allowed to
continue his reckless experiments.

As a reward for this support, the top 75% of contributors will receive
four turret mounted Class 3 AX Missile Racks. These will be placed in
storage at Felice Dock by the 18th of December 3307.

The first tier target will be enough to successfully analyse the
superweapon. Surplus deliveries will be stocked for future tests, with
deliveries still counting towards a pilot's final contribution total.

The initivative begins on the 9th of December 3307 and will run until
the 16th of December. It is expected that the classified experimental
equipment will be unavailable for collection from the morning of the
14th of December.
