:PROPERTIES:
:ID:       40530f95-11ec-476f-bd86-8918719c50e5
:ROAM_REFS: file:../references/Community%20Goals/Colonia_Migration_Appeal___April_3303__Rares__very_long_distance__.md
:END:
#+title: Community Goal: Colonia Migration Appeal - April 3303 (Rares, very long distance!)
#+filetags: :CommunityGoal:3303:Colonia:

* Location

[[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]] | [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]

* Objective

Deliver Galactic Travel Guides from [[id:64e5b644-cc28-4586-a4a4-32dc226447bd][Bluford Orbital]] in [[id:951f5c68-2395-4eb9-af43-b26172d0fe64][LHS 3447]]

* Progress

Tier 0/1

* Contributors

0

* Contributions

0

* End

10 Apr 2017, 3:24am

* Status

Finished

The [[id:6b6559fd-c7fa-44c9-b540-b94ddcadbd50][Colonia Council]] has launched its fifth migration appeal, giving the
galaxy's minor factions an opportunity to establish a permanent
presence in the [[id:1d45a325-abf9-44b6-90d9-d91beebbdec1][Colonia Nebula]].

This month, the Council has targeted the following systems for
colonisation:

•EOL PROU QC-K C9-65
•EOL PROU VY-R D4-49
•EOL PROU TD-S D4-60
•EOL PROU RS-T D3-46
•EOL PROU IW-W e1-3046
•EOL PROU PX-T d3-122
•EOL PROU LW-L c8-48
•EOL PROU LW-L c8-322
•EOL PROU PC-K c9-107
•EOL PROU MW-L c8-16

To compete for a migration visa, pilots must sign up with [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]
Migration Services before delivering quantities of Galactic Travel
Guides to [[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]] in the [[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system.

At the end of the appeal, the ten factions that have made the largest
contribution will earn the right to settle in one of the specified
systems. A new planetary outpost will be constructed in the system for
the organisation's sole use.

Be aware that organisations settling in the [[id:1d45a325-abf9-44b6-90d9-d91beebbdec1][Colonia Nebula]] will be
considered independent entities, separate from their parent faction.

The campaign begins on the 6th of April 3303 and will run for four
weeks. If the final target is met earlier than planned, the campaign
will end immediately.

To participate in the appeal you must sign up as an active participant
before delivering Galactic Travel Guides to [[id:935880a2-d4fb-4d27-ad48-0f95112ee0fe][Jaques Station]] in the
[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]] system.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)

-   For more information see:

[https://forums.frontier.co.uk/showthread.php/311509-[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]-Expansion-Initiative-Sign-up\\\\](https://forums.frontier.co.uk/showthread.php/311509-[[id:ba6c6359-137b-4f86-ad93-f8ae56b0ad34][Colonia]]-Expansion-Initiative-Sign-up\\)

-   To sign up please use the following link:

[https://www.elitedangerous.com/en/colonia-expansion-initiative/\\\\](https://www.elitedangerous.com/en/colonia-expansion-initiative/\\)

-   Galactic Travels Guides can be found at [[id:64e5b644-cc28-4586-a4a4-32dc226447bd][Bluford Orbital]] in the LH
