:PROPERTIES:
:ID:       1942c20e-d498-4295-afdf-0ba38f24b38c
:ROAM_REFS: file:../references/Community%20Goals/Protect_Empire_Capital_Ship_Production.md
:END:
#+title: Community Goal: Protect Empire Capital Ship Production
#+filetags: :CommunityGoal:3306:Empire:

* Location

Miyasaka Orbital | Mandh

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] for [[id:845d8ae3-0796-40a0-bd5c-d6d552243edb][Artemis]] Corporation​

* Progress

Tier 5/5

* Contributors

3,698

* Contributions

40,009,137,091/40,000,000,000 (100.00%)

* End

01 Dec 2020, 9:24pm

* Status

Finished

The [[id:e9becd28-9644-42aa-afc8-7bba3ce10076][Imperial Navy]] has requested commodities for the construction of new
capital ships in Mandh.

The [[id:6b539fa1-7ebe-44d3-874b-41a3bd400af9][Imperial Senate]] has approved funding for the construction of a new
wave of Majestic-class Interdictors. Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] announced:

"We face adversaries on all sides and from within, eager to corrupt and
destroy our proud [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]]. This is a time to bolster our strength and our
resolve."

A request has been made for shipments of [[id:0f1939e4-1ab1-4f9c-8b73-ebc572081433][Building Fabricators]], Microbial
Furnaces and Energy Grid Assemblies to Miyasaka Orbital in the Mandh
system.

[[id:845d8ae3-0796-40a0-bd5c-d6d552243edb][Artemis]] Corporation has requested the support of independent pilots to
counter any piracy or other acts that may interfere with the supply of
commodities for the capital ships, and will handsomely reward such
efforts.

If successful, decals will be rewarded to the top 75% of participants by
the 5th of December 3306.
