:PROPERTIES:
:ID:       d2f215c6-fb1f-4c68-a2fd-56180da530de
:END:
#+title: Who Is Lexi October?
#+filetags: :3312:galnet:

* Who Is Lexi October?

/03 Mar 3312/

[[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]] business analyst [[id:d4e49144-20cb-468e-b3ce-f594c2b5bf13][Marlon Royce]] has published a feature piece on [[id:1133e15f-59dd-42b3-aaa9-12a0bf3a3287][October Consortium]] CEO [[id:63f2962b-371f-4475-bbd1-0314201d15c0][Lexi October]]:

“Few figures in the Core Systems command as much quiet influence as Lexi October in recent months.”

“Known for identifying promising technologies before rivals recognise their value, October has built a portfolio spanning advanced engineering, pharmaceuticals and personal tech. Exobiological research is the next challenge.”

“Her hands-on approach came to light in 3305, when the Consortium rescued struggling tech firm [[id:3e9f43fb-038f-46a6-be53-3c9af1bad474][Supratech]]. The investment stabilised the company after poor sales of its [[id:831b1d7f-2742-414a-9cbf-3fca5afb3ce0][Torc]] computing system and enabled further development of products such as the [[id:b33acaa9-26f0-4e25-bad8-d202e113fb75][Artemis exploration suit]].”

“October’s reputation for discretion was reinforced in 3307 when she hosted an exclusive gathering for the secretive [[id:d6578a29-4aa4-47d9-b3b2-22d0bc6c2234][Joker's Deck]], attended by political and corporate elites including [[id:e26683e6-6b19-4671-8676-f333bd5e8ff7][Zachary Rackham]] and [[id:b62c9e2e-8079-44bc-a30d-d192076162e6][Scorpio DeVorrow]]. The event made headlines after master thief [[id:b9519a7c-f00b-4a57-9bcf-964258bdd2d8][Winking Cat]] stole a priceless artefact.”

“October declined to discuss the incident in detail, stating ‘Security failures are lessons. The important thing is how quickly you adapt.’”

“More recently, however, corporate scrutiny has focused on the Consortium’s long-standing permit control over the [[id:64e3ad83-30b5-41fc-bde5-8eb63c38ab83][HIP 87621]] system, where the rare organism [[id:2025d30d-570c-4b01-bde9-116e0f1e4080][Radicoida unica]] may hold the key to a new range of market-leading pharmaceuticals.”

“October confirmed her position on the recent [[id:cf1770d3-2354-433b-83a6-dc384ea84bfd][October Accords]] and a coalition partnership with several Powers. ‘The agreement will ensure Radicoida research is accelerated and shared fairly, with October Consortium retaining oversight. I’m looking forward to seeing the results of this cooperation.’”

“When pressed as to how October managed to negotiate the Accords with several Powers at once, she simply smiled at me, stating ‘When you put decades of research on the table it’s a big incentive. That, and reminding everyone who manufactures the [[id:b33acaa9-26f0-4e25-bad8-d202e113fb75][Artemis suits]].’”

“It'll be interesting to see what the future holds for October.”
