:PROPERTIES:
:ID:       2e60d68c-124a-4a4b-a893-2c6c66c8d4d2
:ROAM_REFS: file:../references/Community%20Goals/Upheaval_in_Sutekh___Imperial_Pilots__Salvage_.md
:END:
#+title: Community Goal: Upheaval in Sutekh - Imperial Pilots (Salvage)
#+filetags: :CommunityGoal:3303:Federation:Empire:

* Location

Archimedes Gateway | Sutekh

* Objective

Deliver salvaged Data Cores

* Progress

Tier 0/8

* Contributors

1,427

* Contributions

0

* End

23 Feb 2017, 3:04pm

* Status

Finished

The Adad Exchange has launched an operation to recover valuable military
intelligence from the wreckage of a Federal convoy in the Sutekh system.
The organisation has appealed to the galactic community for support,
promising to reward pilots who support its operation.

The campaign begins on the 16th of February 3303 and will run for one
week. If the operation achieves its aims earlier than planned, it will
end immediately.

To be eligible for rewards you must sign up as an active participant
before delivering salvaged Data Cores to Archimedes Gateway in the
Sutekh system.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)

-   Competing goal with Federal Bounty Hunting operation
