:PROPERTIES:
:ID:       a17c687f-9254-4042-a55e-1934567cd0ef
:ROAM_REFS: file:../references/Community%20Goals/The_Battle_for_Ho_Hsi___Empire__Combat_.md
:END:
#+title: Community Goal: The Battle for Ho Hsi - Empire (Combat)
#+filetags: :CommunityGoal:3303:Empire:

* Location

Hand Ring | Ho Hsi

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for Freedom Party of Ho Hsi in
Conflict Zones

* Progress

Tier 6/8

* Contributors

4,772

* Contributions

4,294,967,295

* End

21 Sep 2017, 11:22am

* Status

Finished

Recent reports indicate that conflict has erupted in the Ho Hsi system
between the Freedom Party of Ho Hsi and the Ho Hsi Jet Comms Limited.
System security forces were caught off guard by the violence, which
began without warning and has escalated rapidly since then.

Freedom Party of Ho Hsi has issued a call for aid appealing to
independent combat pilots for support. Commanders who participate in the
conflict will be generously rewarded.

A representative of system security forces issued the following
statement:
It would be irresponsible of us to encourage independent pilots to join
this fight, but if the galactic community can bring this conflict to a
swift end, they will have our gratitude.
The Freedom of Ho Hsi has set out a week-long operation to take control
of the system which will begin on the 14th of September 3303.

To be eligible for rewards you must sign up as an active participant
before handing in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Hand Ring in the Ho Hsi system.

Please note that if you have any crew members, a portion of your combat
bonds will be automatically assigned to them. These combat bonds will
not count towards your personal contribution total, and your crew will
receive the reward for their bonds when they are handed in. The
proportion of combat bonds assigned to your crew will depend on their
rank.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.

[Notes:\\\\](Notes:\\)

-   Station services: Commodities Market, Shipyard, Outfitting, Restock,

Repair, Refuel
- [[id:4ed9ac75-9ddc-4533-bc21-00a775fbc0ee][Powerplay]]: [[id:b4892958-b513-46dc-b74e-26887b53f678][Yuri Grom]] [[id:980d793d-2073-4e0b-8eb9-65c8dbd33202][Control]] system
- Available CZs in system:
HO HSI 1 low, high
HO HSI 4 high
HO HSI 6 low, high
HO HSI 7 low, low, high
HO HSI 9 low

Will be added as reported in the thread
