:PROPERTIES:
:ID:       a9662ed5-b71d-43cb-9bbf-3bbb6e0d88fe
:ROAM_REFS: file:../references/Community%20Goals/Support_the_Scriveners_Dredger_Update_Initiative.md
:END:
#+title: Community Goal: Support the Scriveners Dredger Update Initiative
#+filetags: :CommunityGoal:3307:Alliance:

* Location

Oramus Terminal | HIP 43670

* Objective

Deliver [[id:a081e7d6-7384-47d3-87d4-0c2324c9f3d0][Emergency Power Cells]], [[id:d686168a-7903-49dc-8dd6-1c2d690bfa9c][Power Converter]] and [[id:eea9a598-34c9-48d9-b4a5-d3dbd06e56e2][Power Transfer Bus]]

* Progress

Tier 0/5

* Contributors

1,891

* Contributions

14,090,680/32,000,000 (44.03%)

* End

25 Nov 2021, 7:00am

* Status

Finished

The HIP 43670 system is hosting two competing delivery initiatives, each
of which aims to benefit the Scriveners Clan.

Supporters of the Scriveners Clan are being asked to gather emergency
power cells, power converters and power transfer buses and deliver them
to the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] of HIP 42371 at Oramus Terminal. A spokesperson told the
media:

"These supplies are needed to perform vital repairs to the dredger.
Furthermore, if the power systems are sufficiently updated, they can
bypass the ancient components affected by [[id:b0f0e40a-14e9-422d-aa9d-5ff6296f3421][Orion University]]'s override
codes and continue travelling independently."

Although there remains no response from the Scriveners Clan, the dredger
is now actively monitoring all local and interstellar transmissions.
This is a new development for the isolated community, and suggests they
are aware of these campaigns.

The first campaign to reach its maximum tier will successfully make its
case. If neither campaign reaches the maximum tier, then the one with
the highest proportional tier completion will be considered victorious.

The dual initiatives begin on the 18th of November 3307 and will run for
one week. Should the campaign to support the Scriveners Clan reach the
maximum tier it will end immediately.
