:PROPERTIES:
:ID:       d3a44996-89d8-4c4d-99b0-87b997efb5e6
:ROAM_REFS: file:../references/Community%20Goals/Azimuth_Biotech_Seeks_to_Expand_Operational_Assets.md
:END:
#+title: Community Goal: Azimuth Biotech Seeks to Expand Operational Assets
#+filetags: :CommunityGoal:3308:Thargoid:

* Location

[[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]] | Wandrama

* Objective

Deliver [[id:3de49bff-8041-45b0-a713-d3646334efd9][Cobalt]], [[id:34acf2f1-676d-4e52-86f4-80dc606e435c][Power Generators]], [[id:0b64653e-4cad-4f00-bf49-d88ae6049a11][Ceramic Composites]] and Energy Grid
Assembly

* Progress

Tier 3/5

* Contributors

5,071

* Contributions

43,766,712/65,000,000 (67.33%)

* End

10 Nov 2022, 9:01am

* Status

Finished

Azimuth Biotech has announced a campaign in the Wandrama system to
expand its military and surface facility capacity.

The controversial weapons developer has seen a recent downturn in
fortunes, due to fierce opposition by independent pilots protesting
Azimuth's history of illicit research. The failure of Salvation to
bring an end to the war has also soured public sentiment towards the
corporation.

Azimuth Biotech CEO [[id:78d58f4a-e080-4548-a2f0-9506b7b73674][Torben Rademaker]] announced the initiative:

"After a period of reflection, it is time for Azimuth to once again
step forward and assume a position of support for the brave pilots
engaging Thargoid forces wherever they are encountered. To do this, we
shall establish a new megaship equipped to operation in Thargoid-tainted
systems. The tragic loss of the [[id:f55dd9f1-52aa-4ca9-93c4-27175612c59a][Bright Sentinel]] and [[id:f10f7c83-9d29-470c-a640-1a3e5334b686][Heart of Taurus]] in
[[id:55088d83-4221-44fa-a9d5-6ebb0866c722][HIP 22460]] must not hinder our ambition any further."

"We also intend to operate several surface outposts to aid our research
projects. We aim to contribute to humanity's military options once
again, being careful not to repeat the mistakes of our former
figurehead."

Pilots contributing to Azimuth's campaign, hosted at the [[id:2730e920-30ee-435e-943b-d4124f257751][Musashi]]
megaship in Wandrama, will be granted the [[id:a5427e6e-e2f5-4c09-b595-97bbc14894ee][Mbooni]] permit and access to
the company's range of anti-xeno weaponry. Rademaker has promised that
a successful campaign will allow for the [[id:4e26dabc-d7bd-4e6b-9619-7afb122f4ce8][Glorious Prospect]] to offer the
[[id:a5427e6e-e2f5-4c09-b595-97bbc14894ee][Mbooni]] permit from the T-Tauri system permanently.

The top 75% of contributors to the delivery campaign will receive the
[[id:a5427e6e-e2f5-4c09-b595-97bbc14894ee][Mbooni]] permit.

The campaign begins on the 3rd November and will run for one week. If
the final target is met earlier than planned, the campaign will end
immediately.
