:PROPERTIES:
:ID:       6c8b6661-21f5-4c18-b89f-27d499ecfa38
:ROAM_REFS: file:../references/Community%20Goals/Combat_Operation_in_HIP_17692.md
:END:
#+title: Community Goal: Combat Operation in HIP 17692
#+filetags: :CommunityGoal:3304:Federation:Empire:Thargoid:

* Location

Blackmount Orbital | [[id:93410322-85eb-4d58-ae0e-c99b5faf3e02][HIP 17692]]

* Objective

Earn rewards by handing in Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] in Blackmount
Orbital in the [[id:93410322-85eb-4d58-ae0e-c99b5faf3e02][HIP 17692]] system.

* Progress

Tier 8/8

* Contributors

530

* Contributions

4,294,967,295

* End

13 Jan 2018, 8:16am

* Status

Finished

In a move that has come as a surprise to many, the [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] and [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]
have announced a joint initiative to counter Thargoid activity in the
HIP 17692 system.

The two-pronged operation will seek to reduce the Thargoid presence in
the region, and to recover personal effects, data and people from
Thargoid attack sites in [[id:93410322-85eb-4d58-ae0e-c99b5faf3e02][HIP 17692]].

The [[id:e8740636-76cb-40ad-816e-ec17e1323aa0][Merope Expeditionary Fleet]] has been authorised to oversee the combat
operation, promising to reward pilots who hand in Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]
[[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Blackmount Orbital in the [[id:93410322-85eb-4d58-ae0e-c99b5faf3e02][HIP 17692]] system.

The campaign begins on the 11th of January 3304 and will run for one
week. If the final target is met earlier than planned, the campaign will
end immediately.

To earn rewards you must sign up as an active participant before handing
in Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Blackmount Orbital in the [[id:93410322-85eb-4d58-ae0e-c99b5faf3e02][HIP 17692]]
system.

Please note that if you have any crew members, a portion of your combat
bonds will be automatically assigned to them. These combat bonds will
not count towards your personal contribution total, and your crew will
receive the reward for their bonds when they are handed in. The
proportion of combat bonds assigned to your crew will depend on their
rank.

Be aware that faction-state changes, UA bombing and other disruptive
events can negatively impact markets and station services, and could
prevent the initiative from running smoothly.
