:PROPERTIES:
:ID:       8aa53d5b-972f-4c4e-b6e6-47926015dc69
:ROAM_REFS: file:../references/Community%20Goals/Defending_the_Sim_Archive.md
:END:
#+title: Community Goal: Defending the Sim-Archive
#+filetags: :CommunityGoal:3304:Thargoid:

* Location

Bobko City | Narri

* Objective

Deliver Beryllium, Semiconductors, and Reinforced Mounting Plates

* Progress

Tier 6/8

* Contributors

4,415

* Contributions

13,895,627

* End

10 May 2018, 3:59pm

* Status

Finished

The Utopia commune has launched a project to build a military
installation in its home system to defend the Sim-Archive from potential
Thargoid attack.

Dr Leigh Constantinides, a spokesperson for Utopia, made this
announcement:
Following recent observations by the respected strategist Marquis
Novantico, we accept that the Sim-Archive requires increased protection
to prevent its knowledge from falling into the wrong hands. Our partner
organisation, the Narri Justice Party, is therefore overseeing the
construction of a new security installation. We beseech the galactic
community to support this worthy endeavour.

Independent pilots are requested to deliver the requested construction
materials to Bobko City in the Narri system in support of this
initiative.
