:PROPERTIES:
:ID:       a8255515-d5bb-4580-9c2c-17fbd32a51b4
:ROAM_REFS: file:../references/Community%20Goals/Supporting_Recovery_Effort_in_Meene.md
:END:
#+title: Community Goal: Supporting Recovery Effort in Meene
#+filetags: :CommunityGoal:3304:

* Location

Felice Dock | [[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]]

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 3/8

* Contributors

2,573

* Contributions

4,294,967,295

* End

15 Nov 2018, 3:59pm

* Status

Finished

Following a skirmish with a group of mercenaries, security forces in the
[[id:9c59e7e7-1737-43a9-ac67-e818f6d1677d][Meene]] system have launched an operation to capture enemy agents in order
to investigate the attack.

Security Chief [[id:0bd61b69-66c6-4be7-abfc-0395734bdc72][Harper Vargas]] of the [[id:f36afa96-d3df-40d8-bf67-13cbe388e889][Meene Defence Force]] gave the
following statement:
The mercenaries were targeting [[id:4551539e-a6b2-4c45-8923-40fb603202b7][Ram Tah]]'s [[id:1129599f-efa9-4186-969e-eb09ae9d3c2d][Phoenix Base]], but it's clear
they were just hired hands. We need to recover as many surviving
mercenaries as we can and interrogate them, so we can find the real
culprits.

The [[id:706c70bc-7bb0-4b7a-ad90-04112bffaf73][Independent HIP 29241 Green Party]], which is overseeing the
initiative, has placed a kill order on all ships on its wanted list, to
ensure that those contributing to the recovery can do so safely.
