:PROPERTIES:
:ID:       92120722-c810-4ddc-845e-5e813b72dd3a
:ROAM_REFS: file:../references/Community%20Goals/Hammer_of_Justice_.md
:END:
#+title: Community Goal: Hammer of Justice:
#+filetags: :CommunityGoal:3302:Federation:

* Location

Greeboski's Outpost | Phiagre

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] at Greeboski's Outpost

* Progress

Tier 8/8

* Contributors

3,189

* Contributions

0

* End

28 Apr 2016, 3:00pm

* Status

Finished

Chancellor Arias also called on the Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] to support
[[id:82f6fe30-acb7-4e40-a7d5-3f1338d4f520][Sovereign]] Justice Collective forces by protecting traders delivering
titanium to Greeboski's Outpost. Pilots who hand in bounty vouchers or
deliver titanium to the starport will be generously rewarded.

By inviting pilots from all over the galaxy we will no doubt bring
together many honourable commanders in this endeavour, but make no
mistake that with good comes evil and we must prepare for the criminal
opportunists who will most assuredly show up. There are hunters and
there are victims. By your discipline, cunning, obedience and alertness,
you will decide if you are a hunter or a victim." Chancellor Zahra
Arias

AA Top 10 CMDRs: 65,000,000 Cr + global awards
A Top 15%: 40,000,000 Cr + global awards
B Top 30%: 25,000,000 Cr + global awards
C Top 60%: 15,187,500 Cr + global awards
D Top 90%: 5,593,750 Cr + global awards
E Top 99%: 1,000,000 Cr + global awards

HI/HAZ RES @ PHIAGRE 4 aprox 1000ls from Greeboski
