:PROPERTIES:
:ID:       bdea06fc-e2e0-4f61-82fb-68488fe2189c
:ROAM_REFS: file:../references/Community%20Goals/Deliver_goods_to_support_Sirius_Corporation_Campaign_to_Establish_Marlinist_Colonies.md
:END:
#+title: Community Goal: Deliver goods to support Sirius Corporation Campaign to Establish Marlinist Colonies
#+filetags: :CommunityGoal:3306:Federation:Empire:

* Location

Ellis Gateway | BD+05 1146

* Objective

Deliver [[id:fa234a22-ca2a-413c-bfd4-28f9bb0d3cd1][Atmospheric Processors]], [[id:5d99c688-f21a-41e1-9ebb-00b626b4c31f][Auto-Fabricators]], [[id:febbcc7c-743b-4332-bc15-9e36ecd0442f][Structural Regulators]]
and [[id:2f1be518-d6d9-4e2e-84ce-ea7e5d86e099][Water Purifiers]]

* Progress

Tier 4/5

* Contributors

7,467

* Contributions

39,585,427/40,000,000 (98.96%)

* End

17 Dec 2020, 7:00am

* Status

Finished

Commodities are requested to create new settlements for [[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]]
refugees who fled from the [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] to the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]].

[[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]] has offered to resolve the current standoff between
superpowers by establishing colonies where the refugees can live
independently.

[[id:f0655b3a-aca9-488f-bdb3-c481a42db384][Li Yong-Rui]], CEO of [[id:aae70cda-c437-4ffa-ac0a-39703b6aa15a][Sirius Corporation]], summarised his proposal:

"It is clear that the Marlinists cannot return to the [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]], and are a
destabilising presence within the [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]]. We offer an alternative by
constructing permanent habitats for their population. These will be
self-governed and may freely trade with the galactic community."

"[[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] cannot stand by while the risk of interstellar war increases. I
sincerely hope this leads to a more stable and profitable period for us
all."

Traders are asked to deliver [[id:fa234a22-ca2a-413c-bfd4-28f9bb0d3cd1][Atmospheric Processors]], [[id:5d99c688-f21a-41e1-9ebb-00b626b4c31f][Auto-Fabricators]],
[[id:febbcc7c-743b-4332-bc15-9e36ecd0442f][Structural Regulators]] and [[id:2f1be518-d6d9-4e2e-84ce-ea7e5d86e099][Water Purifiers]] to Ellis Gateway in the Bd+05
1146 system. From there, the Omega Merchant Command will distribute
resources for the colonisation of up to ten uninhabited systems which
will be ready in early 3307.

Each completed tier will provide the resources to populate two systems,
listed in order of priority:

HIP 22550 and Hyades Sector RO-P b6-6.
LP 659-31 and Hyades Sector LX-T c3-30.
Hyades Sector SU-C a14-1 and Hyades Sector RO-P b6-2.
Hyades Sector VP-N b7-4 and Hyades Sector AB-M b8-2.
Hyades Sector YA-M b8-1 and Hyades Sector TJ-P b6-6.

The initiative begins on the 10th of December 3306 and will run for one
week. If the final target is met earlier than planned, the campaign will
end immediately.
