:PROPERTIES:
:ID:       af3e2676-dfc5-4a45-8888-9b2b0710f28c
:ROAM_REFS: file:../references/Community%20Goals/Appeal_for_Guardian_Artefacts.md
:END:
#+title: Community Goal: Appeal for Guardian Artefacts
#+filetags: :CommunityGoal:3308:Thargoid:Guardian:

* Location

Musashi | HIP 39768

* Objective

Deliver Guardian Relic, Guardian Orb, Guardian Casket, Guardian Tablet,
Guardian Urn, Guardian Totem and Ancient Key

* Progress

Tier 3/5

* Contributors

1,927

* Contributions

298,164

* End

07 Apr 2022, 6:00am

* Status

Finished

Commodore Morag Halloran has offered you an opportunity to support
Salvation's next phase of his work, which seeks to bring eventual
victory over the Thargoids.

Taurus Mining Ventures requires you to transport as many Guardian
artefacts as possible to the Musashi megaship in the HIP 39768 system.
Salvation is offering an extremely generous payout for artefacts sold to
the Musashi.

This opportunity is open until the 7th of April 3308. The Musashi must
depart on this date, as the Thargoids may take notice of its cargo if it
remains in the system much longer. It is vital that you complete your
deliveries by then, as the same increased rate for Guardian artefacts
cannot be offered afterwards without drawing unwanted attention.

In addition to financial rewards, the top 75% of contributors will also
receive a unique Anti-Xeno decal.

The initiative begins on the 31st of March 3308. Commodore Halloran has
asked for your aid and discretion in this assignment.
