:PROPERTIES:
:ID:       f9956ec5-5355-4437-b61e-20aa106917f8
:ROAM_REFS: file:../references/Community%20Goals/A_Safe_Haven___Eravate.md
:END:
#+title: Community Goal: A Safe Haven - Eravate
#+filetags: :CommunityGoal:3303:Federation:

* Location

Cleve Hub | [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]]

* Objective

Bounty

* Progress

Tier 5/8

* Contributors

6,410

* Contributions

0

* End

06 Jul 2017, 2:11pm

* Status

Finished

A spokesperson for the Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] has announced a new
peacekeeping initiative centred on the [[id:951f5c68-2395-4eb9-af43-b26172d0fe64][LHS 3447]], [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]] and Asellus
Primus systems. The purpose of the initiative is to minimise criminal
activity in these regions and thereby ensure the safety of inexperienced
pilots.

The spokesperson elaborated on the nature of the campaign:

"Many of the galaxy's independent pilots start their careers in these
systems, and we believe they should be able operate without fear of
being targeted by opportunistic aggressors."

"Of course, pilots will not be the only beneficiaries of this initiative
-- the people of [[id:951f5c68-2395-4eb9-af43-b26172d0fe64][LHS 3447]], [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]] and [[id:b21e7cf9-145c-4546-8305-8dc866024f3c][Asellus Primus]] will also benefit
from the increase in security."

Authorities in the pertinent systems have responded positively to the
proposal, with Governor Mandelbaum, administrator of Cleve Hub,
describing it as "a boon to our people". They have also expressed hope
that the success of the initiative will allow peacekeeping forces to
maintain order once the campaign is over.

The Pilots [[id:847b877e-8a00-4e9c-baa3-22f2a071c74b][Federation]] has called on the galaxy's independent combat
pilots for support, and has authorised Adle's Armada, [[id:951f5c68-2395-4eb9-af43-b26172d0fe64][LHS 3447]] Dynamic
and Co, and [[id:b21e7cf9-145c-4546-8305-8dc866024f3c][Asellus Primus]] Gold Legal Ind. to reward those who support
the initiative.

The campaign begins on the 29th of July 3303 and will run for one week.
If the final target is met earlier than planned, the campaign will end
immediately.

-----

Objective: Deliver bounty vouchers to [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]] - Cleve Hub or Ackerman
station

How: [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]] Planet #10 - Resource Zone - High Intensity, low
performance ship are advised to form wings with other cmdrs
Next CNB: NGALIBA - only medium sized stations there, only a part of
earned vouchers from there accepted at [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]].

Caution: [[id:758e843d-ea7e-48f2-b480-d62faa129900][Eravate]] is a melting pot where newbies meet outlaws without
much protection. You are advised to watch your back and take security
precautions, especially when using sub combat class ships.
5.4 giga Cr,

Top 10 Commanders - 14,200,000 C
