:PROPERTIES:
:ID:       69d8b917-6df0-42e8-8e06-b238d68b61b4
:ROAM_REFS: file:../references/Community%20Goals/Protect_the_Kumo_Crew_s_Initiative_to_Produce_a_new_Commodity.md
:END:
#+title: Community Goal: Protect the Kumo Crew's Initiative to Produce a new Commodity
#+filetags: :CommunityGoal:3307:

* Location

[[id:82a0f345-bc03-4564-897c-b00bcda5b74e][Kumo City]] | [[id:93f55330-0ae5-42d5-bee2-368453bcd9e1][Pegasi Sector PN-T c3-14]]

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]​

* Progress

Tier 1/5

* Contributors

1,817

* Contributions

44,460,459,095/240,000,000,000 (18.53%)

* End

15 Jul 2021, 6:59am

* Status

Finished

The [[id:1dfc7c53-642a-4404-a8e8-16a8cc18482a][Kumo Crew]] syndicate is requesting deliveries to mass-produce a
recreational drug.

The drug is believed to originate with the [[id:327af983-8859-4d4d-9906-78d535ad621a][Blue Viper Club]], a nomadic
clan travelling aboard an ancient dredger that recently appeared near
[[id:82a0f345-bc03-4564-897c-b00bcda5b74e][Kumo City]] station.

Arch-Corsair [[id:a002575a-7b72-4d9b-8c76-e748073a8e3e][Kay Volantyne]], representing the [[id:2dc1b92f-4bdc-4504-ad5f-a9c5794155dc][Kumo Council]], provided
details to local newsfeed The [[id:dc25c5b7-381e-4e8a-8599-68be61b19bae][Pegasi Sentinel]]:

"Helix will change lives across the galaxy! Derived from high-quality
organic crops, and with many medicinal and psychological benefits, it is
guaranteed to bring contentment."

She later called on all freedom-loving pilots to help protect this
initiative, and that they will be handsomely rewarded for their
efforts.

Many authorities have registered concern that this will exacerbate drug
addiction and misuse, which are common social problems. However, some
markets have shown interest in the potential new product.

[[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]] has reported rumours that it may be a previously unknown
strain of onionhead, a highly popular psychedelic. It remains unknown
whether the [[id:327af983-8859-4d4d-9906-78d535ad621a][Blue Viper Club]] cultivated it aboard their dredger or
acquired it from another source.

Experts predict that if enough commodities are provided, the product
will come to market around the 22nd of July 3307.

To support this initiative, hand in your bounties to the [[id:2dc1b92f-4bdc-4504-ad5f-a9c5794155dc][Kumo Council]] at
[[id:82a0f345-bc03-4564-897c-b00bcda5b74e][Kumo City]] in the Pegasi Sector PN-T C3-14 system.

The initiative begins on the 8th of July 3307 and will run for one week.
If the final target is met, the campaign will end immediately.
