:PROPERTIES:
:ID:       8a44f784-c1cb-4186-a94f-105ab46635a5
:ROAM_REFS: file:../references/Community%20Goals/Salvage_and_Rescue_Operation.md
:END:
#+title: Community Goal: Salvage and Rescue Operation
#+filetags: :CommunityGoal:3304:

* Location

Bacon City | Carnoeck

* Objective

Deliver Occupied Escape Pods, Black Boxes and Wreckage Components

* Progress

Tier 7/8

* Contributors

4,334

* Contributions

1,329,042

* End

24 May 2018, 3:59pm

* Status

Finished

A convoy travelling through the core systems has come under attack from
a pirate group, and local authorities are requesting assistance in
finding survivors.

The operation is being coordinated by Security Chief Tal Woźniak of
United Carnoeck for Equality, who made this announcement:
The convoy came under intense fire from pirates, with many ships damaged
or destroyed. We immediately despatched search-and-rescue teams, but the
volume of debris is significant, and we are therefore requesting help
from any independent pilots in the area.

Our priority is to locate survivors, but we're also keen to acquire
data that might help to bring those responsible to justice.

Pilots are requested to recover Occupied Escape Pods, Black Boxes and
Wreckage Components, and deliver them to Bacon City in the Carnoeck
system.
