:PROPERTIES:
:ID:       ccfc4954-2840-4470-b052-69690408acae
:ROAM_REFS: file:../references/Community%20Goals/Cultivating_The_Corn.md
:END:
#+title: Community Goal: Cultivating The Corn
#+filetags: :CommunityGoal:3301:

* Location

-----
  [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]]
-----

* Objective

Sell Machinery to Birmingham

* Progress

Tier 8

* Contributors

5,188

* Contributions

0

* End

11 May 2015, 6:00am

* Status

Finished

The newest rejuvenation project to hit the OLD World has been announced,
and this time it's the Green Party of [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] who have stepped up to the
challenge of making its home a pleasant (and profitable) place to live.

As most traders are well aware, [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] is famous for its [[id:9ae2b7bc-f042-4a24-b042-2bcbef21e557][Diso Ma Corn]]. A
hearty, healthy, tasty plant, that covers itself in a light dust which
when snorted produces an intense but brief feeling of contentment and
wellbeing. Currently, [[id:9ae2b7bc-f042-4a24-b042-2bcbef21e557][Diso Ma Corn]] can only be (cost-effectively) grown
on the planet of Birmingham. This is due to a unique collection of
nutrients found in the planet's soil, combined with the near-constant
bombardment of the planet by solar waves being ejected from [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]]
itself.

Now the Green Party of [[id:4aedfccd-a366-4b25-a5e2-538bb29a35cb][Diso]] is hoping to capitalise on its unique cash
crop by increasing the output of Birmingham's Ma Corn plantations. To
do that, the Green Party has placed orders to the tune of 15 million
tonnes worth of Machinery, in particular the Green Party are interest in
purchasing a large quantity of [[id:fa234a22-ca2a-413c-bfd4-28f9bb0d3cd1][Atmospheric Processors]], [[id:4397a456-5661-4e9e-9bcf-c1444e421414][Crop Harvesters]],
[[id:34acf2f1-676d-4e52-86f4-80dc606e435c][Power Generators]] and [[id:2f1be518-d6d9-4e2e-84ce-ea7e5d86e099][Water Purifiers]].
