:PROPERTIES:
:ID:       4572f869-0e59-4428-93f2-d0f370686baa
:ROAM_REFS: file:../references/Community%20Goals/Imperial_Investigation__Operation_Mictlan.md
:END:
#+title: Community Goal: Imperial Investigation: Operation Mictlan
#+filetags: :CommunityGoal:3301:Empire:

* Location

Kowal Dock | Mictlan

* Objective

Hand in Imperial Bounty Vouchers to Kowal Dock

* Progress

Tier 4

* Contributors

1,144

* Contributions

0

* End

16 Apr 2015, 7:00am

* Status

Finished

Information relayed to Princess Arissa indicates that criminals
operating in and around this sector may be able to provide information
as to who hired the Emperor's would-be-assassin.

As such, all combat capable pilots of Mictlan are requested to join the
Princess in her crusade against the insidious rot that hides within the
belly of our great nation.

It is believed that the forceful ejection of the criminal elements will
result in furthering the investigation into the attack on the Emperor,
while also helping to improve the lives of those unfortunate enough to
be living in the shadow of organised crime.

In order to achieve her goals before the most likely culprits have a
chance to flee from justice, Princess Arissa is offering a series of
sizable rewards to all honourable Imperial pilots that help re-establish
proper Imperial order in Mictlan.
