:PROPERTIES:
:ID:       c2707cc1-ffd2-40e2-8276-31d182fb252f
:ROAM_REFS: file:../references/Community%20Goals/Protecting_Traders_in_Adenets.md
:END:
#+title: Community Goal: Protecting Traders in Adenets
#+filetags: :CommunityGoal:3304:Alliance:

* Location

Henslow Market | [[id:7ee5896b-1917-4d20-9536-1989e804148a][Adenets]]

* Objective

Earn rewards by handing in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]] at Henslow Market in the
[[id:7ee5896b-1917-4d20-9536-1989e804148a][Adenets]] system.

* Progress

Tier 7/8

* Contributors

4,126

* Contributions

4,294,967,295

* End

06 Dec 2018, 3:59pm

* Status

Finished

The [[id:04ba4637-336a-46c7-bab0-3ac12f16b2f9][Achilles Corporation]] has announced plans to replace all robots
destroyed as a result of the recent spy robot scandal.

Chairman [[id:11262a8f-5a7b-4107-b7da-cae3878f8b3b][Gus Weaver]] of the [[id:6ace5ab9-af2a-4ad7-bb52-6059c0d3ab4a][Sol]] division of Achilles Corp said:

"We take customer support seriously. That's why we're offering to
replace -- free of charge -- any robots destroyed or damaged by owners
who suspected them of behaving inappropriately."

"To achieve this, we've asked the [[id:7ee5896b-1917-4d20-9536-1989e804148a][Adenets]] Pro-[[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] Bond to
organise deliveries of robotics, computer components and
microcontrollers to Henslow Market in the [[id:7ee5896b-1917-4d20-9536-1989e804148a][Adenets]] system. These will be
used to produce brand new [[id:0b7fcbab-6e37-401a-8d52-4d2dee8e5c1e][PA912]] administration robots and other
models."

The initiative begins on the 29th of November 3304 and will run for one
week. If the final target is met earlier than planned, the campaign will
end immediately.
