:PROPERTIES:
:ID:       6884ff12-aab1-4eac-8364-21d551d19359
:ROAM_REFS: file:../references/Community%20Goals/The_great_and_powerful_Osmium.md
:END:
#+title: Community Goal: The great and powerful Osmium
#+filetags: :CommunityGoal:3302:Alliance:

* Location

Fraser Orbital | LHS 2936

* Objective

Mine and sell [[id:89bb247d-d459-4ebf-a000-698cd1d9c5fe][Osmium]] to Fraser Orbital.

* Progress

Tier 2/5

* Contributors

1,115

* Contributions

0

* End

11 Feb 2016, 3:05pm

* Status

Finished

The LHS 2936 [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] Combine, a manufacturing concern based in the LHS
2936 system, has issued a galaxy wide request for [[id:89bb247d-d459-4ebf-a000-698cd1d9c5fe][Osmium]]. According to a
company spokesman, the rare metal will be used to create specialist
alloys with which to improve the organisation's manufacturing
facilities. The organisation has promised to reward contributors with
discounts at the Fraser Orbital shipyard in addition to liberal
financial reimbursements. .

Edit: You can mine [[id:89bb247d-d459-4ebf-a000-698cd1d9c5fe][Osmium]] in the nearby Parjanya system. The gas giant
BC3 (45.000 ls) contains a metallic ring.

Top 10 cmdrs: 3M
Top 10%: 2.4M
Top 20%: 2M
Top 40%: 1.5M
Top 60%: 1M
Top 80%: 500K
Top 100%: 200K
