:PROPERTIES:
:ID:       f2fefb1d-188b-4a4f-b57d-d446a8edd69e
:END:
#+title: Caspian Explorer Trials Deemed a Resounding Success
#+filetags: :3311:galnet:

* Caspian Explorer Trials Deemed a Resounding Success

/16 Dec 3311/

[[id:d24ee8f5-e2ec-4c71-b5fa-afc2d9710141][Zorgon Peterson]] has confirmed the successful conclusion of its [[id:68dd801e-ab32-4883-95ff-3ce42d5e2e6d][Caspian Explorer]] field trials, with pilots securing vast quantities of exobiological data.

A [[id:d24ee8f5-e2ec-4c71-b5fa-afc2d9710141][Zorgon Peterson]] press statement described the results as “exceptional across every metric relevant to long-range exploration.” Engineers supervising the campaign reported that the [[id:68dd801e-ab32-4883-95ff-3ce42d5e2e6d][Caspian]]’s performance exceeded even internal projections.

Chief Marketing Officer [[id:78aac322-5926-44aa-9678-c792c3f2ca68][Devin Kaneda]] commented:

“These trials have demonstrated that the [[id:68dd801e-ab32-4883-95ff-3ce42d5e2e6d][Caspian Explorer]] lives up to every ambition behind its design. Pilots pushed the vessel hard, covering vast distances using the vessel’s neutron and white dwarf boosting capabilities to their fullest, and landing quickly and safely on distant worlds thanks to its unique design.”

“The Caspian not only endured: it excelled. I’m excited to see what new horizons can be found by these brave explorers.”

Kaneda also congratulated [[id:283173c9-b037-4741-92d3-889dae2c9d23][CMDR BitNick]] for providing the largest number of contributions over the two-week campaign.

With the trials now concluded, [[id:d24ee8f5-e2ec-4c71-b5fa-afc2d9710141][Zorgon]] predicts that the [[id:68dd801e-ab32-4883-95ff-3ce42d5e2e6d][Caspian]] will quickly become a key feature of humanity’s next generation of long-range expeditions.

The [[id:68dd801e-ab32-4883-95ff-3ce42d5e2e6d][Caspian Explorer]] is available for exclusive purchase initially and will transition to standard shipyard inventories at a later date.
