:PROPERTIES:
:ID:       16bef3b9-0111-44d9-89e6-205df37c18fd
:ROAM_REFS: file:../references/Community%20Goals/Security_for_Year_s_End_Festivities.md
:END:
#+title: Community Goal: Security for Year's End Festivities
#+filetags: :CommunityGoal:3305:Alliance:Thargoid:

* Location

[[id:aeb2ca41-e6ea-499c-a58e-7bc4427df58b][Davies High]] | [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]]

* Objective

Hand in [[id:5402969f-345d-420c-9025-3a0a89929d11][Bounty Vouchers]]

* Progress

Tier 6/8

* Contributors

7,480

* Contributions

4,294,967,295

* End

18 Dec 2019, 3:59pm

* Status

Finished

The [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] system has been selected for the [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]]'s end-of-year
festivities, prompting huge demand for commodities.​
​
Traders, performance artists and chefs throughout Allied space have
already flocked to the system, where billions of attendees are expected.
The planet Home is planning a synchronous firework display spanning
every continent, while the habitation decks of [[id:aeb2ca41-e6ea-499c-a58e-7bc4427df58b][Davies High]] will offer a
culinary celebration featuring dishes from across the galaxy.​
​
Prime Minister Edward Mahon was the guest of honour at the commencement
ceremony, and he offered these words to the gathered press:​

"As the year draws to a close we have a lot to be thankful for. There
is peace between the superpowers. Thargoid encroachments on human space
have ceased. Through hard work and cooperation, we have proven ourselves
capable of rising together in response to significant challenges. This
is something each and every one of us can be proud of.

And so, the [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] system will host a celebration to tell future
generations about. We call upon the galactic community to ensure the
system is well supplied, and look forward to rewarding these
ever-reliable pilots for their continued service."

The [[id:83d61aae-150c-4a38-81aa-0443046505c3][Reorte Mining Coalition]] has elected to oversee the initiative. To
ensure the celebration goes without a hitch, they have offered to pay
handsomely for all bounties collected on wanted ships in the system.​
​
Hint: [[id:5292d8c1-fa6e-4352-a03f-ef984f706203][Reorte]] offers only mediocre resource zones for bounty hunting.
Flechti system is \~19 ly away and provides two hazardous resource zones
near planet A4 with bounties valid for the CG.
