:PROPERTIES:
:ID:       fead00df-2da0-4ab3-9e1d-caff78d0ac14
:ROAM_REFS: file:../references/Community%20Goals/Fight_for_the_Epsilon_Fornacis_Empire_Group_against_the_Neo_Marlinists.md
:END:
#+title: Community Goal: Fight for the Epsilon Fornacis Empire Group against the Neo-Marlinists
#+filetags: :CommunityGoal:3307:Empire:

* Location

Payne-Scott City | [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]]

* Objective

Hand in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] after fighting for Epsilon Fornacis [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] Group in
Conflict Zones​

* Progress

Tier 2/5

* Contributors

12,954

* Contributions

171,993,452,388/300,000,000,000 (57.33%)

* End

08 Apr 2021, 7:00am

* Status

Finished

Conflict has erupted between the Epsilon Fornacis [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] Group and the
Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]] Order of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]].

An investigation by ACT in the [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] system confirmed that the Order
of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] provided logistical support for the NMLA's starport attacks.
Their agents infiltrated other local factions to transport enzyme bombs
to their targets.

The faction has now renamed itself the Neo-[[id:46536da8-abd4-461f-9bf9-b749d4fc25e1][Marlinist]] Order of [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]].
Landgrave Arastin Delacroix, its leader, has declared a revolution
against the [[id:85e6fd5f-69a0-4f7c-95d0-ddb89ef150e9][Imperial Family]]. From his flagship, the [[id:5736dd4c-6645-4a96-b30b-7a56277decab][Steel]] Majesty, he
announced:

"The corrupt Duvals will never give up their power, so we must take it
from them. All those who seek to change the established order -- join
us!"

The Epsilon Fornacis [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] Group responded by engaging their forces in
battle. Senator [[id:75daea85-5e9f-4f6f-a102-1a5edea0283c][Denton Patreus]] has ordered them to "take revenge for
the '[[id:0713b7e5-a805-4b4d-91c0-104735484fbc][Nine Martyrs]]' atrocities." He added that pilots who support
their just cause by handing in [[id:bbbc7bc6-79d7-46b7-925e-c1f882c8f25a][Combat Bonds]] at Payne-Scott City in the
[[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]] system will be well rewarded.

If Tier 1 is reached, the top 10% of participants will receive a fully
engineered class 2 rating B long range and high capacity railgun with
feedback cascade.
Should the Epsilon Fornacis [[id:541dcfb3-93ef-40e5-9284-bf5a4f999043][Empire]] Group be victorious the top 75% of
participants will receive the module.
The module will be placed in storage at Payne-Scott City in the [[id:bb9435b7-f21d-4afc-8ca6-a57d0fd51065][Mudhrid]]
system by Friday the 9th of April 3307.

The two factions have set out seven-day campaigns, which will end early
on Thursday the 8th of April 3307. If the final target is met earlier
than planned, the initiatives will end immediately.
