:PROPERTIES:
:ID:       5c126d77-6ee4-4fa9-b5e3-e21bbf23faa9
:ROAM_REFS: file:../references/Community%20Goals/Debilitating_disease_devastating_BD_11_4280.md
:END:
#+title: Community Goal: Debilitating disease devastating BD-11 4280
#+filetags: :CommunityGoal:3301:

* Location

Mitchell City | BD-11 4280

* Objective

Sell Medicines to Mitchell City

* Progress

Tier 0/1

* Contributors

0

* Contributions

0

* End

06 Aug 2015, 3:05pm

* Status

Finished

A terrifying disease is currently working its way through BD-11 4280. So
far the illness has defied attempts to contain it, despite the best
efforts of medical staff aboard Mitchell City.

Many people have already been placed in quarantine, with many more
thought to have already been infected. Doctors are concerned that the
pathogen responsible may have already begun to spread to other systems.
To assist medical staff aboard Mitchell City, the Aliance of BD-11 4280
are offering a series of incentives to any pilots that provide medicines
to Mitchell City market until such time as the crisis has been averted.
