:PROPERTIES:
:ID:       cee04a47-32de-4a2f-9f5e-01f4fc877054
:END:
#+title: Core Dynamics Unveils Kestrel Fighter
#+filetags: :3312:galnet:

* Core Dynamics Unveils Kestrel Fighter

/24 Feb 3312/

[[id:4a28463f-cbed-493b-9466-70cbc6e19662][Core Dynamics]] has announced the limited release of the [[id:e8a1cc47-c48a-4269-8ee1-726757a9547e][Kestrel]], a new small combat ship engineered exclusively for high-intensity engagements.

Designed as a pure combat fighter, the Kestrel prioritises speed, agility and striking power over versatility. Its compact frame, Size 5 thrusters and high-speed manoeuvrability make it particularly effective in close-quarters combat, interception duties and rapid strike operations. Engineers have also confirmed the ship will be fitted with supercharged [[id:46a9c980-af48-4e43-a820-9971d7c76c34][Frame Shift Drives]], a first for such a small craft.

A Core Dynamics senior test pilot stated:

“The Kestrel was built with a singular purpose: to win fights. Its handling characteristics and acceleration allow experienced pilots to outmanoeuvre much larger vessels, while the three Mk II large combat hardpoints, which can be fitted with the new [[id:f9d68265-463c-48dc-8b88-9ed1dd4989c7][Mk II Plasma Shock Accelerator]], ensures it delivers decisive force when it counts.”

Early reports indicate that, in capable hands, the Kestrel can challenge medium and even large multi-role ships, with elite combat pilots pushing the design to its operational limits.

To test the new Kestrel’s combat capabilities, Core Dynamics has called for interested independent pilots to sign up at [[id:77d1e47c-b2b7-4475-b075-7e2cbf079f07][Polyakov Station]] in the [[id:b16e9508-ccde-4a48-86ff-f3674c9c720e][Duamta]] system before accepting any Combat mission types from any Mission Board within a 15ly radius.

The Kestrel is available now as an early-release purchase and will later transition to wider shipyard availability.
