:PROPERTIES:
:ID:       2e3b21c6-7de6-40c0-bb1b-8907b1db3b9d
:ROAM_REFS: file:../references/Community%20Goals/Privateer_s_Alliance_Campaign.md
:END:
#+title: Community Goal: Privateer's Alliance Campaign
#+filetags: :CommunityGoal:3304:Alliance:Thargoid:

* Location

Barjavel Station | HIP 33368

* Objective

Deliver Industrial Materials and Machinery

* Progress

Tier 6/8

* Contributors

3,189

* Contributions

16,316,432

* End

12 Apr 2018, 3:59pm

* Status

Finished

The Privateer's [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] has announced plans to build a military
installation in the HIP 33368 system.

The installation will "reinforce the gates" by defending the core
systems from Thargoid forces in the [[id:cd15e78b-89d1-4051-bd92-05d0ab49ec17][Pleiades]].

A spokesperson for the Privateer's [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] released the following
statement:
We need to make a show of strength. That is why we are humbly requesting
the help of the galactic community in building this installation.

Once complete, it will allow pilots from across the galaxy --
irrespective of their allegiance -- to work together in resisting the
Thargoid threat.
In support of this goal, the Privateer's [[id:2506edb2-fef4-4723-85c6-02482635229d][Alliance]] has placed an open
order for various commodities, and has pledged to reward pilots who
deliver these commodities to Barjavel Station in the HIP 33368 system.
