:PROPERTIES:
:ID:       215b5b9e-6623-4a31-bf98-5b00d599c007
:ROAM_REFS: file:../references/Community%20Goals/The_Grand_Sirius_Interstellar_Expedition.md
:END:
#+title: Community Goal: The Grand Sirius Interstellar Expedition
#+filetags: :CommunityGoal:3301:

* Location

Goldstein Port | Lembava

* Objective

Sell Exploration Data to Goldstein Port

* Progress

Tier 6/10

* Contributors

5,367

* Contributions

0

* End

02 Jul 2015, 4:59pm

* Status

Finished

Ever since mankind's first tentative steps to the stars, the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation has prided itself on standing shoulder to shoulder with
those men and woman whose bravery and sacrifice led humanity safely
through the unknowns depths of space.

In the last thousand years, a multitude of human civilizations have
spread themselves across our galaxy, and yet.... there is still so much
more for us to explore. Countless pristine worlds and countless more
fixer-uppers, just waiting to be discovered by those brave enough to
take that step into the unknown.

To help inspire a new generation of galactic explorers, the [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]]
Corporation is pleased to announce the Grand [[id:83f24d98-a30b-4917-8352-a2d0b4f8ee65][Sirius]] Interstellar
Expedition. This is a month-long initiative to survey the uncharted
depths of the galaxy to find new habitable systems in which humanity can
flourish and grow.
