:PROPERTIES:
:ID:       87c0aca0-4bdf-4a82-9816-b309ca0097b5
:END:
#+title: Criminal Factions Remains Silent After Lhou Mans Attacks
#+filetags: :3312:galnet:

* Criminal Factions Remains Silent After Lhou Mans Attacks

/11 May 3312/

Questions remain unanswered following last week’s unprovoked attacks on [[id:83cc5ab9-e42c-4049-b6ed-081927b0b286][starport]] facilities across [[id:ffc1cf53-212c-4075-b171-239c88a9b2b0][Lhou Mans]].

Security analysts stated that the attacks bore remarkable similarities to last month’s coordinated attacks across military installations in the core systems.

“These patterns are usually reserved for military trials and reconnaissance operations,” a senior security observer told [[id:4ab0f53c-0b85-43a3-83ca-b9e88c0db30e][Vox Galactica]].

“Simulated attacks are used to probe response times, defensive weak points and the speed with which system security can coordinate with independent pilots.”

Similar data malware packages bearing the hallmarks of twin axe motifs have also been witnessed across [[id:ffc1cf53-212c-4075-b171-239c88a9b2b0][Lhou Mans]] networks.

Crime correspondent [[id:39c4c90a-eb6a-4306-b1a4-b95ff114a428][Mira Bukowski]] has revealed evidence from underworld sources allegedly linking the motif to a rogue pirate admiral going by the nom de guerre ‘[[id:7b08dbc0-8c7b-4ecc-8c93-676d0d67abe4][Lady Zi]]’ and a coalition fleet directed by a single criminal syndicate.

“Very few are willing to share more details on who [[id:7b08dbc0-8c7b-4ecc-8c93-676d0d67abe4][Lady Zi]] is. We don’t know if this is because they are unaware, or if they’re simply scared,” she added.

With evacuation efforts still under way, the attackers’ true motives remain unclear for now. Yet investigators warn that [[id:ffc1cf53-212c-4075-b171-239c88a9b2b0][Lhou Mans]] may have been selected for reasons beyond simple disruption.
