name: Generate static org-roam-ui page
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate org-roam-ui page
        uses: thargosu/publish-org-roam-ui@main
        with:
          org-roam-directory: src
          org-roam-db-filename: org-roam.db
          site-title: Elite Dangerous Lore Explorer
          deploy-to-pages: true
